#!/usr/bin/env python3
"""
generate_pages.py — BestDateWeather unified page generator
============================================================
Generates all destination pages (annual + monthly) for FR or EN.

Usage:
  python3 generate_pages.py --lang fr              # all FR pages
  python3 generate_pages.py --lang en              # all EN pages
  python3 generate_pages.py --lang fr paris        # one destination FR
  python3 generate_pages.py --lang en --dry-run    # EN simulation
  python3 generate_pages.py --lang fr --validate-only

Replaces generate_all.py and generate_all_en.py.
"""

import csv, re, os, sys, json, glob, hashlib

# ── Editorial content (generated by generate_editorial.py) ───────────────────
_EDITORIAL_FILE = 'data/editorial.json'
_EDITORIAL = {}
if os.path.exists(_EDITORIAL_FILE):
    with open(_EDITORIAL_FILE, encoding='utf-8') as _f:
        _EDITORIAL = json.load(_f)
from datetime import date
from urllib.parse import quote_plus
from lib.common import (score_badge as _score_badge, best_months as _best_months,
                        budget_tier as _budget_tier, seasonal_stats as _seasonal_stats,
                        bar_chart, climate_table_html as _climate_table_html,
                        weather_emoji, build_lang, fmt_temp, fmt_precip, fill_tpl, c_to_f)
from lib.page_config import (build_config, dest_name, dest_name_full, dest_slug,
                              dest_country, annual_url, monthly_url,
                              annual_url_cross, monthly_url_cross, hero_sub as _hero_sub,
                              pillar_url, month_lc, MONTH_URL, MONTH_URL_FR,
                              SEASON_ICONS, TODAY, YEAR, DATA_UPDATED,
                              date_modified_for, build_hreflang_tags)

# ── PATHS ───────────────────────────────────────────────────────────────────
DIR  = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(DIR, 'data')

# IDs partenaires — source de vérité dans config.py
from config import BOOKING_AID, GYG_PARTNER_ID, TP_MARKER

MONTHLY_GRAD = [
    'linear-gradient(160deg,#0d1a3a 0%,#1a2a6a 55%,#2a4a9a 100%)',
    'linear-gradient(160deg,#0d1a3a 0%,#1a2a6a 55%,#2a4a9a 100%)',
    'linear-gradient(160deg,#0a2a1a 0%,#1a4a2a 55%,#3a8a5a 100%)',
    'linear-gradient(160deg,#0a2a1a 0%,#1a4a2a 55%,#3a8a5a 100%)',
    'linear-gradient(160deg,#0a2a1a 0%,#1a4a2a 55%,#3a8a5a 100%)',
    'linear-gradient(160deg,#2a1a0a 0%,#6a3a1a 55%,#d97706 100%)',
    'linear-gradient(160deg,#2a1a0a 0%,#6a3a1a 55%,#d97706 100%)',
    'linear-gradient(160deg,#2a1a0a 0%,#6a3a1a 55%,#d97706 100%)',
    'linear-gradient(160deg,#1a1a0a 0%,#4a3a0a 55%,#8a6a2a 100%)',
    'linear-gradient(160deg,#1a1a0a 0%,#4a3a0a 55%,#8a6a2a 100%)',
    'linear-gradient(160deg,#1a1a0a 0%,#4a3a0a 55%,#8a6a2a 100%)',
    'linear-gradient(160deg,#0d1a3a 0%,#1a2a6a 55%,#2a4a9a 100%)',
]


def _stable_hash(s, n):
    """Deterministic variant selector — md5, unaffected by PYTHONHASHSEED."""
    return int(hashlib.md5(s.encode(), usedforsecurity=False).hexdigest()[:8], 16) % n


def _bind_lang(cfg):
    """Bind shared functions to the selected language."""
    L = build_lang(cfg['lang'])
    L['imperial'] = cfg.get('imperial', False)  # propagate to table helpers
    return {
        'score_badge': lambda s, c=None, t=False: _score_badge(s, c, L=L, is_tropical=t),
        'best_months': lambda m: _best_months(m, L=L),
        'budget_tier': lambda s, a: _budget_tier(s, a, L=L),
        'seasonal_stats': lambda m: _seasonal_stats(m, L=L),
        'climate_table_html': lambda m, n, mtn=False: _climate_table_html(m, n, mtn, L=L),
    }


# ── COMPARISON PAIRS ────────────────────────────────────────────────────────

COMPARISON_PAIRS = [
    ('nice','barcelone'),('algarve','canaries'),('crete','sardaigne'),
    ('sicile','crete'),('majorque','sardaigne'),('corse','sardaigne'),
    ('malte','sicile'),('dubrovnik','split'),('cote-azur','costa-brava'),
    ('mykonos','santorin'),('ibiza','majorque'),('lisbonne','porto'),
    ('barcelone','lisbonne'),('algarve','cote-azur'),('marrakech','fes'),
    ('marrakech','agadir'),('dubai','abu-dhabi'),('bali','phuket'),
    ('koh-samui','koh-lanta'),('chiang-mai','bangkok'),('bali','sri-lanka'),
    ('langkawi','phuket'),('maldives','seychelles'),('ile-maurice','reunion'),
    ('maldives','zanzibar'),('guadeloupe','martinique'),
    ('republique-dominicaine','jamaique'),('cancun','riviera-maya'),
    ('costa-rica','colombie'),('bali','republique-dominicaine'),
    ('tenerife','madere'),('canaries','madere'),('fuerteventura','gran-canaria'),
]


def build_comparison_index(cfg, all_dests=None):
    """Build reverse index for comparison links."""
    lang = cfg['lang']
    if lang == 'fr':
        idx = {}
        for a, b in COMPARISON_PAIRS:
            idx.setdefault(a, []).append((b, f"{a}-ou-{b}-climat.html"))
            idx.setdefault(b, []).append((a, f"{a}-ou-{b}-climat.html"))
        return idx
    else:
        out_dir = os.path.join(DIR, cfg['out_subdir'])
        idx = {}
        for f in glob.glob(os.path.join(out_dir, '*-vs-*-weather.html')):
            fname = os.path.basename(f)
            parts = fname.replace('-weather.html', '').split('-vs-')
            if len(parts) == 2:
                a, b = parts
                idx.setdefault(a, []).append((b, fname))
                idx.setdefault(b, []).append((a, fname))
        return idx


# ── DATA LOADING ────────────────────────────────────────────────────────────

def load_data(cfg):
    """Load destinations, climate, cards, overrides, events."""
    dests = {}
    for row in csv.DictReader(open(f'{DATA}/destinations.csv', encoding='utf-8-sig')):
        dests[row['slug_fr']] = row

    climate = {}
    for row in csv.DictReader(open(f'{DATA}/climate.csv', encoding='utf-8-sig')):
        slug = row['slug']
        if slug not in climate:
            climate[slug] = [None] * 12
        mi = int(row['mois_num']) - 1
        climate[slug][mi] = {
            'mois'    : row['mois'],
            'tmin'    : int(row['tmin']),
            'tmax'    : int(row['tmax']),
            'rain_pct': int(row['rain_pct']),
            'precip'  : float(row['precip_mm']),
            'sun_h'   : float(row['sun_h']),
            'score'     : float(row['score']),
            'classe'    : row['classe'],
            'sea_temp'  : row.get('sea_temp', ''),
            'beach_score': row.get('beach_score', ''),
        }

    cards_file = f'{DATA}/{cfg["cards_file"]}'
    cards = {}
    if os.path.exists(cards_file):
        for row in csv.DictReader(open(cards_file, encoding='utf-8-sig')):
            cards.setdefault(row['slug'], []).append(row)

    overrides = {}
    ov_path = f'{DATA}/overrides.csv'
    if os.path.exists(ov_path):
        for row in csv.DictReader(open(ov_path, encoding='utf-8-sig')):
            key = (row['slug'], int(row['mois_num']) - 1, row['champ'])
            overrides[key] = row['valeur']
        for (slug, mi, champ), val in overrides.items():
            if slug in climate and climate[slug][mi]:
                try:
                    if champ in ('tmin','tmax','rain_pct'):
                        climate[slug][mi][champ] = int(val)
                    elif champ in ('precip','sun_h','score'):
                        climate[slug][mi][champ] = float(val)
                    else:
                        climate[slug][mi][champ] = val
                except ValueError:
                    print(f"[WARN] Invalid override: {slug}/{mi}/{champ}={val}")

    events = {}
    events_path = f'{DATA}/events.csv'
    if os.path.exists(events_path):
        for row in csv.DictReader(open(events_path, encoding='utf-8-sig')):
            events[(row['slug'], int(row['month']))] = {
                'fr': row['event_fr'], 'en': row['event_en'],
            }

    photos = {}
    photos_path = f'{DATA}/destination_photos.csv'
    if os.path.exists(photos_path):
        for row in csv.DictReader(open(photos_path, encoding='utf-8-sig')):
            photos[row['slug_fr']] = {
                'url': row['photo_url'],
                'credit_name': row['photo_credit_name'],
                'credit_url': row['photo_credit_url'],
            }

    return dests, climate, cards, overrides, events, photos


# ── VALIDATION ──────────────────────────────────────────────────────────────

def validate(cfg, dests, climate, cards=None):
    """Validate data consistency. Returns list of errors."""
    errors = []
    MONTHS = cfg['months']

    for slug, months_data in climate.items():
        if None in months_data:
            missing = [MONTHS[i] for i, m in enumerate(months_data) if m is None]
            errors.append(cfg['val_missing_months'].format(slug=slug, missing=', '.join(missing)))
            continue
        for i, m in enumerate(months_data):
            if not (0.0 <= m['score'] <= 10.0):
                errors.append(cfg['val_score_range'].format(slug=slug, month=MONTHS[i], score=m['score']))

    for slug in dests:
        if slug not in climate:
            errors.append(cfg['val_no_climate'].format(slug=slug))

    return errors


# ── SIMILARITY ──────────────────────────────────────────────────────────────

def compute_all_similarities(dests, climate):
    """Compute similarity scores between all destinations."""
    profiles = {}
    for slug in dests:
        if slug not in climate or None in climate[slug]:
            continue
        months = climate[slug]
        profiles[slug] = [m['tmax'] for m in months] + [m['rain_pct'] for m in months] + [m['sun_h'] for m in months]

    import math
    def cos_sim(a, b):
        dot = sum(x * y for x, y in zip(a, b))
        na = math.sqrt(sum(x * x for x in a))
        nb = math.sqrt(sum(x * x for x in b))
        return dot / (na * nb) if na and nb else 0

    similarities = {}
    slugs = list(profiles.keys())
    for i, s1 in enumerate(slugs):
        sims = []
        for j, s2 in enumerate(slugs):
            if i == j:
                continue
            sims.append((cos_sim(profiles[s1], profiles[s2]), s2))
        sims.sort(reverse=True)
        similarities[s1] = sims[:5]
    return similarities


def compute_monthly_crosslinks(dests, climate, top_n=50):
    """For each (destination, month), find the 5 closest top-N destinations
    by monthly score, excluding same country. Returns:
      {slug_fr: {mi (0-based): [other_slug, ...]}}
    """
    import pandas as pd

    # Build top-N by average score
    all_scores = {}
    for slug, months in climate.items():
        if None in months:
            continue
        all_scores[slug] = sum(m['score'] for m in months) / len(months)
    top_slugs = set(sorted(all_scores, key=all_scores.get, reverse=True)[:top_n])

    # Country lookup
    country_of = {slug: dests[slug].get('pays', '') for slug in dests}

    # Monthly score lookup: {slug: [score_m0, score_m1, ..., score_m11]}
    monthly_scores = {}
    for slug in top_slugs:
        if slug not in climate or None in climate[slug]:
            continue
        monthly_scores[slug] = [m['score'] for m in climate[slug]]

    result = {}
    for slug in dests:
        if slug not in climate or None in climate[slug]:
            continue
        my_country = country_of.get(slug, '')
        result[slug] = {}
        for mi in range(12):
            my_score = climate[slug][mi]['score']
            neighbors = []
            for other_slug, other_scores in monthly_scores.items():
                if other_slug == slug:
                    continue
                if country_of.get(other_slug, '') == my_country:
                    continue
                diff = abs(other_scores[mi] - my_score)
                neighbors.append((diff, other_scores[mi], other_slug))
            neighbors.sort()
            result[slug][mi] = [s for _, _, s in neighbors[:5]]
    return result


# ── HTML CONSTANTS ──────────────────────────────────────────────────────────

def GTAG_HTML(pfx=''):
    return f'''<script async src="https://www.googletagmanager.com/gtag/js?id=G-NTCJTDPSJL"></script>
<script defer src="{pfx}js/ga.js"></script>'''







def head_css(cfg):
    pfx = cfg['asset_prefix']
    font_url = "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700;900&family=DM+Sans:wght@300;400;500;600;700&display=swap&font-display=swap"
    return f'''<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link rel="stylesheet" href="{font_url}" media="print" onload="this.media='all'"/>
<noscript><link rel="stylesheet" href="{font_url}"/></noscript>
<link rel="stylesheet" href="{pfx}style.css"/>
<link rel="icon" type="image/x-icon" href="{pfx}favicon.ico"/>
<link rel="apple-touch-icon" sizes="180x180" href="{pfx}apple-touch-icon.png"/>
<meta name="theme-color" content="#1a1f2e"/>'''


def nav_html(cfg, slug_fr=None):
    home_href = cfg['nav_cta_href']
    cta_label = cfg['nav_cta_label']
    share_label = cfg.get('lbl_share_label', 'Share')
    fav_btn = (
        f'<button id="btn-fav" class="nav-share" style="display:flex" '
        f'data-slug="{slug_fr}" onclick="bdwToggleFav(this)" '
        f'aria-label="Ajouter aux favoris" aria-pressed="false">'
        f'<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2">'
        f'<path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/>'
        f'</svg></button>'
    ) if slug_fr else ''
    return f'''<nav>
 <a class="nav-brand" href="{home_href}">Best<em>Date</em>Weather</a>
 <div class="nav-actions">
  {fav_btn}<button class="nav-share" onclick="shareThis()" aria-label="{share_label}"><svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="M8.59 13.51l6.83 3.98M15.41 6.51l-6.82 3.98"/></svg></button>
  <a class="nav-cta" href="{home_href}">{cta_label}</a>
 </div>
</nav>'''


def footer_html(cfg, dest):
    """Generate footer with language toggle."""
    fc = cfg['footer']
    pfx = cfg['asset_prefix']
    slug_fr = dest['slug_fr']
    slug_en = dest['slug_en']

    lang = cfg['lang']
    cross_lang = cfg.get('cross_lang', 'en')
    pfx = cfg['asset_prefix']

    # Build cross-language links from locale cross_links config
    cross_links_cfg = cfg.get('cross_links', [])
    alt_links = []
    for cl in cross_links_cfg:
        cl_lang = cl['lang']
        cl_flag = cl['flag']
        cl_label = cl['label']
        cl_pfx = cl['asset_prefix']
        if cl_lang == 'fr':
            cl_url = f"{cl_pfx}meilleure-periode-{slug_fr}.html"
        elif cl_lang == 'en':
            cl_url = f"{cl_pfx}best-time-to-visit-{slug_en}.html"
        elif cl_lang == 'es':
            slug_es = dest.get('slug_es', slug_en)
            cl_url = f"{cl_pfx}mejor-epoca-{slug_es}.html"
        elif cl_lang == 'en-us':
            cl_url = f"{cl_pfx}best-time-to-visit-{slug_en}.html"
        elif cl_lang == 'de':
            slug_de = dest.get('slug_de', slug_en)
            cl_url = f"{cl_pfx}beste-reisezeit-{slug_de}.html"
        else:
            continue
        alt_links.append(f'<span style="white-space:nowrap"><a href="{cl_url}" class="txt-muted"><img src="{pfx}flags/{cl_flag}.png" srcset="{pfx}flags/2x/{cl_flag}.png 2x" width="20" height="15" alt="" loading="lazy" class="flag-icon-lg"> {cl_label}</a></span>')
    alt_link_p = ('<p class="mt-8">'  + ' · '.join(alt_links) + '</p>') if alt_links else ''

    meth_url, meth_label = fc['methodology']
    app_url, app_label = fc['app']
    about_url, about_label = fc['about']
    faq_url, faq_label = fc['faq']
    legal_url, legal_label = fc['legal']
    priv_url, priv_label = fc['privacy']
    widget_url, widget_label = fc.get('widget', ['../widgets.html', 'Widgets'])

    return f'''<footer>
 <p class="txt-muted-label">bestdateweather.com</p>
 <p><a href="https://open-meteo.com/" rel="noopener" class="txt-muted">{fc['data_by']}</a> · {fc['sources']}</p>
 <p class="mt-8"><a href="{meth_url}" class="txt-muted">{meth_label}</a> · <a href="{about_url}" class="txt-muted">{about_label}</a> · <a href="{faq_url}" class="txt-muted">{faq_label}</a> · <a href="{app_url}" class="txt-muted">{app_label}</a> · <a href="{widget_url}" class="txt-muted">{widget_label}</a></p>
{alt_link_p}
 <p class="f11-muted"><a href="{legal_url}" class="txt-muted">{legal_label}</a> · <a href="{priv_url}" class="txt-muted">{priv_label}</a> · <a href="{fc['contact'][0]}" class="txt-muted">{fc['contact'][1]}</a></p>
</footer>
<script src="{cfg['asset_prefix']}js/core.min.js?v=14" defer></script>
<script src="{cfg['asset_prefix']}js/favs.min.js?v=1" defer></script>
<script src="{cfg['asset_prefix']}js/share.js" defer></script>'''


def _resolve_prep_and_bare(cfg, dest):
    """Return (prep, nom_bare) for the current language.

    Centralise la logique pour gen_annual et gen_monthly.
    Pour ajouter une langue : ajouter un elif avec les colonnes CSV correspondantes.
    """
    lang    = cfg['lang']
    slug_fr = dest['slug_fr']
    lang_key = cfg['dest_fields'].get('prep_key')   # colonne prep dans le CSV
    bare_key = cfg['dest_fields'].get('bare_key')    # colonne nom_bare/nom_xx

    if lang == 'fr':
        prep     = dest.get('prep_fr', 'à')
        nom_bare = dest.get('nom_bare', slug_fr)
    elif lang == 'es':
        prep     = dest.get('prep_es', 'en')
        nom_bare = dest.get('nom_es', dest.get('nom_bare', slug_fr))
    else:
        # EN (et futures langues sans préposition grammaticale)
        prep     = dest.get(f'prep_{lang}', '')
        nom_bare = dest.get(f'nom_{lang}', dest.get('nom_bare', slug_fr))
    return prep, nom_bare


def _resolve_dest_name(cfg, slug, all_dests):
    """Resolve a destination name from its slug (FR or EN) using dest_fields."""
    name_key = cfg['dest_fields']['name_key']
    slug_key = cfg['dest_fields']['slug_key']
    # Try direct lookup by slug_fr first (FR comparison index uses slug_fr)
    d = all_dests.get(slug, {})
    if d:
        return d.get(name_key, d.get('nom_bare', slug))
    # For EN, search by slug_en
    for d in all_dests.values():
        if d.get(slug_key) == slug:
            return d.get(name_key, d.get('nom_bare', slug))
    return slug


# ── ANNUAL PAGE GENERATOR ──────────────────────────────────────────────────

def gen_annual(cfg, fn, dest, months, dest_cards, all_dests, similarities, comparison_index=None):
    C = cfg
    MONTHS = C['months']
    slug_fr = dest['slug_fr']
    slug_en = dest['slug_en']
    slug    = dest_slug(C, dest)
    nom     = dest_name(C, dest)
    nom_f   = dest_name_full(C, dest)  # "à Paris" (FR) or "Paris" (EN)
    country = dest_country(C, dest)
    flag    = dest['flag']
    lat     = float(dest['lat'])
    lon     = float(dest['lon'])
    pfx     = C['asset_prefix']
    booking_id = dest['booking_dest_id']

    # Hero photo (optional)
    _photo = dest.get('_photo', {})
    _photo_url = _photo.get('url', '')
    _photo_credit_name = _photo.get('credit_name', '')
    _photo_credit_url = _photo.get('credit_url', '')

    bests      = fn['best_months'](months)
    best_str   = ' & '.join(bests[:2]) if len(bests) >= 2 else bests[0]
    best_score = max(m['score'] for m in months)
    best_idx   = next(i for i, m in enumerate(months) if m['score'] == best_score)
    best_m     = months[best_idx]
    seas       = fn['seasonal_stats'](months)
    all_scores = [m['score'] for m in months]
    best_rain  = best_m['rain_pct']
    best_tmax  = best_m['tmax']
    is_mountain = dest.get('mountain', 'False').strip() == 'True'
    # Best ski month for mountain destinations
    if is_mountain:
        from scoring import compute_ski_score
        ski_scores = [compute_ski_score(m['tmax'], m['rain_pct'], m['sun_h']) for m in months]
        best_ski_idx   = max(range(12), key=lambda i: ski_scores[i])
        best_ski_score = ski_scores[best_ski_idx]
        # Override hero KPIs : top-2 mois ski (ordre chronologique)
        ski_top2_idx = sorted(
            sorted(range(12), key=lambda i: ski_scores[i], reverse=True)[:2]
        )
        bests     = [MONTHS[i] for i in ski_top2_idx]
        best_str  = ' & '.join(bests)
        best_m    = months[best_ski_idx]
        best_tmax = best_m['tmax']
        best_rain = best_m['rain_pct']
    worst_idx  = min(range(12), key=lambda i: months[i]['score'])
    worst_rain = months[worst_idx]['rain_pct']

    # ── Title & description (5 desc variants, 3 title variants) ──
    title_var = _stable_hash(slug_fr, 3)
    desc_var  = _stable_hash(slug_fr + "desc", 5)

    # Best season name for richer descriptions
    _best_season_name = max(seas, key=lambda s: seas[s]['score'])
    best_sun = best_m['sun_h']

    prep, nom_bare = _resolve_prep_and_bare(C, dest)

    # For mountain destinations, best_month in titles should be the ski best month
    _title_best_idx = best_ski_idx if is_mountain else best_idx
    tpl_vars = dict(prep=prep, nom_bare=nom_bare, nom=nom, year=YEAR,
                    best_month=MONTHS[_title_best_idx], best_month_lc=month_lc(C, MONTHS[_title_best_idx]),
                    best_tmax=best_tmax, best_rain=best_rain, best_score=best_score,
                    best_sun=best_sun, best_tmin=best_m['tmin'],
                    worst_month=MONTHS[worst_idx], worst_month_lc=month_lc(C, MONTHS[worst_idx]),
                    worst_rain=worst_rain,
                    best_season_lc=_best_season_name.lower(),
                    best_ski_month=MONTHS[best_ski_idx] if is_mountain else '',
                    best_ski_month_lc=month_lc(C, MONTHS[best_ski_idx]) if is_mountain else '')

    # Convert temperatures for imperial locales
    if C.get('imperial'):

        for _k in ('best_tmax', 'best_tmin'):
            if _k in tpl_vars:
                tpl_vars[_k] = c_to_f(tpl_vars[_k])

    title    = fill_tpl(C['annual_titles'][title_var], C, **tpl_vars)
    h1_text  = fill_tpl(C['annual_h1s'][title_var],   C, **tpl_vars)
    desc     = fill_tpl(C['annual_descs'][desc_var],   C, **tpl_vars)
    og_title = fill_tpl(C['lbl_og_title_tpl'],         C, **tpl_vars)

    # ── Climate table ──
    table_html = fn['climate_table_html'](months, nom, is_mountain)
    _custom_hsub = dest.get(C['dest_fields']['hero_sub_key'], '').strip()
    if is_mountain and not _custom_hsub and C.get('annual_hero_subs_ski'):
        _hash = int(hashlib.md5(dest.get("slug_fr", "").encode()).hexdigest()[:8], 16) % len(C["annual_hero_subs_ski"])
        hsub = C['annual_hero_subs_ski'][_hash].format(**tpl_vars)
    else:
        hsub = _hero_sub(C, dest)

    # ── Quick facts ──
    qf = f'''<section class="section">
 <div class="section-label">{C['lbl_quick_section']}</div>
 <h2 class="section-title">{C['lbl_quick_title_tpl'].format(name=nom_f)}</h2>
 <div class="quick-facts">
 <div class="quick-facts-row"><div class="qf-label">{C['lbl_best_overall']}</div><div class="qf-value"><strong>{MONTHS[best_idx]}</strong></div></div>
 <div class="quick-facts-row"><div class="qf-label">{C['lbl_optimal_temp']}</div><div class="qf-value"><strong>{fmt_temp(best_m["tmin"], C)}–{fmt_temp(best_m["tmax"], C)}</strong> {C['lbl_in']} {month_lc(C, MONTHS[best_idx])}</div></div>
 <div class="quick-facts-row"><div class="qf-label">{C['lbl_least_rain']}</div><div class="qf-value"><strong>{best_rain}%</strong> {C['lbl_rainy_days_in']} {month_lc(C, MONTHS[best_idx])}</div></div>
 <div class="quick-facts-row"><div class="qf-label">{C['lbl_wettest']}</div><div class="qf-value"><strong>{MONTHS[worst_idx]}</strong> ({worst_rain}%)</div></div>
 <div class="quick-facts-row"><div class="qf-label">{C['lbl_best_score']}</div><div class="qf-value"><strong>{best_score}/10</strong></div></div>
 </div>
</section>'''

    # ── Cards section ──
    tk, xk = C['card_title_key'], C['card_text_key']
    cards_html = '\n'.join(
        f'<div class="project-card"><span class="proj-icon">{c["icon"]}</span>'
        f'<span class="proj-title">{c[tk]}</span>'
        f'<span class="proj-text">{c[xk]}</span></div>'
        for c in dest_cards
    )
    cards_section = f'''<section class="section">
 <div class="section-label">{C['lbl_cards_section']}</div>
 <h2 class="section-title">{C['lbl_cards_title']}</h2>
 <div class="project-grid">{cards_html}</div>
</section>''' if dest_cards else ''

    # ── Climate table section ──
    is_tropical = dest.get('tropical', '').strip().lower() in ('true', '1')
    tropical_note = ''
    if is_tropical:
        tropical_note = C['lbl_tropical_note_html']
    table_section = f'''<section class="section">
 <div class="section-label">{C['lbl_table_section']}</div>
 <h2 class="section-title">{C['lbl_table_title_tpl'].format(name=nom_f)}</h2>
 {table_html}
 {tropical_note}
</section>'''

    # ── Seasonal analysis ──
    season_rows = ''
    for sname in C['season_order']:
        s = seas[sname]
        icon = SEASON_ICONS[sname]
        mrange = C['season_range'][sname]
        season_rows += (f'<h3 class="sub-title">{icon} {sname} ({mrange}) — {s["verdict"]}</h3>'
                        f'<p>{C["lbl_season_temp_tpl"].format(tmax=s["tmax"], rain=s["rain_pct"], sun=s["sun_h"], score=s["score"])}</p>\n')
    seasonal_section = f'''<section class="section">
 <div class="section-label">{C['lbl_season_section']}</div>
 <h2 class="section-title">{C['lbl_season_title']}</h2>
 {season_rows}
</section>'''

    # ── Hotels.com (Expedia Group) ──
    booking_section = ''
    country_name = country
    hotels_dest = quote_plus(f"{nom}, {country_name}")
    hotels_subdomain = C['booking_domain']
    booking_url = f"https://expedia.com/affiliate?siteid=1&landingPage={quote_plus('https://www.expedia.com/Hotel-Search?destination=' + nom + ', ' + country_name)}&camref=1110IB57J&creativeref=1100168075&adref=PZqrOrxQe3"

    off_months = [month_lc(C, MONTHS[i])
                  for i in range(12) if months[i]['score'] >= 6.5 and months[i]['score'] < best_score - 1.5]
    if off_months:
        verb = C['lbl_offer_pl'] if len(off_months[:2]) > 1 else C['lbl_offer_sg']
        budget_tip = f"{C['lbl_tip_prefix']} : {C['lbl_tip_good_tpl'].format(months=', '.join(off_months[:2]), verb=verb)}"
    else:
        m1 = month_lc(C, MONTHS[worst_idx])
        m2 = month_lc(C, MONTHS[(worst_idx+1)%12])
        budget_tip = f"{C['lbl_tip_prefix']} : {C['lbl_tip_offpeak_tpl'].format(m1=m1, m2=m2)}"
    booking_section = f'''<section class="section">
 <div class="section-label">{C['lbl_booking_section']}</div>
 <h2 class="section-title">{C['lbl_booking_title_tpl'].format(name=nom_f)}</h2>
 <div class="affil-box">
 <strong>{C['lbl_booking_cta']}</strong>
 <p>{budget_tip}</p>
 <a href="{booking_url}" target="_blank" rel="sponsored noopener" class="affil-btn">{C['lbl_booking_btn']}</a>
 </div>
</section>'''

    # ── Activities (GetYourGuide) ──
    gyg_domain = C['gyg_domain']
    gyg_lang = C['lang']
    _GYG_LOCALE = {'fr':'fr-FR','en':'en-US','en-us':'en-US','es':'es-ES','de':'de-DE'}
    gyg_locale_code = _GYG_LOCALE.get(gyg_lang, 'en-US')
    gyg_dest = f"{nom}, {country_name}"
    gyg_dest_enc = quote_plus(gyg_dest)
    gyg_url = f"https://www.{gyg_domain}/s/?q={gyg_dest_enc}&partner_id={GYG_PARTNER_ID}&locale={gyg_lang}"
    activities_section = f'''<section class="section">
 <div class="section-label">{C['lbl_activities_section']}</div>
 <h2 class="section-title">{C['lbl_activities_title_tpl'].format(name=nom_f)}</h2>
 <div class="affil-box">
 <strong>{C['lbl_activities_cta']}</strong>
 <a href="{gyg_url}" target="_blank" rel="sponsored noopener" class="affil-btn">{C['lbl_activities_btn']}</a>
 </div>
</section>'''

    # ── Flights (Kiwi via Travelpayouts) ──
    kiwi_to = quote_plus(f"{nom}-{country_name}")
    kiwi_deep = f"https://www.kiwi.com/deep?to={kiwi_to}&lang={gyg_lang}"
    flights_url = f"https://c111.travelpayouts.com/click?shmarker={TP_MARKER}&promo_id=3791&source_type=customlink&type=click&custom_url={quote_plus(kiwi_deep)}"
    flights_section = f'''<section class="section">
 <div class="section-label">{C['lbl_flights_section']}</div>
 <h2 class="section-title">{C['lbl_flights_title_tpl'].format(name=nom_f)}</h2>
 <div class="affil-box">
 <strong>{C['lbl_flights_cta']}</strong>
 <a href="{flights_url}" target="_blank" rel="sponsored noopener" class="affil-btn">{C['lbl_flights_btn']}</a>
 </div>
</section>'''
    # ── Plan bar (compact affiliate strip) ──
    _pb_hotel_lbl = C.get('lbl_plan_hotel', '🏨 ' + C.get('lbl_booking_btn', 'Hébergement'))
    _pb_activ_lbl = C.get('lbl_plan_activ', '🎟️ ' + C.get('lbl_activities_btn', 'Activités'))
    _pb_flight_lbl = C.get('lbl_plan_flight', '✈️ ' + C.get('lbl_flights_btn', 'Vols'))
    _pb_label = C.get('lbl_plan_bar', 'Planifier votre voyage')
    plan_bar_html = f'''<div class="plan-bar">
<span class="plan-bar-label">{_pb_label}</span>
<a href="{booking_url}" target="_blank" rel="sponsored noopener" class="plan-link plan-link-hotel">{_pb_hotel_lbl}</a>
<a href="{gyg_url}" target="_blank" rel="sponsored noopener" class="plan-link plan-link-activ">{_pb_activ_lbl}</a>
<a href="{flights_url}" target="_blank" rel="sponsored noopener" class="plan-link plan-link-flight">{_pb_flight_lbl}</a>
</div>'''

    MONTH_BTN_CLS = {'rec': 'month-btn-rec', 'mid': 'month-btn-mid', 'avoid': 'month-btn-avoid'}
    monthly_links = ''.join(
        f'<a href="{monthly_url(C, slug, i)}" class="month-btn '
        f'{MONTH_BTN_CLS.get(months[i]["classe"], "month-btn-mid")}">'
        f'<div class="fw700-f13">{MONTHS[i]}</div>'
        f'</a>'
        for i in range(12)
    )
    monthly_section = f'''<section class="section">
 <div class="section-label">{C['lbl_monthly_section']}</div>
 <h2 class="section-title">{C['lbl_monthly_title']}</h2>
 <div class="grid-months">
 {monthly_links}
 </div>
</section>'''

    # ── Editorial highlights (top 3 months with snippet) ──
    top3_idx = sorted(range(12), key=lambda i: months[i]['score'], reverse=True)[:3]
    top3_idx_sorted = sorted(top3_idx)  # ordre chronologique
    editorial_cards = []
    for idx in top3_idx_sorted:
        _ed_lang = 'en' if C['lang'] == 'en-us' else C['lang']
        ed_key = f"{slug_fr}:{idx + 1}:{_ed_lang}"
        snippet = _EDITORIAL.get(ed_key, '')
        if not snippet:
            continue
        m_url = monthly_url(C, slug, idx)
        m_score = months[idx]['score']
        m_tmax = fmt_temp(months[idx]['tmax'], C)
        m_classe = months[idx]['classe']
        bg_lbl, txt_lbl, badge_lbl = fn['score_badge'](m_score, m_classe, t=is_tropical)
        badge_html = f'<span style="background:{bg_lbl};color:{txt_lbl};padding:1px 6px;border-radius:4px;font-size:.75rem;font-weight:600">{badge_lbl}</span>'
        # Truncate to ~120 chars for annual view
        short = snippet[:120].rsplit(' ', 1)[0] + '…' if len(snippet) > 120 else snippet
        editorial_cards.append(
            f'<a href="{m_url}" class="editorial-month-card">'
            f'<div class="em-header">'
            f'<span class="em-month">{MONTHS[idx]}</span>'
            f'<span class="em-meta">{badge_html} · {m_tmax}</span>'
            f'</div>'
            f'<p class="em-snippet">{short}</p>'
            f'</a>'
        )
    if editorial_cards:
        ed_label = C.get('lbl_m_editorial_highlights_label', C['lbl_monthly_section'])
        ed_title = C.get('lbl_m_editorial_highlights_title', C['lbl_monthly_title'])
        editorial_highlights_section = f'''<section class="section">
 <div class="section-label">{ed_label}</div>
 <h2 class="section-title">{ed_title.format(nom=nom) if '{nom}' in ed_title else ed_title}</h2>
 <div class="editorial-months-grid">{''.join(editorial_cards)}</div>
</section>'''
    else:
        editorial_highlights_section = ''

    # ── FAQ ──
    winter_key = C['season_order'][-1]  # 'Hiver' (FR) or 'Winter' (EN)
    if is_mountain:
        from scoring import compute_ski_score
        best_ski_idx = max(range(12), key=lambda i: compute_ski_score(months[i]['tmax'], months[i]['rain_pct'], months[i]['sun_h']))
        best_ski_score = f"{compute_ski_score(months[best_ski_idx]['tmax'], months[best_ski_idx]['rain_pct'], months[best_ski_idx]['sun_h']):.1f}"
        winter_months_ski = [compute_ski_score(months[i]['tmax'], months[i]['rain_pct'], months[i]['sun_h']) for i in (11, 0, 1)]
        winter_ski_avg = f"{sum(winter_months_ski)/3:.1f}"
        faq_vars = dict(prep=prep, nom_bare=nom_bare, nom=nom,
                        best_ski_month=MONTHS[best_ski_idx],
                        best_ski_month_lc=month_lc(C, MONTHS[best_ski_idx]),
                        best_ski_score=best_ski_score,
                        best_month=MONTHS[best_idx], best_month_lc=month_lc(C, MONTHS[best_idx]),
                        best_score=best_score, best_tmax=best_tmax,
                        worst_month=MONTHS[worst_idx], worst_rain=worst_rain,
                        winter_ski_avg=winter_ski_avg, jan_tmax=months[0]['tmax'])
        faq_items = [(fill_tpl(item['q'], C, **faq_vars), fill_tpl(item['a'], C, **faq_vars))
                     for item in C['annual_faq_mountain']]
    else:
        # Bests suffix
        bests_suffix = ''
        if len(bests) > 1:
            bests_suffix = C['annual_faq_bests_suffix'].format(bests_str=' & '.join(bests[:2]))
        winter_score = seas[winter_key]['score']
        winter_verdict = C['annual_faq_winter_verdicts']['ok'] if winter_score >= 5.5 else C['annual_faq_winter_verdicts']['bad']
        _best_sun  = round(months[best_idx]['sun_h'], 1)
        _best_tmin = months[best_idx]['tmin']
        _best_tmax_v = best_tmax
        if C.get('imperial'):
            _best_tmax_v = c_to_f(_best_tmax_v)
            _best_tmin   = c_to_f(_best_tmin)
        _temp_unit = C.get('temp_unit', '°C')
        faq_vars = dict(prep=prep, nom_bare=nom_bare, nom=nom,
                        best_month=MONTHS[best_idx], best_month_lc=month_lc(C, MONTHS[best_idx]),
                        best_score=best_score, best_rain=best_rain, best_tmax=_best_tmax_v,
                        best_tmin=_best_tmin, best_sun=_best_sun, temp_unit=_temp_unit,
                        worst_month=MONTHS[worst_idx], worst_rain=worst_rain,
                        bests_suffix=bests_suffix,
                        winter_score=winter_score, winter_verdict=winter_verdict)
        faq_items = [(fill_tpl(item['q'], C, **faq_vars), fill_tpl(item['a'], C, **faq_vars))
                     for item in C['annual_faq_standard']]

    faq_html = '<div class="faq-list">' + ''.join(
        f'<div class="faq-item"><button class="faq-q" onclick="toggleFaq(this)">'
        f'{q}<span class="faq-icon">+</span></button>'
        f'<div class="faq-a">{a}</div></div>'
        for q, a in faq_items
    ) + '</div>'
    faq_schema = json.dumps({
        "@context": "https://schema.org", "@type": "FAQPage",
        "mainEntity": [{"@type": "Question", "name": q,
                        "acceptedAnswer": {"@type": "Answer", "text": a}} for q, a in faq_items]
    }, ensure_ascii=False)
    faq_section = f'''<section class="section">
 <div class="section-label">FAQ</div>
 <h2 class="section-title">{C['lbl_faq_title']}</h2>
 {faq_html}
</section>'''

    # ── Similar destinations ──
    similar_section = ''
    sim_list = (similarities or {}).get(slug_fr, [])
    if sim_list and all_dests:
        sim_cards = ''
        for sim_score, sim_slug in sim_list[:5]:
            # Rescale cosine similarity: 0.975→0%, 1.0→100%
            display_pct = max(0, min(1, (sim_score - 0.975) / 0.025))
            # Qualifier based on rescaled score
            if display_pct >= 0.70:
                sim_label = C['lbl_similar_very']
            elif display_pct >= 0.35:
                sim_label = C['lbl_similar_mid']
            else:
                sim_label = C['lbl_similar_low']
            sd = all_dests.get(sim_slug, {})
            sn = dest_name(C, sd) if sd else sim_slug
            sc = dest_country(C, sd) if sd else ''
            sf = sd.get('flag', '')
            s_slug = dest_slug(C, sd) if sd else sim_slug
            sim_cards += (
                f'<a href="{annual_url(C, s_slug)}" class="sim-card">'
                f'<div class="f13-slate3"><img src="{pfx}flags/{sf}.png" srcset="{pfx}flags/2x/{sf}.png 2x" loading="lazy" width="16" height="12" '
                f'alt="{sf}" class="flag-icon">{sc}</div>'
                f'<div class="fw700-navy">{sn}</div>'
                f'<div class="f12-slate2">{sim_label}</div>'
                f'</a>')
        similar_section = f'''<section class="section">
 <div class="section-label">{C['lbl_similar_section']}</div>
 <h2 class="section-title">{C['lbl_similar_title']}</h2>
 <div class="flex-wrap-14">{sim_cards}</div>
</section>'''

    # ── Rankings ──
    rank_links = ''.join(f'<a href="{url}" class="link-card">{label}</a>' for url, label in C['rankings'])
    ranking_section = f'''<section class="section">
 <div class="section-label">{C['lbl_ranking_section']}</div>
 <h2 class="section-title">{C['lbl_ranking_title']}</h2>
 <div class="flex-wrap-14">{rank_links}</div>
</section>'''

    # ── Pillar + comparison ──
    pillar_comp_cards = []
    best_month_name = MONTHS[best_idx]
    pillar_comp_cards.append(
        f'<a href="{pillar_url(C, best_idx)}" class="link-card">'
        f'{C["lbl_pillar_tpl"].format(month=month_lc(C, best_month_name))}</a>')
    pillar_comparison_section = f'''<section class="section">
 <div class="section-label">{C['lbl_guides_section']}</div>
 <h2 class="section-title">{C['lbl_guides_title']}</h2>
 <div class="flex-wrap-14">{"".join(pillar_comp_cards)}</div>
</section>'''

    # ── Schema.org ──
    canonical = f"{C['canonical_prefix']}{annual_url(C, slug)}"
    hreflang_tags = build_hreflang_tags(dest, mi=None)

    headline = C['lbl_headline_tpl'].format(prep=prep, nom_bare=nom_bare, nom=nom)

    _inlang = {"inLanguage": C['in_language']} if C['in_language'] else {}
    article_schema = json.dumps({
        "@context": "https://schema.org", "@type": "Article",
        "headline": headline, "description": desc,
        "image": {"@type": "ImageObject", "url": "https://bestdateweather.com/og-image.png", "width": 1200, "height": 630},
        "author": {"@type": "Organization", "name": "BestDateWeather", "url": "https://bestdateweather.com", "logo": {"@type": "ImageObject", "url": "https://bestdateweather.com/icon-192.png", "width": 192, "height": 192}},
        "publisher": {"@type": "Organization", "name": "BestDateWeather", "url": "https://bestdateweather.com", "logo": {"@type": "ImageObject", "url": "https://bestdateweather.com/icon-192.png", "width": 192, "height": 192}},
        "datePublished": date_modified_for(slug_fr),
        "dateModified": date_modified_for(slug_fr),
        "inLanguage": C["html_lang"],
        "url": canonical,
        **_inlang,
        "mainEntityOfPage": {"@type": "WebPage", "@id": canonical}
    }, ensure_ascii=False)

    breadcrumb_schema = json.dumps({
        "@context": "https://schema.org", "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": C['lbl_breadcrumb_home'], "item": C['schema_home_url']},
            {"@type": "ListItem", "position": 2, "name": nom, "item": canonical}
        ]
    }, ensure_ascii=False)

    ds_name = C['lbl_dataset_name_tpl'].format(nom=nom)
    ds_desc = C['lbl_dataset_desc_tpl'].format(nom=nom, nom_f=nom_f)

    dataset_schema = json.dumps({
        "@context": "https://schema.org", "@type": "Dataset",
        "name": ds_name, "description": ds_desc,
        "temporalCoverage": "2015/2024",
        "spatialCoverage": {"@type": "Place", "name": nom},
        "creator": {"@type": "Organization", "name": "BestDateWeather", "url": "https://bestdateweather.com"},
        "license": "https://creativecommons.org/licenses/by-nc/4.0/",
        **_inlang,
        "variableMeasured": ["Temperature", "Precipitation", "Sunshine hours", "Wind speed"]
    }, ensure_ascii=False)

    # ── Hero stats ──
    if is_mountain and C.get('lbl_best_ski_months_lbl_tpl'):
        _ski_lbl = C['lbl_best_ski_months_lbl_tpl']
        best_months_lbl = _ski_lbl.replace('{s}', 's' if len(bests) > 1 else '').replace('{es}', 'es' if len(bests) > 1 else '')
    elif len(bests) > 1:
        best_months_lbl = C['lbl_best_months_lbl_tpl'].replace('{s}', 's').replace('{es}', 'es')
    else:
        best_months_lbl = C['lbl_best_months_lbl_tpl'].replace('{s}', '').replace('{es}', '')
    updated_date = f"{MONTHS[date.today().month - 1]} {date.today().year}"

    coords = f"{lat}°N {abs(lon)}°{'E' if lon >= 0 else 'W'}"
    kicker = C['lbl_updated_tpl'].format(date=updated_date, coords=coords)

    # ── Hero photo HTML blocks (pre-computed to avoid backslash in f-string) ──
    if _photo_url:
        _preload_tag = f'<link rel="preload" as="image" href="{_photo_url}" fetchpriority="high"/>'
        _hero_img_block = (
            f'<img src="{_photo_url}" class="hero-bg-img" alt="{nom}"'
            f' loading="eager" decoding="async" fetchpriority="high"/>'
            f'<div class="hero-overlay"></div>'
        )
        _hero_credit = (
            f'<a href="{_photo_credit_url}" class="hero-photo-credit"'
            f' target="_blank" rel="noopener">© {_photo_credit_name}</a>'
            if _photo_credit_name else ''
        )
    else:
        _preload_tag = ''
        _hero_img_block = ''
        _hero_credit = ''

    # ── HTML ASSEMBLY ──
    html = f'''<!DOCTYPE html>
<html lang="{C['html_lang']}">
<head>
<!-- SCORING: generate_pages.py | lang={C['lang']} | slug={slug_fr} | tropical={dest["tropical"]} | generated={TODAY} -->
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>{title}</title>
<meta name="description" content="{desc}"/>
<link rel="canonical" href="{canonical}"/>
{hreflang_tags}
<meta property="og:type" content="article"/>
<meta property="og:title" content="{og_title}"/>
<meta property="og:description" content="{desc}"/>
<meta property="og:url" content="{canonical}"/>
<meta property="og:image" content="https://bestdateweather.com/og-image.png"/>
<meta property="og:image:width" content="1200"/>
<meta property="og:image:height" content="630"/>
<script type="application/ld+json">{article_schema}</script>
<script type="application/ld+json">{faq_schema}</script>
<script type="application/ld+json">{breadcrumb_schema}</script>
<script type="application/ld+json">{dataset_schema}</script>
{GTAG_HTML(pfx)}
{head_css(C)}
{_preload_tag}
<style>
.hero-band{{position:relative;overflow:hidden;background:#0d1a3a;}}
.hero-bg-img{{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center;z-index:0;}}
.hero-overlay{{position:absolute;inset:0;background:linear-gradient(160deg,rgba(13,26,58,0.85) 0%,rgba(26,42,106,0.75) 55%,rgba(42,74,154,0.65) 100%);z-index:1;}}
.hero-band>:not(.hero-bg-img):not(.hero-overlay){{position:relative;z-index:2;}}
.hero-photo-credit{{position:absolute;bottom:6px;right:10px;font-size:.68rem;color:rgba(255,255,255,.45);z-index:3;text-decoration:none;}}
.hero-title em{{color:#93c5fd;}}
.editorial-months-grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:12px;}}
.editorial-month-card{{display:block;padding:14px 16px;background:#fff;border:1px solid #e2e8f0;border-radius:10px;text-decoration:none;color:inherit;transition:box-shadow .15s;}}
.editorial-month-card:hover{{box-shadow:0 4px 14px rgba(0,0,0,.1);border-color:#93c5fd;}}
.em-header{{display:flex;align-items:center;justify-content:space-between;margin-bottom:6px;}}
.em-month{{font-weight:700;font-size:.95rem;color:#1e3a5f;}}
.em-meta{{font-size:.8rem;color:#64748b;}}
.em-snippet{{font-size:.82rem;color:#475569;margin:0;line-height:1.5;}}
</style>
<script async defer src="https://widget.getyourguide.com/dist/pa.umd.production.min.js" data-gyg-partner-id="{GYG_PARTNER_ID}"></script>
</head>
<body>
{nav_html(C, slug_fr=slug_fr)}
<header class="hero-band">
{_hero_img_block}
 <div class="dest-tag"><img src="{pfx}flags/{flag}.png" srcset="{pfx}flags/2x/{flag}.png 2x" width="20" height="15" alt="{flag.upper()}" loading="lazy" class="flag-icon"> {nom}, {country}</div>
 <h1 class="hero-title">{h1_text}</h1>
 <p class="hero-sub">{hsub}</p>
 <div class="kicker">{kicker}</div>
 <div class="hero-stats mt-22">
 <div><span class="hstat-val">{best_str}</span><span class="hstat-lbl">{best_months_lbl}</span></div>
 <div><span class="hstat-val">{fmt_temp(best_tmax, C)}</span><span class="hstat-lbl">{C['lbl_optimal_temp_stat']}</span></div>
 <div><span class="hstat-val">{best_rain}%</span><span class="hstat-lbl">{C['lbl_rainy_days_stat']}</span></div>
 </div>
{_hero_credit}
</header>
<main class="page">
{qf}
{cards_section}
{table_section}
{plan_bar_html}
{seasonal_section}
{booking_section}
{activities_section}
{flights_section}
{monthly_section}
{editorial_highlights_section}
{faq_section}
{similar_section}
{ranking_section}
{pillar_comparison_section}
</main>
{footer_html(C, dest)}
<script src="{pfx}js/faq.js" defer></script>
</body>
</html>'''
    return html


# ── CONTEXT PARAGRAPH ──────────────────────────────────────────────────────

def context_paragraph(cfg, nom, nom_f, m, mi, score, best_month, best_score, is_tropical, event_text=None, is_mountain=False, ski_sc=0):
    """Generate a context paragraph per destination × month."""
    C = cfg
    MONTHS = C['months']
    month = MONTHS[mi]
    season_map = C['seasons_map']
    season = season_map[mi]
    tmax, rain, sun = m['tmax'], m['rain_pct'], m['sun_h']
    cp = C['context_paragraphs']

    # Season names from locale
    season_order = C['season_order']  # [Spring/Printemps, Summer/Été, Autumn/Automne, Winter/Hiver]
    season_spring, season_summer, season_autumn, season_winter = season_order

    fvars = dict(month=month, month_lc=month_lc(C, month), nom=nom, nom_f=nom_f,
                 tmax=tmax, rain=rain, sun=sun, score=score,
                 best_month=best_month, best_month_lc=month_lc(C, best_month),
                 best_score=f"{best_score:.1f}")

    parts = []
    if event_text:
        parts.append(f"<strong>🎯 {event_text}</strong>")

    # ── Ski context override for mountain destinations ──
    if is_mountain and C.get('context_paragraphs_ski'):
        cps = C['context_paragraphs_ski']
        if ski_sc >= 8.0:
            parts.append(cps['ski_peak'].format(**fvars))
        elif ski_sc >= 6.5:
            parts.append(cps['ski_good'].format(**fvars))
        elif ski_sc >= 5.0:
            parts.append(cps['ski_shoulder'].format(**fvars))
        elif ski_sc >= 3.0:
            parts.append(cps['ski_poor'].format(**fvars))
        else:
            parts.append(cps['ski_offseason'].format(**fvars))
        # Ajouter pluie si conditions limit (tmax > 2°C)
        if m['tmax'] > 2:
            if rain <= 25:
                parts.append(cp['rain_low'].format(**fvars))
            elif rain >= 50:
                parts.append(cp['rain_high'].format(**fvars))
        return ' '.join(parts)

    # Main condition (non-ski)
    if is_tropical and rain >= 50:
        parts.append(cp['tropical_wet'].format(**fvars))
    elif is_tropical and rain <= 20:
        parts.append(cp['tropical_dry'].format(**fvars))
    elif season == season_summer and tmax >= 30:
        parts.append(cp['summer_hot'].format(**fvars))
    elif season == season_summer and tmax >= 22:
        parts.append(cp['summer_warm'].format(**fvars))
    elif season == season_winter and tmax <= 10:
        parts.append(cp['winter_cold'].format(**fvars))
    elif season == season_winter and tmax >= 20:
        parts.append(cp['winter_warm'].format(**fvars))
    elif season == season_spring:
        parts.append(cp['spring'].format(**fvars))
    elif season == season_autumn and score >= 7:
        parts.append(cp['autumn_good'].format(**fvars))
    elif season == season_autumn:
        parts.append(cp['autumn_bad'].format(**fvars))
    else:
        parts.append(cp['default'].format(**fvars))

    # Rain
    if rain <= 10:
        parts.append(cp['rain_none'].format(**fvars))
    elif rain <= 25:
        parts.append(cp['rain_low'].format(**fvars))
    elif rain <= 45:
        parts.append(cp['rain_mid'].format(**fvars))
    else:
        parts.append(cp['rain_high'].format(**fvars))

    # Best month comparison
    if score >= 9:
        parts.append(cp['score_top'].format(**fvars))
    elif score >= 7.5:
        parts.append(cp['score_good'].format(**fvars))
    elif score >= 5.5:
        parts.append(cp['score_fair'].format(**fvars))

    return ' '.join(parts)


# ── HELPER: SIM CARDS ──────────────────────────────────────────────────────

def _build_sim_cards(cfg, sim_list, all_dests, climate_for_sim, mi):
    C = cfg
    MONTHS = C['months']
    parts = []
    for _, sim_slug in sim_list:
        sd = all_dests.get(sim_slug)
        if not sd:
            continue
        if sd.get('monthly', 'True').strip().lower() not in ('true', '1', 'yes', ''):
            continue
        sc = climate_for_sim.get(sim_slug, {})
        s_slug = dest_slug(C, sd)
        name = dest_name(C, sd)
        url = f"{s_slug}{C['monthly_sep']}{C['month_url'][mi]}.html"
        pfx_flag = f"{C['asset_prefix']}flags/"
        sep = C.get('lbl_colon_sep', ': ')
        lbl = f"{MONTHS[mi]}{sep}{sc.get('score','?')}/10 · {fmt_temp(sc.get('tmax', 0), C)}"
        parts.append(
            f'<a href="{url}" class="sim-card-sm">'
            f'<div class="fw700-navy-f14">'
            f'<img src="{pfx_flag}{sd.get("flag","")}.png" loading="lazy" width="16" height="12" '
            f'alt="" class="flag-icon">'
            f'{name}</div>'
            f'<div class="f12-slate2">{lbl}</div>'
            f'</a>')
    return ''.join(parts)


def _build_comp_cards_monthly(cfg, slug, nom, comparison_index, all_dests):
    if not comparison_index or slug not in comparison_index:
        return ''
    cards = []
    or_word = cfg['lbl_or_word']
    for other_slug, comp_file in comparison_index[slug][:2]:
        other_nom = _resolve_dest_name(cfg, other_slug, all_dests)
        label = f'⚖️ {nom} {or_word} {other_nom} ?'
        cards.append(
            f'<a href="{comp_file}" class="link-card">'
            f'{label}</a>')
    return ''.join(cards)


# ── MONTHLY PAGE GENERATOR ────────────────────────────────────────────────

def gen_monthly(cfg, fn, dest, months, mi, all_dests, similarities, all_climate, events=None, comparison_index=None, monthly_crosslinks=None):
    C = cfg
    lang    = C['lang']
    MONTHS  = C['months']
    MABBR   = C['month_abbr']
    slug_fr = dest['slug_fr']
    slug_en = dest['slug_en']
    slug    = dest_slug(C, dest)
    nom     = dest_name(C, dest)
    nom_f   = dest_name_full(C, dest)
    flag    = dest['flag']
    lat     = float(dest['lat'])
    lon     = float(dest['lon'])
    pfx     = C['asset_prefix']

    m        = months[mi]
    score    = m['score']
    season   = C['seasons_map'][mi]
    month    = MONTHS[mi]
    m_url    = C['month_url'][mi]
    is_fr    = C['is_fr']
    is_mountain = dest.get('mountain', 'False').strip() == 'True'
    is_tropical = dest.get('tropical', '').strip().lower() in ('true', '1')

    all_scores = [mo['score'] for mo in months]
    best_idx   = max(range(12), key=lambda i: months[i]['score'])
    best_month = MONTHS[best_idx]
    best_score = months[best_idx]['score']

    eff_classe = m['classe']
    ski_sc = 0  # default; overridden for mountain below
    if is_mountain:
        from scoring import compute_ski_score, best_class
        ski_sc = compute_ski_score(m['tmax'], m['rain_pct'], m['sun_h'])
        eff_classe = best_class(m['classe'], ski_sc)
    bg, txt, verdict_lbl = fn['score_badge'](score, eff_classe, is_tropical)
    bud = fn['budget_tier'](score, all_scores)

    prev_mi = (mi - 1) % 12
    next_mi = (mi + 1) % 12

    # Activities — use locale labels
    is_coastal  = dest.get('coastal', 'True').strip().lower() in ('true', '1', 'yes')
    act_city  = C['lbl_m_act_city_good'] if score >= 6.5 else C['lbl_m_act_city_ok']
    act_ext   = C['lbl_m_act_ext_good'] if score >= 7.5 else (C['lbl_m_act_ext_ok'] if score >= 6.0 else C['lbl_m_act_ext_bad'])
    if not is_coastal:
        act_beach = C['lbl_m_act_beach_na']
    else:
        act_beach = (C['lbl_m_act_beach_good'] if score >= 7.5 and m['tmax'] >= 25
                     else (C['lbl_m_act_beach_ok'] if score >= 6.5 and m['tmax'] >= 20 else C['lbl_m_act_beach_bad']))

    # Context flags
    is_hot      = m['tmax'] >= 30
    is_warm     = 22 <= m['tmax'] < 30
    is_mild     = 15 <= m['tmax'] < 22
    is_cold     = m['tmax'] < 15
    is_rainy    = m['rain_pct'] >= 50
    is_dry      = m['rain_pct'] <= 15
    is_sunny    = m['sun_h'] >= 10
    is_winter   = mi in (11, 0, 1)
    is_summer   = mi in (5, 6, 7)
    is_shoulder = mi in (3, 4, 8, 9)
    hash_var    = (_stable_hash(slug_fr + str(mi), 3))

    prep, nom_bare = _resolve_prep_and_bare(C, dest)
    mlc = month_lc(C, month)

    # Template vars for locale lookups
    tpl = dict(month=month, month_lc=mlc, nom=nom, nom_bare=nom_bare, prep=prep,
               name=nom, year=YEAR, tmin=m['tmin'],
               best_month=best_month, best_month_lc=month_lc(C, best_month),
               tmax=m['tmax'], rain=m['rain_pct'], sun=m['sun_h'],
               score=f"{score:.1f}", best_score=f"{best_score:.1f}",
               diff=round(best_score - score, 1),
               lat=f"{lat:.2f}", lon=f"{abs(lon):.2f}",
               dir="E" if lon >= 0 else "W",
               annual_link=annual_url(C, slug))

    # Convert temperatures in tpl for imperial locales (en-us)
    if C.get('imperial'):

        for _k in ('tmax', 'tmin'):
            if _k in tpl:
                tpl[_k] = c_to_f(tpl[_k])

    # ── Hero sub ──
    if is_mountain and C.get('monthly_hero_subs_ski'):
        from scoring import compute_ski_score
        ski_sc_hero = compute_ski_score(m['tmax'], m['rain_pct'], m['sun_h'])
        best_ski_idx_hero = max(range(12), key=lambda i: compute_ski_score(months[i]['tmax'], months[i]['rain_pct'], months[i]['sun_h']))
        tpl['best_ski_month_lc'] = month_lc(C, MONTHS[best_ski_idx_hero])
        if ski_sc_hero >= 7.5:
            ski_tier = 'ski_excellent'
        elif ski_sc_hero >= 6.0:
            ski_tier = 'ski_good'
        else:
            ski_tier = 'ski_poor'
        ski_subs = C['monthly_hero_subs_ski'][ski_tier]
        hero_sub = ski_subs[hash_var % len(ski_subs)].format(**tpl)
    else:
        tier = 'excellent' if score >= 8.5 else ('good' if score >= 7.0 else 'poor')
        hero_sub = C['monthly_hero_subs'][tier][hash_var].format(**tpl)

    # ── Verdict text ──
    vtier = 'excellent' if score >= 9.0 else ('good' if score >= 7.0 else ('fair' if score >= 5.0 else 'poor'))
    # Contenu éditorial enrichi (generate_editorial.py) prioritaire sur template
    _editorial_lang = 'en' if lang == 'en-us' else lang
    _editorial_key = f"{slug_fr}:{mi + 1}:{_editorial_lang}"
    if _editorial_key in _EDITORIAL:
        verdict_txt = _EDITORIAL[_editorial_key]
    else:
        verdict_txt = C['monthly_verdicts'][vtier][hash_var].format(**tpl)

    # Bars
    rain_bar = bar_chart(m['rain_pct'])
    temp_bar = bar_chart(min(m['tmax'], 40), 40)
    sun_bar  = bar_chart(min(m['sun_h'], 14), 14)

    # ── Oui si / Yes if ──
    osi = C['monthly_oui_si']
    fvars = dict(sun=m['sun_h'], tmax=m['tmax'], rain=m['rain_pct'])
    if score >= 8.0:
        if is_tropical and is_dry:     key = 'high_tropical_dry'
        elif is_hot and is_sunny:      key = 'high_hot_sunny'
        elif is_warm and is_dry:       key = 'high_warm_dry'
        elif is_summer:                key = 'high_summer'
        elif is_shoulder:              key = 'high_shoulder'
        else:                          key = 'high_default'
    elif score >= 6.0:
        if is_rainy:                   key = 'mid_rainy'
        elif is_cold:                  key = 'mid_cold'
        elif is_mild:                  key = 'mid_mild'
        elif is_shoulder:              key = 'mid_shoulder'
        else:                          key = 'mid_default'
    else:
        if is_tropical and is_rainy:   key = 'low_tropical_rainy'
        elif is_cold and is_winter:    key = 'low_cold_winter'
        elif is_rainy:                 key = 'low_rainy'
        else:                          key = 'low_default'
    oui_si = osi[key + '_yes'].format(**fvars)
    non_si = osi[key + '_no'].format(**fvars)

    # ── Month nav ──
    MNAV_CLS = {'rec': 'mnav-rec', 'mid': 'mnav-mid', 'avoid': 'mnav-avoid'}
    def _mnav_attr(i):
        if i == mi:
            return ' class="active"'
        c = MNAV_CLS.get(months[i]['classe'], '')
        return f' class="{c}"' if c else ''

    month_nav = ''.join(
        f'<a href="{slug}{C["monthly_sep"]}{C["month_url"][i]}.html"{_mnav_attr(i)}>{MABBR[i]}</a>'
        for i in range(12))

    # ── Annual table ──
    table_rows = ''
    for i, mo in enumerate(months):
        highlight = ' class="row-highlight"' if i == mi else ''
        cls = mo['classe']
        ski_col = ''
        if is_mountain:
            from scoring import compute_ski_score, best_class
            ski = compute_ski_score(mo['tmax'], mo['rain_pct'], mo['sun_h'])
            cls = best_class(mo['classe'], ski)
            ski_col = f'<td>{ski:.1f}/10</td>'
        table_rows += (f'<tr class="{cls}"{highlight}>'
                       f'<td>{weather_emoji(mo["tmax"], mo["rain_pct"], mo["sun_h"], mo.get("tmin"))} {MONTHS[i]}</td>'
                       f'<td data-label="{C["lbl_m_th_tmin"]}">{fmt_temp(mo["tmin"], C)}</td>'
                       f'<td data-label="{C["lbl_m_th_tmax"]}">{fmt_temp(mo["tmax"], C)}</td>'
                       f'<td data-label="{C["lbl_m_th_rain"]}">{mo["rain_pct"]}%</td>'
                       f'<td data-label="{C["lbl_m_th_precip"]}">{fmt_precip(mo["precip"], C)}</td>'
                       f'<td data-label="{C["lbl_m_th_sun"]}">{mo["sun_h"]}h</td>'
                       f'<td data-label="{C["lbl_m_th_score"]}">{mo["score"]:.1f}/10</td>{ski_col}</tr>\n')

    # Best month diff
    bm = months[best_idx]
    diff_t = round(bm['tmax'] - m['tmax'])
    diff_r = round(bm['rain_pct'] - m['rain_pct'])
    diff_s = round(bm['sun_h'] - m['sun_h'], 1)

    # ── FAQ (locale-driven, language-agnostic) ──
    ft = C['faq_templates']
    _fv = dict(
        name=nom_f, month=month, month_lc=mlc,
        tmax=m['tmax'], tmin=m['tmin'], rain=m['rain_pct'],
        sun=m['sun_h'], score=f"{score:.1f}",
        best_month=best_month, best_month_lc=month_lc(C, best_month),
        best_score=f"{best_score:.1f}", prep=prep, nom_bare=nom_bare,
    )
    if C.get('imperial'):
        _fv['tmax'] = c_to_f(_fv['tmax'])
        _fv['tmin'] = c_to_f(_fv['tmin'])

    # Q1 — is this a good time?
    faq_q1 = ft['good_period_q'].format(**_fv)
    if is_mountain:
        from scoring import compute_ski_score
        ski_this = compute_ski_score(m['tmax'], m['rain_pct'], m['sun_h'])
        _fv['ski'] = f"{ski_this:.1f}"
        if ski_this >= 6.5 and score < 5:
            faq_a1 = ft['ski_a_good'].format(**_fv)
        elif ski_this >= 5 and score < 5:
            faq_a1 = ft['ski_a_fair'].format(**_fv)
        elif score >= 9:
            faq_a1 = ft.get('mountain_summer_a_good', ft['good_period_a_rec']).format(**_fv)
        elif score >= 7:
            faq_a1 = ft.get('mountain_summer_a_mid', ft['good_period_a_rec']).format(**_fv)
        else:
            faq_a1 = ft.get('mountain_summer_a_transition', ft['good_period_a_avoid']).format(**_fv)
    elif score >= 9:
        faq_a1 = ft['good_period_a_rec'].format(**_fv)
    elif score >= 7.5:
        faq_a1 = ft['good_period_a_rec'].format(**_fv)
    elif score >= 5.5:
        faq_a1 = ft['good_period_a_mid'].format(**_fv)
    else:
        faq_a1 = ft['good_period_a_avoid'].format(**_fv)

    # Q2 — contextual follow-up
    if is_mountain and is_cold:
        if not is_mountain or 'ski_this' not in dir():
            from scoring import compute_ski_score
            ski_this = compute_ski_score(m['tmax'], m['rain_pct'], m['sun_h'])
            _fv['ski'] = f"{ski_this:.1f}"
        faq_q2 = ft.get('ski_q_cold', ft['ski_q']).format(**_fv)
        if ski_this >= 6.5:
            faq_a2 = ft.get('ski_a_good_mountain', ft['ski_a_good']).format(**_fv)
        elif ski_this >= 4:
            faq_a2 = ft.get('ski_a_fair_mountain', ft['ski_a_fair']).format(**_fv)
        else:
            faq_a2 = ft.get('ski_a_bad_mountain', ft['ski_a_bad']).format(**_fv)
    elif is_hot and is_dry:
        faq_q2 = ft.get('weather_q_hot2', ft['weather_q_hot']).format(**_fv)
        faq_a2 = (ft['weather_a_hot_intense'] if m['tmax'] >= 38 else ft['weather_a_hot_ok']).format(**_fv)
    elif is_rainy:
        faq_q2 = ft['weather_q_rain'].format(**_fv)
        faq_a2 = (ft['weather_a_rain_tropical'] if is_tropical else ft['weather_a_rain_normal']).format(**_fv)
    elif is_cold:
        faq_q2 = ft['weather_q_cold'].format(**_fv)
        faq_a2 = ft['weather_a_cold'].format(**_fv)
    elif score >= 8:
        faq_q2 = ft.get('activity_q', ft['weather_q_default']).format(**_fv)
        faq_a2 = (ft.get('activity_a_outdoor_tropical', ft.get('activity_a_outdoor', ft['weather_a_default'])) if is_tropical
                  else ft.get('activity_a_outdoor', ft['weather_a_default'])).format(**_fv)
    else:
        faq_q2 = ft.get('activity_q', ft['weather_q_default']).format(**_fv)
        faq_a2 = (ft.get('activity_a_cultural', ft.get('activity_a_indoor', ft['weather_a_default'])) if score >= 6
                  else ft.get('activity_a_indoor', ft['weather_a_default'])).format(**_fv)
    # Q3 — what to pack
    faq_q3 = ft.get('pack_q', '').format(**_fv) if ft.get('pack_q') else ''
    faq_a3 = ''
    if faq_q3:
        tmax_val = m['tmax'] if not C.get('imperial') else c_to_f(m['tmax'])
        if tmax_val >= 28 and m['rain_pct'] <= 20:
            faq_a3 = ft.get('pack_a_hot_dry', '').format(**_fv)
        elif tmax_val >= 25:
            faq_a3 = ft.get('pack_a_hot_rain', '').format(**_fv)
        elif tmax_val >= 12:
            faq_a3 = ft.get('pack_a_mild', '').format(**_fv)
        else:
            faq_a3 = ft.get('pack_a_cold', '').format(**_fv)

    # Q4 — comparison with best month
    faq_q4 = ft.get('compare_q', '').format(**_fv) if ft.get('compare_q') else ''
    faq_a4 = ''
    if faq_q4:
        if score >= best_score - 0.3:
            faq_a4 = ft.get('compare_a_best', '').format(**_fv)
        elif score >= best_score - 1.5:
            faq_a4 = ft.get('compare_a_good', '').format(**_fv)
        else:
            faq_a4 = ft.get('compare_a_below', '').format(**_fv)

    # ── Schemas ──
    faq_entities = [
        {"@type": "Question", "name": faq_q1, "acceptedAnswer": {"@type": "Answer", "text": faq_a1}},
        {"@type": "Question", "name": faq_q2, "acceptedAnswer": {"@type": "Answer", "text": faq_a2}},
    ]
    if faq_q3 and faq_a3:
        faq_entities.append({"@type": "Question", "name": faq_q3, "acceptedAnswer": {"@type": "Answer", "text": faq_a3}})
    if faq_q4 and faq_a4:
        faq_entities.append({"@type": "Question", "name": faq_q4, "acceptedAnswer": {"@type": "Answer", "text": faq_a4}})

    faq_schema = json.dumps({
        "@context": "https://schema.org", "@type": "FAQPage",
        "mainEntity": faq_entities
    }, ensure_ascii=False)

    canonical = C['canonical_prefix'] + monthly_url(C, slug, mi)
    hreflang_tags = build_hreflang_tags(dest, mi=mi)
    article_headline = C['monthly_article_headline_tpl'].format(**tpl)
    article_desc = C['monthly_article_desc_tpl'].format(**tpl)

    article_schema = json.dumps({
        "@context": "https://schema.org", "@type": "Article",
        "headline": article_headline,
        "description": article_desc,
        "image": {"@type": "ImageObject", "url": "https://bestdateweather.com/og-image.png", "width": 1200, "height": 630},
        "author": {"@type": "Organization", "name": "BestDateWeather", "url": "https://bestdateweather.com", "logo": {"@type": "ImageObject", "url": "https://bestdateweather.com/icon-192.png", "width": 192, "height": 192}},
        "publisher": {"@type": "Organization", "name": "BestDateWeather", "url": "https://bestdateweather.com", "logo": {"@type": "ImageObject", "url": "https://bestdateweather.com/icon-192.png", "width": 192, "height": 192}},
        "datePublished": date_modified_for(slug_fr, str(mi)),
        "dateModified": date_modified_for(slug_fr, str(mi)),
        "inLanguage": C["html_lang"],
        "url": canonical,
        "mainEntityOfPage": {"@type": "WebPage", "@id": canonical}
    }, ensure_ascii=False)

    bc_items = [
        {"@type": "ListItem", "position": 1, "name": C['lbl_breadcrumb_home'], "item": C['base_url']},
        {"@type": "ListItem", "position": 2, "name": nom, "item": C['canonical_prefix'] + annual_url(C, slug)},
        {"@type": "ListItem", "position": 3, "name": month, "item": canonical}
    ]
    breadcrumb_schema = json.dumps({
        "@context": "https://schema.org", "@type": "BreadcrumbList",
        "itemListElement": bc_items
    }, ensure_ascii=False)

    # ── Title / Desc / H1 (from locale template arrays) ──
    title_var = _stable_hash(slug_fr + str(mi), 4)
    desc_var  = _stable_hash(slug_fr + str(mi) + "d", 3)
    h1_var    = _stable_hash(slug_fr + str(mi) + "h1", 3)

    _verdict = C['lbl_m_verdict_period_rec'] if score >= 7.5 else C['lbl_m_verdict_period_avg'] if score >= 5.5 else C['lbl_m_verdict_period_bad']
    tpl['verdict'] = _verdict

    tpl['season'] = C['seasons_map'][mi]
    tpl['season_lc'] = C['seasons_map'][mi].lower()

    # ── rain_label : contextuel pour destinations tropicales ──────────────────
    # Tropical + rain>60% : remplacer le % brut par une formulation qualitative
    # Les averses tropicales brèves ne sont pas comparables à la pluie tempérée
    if is_tropical and m['rain_pct'] >= 60:
        if m['rain_pct'] >= 75:
            tpl['rain_label'] = C.get('tropical_rainy_season', f"{int(m['rain_pct'])}% rain")
        else:
            tpl['rain_label'] = C.get('tropical_showers', f"{int(m['rain_pct'])}% rain")
    else:
        tpl['rain_label'] = f"{int(m['rain_pct'])}% rain"

    # ── sea_temp : disponible si renseigné dans climate.csv ──────────────────
    _sea = m.get('sea_temp')
    if _sea and str(_sea).strip() not in ('', 'None', '0'):
        _sea_val = round(float(_sea))
        if C.get('imperial'):
            _sea_val = round(float(_sea) * 9/5 + 32)
        tpl['sea_temp'] = _sea_val
        tpl['sea_label'] = C.get('sea_temp_label', f'{_sea_val}° sea').format(sea_temp=_sea_val)
    else:
        tpl['sea_temp'] = ''
        tpl['sea_label'] = ''

    # sea_label_comma : ', 28°C sea' si disponible, sinon vide
    tpl['sea_label_comma'] = f", {tpl['sea_label']}" if tpl['sea_label'] else ''

    title    = fill_tpl(C['monthly_titles'][title_var], C, **tpl)
    desc     = fill_tpl(C['monthly_descs'][desc_var],   C, **tpl)
    h1_text  = fill_tpl(C['monthly_h1s'][h1_var],       C, **tpl)
    og_title = fill_tpl(C['lbl_m_og_title_tpl'],         C, **tpl)

    # ── Cross-linking similar destinations ──
    if is_mountain:
        # Pour les stations ski : trier les autres stations par proximité de ski_score ce mois
        from scoring import compute_ski_score as _csk
        _my_ski = _csk(m['tmax'], m['rain_pct'], m['sun_h'])
        _ski_sims = []
        for _ss, _sd in all_dests.items():
            if _ss == slug_fr: continue
            if _sd.get('mountain','False').strip() != 'True': continue
            if _ss not in all_climate or not all_climate[_ss][mi]: continue
            _sm = all_climate[_ss][mi]
            _other_ski = _csk(_sm['tmax'], _sm['rain_pct'], _sm['sun_h'])
            _ski_sims.append((abs(_other_ski - _my_ski), _ss))
        _ski_sims.sort(key=lambda x: x[0])
        sim_list_for_page = [(1 - d/10, s) for d, s in _ski_sims[:3]]
        climate_for_sim = {}
        for _, sim_slug in sim_list_for_page:
            if sim_slug in all_climate and all_climate[sim_slug][mi]:
                sm = all_climate[sim_slug][mi]
                _ssc = _csk(sm['tmax'], sm['rain_pct'], sm['sun_h'])
                climate_for_sim[sim_slug] = {'score': f"{_ssc:.1f}", 'tmax': sm['tmax']}
        sim_cards_html = _build_sim_cards(cfg, sim_list_for_page, all_dests, climate_for_sim, mi)
    else:
        climate_for_sim = {}
        for _, sim_slug in similarities.get(slug_fr, [])[:3]:
            if sim_slug in all_climate and all_climate[sim_slug][mi]:
                sm = all_climate[sim_slug][mi]
                climate_for_sim[sim_slug] = {'score': f"{sm['score']:.1f}", 'tmax': sm['tmax']}
        sim_cards_html = _build_sim_cards(cfg, similarities.get(slug_fr, [])[:3], all_dests, climate_for_sim, mi)

    if is_mountain and C.get('lbl_m_sec_similar_ski_tpl'):
        sim_section_title = C['lbl_m_sec_similar_ski_tpl'].format(**tpl)
        sim_section_label = C.get('lbl_m_sim_label_ski', C['lbl_m_sim_label'])
    else:
        sim_section_title = C['lbl_m_sec_similar_title_tpl'].format(**tpl)
        sim_section_label = C['lbl_m_sim_label']

    # ── Monthly score crosslinks (top-50, pays différent, même mois) ──
    crosslink_section_html = ''
    if monthly_crosslinks:
        cl_slugs = (monthly_crosslinks.get(slug_fr) or {}).get(mi, [])
        cl_climate = {}
        for cs in cl_slugs:
            if cs in all_climate and all_climate[cs][mi]:
                sm = all_climate[cs][mi]
                cl_climate[cs] = {'score': f"{sm['score']:.1f}", 'tmax': sm['tmax']}
        if cl_slugs:
            cl_cards = _build_sim_cards(cfg, [(0, s) for s in cl_slugs], all_dests, cl_climate, mi)
            cl_title = C.get('lbl_m_crosslink_title_tpl', C['lbl_m_sec_similar_title_tpl']).format(**tpl)
            cl_label = C.get('lbl_m_crosslink_label', C['lbl_m_sim_label'])
            crosslink_section_html = f'''<section class="section">
 <div class="section-label">{cl_label}</div>
 <h2 class="section-title">{cl_title}</h2>
 <div class="flex-wrap-14">{cl_cards}</div>
 </section>'''

    # Pillar + comparison links
    pillar_link = (f'<a href="{pillar_url(C, mi)}" class="link-card">'
                   f'{C["lbl_pillar_tpl"].format(**tpl)}</a>')

    # ── Context paragraph ──
    event_text = (events or {}).get((slug_fr, mi+1), {}).get(C['lang'])
    _ski_sc_ctx = ski_sc if is_mountain else 0
    ctx_para = context_paragraph(cfg, nom,
                                 nom_f, m, mi, score, best_month, best_score,
                                 dest.get('tropical', '').strip().lower() in ('true', '1'), event_text,
                                 is_mountain=is_mountain, ski_sc=_ski_sc_ctx)

    # ── Labels ──
    # ── Labels (built from locale config) ──
    L = {
        'html_lang':      C['html_lang'],
        'hstat_tmax':     C['lbl_m_hstat_tmax'],
        'hstat_rain':     C['lbl_m_hstat_rain'],
        'hstat_sun':      C['lbl_m_hstat_sun'],
        'sec_summary':    C['lbl_m_sec_summary'],
        'sec_summary_title': C['lbl_m_sec_summary_title_tpl'].format(**tpl),
        'qf_tminmax':     C['lbl_m_qf_tminmax'],
        'qf_rain':        C['lbl_m_qf_rain'],
        'qf_rain_unit':   C['lbl_m_rain_unit'],
        'qf_sun':         C['lbl_m_qf_sun'],
        'qf_sun_unit':    C['lbl_m_sun_unit'],
        'qf_season':      C['lbl_m_qf_season'],
        'qf_score':       C['lbl_m_qf_score'],
        'qf_best':        C['lbl_m_qf_best_month'],
        'sec_verdict':    C['lbl_m_sec_decision'],
        'sec_verdict_title': C['lbl_m_sec_decision_title_tpl'].format(**tpl),
        'yes_lbl':        C['lbl_m_yes_if'],
        'no_lbl':         C['lbl_m_no_if'],
        'bar_rain':       C['lbl_m_bar_rain'],
        'bar_temp':       C['lbl_m_bar_temp'],
        'bar_sun':        C['lbl_m_bar_sun'],
        'verdict_intro':  C['lbl_m_our_opinion'],
        'sec_activity':   C['lbl_m_sec_activities'],
        'sec_activity_title': C['lbl_m_sec_activities_title_tpl'].format(**tpl),
        'act_city':       C['lbl_m_lbl_city'],
        'act_ext':        C['lbl_m_lbl_ext'],
        'act_beach':      C['lbl_m_lbl_beach'],
        'act_budget':     C['lbl_m_lbl_budget'],
        'sec_context':    C['lbl_m_sec_context'],
        'sec_context_title': C['lbl_m_sec_context_title'].format(**tpl),
        'sec_nav':        C['lbl_m_sec_nav'],
        'sec_nav_title':  C['lbl_m_sec_nav_title_tpl'].format(**tpl),
        'sec_table':      C['lbl_m_sec_table'],
        'sec_table_title': C['lbl_m_sec_table_title'],
        'th_month':       C['lbl_m_th_month'],
        'th_tmin':        C['lbl_m_th_tmin'],
        'th_tmax':        C['lbl_m_th_tmax'],
        'th_rain':        C['lbl_m_th_rain'],
        'th_precip':      C['lbl_m_th_precip'],
        'th_sun':         C['lbl_m_th_sun'],
        'th_score':       C['lbl_m_th_score'],
        'th_ski':         C['lbl_m_th_ski'],
        'legend_ideal':   C['table_legend_ideal'],
        'legend_ok':      C['table_legend_fair'],
        'legend_bad':     C['table_legend_off'],
        'legend_note':    C['lbl_m_legend_note'],
        'src_label':      C['lbl_m_src_label'],
        'src_text':       C['lbl_m_src_text_tpl'].format(**tpl),
        'src_link_text':  C['lbl_m_src_link_text'],
        'src_link':       C['lbl_m_src_link'],
        'sec_compare':    C['lbl_m_sec_compare'],
        'sec_compare_title': C['lbl_m_sec_compare_title_tpl'].format(**tpl),
        'compare_intro':  C['lbl_m_compare_intro_tpl'].format(**tpl),
        'cmp_tmax':       C['lbl_m_cmp_tmax'],
        'cmp_rain':       C['lbl_m_cmp_rain'],
        'cmp_sun':        C['lbl_m_cmp_sun'],
        'sec_faq':        C['lbl_m_sec_faq'],
        'sec_faq_title':  C['lbl_m_sec_faq_title_tpl'].format(**tpl),
        'prev_label':     C['lbl_m_prev_label'],
        'next_label':     C['lbl_m_next_label'],
        'annual_label':   C['lbl_m_annual_label'],
        'annual_text':    C['lbl_m_annual_text'],
        'annual_best':    C['lbl_m_annual_best_tpl'].format(**tpl),
        'sec_rankings':   C['lbl_m_sec_rankings'],
        'sec_rankings_title': C['lbl_m_sec_rankings_title'],
        'rank_links':     C['rankings'],
        'sec_guides':     C['lbl_m_sec_guides'],
        'sec_guides_title': C['lbl_m_sec_guides_title'],
        'cta_title':      C['lbl_m_cta_title'],
        'cta_text':       C['lbl_m_cta_text'],
        'cta_btn':        C['lbl_m_cta_btn'],
        'cta_link':       C['lbl_m_cta_link'],
        'kicker':         C['lbl_m_kicker_tpl'].format(**tpl),
    }

    # ── Prev/Next URLs ──
    prev_url = monthly_url(C, slug, prev_mi)
    next_url = monthly_url(C, slug, next_mi)
    annual_link = annual_url(C, slug)

    rank_links_html = ''.join(
        f'<a href="{url}" class="link-card">{label}</a>'
        for url, label in L['rank_links'])

    # ── HEAD CSS / NAV / FOOTER from gen_annual helpers ──
    NAV      = nav_html(cfg, slug_fr=slug_fr)

    # ── Hotels.com (monthly) ──
    country_name = dest_country(cfg, dest)
    hotels_dest_m = quote_plus(f"{nom}, {country_name}")
    hotels_subdomain_m = cfg['booking_domain']
    bk_url = f"https://expedia.com/affiliate?siteid=1&landingPage={quote_plus('https://www.expedia.com/Hotel-Search?destination=' + nom + ', ' + country_name)}&camref=1110IB57J&creativeref=1100168075&adref=PZqrOrxQe3"
    bk_cta = C['lbl_m_bk_cta_tpl'].format(**tpl)
    booking_section = f'''<section class="section">
 <div class="section-label">{cfg['lbl_booking_section']}</div>
 <h2 class="section-title">{cfg['lbl_booking_title_tpl'].format(name=nom_f)}</h2>
 <div class="affil-box">
 <strong>{bk_cta}</strong>
 <a href="{bk_url}" target="_blank" rel="sponsored noopener" class="affil-btn">{cfg['lbl_booking_btn']}</a>
 </div>
</section>'''

    # ── Activities (GetYourGuide) – monthly ──
    gyg_domain_m = C['gyg_domain']
    gyg_lang_m = C['gyg_lang']
    _GYG_LOCALE_M = {'fr':'fr-FR','en':'en-US','en-us':'en-US','es':'es-ES','de':'de-DE'}
    gyg_locale_code_m = _GYG_LOCALE_M.get(C['lang'], 'en-US')
    gyg_dest_m = f"{nom}, {country_name}"
    gyg_dest_m_enc = quote_plus(gyg_dest_m)
    gyg_url_m = f"https://www.{gyg_domain_m}/s/?q={gyg_dest_m_enc}&partner_id={GYG_PARTNER_ID}&locale={gyg_lang_m}"
    activities_section = f'''<section class="section">
 <div class="section-label">{cfg['lbl_activities_section']}</div>
 <h2 class="section-title">{cfg['lbl_activities_title_tpl'].format(name=nom_f)}</h2>
 <div class="affil-box">
 <strong>{cfg['lbl_activities_cta']}</strong>
 <a href="{gyg_url_m}" target="_blank" rel="sponsored noopener" class="affil-btn">{cfg['lbl_activities_btn']}</a>
 </div>
</section>'''

    # ── Flights (Kiwi via Travelpayouts) – monthly ──
    kiwi_to_m = quote_plus(f"{nom}-{country_name}")
    kiwi_deep_m = f"https://www.kiwi.com/deep?to={kiwi_to_m}&departure={YEAR}-{mi+1:02d}-01&lang={gyg_lang_m}"
    flights_url_m = f"https://c111.travelpayouts.com/click?shmarker={TP_MARKER}&promo_id=3791&source_type=customlink&type=click&custom_url={quote_plus(kiwi_deep_m)}"
    flights_section = f'''<section class="section">
 <div class="section-label">{cfg['lbl_flights_section']}</div>
 <h2 class="section-title">{cfg['lbl_flights_title_tpl'].format(name=nom_f)}</h2>
 <div class="affil-box">
 <strong>{cfg['lbl_flights_cta']}</strong>
 <a href="{flights_url_m}" target="_blank" rel="sponsored noopener" class="affil-btn">{cfg['lbl_flights_btn']}</a>
 </div>
</section>'''

    # ── Plan bar mensuel ──
    _pb_label_m = cfg.get('lbl_plan_bar', 'Planifier votre voyage')
    _pb_hotel_m = cfg.get('lbl_plan_hotel', '🏨 ' + cfg.get('lbl_booking_btn', 'Hébergement'))
    _pb_activ_m = cfg.get('lbl_plan_activ', '🎟️ ' + cfg.get('lbl_activities_btn', 'Activités'))
    _pb_flight_m = cfg.get('lbl_plan_flight', '✈️ ' + cfg.get('lbl_flights_btn', 'Vols'))
    plan_bar_m = f'''<div class="plan-bar">
<span class="plan-bar-label">{_pb_label_m}</span>
<a href="{bk_url}" target="_blank" rel="sponsored noopener" class="plan-link plan-link-hotel">{_pb_hotel_m}</a>
<a href="{gyg_url_m}" target="_blank" rel="sponsored noopener" class="plan-link plan-link-activ">{_pb_activ_m}</a>
<a href="{flights_url_m}" target="_blank" rel="sponsored noopener" class="plan-link plan-link-flight">{_pb_flight_m}</a>
</div>'''

    html = f'''<!DOCTYPE html>
<html lang="{L['html_lang']}">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>{title}</title>
<meta name="description" content="{desc}"/>
<link rel="canonical" href="{canonical}"/>
{hreflang_tags}
<meta property="og:type" content="article"/>
<meta property="og:title" content="{og_title}"/>
<meta property="og:description" content="{desc}"/>
<meta property="og:url" content="{canonical}"/>
<meta property="og:image" content="https://bestdateweather.com/og-image.png"/>
<meta property="og:image:width" content="1200"/>
<meta property="og:image:height" content="630"/>
<script type="application/ld+json">{article_schema}</script>
<script type="application/ld+json">{faq_schema}</script>
<script type="application/ld+json">{breadcrumb_schema}</script>
{GTAG_HTML(pfx)}
{head_css(cfg)}
<style>
.hero-band{{background:{MONTHLY_GRAD[mi]};}}
.hero-title em{{color:#93c5fd;}}
.month-nav{{display:flex;gap:10px;margin-bottom:24px;flex-wrap:wrap;}}
.month-nav a{{padding:8px 14px;border-radius:8px;font-size:13px;font-weight:600;text-decoration:none;background:white;border:1.5px solid #e8e0d0;color:var(--navy);}}
.month-nav a.active{{background:var(--gold);color:white;border-color:var(--gold);}}
.month-nav a:hover{{border-color:var(--gold);}}
</style>
<script async defer src="https://widget.getyourguide.com/dist/pa.umd.production.min.js" data-gyg-partner-id="{GYG_PARTNER_ID}"></script>
</head>
<body>
{NAV}
<header class="hero-band">
 <div class="dest-tag"><img src="{pfx}flags/{flag}.png" srcset="{pfx}flags/2x/{flag}.png 2x" width="20" height="15" alt="{flag.upper()}" loading="lazy" class="flag-icon"> {nom} · {season}</div>
 <h1 class="hero-title">{h1_text}</h1>
 <p class="hero-sub">{hero_sub}</p>
 <div class="kicker">{L['kicker']}</div>
 <div class="hero-stats mt-22">
 <div><span class="hstat-val">{fmt_temp(m['tmax'], C)}</span><span class="hstat-lbl">{L['hstat_tmax']}</span></div>
 <div><span class="hstat-val">{m['rain_pct']}%</span><span class="hstat-lbl">{L['hstat_rain']}</span></div>
 <div><span class="hstat-val">{m['sun_h']}h</span><span class="hstat-lbl">{L['hstat_sun']}</span></div>
 </div>
</header>
<main class="page">
 <section class="section">
 <div class="section-label">{L['sec_summary']}</div>
 <h2 class="section-title">{L['sec_summary_title']}</h2>
 <div class="verdict-badge" style="background:{bg};color:{txt};border:1.5px solid {txt}">{verdict_lbl}</div>
 <div class="quick-facts">
 <div class="quick-facts-row"><div class="qf-label">🌡️ {L['qf_tminmax']}</div><div class="qf-value"><strong>{fmt_temp(m['tmin'], C)} – {fmt_temp(m['tmax'], C)}</strong></div></div>
 <div class="quick-facts-row"><div class="qf-label">🌧 {L['qf_rain']}</div><div class="qf-value"><strong>{m['rain_pct']}%</strong> {L['qf_rain_unit']}</div></div>
 <div class="quick-facts-row"><div class="qf-label">☀️ {L['qf_sun']}</div><div class="qf-value"><strong>{m['sun_h']}h</strong> {L['qf_sun_unit']}</div></div>
 <div class="quick-facts-row"><div class="qf-label">🌊 {L['qf_season']}</div><div class="qf-value"><strong>{season}</strong></div></div>
 <div class="quick-facts-row"><div class="qf-label">⭐ {L['qf_score']}</div><div class="qf-value"><strong>{score:.1f}/10</strong></div></div>
 <div class="quick-facts-row"><div class="qf-label">📅 {L['qf_best']}</div><div class="qf-value"><strong>{best_month}</strong> ({best_score:.1f}/10)</div></div>
 </div>
 </section>

 <section class="section" class="mb-28">
 <div class="section-label">{L['sec_verdict']}</div>
 <h2 class="section-title">{L['sec_verdict_title']}</h2>
 <div class="verdict-badge" style="background:{bg};color:{txt};border:1.5px solid {txt}">{verdict_lbl}</div>
 <div class="f14-body-mb">
 <p class="mb-8"><strong>{L['yes_lbl']}</strong> {oui_si}</p>
 <p><strong>{L['no_lbl']}</strong> {non_si}</p>
 </div>
 <div class="bar-wrap">
 <div>🌧 {L['bar_rain']} : {rain_bar} <span class="txt-gray">{m['rain_pct']}%</span></div>
 <div>🌡 {L['bar_temp']} : {temp_bar} <span class="txt-gray">{fmt_temp(m['tmax'], C)}</span></div>
 <div>☀️ {L['bar_sun']} : {sun_bar} <span class="txt-gray">{m['sun_h']}{C['locale']['comp']['sun_per_day_short']}</span></div>
 </div>
 <p class="f14-body-sep"><strong>{L['verdict_intro']}</strong> {verdict_txt}</p>
 </section>

 <section class="section" class="mb-28">
 <div class="section-label">{L['sec_activity']}</div>
 <h2 class="section-title">{L['sec_activity_title']}</h2>
 <ul class="act-list">
 <li class="act-item-odd">🏙️ {L['act_city']} : <strong>{act_city}</strong></li>
 <li class="act-item-even">🚶 {L['act_ext']} : <strong>{act_ext}</strong></li>
 <li class="act-item-odd">{L['act_beach']} : <strong>{act_beach}</strong></li>
 <li class="act-item-last">💰 {L['act_budget']} : <strong>{bud}</strong></li>
 </ul>
 </section>

 <section class="section" class="ctx-section mb-28">
 <div class="section-label">{L['sec_context']}</div>
 <h2 class="section-title">{L['sec_context_title']}</h2>
 <p class="f14-context">{ctx_para}</p>
 </section>

 <section class="section">
 <div class="section-label">{L['sec_nav']}</div>
 <h2 class="section-title">{L['sec_nav_title']}</h2>
 <div class="month-nav">{month_nav}</div>
 </section>

 <section class="section">
 <div class="section-label">{L['sec_table']}</div>
 <h2 class="section-title">{L['sec_table_title']}</h2>
 <div class="{'climate-table-wrap mountain' if is_mountain else 'climate-table-wrap'}">
 <table class="climate-table climate-table--horizontal" aria-label="{L['sec_table_title']} {nom}">
 <thead><tr><th>{L['th_month']}</th><th>{L['th_tmin']}</th><th>{L['th_tmax']}</th><th>{L['th_rain']}</th><th>{L['th_precip']}</th><th>{L['th_sun']}</th><th>{L['th_score']}</th>{'<th>' + L['th_ski'] + '</th>' if is_mountain else ''}</tr></thead>
 <tbody>{table_rows}</tbody>
 </table>
 </div>
 <div class="table-legend">
 <span><span class="legend-dot legend-rec"></span>{L.get('legend_ideal_mtn', L['legend_ideal']) if is_mountain else L['legend_ideal']}</span>
 <span><span class="legend-dot legend-mid"></span>{L['legend_ok']}</span>
 <span><span class="legend-dot legend-avoid"></span>{L.get('legend_off_mtn', L['legend_bad']) if is_mountain else L['legend_bad']}</span>
 <span class="ml-auto">{L['legend_note']}</span>
 </div>
 </section>

 <div class="eeat-note" class="eeat-note">
 <strong class="txt-navy-block">{L['src_label']}</strong>
 {L['src_text']}
 <a href="{L['src_link']}" class="txt-gold">{L['src_link_text']}</a>
 · <a href="{annual_link}" class="txt-gold">{C['lbl_annual_view_link']}</a>
 </div>

 <section class="section" class="mb-28">
 <div class="section-label">{L['sec_compare']}</div>
 <h2 class="section-title">{L['sec_compare_title']}</h2>
 <p class="f14-mb12">{L['compare_intro']}</p>
 <ul class="cmp-list">
 <li class="act-item-odd">🌡️ {L['cmp_tmax']} : <strong>{'+' if diff_t >= 0 else ''}{diff_t}{'°F' if C.get('imperial') else '°C'}</strong></li>
 <li class="act-item-even">🌧 {L['cmp_rain']} : <strong>{'+' if diff_r >= 0 else ''}{diff_r}%</strong></li>
 <li class="act-item-last">☀️ {L['cmp_sun']} : <strong>{'+' if diff_s >= 0 else ''}{diff_s}{C['locale']['comp']['sun_per_day']}</strong></li>
 </ul>
 </section>

 <section class="section" class="mb-28">
 <div class="section-label">{L['sec_faq']}</div>
 <h2 class="section-title">{L['sec_faq_title']}</h2>
 <div class="flex-col-12">
 <div class="faq-card">
 <div class="fw700-mb">{faq_q1}</div>
 <div class="f14-detail">{faq_a1}</div>
 </div>
 <div class="faq-card">
 <div class="fw700-mb">{faq_q2}</div>
 <div class="f14-detail">{faq_a2}</div>
 </div>
 </div>
 </section>

{plan_bar_m}
{booking_section}
{activities_section}
{flights_section}

 <section class="section">
 <div class="section-label">{L['prev_label'].split()[0]}</div>
 <div class="flex-wrap-14">
 <a href="{prev_url}" class="nav-card">
 <div class="f11-slate3-mb">{L['prev_label']}</div>
 <div class="fw700-navy">{MONTHS[prev_mi]}</div>
 <div class="f12-slate2">{fmt_temp(months[prev_mi]['tmax'], C)} · {months[prev_mi]['rain_pct']}% {C['lbl_rain_word']}</div>
 </a>
 <a href="{annual_link}" class="nav-card-active">
 <div class="f11-slate3-mb">{L['annual_label']}</div>
 <div class="fw700-navy">{L['annual_text']}</div>
 <div class="f12-slate2">{L['annual_best']}</div>
 </a>
 <a href="{next_url}" class="nav-card">
 <div class="f11-slate3-mb">{L['next_label']}</div>
 <div class="fw700-navy">{MONTHS[next_mi]}</div>
 <div class="f12-slate2">{fmt_temp(months[next_mi]['tmax'], C)} · {months[next_mi]['rain_pct']}% {C['lbl_rain_word']}</div>
 </a>
 </div>
 </section>

 <section class="section">
 <div class="section-label">{sim_section_label}</div>
 <h2 class="section-title">{sim_section_title}</h2>
 <div class="flex-wrap-14">{sim_cards_html}</div>
 </section>

 {crosslink_section_html}

 <section class="section">
 <div class="section-label">{L['sec_rankings']}</div>
 <h2 class="section-title">{L['sec_rankings_title']}</h2>
 <div class="flex-wrap-14">{rank_links_html}</div>
 </section>

 <section class="section">
 <div class="section-label">{L['sec_guides']}</div>
 <h2 class="section-title">{L['sec_guides_title']}</h2>
 <div class="flex-wrap-14">{pillar_link}</div>
 </section>

 <section class="widget-section">
 <div class="cta-box" class="text-center">
 <strong>{L['cta_title']}</strong>
 <p>{L['cta_text']}</p>
 <a class="cta-btn" href="{L['cta_link']}">
 <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" class="icon-18"><path d="M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01"/></svg>
 {L['cta_btn']}
 </a>
 </div>
 </section>
</main>
{footer_html(cfg, dest)}
</body>
</html>'''
    return html


# ── MAIN ────────────────────────────────────────────────────────────────────

def main():
    import argparse
    parser = argparse.ArgumentParser(description='BestDateWeather unified page generator')
    parser.add_argument('--lang', required=True, choices=['fr', 'en', 'en-us', 'es', 'de'])
    parser.add_argument('--dry-run', action='store_true')
    parser.add_argument('--validate-only', action='store_true')
    parser.add_argument('target', nargs='*', default=None, help='One or more destination slugs (omit for all)')
    args = parser.parse_args()

    cfg = build_config(args.lang)
    fn  = _bind_lang(cfg)

    print(f"BestDateWeather — generate_pages.py --lang {args.lang}")
    print(f"Mode: {'validate-only' if args.validate_only else 'dry-run' if args.dry_run else 'production'}")
    target_list = args.target if args.target else None
    print(f"Target: {', '.join(target_list) if target_list else 'all destinations'}\n")

    dests, climate, cards, overrides, events, photos = load_data(cfg)

    errors = validate(cfg, dests, climate, cards)
    if errors:
        print(f"⚠️  {len(errors)} issue(s) detected:")
        for e in errors:
            print(f"   {e}")
        if any(e.startswith('[P0]') for e in errors):
            print("\n❌ P0 blocking errors. Fix data/climate.csv first.")
            if not args.dry_run:
                sys.exit(1)
    else:
        print("✅ Validation OK\n")

    if args.validate_only:
        return

    similarities = compute_all_similarities(dests, climate)
    monthly_crosslinks = compute_monthly_crosslinks(dests, climate)
    comp_index = build_comparison_index(cfg)

    OUT = os.path.join(DIR, cfg['out_subdir']) if cfg['out_subdir'] else DIR
    os.makedirs(OUT, exist_ok=True)

    slugs = target_list if target_list else list(dests.keys())
    total_annual = total_monthly = 0
    errors_gen = []

    for slug_key in slugs:
        if slug_key not in dests:
            print(f"[SKIP] {slug_key}: unknown destination")
            continue
        if slug_key not in climate or None in climate[slug_key]:
            print(f"[SKIP] {slug_key}: incomplete climate data")
            continue

        dest   = dests[slug_key]
        months = climate[slug_key]
        dest_cards_list = cards.get(slug_key, [])
        slug = dest_slug(cfg, dest)

        # Inject photo info into dest dict
        dest['_photo'] = photos.get(slug_key, {})

        # Annual page
        try:
            html = gen_annual(cfg, fn, dest, months, dest_cards_list, dests, similarities, comp_index)
            out  = os.path.join(OUT, annual_url(cfg, slug))
            if not args.dry_run:
                open(out, 'w', encoding='utf-8').write(html)
            total_annual += 1
        except Exception as e:
            errors_gen.append(f"{slug_key}/annual: {e}")

        # 12 monthly pages
        gen_monthly_pages = dest.get('monthly', 'True').strip().lower() in ('true', '1', 'yes', '')
        if gen_monthly_pages:
            for mi in range(12):
                try:
                    html = gen_monthly(cfg, fn, dest, months, mi, dests, similarities, climate, events, comp_index, monthly_crosslinks)
                    out  = os.path.join(OUT, monthly_url(cfg, slug, mi))
                    if not args.dry_run:
                        open(out, 'w', encoding='utf-8').write(html)
                    total_monthly += 1
                except Exception as e:
                    errors_gen.append(f"{slug_key}/{cfg['months'][mi]}: {e}")

        if not args.dry_run:
            monthly_msg = f"12 monthly" if gen_monthly_pages else "monthly skipped"
            print(f"✓ {slug}: 1 annual + {monthly_msg}")

    print(f"\n{'[DRY-RUN] ' if args.dry_run else ''}Generated: {total_annual} annual + {total_monthly} monthly pages")
    if errors_gen:
        print(f"Generation errors ({len(errors_gen)}):")
        for e in errors_gen:
            print(f"  {e}")
    else:
        print("✅ No generation errors")

    if overrides:
        print(f"ℹ️  {len(overrides)} override(s) applied from overrides.csv")


if __name__ == '__main__':
    main()
