#!/usr/bin/env python3
"""Translate 799 FR activity cards to proper English."""
import csv, re

# ── TITLE MAP (all 684 unique titles) ──
T = {
"42 plages":"42 beaches","Abou Simbel":"Abu Simbel","Aconcagua & Andes":"Aconcagua & Andes",
"Acquario di Genova":"Genoa Aquarium","Adelaide Festival":"Adelaide Festival",
"Afrobeats & vie nocturne":"Afrobeats & nightlife","Agneau mystique & cathédrale":"Mystic Lamb & cathedral",
"Aitutaki Lagoon":"Aitutaki Lagoon","Al-Balad":"Al-Balad","AlUla Moments Festival":"AlUla Moments Festival",
"Ala-Archa & Tian Shan":"Ala-Archa & Tian Shan","Altiplano & Illimani":"Altiplano & Illimani",
"Amazonie & lodges":"Amazon & lodges","Amber Fort & Hawa Mahal":"Amber Fort & Hawa Mahal",
"Ananas & agriculture":"Pineapple & farming","Ancienne capitale Hoa Lu":"Ancient capital Hoa Lu",
"Apartheid Museum":"Apartheid Museum","Aquarium":"Aquarium",
"Arbres dragon sang":"Dragon blood trees","Archipel de Göteborg":"Gothenburg archipelago",
"Architecture coloniale":"Colonial architecture","Armée de terre cuite":"Terracotta Army",
"Art & Red Rocks":"Art & Red Rocks","Arthur's Pass & Canterbury":"Arthur's Pass & Canterbury",
"Artisanat & miniatures":"Crafts & miniatures","Arènes historiques":"Historic arena",
"Asado & Mercado del Puerto":"Asado & Mercado del Puerto","Asado & gastronomie":"Asado & gastronomy",
"Aurores boréales":"Northern lights","Auroville & Matrimandir":"Auroville & Matrimandir",
"Avenue des volcans":"Avenue of Volcanoes","BBQ de Memphis":"Memphis BBQ",
"BBQ texan":"Texas BBQ","Backwaters d'Alleppey":"Alleppey backwaters",
"Bailong Elevator":"Bailong Elevator","Balade dans les rizières":"Rice paddy walk",
"Balboa Park":"Balboa Park","Baleines & dauphins":"Whales & dolphins",
"Baleines à bosse":"Humpback whales","Bamboo Train":"Bamboo Train",
"Barcola & Grotta Gigante":"Barcola & Grotta Gigante",
"Bari Vecchia & Saint-Nicolas":"Bari Vecchia & St Nicholas","Baroque leccese":"Lecce Baroque",
"Baroque sicilien":"Sicilian Baroque","Barossa Valley":"Barossa Valley",
"Barrière de corail":"Coral reef","Barrière de corail méso-américaine":"Mesoamerican Barrier Reef",
"Barton Springs Pool":"Barton Springs Pool","Base des pandas géants":"Giant Panda Base",
"Batik & artisanat":"Batik & crafts","Batroun & Tyr":"Batroun & Tyre",
"Bazar & cuisine perse":"Bazaar & Persian cuisine","Bazar vert & cuisine":"Green bazaar & cuisine",
"Bazars & artisanat":"Bazaars & crafts","Baščaršija":"Baščaršija",
"Beale Street & blues":"Beale Street & blues","Belvédère & Trois Cocotiers":"Belvédère viewpoint",
"Biergarten & Tiroler Gröstl":"Biergarten & Tiroler Gröstl",
"Biodiversité unique":"Unique biodiversity","Bivouac bédouin":"Bedouin bivouac",
"Blue Lagoon & Champagne Beach":"Blue Lagoon & Champagne Beach",
"Bodegas de Ronda":"Ronda bodegas","Boiling Lake":"Boiling Lake",
"Bollywood":"Bollywood","Borobudur au lever":"Borobudur at sunrise",
"Bouddha géant de Leshan":"Leshan Giant Buddha","Bouldering":"Bouldering",
"Boulevard Riyadh City":"Riyadh Boulevard","Brasseries & restaurants":"Breweries & restaurants",
"Brasseries & winstubs":"Breweries & winstubs","Brasseries artisanales":"Craft breweries",
"Bruny Island":"Bruny Island","Budget":"Budget",
"Bunny chow & curry":"Bunny chow & curry","Byblos & Baalbek":"Byblos & Baalbek",
"Bà Nà Hills & Golden Bridge":"Bà Nà Hills & Golden Bridge",
"Cable Beach & Paradise Island":"Cable Beach & Paradise Island",
"Cacao & café du Chiapas":"Chiapas cacao & coffee","Cachalots résidents":"Resident sperm whales",
"Café & chocolat":"Coffee & chocolate","Café guatémaltèque":"Guatemalan coffee",
"Café rwandais":"Rwandan coffee","Cafés & chocolat":"Cafés & chocolate",
"Cafés historiques":"Historic cafés","Caldeiras & Sete Cidades":"Caldeiras & Sete Cidades",
"Callejones & maisons colorées":"Alleys & colorful houses",
"Canal du Midi":"Canal du Midi","Canyon Matka":"Matka Canyon",
"Cap Spartel & grottes d'Hercule":"Cap Spartel & Hercules Caves",
"Cape Coast Castle":"Cape Coast Castle","Capitale gastronomique":"Food capital",
"Capri":"Capri","Carnaval de Salvador":"Salvador Carnival",
"Casco Antiguo":"Casco Antiguo","Casco histórico & Panteón":"Historic center & Panteón",
"Castel del Monte":"Castel del Monte","Cathédrale de la Seu":"La Seu Cathedral",
"Central Market":"Central Market","Central Otago Pinot Noir":"Central Otago Pinot Noir",
"Centre colonial":"Colonial center","Centre colonial blanc":"White colonial center",
"Centre culturel Tjibaou":"Tjibaou Cultural Centre","Centre historique":"Historic center",
"Centre historique UNESCO":"UNESCO historic center","Centre historique inca":"Inca historic center",
"Centro histórico":"Historic center","Cerro Catedral":"Cerro Catedral",
"Ceviche & Getsemaní":"Ceviche & Getsemaní","Chale Wote Festival":"Chale Wote Festival",
"Champagne Reef":"Champagne Reef","Champon & castella":"Champon & castella",
"Charyn Canyon":"Charyn Canyon","Chianti Classico":"Chianti Classico",
"Chocolat & marchés":"Chocolate & markets","Chocolat artisanal":"Artisan chocolate",
"Christuskirche & Alte Feste":"Christuskirche & Alte Feste",
"Chutes Victoria":"Victoria Falls","Chutes Victoria côté Zambie":"Victoria Falls (Zambia side)",
"Chutes d'Iguazú":"Iguazú Falls","Château de Miramare":"Miramare Castle",
"Château des ducs de Bretagne":"Castle of the Dukes of Brittany",
"Château médiéval":"Medieval castle","Ciel étoilé":"Stargazing",
"Cijin Island":"Cijin Island","Cinque Terre":"Cinque Terre",
"Circuito Chico":"Circuito Chico","Cité de l'Espace":"Cité de l'Espace",
"Cité des voiles":"City of Sails","Cité impériale":"Imperial Citadel",
"Ciudad Amurallada":"Walled City","Cochons nageurs d'Exuma":"Exuma swimming pigs",
"Columbia River Gorge":"Columbia River Gorge","Conch salad & Fish Fry":"Conch salad & Fish Fry",
"Condado & Isla Verde":"Condado & Isla Verde","Congress Bridge Bats":"Congress Bridge Bats",
"Costa Verde & Barranco":"Costa Verde & Barranco","Cotton Tree & histoire":"Cotton Tree & history",
"Coucher depuis les remparts":"Sunset from the ramparts",
"Cradle Mountain":"Cradle Mountain","Craft beer & cafés":"Craft beer & cafés",
"Craft beer & food trucks":"Craft beer & food trucks","Criques turquoise":"Turquoise coves",
"Crocodiles & Kakadu":"Crocodiles & Kakadu","Croisière Li River":"Li River cruise",
"Croisière Padar & Rinca":"Padar & Rinca cruise","Cross-Island Track":"Cross-Island Track",
"Cuisine & friteries":"Cuisine & friteries","Cuisine Southern":"Southern cuisine",
"Cuisine bahianaise":"Bahian cuisine","Cuisine birmane":"Burmese cuisine",
"Cuisine burkinabè":"Burkinabè cuisine","Cuisine cajun & créole":"Cajun & Creole cuisine",
"Cuisine camerounaise":"Cameroonian cuisine","Cuisine caribéenne":"Caribbean cuisine",
"Cuisine d'Ispahan":"Isfahan cuisine","Cuisine de Mandalay":"Mandalay cuisine",
"Cuisine du Centre":"Central Vietnamese cuisine","Cuisine du Low Country":"Low Country cuisine",
"Cuisine franco-indienne":"Franco-Indian cuisine","Cuisine fusion Pacifique":"Pacific fusion cuisine",
"Cuisine fusion franco-mélanésienne":"Franco-Melanesian fusion",
"Cuisine guaraní":"Guaraní cuisine","Cuisine impériale":"Imperial cuisine",
"Cuisine kéralaise":"Kerala cuisine","Cuisine moghole":"Mughal cuisine",
"Cuisine novoandina":"Novoandina cuisine","Cuisine nubienne":"Nubian cuisine",
"Cuisine rajasthani":"Rajasthani cuisine","Cuisine régionale":"Regional cuisine",
"Cuisine serbe":"Serbian cuisine","Cuisine sichuanaise":"Sichuan cuisine",
"Cuisine sri-lankaise":"Sri Lankan cuisine","Cuisine swahilie":"Swahili cuisine",
"Cuisine tangéroise":"Tangier cuisine","Cuisine togolaise":"Togolese cuisine",
"Cuisine égéenne":"Aegean cuisine","Cuisine équatorienne":"Ecuadorian cuisine",
"Culture Aṉangu":"Aṉangu culture","Culture aborigène":"Aboriginal culture",
"Culture du café bosniaque":"Bosnian coffee culture","Culture hawaïenne":"Hawaiian culture",
"Culture māorie":"Māori culture","Culture naxi & dongba":"Naxi & Dongba culture",
"Culture polynésienne":"Polynesian culture","Culture samoane":"Samoan culture",
"Culture tzotzil & tzeltal":"Tzotzil & Tzeltal culture",
"Cèdres & vallée de Qadisha":"Cedars & Qadisha Valley",
"Cérémonie du café":"Coffee ceremony","Côte Amalfitaine":"Amalfi Coast",
"Daims du parc":"Park deer","Dajti Express":"Dajti Express",
"Delta de l'Okavango":"Okavango Delta","Descente en luge de Monte":"Monte toboggan ride",
"Dhow & coucher de soleil":"Dhow sunset cruise",
"Diamond Head":"Diamond Head","Diriyah & At-Turaif":"Diriyah & At-Turaif",
"Dragon Tiger Temple":"Dragon Tiger Pagodas","Dragons de Komodo":"Komodo dragons",
"Dzongs de Punakha & Paro":"Punakha & Paro dzongs",
"Dégustation de vins":"Wine tasting","Désert & dunes":"Desert & dunes",
"Désert de Gobi":"Gobi Desert","Désert en 4x4 & chameau":"Desert 4x4 & camel rides",
"Eat Street Northshore":"Eat Street Northshore","Edge of the World":"Edge of the World",
"Elephant Rock & désert":"Elephant Rock & desert","Elephanta Caves":"Elephanta Caves",
"Erg Chebbi & dromadaires":"Erg Chebbi & camels","Excursion Etna":"Mount Etna excursion",
"Excursion Rift Valley":"Rift Valley excursion","Excursion Sossusvlei":"Sossusvlei excursion",
"FESPACO":"FESPACO","Face de Bellevarde":"Bellevarde face",
"Failaka Island":"Failaka Island","Famille":"Family",
"Fasil Ghebbi":"Fasil Ghebbi","Fatehpur Sikri":"Fatehpur Sikri",
"Faune amazonienne":"Amazon wildlife","Faune marine":"Marine wildlife",
"Faune subtropicale":"Subtropical wildlife","Felouque sur le Nil":"Nile felucca ride",
"Festival Cervantino":"Cervantino Festival","Festival Dhrupad":"Dhrupad Festival",
"Festival Gnaoua":"Gnaoua Festival","Festival Spoleto":"Spoleto Festival",
"Festival de Cannes":"Cannes Film Festival","Festival de Gand":"Ghent Festival",
"Festival de Ravello":"Ravello Festival","Festival de neige":"Snow festival",
"Festival des éléphants":"Elephant festival","Festivals tshechu":"Tshechu festivals",
"Feu d'artifice du Nouvel An":"New Year's fireworks","Feuillages d'automne":"Fall foliage",
"Field of Light":"Field of Light","Fika & fruits de mer":"Fika & seafood",
"Filets chinois & Fort Cochin":"Chinese fishing nets & Fort Cochin",
"Fish tacos & Gaslamp":"Fish tacos & Gaslamp Quarter",
"Fjords de Musandam":"Musandam fjords","Flamants roses":"Flamingos",
"Forodhani Night Market":"Forodhani Night Market","Fort & Gangaramaya":"Fort & Gangaramaya",
"Fort Jesus":"Fort Jesus","Fort d'Agra":"Agra Fort",
"Fort d'Aqaba":"Aqaba Fort","Fort de Bahreïn":"Bahrain Fort",
"Forteresse de Kalemegdan":"Kalemegdan Fortress","Forêt de Mabira":"Mabira Forest",
"Forêt de nuages":"Cloud forest","Forêt de nuages Mindo":"Mindo cloud forest",
"French Quarter":"French Quarter","Front de mer Corniche":"Corniche waterfront",
"Fruits de mer & marché":"Seafood & market","Fruits de mer & vin":"Seafood & wine",
"Galeries d'art":"Art galleries","Ganvié (Venise d'Afrique)":"Ganvié (Venice of Africa)",
"Gare CFM & Fort":"CFM Station & Fort",
"Gastronomie":"Food & dining","Gastronomie & marché central":"Food & central market",
"Gastronomie & night market":"Food & night market",
"Gastronomie Sud-Ouest":"Southwest French cuisine",
"Gastronomie libanaise":"Lebanese cuisine","Gastronomie mondiale":"World-class dining",
"Gastronomie naïrobienne":"Nairobi food scene","Gastronomie savoyarde":"Savoyard cuisine",
"Gastronomie étoilée":"Michelin-starred dining",
"Gateway of India & Colaba":"Gateway of India & Colaba",
"Geysers & sources chaudes":"Geysers & hot springs",
"Ghats du Gange":"Ganges ghats",
"Giraffe Centre & David Sheldrick":"Giraffe Centre & Sheldrick Trust",
"Glaciers & fjords":"Glaciers & fjords",
"Glenelg & Kangaroo Island":"Glenelg & Kangaroo Island",
"Glover Garden":"Glover Garden","Gnocchi alla sorrentina":"Gnocchi alla sorrentina",
"Gold Coast & Sunshine Coast":"Gold Coast & Sunshine Coast","Golden Mile":"Golden Mile",
"Golestan & musées":"Golestan Palace & museums","Golf":"Golf",
"Gorge de Loussios & Magne":"Loussios Gorge & Mani",
"Gorge de Vintgar":"Vintgar Gorge","Gorge du Saut du Tigre":"Tiger Leaping Gorge",
"Gorilles de Bwindi":"Bwindi gorillas","Gorilles des Virunga":"Virunga gorillas",
"Grace Bay Beach":"Grace Bay Beach","Graceland & Sun Studio":"Graceland & Sun Studio",
"Grand Prix de F1":"F1 Grand Prix","Grand Teton & Yellowstone":"Grand Teton & Yellowstone",
"Grande Barrière de Corail":"Great Barrier Reef",
"Grande Mosquée Sultan Qaboos":"Sultan Qaboos Grand Mosque",
"Gumbalimba Park":"Gumbalimba Park","Haleakalā":"Haleakalā",
"Hegra (Madain Saleh)":"Hegra (Mada'in Salih)",
"Highlands & tribus":"Highlands & tribes","Historic District":"Historic District",
"Historic District & Rainbow Row":"Historic District & Rainbow Row",
"Hluhluwe-Imfolozi":"Hluhluwe-Imfolozi","Hoi An à 30 km":"Hoi An 30 km away",
"Honky tonks & country":"Honky tonks & country","Hot chicken & BBQ":"Hot chicken & BBQ",
"Huaca Pucllana":"Huaca Pucllana",
"Huîtres Marennes-Oléron":"Marennes-Oléron oysters",
"Injera & cuisine éthiopienne":"Injera & Ethiopian cuisine",
"Intramuros & Fort Santiago":"Intramuros & Fort Santiago",
"Island hopping":"Island hopping","Isletas de Granada":"Las Isletas",
"Isola Bella":"Isola Bella","Itchan Kala":"Itchan Kala",
"Jardins botaniques":"Botanical gardens","Jardins botaniques royaux":"Royal Botanic Gardens",
"Jardins de Forodhani":"Forodhani Gardens","Jardins tropicaux":"Tropical gardens",
"Jazz & Bourbon Street":"Jazz & Bourbon Street",
"Jebel Jais & via ferrata":"Jebel Jais & via ferrata",
"Joe's Beerhouse & cuisine":"Joe's Beerhouse & cuisine",
"Kasbah & médina":"Kasbah & medina",
"Kashi Vishwanath & Sarnath":"Kashi Vishwanath & Sarnath",
"Kata Tjuta (Olgas)":"Kata Tjuta (The Olgas)","Kathakali":"Kathakali dance",
"Kayangan & Twin Lagoon":"Kayangan & Twin Lagoon","Khareef (mousson)":"Khareef (monsoon)",
"Kition & Choirokoitia":"Kition & Choirokoitia",
"Kivukoni Fish Market":"Kivukoni Fish Market","Kotor à 30 min":"Kotor 30 min away",
"Kunchi Festival":"Kunchi Festival",
"La Pagode & marché central":"The Pagoda & central market",
"Labadi Beach":"Labadi Beach","Lac & vieille ville UNESCO":"Lake & UNESCO old town",
"Lac & église sur l'île":"Lake & island church","Lac Issyk-Kul":"Issyk-Kul Lake",
"Lac Phewa":"Phewa Lake","Lac Pichola":"Lake Pichola",
"Lac d'Annecy":"Lake Annecy","Lac salé & Hala Sultan Tekke":"Salt lake & Hala Sultan Tekke",
"Lacs & kayak":"Lakes & kayaking","Lagoa da Conceição":"Lagoa da Conceição",
"Lagon UNESCO":"UNESCO lagoon",
"Lake Palace & City Palace":"Lake Palace & City Palace",
"Limoncello & citronniers":"Limoncello & lemon groves",
"Liseberg":"Liseberg","Little Adam's Peak":"Little Adam's Peak",
"Live Music Capital":"Live Music Capital","Live music & Ryman":"Live music & Ryman",
"Lone Pine Koala Sanctuary":"Lone Pine Koala Sanctuary",
"MONA & gastronomie":"MONA & food scene",
"Maboneng & Arts on Main":"Maboneng & Arts on Main",
"Machines de l'île":"Machines of the Isle","Machu Picchu":"Machu Picchu",
"Maisons de thé":"Teahouses","Malbec & bodegas":"Malbec & bodegas",
"Manama & souks":"Manama & souks","Maquis & attiéké":"Maquis bars & attiéké",
"Marché Dantokpa":"Dantokpa Market",
"Marché Forville & bars du Suquet":"Forville Market & Le Suquet bars",
"Marché Maasai":"Maasai Market","Marché central & artisanat":"Central market & crafts",
"Marché des sorcières":"Witches' Market","Marchés de Noël":"Christmas markets",
"Mardi Gras":"Mardi Gras","Marrabenta & vie nocturne":"Marrabenta & nightlife",
"Maulidi Festival":"Maulidi Festival","Mausolée des Samanides":"Samanid Mausoleum",
"Meilleure période":"Best time to visit","Mercado Central":"Mercado Central",
"Milford Sound":"Milford Sound","Mindil Beach Markets":"Mindil Beach Markets",
"Mine de sel préhistorique":"Prehistoric salt mine",
"Mission & Pacific Beach":"Mission & Pacific Beach",
"Mochi de Nakatanidou":"Nakatanidou mochi","Momies & mines":"Mummies & mines",
"Monastery (Ad-Deir)":"Monastery (Ad-Deir)","Mont Cameroun":"Mount Cameroon",
"Mont Damavand":"Mount Damavand","Mont Meru":"Mount Meru",
"Montagne Arc-en-ciel":"Rainbow Mountain",
"Montagne du Dragon de Jade":"Jade Dragon Snow Mountain",
"Montagnes du Tian Shan":"Tian Shan Mountains","Montagnes olympiques":"Olympic Mountains",
"Monteverde & Arenal":"Monteverde & Arenal","Monts Simien":"Simien Mountains",
"Moremi Game Reserve":"Moremi Game Reserve","Mosi-oa-Tunya NP":"Mosi-oa-Tunya NP",
"Mosquée Hassan II":"Hassan II Mosque","Muri Lagoon":"Muri Lagoon",
"Muscadet & vignobles":"Muscadet & vineyards",
"Musée national & Lucy":"National Museum & Lucy",
"Musées & Beco do Batman":"Museums & Beco do Batman",
"Médina de Zanzibar":"Zanzibar medina",
"Mémorial de la paix":"Peace Memorial","Mémorial du génocide":"Genocide Memorial",
"Naadam Festival":"Naadam Festival",
"National Civil Rights Museum":"National Civil Rights Museum",
"Navigation Split-Trogir":"Split-Trogir sailing",
"Navigation île en île":"Island-hopping sailing","Night markets":"Night markets",
"Nike Art Gallery":"Nike Art Gallery","Nine Arches Bridge":"Nine Arches Bridge",
"Nordkette & Golden Roof":"Nordkette & Golden Roof",
"Nouilles de riz de Guilin":"Guilin rice noodles",
"Noël éthiopien (Genna)":"Ethiopian Christmas (Genna)",
"Observation baleines":"Whale watching","Observation ours":"Bear watching",
"Orecchiette & focaccia":"Orecchiette & focaccia",
"Osmize du Carso":"Karst osmize","Ours polaires":"Polar bears",
"Palais Tosh-Hovli":"Tosh-Hovli Palace","Palais royal & colline":"Royal palace & hill",
"Palazzi dei Rolli":"Palazzi dei Rolli","Palio di Siena":"Palio di Siena",
"Pan d'Etosha":"Etosha Pan","Paradise Beach":"Paradise Beach",
"Paradisiers":"Birds of paradise","Parapente Sarangkot":"Sarangkot paragliding",
"Parc Crétacique":"Cretaceous Park","Parc de Nyungwe":"Nyungwe Forest",
"Parc de la Vanoise":"Vanoise National Park",
"Parc national & randonnée":"National park & hiking",
"Parc national de Tacugama":"Tacugama Sanctuary",
"Peinture miniature":"Miniature painting",
"Pelourinho & Olodum":"Pelourinho & Olodum",
"Pescheria & street food":"Fish market & street food",
"Pesto & focaccia di Recco":"Pesto & focaccia di Recco",
"Petra by Night":"Petra by Night","Pettah Market":"Pettah Market",
"Piazza del Campo":"Piazza del Campo","Pier-2 Art Center":"Pier-2 Art Center",
"Piliers Avatar":"Avatar Hallelujah Mountains",
"Piña colada & gastronomie":"Piña colada & gastronomy",
"Place Naqsh-e Jahan":"Naqsh-e Jahan Square","Place Skanderbeg":"Skanderbeg Square",
"Plage & marché aux fétiches":"Beach & fetish market","Plage de Tofo":"Tofo Beach",
"Plages & Croisette":"Beaches & La Croisette","Plages & chiringuitos":"Beaches & chiringuitos",
"Plages & lagons":"Beaches & lagoons","Plages & mangroves":"Beaches & mangroves",
"Plages & promenade":"Beaches & promenade",
"Plages & sel de Sečovlje":"Beaches & Sečovlje salt pans",
"Plages & vieille ville":"Beaches & old town","Plages & wadis":"Beaches & wadis",
"Plages Diani & Nyali":"Diani & Nyali beaches",
"Plages Itapuã & Porto da Barra":"Itapuã & Porto da Barra beaches",
"Plages My Khe & An Bang":"My Khe & An Bang beaches",
"Plages d'Inhaca":"Inhaca Island beaches",
"Plages de Folly & Sullivan's":"Folly & Sullivan's Island beaches",
"Plages de Grand-Bassam":"Grand-Bassam beaches",
"Plages de Ha'apai":"Ha'apai beaches","Plages de Kigamboni":"Kigamboni beaches",
"Plages de Lalomanu":"Lalomanu beaches","Plages de Nungwi":"Nungwi beaches",
"Plages de Nungwi & Kendwa":"Nungwi & Kendwa beaches",
"Plages de Santa Maria":"Santa Maria beaches",
"Plages de la mer Rouge":"Red Sea beaches",
"Plages de la péninsule":"Peninsula beaches",
"Plages de Čiovo":"Čiovo beaches","Plages du Salento":"Salento beaches",
"Plages désertes":"Deserted beaches","Plages lacustres":"Lakeside beaches",
"Plages noires & lagons":"Black sand beaches & lagoons",
"Plages sauvages":"Wild beaches","Plages volcaniques":"Volcanic beaches",
"Plantations de café":"Coffee plantations","Plantations de thé":"Tea plantations",
"Plantations de thé Doi Mae Salong":"Doi Mae Salong tea plantations",
"Plateau & cathédrale":"Plateau & cathedral",
"Plaza de Armas & Qorikancha":"Plaza de Armas & Qorikancha",
"Plongée & perles":"Diving & pearl heritage","Plongée & requins":"Diving & sharks",
"Plongée & snorkel":"Diving & snorkeling","Plongée Kimbe Bay":"Kimbe Bay diving",
"Plongée Manta Point":"Manta Point diving","Plongée du rivage":"Shore diving",
"Plongée mer Rouge":"Red Sea diving","Plongée raies manta":"Manta ray diving",
"Plov & bazars":"Plov & bazaars",
"Plus grand district historique US":"Largest US historic district",
"Poisson cru au lait de coco":"Raw fish in coconut milk",
"Polignano a Mare":"Polignano a Mare","Pont & saut à l'élastique":"Bridge & bungee jumping",
"Pont Neuf & gorge du Tajo":"Puente Nuevo & El Tajo gorge",
"Ponts historiques":"Historic bridges","Ponts suspendus & zip-line":"Hanging bridges & zip-line",
"Powell's & culture indie":"Powell's & indie culture","Prambanan":"Prambanan",
"Primitivo & pasticciotto":"Primitivo wine & pasticciotto","Puerto Banús":"Puerto Banús",
"Péninsule de Banks":"Banks Peninsula","Quad & 4x4":"Quad & 4x4",
"Quartier Art déco":"Art Deco district","Quartier colonial":"Colonial quarter",
"Quartier français":"French Quarter","Quartier musulman":"Muslim Quarter",
"Quetzal resplendissant":"Resplendent quetzal",
"Rafting Río Mendoza":"Río Mendoza rafting","Rafting Zambèze":"Zambezi rafting",
"Rafting source du Nil":"Nile source rafting",
"Rainforest & cascades":"Rainforest & waterfalls",
"Rambla & Ciudad Vieja":"Rambla & Ciudad Vieja",
"Ramen miso & crabe":"Miso ramen & crab",
"Randonnée Abuna Yosef":"Abuna Yosef hiking","Randonnée volcanique":"Volcanic hiking",
"Randonnée vosgienne":"Vosges hiking","Red Rocks":"Red Rocks",
"Redwoods & VTT":"Redwoods & mountain biking","Registan":"Registan",
"Remparts de Xi'an":"Xi'an city walls","Rencontre des eaux":"Meeting of the Waters",
"Requins-baleines":"Whale sharks","Rhinocéros noirs":"Black rhinos",
"River Walk":"River Walk","Rivière des Parfums":"Perfume River",
"Rizières de Banaue":"Banaue Rice Terraces","Rocky Mountains":"Rocky Mountains",
"Rolex & street food":"Rolex wraps & street food",
"Rose Garden & Forest Park":"Rose Garden & Forest Park",
"Route de Hana":"Road to Hana","Route de l'encens":"Frankincense route",
"Route de la Mort VTT":"Death Road mountain biking",
"Route de la Mort à VTT":"Death Road mountain biking",
"Route des Pêches":"Beach Route","Route des Sept Lacs":"Route of the Seven Lakes",
"Route des vins":"Wine route","Rues pavées & boutiques":"Cobblestone streets & shops",
"Ruines coloniales":"Colonial ruins","Ruines de Sumhuram":"Sumhuram ruins",
"Ruines de Vijayanagara":"Vijayanagara ruins",
"Réserve de flamants":"Flamingo reserve","SS President Coolidge":"SS President Coolidge wreck",
"Safari Chobe":"Chobe safari","Safari Etosha":"Etosha safari",
"Safari Nairobi National Park":"Nairobi National Park safari",
"Safari Pilanesberg":"Pilanesberg safari",
"Safari Serengeti & Ngorongoro":"Serengeti & Ngorongoro safari",
"Sagre & fêtes":"Sagre & festivals","Sakura tardifs":"Late cherry blossoms",
"Salamanca Market":"Salamanca Market","Salines de Pedra de Lume":"Pedra de Lume salt pans",
"Sanctuaire de paresseux":"Sloth sanctuary","Saut du Naghol":"Naghol land diving",
"Saut à l'élastique":"Bungee jumping","Savannah hantée":"Haunted Savannah",
"Scenic drives":"Scenic drives","Sea Dance Festival":"Sea Dance Festival",
"Semana Santa":"Semana Santa","Semnoz & Tournette":"Semnoz & Tournette",
"Sentier des Dieux":"Path of the Gods","Serra de Tramuntana":"Serra de Tramuntana",
"Shah-i-Zinda":"Shah-i-Zinda","Shwedagon Pagoda":"Shwedagon Pagoda",
"Sing-sing Goroka Show":"Goroka Show","Sites antiques":"Ancient sites",
"Sites de tournage":"Film locations","Ski Espace Killy":"Espace Killy skiing",
"Ski Jackson Hole":"Jackson Hole skiing","Ski Niseko & Furano":"Niseko & Furano skiing",
"Ski Remarkables & Coronet Peak":"Remarkables & Coronet Peak skiing",
"Ski Shymbulak":"Shymbulak skiing","Ski alpin":"Alpine skiing",
"Ski à 2h":"Skiing 2h away","Skywalk & 5 Fingers":"Skywalk & 5 Fingers",
"Snake River rafting":"Snake River rafting",
"Snorkel & récifs":"Snorkeling & reefs","Snorkel & tortues":"Snorkeling & turtles",
"Soleil de minuit":"Midnight sun","Sonoran Desert":"Sonoran Desert",
"Souks & Mubarakiya":"Souks & Mubarakiya","Souks de Muttrah":"Muttrah souks",
"Source du Nil":"Source of the Nile","South Bank Parklands":"South Bank Parklands",
"Speed boat sous les chutes":"Speedboat under the falls",
"Spice Tour":"Spice Tour","Squares & chênes":"Squares & live oaks",
"Squares & mousse espagnole":"Squares & Spanish moss",
"Steppes & vie nomade":"Steppes & nomadic life",
"Stone Town & portes sculptées":"Stone Town & carved doors",
"Street art & Blloku":"Street art & Blloku",
"Street art & renaissance":"Street art & renaissance",
"Street food & Makola Market":"Street food & Makola Market",
"Street food & jollof":"Street food & jollof rice",
"Street food Binondo":"Binondo street food","Street food Malioboro":"Malioboro street food",
"Street food de Chowpatty":"Chowpatty street food","Street food sacrée":"Sacred street food",
"Sunset cruise Zambèze":"Zambezi sunset cruise",
"Surf & kitesurf":"Surf & kitesurf","Surf & plages":"Surf & beaches",
"Surf North Shore":"North Shore surfing","Surf Teahupo'o":"Teahupo'o surfing",
"Taj Mahal au lever":"Taj Mahal at sunrise","Taliesin West":"Taliesin West",
"Tam Coc & Trang An":"Tam Coc & Trang An","Tannat & bodegas":"Tannat & bodegas",
"Taormina Film Fest":"Taormina Film Fest","Tapis & artisanat":"Carpets & crafts",
"Tarkwa Bay & Elegushi":"Tarkwa Bay & Elegushi",
"Tavče gravče & kebapi":"Tavče gravče & kebapi",
"Te Papa & côte sauvage":"Te Papa & wild coast",
"Teatro Amazonas":"Teatro Amazonas",
"Temple Blanc (Wat Rong Khun)":"White Temple (Wat Rong Khun)",
"Temple de Philae":"Philae Temple","Temple de la Dent":"Temple of the Tooth",
"Temples & campagne":"Temples & countryside","Temples de Bagan":"Bagan temples",
"Terrasse de l'Infini":"Terrace of Infinity","Terrasses de Longji":"Longji Rice Terraces",
"Tex-Mex & Market Square":"Tex-Mex & Market Square","The Alamo":"The Alamo",
"Thé & ananas":"Tea & pineapple","Théâtre gréco-romain":"Greco-Roman theater",
"Tiger's Nest (Taktsang)":"Tiger's Nest (Taktsang)",
"Timkat (Épiphanie)":"Timkat (Epiphany)",
"To Sua Ocean Trench":"To Sua Ocean Trench","Tobago Cays":"Tobago Cays",
"Todai-ji":"Todai-ji","Togoville & lac Togo":"Togoville & Lake Togo",
"Tombes des rois du Buganda":"Buganda Royal Tombs","Tortues marines":"Sea turtles",
"Tour de l'île":"Island tour","Tours de Koweït":"Kuwait Towers",
"Train Kandy-Ella":"Kandy-Ella train",
"Trek Annapurna Base Camp":"Annapurna Base Camp trek",
"Treks himalayens":"Himalayan treks","Triangle d'Or":"Golden Triangle",
"Trésor (Al-Khazneh)":"Treasury (Al-Khazneh)",
"Tunnel de l'espoir":"Tunnel of Hope","U Bein Bridge":"U Bein Bridge",
"Uluru au lever et coucher":"Uluru sunrise & sunset","VTT & trail":"Mountain biking & trail",
"Val d'Orcia":"Val d'Orcia","Vallée Sacrée":"Sacred Valley",
"Via Ferrata El Tajo":"El Tajo via ferrata",
"Vida noturna & samba":"Nightlife & samba",
"Vie nocturne & splavovi":"Nightlife & splavovi",
"Vieille ville & Hofburg":"Old town & Hofburg",
"Vieille ville & Palais de l'Île":"Old town & Palais de l'Île",
"Vieille ville naxi":"Naxi old town","Vieille ville swahilie":"Swahili old town",
"Vieille ville vénitienne":"Venetian old town","Viejo San Juan":"Old San Juan",
"Vieux bazar ottoman":"Old Ottoman bazaar","Vieux-Port & voile":"Old Port & sailing",
"Vigan & côte d'Ilocos":"Vigan & Ilocos coast","Village & lac alpin":"Village & alpine lake",
"Villages à colombages":"Half-timbered villages","Ville littéraire":"Literary city",
"Ville rose & Capitole":"Pink city & Capitole",
"Vin de Madère & levadas":"Madeira wine & levadas","Vins & ensaïmada":"Wine & ensaïmada",
"Vins de Némée":"Nemea wines","Vins de l'Etna":"Etna wines",
"Visite Airbus":"Airbus factory tour","Voie verte du lac":"Lakeside greenway",
"Voile & île en île":"Sailing & island hopping",
"Vol en montgolfière":"Hot air balloon ride","Vol scenic delta":"Scenic delta flight",
"Volcan Yasur":"Yasur Volcano","Volcans & Rangitoto":"Volcanoes & Rangitoto",
"Volcans Mayon & Taal":"Mayon & Taal volcanoes","Volcán Masaya":"Masaya Volcano",
"Volcán Poás & Irazú":"Poás & Irazú volcanoes","Volcán de Fuego":"Fuego Volcano",
"Vortex & bien-être":"Vortex & wellness","Voyage à Nantes":"Voyage à Nantes",
"Vue Annapurna & Machhapuchhre":"Annapurna & Machapuchare views",
"Vélo dans les ruines":"Cycling through ruins","Wahiba Sands":"Wahiba Sands",
"Waiheke Island":"Waiheke Island","Waikiki Beach":"Waikiki Beach",
"West Bay Beach":"West Bay Beach","Weta Workshop & cinéma":"Weta Workshop & film",
"Whitehaven Beach":"Whitehaven Beach","Windsurf & kite":"Windsurf & kite",
"Windsurf & kitesurf":"Windsurf & kitesurf","Windsurf Lac Bay":"Lac Bay windsurfing",
"Yangshuo & vélo":"Yangshuo & cycling","Yourtes & vie nomade":"Yurts & nomadic life",
"Zoo de San Diego":"San Diego Zoo","Églises byzantines":"Byzantine churches",
"Églises rupestres":"Rock-hewn churches","Épave du Zenobia":"Zenobia wreck dive",
"Épaves japonaises":"Japanese WWII wrecks",
"Île de Bongoyo":"Bongoyo Island","Île de Ré":"Île de Ré",
"Île des Pins":"Isle of Pines","Îles & lagons":"Islands & lagoons",
"Îles de Batangas":"Batangas islands","Îles de Lérins":"Lérins Islands",
"Îles du Rosaire":"Rosario Islands","Ñeembucú & Chaco":"Ñeembucú & Chaco",
"Bien-être & détente":"Wellness & relaxation",
}

# ── TEXT TRANSLATION ──
# Phrases sorted longest-first to avoid partial matches
PHRASES = [
    ("Toute l'année","Year-round"),("toute l'année","year-round"),
    ("score climatique optimal","optimal climate score"),
    ("ensoleillement maximal","maximum sunshine"),("ensoleillement optimal","optimal sunshine"),
    ("h d'ensoleillement/jour","h of daily sunshine"),("h d'ensoleillement","h of sunshine"),
    ("jours de pluie","rainy days"),("jours secs","dry days"),
    ("en arrière-plan","in the background"),("au cœur de","in the heart of"),
    ("Hors vacances scolaires","Outside school holidays"),
    ("Hors haute saison","Off peak season"),("Hors saison","Off-season"),
    ("haute saison","peak season"),("basse saison","low season"),
    ("saison sèche","dry season"),("saison des pluies","rainy season"),
    ("saison humide","wet season"),("saison cyclonique","cyclone season"),
    ("chaleur modérée","moderate heat"),("chaleur extrême","extreme heat"),
    ("chaleur intense","intense heat"),("chaleur torride","scorching heat"),
    ("températures douces","mild temperatures"),("températures idéales","ideal temperatures"),
    ("températures agréables","pleasant temperatures"),("températures supportables","bearable temperatures"),
    ("conditions optimales","optimal conditions"),("conditions idéales","ideal conditions"),
    ("conditions parfaites","perfect conditions"),("meilleures conditions","best conditions"),
    ("meilleure visibilité","best visibility"),("meilleure période","best time"),
    ("climat idéal","ideal climate"),("temps sec","dry weather"),
    ("moins de monde","fewer crowds"),("moins de touristes","fewer tourists"),
    ("moins de foule","fewer crowds"),("affluence moindre","fewer crowds"),
    ("prix réduits","lower prices"),("prix plus bas","lower prices"),
    ("prix hébergement","accommodation prices"),("tarifs réduits","reduced rates"),
    ("prix bas","low prices"),
    ("vue panoramique","panoramic view"),("vue imprenable","breathtaking view"),
    ("patrimoine mondial","World Heritage"),("classé UNESCO","UNESCO-listed"),
    ("site UNESCO","UNESCO site"),
    ("unique au monde","unique in the world"),
    ("l'un des plus beaux","one of the most beautiful"),
    ("l'une des plus belles","one of the most beautiful"),
    ("l'un des plus grands","one of the largest"),
    ("l'une des plus grandes","one of the largest"),
    ("parmi les plus beaux","among the most beautiful"),
    ("plus ancienne","oldest"),("plus ancien","oldest"),
    ("plus grand","largest"),("plus grande","largest"),
    ("plus beau","most beautiful"),("plus belle","most beautiful"),
    ("coucher de soleil","sunset"),("lever du soleil","sunrise"),
    ("lever de soleil","sunrise"),("au lever","at sunrise"),("au coucher","at sunset"),
    ("lumière dorée","golden light"),("lumière douce","soft light"),
    ("luminosité idéale","ideal light"),
    ("vieille ville","old town"),("centre historique","historic center"),
    ("centre-ville","city center"),("front de mer","waterfront"),
    ("bord de mer","seaside"),("en bord de mer","by the sea"),
    ("arrière-pays","hinterland"),("en altitude","at altitude"),
    ("forêt tropicale","tropical forest"),("forêt de nuages","cloud forest"),
    ("récif corallien","coral reef"),
    ("rizières en terrasses","terraced rice paddies"),("rizières","rice paddies"),
    ("sources chaudes","hot springs"),("source chaude","hot spring"),
    ("eau turquoise","turquoise water"),("eau claire","clear water"),
    ("eau chaude","warm water"),("mer calme","calm sea"),("mer chaude","warm sea"),
    ("sable blanc","white sand"),("sable noir","black sand"),("sable fin","fine sand"),
    ("marché nocturne","night market"),("marché couvert","covered market"),
    ("marchés couverts","covered markets"),("marchés locaux","local markets"),
    ("produits locaux","local produce"),("spécialités locales","local specialties"),
    ("cuisine locale","local cuisine"),("gastronomie locale","local gastronomy"),
    ("plats traditionnels","traditional dishes"),
    ("fruits de mer","seafood"),("poisson grillé","grilled fish"),
    ("poisson frais","fresh fish"),("fruits tropicaux","tropical fruits"),
    ("produits frais","fresh produce"),("fruits frais","fresh fruits"),
    ("street food","street food"),("vie nocturne","nightlife"),
    ("en plein air","outdoors"),("à proximité","nearby"),
    ("vol direct","direct flight"),("en ferry","by ferry"),
    ("en bateau","by boat"),("en pirogue","by pirogue"),
    ("en felouque","by felucca"),("en 4x4","by 4x4"),
    ("à vélo","by bike"),("à pied","on foot"),
    ("hors Ramadan","outside Ramadan"),("hors mousson","outside monsoon"),
    ("avant la mousson","before monsoon"),("après la mousson","after monsoon"),
    ("peu de pluie","little rain"),("faible pluviométrie","low rainfall"),
    ("risque cyclonique","cyclone risk"),
    ("sentiers praticables","accessible trails"),("sentiers secs","dry trails"),
    ("pistes cyclables","bike paths"),
    ("musée national","national museum"),("palais royal","royal palace"),
    ("art contemporain","contemporary art"),
    ("classée au patrimoine","heritage-listed"),
    ("à l'aube","at dawn"),("au crépuscule","at dusk"),
    ("tôt le matin","early morning"),
    ("visite guidée","guided tour"),("visite tôt le matin","early morning visit"),
    ("visite tôt","early visit"),
    ("communauté grimpeurs active","active climbing community"),
    ("communauté","community"),
    ("randonnée","hiking"),("plongée","diving"),("snorkeling","snorkeling"),
    ("baignade","swimming"),("escalade","climbing"),("parapente","paragliding"),
    ("kayak","kayaking"),("canyoning","canyoning"),("kitesurf","kitesurfing"),
    ("windsurf","windsurfing"),
    ("surf mythique","legendary surfing"),("surf","surfing"),
    ("incontournable","must-see"),("emblématique","iconic"),
    ("mythique","legendary"),("spectaculaire","spectacular"),
    ("accessible","accessible"),("gratuit","free"),("entrée libre","free entry"),
    ("depuis le sommet","from the summit"),("au sommet","at the summit"),
    ("trésor caché","hidden gem"),("joyau","jewel"),("perle","gem"),
]

# Word-level translations for remaining French
WORDS = [
    # Articles & prepositions
    (" et "," and "),(" ou "," or "),(" mais "," but "),(" avec "," with "),
    (" sans "," without "),(" pour "," for "),(" dans "," in "),(" vers "," towards "),
    (" sur "," on "),(" sous "," under "),(" entre "," between "),(" parmi "," among "),
    (" depuis "," from "),(" environ "," about "),(" autour de "," around "),
    (" plus de "," more than "),(" moins de "," less than "),(" jusqu'à "," up to "),
    (" du "," of "),(" des "," of the "),(" de la "," of the "),
    (" de l'"," of "),(" d'"," of "),
    (" le plus "," the most "),(" la plus "," the most "),
    (" les plus "," the most "),(" le "," the "),(" la "," the "),
    (" les "," the "),(" un "," a "),(" une "," a "),
    # Verbs / adjectives
    (" blanc "," white "),(" blanche "," white "),(" noir "," black "),(" noire "," black "),
    (" grand "," great "),(" grande "," great "),(" petit "," small "),(" petite "," small "),
    (" ancienne "," ancient "),(" ancien "," ancient "),
    (" magnifique "," magnificent "),(" superbe "," superb "),
    (" célèbre "," famous "),(" typique "," typical "),
    (" locale "," local "),(" local "," local "),
    (" frais "," fresh "),(" fraîche "," fresh "),
    (" vivant "," lively "),(" animé "," lively "),(" animée "," lively "),
    (" sauvage "," wild "),(" tropicale "," tropical "),(" tropical "," tropical "),
    (" coloniale "," colonial "),(" colonial "," colonial "),
    (" historique "," historic "),(" médiéval "," medieval "),(" médiévale "," medieval "),
    (" traditionnelle "," traditional "),(" traditionnel "," traditional "),
    (" artisanale "," artisanal "),(" artisanal "," artisanal "),
    # Nouns
    (" ville "," city "),(" île "," island "),(" îles "," islands "),
    (" plage "," beach "),(" plages "," beaches "),
    (" lac "," lake "),(" lacs "," lakes "),
    (" montagne "," mountain "),(" montagnes "," mountains "),
    (" volcan "," volcano "),(" volcans "," volcanoes "),
    (" colline "," hill "),(" collines "," hills "),
    (" falaise "," cliff "),(" falaises "," cliffs "),
    (" cascade "," waterfall "),(" cascades "," waterfalls "),
    (" grotte "," cave "),(" grottes "," caves "),
    (" dunes "," dunes "),(" oasis "," oasis "),
    (" lagon "," lagoon "),(" lagons "," lagoons "),
    (" forêt "," forest "),(" jungle "," jungle "),
    (" mangrove "," mangrove "),(" savane "," savanna "),
    (" désert "," desert "),(" cratère "," crater "),
    (" gorge "," gorge "),(" vallée "," valley "),
    (" jardin "," garden "),(" jardins "," gardens "),
    (" parc "," park "),
    (" quartier "," quarter "),(" quartiers "," quarters "),
    (" musée "," museum "),(" musées "," museums "),
    (" palais "," palace "),(" temple "," temple "),(" temples "," temples "),
    (" cathédrale "," cathedral "),(" église "," church "),(" églises "," churches "),
    (" mosquée "," mosque "),(" mosquées "," mosques "),
    (" château "," castle "),(" fort "," fort "),(" forteresse "," fortress "),
    (" remparts "," ramparts "),(" murailles "," walls "),
    (" marché "," market "),(" marchés "," markets "),
    (" port "," port "),(" ports "," ports "),
    (" restaurants "," restaurants "),(" hôtels "," hotels "),
    (" hébergement "," accommodation "),
    (" boutiques "," shops "),(" magasins "," stores "),
    (" monde "," world "),
    (" soleil "," sun "),(" pluie "," rain "),(" vent "," wind "),
    (" neige "," snow "),(" chaleur "," heat "),(" brouillard "," fog "),
    (" sable "," sand "),(" pierre "," stone "),(" bois "," wood "),
    (" rue "," street "),(" rues "," streets "),
    (" pont "," bridge "),(" ponts "," bridges "),
    (" couleurs "," colors "),(" lumière "," light "),
    (" vue "," view "),(" vues "," views "),(" panorama "," panorama "),
    (" nuit "," night "),(" soir "," evening "),(" matin "," morning "),
    (" après-midi "," afternoon "),
    (" siècle "," century "),(" histoire "," history "),
    (" artisanat "," crafts "),(" céramique "," ceramics "),(" soie "," silk "),
    (" épices "," spices "),(" thé "," tea "),(" café "," coffee "),
    (" chocolat "," chocolate "),(" fromage "," cheese "),
    (" vin "," wine "),(" vins "," wines "),(" bière "," beer "),
    (" poisson "," fish "),(" crabe "," crab "),(" huîtres "," oysters "),
    (" viande "," meat "),(" riz "," rice "),(" pain "," bread "),
    (" dégustations "," tastings "),(" dégustation "," tasting "),
    (" habitants "," locals "),(" hospitalité "," hospitality "),
    (" immensité "," vastness "),(" beauté "," beauty "),
    (" traditions "," traditions "),(" tradition "," tradition "),
    (" fête "," festival "),(" fêtes "," festivals "),
    (" spectacle "," show "),(" spectacles "," shows "),
    (" danse "," dance "),(" danses "," dances "),
    (" musique "," music "),(" classique "," classical "),
    (" galeries "," galleries "),
    (" tortues "," turtles "),(" baleines "," whales "),
    (" dauphins "," dolphins "),(" requins "," sharks "),
    (" oiseaux "," birds "),(" flamants "," flamingos "),
    (" gorilles "," gorillas "),(" singes "," monkeys "),
    (" crocodiles "," crocodiles "),(" hippopotames "," hippos "),
    (" éléphants "," elephants "),(" lions "," lions "),
    (" animaux "," animals "),(" faune "," wildlife "),
    (" flore "," flora "),(" coraux "," corals "),(" corail "," coral "),
    (" pandas "," pandas "),
    (" plantes "," plants "),(" fleurs "," flowers "),
    (" croisière "," cruise "),(" excursion "," excursion "),
    (" aventure "," adventure "),
    (" ponte "," nesting "),
    (" apéro "," sundowners "),
    (" sentier "," trail "),(" sentiers "," trails "),
    (" piste "," track "),(" pistes "," tracks "),
    (" chemin "," path "),
    (" réserve "," reserve "),
    (" plantation "," plantation "),(" plantations "," plantations "),
    (" vignoble "," vineyard "),(" vignobles "," vineyards "),
    (" verger "," orchard "),(" vergers "," orchards "),
    (" prix "," prices "),(" coût "," cost "),
]

# Month translations
MONTHS = {
    "Jan":"Jan","Fév":"Feb","Mars":"Mar","Avr":"Apr","Mai":"May","Juin":"Jun",
    "Juil":"Jul","Août":"Aug","Sep":"Sep","Oct":"Oct","Nov":"Nov","Déc":"Dec",
    "Janvier":"January","Février":"February","Mars":"March","Avril":"April",
    "Mai":"May","Juin":"June","Juillet":"July","Août":"August",
    "Septembre":"September","Octobre":"October","Novembre":"November","Décembre":"December",
}

def translate_text(txt):
    t = txt
    # Months (longest first)
    for fr, en in sorted(MONTHS.items(), key=lambda x: -len(x[0])):
        t = re.sub(r'\b' + re.escape(fr) + r'\b', en, t)
    # Phrases (longest first)
    for fr, en in sorted(PHRASES, key=lambda x: -len(x[0])):
        t = t.replace(fr, en)
    # Words
    for fr, en in WORDS:
        t = t.replace(fr, en)
    return t

# ── MAIN ──
with open('data/cards.csv', encoding='utf-8-sig') as f:
    all_fr = list(csv.DictReader(f))
with open('data/cards_en.csv', encoding='utf-8-sig') as f:
    all_en = list(csv.DictReader(f))

good_en = all_en[:1446]
new_fr = all_fr[1446:]
print(f"Original EN: {len(good_en)} | FR to translate: {len(new_fr)}")

new_en = []
missing_titles = set()
for c in new_fr:
    title_en = T.get(c['titre'])
    if not title_en:
        missing_titles.add(c['titre'])
        title_en = c['titre']
    text_en = translate_text(c['texte'])
    new_en.append({'slug':c['slug'],'icon':c['icon'],'title':title_en,'text':text_en})

if missing_titles:
    print(f"\n⚠️  {len(missing_titles)} unmapped titles:")
    for t in sorted(missing_titles): print(f"  - {t}")

# Write
with open('data/cards_en.csv', 'w', encoding='utf-8-sig', newline='') as f:
    w = csv.DictWriter(f, fieldnames=['slug','icon','title','text'])
    w.writeheader()
    for c in good_en: w.writerow(c)
    for c in new_en: w.writerow(c)

print(f"\n✅ {len(good_en)+len(new_en)} EN cards written")

# Quality check
print("\n── Samples ──")
for slug in ['annecy','toulouse','cusco','honolulu','mongolie','cannes','petra','sapporo']:
    en_cards = [c for c in new_en if c['slug']==slug]
    if en_cards:
        c = en_cards[0]
        print(f"  {slug}: {c['title']} | {c['text'][:80]}")

# Check for residual French
import string
fr_words = {'dans','avec','pour','mais','sur','sous','entre','vers','depuis','très',
            'aussi','cette','sont','tous','tout','comme','peut','être','avoir','fait',
            'bien','même','aucun','peu','après','avant','chaque','plusieurs','quelques',
            'seulement','environ','pendant','toujours','parfois','souvent','jamais',
            'encore','déjà','assez','beaucoup','trop','ici','ailleurs',
            'où','quand','comment','pourquoi','ainsi','donc','puis','puis',
            'hors','selon','grâce','malgré','sauf',
            'beau','bel','belle','belles','beaux','bon','bonne','bons',
            'nouvelle','nouveau','nouveaux','nouvelles',
            'jour','jours','mois','semaine','année','années',
            'premier','première','dernier','dernière','seul','seule',
            'nombreux','nombreuses','différents','différentes',
            'possible','idéal','idéale','parfait','parfaite',
            'populaire','célèbre','connu','connue','fameux','fameuse',
            'millénaires','millénaire','séculaire','séculaires',
}
residual = []
for c in new_en:
    words = set(re.findall(r'[a-zàâäéèêëïîôùûüç]+', c['text'].lower()))
    found = words & fr_words
    if found:
        residual.append((c['slug'], c['title'], found, c['text'][:60]))

if residual:
    print(f"\n⚠️  {len(residual)} cards with possible French residue:")
    for slug, title, words, text in residual[:20]:
        print(f"  {slug} ({title}): {words} | {text}")
