#!/usr/bin/env python3
"""Translate cards.csv → cards_en.csv with proper phrase-level translations."""
import csv, re

# ── TITLE TRANSLATIONS ──────────────────────────────────────────────────────
TITRE_EN = {
    "Alcázar & cathédrale": "Alcázar & Cathedral",
    "Angkor": "Angkor",
    "Antiquité & Vatican": "Ancient Rome & Vatican",
    "Architecture": "Architecture",
    "Architecture & culture": "Architecture & Culture",
    "Architecture portugaise": "Portuguese Architecture",
    "Archéologie": "Archaeology",
    "Art Basel & culture": "Art Basel & Culture",
    "Arthur's Seat": "Arthur's Seat",
    "Atlas & désert": "Atlas Mountains & Desert",
    "Aurores boréales": "Northern Lights",
    "Automne (foliage)": "Autumn Foliage",
    "Baignade & crique": "Swimming & Coves",
    "Baleines & dauphins": "Whales & Dolphins",
    "Baleines & pingouins": "Whales & Penguins",
    "Baleines à bosse": "Humpback Whales",
    "Beaujolais & vignes": "Beaujolais & Vineyards",
    "Bière & gastronomie": "Beer & Food",
    "Bouillabaisse & marché": "Bouillabaisse & Market",
    "Budget": "Budget",
    "Budget serré": "Tight Budget",
    "Cafés viennois": "Viennese Coffeehouses",
    "Calanques & mer": "Calanques & Sea",
    "Calas & plages": "Coves & Beaches",
    "Caminito del Rey": "Caminito del Rey",
    "Carnaval": "Carnival",
    "Casino & vie nocturne": "Casino & Nightlife",
    "Chianti & vignobles": "Chianti & Vineyards",
    "Château & Royal Mile": "Castle & Royal Mile",
    "Château & vieille ville": "Castle & Old Town",
    "Château de Santa Bárbara": "Santa Bárbara Castle",
    "Collines toscanes": "Tuscan Hills",
    "Comino & grottes": "Comino & Caves",
    "Corcovado & Pain de Sucre": "Corcovado & Sugarloaf",
    "Corfu Trail": "Corfu Trail",
    "Coucher de soleil": "Sunset",
    "Coucher de soleil Oia": "Oia Sunset",
    "Criques & plages": "Coves & Beaches",
    "Croisière Cyclades": "Cyclades Cruise",
    "Culture & Riviera": "Culture & Riviera",
    "Culture & fado": "Culture & Fado",
    "Culture & mosquées": "Culture & Mosques",
    "Culture & musées": "Culture & Museums",
    "Culture & patrimoine": "Culture & Heritage",
    "Culture & temples": "Culture & Temples",
    "Culture khmère": "Khmer Culture",
    "Culture médiévale": "Medieval Culture",
    "Cyclisme": "Cycling",
    "Côtes & mégalithes": "Coast & Megaliths",
    "Dauphins & baleines": "Dolphins & Whales",
    "Excursion bateau": "Boat Trip",
    "Excursions": "Day Trips",
    "Famille": "Family",
    "Faune sauvage": "Wildlife",
    "Feria de Abril": "Feria de Abril",
    "Festival d'Édimbourg": "Edinburgh Festival",
    "Festival des tulipes": "Tulip Festival",
    "Festivals": "Festivals",
    "Festivals celtiques": "Celtic Festivals",
    "Fête & clubs": "Parties & Clubs",
    "Fête des Lumières": "Festival of Lights",
    "Fêtes & festivals": "Parties & Festivals",
    "Fêtes & vie nocturne": "Parties & Nightlife",
    "GR20": "GR20",
    "Game of Thrones": "Game of Thrones",
    "Gardens by the Bay": "Gardens by the Bay",
    "Gastronomie": "Food & Dining",
    "Gastronomie & tapas": "Food & Tapas",
    "Gastronomie & vins": "Food & Wine",
    "Gastronomie bouchons": "Bouchon Restaurants",
    "Gastronomie hawker": "Hawker Food",
    "Gastronomie marine": "Seafood",
    "Gastronomie niçoise": "Niçoise Cuisine",
    "Gaudí & architecture": "Gaudí & Architecture",
    "Geysers & géothermie": "Geysers & Geothermal",
    "Golf": "Golf",
    "Gorges de Samaria": "Samaria Gorge",
    "Gorges du Verdon": "Verdon Gorge",
    "Grand Bazar & Bosphore": "Grand Bazaar & Bosphorus",
    "Grand Prix F1": "F1 Grand Prix",
    "Grotte Bleue": "Blue Grotto",
    "Haleakalā & nature": "Haleakalā & Nature",
    "Histoire & musées": "History & Museums",
    "Hiver ensoleillé": "Sunny Winter",
    "Hollywood & studios": "Hollywood & Studios",
    "Ipanema & Copacabana": "Ipanema & Copacabana",
    "Jardins & flores": "Gardens & Flowers",
    "Kayak & canyoning": "Kayaking & Canyoning",
    "Kayak & grottes": "Kayaking & Caves",
    "Koyo (feuillage automne)": "Kōyō (Autumn Leaves)",
    "Las Fallas": "Las Fallas",
    "Lavande": "Lavender",
    "Levadas": "Levadas",
    "Librairie Lello & culture": "Lello Bookshop & Culture",
    "Marathon de Rome": "Rome Marathon",
    "Marchés de Noël": "Christmas Markets",
    "Minoen & archéo": "Minoan & Archaeology",
    "Montagne Mosor": "Mosor Mountain",
    "Monuments & culture": "Landmarks & Culture",
    "Moulins & coucher de soleil": "Windmills & Sunset",
    "Musique & culture": "Music & Culture",
    "Musique & samba": "Music & Samba",
    "Musique classique": "Classical Music",
    "Musées": "Museums",
    "Musées & culture": "Museums & Culture",
    "Médina & souks": "Medina & Souks",
    "Navagio & plages": "Navagio & Beaches",
    "Noël & marchés": "Christmas & Markets",
    "Noël à NYC": "Christmas in NYC",
    "Nuraghe & archéo": "Nuraghe & Archaeology",
    "Observation cétacés": "Whale Watching",
    "Observation des baleines": "Whale Watching",
    "Oenotourisme": "Wine Tourism",
    "Paella & gastronomie": "Paella & Food",
    "Palais & musées": "Palaces & Museums",
    "Palais de Dioclétien": "Diocletian's Palace",
    "Parc fluvial & vélo": "Riverside Park & Cycling",
    "Parcs & Tiergarten": "Parks & Tiergarten",
    "Parcs & architecture": "Parks & Architecture",
    "Parcs royaux": "Royal Parks",
    "Petit budget": "Budget Travel",
    "Photographie": "Photography",
    "Picasso & culture": "Picasso & Culture",
    "Piton de la Fournaise": "Piton de la Fournaise",
    "Plage": "Beach",
    "Plage & Caraïbes": "Beach & Caribbean",
    "Plage & baignade": "Beach & Swimming",
    "Plage & calanques": "Beach & Calanques",
    "Plage & calas": "Beach & Coves",
    "Plage & cenotes": "Beach & Cenotes",
    "Plage & dunes": "Beach & Dunes",
    "Plage & falaises": "Beach & Cliffs",
    "Plage & granit": "Beach & Granite",
    "Plage & kitesurf": "Beach & Kitesurfing",
    "Plage & lagon": "Beach & Lagoon",
    "Plage & piscine": "Beach & Pool",
    "Plage & snorkeling": "Beach & Snorkelling",
    "Plage & surf": "Beach & Surfing",
    "Plage & îles": "Beach & Islands",
    "Plage An Bang": "An Bang Beach",
    "Plage Costa del Sol": "Costa del Sol Beach",
    "Plage Pacifique": "Pacific Beach",
    "Plages & Varadero": "Beaches & Varadero",
    "Plongée": "Diving",
    "Plongée & cenotes": "Diving & Cenotes",
    "Plongée & cénotes": "Diving & Cenotes",
    "Plongée & excursion Délos": "Diving & Delos Trip",
    "Plongée & grottes": "Diving & Caves",
    "Plongée & snorkeling": "Diving & Snorkelling",
    "Plongée & surf": "Diving & Surfing",
    "Plongée & îles Phi Phi": "Diving & Phi Phi Islands",
    "Porto & caves à vin": "Porto & Wine Cellars",
    "Printemps parisien": "Parisian Spring",
    "Printemps romain": "Roman Spring",
    "Promenade & plage": "Promenade & Beach",
    "Pubs & gastronomie": "Pubs & Food",
    "Pubs & whisky": "Pubs & Whisky",
    "Quartiers culturels": "Cultural Quarters",
    "Randonnée": "Hiking",
    "Randonnée & Teide": "Hiking & Teide",
    "Randonnée & faune": "Hiking & Wildlife",
    "Randonnée Anti-Atlas": "Anti-Atlas Hiking",
    "Randonnée Calanques": "Calanques Hiking",
    "Randonnée Cirques": "Cirques Hiking",
    "Randonnée Douro": "Douro Hiking",
    "Randonnée GR34": "GR34 Coastal Trail",
    "Randonnée Luberon": "Luberon Hiking",
    "Remparts & vieille ville": "Ramparts & Old Town",
    "Renaissance & musées": "Renaissance & Museums",
    "Requins-baleines": "Whale Sharks",
    "Retraite / yoga": "Retreat / Yoga",
    "Rhum & gastronomie": "Rum & Food",
    "Route des vins": "Wine Route",
    "Ruines mayas": "Mayan Ruins",
    "Saison sèche": "Dry Season",
    "Sakura": "Sakura",
    "Scène musicale": "Music Scene",
    "Selvaggio Blu": "Selvaggio Blu",
    "Sentier des Dieux": "Path of the Gods",
    "Sentier du Littoral": "Coastal Path",
    "Serra de Tramuntana": "Serra de Tramuntana",
    "Shopping": "Shopping",
    "Shopping & dolce vita": "Shopping & Dolce Vita",
    "Shopping & luxe": "Shopping & Luxury",
    "Sierra de Aitana": "Sierra de Aitana",
    "Sintra & Arrábida": "Sintra & Arrábida",
    "Sites historiques": "Historical Sites",
    "Sites mayas": "Mayan Sites",
    "Soirées & clubs": "Nightlife & Clubs",
    "Sources chaudes": "Hot Springs",
    "Spa & détente": "Spa & Relaxation",
    "Spa & lune de miel": "Spa & Honeymoon",
    "Stone Town": "Stone Town",
    "Street food": "Street Food",
    "Surf": "Surfing",
    "Surf & Atlantique": "Surf & Atlantic",
    "Surf & Jardin": "Surf & Garden",
    "Surf & bodyboard": "Surf & Bodyboard",
    "Surf & lagon": "Surf & Lagoon",
    "Surf & plage": "Surf & Beach",
    "Séville la nuit": "Seville by Night",
    "Table Mountain": "Table Mountain",
    "Tango": "Tango",
    "Teide & randonnée": "Teide & Hiking",
    "Temples & culture": "Temples & Culture",
    "Temples & palais": "Temples & Palaces",
    "Théâtre & West End": "Theatre & West End",
    "Tigre & estancias": "Tigre & Estancias",
    "Tonlé Sap": "Tonlé Sap",
    "Tortues Caretta": "Caretta Turtles",
    "Tortues géantes": "Giant Tortoises",
    "Tortues marines": "Sea Turtles",
    "Tramways & azulejos": "Trams & Azulejos",
    "Trek Himalaya": "Himalayan Trek",
    "Trek volcans": "Volcano Trek",
    "Tulipes & Keukenhof": "Tulips & Keukenhof",
    "VTT & randonnée": "Mountain Biking & Hiking",
    "Vallée des papillons": "Valley of Butterflies",
    "Venise secrète": "Secret Venice",
    "Via Krupp & randonnée": "Via Krupp & Hiking",
    "Vie nocturne": "Nightlife",
    "Vieille ville UNESCO": "UNESCO Old Town",
    "Vieille ville médiévale": "Medieval Old Town",
    "Vieux-Lyon Renaissance": "Renaissance Old Lyon",
    "Vignes & rosé": "Vineyards & Rosé",
    "Vignobles": "Vineyards",
    "Villages perchés & antiques": "Hilltop & Ancient Villages",
    "Vins & gastronomie": "Wine & Food",
    "Vins & tapas": "Wine & Tapas",
    "Vins de lave": "Volcanic Wines",
    "Voile & sports nautiques": "Sailing & Water Sports",
    "Voitures & architecture": "Cars & Architecture",
    "Volcans & Timanfaya": "Volcanos & Timanfaya",
    "Vélo & Garonne": "Cycling & Garonne",
    "Vélo & canaux": "Cycling & Canals",
    "Vélo & randonnée": "Cycling & Hiking",
    "Vélo & villages": "Cycling & Villages",
    "Wildlife & Chitwan": "Wildlife & Chitwan",
    "Yoga & bien-être": "Yoga & Wellness",
    "Écotourisme & forêts": "Ecotourism & Rainforest",
    "Îles & croisières": "Islands & Cruises",
}

# ── PERIOD TRANSLATIONS ─────────────────────────────────────────────────────
PERIOD_MAP = {
    "Toute l'année": "Year-round",
    "Juillet-août": "July–August",
    "Juillet-septembre": "July–September",
    "Juin-septembre": "June–September",
    "Juin-août": "June–August",
    "Juin ou septembre": "June or September",
    "Juin ou septembre-octobre": "June or September–October",
    "Juin": "June",
    "Mai-septembre": "May–September",
    "Mai ou septembre-octobre": "May or September–October",
    "Mai ou septembre": "May or September",
    "Mai ou octobre": "May or October",
    "Mai-octobre": "May–October",
    "Avril-septembre": "April–September",
    "Avril-octobre": "April–October",
    "Avril-mai ou octobre": "April–May or October",
    "Avril-mai": "April–May",
    "Avril-juin": "April–June",
    "Avril ou octobre": "April or October",
    "Mars-mai ou octobre": "March–May or October",
    "Mars-mai": "March–May",
    "Mars-avril": "March–April",
    "Mars ou novembre": "March or November",
    "Mars-novembre": "March–November",
    "Mars-octobre": "March–October",
    "Février-mai": "February–May",
    "Février-mars": "February–March",
    "Février-avril": "February–April",
    "Janvier-mars": "January–March",
    "Janvier-avril": "January–April",
    "Novembre-mars": "November–March",
    "Novembre-février": "November–February",
    "Novembre-avril": "November–April",
    "Octobre-avril": "October–April",
    "Octobre-mars": "October–March",
    "Octobre-novembre": "October–November",
    "Octobre-décembre": "October–December",
    "Septembre-novembre": "September–November",
    "Septembre-octobre": "September–October",
    "Décembre-mars": "December–March",
    "Décembre-février": "December–February",
    "Décembre-avril": "December–April",
    "Mi-mars à mi-mai": "Mid-March to mid-May",
    "Mi-juin à mi-juillet": "Mid-June to mid-July",
    "Août": "August",
    "Septembre": "September",
    "Octobre": "October",
    "Novembre": "November",
    "Décembre": "December",
    "Janvier": "January",
    "Février": "February",
    "Mars": "March",
    "Avril": "April",
    "Mai": "May",
    "Juillet": "July",
    "Mai ou octobre-novembre": "May or October–November",
    "Mai ou juin": "May or June",
    "Juin-octobre": "June–October",
    "Juin-juillet": "June–July",
    "Avril-août": "April–August",
    "Avril-juin ou septembre": "April–June or September",
    "Mai-juin ou septembre-octobre": "May–June or September–October",
    "Mai-juin ou septembre": "May–June or September",
    "Octobre ou mai": "October or May",
    "Mai-août": "May–August",
    "Juillet-octobre": "July–October",
    "Septembre-décembre": "September–December",
    "Fin mars-début avril": "Late March–early April",
    "Novembre-décembre": "November–December",
}

# ── DESCRIPTION TRANSLATIONS (full phrases after the "—") ──────────────────
DESC_EN = {
    # Agadir
    "Agadir a l'une des meilleures conditions de surf du Maroc, vent régulier.": "one of Morocco's best surf spots, consistent wind.",
    "3 golfs de référence, températures idéales 20-25°C.": "3 top-rated courses, ideal temperatures of 20–25°C.",
    "massif de l'Anti-Atlas accessible depuis Agadir, villages berbères.": "Anti-Atlas mountains accessible from Agadir, Berber villages.",
    "mer chaude, plage sécurisée, moins de chaleur extrême.": "warm sea, safe beach, less extreme heat.",
    "hors saison estivale, prix hébergement -30%.": "off summer season, accommodation prices -30%.",
    "poissons grillés au port, tajines, huile d'argan.": "grilled fish at the port, tagines, argan oil.",
    # Algarve
    "Praia da Marinha, Ponta da Piedade, Meia Praia.": "Praia da Marinha, Ponta da Piedade, Meia Praia.",
    "Sagres et Arrifana pour les swells atlantiques.": "Sagres and Arrifana for Atlantic swells.",
    "mer calme, grottes de Benagil accessibles.": "calm sea, Benagil caves accessible.",
    "mer 20-22°C, plages sécurisées.": "sea 20–22°C, safe beaches.",
    "météo correcte, prix -40%.": "decent weather, prices -40%.",
    # Alicante
    "Playa de San Juan, eaux calmes et chaudes (26°C).": "Playa de San Juan, calm warm waters (26°C).",
    "visite sans chaleur, vue panoramique sur la ville.": "visit without the heat, panoramic city views.",
    "DO Alicante, tapas, riz à la bande noire.": "DO Alicante wines, tapas, arroz a banda.",
    "mer 25°C, plages familiales, moins de monde.": "sea 25°C, family beaches, fewer crowds.",
    "températures agréables, prix -30% vs juillet.": "pleasant temperatures, prices -30% vs July.",
    "randonnées à 30 min d'Alicante.": "hiking trails 30 min from Alicante.",
    # Amalfi
    "plages de Positano et Maiori, mer 24-26°C.": "Positano and Maiori beaches, sea 24–26°C.",
    "randonnée Agerola-Positano.": "Agerola-to-Positano trail.",
    "Capri, Grotte bleue depuis Amalfi.": "Capri, Blue Grotto from Amalfi.",
    "routes praticables, foule raisonnable.": "roads manageable, reasonable crowds.",
    "lumière d'or, terrasses vides.": "golden light, empty terraces.",
    # Amsterdam
    "7 millions de fleurs, Keukenhof ouvert seulement 8 semaines.": "7 million flowers, Keukenhof open only 8 weeks.",
    "réseau cyclable unique, croisières canaux.": "world-class cycling network, canal cruises.",
    "Rijksmuseum, Van Gogh, Anne Frank sans files en hiver.": "Rijksmuseum, Van Gogh, Anne Frank House without winter queues.",
    "King's Day (27 avril), Pride, festivals open-air.": "King's Day (Apr 27), Pride, outdoor festivals.",
    "NEMO Science Museum, Artis zoo, jours très longs.": "NEMO Science Museum, Artis Zoo, very long days.",
    "hôtels souvent moins chers, musées accessibles, ambiance locale.": "hotels often cheaper, museums accessible, local atmosphere.",
    # Bali
    "côte sud (Seminyak, Canggu). Saison surf côte ouest : avril-octobre.": "south coast (Seminyak, Canggu). West coast surf season: April–October.",
    "avant/après la haute saison, moins de monde.": "before/after peak season, fewer crowds.",
    "Agung et Batur dans les meilleures conditions de visibilité.": "Agung and Batur in best visibility conditions.",
    "saison sèche, activités aquatiques, mais prix élevés.": "dry season, water activities, but higher prices.",
    "moins de monde, tarifs inférieurs, bonne météo.": "fewer crowds, lower prices, good weather.",
    # Barcelone
    "Barceloneta, Bogatell, eau 24°C.": "Barceloneta, Bogatell, water 24°C.",
    "Sagrada Família, Park Güell sans files interminables.": "Sagrada Família, Park Güell without endless queues.",
    "tapas, cava, marché de la Boqueria.": "tapas, cava, La Boqueria market.",
    "plage, Tibidabo, Aquàrium, Zoo.": "beach, Tibidabo, Aquarium, Zoo.",
    "hôtels souvent moins chers, sans foule estivale.": "hotels often cheaper, no summer crowds.",
    "Primavera Sound, Sónar, Festa Major de Gràcia.": "Primavera Sound, Sónar, Festa Major de Gràcia.",
    # Berlin
    "Pergamon, DDR Museum, Mémorial de l'Holocauste.": "Pergamon, DDR Museum, Holocaust Memorial.",
    "Tiergarten, Treptower Park, baignades en lac.": "Tiergarten, Treptower Park, lake swimming.",
    "festivals open-air, clubs, scène électro mondiale.": "outdoor festivals, clubs, world-class electronic music scene.",
    "LEGOLAND Discovery Centre, Zoo de Berlin, jours longs.": "LEGOLAND Discovery Centre, Berlin Zoo, long days.",
    "Markthalle Neun, brasseries artisanales, currywurst.": "Markthalle Neun, craft breweries, currywurst.",
    "hôtels très accessibles, marchés de Noël, musées gratuits.": "very affordable hotels, Christmas markets, free museums.",
    # Bali (suite)
    "mer chaude, plages familiales, moins de monde.": "warm sea, family beaches, fewer crowds.",
    # Bordeaux
    "Place de la Bourse, CAPC, Cité du Vin.": "Place de la Bourse, CAPC, Cité du Vin.",
    "Dune du Pilat, côte Atlantique à 1h, Base sous-marine.": "Dune du Pilat, Atlantic coast 1h away, Submarine Base.",
    "vendanges, Route des Châteaux, Saint-Émilion en fête.": "harvest season, Château Route, Saint-Émilion festivities.",
    "bistrots, marchés, pâtisseries, vin naturel.": "bistros, markets, pastries, natural wine.",
    "pistes cyclables, croisières fluviales.": "cycle paths, river cruises.",
    "hôtels accessibles, gastronomie toute l'année.": "affordable hotels, year-round food scene.",
    # Bretagne
    "Côte de Granit Rose, alignements de Carnac, Pointe du Raz.": "Pink Granite Coast, Carnac alignments, Pointe du Raz.",
    "plages sécurisées, crêperies, châteaux médiévaux.": "safe beaches, crêperies, medieval castles.",
    "Festival Interceltique de Lorient, Fest Noz.": "Lorient Celtic Festival, Fest Noz.",
    "homard, galettes, huîtres, cidre breton.": "lobster, galettes, oysters, Breton cider.",
    "sentier côtier de 2000 km, vues spectaculaires.": "2,000 km coastal path, spectacular views.",
    "météo acceptable, -30-40% sur les hébergements.": "acceptable weather, -30-40% on accommodation.",
    # Buenos Aires
    "milongas, cours, Caminito à La Boca.": "milongas, lessons, Caminito in La Boca.",
    "pampa verte, Delta du Tigre à 1h.": "green pampa, Tigre Delta 1h away.",
    "parrilla, malbec, facturas, dulce de leche.": "parrilla, Malbec, facturas, dulce de leche.",
    "été austral, jardins botaniques, Reserva Ecológica.": "southern summer, botanical gardens, Reserva Ecológica.",
    "hiver brésilien, moins de touristes, tarifs corrects.": "southern winter, fewer tourists, reasonable prices.",
    # Cancun
    "Playa Paraíso, cenotes cristallins, sans sargasses.": "Playa Paraíso, crystal-clear cenotes, no sargassum.",
    "Chichén Itzá, Tulum, Cobá sans chaleur écrasante.": "Chichén Itzá, Tulum, Cobá without extreme heat.",
    "cenotes de la Riviera Maya, récif mésoaméricain.": "Riviera Maya cenotes, Mesoamerican reef.",
    "mer calme, parcs aquatiques, Xcaret, Xel-Há.": "calm sea, water parks, Xcaret, Xel-Há.",
    "avant les ouragans, prix -35%, plages quasi désertes.": "before hurricane season, prices -35%, nearly empty beaches.",
    # Cap Vert (incl Fuerteventura, etc)
    "Corralejo, Sotavento, vent régulier idéal pour sports nautiques.": "Corralejo, Sotavento, consistent wind ideal for water sports.",
    "Jandía, dunes de Corralejo, températures douces.": "Jandía, Corralejo dunes, mild temperatures.",
    "relief volcanique, routes peu fréquentées.": "volcanic landscape, uncrowded roads.",
    "houle atlantique, spots de Majanicho et El Hierro.": "Atlantic swell, Majanicho and El Hierro spots.",
    "soleil garanti, hors saison, prix bas. Idéal avec enfants.": "guaranteed sun, off-season, low prices. Ideal with children.",
    # Capri
    "Bagni di Tiberio, Marina Piccola.": "Bagni di Tiberio, Marina Piccola.",
    "sentiers côtiers, vue Faraglioni.": "coastal trails, Faraglioni views.",
    "Via Camerelle, boutiques de luxe.": "Via Camerelle, luxury boutiques.",
    "lumière d'or sur les Faraglioni, île déserte.": "golden light on the Faraglioni, deserted island.",
    "matin uniquement, accès en barque.": "mornings only, accessible by rowing boat.",
    # Corfou
    "Paleokastritsa, Glyfada, eaux cristallines.": "Paleokastritsa, Glyfada, crystal-clear waters.",
    "UNESCO vivant, architecture vénitienne sans chaleur extrême.": "living UNESCO site, Venetian architecture without extreme heat.",
    "mer accessible, chaleur agréable, moins de monde.": "swimmable sea, pleasant warmth, fewer crowds.",
    "220 km nord-sud, villages intérieurs authentiques.": "220 km north-to-south, authentic inland villages.",
    "sofrito, bianco, spitiko krasi, oliviers millénaires.": "sofrito, bianco, spitiko krasi, ancient olive trees.",
    "ferrys et hébergements -40%.": "ferries and accommodation -40%.",
    # Corse
    "Bonifacio, Porto, Rondinara, eaux turquoise de Méditerranée.": "Bonifacio, Porto, Rondinara, turquoise Mediterranean waters.",
    "le trek le plus difficile d'Europe, 180 km, 2 semaines.": "Europe's toughest trek, 180 km, 2 weeks.",
    "gorges de Spelunca, canyons du Tavignano.": "Spelunca gorges, Tavignano canyons.",
    "charcuterie AOP, fromages, vins de Patrimonio.": "PDO charcuterie, cheeses, Patrimonio wines.",
    "mer encore agréable, prix hébergements -35%.": "sea still pleasant, accommodation prices -35%.",
    # Costa Rica
    "Tamarindo, Manuel Antonio, mer calme et ciel bleu.": "Tamarindo, Manuel Antonio, calm sea and blue skies.",
    "Monteverde, Arenal, faune exceptionnelle en saison sèche.": "Monteverde, Arenal, exceptional wildlife in dry season.",
    "jaguars, toucans, tortues marines sur la côte Caraïbe.": "jaguars, toucans, sea turtles on the Caribbean coast.",
    "mer calme, activités nature, resorts familiaux.": "calm sea, nature activities, family resorts.",
    "début de saison verte, prix -30%, plages moins fréquentées.": "start of green season, prices -30%, quieter beaches.",
    # Crète
    "Elafonisi (sable rose), Balos, Vai (palmiers).": "Elafonisi (pink sand), Balos, Vai (palm trees).",
    "Cnossos, Phaistos sans chaleur.": "Knossos, Phaistos without the heat.",
    "randonnée dans les gorges, températures idéales.": "gorge hiking, ideal temperatures.",
    "mer chaude (23-26°C), chaleur supportable, moins de monde.": "warm sea (23–26°C), bearable heat, fewer crowds.",
    "fin de saison, prix -40%, criques désertes, météo estivale.": "end of season, prices -40%, deserted coves, summer weather.",
    # Cuba
    "Floridita, Bodeguita del Medio, daïquiri.": "Floridita, Bodeguita del Medio, daïquiri.",
    "saison sèche, promenades en Chevrolet des années 50.": "dry season, rides in 1950s Chevrolets.",
    "son cubano, salsa, cabarets, Casa de la Música.": "son cubano, salsa, cabarets, Casa de la Música.",
    "Varadero à 2h, eaux turquoise des Caraïbes.": "Varadero 2h away, turquoise Caribbean waters.",
    "hors saison, prix -50%, ville authentique.": "off-season, prices -50%, authentic city.",
    # Dubrovnik
    "UNESCO vivant, appartements dans les murs antiques.": "living UNESCO site, apartments within the ancient walls.",
    "UNESCO, remparts sans foule.": "UNESCO site, ramparts without crowds.",
    "lieux de tournage accessibles sans files.": "filming locations accessible without queues.",
    "foule modérée, lumière parfaite, vent acceptable.": "moderate crowds, perfect light, manageable wind.",
    "hôtels souvent moins chers, ville animée toute l'année.": "hotels often cheaper, lively city year-round.",
    # Dubaï
    "Jumeirah Beach, Palm. Eau à 22-26°C.": "Jumeirah Beach, The Palm. Water 22–26°C.",
    "Burj Khalifa, Dubai Museum, Frame.": "Burj Khalifa, Dubai Museum, Dubai Frame.",
    "Aquaventure, safari désert, ski indoor.": "Aquaventure, desert safari, indoor skiing.",
    "Dubai Shopping Festival. Décembre — ambiance festive.": "Dubai Shopping Festival. December — festive atmosphere.",
    "chaleur agréable, piscines encore utilisables.": "pleasant warmth, pools still usable.",
    # Edimbourg
    "château d'Édimbourg, Holyrood, Scotch whisky.": "Edinburgh Castle, Holyrood, Scotch whisky.",
    "le plus grand festival des arts au monde, 4000 spectacles.": "world's largest arts festival, 4,000 shows.",
    "volcan éteint au cœur de la ville, vue panoramique.": "extinct volcano in the city centre, panoramic views.",
    "Scotch Whisky Experience, pub crawl historique.": "Scotch Whisky Experience, historic pub crawl.",
    "Dynamic Earth, zoo d'Édimbourg, Fringe festival.": "Dynamic Earth, Edinburgh Zoo, Fringe festival.",
    "basse saison touristique, hôtels -30%, musées moins fréquentés.": "tourist low season, hotels -30%, less crowded museums.",
    # Florence
    "Offices, David, sans chaleur ni files interminables.": "Uffizi, David, without heat or endless queues.",
    "vendanges, route du Chianti, dégustations.": "harvest, Chianti wine route, tastings.",
    "bistecca fiorentina, lampredotto, gelato, mercato centrale.": "bistecca fiorentina, lampredotto, gelato, Mercato Centrale.",
    "Fiesole, San Miniato, vues sur Florence.": "Fiesole, San Miniato, views over Florence.",
    "glycines Villa Borghese, azalées Spanish Steps, températures idéales.": "wisteria at Villa Borghese, azaleas at Spanish Steps, ideal temperatures.",
    "Boboli, Palazzo Vecchio Kids, moins chaud.": "Boboli, Palazzo Vecchio Kids, less heat.",
    # Goa
    "Anjuna, Palolem, Vagator — saison sèche et mer calme.": "Anjuna, Palolem, Vagator — dry season and calm sea.",
    "Old Goa, Basilique Bom Jesus, visite sans humidité.": "Old Goa, Basilica of Bom Jesus, visiting without humidity.",
    "Noël, Nouvel An, ambiance animée sur South Goa.": "Christmas, New Year's, lively atmosphere in South Goa.",
    "mer calme, hôtels familiaux, températures idéales.": "calm sea, family hotels, ideal temperatures.",
    "mousson, hébergements -40%, moins de touristes.": "monsoon, accommodation -40%, fewer tourists.",
    # Gran Canaria
    "Maspalomas et ses dunes, Playa del Inglés.": "Maspalomas and its dunes, Playa del Inglés.",
    "Roque Nublo, Caldera de Tejeda, relief spectaculaire.": "Roque Nublo, Caldera de Tejeda, spectacular landscape.",
    "El Cabrón (dive site de référence), Pozo Izquierdo (windsurf).": "El Cabrón (top dive site), Pozo Izquierdo (windsurfing).",
    "Palmitos Park, Aqua Sur, plages protégées.": "Palmitos Park, Aqua Sur, sheltered beaches.",
    "hôtels accessibles, 300 jours de soleil/an.": "affordable hotels, 300 days of sunshine/year.",
    # Hoi An
    "lanternes, maisons marchandes, ambiance douce.": "lanterns, merchant houses, gentle atmosphere.",
    "saison sèche, activités artisanales, lanterne workshop.": "dry season, craft activities, lantern workshop.",
    "cao lầu, bánh mì, White Rose, cours de cuisine.": "cao lầu, bánh mì, White Rose, cooking classes.",
    "rizières, villages de pêcheurs, mangroves.": "rice paddies, fishing villages, mangroves.",
    "saison des pluies, tarifs -40%, guesthouses locales.": "rainy season, prices -40%, local guesthouses.",
    # Ibiza
    "Amnesia, Ushuaïa, Pacha. Saison ouverte de juin à septembre.": "Amnesia, Ushuaïa, Pacha. Club season June to September.",
    "Cala Conta, Cala Bassa cristallines et tranquilles.": "Cala Conta, Cala Bassa — crystal-clear and peaceful.",
    "eaux cristallines, calas encore accessibles sans foule.": "crystal-clear waters, coves still accessible without crowds.",
    "avant la haute saison clubs, plages abordables, prix raisonnables.": "before club peak season, affordable beaches, reasonable prices.",
    "saison clubs terminée, prix -40%, calas vides, météo estivale.": "club season over, prices -40%, empty coves, summer weather.",
    # Islande
    "Golden Circle, Blue Lagoon, geysers de Geysir.": "Golden Circle, Blue Lagoon, Geysir geysers.",
    "nuits longues, KP index > 2, Þingvellir idéal.": "long nights, KP index > 2, Þingvellir ideal.",
    "Sky Lagoon, Reykjadalur, sources naturelles.": "Sky Lagoon, Reykjadalur, natural hot springs.",
    "soleil de minuit, Perlan, balades en Islande verte.": "midnight sun, Perlan, strolls through green Iceland.",
    "vols accessibles, aurores boréales, Blue Lagoon moins cher.": "affordable flights, northern lights, cheaper Blue Lagoon.",
    "baleines à bosse dans la baie de Faxaflói.": "humpback whales in Faxaflói bay.",
    # Istanbul
    "Sainte-Sophie, Mosquée Bleue, Topkapi sans chaleur.": "Hagia Sophia, Blue Mosque, Topkapi without the heat.",
    "des millions de tulipes dans les parcs d'Istanbul.": "millions of tulips in Istanbul's parks.",
    "shopping, croisière Bosphore, marchés de Kadıköy.": "shopping, Bosphorus cruise, Kadıköy markets.",
    "croisières, Miniaturk, aquarium.": "cruises, Miniaturk, aquarium.",
    "meze, kebabs, baklava, et une scène restaurant mondiale.": "meze, kebabs, baklava, and a world-class restaurant scene.",
    "hors saison, sites sans file.": "off-season, sites without queues.",
    # Keys (Florida)
    "John Pennekamp Coral Reef, meilleure visibilité.": "John Pennekamp Coral Reef, best visibility.",
    "vacances scolaires américaines, hébergements familiaux, plages abritées.": "US school holidays, family accommodation, sheltered beaches.",
    "tarifs basse saison, plages désertes, soleil garanti.": "low-season rates, deserted beaches, guaranteed sunshine.",
    # Lanzarote
    "Playa Papagayo, Famara (surf), températures constantes 20-28°C.": "Playa Papagayo, Famara (surf), steady 20–28°C temperatures.",
    "Parc national de Timanfaya, paysages lunaires uniques.": "Timanfaya National Park, unique lunar landscapes.",
    "vignes en creux (zocos) contre le vent, vins uniques.": "sunken vines (zocos) sheltered from wind, unique wines.",
    "Jameos del Agua, Cueva de los Verdes, plages sécurisées.": "Jameos del Agua, Cueva de los Verdes, safe beaches.",
    "hôtels souvent moins chers, soleil quasi permanent.": "hotels often cheaper, near-constant sunshine.",
    # La Réunion
    "Cilaos, Mafate, Salazie, Piton des Neiges.": "Cilaos, Mafate, Salazie, Piton des Neiges.",
    "l'un des volcans les plus actifs du monde, lave accessible.": "one of the world's most active volcanoes, accessible lava flows.",
    "Saint-Leu, lagon protégé, vagues de compétition.": "Saint-Leu, protected lagoon, competition-level waves.",
    "lagon, cascades, sentiers accessibles.": "lagoon, waterfalls, accessible trails.",
    "hors saison, prix -40%, pas de cyclones.": "off-season, prices -40%, no cyclones.",
    # Londres
    "British Museum, Tate, V&A, tous gratuits.": "British Museum, Tate, V&A, all free.",
    "Hyde Park, Regent's Park, Kew Gardens en fleurs.": "Hyde Park, Regent's Park, Kew Gardens in bloom.",
    "meilleure scène théâtrale au monde.": "the world's best theatre scene.",
    "Borough Market, pubs historiques, Brick Lane.": "Borough Market, historic pubs, Brick Lane.",
    "Tower Bridge, Natural History Museum, London Eye.": "Tower Bridge, Natural History Museum, London Eye.",
    "hôtels souvent moins chers, musées gratuits, marchés de Noël.": "hotels often cheaper, free museums, Christmas markets.",
    # Lyon
    "UNESCO, traboules, colline de Fourvière.": "UNESCO site, traboules, Fourvière hill.",
    "capitale mondiale de la gastronomie, bouchons lyonnais.": "world capital of gastronomy, Lyonnais bouchons.",
    "4 nuits de projections monumentales, 2 millions de visiteurs.": "4 nights of monumental projections, 2 million visitors.",
    "Parc de la Tête d'Or, Confluences, musée Miniature.": "Parc de la Tête d'Or, Confluences, Miniature Museum.",
    "Beaujolais Nouveau, route des vignobles.": "Beaujolais Nouveau, vineyard route.",
    "hôtels accessibles, gastronomie reste abordable.": "affordable hotels, food scene remains budget-friendly.",
    # Madère
    "2500 km de sentiers longeant les canaux d'irrigation.": "2,500 km of trails along irrigation canals.",
    "Jardim do Mar et Paul do Mar, spot mondial de surf.": "Jardim do Mar and Paul do Mar, world-class surf spot.",
    "Monte Palace, Jardim Botânico, anthuriums en fleurs.": "Monte Palace, Botanical Garden, anthuriums in bloom.",
    "piscines naturelles de Seixal, toboggans en osier de Monte.": "Seixal natural pools, Monte wicker toboggans.",
    "vin de Madère AOC, espada, poncha.": "Madeira DOC wine, espada, poncha.",
    "hors saison touristique, hébergements accessibles.": "tourist off-season, affordable accommodation.",
    # Majorque
    "eaux cristallines, Parc national des Kornati.": "crystal-clear waters, Kornati National Park.",
    "Majorque est LA destination cyclisme pro d'Europe. Températures idéales (15-25°C).": "Mallorca is THE pro cycling destination in Europe. Ideal temperatures (15–25°C).",
    "UNESCO, sentiers praticables, températures idéales.": "UNESCO site, walkable trails, ideal temperatures.",
    "mer accessible (côte toscane), chaleur supportable.": "swimmable sea (Tuscan coast), bearable heat.",
    "avant/après la chaleur, sentiers praticables.": "before/after the heat, walkable trails.",
    # Malaga
    "Playa de la Malagueta, La Cala, 300 jours de soleil/an.": "Playa de la Malagueta, La Cala, 300 days of sunshine/year.",
    "Musée Picasso, Centre Pompidou Málaga, Musée Carmen Thyssen.": "Picasso Museum, Centre Pompidou Málaga, Carmen Thyssen Museum.",
    "vin doux de Málaga, Atarazanas, El Pimpi.": "sweet Málaga wine, Atarazanas market, El Pimpi.",
    "températures idéales, Isla Mágica, parcs accessibles.": "ideal temperatures, Isla Mágica, accessible parks.",
    "hôtels accessibles, musées moins fréquentés.": "affordable hotels, less crowded museums.",
    "18 km, ouvert mai-oct par temps sec.": "18 km, open May–Oct in dry weather.",
    # Malte
    "Baie Bleue, Grotte bleue de Malte.": "Blue Bay, Blue Grotto of Malta.",
    "Mdina, Valletta, hypogée de Hal Saflieni.": "Mdina, Valletta, Ħal Saflieni Hypogeum.",
    "UNESCO, Palais des Grands Maîtres des Chevaliers.": "UNESCO site, Grand Master's Palace.",
    "Baie de Saint-George, Baie Bleue, Gozo.": "St George's Bay, Blue Bay, Gozo.",
    "eaux cristallines, épaves de la Seconde Guerre mondiale.": "crystal-clear waters, WWII wrecks.",
    "hiver doux, prix minimum, tranquillité absolue.": "mild winter, lowest prices, absolute tranquillity.",
    # Marrakech
    "chaleur agréable, éclairage automnal sur les riads.": "pleasant warmth, autumn light on the riads.",
    "riads moins chers, ambiance intime.": "cheaper riads, intimate atmosphere.",
    "cols accessibles (Toubkal), randonnées confortables.": "accessible passes (Toubkal), comfortable hiking.",
    "le Maroc en hiver est sous-coté : 18°C, riads à -40%.": "winter Morocco is underrated: 18°C, riads at -40%.",
    # Marseille
    "Calanque de Sugiton, Morgiou, Sormiou.": "Calanque de Sugiton, Morgiou, Sormiou.",
    "kayak, randonnées Calanques, eaux turquoise.": "kayaking, Calanques hiking, turquoise waters.",
    "MuCEM, Villa Méditerranée, Vieux-Port animé.": "MuCEM, Villa Méditerranée, lively Vieux-Port.",
    "marché des Capucins, poissons frais, bouillabaisse authentique.": "Capucins market, fresh fish, authentic bouillabaisse.",
    "plages familiales, Parc national des Calanques.": "family beaches, Calanques National Park.",
    "hôtels souvent moins chers, musées accessibles, ventes privées.": "hotels often cheaper, museums accessible, private sales.",
    # Maui
    "Kaanapali, Wailea, houle calme côté sud, idéal baignade.": "Kaanapali, Wailea, calm surf on south side, ideal for swimming.",
    "migration des baleines dans le Chenal de Maui.": "whale migration in the Maui Channel.",
    "Molokini Crater, tortues vertes, eaux cristallines.": "Molokini Crater, green turtles, crystal-clear waters.",
    "lever de soleil au sommet, parc national accessible.": "sunrise at the summit, accessible national park.",
    "haute saison scolaire, eau calme, activités variées.": "school peak season, calm water, varied activities.",
    # Maurice
    "Belle Mare, Le Morne, Flic en Flac.": "Belle Mare, Le Morne, Flic en Flac.",
    "dauphins spinner sur la côte ouest.": "spinner dolphins off the west coast.",
    "bungalows sur l'eau, couchers de soleil.": "overwater bungalows, sunsets.",
    "alizés doux, mer calme, resorts familiaux.": "gentle trade winds, calm sea, family resorts.",
    "saison des pluies, hébergements -40%.": "rainy season, accommodation -40%.",
    # Miami
    "South Beach, Miami Beach, mer chaude et soleil.": "South Beach, Miami Beach, warm sea and sunshine.",
    "Art Basel Miami Beach, Wynwood Walls, Design District animé.": "Art Basel Miami Beach, Wynwood Walls, lively Design District.",
    "Everglades, Zoo de Miami, plages calmes.": "Everglades, Miami Zoo, calm beaches.",
    "South Beach clubs, concerts, rooftops de Brickell.": "South Beach clubs, concerts, Brickell rooftops.",
    "entre-deux saisons, hébergements -30%.": "between seasons, accommodation -30%.",
    # Monaco
    "Monte-Carlo, Casino Café de Paris, hôtels palace.": "Monte-Carlo, Casino Café de Paris, palace hotels.",
    "expérience unique en sport automobile, réservations 1 an à l'avance.": "unique motorsport experience, book 1 year ahead.",
    "22 km de Cap Martin à Menton, panoramas mer.": "22 km from Cap Martin to Menton, sea panoramas.",
    "Jardin Exotique, Musée océanographique, plages.": "Exotic Garden, Oceanographic Museum, beaches.",
    "tables étoilées, marché de la Condamine.": "Michelin-starred restaurants, Condamine market.",
    # Mykonos
    "Paradise Beach, clubs jusqu'à l'aube. Réservez 6 mois à l'avance.": "Paradise Beach, clubs until dawn. Book 6 months ahead.",
    "avant le Meltemi, mer déjà chaude (23°C), moins de monde.": "before the Meltemi, sea already warm (23°C), fewer crowds.",
    "site archéologique de Délos sans foule.": "Delos archaeological site without crowds.",
    "lumière ambrée, moulins sans foule, ambiance de fin de saison.": "amber light, windmills without crowds, end-of-season atmosphere.",
    "île partiellement ouverte mais prix divisés par deux.": "island partially open but prices halved.",
    # Naples/Amalfi (extended)
    "Colisée, Forum, Vatican sans foule excessive.": "Colosseum, Forum, Vatican without excessive crowds.",
    "cacio e pepe, carbonara, supplì, gelato artisanal.": "cacio e pepe, carbonara, supplì, artisan gelato.",
    "Villa Borghese, fontaine de Trevi, plage d'Ostie.": "Villa Borghese, Trevi Fountain, Ostia beach.",
    "course dans les rues du centre historique classé UNESCO.": "race through the UNESCO-listed historic centre.",
    "Champs-Élysées illuminés, marchés de Noël, patinoires.": "Champs-Élysées lights, Christmas markets, ice rinks.",
    # Népal
    "Everest Base Camp, Annapurna, vues nettes.": "Everest Base Camp, Annapurna, clear views.",
    "Boudhanath, Pashupatinath, Durbar Squares.": "Boudhanath, Pashupatinath, Durbar Squares.",
    "Parc national de Chitwan, rhinos, tigres.": "Chitwan National Park, rhinos, tigers.",
    "mousson, hébergements -30%, circuits abordables.": "monsoon, accommodation -30%, affordable tours.",
    "meilleure visibilité, randonnées praticables.": "best visibility, walkable trails.",
    # New York
    "Central Park, High Line, Brooklyn Bridge.": "Central Park, High Line, Brooklyn Bridge.",
    "Central Park en couleurs, températures idéales, événements.": "Central Park in colours, ideal temperatures, events.",
    "MET, MoMA, Brooklyn Museum, concerts Carnegie Hall.": "MET, MoMA, Brooklyn Museum, Carnegie Hall concerts.",
    "Coney Island, Bronx Zoo, Natural History Museum.": "Coney Island, Bronx Zoo, Natural History Museum.",
    "Rockefeller, skating, marchés de Noël, 5th Avenue illuminée.": "Rockefeller, ice skating, Christmas markets, 5th Avenue lights.",
    "hôtels souvent moins chers, soldes post-fêtes.": "hotels often cheaper, post-holiday sales.",
    # Nice
    "Promenade des Anglais, galets, mer 25°C.": "Promenade des Anglais, pebble beach, sea 25°C.",
    "MAMAC, Musée Matisse, Chagall, marché du Cours Saleya.": "MAMAC, Matisse Museum, Chagall, Cours Saleya market.",
    "socca, salade niçoise, pissaladière, pan bagnat.": "socca, salade niçoise, pissaladière, pan bagnat.",
    "Matisse, Picasso, Chagall sans les files.": "Matisse, Picasso, Chagall without the queues.",
    "plage accessible, Promenade du Paillon, musées.": "beach access, Promenade du Paillon, museums.",
    "hors saison, hôtels de la Riviera -30%.": "off-season, Riviera hotels -30%.",
    "mer à 25-26°C, plages de galets à Nice, sable à Antibes/Pampelonne.": "sea 25–26°C, pebble beaches in Nice, sandy in Antibes/Pampelonne.",
    # Paris
    "Eiffel, Louvre, Versailles sans foule extrême.": "Eiffel Tower, Louvre, Versailles without extreme crowds.",
    "cerisiers au Trocadéro, jardins en fleurs, terrasses.": "cherry blossoms at Trocadéro, gardens in bloom, terraces.",
    "Disneyland à 40 min, grande roue des Tuileries, musées.": "Disneyland 40 min away, Tuileries Ferris wheel, museums.",
    "hôtels souvent moins chers, musées accessibles, ventes privées.": "hotels often cheaper, museums accessible, private sales.",
    # Phuket
    "Kata, Karon, Patong, eaux calmes et transparentes.": "Kata, Karon, Patong, calm clear waters.",
    "Big Buddha, Wat Chalong, Old Town de Phuket.": "Big Buddha, Wat Chalong, Phuket Old Town.",
    "Similan Islands, visibilité 30m+, requins-baleines.": "Similan Islands, 30m+ visibility, whale sharks.",
    "mer calme, Fantasea, Splash Jungle waterpark.": "calm sea, Fantasea, Splash Jungle waterpark.",
    "mousson, hôtels souvent moins chers, temples quasi vides.": "monsoon, hotels often cheaper, temples nearly empty.",
    # Porto
    "Lello, gare São Bento, Musée Serralves.": "Lello bookshop, São Bento station, Serralves Museum.",
    "caves de Vila Nova de Gaia, dégustation, croisières Douro.": "Vila Nova de Gaia cellars, tastings, Douro cruises.",
    "tramway historique, façades d'azulejos, Clerigos.": "historic tram, azulejo facades, Clérigos.",
    "plages de Matosinhos à 20 min, festivals estivaux.": "Matosinhos beaches 20 min away, summer festivals.",
    "vol + hôtel accessibles, moins cher que Lisbonne.": "affordable flights + hotels, cheaper than Lisbon.",
    "Nazaré (vagues géantes mondiales), Peniche.": "Nazaré (world-class giant waves), Peniche.",
    # Prague
    "Place de la Vieille Ville, parmi les plus beaux d'Europe.": "Old Town Square, among the finest in Europe.",
    "meilleure bière au monde (Pilsner Urquell), gulaš.": "world's best beer (Pilsner Urquell), guláš.",
    "ZOO de Prague, bateaux sur la Vltava, jardins Valdštejn.": "Prague Zoo, boats on the Vltava, Wallenstein Gardens.",
    "Dvořák, Smetana, concerts dans les palais.": "Dvořák, Smetana, concerts in palaces.",
    "hébergements -35%, vie moins chère que l'Europe Ouest.": "accommodation -35%, cheaper than Western Europe.",
    # Provence
    "Plateau de Valensole, Abbaye de Sénanque, pic mi-juillet.": "Plateau de Valensole, Sénanque Abbey, peak mid-July.",
    "Les Baux, Gordes, Pont du Gard.": "Les Baux, Gordes, Pont du Gard.",
    "Gorges du Verdon, Montagne Sainte-Victoire.": "Verdon Gorge, Montagne Sainte-Victoire.",
    "marchés colorés, lavande, Gorges du Verdon.": "colourful markets, lavender, Verdon Gorge.",
    "vendanges, route des vins, rosé de Provence AOP.": "harvest, wine route, Provence AOP rosé.",
    "tapenade, herbes de Provence, truffes (décembre-janvier).": "tapenade, herbes de Provence, truffles (December–January).",
    # Rhodes
    "Tsambika, Anthony Quinn Bay, Lindos, eau 26°C.": "Tsambika, Anthony Quinn Bay, Lindos, water 26°C.",
    "UNESCO, Palais des Grands Maîtres des Chevaliers.": "UNESCO site, Grand Master's Palace.",
    "Petaloudes, phénomène naturel unique à Rhodes.": "Petaloudes, unique natural phenomenon in Rhodes.",
    "mer chaude, plages, moins de foule qu'en juillet.": "warm sea, beaches, fewer crowds than July.",
    "hôtels souvent moins chers, opéra accessible, Naschmarkt abordable.": "hotels often cheaper, opera accessible, affordable Naschmarkt.",
    # Rio
    "été brésilien, plages animées, volley de plage.": "Brazilian summer, lively beaches, beach volleyball.",
    "Sambódromo, blocos de rua, l'un des plus grands spectacles du monde.": "Sambódromo, blocos de rua, one of the world's greatest spectacles.",
    "Christ Rédempteur, téléphérique, vues panoramiques.": "Christ the Redeemer, cable car, panoramic views.",
    "Lapa le vendredi soir, Pedra do Sal, clubs de forro.": "Lapa on Friday nights, Pedra do Sal, forró clubs.",
    "hiver doux, jardins botaniques, Niterói.": "mild winter, botanical gardens, Niterói.",
    # Rome
    "passerelle spectaculaire, réservation obligatoire.": "spectacular walkway, booking required.",
    "Santa Monica, Venice Beach, Malibu — ciel bleu garanti.": "Santa Monica, Venice Beach, Malibu — guaranteed blue skies.",
    "Runyon Canyon, Angeles Crest, températures douces.": "Runyon Canyon, Angeles Crest, mild temperatures.",
    "Universal Studios, Warner Bros, Griffith Observatory.": "Universal Studios, Warner Bros, Griffith Observatory.",
    "food trucks, restaurants fusion, marchés fermiers de Santa Monica.": "food trucks, fusion restaurants, Santa Monica farmers' markets.",
    "hors saison, hébergements accessibles, ville animée.": "off-season, affordable accommodation, lively city.",
    "hôtels souvent moins chers, basiliques gratuites, gastronomie abordable.": "hotels often cheaper, free basilicas, affordable dining.",
    # Santorin
    "avant le Meltemi et les clubs de juillet-août.": "before the Meltemi and July–August club crowds.",
    "lumière ambrée, terrasses moins bondées, couchers de soleil exceptionnels.": "amber light, less crowded terraces, exceptional sunsets.",
    # Sardaigne
    "Costa Smeralda, Cala Goloritzé, eaux turquoise parmi les plus belles.": "Costa Smeralda, Cala Goloritzé, some of the world's most beautiful turquoise waters.",
    "trek côtier spectaculaire, réservé aux initiés.": "spectacular coastal trek, for experienced hikers only.",
    "Su Nuraxi (UNESCO), civilisation unique.": "Su Nuraxi (UNESCO), unique ancient civilisation.",
    "Maddalena, Asinara, épaves remarquables.": "Maddalena, Asinara, remarkable wrecks.",
    "arancini, cannoli. Octobre : récolte des olives.": "arancini, cannoli. October: olive harvest.",
    "mer agréable, prix hébergements -35%.": "pleasant sea, accommodation prices -35%.",
    "mer agréable, prix hébergements -40%.": "pleasant sea, accommodation prices -40%.",
    # Séville
    "feria incontournable, flamenco, chevaux, ambiance unique.": "unmissable feria, flamenco, horses, unique atmosphere.",
    "tablao de flamenco, promenades en calèche, Giralda illuminée.": "flamenco tablao, horse-drawn carriage rides, illuminated Giralda.",
    "tapas, manzanilla, jamón ibérico dans le Barrio Santa Cruz.": "tapas, manzanilla, jamón ibérico in Barrio Santa Cruz.",
    "Cité des Arts et Sciences, plage, L'Oceanogràfic.": "City of Arts and Sciences, beach, L'Oceanogràfic.",
    # Seychelles
    "Anse Source d'Argent, Anse Lazio, rochers granitiques uniques.": "Anse Source d'Argent, Anse Lazio, unique granite boulders.",
    "Vallée de Mai (cocotier de mer), oiseaux endémiques.": "Vallée de Mai (coco de mer), endemic birds.",
    "Aldabra (UNESCO), Bird Island, île Curieuse.": "Aldabra (UNESCO), Bird Island, Curieuse Island.",
    "mer calme entre les 2 moussons, visibilité excellente.": "calm sea between the 2 monsoons, excellent visibility.",
    "entre-deux saisons, tarifs légèrement inférieurs.": "between seasons, slightly lower prices.",
    # Sicile
    "Scala dei Turchi, San Vito Lo Capo, eaux cristallines.": "Scala dei Turchi, San Vito Lo Capo, crystal-clear waters.",
    "Agrigente, Sélinonte, Segeste sans 38°C.": "Agrigento, Selinunte, Segesta without 38°C heat.",
    # Siem Reap
    "saison sèche, lever du soleil sur Angkor Wat, Ta Prohm.": "dry season, sunrise over Angkor Wat, Ta Prohm.",
    "musée national, spectacles d'Apsara, artisanat local.": "national museum, Apsara dance shows, local crafts.",
    "lac gonflé, villages flottants impressionnants.": "lake at full flood, impressive floating villages.",
    "amok, lok lak, marché nocturne de Pub Street.": "amok, lok lak, Pub Street night market.",
    "températures supportables, Angkor en famille.": "bearable temperatures, Angkor with the family.",
    "basse saison, tarifs minimaux, Songkran en avril.": "low season, lowest prices, Songkran in April.",
    # Singapour
    "Supertrees, Cloud Forest, dômes climatisés spectaculaires.": "Supertrees, Cloud Forest, spectacular climate-controlled domes.",
    "Chinatown, Little India, Kampong Glam, Clarke Quay.": "Chinatown, Little India, Kampong Glam, Clarke Quay.",
    "Maxwell Food Centre, Lau Pa Sat, Chilli Crab, laksa.": "Maxwell Food Centre, Lau Pa Sat, Chilli Crab, laksa.",
    "Orchard Road, VivoCity, boutiques duty-free.": "Orchard Road, VivoCity, duty-free shops.",
    "Universal Studios, Zoo de Singapour, S.E.A. Aquarium.": "Universal Studios, Singapore Zoo, S.E.A. Aquarium.",
    "hawker centers parmi les moins chers d'Asie du Sud-Est.": "hawker centres among the cheapest in Southeast Asia.",
    # Split
    "architecture vénitienne sans chaleur extrême.": "Venetian architecture without extreme heat.",
    "Hvar, Brač (Zlatni Rat), Vis en ferry depuis Split.": "Hvar, Brač (Zlatni Rat), Vis by ferry from Split.",
    "randonnées à 30 min de Split.": "hiking trails 30 min from Split.",
    "mer calme, plages, ferries vers les îles.": "calm sea, beaches, ferries to the islands.",
    "météo très correcte, prix 30-40% inférieurs au pic.": "very decent weather, prices 30–40% below peak.",
    # South Africa
    "Clifton Beach, Camps Bay, eaux fraîches de l'Atlantique.": "Clifton Beach, Camps Bay, fresh Atlantic waters.",
    "Stellenbosch, Franschhoek, vendanges et dégustations.": "Stellenbosch, Franschhoek, harvest and tastings.",
    "baleines franches australes à Hermanus, pingouins à Boulders Beach.": "southern right whales at Hermanus, penguins at Boulders Beach.",
    "printemps/automne austral idéal.": "ideal southern spring/autumn.",
    "excellente valeur avec le taux de change favorable.": "excellent value with favourable exchange rate.",
    # Tenerife
    "plages du sud de Tenerife, Las Teresitas. Eau à 24°C.": "south Tenerife beaches, Las Teresitas. Water at 24°C.",
    "Parc national du Teide (3718m), ciel étoilé exceptionnel.": "Teide National Park (3,718m), exceptional starry sky.",
    "dauphins, baleines pilotes au large de Tenerife.": "dolphins, pilot whales off Tenerife.",
    "Las Teresitas (sable du Sahara), El Médano (windsurf).": "Las Teresitas (Saharan sand), El Médano (windsurfing).",
    "Loro Parque, Siam Park (meilleur parc aquatique d'Europe).": "Loro Parque, Siam Park (Europe's best water park).",
    "Parc national, téléphérique, sentiers de lave.": "national park, cable car, lava trails.",
    # Bangkok
    "Grand Palais, Wat Pho, Wat Arun sans chaleur écrasante.": "Grand Palace, Wat Pho, Wat Arun without crushing heat.",
    "Chatuchak, malls géants, soldes de fin d'année.": "Chatuchak, mega malls, year-end sales.",
    "Chinatown, marchés nocturnes, cours de cuisine thaï.": "Chinatown, night markets, Thai cooking classes.",
    "marchés nocturnes, cours de cuisine thaï.": "night markets, Thai cooking classes.",
    "saison sèche, Safari World, parcs aquatiques.": "dry season, Safari World, water parks.",
    "Ayutthaya (UNESCO), Kanchanaburi, Floating Market.": "Ayutthaya (UNESCO), Kanchanaburi, Floating Market.",
    # Tokyo
    "Senso-ji, Meiji, Shibuya, sans chaleur ni humidité.": "Senso-ji, Meiji, Shibuya, without heat or humidity.",
    "Ueno, Chidorigafuchi, Shinjuku Gyoen, spectacle unique.": "Ueno, Chidorigafuchi, Shinjuku Gyoen, a unique spectacle.",
    "Disneyland Tokyo, teamLab, températures idéales.": "Tokyo Disneyland, teamLab, ideal temperatures.",
    "plus d'étoiles Michelin que Paris, ramen, sushi, izakaya.": "more Michelin stars than Paris, ramen, sushi, izakaya.",
    "Nikko, Shinjuku Gyoen, Meiji Jingu, couleurs spectaculaires.": "Nikko, Shinjuku Gyoen, Meiji Jingu, spectacular colours.",
    "hors sakura, hôtels souvent moins chers, yen favorable aux Européens.": "outside sakura, hotels often cheaper, yen favourable for Europeans.",
    # Toscane
    "vendanges, couleurs d'automne, dégustations. Le moment le plus photogénique de l'année dans le Chianti.": "harvest, autumn colours, tastings. The most photogenic time of year in Chianti.",
    "Florence moins bondée, températures agréables.": "Florence less crowded, pleasant temperatures.",
    "lumière ambrée, vignes en couleurs, brumes matinales dans les vallées.": "amber light, colourful vines, morning mist in the valleys.",
    # Valence
    "La Malvarrosa, El Saler, eaux Méditerranée.": "La Malvarrosa, El Saler, Mediterranean waters.",
    "l'un des festivals les plus spectaculaires du monde, UNESCO.": "one of the world's most spectacular festivals, UNESCO.",
    "paella authentique (berceau de la paella), marché central.": "authentic paella (birthplace of paella), central market.",
    "Turia riverbed park, réseau vélo de 150 km.": "Turia riverbed park, 150 km cycling network.",
    "plage, Bioparc, Aquarium, mer 24°C.": "beach, Bioparc, Aquarium, sea 24°C.",
    "températures douces, festivals de printemps.": "mild temperatures, spring festivals.",
    # Venise
    "lagune en bateau, Murano (verre), Burano (maisons colorées).": "lagoon by boat, Murano (glass), Burano (colourful houses).",
    "Biennale, Gallerie dell'Accademia sans la foule d'été.": "Biennale, Gallerie dell'Accademia without summer crowds.",
    "Dorsoduro, Cannaregio, Castello sans touristes.": "Dorsoduro, Cannaregio, Castello without tourists.",
    "lumière dorée, brumes matinales, gondoles vides.": "golden light, morning mist, empty gondolas.",
    "unique mais froid (3-10°C) et acqua alta fréquente.": "unique but cold (3–10°C) and frequent acqua alta.",
    "l'un des carnavals les plus célèbres au monde.": "one of the world's most famous carnivals.",
    # Vienne
    "Schönbrunn, Hofburg, Kunsthistorisches Museum.": "Schönbrunn, Hofburg, Kunsthistorisches Museum.",
    "Café Central, Schwarzenberg, Sacher, UNESCO immatériel.": "Café Central, Schwarzenberg, Sacher, UNESCO intangible heritage.",
    "Rathausplatz, Schönbrunn, Belvedere, parmi les plus beaux d'Europe.": "Rathausplatz, Schönbrunn, Belvedere, among the finest in Europe.",
    "Philharmonique de Vienne, Opéra d'État, concerts.": "Vienna Philharmonic, State Opera, concerts.",
    "Prater & grande roue, zoo de Schönbrunn, Danube Island.": "Prater & Ferris wheel, Schönbrunn Zoo, Danube Island.",
    "hôtels souvent moins chers, opéra accessible, Naschmarkt abordable.": "hotels often cheaper, opera accessible, affordable Naschmarkt.",
    # Zakynthos
    "plage du Naufragé (icône mondiale), Blue Caves en bateau.": "Shipwreck Beach (world icon), Blue Caves by boat.",
    "nidification sur les plages de Gerakas et Sekania (accès protégé).": "nesting on Gerakas and Sekania beaches (protected access).",
    "Blue Caves, Keri Caves, eaux cristallines.": "Blue Caves, Keri Caves, crystal-clear waters.",
    "villages montagnards, Bohali, vues sur l'île.": "mountain villages, Bohali, island views.",
    "mer encore agréable, prix 30-40% moins chers qu'en été.": "sea still pleasant, prices 30–40% cheaper than summer.",
    # Zanzibar
    "Nungwi, Kendwa, Paje, eaux turquoise.": "Nungwi, Kendwa, Paje, turquoise waters.",
    "UNESCO, culture swahili, spice tours.": "UNESCO site, Swahili culture, spice tours.",
    "mer calme, plages de sable blanc, tortues à Nungwi.": "calm sea, white sand beaches, turtles at Nungwi.",
    "récif corallien, tortues, dauphins à Kizimkazi.": "coral reef, turtles, dolphins at Kizimkazi.",
    "saison sèche, mer calme, eaux turquoise 28°C.": "dry season, calm sea, turquoise waters 28°C.",
    "début/fin de saison verte, prix -25%, moins de monde.": "start/end of green season, prices -25%, fewer crowds.",
    # Generic / shared
    "mer calme, eau turquoise, pas de sargasses.": "calm sea, turquoise water, no sargassum.",
    "mer calme, eau turquoise, sans sargasses.": "calm sea, turquoise water, no sargassum.",
    "mer calme, tortues, plages sécurisées.": "calm sea, turtles, safe beaches.",
    "mer calme, lagons peu profonds, sécurisés.": "calm sea, shallow lagoons, safe.",
    "mer calme, plages protégées, faune accessible.": "calm sea, sheltered beaches, accessible wildlife.",
    "mer chaude, plages familiales, moins de foule.": "warm sea, family beaches, fewer crowds.",
    "mer chaude, chaleur supportable.": "warm sea, bearable heat.",
    "mer chaude, plages, moins de foule qu'en juillet.": "warm sea, beaches, fewer crowds than July.",
    "mer déjà chaude (22°C), foule raisonnable, pas encore les prix d'été.": "sea already warm (22°C), reasonable crowds, not yet summer prices.",
    "mer encore agréable, prix hébergements -35%.": "sea still pleasant, accommodation prices -35%.",
    "mer à 24-26°C, sites historiques, animations.": "sea 24–26°C, historical sites, entertainment.",
    "plage à 5 km de la vieille ville, bars.": "beach 5 km from the old town, bars.",
    "plages sécurisées, eaux calmes, moins de monde.": "safe beaches, calm waters, fewer crowds.",
    "plages sécurisées, moins de monde, tarifs corrects.": "safe beaches, fewer crowds, reasonable prices.",
    "eaux turquoise, plages de sable blanc, mer calme.": "turquoise waters, white sand beaches, calm sea.",
    "chaleur modérée, plages immenses et peu fréquentées.": "moderate heat, vast uncrowded beaches.",
    "meilleure visibilité, coraux vivants.": "best visibility, living coral.",
    "meilleure visibilité, récifs coralliens vivants.": "best visibility, living coral reefs.",
    "meilleure visibilité, vagues pour surfeurs.": "best visibility, waves for surfers.",
    "visibilité 30m+, raies manta, requins-baleines.": "30m+ visibility, manta rays, whale sharks.",
    "visibilité excellente, eau 24-26°C.": "excellent visibility, water 24–26°C.",
    "visibilité optimale, poissons tropicaux, coraux.": "optimal visibility, tropical fish, coral.",
    "eau claire 20-25°C, tortues marines et raies.": "clear water 20–25°C, sea turtles and rays.",
    "eau à 25-26°C, visibilité maximale.": "water 25–26°C, maximum visibility.",
    "eaux cristallines, épaves, grottes sous-marines.": "crystal-clear waters, wrecks, underwater caves.",
    "requins, tortues, poissons tropicaux.": "sharks, turtles, tropical fish.",
    "la pluie n'affecte pas les activités sous-marines.": "rain doesn't affect underwater activities.",
    "la pluie ne gêne pas sous l'eau.": "rain doesn't bother you underwater.",
    "baleines pilotes sédentaires, dauphins communs.": "resident pilot whales, common dolphins.",
    "point le plus favorable pour l'observation.": "best vantage point for observation.",
    "saison sèche, routes praticables, activités nature accessibles.": "dry season, passable roads, accessible nature activities.",
    "saison sèche, visite culturelle, plages accessibles.": "dry season, cultural visits, accessible beaches.",
    "saison des pluies, tarifs accessibles, moins de touristes.": "rainy season, affordable prices, fewer tourists.",
    "début de saison, prix en baisse, plages tranquilles.": "start of season, falling prices, quiet beaches.",
    "fuir le froid européen, vols et hôtels accessibles.": "escape European cold, affordable flights and hotels.",
    "22°C en moyenne, parfait pour fuir l'Europe grise.": "22°C on average, perfect for escaping grey Europe.",
    "tarifs post-été, météo excellente, moins de monde.": "post-summer rates, excellent weather, fewer crowds.",
    "tarifs basse saison, plages désertes, soleil garanti.": "low-season rates, deserted beaches, guaranteed sunshine.",
    "météo correcte, prix -40%, sites sans file.": "decent weather, prices -40%, sites without queues.",
    "vols accessibles, hébergements -40%.": "affordable flights, accommodation -40%.",
    "vol + hôtel plus accessibles qu'en été.": "flight + hotel more affordable than in summer.",
    "basse saison touristique, hébergements -30%, côté Atlantique ensoleillé.": "tourist low season, accommodation -30%, sunny Atlantic side.",
    "hors saison, prix -50%, ville authentique.": "off-season, prices -50%, authentic city.",
    "ouvert toute l'année, prix -50%.": "open year-round, prices -50%.",
    "hôtels souvent moins chers, musées accessibles, ventes privées.": "hotels often cheaper, museums accessible, private sales.",
    "moins de touristes, tarifs vols accessibles.": "fewer tourists, affordable flight prices.",
    "moins de touristes, vols accessibles depuis l'Europe.": "fewer tourists, affordable flights from Europe.",
    "hôtels -30%, moins de touristes, temps souvent ensoleillé.": "hotels -30%, fewer tourists, often sunny weather.",
    "vacances d'été austral, plages accessibles, activités variées.": "southern summer holidays, accessible beaches, varied activities.",
    "vacances scolaires, mer calme, activités variées.": "school holidays, calm sea, varied activities.",
    "2e plus grand carnaval du monde après Rio de Janeiro.": "world's 2nd biggest carnival after Rio de Janeiro.",
    "Sistema Dos Ojos, Gran Cenote, visibilité exceptionnelle.": "Sistema Dos Ojos, Gran Cenote, exceptional visibility.",
    "Playa Paraíso, cenotes cristallins, sans sargasses.": "Playa Paraíso, crystal-clear cenotes, no sargassum.",
    "Tulum Pueblo, retraites de yoga, cuisine saine.": "Tulum Pueblo, yoga retreats, healthy cuisine.",
    "ponte nocturne sur les plages de Cancún.": "nighttime nesting on Cancún beaches.",
    "Chichen Itza et Tulum moins bondés.": "Chichen Itza and Tulum less crowded.",
    "site archéologique au lever du soleil, moins de chaleur.": "archaeological site at sunrise, less heat.",
    "avant la haute saison, plages accessibles, prix raisonnables.": "before peak season, accessible beaches, reasonable prices.",
    "saison ouverte de juin à septembre, clubs animés.": "open season June to September, lively clubs.",
    "températures agréables, îles encore/encore ouvertes.": "pleasant temperatures, islands still open.",
    # LA
    "Disneyland, plages, meteorology parfaite pour activités en plein air.": "Disneyland, beaches, perfect weather for outdoor activities.",
    "visites sans chaleur écrasante, queue plus courte.": "visiting without crushing heat, shorter queues.",
    # Lisbonne
    "Lisbonne hors saison, musées sans file, prix réduits.": "Lisbon off-season, museums without queues, lower prices.",
    "Cascais, Setúbal, Comporta. Eau à 20-22°C, brise Nortada rafraîchissante.": "Cascais, Setúbal, Comporta. Water 20–22°C, refreshing Nortada breeze.",
    "vendanges, train jusqu'à Peso da Régua.": "harvest, train to Peso da Régua.",
    "parcs nationaux, sentiers côtiers.": "national parks, coastal trails.",
    # Santorin (extended)
    "juin offre le meilleur rapport lumière/affluence.": "June offers the best light-to-crowds ratio.",
    "juin reste le plus beau rapport lumière/foule.": "June remains the best light-to-crowds balance.",
    # Barbade
    "Carlisle Bay, Bridgetown, Oistins Bay.": "Carlisle Bay, Bridgetown, Oistins Bay.",
    "saison sèche, mer calme, eaux turquoise 28°C.": "dry season, calm sea, turquoise waters 28°C.",
    "mer calme, eau turquoise, pas de sargasses.": "calm sea, turquoise water, no sargassum.",
    # Voile & Brest
    "Brest, La Trinité-sur-Mer, régates.": "Brest, La Trinité-sur-Mer, regattas.",
    # Catch-all for remaining
    "Lacanau, Hossegor à 1h, vagues de renommée mondiale.": "Lacanau, Hossegor 1h away, world-renowned waves.",
    "Blue Mountains, Port Royal moins fréquentés.": "Blue Mountains, Port Royal less crowded.",
    "Sintra & Arrábida.": "Sintra & Arrábida.",
    "Sintra & Arrábida": "Sintra & Arrábida",
    "mer chaude, plages familiales, moins de monde.": "warm sea, family beaches, fewer crowds.",
    "mer 24°C, gorges accessibles, sans foule.": "sea 24°C, accessible gorges, no crowds.",
    "Mljet, Korčula, Hvar en ferry.": "Mljet, Korčula, Hvar by ferry.",
    "parc national des Gorges, plateau du Grand Bassin.": "Gorges national park, Grand Bassin plateau.",
    "randonnées par ciel dégagé, vues panoramiques sur la ville.": "clear-sky hiking, panoramic city views.",
    "UNESCO vivant, architecture baroque et gothique.": "living UNESCO site, Baroque and Gothic architecture.",
    "mer encore agréable, prix -40% vs juillet.": "sea still pleasant, prices -40% vs July.",
    "baleines à bosse migrant depuis l'Antarctique.": "humpback whales migrating from Antarctica.",
}

# ── MAIN LOGIC ──────────────────────────────────────────────────────────────

def translate_period(text):
    """Translate the period prefix before ' — '"""
    # First try exact match
    if text in PERIOD_MAP:
        return PERIOD_MAP[text]
    
    # Then translate connectors
    result = text
    result = result.replace(' ou ', ' or ')
    result = result.replace(' à ', ' to ')
    
    # Then translate individual French months (longest first to avoid partial matches)
    MONTH_FR_EN = [
        ('janvier', 'January'), ('février', 'February'), ('mars', 'March'),
        ('avril', 'April'), ('mai', 'May'), ('juin', 'June'),
        ('juillet', 'July'), ('août', 'August'), ('septembre', 'September'),
        ('octobre', 'October'), ('novembre', 'November'), ('décembre', 'December'),
        # Capitalised versions
        ('Janvier', 'January'), ('Février', 'February'), ('Mars', 'March'),
        ('Avril', 'April'), ('Mai', 'May'), ('Juin', 'June'),
        ('Juillet', 'July'), ('Août', 'August'), ('Septembre', 'September'),
        ('Octobre', 'October'), ('Novembre', 'November'), ('Décembre', 'December'),
        # Also handle "Mi-" prefix
        ('Mi-mars', 'Mid-March'), ('Mi-mai', 'Mid-May'),
        ('Mi-juin', 'Mid-June'), ('Mi-juillet', 'Mid-July'),
        ('mi-mars', 'mid-March'), ('mi-mai', 'mid-May'),
        ('mi-juin', 'mid-June'), ('mi-juillet', 'mid-July'),
    ]
    for fr, en in MONTH_FR_EN:
        result = result.replace(fr, en)
    
    return result

def translate_card(titre_fr, texte_fr):
    """Translate a single card."""
    titre_en = TITRE_EN.get(titre_fr, titre_fr)  # fallback to original
    
    # Split texte on " — " to get period + description
    parts = texte_fr.split(' — ', 1)
    if len(parts) == 2:
        period_fr, desc_fr = parts
        period_en = translate_period(period_fr)
        desc_en = DESC_EN.get(desc_fr, None)
        if desc_en is None:
            # Try full text match
            desc_en = DESC_EN.get(texte_fr, None)
        if desc_en is None:
            desc_en = f"[UNTRANSLATED] {desc_fr}"
        texte_en = f"{period_en} — {desc_en}"
    else:
        # No period separator
        desc_en = DESC_EN.get(texte_fr, None)
        if desc_en is None:
            texte_en = f"[UNTRANSLATED] {texte_fr}"
        else:
            texte_en = desc_en
    
    return titre_en, texte_en

# Load FR cards and translate
cards_fr = list(csv.DictReader(open('data/cards.csv', encoding='utf-8-sig')))

untranslated = []
with open('data/cards_en.csv', 'w', newline='', encoding='utf-8-sig') as f:
    writer = csv.DictWriter(f, fieldnames=['slug', 'icon', 'title', 'text'])
    writer.writeheader()
    for c in cards_fr:
        titre_en, texte_en = translate_card(c['titre'], c['texte'])
        writer.writerow({
            'slug': c['slug'],
            'icon': c['icon'],
            'title': titre_en,
            'text': texte_en,
        })
        if '[UNTRANSLATED]' in texte_en:
            untranslated.append((c['slug'], c['titre'], c['texte']))

print(f"✅ Translated {len(cards_fr)} cards")
print(f"❌ Untranslated descriptions: {len(untranslated)}")
if untranslated:
    print("\n--- Missing translations ---")
    for slug, titre, texte in untranslated:
        parts = texte.split(' — ', 1)
        desc = parts[1] if len(parts) == 2 else texte
        print(f'    "{desc}": "",')

if __name__ == '__main__':
    pass
