"""
Monthly insights par climat × mois × langue.

5 climats × 12 mois = 60 paragraphes uniques par langue.
Permet de différencier les fiches mensuelles V5 entre destinations de climats différents
et entre mois de la même destination.

Classification climat (simplifiée pour usage SEO):
- alpine: mountain=True (stations + montagnes, saison ski/randonnée)
- tropical: tropical=True (saisons sèche/humide, climat équatorial/subtropical)
- mediterranean: coastal=True ET 28° <= |lat| <= 46° (étés chauds secs, hivers doux)
- oceanic: coastal=True ET |lat| > 46° (modéré pluvieux, océanique tempéré)
- continental: tout le reste (saisons marquées, intérieur des terres)
"""

def classify_climate(dest: dict) -> str:
    """Retourne le climat d'une destination selon ses caractéristiques."""
    if str(dest.get('mountain', '')).lower() in ('true', '1', 'yes'):
        return 'alpine'
    if str(dest.get('tropical', '')).lower() in ('true', '1', 'yes'):
        return 'tropical'
    try:
        lat = abs(float(dest.get('lat', 0)))
    except (TypeError, ValueError):
        lat = 0
    is_coastal = str(dest.get('coastal', '')).lower() in ('true', '1', 'yes')
    if is_coastal and 28 <= lat <= 46:
        return 'mediterranean'
    if is_coastal and lat > 46:
        return 'oceanic'
    return 'continental'


# ─────────────────────────────────────────────────────────────────────────────
# FR — 60 paragraphes (5 climats × 12 mois)
# ─────────────────────────────────────────────────────────────────────────────

INSIGHTS_FR = {
    'continental': {
        1: "Janvier marque le cœur de l'hiver continental. Journées courtes (lever 8h, coucher 17h), gel fréquent, neige possible jusqu'en plaine. Saison des marchés couverts, musées et thermes urbains. Soldes d'hiver dans la plupart des pays européens. Hors vacances scolaires, les tarifs hôteliers chutent fortement et les sites touristiques se vident.",
        2: "Février prolonge l'hiver mais les jours s'allongent visiblement. Carnavals à Venise, Cologne, Bâle, Nice. Vacances scolaires européennes décalées par zones (affluence variable). Saint-Valentin et offres city-break. Météo encore froide mais bonus : lumière hivernale photogénique et brouillards matinaux sur les fleuves.",
        3: "Mars amorce la transition vers le printemps. Premières floraisons en fin de mois (crocus, jonquilles, magnolias). Températures encore fraîches le matin. Retour du vivant dans les parcs urbains. Marathon de Paris en avril, mais préparations visibles en mars. Pâques parfois en fin de mois (affluence + tarifs élevés).",
        4: "Avril déploie le printemps continental : arbres en fleurs, terrasses qui ré-ouvrent, premières journées à 18-20°C. Météo capricieuse (averses fréquentes, l'adage 'avril ne te découvre pas d'un fil'). Tulipes en Hollande, cerisiers en Allemagne. Pâques affluence pic. Bonne période avant la haute saison.",
        5: "Mai est l'un des meilleurs mois pour visiter les villes d'Europe continentale. Températures douces (15-22°C), lumière longue, jardins en pleine floraison. Ponts du 1er et du 8 mai créent des micro-pics d'affluence. Festivals printaniers (Cannes côté Méditerranée, festivals indé partout). Moustiques absents.",
        6: "Juin ouvre l'été : journées les plus longues de l'année (solstice 21 juin), terrasses bondées, festivals de musique en plein air. Températures agréables (20-26°C) avant les canicules de juillet. Fête de la Musique 21 juin partout en France et en Europe. Avant l'afflux estival des vacances scolaires.",
        7: "Juillet est en pleine haute saison touristique. Chaleur installée (25-32°C), parfois caniculaire fin juillet. Festivals en plein air (Avignon, Tomorrowland, Roskilde). Affluence maximale dans les capitales. Tarifs hôteliers au plus haut. Soirées animées tard grâce aux journées longues. Réserver très en avance.",
        8: "Août reste estival mais beaucoup de locaux partent en vacances. Certaines villes (Paris, Milan) se vident de leurs habitants, créant une atmosphère étrange : touristes nombreux, mais commerces de quartier parfois fermés. Météo : chaud, possibilité d'orages d'été. Pic de la canicule traditionnelle 'mi-août'.",
        9: "Septembre signe le retour à la normale : rentrée scolaire, tarifs en baisse, météo encore douce (18-25°C). Lumière dorée de fin d'été, vendanges en cours dans les régions viticoles. Une des meilleures périodes pour visiter : confort climatique et affluence réduite. Marathons d'automne en planification.",
        10: "Octobre installe l'automne. Couleurs spectaculaires sur les arbres (érables, hêtres, chênes), photogéniques surtout en fin de mois. Températures qui basculent (10-18°C), pluies plus fréquentes. Vacances de la Toussaint en fin de mois (affluence ponctuelle). Halloween de plus en plus marqué dans les villes.",
        11: "Novembre est le mois le moins touristique de l'année dans la plupart des villes européennes continentales. Météo grise, journées courtes, premières gelées. Tarifs au plancher. Bon moment pour les musées (peu d'attente), gastronomie hivernale qui démarre. Beaujolais Nouveau 3e jeudi du mois.",
        12: "Décembre transforme les villes avec les marchés de Noël (Strasbourg, Vienne, Nuremberg, Prague). Décorations lumineuses, vin chaud, ambiance unique. Affluence forte les week-ends et autour du 24-25. Météo froide, neige possible. Tarifs élevés autour des fêtes. À faire au moins une fois pour l'atmosphère.",
    },
    'mediterranean': {
        1: "Janvier est doux et lumineux sur la Méditerranée (10-15°C maxi en journée). Mer trop froide pour se baigner mais ciel souvent bleu. Citronniers et orangers en fruits. Saison creuse touristique : tarifs bas, sites quasi vides. Idéal pour la culture et la gastronomie sans la foule estivale. Vent frais possible (Mistral, Tramontane).",
        2: "Février voit les amandiers fleurir, premier signe de printemps méditerranéen. Carnaval de Nice, Limoux, Sitges. Températures qui remontent doucement (12-17°C). Mer encore fraîche. Bonne période pour la randonnée côtière, sentiers du littoral encore peu fréquentés. Lumière hivernale photogénique.",
        3: "Mars apporte le printemps méditerranéen. Mimosa en pleine floraison (Côte d'Azur, Andalousie). Températures agréables (14-19°C). Premières terrasses ré-ouvrent. Mer encore froide (14°C). Festival du Citron à Menton. Pluies épisodiques. Bonne période pour découvrir la nature qui explose avant la haute saison.",
        4: "Avril est l'un des meilleurs mois pour la Méditerranée. Floraisons spectaculaires (glycines, bougainvilliers, oliviers), températures douces (16-21°C), lumière qui s'allonge. Pâques crée un pic d'affluence en fin de mois. Mer encore fraîche (15-16°C) mais ciel bleu majoritaire. Idéal pour visites culturelles et randonnée.",
        5: "Mai marque l'éveil de la saison estivale. Températures de 19-25°C, mer qui se réchauffe (17-19°C). Festival de Cannes mi-mai. Tour des Bouches du Rhône. Les figues de Barbarie commencent. Encore avant le grand afflux touristique. Soirées douces, taverne en terrasse. Excellent compromis météo/affluence.",
        6: "Juin ouvre vraiment l'été méditerranéen. Mer chaude (21-23°C), longues journées, températures de 24-29°C. Encore tolérable avant les canicules. Festivals s'enchaînent (Hellfest, Fête de la Musique, Provence Jazz). Hausse marquée des tarifs en fin de mois. Le bonheur côtier sans la suffocation de juillet-août.",
        7: "Juillet est la haute saison absolue : plages bondées, températures de 28-35°C, mer à 24-26°C, soirées tardives en bord de mer. Risque caniculaire en intérieur des terres (Provence, Andalousie). Affluence maximale, tarifs au plus haut. Réservation obligatoire des restaurants en bord de mer. Été méditerranéen iconique.",
        8: "Août prolonge juillet en plus chaud encore. Pics de canicule fréquents (35-40°C dans certaines régions). Mer chaude (25-27°C). Foule maximale, tarifs élevés. Festival d'Avignon, Calvi on the Rocks, Sziget en Hongrie. Pluies inexistantes. Bonne idée : privilégier les heures matinales pour les visites, sieste l'après-midi.",
        9: "Septembre est souvent considéré comme le meilleur mois de la Méditerranée. Eau encore chaude (24-25°C), foule qui diminue après le 15, soleil constant, températures plus douces (24-29°C). Vendanges en Provence et Andalousie. Festivals d'automne démarrent. Lumière dorée idéale photographie. Compromis parfait.",
        10: "Octobre installe la douceur automnale. Encore agréable pour la plage début de mois (mer à 22°C, air 22-26°C). Pluies plus fréquentes en deuxième quinzaine. Vacances de la Toussaint = pic d'affluence. Champignons, châtaignes, olive nouvelle. Couleurs automnales sur les massifs intérieurs. Tarifs en baisse.",
        11: "Novembre est calme et frais sur la Méditerranée (13-19°C). Vent et pluies plus fréquents. Foule absente, tarifs très bas. Saison des truffes (Provence), de l'olive nouvelle, des vins primeurs. Bonne période pour visiter les sites antiques sans la foule (Paestum, Ostia, Tarragone). Lumière hivernale superbe.",
        12: "Décembre apporte un climat doux mais humide (11-16°C). Marchés de Noël à Aix, Marseille, Barcelone. Pluies parfois soutenues. Mer trop froide pour se baigner (16°C) mais sentiers côtiers magnifiques par temps clair. Tarifs en pic autour des fêtes uniquement, plancher avant et après.",
    },
    'tropical': {
        1: "Janvier se situe en pleine saison sèche dans la plupart des destinations tropicales de l'hémisphère nord (Caraïbes, Asie du Sud-Est, Mexique). Soleil constant, peu de pluie, températures de 28-32°C, humidité supportable. Haute saison touristique : tarifs au plus haut, plages bondées. Réservation impérative très en avance.",
        2: "Février prolonge la saison sèche, conditions souvent optimales : moins humide qu'en janvier, soleil constant, mer chaude. Hémisphère sud (Bali, Polynésie, nord Australie) en pleine saison humide : averses tropicales quotidiennes, mais courtes. Carnaval de Rio en fin de mois (affluence Brésil).",
        3: "Mars termine la haute saison dans les destinations tropicales nord. Très bonnes conditions, températures qui montent légèrement (29-33°C). Plongée et snorkeling au top (visibilité excellente). Côté hémisphère sud, fin de saison des pluies. Holi en Inde marquant le début du printemps. Spring Break afflux côté Caraïbes.",
        4: "Avril est un excellent mois transition. Hémisphère nord tropical : encore sec, températures élevées (30-34°C), avant les pluies. Hémisphère sud (Australie, Bali) : conditions se stabilisent, fin saison humide. Songkran (nouvel an thaï) mi-avril : festivités à l'eau, affluence forte en Asie du Sud-Est. Mer toujours chaude.",
        5: "Mai bascule vers la saison humide dans les tropiques de l'hémisphère nord. Premières averses tropicales en fin de journée (souvent courtes). Températures restent à 30-33°C, humidité plus marquée (70-85%). Tarifs en chute, foule disparaît. Plongée encore possible matin. Bali commence sa belle saison sèche.",
        6: "Juin marque le début de la saison humide dans les tropiques nord (mousson sud-est asiatique, saison des pluies Caraïbes). Pluies quotidiennes mais souvent en fin de journée. Tarifs hôteliers parfois moitié prix. Hémisphère sud (Bali, Tahiti) : pleine saison sèche, conditions idéales, lumière magnifique.",
        7: "Juillet est en pleine mousson en Asie du Sud-Est (Thaïlande ouest, Cambodge, Vietnam centre). Caraïbes : début saison cyclonique (faible risque encore). Hémisphère sud : Bali et Polynésie au top, ciel bleu, températures parfaites (26-29°C), surf au mieux. Brésil sud : hiver doux, sec, agréable.",
        8: "Août est le mois le plus humide en mousson asiatique. Pluies intenses mais souvent localisées. Vacances européennes = afflux malgré météo. Hémisphère sud (Bali, Australie nord) : conditions parfaites, sèches, ensoleillées. Pic de la saison sèche aux Galápagos. Festival Esala Perahera au Sri Lanka.",
        9: "Septembre est le pic de la saison cyclonique aux Caraïbes (risque maximal, surveiller). Vraies tropicales : pluies intenses. Tarifs très bas, foule absente. Hémisphère sud : transition fin saison sèche en Asie du Sud-Est sud. Bali fin de la belle saison. Souvent un bon mois pour rester loin de l'Atlantique tropical.",
        10: "Octobre voit la saison cyclonique caribéenne décroître en fin de mois. Pluies s'espacent en Asie du Sud-Est. Reprise progressive du tourisme. Tarifs encore bas. Inde : fin de mousson, Diwali en fin de mois (festivités lumineuses). Bali : transition vers la saison humide (fin de mois).",
        11: "Novembre marque le retour de la saison sèche dans les tropiques nord. Conditions s'améliorent rapidement, plongée redevient excellente. Foule encore absente, tarifs bas. Bonne période avant le rush de décembre. Thaïlande : Loy Krathong (festival des lanternes flottantes). Hémisphère sud entre en saison humide.",
        12: "Décembre lance la haute saison tropicale (hémisphère nord). Soleil revient, températures parfaites (28-31°C), mer chaude. Vacances de Noël : tarifs au plus haut, plages bondées. Réservations très en avance. Hémisphère sud : Bali, nord Australie en pleine saison humide. Carnaval australien et fêtes pacifiques.",
    },
    'oceanic': {
        1: "Janvier est le cœur de l'hiver océanique : températures de 4-9°C, pluies fréquentes, vent. Journées courtes (lever 8h-9h, coucher 16h-17h). Atmosphère cosy : pubs, brasseries, musées, théâtres. Tarifs touristiques au plus bas. Excellente période pour villes culturelles (Londres, Dublin, Édimbourg, Vancouver) loin de la foule.",
        2: "Février reste hivernal mais lumière qui revient. Saint-Valentin et offres city-break. Tempêtes hivernales encore actives en Atlantique nord. Premiers signes de printemps en fin de mois (perce-neige, jonquilles précoces). Carnaval à Cologne, Rotterdam. Affluence très faible. Idéal pour découvrir les villes intramuros sans la foule.",
        3: "Mars amorce le printemps océanique. Floraisons précoces dans les jardins (camélias, magnolias). Températures encore fraîches (7-12°C). Crachins typiques mais épisodiques. Marathon de Paris (fin du mois en avril généralement). St Patrick 17 mars (Dublin et villes irlandaises : grande affluence). Lumière qui s'allonge nettement.",
        4: "Avril déploie le printemps côté Atlantique. Tulipes (Pays-Bas, Keukenhof), jonquilles, premiers cerisiers en fleurs. Températures de 10-15°C, averses fréquentes (avril typique). Pâques varie selon les années (affluence et tarifs). Bonne période pour le tourisme urbain avant la haute saison estivale.",
        5: "Mai est probablement le meilleur mois pour les destinations océaniques : floraisons spectaculaires, températures douces (13-18°C), journées longues, moins de pluies qu'en avril. Chelsea Flower Show à Londres. Festival d'Eurovision finale. Avant le rush estival. Parcs et jardins à leur apogée.",
        6: "Juin offre les jours les plus longs de l'année (Solstice 21 juin, en Écosse soleil quasi continu en juillet). Températures douces (15-20°C). Saison des roses dans les parcs anglais. Wimbledon démarre fin juin. Climat encore tempéré, foule estivale s'installe progressivement. Excellent pour les balades en soirée.",
        7: "Juillet est le mois le plus chaud (18-23°C maxi). Météo très variable côté Atlantique : alternance soleil/pluies. Festivals d'été en plein air (Glastonbury fin juin, Hyde Park summer concerts). Affluence touristique forte. Soirées agréables dehors. Côté Pacifique nord-ouest : sec et ensoleillé, conditions optimales.",
        8: "Août reste estival mais souvent plus pluvieux que juillet en Europe atlantique. Édimbourg en festival (Fringe, Tattoo) : foule maximale dans la ville. Côté Pacifique nord-ouest (Vancouver, Seattle) : conditions parfaites, sec et chaud (22-26°C). Pluies en hausse en Irlande et Écosse.",
        9: "Septembre est une excellente période sur la côte océanique. Encore chaud (15-19°C), foule en baisse, lumière dorée. Vendanges en cours dans certaines régions. London Fashion Week mi-septembre. Premières couleurs automnales en fin de mois. Idéal pour les visites culturelles. Pluies modérées.",
        10: "Octobre installe l'automne. Couleurs flamboyantes dans les parcs (Hyde Park, Stanley Park Vancouver). Températures qui chutent (10-14°C), pluies plus fréquentes. Halloween très marqué (cultures anglo-saxonnes). Affluence en baisse. Brouillards matinaux sur la Tamise. Saison des soupes et porters en pub.",
        11: "Novembre est le mois le plus gris et le plus pluvieux de l'année océanique. Températures de 6-10°C, journées courtes, pluies fréquentes. Bonfire Night 5 novembre au Royaume-Uni (feux d'artifice). Black Friday fin du mois. Très peu de tourisme. Atmosphère intimiste dans les pubs et théâtres.",
        12: "Décembre apporte l'esprit de Noël aux villes océaniques : marchés (Édimbourg, Hyde Park Winter Wonderland), illuminations spectaculaires (Oxford Street, Champs-Élysées variant), patinoires extérieures. Météo froide et pluvieuse (4-9°C). Affluence forte autour des fêtes. Tarifs élevés mi-fin du mois.",
    },
    'alpine': {
        1: "Janvier est le cœur de la saison de ski alpine. Enneigement généralement optimal après les chutes de décembre. Températures froides (-5 à -15°C en altitude). Journées courtes mais lumière de qualité. Affluence ponctuelle aux vacances scolaires (zones étalées en France). Tarifs élevés en stations, conditions de neige souvent les meilleures.",
        2: "Février est le mois pic de la saison ski : enneigement maximal, météo souvent stable, journées qui s'allongent. Vacances scolaires européennes étalées (toutes zones France + Allemagne + Royaume-Uni + Suisse) : pic d'affluence et de tarifs. Conditions de glisse au meilleur. Risque avalanches modéré à fort, vigilance hors-pistes.",
        3: "Mars combine bonne neige et soleil printanier. Journées qui s'allongent rapidement, lumière intense en altitude. Vacances de printemps en fin de mois (zones). Ski de printemps avec neige profonde le matin, plus molle l'après-midi. Tarifs en légère baisse fin mars. Risques avalanches accrus avec le redoux.",
        4: "Avril marque la transition. Stations d'altitude (au-dessus de 2000m) restent ouvertes avec ski de printemps agréable. Vallées : redoux marqué, fonte rapide. Pâques en pic d'affluence si en avril. Beaucoup de stations basses ferment mi-avril. Saison aux glaciers (Tignes, Zermatt, Hintertux) continue.",
        5: "Mai est entre-deux : neige fond en moyenne montagne, randonnées encore impraticables au-dessus de 1800m. Floraisons spectaculaires en vallées et villages alpins (gentianes, anémones, rhododendrons). Stations ferment, l'été n'a pas démarré. Cascades à plein débit. Peu de monde, bonne période pour villages alpins authentiques.",
        6: "Juin ouvre la saison de randonnée et de montagne. Lacs alpins encore froids, fonte des neiges en cours, cascades spectaculaires. Floraison à étage : rhododendrons en plein éclat. Refuges ouvrent progressivement. Sentiers d'altitude encore enneigés au-dessus de 2500m. Premiers via ferrata accessibles. Solstice et fêtes des feux.",
        7: "Juillet est en pleine saison estivale alpine. Tous les sentiers accessibles. Lacs alpins à 15-18°C (baignade pour braves). Festivals de musique de montagne. Refuges complets : réserver des semaines à l'avance. Tour de France passe souvent dans les Alpes mi-juillet. Affluence forte mais montagnes vastes.",
        8: "Août prolonge la haute saison alpine. Vacances européennes = randonneurs, alpinistes, familles. Conditions au top en altitude (10-25°C). Orages d'après-midi fréquents : départ matinal recommandé. Edelweiss en fleurs. Récolte des génépis. Fin de mois : premières gelées en haute altitude annoncent l'automne.",
        9: "Septembre est un excellent mois pour la montagne : foule en baisse, températures encore agréables (12-22°C), conditions stables, lumière dorée. Mélèzes commencent à virer au jaune en fin de mois. Refuges encore ouverts jusqu'à mi-octobre. Idéal pour les grandes randonnées et les sommets accessibles. Champignons.",
        10: "Octobre installe l'automne alpin. Couleurs spectaculaires des mélèzes (or éclatant) et hêtres en vallée. Premières neiges en altitude. Refuges ferment progressivement. Randonnées encore accessibles en moyenne montagne. Brames du cerf (rut) en forêt. Tarifs en plancher entre les saisons.",
        11: "Novembre est la basse saison absolue. Conditions instables : neige, pluie, brouillards. Stations préparent l'ouverture (mi à fin novembre selon enneigement). Randonnée pédestre limitée. Activité réduite dans les villages alpins. Bonne période pour les amateurs de calme absolu et de gastronomie locale.",
        12: "Décembre lance officiellement la saison de ski. Ouverture progressive des stations (autour du 15). Marchés de Noël dans villages alpins (Bavière, Tyrol). Vacances de Noël : pic d'affluence, tarifs maximaux, neige souvent au rendez-vous. Réveillon en station, ambiance festive. Réservation 6 mois à l'avance.",
    },
}


# ─────────────────────────────────────────────────────────────────────────────
# EN — traductions adaptées (pas littérales, adaptées aux références anglo)
# ─────────────────────────────────────────────────────────────────────────────

INSIGHTS_EN = {
    'continental': {
        1: "January is the heart of continental winter. Short days (sunrise around 8am, sunset around 5pm), frequent frost, snow possible at low altitudes. Season of indoor markets, museums, and urban spas. Winter sales across most European countries. Outside of school holidays, hotel rates drop sharply and tourist sites are nearly empty.",
        2: "February extends winter but days noticeably lengthen. Carnivals in Venice, Cologne, Basel, Nice. European school holidays staggered by zones (variable crowds). Valentine's Day and city-break deals. Weather still cold but bonus: photogenic winter light and morning fog over rivers.",
        3: "March kicks off the transition to spring. First blooms by late month (crocuses, daffodils, magnolias). Mornings still chilly. Life returns to urban parks. Paris Marathon often in April, but preparations visible in March. Easter sometimes falls late month (peak crowds and rates).",
        4: "April unfolds continental spring: blossoming trees, terraces reopening, first 65-70°F days. Capricious weather (frequent showers). Tulips in Holland, cherry blossoms in Germany. Easter peak crowds. Excellent shoulder season before the high season.",
        5: "May is one of the best months to visit continental European cities. Mild temperatures (60-72°F), long light, gardens in full bloom. May 1 and May 8 holidays create mini-peaks in crowds. Spring festivals (Cannes on the Med side, indie festivals everywhere). No mosquitoes yet.",
        6: "June opens summer: longest days of the year (solstice June 21), packed terraces, outdoor music festivals. Pleasant temperatures (68-79°F) before July heatwaves. World Music Day June 21 across France and Europe. Just before the summer school holiday surge.",
        7: "July is peak tourist season. Heat established (77-90°F), occasionally heatwave-level by late month. Outdoor festivals (Avignon, Tomorrowland, Roskilde). Maximum crowds in capitals. Hotel rates at their highest. Long evenings outdoors thanks to extended daylight. Book very early.",
        8: "August stays summery but many locals leave on vacation. Some cities (Paris, Milan) empty of residents, creating a strange atmosphere: many tourists, but some neighborhood shops closed. Weather: hot, summer thunderstorms possible. Peak of the traditional 'mid-August' heatwave.",
        9: "September signals the return to normal: back-to-school season, rates dropping, weather still mild (64-77°F). Golden late-summer light, grape harvest underway in wine regions. One of the best times to visit: climate comfort and reduced crowds. Fall marathons in planning.",
        10: "October installs autumn. Spectacular tree colors (maples, beeches, oaks), especially photogenic by late month. Tipping temperatures (50-64°F), more frequent rain. All Saints' holiday by late month (punctual crowds). Halloween increasingly marked in European cities.",
        11: "November is the least touristy month of the year in most continental European cities. Gray weather, short days, first frosts. Rock-bottom rates. Good time for museums (short waits), winter cuisine starts. Beaujolais Nouveau released on the third Thursday.",
        12: "December transforms cities with Christmas markets (Strasbourg, Vienna, Nuremberg, Prague). Light displays, mulled wine, unique atmosphere. Heavy weekend crowds and around December 24-25. Cold weather, possible snow. High rates around the holidays. Worth experiencing at least once.",
    },
    'mediterranean': {
        1: "January is mild and bright on the Mediterranean (50-59°F daytime highs). Sea too cold for swimming but skies often blue. Lemon and orange trees in fruit. Tourist low season: bargain rates, sites nearly empty. Ideal for culture and gastronomy without the summer crowds. Cool winds possible (Mistral, Tramontane).",
        2: "February sees almond trees in bloom, first sign of Mediterranean spring. Nice, Limoux, Sitges Carnivals. Temperatures gradually rising (54-63°F). Sea still cool. Good time for coastal hiking, littoral paths still quiet. Photogenic winter light.",
        3: "March brings Mediterranean spring. Mimosa in full bloom (French Riviera, Andalusia). Pleasant temperatures (57-66°F). First terraces reopen. Sea still cold (57°F). Lemon Festival in Menton. Occasional rains. Good time to discover nature exploding before high season.",
        4: "April is one of the best months for the Mediterranean. Spectacular blooms (wisteria, bougainvillea, olive trees), mild temperatures (61-70°F), lengthening light. Easter creates a crowd peak by late month. Sea still cool (59-61°F) but mostly blue skies. Ideal for cultural visits and hiking.",
        5: "May marks the awakening of summer season. Temperatures of 66-77°F, sea warming (63-66°F). Cannes Film Festival mid-May. Tour des Bouches du Rhône. Prickly pears start. Still before the major tourist influx. Mild evenings, taverna terraces. Excellent weather/crowd compromise.",
        6: "June truly opens Mediterranean summer. Warm sea (70-73°F), long days, temperatures of 75-84°F. Still tolerable before heatwaves. Festivals stack up (Hellfest, World Music Day, Provence Jazz). Sharp rate increases by late month. Coastal bliss without the July-August suffocation.",
        7: "July is absolute peak season: packed beaches, temperatures 82-95°F, sea at 75-79°F, lingering seaside evenings. Heatwave risk inland (Provence, Andalusia). Maximum crowds, highest rates. Restaurant reservations essential seaside. Iconic Mediterranean summer.",
        8: "August extends July, even hotter. Frequent heatwave peaks (95-104°F in some regions). Warm sea (77-81°F). Maximum crowds, high rates. Avignon Festival, Calvi on the Rocks, Sziget in Hungary. No rain. Good idea: prioritize early morning visits, afternoon siestas.",
        9: "September is often considered the best Mediterranean month. Water still warm (75-77°F), crowds thinning after the 15th, constant sun, milder temperatures (75-84°F). Grape harvests in Provence and Andalusia. Fall festivals begin. Golden light ideal for photography. Perfect compromise.",
        10: "October brings autumn softness. Still pleasant for beaches early month (sea at 72°F, air 72-79°F). More frequent rains in the second half. All Saints' holiday = crowd peak. Mushrooms, chestnuts, new olive oil. Autumn colors on inland massifs. Rates dropping.",
        11: "November is calm and cool on the Mediterranean (55-66°F). Wind and rain more frequent. Crowds absent, rates very low. Truffle season (Provence), new olive oil, young wines. Good time to visit ancient sites without crowds (Paestum, Ostia, Tarragona). Superb winter light.",
        12: "December brings mild but humid climate (52-61°F). Christmas markets in Aix, Marseille, Barcelona. Sometimes heavy rain. Sea too cold for swimming (61°F) but magnificent coastal trails in clear weather. Peak rates only around the holidays, rock-bottom before and after.",
    },
    'tropical': {
        1: "January falls in the heart of dry season for most northern hemisphere tropical destinations (Caribbean, Southeast Asia, Mexico). Constant sun, minimal rain, temperatures 82-90°F, manageable humidity. Peak tourist season: highest rates, packed beaches. Booking well in advance essential.",
        2: "February extends the dry season with often optimal conditions: less humid than January, constant sun, warm sea. Southern hemisphere (Bali, Polynesia, north Australia) in peak wet season: daily tropical showers, but brief. Rio Carnival by late month (Brazil crowd surge).",
        3: "March ends high season in northern tropical destinations. Excellent conditions, temperatures slightly rising (84-91°F). Diving and snorkeling at their best (excellent visibility). Southern hemisphere: end of rainy season. Holi in India marking spring's arrival. Spring Break surge on Caribbean side.",
        4: "April is an excellent transition month. Northern tropics: still dry, high temperatures (86-93°F), before rains. Southern hemisphere (Australia, Bali): conditions stabilizing, end of wet season. Songkran (Thai New Year) mid-April: water festivities, strong crowds in Southeast Asia. Sea still warm.",
        5: "May tips toward wet season in northern tropics. First tropical showers in late day (often brief). Temperatures remain at 86-91°F, humidity more marked (70-85%). Rates dropping, crowds disappearing. Diving still possible mornings. Bali begins its beautiful dry season.",
        6: "June marks the start of wet season in northern tropics (Southeast Asian monsoon, Caribbean rainy season). Daily rains but often late-day. Hotel rates sometimes half-price. Southern hemisphere (Bali, Tahiti): full dry season, ideal conditions, magnificent light.",
        7: "July is in full monsoon mode in Southeast Asia (west Thailand, Cambodia, central Vietnam). Caribbean: early hurricane season (still low risk). Southern hemisphere: Bali and Polynesia peak, blue sky, perfect temperatures (79-84°F), best surf. Southern Brazil: mild, dry winter.",
        8: "August is the most humid monsoon month in Asia. Intense rains but often localized. European holidays = surge despite weather. Southern hemisphere (Bali, north Australia): perfect conditions, dry, sunny. Galápagos dry-season peak. Esala Perahera festival in Sri Lanka.",
        9: "September is peak Caribbean hurricane season (max risk, watch closely). True tropics: heavy rains. Very low rates, no crowds. Southern hemisphere: transition end of dry season in southern Southeast Asia. Bali end of beautiful season. Often a good month to stay away from tropical Atlantic.",
        10: "October sees Caribbean hurricane season declining by month's end. Rains thinning in Southeast Asia. Gradual tourism recovery. Rates still low. India: end of monsoon, Diwali late month (light festivities). Bali: transition to wet season (end of month).",
        11: "November marks the return of dry season in northern tropics. Conditions improve rapidly, diving becomes excellent again. Crowds still absent, rates low. Good window before December rush. Thailand: Loy Krathong (floating lantern festival). Southern hemisphere entering wet season.",
        12: "December launches tropical high season (northern hemisphere). Sun returns, perfect temperatures (82-88°F), warm sea. Christmas holidays: highest rates, packed beaches. Reservations way in advance. Southern hemisphere: Bali, north Australia in peak wet season. Australian carnival and Pacific festivals.",
    },
    'oceanic': {
        1: "January is the heart of oceanic winter: temperatures 39-48°F, frequent rain, wind. Short days (sunrise 8-9am, sunset 4-5pm). Cozy atmosphere: pubs, breweries, museums, theaters. Tourist rates at their lowest. Excellent for cultural cities (London, Dublin, Edinburgh, Vancouver) far from crowds.",
        2: "February stays wintry but light returns. Valentine's Day and city-break deals. Winter storms still active in North Atlantic. First signs of spring by late month (snowdrops, early daffodils). Carnival in Cologne, Rotterdam. Very low crowds. Ideal for discovering walled cities without tourists.",
        3: "March starts oceanic spring. Early blooms in gardens (camellias, magnolias). Temperatures still cool (45-54°F). Typical drizzle but episodic. Paris Marathon (end of month, usually April). St. Patrick's Day March 17 (Dublin and Irish cities: huge crowds). Light noticeably lengthening.",
        4: "April unfolds spring on the Atlantic side. Tulips (Netherlands, Keukenhof), daffodils, first cherry blossoms. Temperatures of 50-59°F, frequent showers (typical April). Easter varies by year (crowds and rates). Good time for urban tourism before summer high season.",
        5: "May is probably the best month for oceanic destinations: spectacular blooms, mild temperatures (55-64°F), long days, less rain than April. Chelsea Flower Show in London. Eurovision finale. Before summer rush. Parks and gardens at their peak.",
        6: "June offers the longest days of the year (solstice June 21, in Scotland near-continuous sun by July). Mild temperatures (59-68°F). Rose season in English parks. Wimbledon starts late June. Still temperate climate, summer crowds settling in gradually. Excellent for evening walks.",
        7: "July is the warmest month (64-73°F highs). Very variable weather on Atlantic side: alternating sun/rain. Outdoor summer festivals (Glastonbury late June, Hyde Park summer concerts). Strong tourist crowds. Pleasant evenings outdoors. Pacific Northwest side: dry and sunny, optimal conditions.",
        8: "August stays summery but often rainier than July in Atlantic Europe. Edinburgh in festival (Fringe, Tattoo): maximum crowds in the city. Pacific Northwest (Vancouver, Seattle): perfect conditions, dry and warm (72-79°F). Rains increase in Ireland and Scotland.",
        9: "September is an excellent period on the oceanic coast. Still warm (59-66°F), crowds dropping, golden light. Grape harvests underway in some regions. London Fashion Week mid-September. First fall colors by late month. Ideal for cultural visits. Moderate rains.",
        10: "October installs autumn. Flamboyant colors in parks (Hyde Park, Stanley Park Vancouver). Temperatures dropping (50-57°F), more frequent rains. Halloween very marked (Anglo-Saxon cultures). Crowds dropping. Morning fog on the Thames. Soup and porter season in pubs.",
        11: "November is the grayest and rainiest oceanic month of the year. Temperatures of 43-50°F, short days, frequent rains. Bonfire Night November 5 in UK (fireworks). Black Friday late month. Very little tourism. Intimate atmosphere in pubs and theaters.",
        12: "December brings Christmas spirit to oceanic cities: markets (Edinburgh, Hyde Park Winter Wonderland), spectacular illuminations (Oxford Street), outdoor ice rinks. Cold and rainy weather (39-48°F). Heavy crowds around the holidays. High rates mid-to-late month.",
    },
    'alpine': {
        1: "January is the heart of alpine ski season. Snow cover generally optimal after December storms. Cold temperatures (23 to 5°F at altitude). Short days but quality light. Punctual crowds at school holidays (French zones staggered). High resort rates, snow conditions often at their best.",
        2: "February is the peak month of ski season: maximum snow cover, often stable weather, lengthening days. European school holidays staggered (all French zones + Germany + UK + Switzerland): peak crowds and rates. Best skiing conditions. Moderate to high avalanche risk, watch off-piste.",
        3: "March combines good snow with spring sun. Days lengthening rapidly, intense light at altitude. Spring break by late month (zones). Spring skiing with deep snow morning, softer afternoon. Rates slightly dropping late March. Increased avalanche risks with warming.",
        4: "April marks the transition. High-altitude resorts (above 6,500ft) stay open with pleasant spring skiing. Valleys: marked warming, rapid melt. Easter at peak crowds if in April. Many low resorts close mid-April. Glacier season (Tignes, Zermatt, Hintertux) continues.",
        5: "May is in-between: snow melts in mid-mountain, hikes still impractical above 5,900ft. Spectacular blooms in valleys and alpine villages (gentians, anemones, rhododendrons). Resorts close, summer hasn't started. Waterfalls at peak flow. Few people, good time for authentic alpine villages.",
        6: "June opens hiking and mountain season. Alpine lakes still cold, snowmelt underway, spectacular waterfalls. Tiered blooms: rhododendrons at peak. Mountain huts opening gradually. High-altitude trails still snowy above 8,200ft. First via ferrata accessible. Solstice and bonfire festivals.",
        7: "July is in full alpine summer season. All trails accessible. Alpine lakes at 59-64°F (swimming for the brave). Mountain music festivals. Mountain huts full: book weeks ahead. Tour de France often passes through the Alps mid-July. Strong crowds but vast mountains.",
        8: "August extends alpine high season. European holidays = hikers, climbers, families. Top conditions at altitude (50-77°F). Frequent afternoon thunderstorms: early start recommended. Edelweiss in bloom. Harvest of génépy. End of month: first high-altitude frosts announce autumn.",
        9: "September is an excellent mountain month: dropping crowds, still pleasant temperatures (54-72°F), stable conditions, golden light. Larches start turning yellow by late month. Huts still open until mid-October. Ideal for long hikes and accessible summits. Mushrooms.",
        10: "October installs alpine autumn. Spectacular larch colors (brilliant gold) and beeches in valleys. First snow at altitude. Huts gradually close. Hiking still accessible in mid-mountain. Deer rut in forests. Rock-bottom rates between seasons.",
        11: "November is absolute low season. Unstable conditions: snow, rain, fog. Resorts preparing to open (mid-to-late November depending on snow). Limited pedestrian hiking. Reduced activity in alpine villages. Good time for fans of absolute calm and local gastronomy.",
        12: "December officially launches ski season. Gradual resort openings (around the 15th). Christmas markets in alpine villages (Bavaria, Tyrol). Christmas holidays: peak crowds, maximum rates, snow usually present. New Year's Eve in resort, festive atmosphere. Book 6 months in advance.",
    },
}


# ─────────────────────────────────────────────────────────────────────────────
# EN-US — variant adapté à l'audience américaine (référence Vegas, Aspen…)
# ─────────────────────────────────────────────────────────────────────────────

# Pour EN-US, on réutilise le contenu EN (déjà en anglais international compatible US)
INSIGHTS_EN_US = INSIGHTS_EN


# ─────────────────────────────────────────────────────────────────────────────
# ES
# ─────────────────────────────────────────────────────────────────────────────

INSIGHTS_ES = {
    'continental': {
        1: "Enero marca el corazón del invierno continental. Días cortos (amanecer 8h, anochecer 17h), heladas frecuentes, nieve posible incluso en llanuras. Temporada de mercados cubiertos, museos y termas urbanas. Rebajas de invierno en la mayoría de países europeos. Fuera de vacaciones escolares, tarifas hoteleras bajas y sitios turísticos casi vacíos.",
        2: "Febrero prolonga el invierno pero los días se alargan visiblemente. Carnavales en Venecia, Colonia, Basilea, Niza. Vacaciones escolares europeas escalonadas por zonas (afluencia variable). San Valentín y ofertas city-break. Tiempo aún frío pero bono: luz invernal fotogénica y nieblas matinales sobre los ríos.",
        3: "Marzo inicia la transición hacia la primavera. Primeras floraciones a finales de mes (azafranes, narcisos, magnolios). Mañanas aún frescas. Vuelve la vida a los parques urbanos. Pascua a veces a finales de mes (afluencia y tarifas altas).",
        4: "Abril despliega la primavera continental: árboles en flor, terrazas reabriendo, primeros días a 18-20°C. Tiempo caprichoso (lluvias frecuentes). Tulipanes en Holanda, cerezos en Alemania. Pascua en pico de afluencia. Buena temporada antes de la alta.",
        5: "Mayo es uno de los mejores meses para visitar ciudades de Europa continental. Temperaturas suaves (15-22°C), luz larga, jardines en plena floración. Días festivos 1 y 8 de mayo crean micro-picos. Festivales primaverales (Cannes en Mediterráneo, festivales indie). Sin mosquitos.",
        6: "Junio abre el verano: días más largos del año (solsticio 21 junio), terrazas llenas, festivales de música al aire libre. Temperaturas agradables (20-26°C) antes de olas de calor de julio. Fiesta de la Música 21 junio en Francia y Europa. Antes del aluvión vacacional escolar.",
        7: "Julio está en plena alta temporada turística. Calor establecido (25-32°C), a veces ola de calor a finales. Festivales al aire libre (Avignon, Tomorrowland, Roskilde). Máxima afluencia en capitales. Tarifas hoteleras al máximo. Veladas animadas hasta tarde por días largos. Reservar muy con antelación.",
        8: "Agosto sigue siendo veraniego pero muchos locales se van de vacaciones. Algunas ciudades (París, Milán) se vacían de habitantes, creando ambiente extraño: muchos turistas, pero algunos comercios de barrio cerrados. Tiempo: caluroso, posibles tormentas estivales. Pico de la canícula tradicional 'medio-agosto'.",
        9: "Septiembre marca la vuelta a la normalidad: regreso a clases, tarifas bajando, tiempo aún suave (18-25°C). Luz dorada de fin de verano, vendimias en regiones vinícolas. Una de las mejores épocas: confort climático y afluencia reducida. Maratones de otoño en planificación.",
        10: "Octubre instala el otoño. Colores espectaculares en árboles (arces, hayas, robles), fotogénicos sobre todo a finales. Temperaturas que basculan (10-18°C), lluvias más frecuentes. Vacaciones de Todos los Santos a finales (afluencia puntual). Halloween cada vez más marcado.",
        11: "Noviembre es el mes menos turístico del año en la mayoría de ciudades europeas continentales. Tiempo gris, días cortos, primeras heladas. Tarifas en mínimos. Buen momento para museos (poca espera), gastronomía invernal arranca. Beaujolais Nouveau tercer jueves del mes.",
        12: "Diciembre transforma las ciudades con mercados de Navidad (Estrasburgo, Viena, Núremberg, Praga). Decoraciones luminosas, vino caliente, ambiente único. Afluencia alta los fines de semana y alrededor del 24-25. Tiempo frío, nieve posible. Tarifas altas en fiestas. Vivir al menos una vez por el ambiente.",
    },
    'mediterranean': {
        1: "Enero es suave y luminoso en el Mediterráneo (10-15°C de máxima). Mar demasiado frío para bañarse pero cielo a menudo azul. Limoneros y naranjos con fruta. Temporada baja turística: tarifas bajas, sitios casi vacíos. Ideal para cultura y gastronomía sin la multitud estival. Viento fresco posible (Mistral, Tramontana).",
        2: "Febrero ve a los almendros florecer, primer signo de primavera mediterránea. Carnaval de Niza, Limoux, Sitges. Temperaturas subiendo suavemente (12-17°C). Mar aún fresco. Buena temporada para senderismo costero, senderos del litoral aún poco frecuentados. Luz invernal fotogénica.",
        3: "Marzo trae la primavera mediterránea. Mimosa en plena floración (Costa Azul, Andalucía). Temperaturas agradables (14-19°C). Primeras terrazas reabren. Mar aún frío (14°C). Festival del Limón en Menton. Lluvias episódicas. Buena temporada para descubrir la naturaleza explotando antes de la alta temporada.",
        4: "Abril es uno de los mejores meses para el Mediterráneo. Floraciones espectaculares (glicinas, buganvillas, olivos), temperaturas suaves (16-21°C), luz que se alarga. Pascua crea un pico de afluencia a finales. Mar aún fresco (15-16°C) pero cielo azul mayoritario. Ideal para visitas culturales y senderismo.",
        5: "Mayo marca el despertar de la temporada estival. Temperaturas de 19-25°C, mar calentándose (17-19°C). Festival de Cannes mediados de mayo. Higos chumbos empiezan. Aún antes del gran afluencia turística. Veladas suaves, taberna en terraza. Excelente compromiso tiempo/afluencia.",
        6: "Junio realmente abre el verano mediterráneo. Mar cálido (21-23°C), días largos, temperaturas de 24-29°C. Aún tolerable antes de olas de calor. Festivales se suceden (Hellfest, Fiesta de la Música, Provence Jazz). Subida marcada de tarifas a finales. La dicha costera sin la sofocación de julio-agosto.",
        7: "Julio es la alta temporada absoluta: playas abarrotadas, temperaturas 28-35°C, mar a 24-26°C, veladas tardías frente al mar. Riesgo de ola de calor en el interior (Provenza, Andalucía). Afluencia máxima, tarifas al máximo. Reserva obligatoria de restaurantes frente al mar. Verano mediterráneo icónico.",
        8: "Agosto prolonga julio aún más caluroso. Picos de ola de calor frecuentes (35-40°C en algunas regiones). Mar cálido (25-27°C). Multitud máxima, tarifas altas. Festival de Avignon, Calvi on the Rocks, Sziget en Hungría. Sin lluvias. Buena idea: priorizar horas matinales para visitas, siesta por la tarde.",
        9: "Septiembre es a menudo considerado el mejor mes del Mediterráneo. Agua aún cálida (24-25°C), multitud disminuyendo tras el 15, sol constante, temperaturas más suaves (24-29°C). Vendimias en Provenza y Andalucía. Festivales de otoño arrancan. Luz dorada ideal fotografía. Compromiso perfecto.",
        10: "Octubre instala la suavidad otoñal. Aún agradable para playa a principio de mes (mar a 22°C, aire 22-26°C). Lluvias más frecuentes en segunda quincena. Vacaciones de Todos los Santos = pico de afluencia. Setas, castañas, aceite nuevo. Colores otoñales en macizos interiores. Tarifas bajando.",
        11: "Noviembre es tranquilo y fresco en el Mediterráneo (13-19°C). Viento y lluvias más frecuentes. Multitud ausente, tarifas muy bajas. Temporada de trufas (Provenza), del aceite nuevo, vinos jóvenes. Buena temporada para visitar sitios antiguos sin multitud (Paestum, Ostia, Tarragona). Luz invernal soberbia.",
        12: "Diciembre aporta clima suave pero húmedo (11-16°C). Mercados de Navidad en Aix, Marsella, Barcelona. Lluvias a veces fuertes. Mar demasiado frío para bañarse (16°C) pero senderos costeros magníficos con tiempo despejado. Tarifas en pico solo alrededor de fiestas, mínimo antes y después.",
    },
    'tropical': {
        1: "Enero está en plena estación seca en la mayoría de destinos tropicales del hemisferio norte (Caribe, Sudeste Asiático, México). Sol constante, poca lluvia, temperaturas 28-32°C, humedad soportable. Alta temporada turística: tarifas al máximo, playas abarrotadas. Reserva imperativa muy con antelación.",
        2: "Febrero prolonga la estación seca, condiciones a menudo óptimas: menos húmedo que enero, sol constante, mar cálido. Hemisferio sur (Bali, Polinesia, norte Australia) en plena estación húmeda: aguaceros tropicales diarios, pero cortos. Carnaval de Río a finales (afluencia Brasil).",
        3: "Marzo termina la alta temporada en destinos tropicales norte. Muy buenas condiciones, temperaturas subiendo ligeramente (29-33°C). Buceo y snorkel al máximo (visibilidad excelente). Hemisferio sur, fin de estación de lluvias. Holi en India marcando inicio de primavera. Spring Break afluencia Caribe.",
        4: "Abril es un excelente mes de transición. Hemisferio norte tropical: aún seco, temperaturas elevadas (30-34°C), antes de lluvias. Hemisferio sur (Australia, Bali): condiciones se estabilizan, fin estación húmeda. Songkran (año nuevo tailandés) medio-abril: festividades de agua, afluencia fuerte en Sudeste Asiático.",
        5: "Mayo bascula hacia estación húmeda en trópicos del hemisferio norte. Primeros aguaceros tropicales al final del día (a menudo cortos). Temperaturas siguen a 30-33°C, humedad más marcada (70-85%). Tarifas en caída, multitud desaparece. Buceo aún posible mañana. Bali inicia su hermosa temporada seca.",
        6: "Junio marca el inicio de la estación húmeda en trópicos norte (monzón sudeste asiático, estación de lluvias Caribe). Lluvias diarias pero a menudo al final del día. Tarifas hoteleras a veces mitad de precio. Hemisferio sur (Bali, Tahití): plena estación seca, condiciones ideales, luz magnífica.",
        7: "Julio está en pleno monzón en Sudeste Asiático (Tailandia oeste, Camboya, Vietnam centro). Caribe: inicio estación ciclónica (riesgo bajo aún). Hemisferio sur: Bali y Polinesia al máximo, cielo azul, temperaturas perfectas (26-29°C), mejor surf. Brasil sur: invierno suave, seco, agradable.",
        8: "Agosto es el mes más húmedo en monzón asiático. Lluvias intensas pero a menudo localizadas. Vacaciones europeas = afluencia a pesar del tiempo. Hemisferio sur (Bali, Australia norte): condiciones perfectas, secas, soleadas. Pico de temporada seca en Galápagos. Festival Esala Perahera en Sri Lanka.",
        9: "Septiembre es el pico de temporada ciclónica caribeña (riesgo máximo, vigilar). Trópicos verdaderos: lluvias intensas. Tarifas muy bajas, multitud ausente. Hemisferio sur: transición fin temporada seca en sur Sudeste Asiático. Bali fin de hermosa temporada. A menudo un buen mes para mantenerse lejos del Atlántico tropical.",
        10: "Octubre ve la temporada ciclónica caribeña decreciendo a finales. Lluvias se espacian en Sudeste Asiático. Recuperación gradual del turismo. Tarifas aún bajas. India: fin de monzón, Diwali a finales (festividades luminosas). Bali: transición hacia estación húmeda (finales de mes).",
        11: "Noviembre marca el regreso de la estación seca en trópicos norte. Condiciones mejoran rápidamente, buceo vuelve a ser excelente. Multitud aún ausente, tarifas bajas. Buena ventana antes del rush de diciembre. Tailandia: Loy Krathong (festival de linternas flotantes). Hemisferio sur entrando en estación húmeda.",
        12: "Diciembre lanza la alta temporada tropical (hemisferio norte). Vuelve el sol, temperaturas perfectas (28-31°C), mar cálido. Vacaciones de Navidad: tarifas al máximo, playas abarrotadas. Reservas muy con antelación. Hemisferio sur: Bali, norte Australia en plena estación húmeda. Carnaval australiano y fiestas pacíficas.",
    },
    'oceanic': {
        1: "Enero es el corazón del invierno oceánico: temperaturas de 4-9°C, lluvias frecuentes, viento. Días cortos (amanecer 8-9h, anochecer 16-17h). Atmósfera acogedora: pubs, cervecerías, museos, teatros. Tarifas turísticas en mínimos. Excelente para ciudades culturales (Londres, Dublín, Edimburgo, Vancouver) lejos de la multitud.",
        2: "Febrero sigue invernal pero la luz vuelve. San Valentín y ofertas city-break. Tormentas invernales aún activas en Atlántico norte. Primeras señales de primavera a finales (campanillas, narcisos tempranos). Carnaval en Colonia, Róterdam. Afluencia muy baja. Ideal para descubrir ciudades intramuros sin multitud.",
        3: "Marzo inicia la primavera oceánica. Floraciones tempranas en jardines (camelias, magnolios). Temperaturas aún frescas (7-12°C). Lloviznas típicas pero episódicas. Maratón de París (finales de mes, generalmente abril). St Patrick 17 marzo (Dublín y ciudades irlandesas: gran afluencia). Luz alargándose notablemente.",
        4: "Abril despliega la primavera del lado Atlántico. Tulipanes (Países Bajos, Keukenhof), narcisos, primeros cerezos en flor. Temperaturas de 10-15°C, lluvias frecuentes (abril típico). Pascua varía según los años (afluencia y tarifas). Buena temporada para turismo urbano antes de alta temporada estival.",
        5: "Mayo es probablemente el mejor mes para destinos oceánicos: floraciones espectaculares, temperaturas suaves (13-18°C), días largos, menos lluvias que en abril. Chelsea Flower Show en Londres. Final de Eurovisión. Antes del rush estival. Parques y jardines en apogeo.",
        6: "Junio ofrece los días más largos del año (Solsticio 21 junio, en Escocia sol casi continuo en julio). Temperaturas suaves (15-20°C). Temporada de rosas en parques ingleses. Wimbledon arranca finales de junio. Clima aún templado, multitud estival instalándose gradualmente. Excelente para paseos vespertinos.",
        7: "Julio es el mes más cálido (18-23°C de máxima). Tiempo muy variable lado Atlántico: alternancia sol/lluvia. Festivales de verano al aire libre (Glastonbury finales junio, Hyde Park summer concerts). Afluencia turística fuerte. Veladas agradables fuera. Lado Pacífico noroeste: seco y soleado, condiciones óptimas.",
        8: "Agosto sigue veraniego pero a menudo más lluvioso que julio en Europa atlántica. Edimburgo en festival (Fringe, Tattoo): máxima afluencia en la ciudad. Lado Pacífico noroeste (Vancouver, Seattle): condiciones perfectas, seco y cálido (22-26°C). Lluvias aumentan en Irlanda y Escocia.",
        9: "Septiembre es una excelente temporada en costa oceánica. Aún cálido (15-19°C), multitud bajando, luz dorada. Vendimias en curso en algunas regiones. London Fashion Week medio-septiembre. Primeros colores otoñales a finales. Ideal para visitas culturales. Lluvias moderadas.",
        10: "Octubre instala el otoño. Colores flamantes en parques (Hyde Park, Stanley Park Vancouver). Temperaturas cayendo (10-14°C), lluvias más frecuentes. Halloween muy marcado (culturas anglosajonas). Afluencia bajando. Nieblas matinales sobre el Támesis. Temporada de sopas y porters en pub.",
        11: "Noviembre es el mes más gris y lluvioso del año oceánico. Temperaturas de 6-10°C, días cortos, lluvias frecuentes. Bonfire Night 5 noviembre en Reino Unido (fuegos artificiales). Black Friday finales de mes. Muy poco turismo. Atmósfera íntima en pubs y teatros.",
        12: "Diciembre aporta espíritu navideño a ciudades oceánicas: mercados (Edimburgo, Hyde Park Winter Wonderland), iluminaciones espectaculares (Oxford Street), pistas de hielo exteriores. Tiempo frío y lluvioso (4-9°C). Afluencia fuerte alrededor de fiestas. Tarifas altas medio-finales de mes.",
    },
    'alpine': {
        1: "Enero es el corazón de la temporada de esquí alpina. Nevadas generalmente óptimas tras las caídas de diciembre. Temperaturas frías (-5 a -15°C en altitud). Días cortos pero luz de calidad. Afluencia puntual en vacaciones escolares (zonas escalonadas en Francia). Tarifas altas en estaciones, condiciones de nieve a menudo las mejores.",
        2: "Febrero es el mes pico de temporada de esquí: máxima nieve, tiempo a menudo estable, días alargándose. Vacaciones escolares europeas escalonadas (todas zonas Francia + Alemania + Reino Unido + Suiza): pico de afluencia y tarifas. Condiciones de deslizamiento al máximo. Riesgo avalanchas moderado a fuerte, vigilancia fuera-pistas.",
        3: "Marzo combina buena nieve y sol primaveral. Días alargándose rápidamente, luz intensa en altitud. Vacaciones de primavera a finales (zonas). Esquí primaveral con nieve profunda por la mañana, más blanda por la tarde. Tarifas en ligera baja finales de marzo. Riesgos avalanchas acrecentados con el deshielo.",
        4: "Abril marca la transición. Estaciones de altitud (por encima de 2000m) siguen abiertas con esquí primaveral agradable. Valles: deshielo marcado, fusión rápida. Pascua en pico de afluencia si en abril. Muchas estaciones bajas cierran medio-abril. Temporada en glaciares (Tignes, Zermatt, Hintertux) continúa.",
        5: "Mayo es entre-dos: nieve se derrite en media montaña, senderismo aún impracticable por encima de 1800m. Floraciones espectaculares en valles y pueblos alpinos (gencianas, anémonas, rododendros). Estaciones cierran, el verano no ha arrancado. Cascadas a pleno caudal. Poca gente, buena temporada para pueblos alpinos auténticos.",
        6: "Junio abre la temporada de senderismo y montaña. Lagos alpinos aún fríos, deshielo en curso, cascadas espectaculares. Floración por pisos: rododendros en pleno esplendor. Refugios abren progresivamente. Senderos de altitud aún nevados por encima de 2500m. Primeras vías ferratas accesibles. Solsticio y fiestas de fuegos.",
        7: "Julio está en plena temporada estival alpina. Todos los senderos accesibles. Lagos alpinos a 15-18°C (baño para valientes). Festivales de música de montaña. Refugios completos: reservar semanas con antelación. Tour de France pasa a menudo en Alpes medio-julio. Afluencia fuerte pero montañas vastas.",
        8: "Agosto prolonga la alta temporada alpina. Vacaciones europeas = senderistas, alpinistas, familias. Condiciones al máximo en altitud (10-25°C). Tormentas vespertinas frecuentes: salida matinal recomendada. Edelweiss en flor. Cosecha de génépi. Finales: primeras heladas en alta altitud anuncian el otoño.",
        9: "Septiembre es un excelente mes para la montaña: afluencia bajando, temperaturas aún agradables (12-22°C), condiciones estables, luz dorada. Alerces empiezan a virar al amarillo a finales. Refugios aún abiertos hasta medio-octubre. Ideal para grandes senderismos y cumbres accesibles. Setas.",
        10: "Octubre instala el otoño alpino. Colores espectaculares de alerces (oro brillante) y hayas en valle. Primeras nieves en altitud. Refugios cierran progresivamente. Senderismo aún accesible en media montaña. Bramidos del ciervo (celo) en bosque. Tarifas en mínimo entre temporadas.",
        11: "Noviembre es la baja temporada absoluta. Condiciones inestables: nieve, lluvia, nieblas. Estaciones preparan la apertura (medio a finales noviembre según nevada). Senderismo peatonal limitado. Actividad reducida en pueblos alpinos. Buena temporada para amantes de calma absoluta y gastronomía local.",
        12: "Diciembre lanza oficialmente la temporada de esquí. Apertura progresiva de estaciones (alrededor del 15). Mercados de Navidad en pueblos alpinos (Baviera, Tirol). Vacaciones de Navidad: pico de afluencia, tarifas máximas, nieve a menudo presente. Nochevieja en estación, ambiente festivo. Reserva 6 meses con antelación.",
    },
}


# ─────────────────────────────────────────────────────────────────────────────
# DE
# ─────────────────────────────────────────────────────────────────────────────

INSIGHTS_DE = {
    'continental': {
        1: "Januar markiert das Herz des kontinentalen Winters. Kurze Tage (Sonnenaufgang 8 Uhr, Sonnenuntergang 17 Uhr), häufige Fröste, Schnee selbst in den Ebenen möglich. Saison der Markthallen, Museen und städtischen Thermen. Winterschlussverkauf in den meisten europäischen Ländern. Außerhalb der Schulferien stark gesenkte Hotelpreise und fast leere Sehenswürdigkeiten.",
        2: "Februar verlängert den Winter, doch die Tage werden spürbar länger. Karneval in Venedig, Köln, Basel, Nizza. Europäische Schulferien gestaffelt nach Zonen (variable Besucherzahlen). Valentinstag und City-Break-Angebote. Wetter noch kalt, aber Bonus: fotogenes Winterlicht und morgendlicher Nebel über Flüssen.",
        3: "März leitet den Übergang zum Frühling ein. Erste Blüten Ende des Monats (Krokusse, Narzissen, Magnolien). Morgens noch kühl. Leben kehrt in städtische Parks zurück. Paris-Marathon meist im April, aber Vorbereitungen im März sichtbar. Ostern manchmal Monatsende (Hochsaisonpreise und Andrang).",
        4: "April entfaltet den kontinentalen Frühling: blühende Bäume, wiedereröffnete Terrassen, erste Tage mit 18-20°C. Launisches Wetter (häufige Schauer). Tulpen in Holland, Kirschblüten in Deutschland. Osterhochsaison. Ausgezeichnete Übergangszeit vor der Hochsaison.",
        5: "Mai ist einer der besten Monate für Städte im kontinentalen Europa. Milde Temperaturen (15-22°C), langes Licht, blühende Gärten. Feiertage am 1. und 8. Mai erzeugen kleine Andrang-Spitzen. Frühlingsfestivals (Cannes auf der Mittelmeerseite, Indie-Festivals überall). Noch keine Mücken.",
        6: "Juni eröffnet den Sommer: längste Tage des Jahres (Sonnenwende 21. Juni), volle Terrassen, Open-Air-Musikfestivals. Angenehme Temperaturen (20-26°C) vor den Hitzewellen im Juli. Fête de la Musique am 21. Juni in ganz Frankreich und Europa. Kurz vor dem Sommerschulferien-Ansturm.",
        7: "Juli ist Hochsaison. Hitze etabliert (25-32°C), gelegentlich Hitzewelle Ende des Monats. Open-Air-Festivals (Avignon, Tomorrowland, Roskilde). Maximale Besucherzahlen in Hauptstädten. Hotelpreise am höchsten. Lange Abende draußen dank langer Tage. Sehr früh buchen.",
        8: "August bleibt sommerlich, doch viele Einheimische sind im Urlaub. Manche Städte (Paris, Mailand) leeren sich, was eine seltsame Atmosphäre schafft: viele Touristen, doch manche Geschäfte im Viertel geschlossen. Wetter: heiß, mögliche Sommergewitter. Höhepunkt der traditionellen 'Mitte-August'-Hitzewelle.",
        9: "September markiert die Rückkehr zur Normalität: Schulanfang, sinkende Preise, noch mildes Wetter (18-25°C). Goldenes Spätsommerlicht, Weinlese in Weinregionen. Eine der besten Reisezeiten: Klimakomfort und reduzierte Besucherzahlen. Herbstmarathons in Vorbereitung.",
        10: "Oktober installiert den Herbst. Spektakuläre Farben an Bäumen (Ahorn, Buche, Eiche), besonders fotogen Ende des Monats. Kippende Temperaturen (10-18°C), häufigere Regenfälle. Allerheiligen-Ferien Monatsende (punktueller Andrang). Halloween immer stärker in Städten markiert.",
        11: "November ist der touristisch ruhigste Monat des Jahres in den meisten kontinentaleuropäischen Städten. Graues Wetter, kurze Tage, erste Fröste. Tiefste Preise. Gute Zeit für Museen (kurze Wartezeit), Winterküche startet. Beaujolais Nouveau am dritten Donnerstag des Monats.",
        12: "Dezember verwandelt Städte mit Weihnachtsmärkten (Straßburg, Wien, Nürnberg, Prag). Lichterketten, Glühwein, einzigartige Atmosphäre. Starker Andrang an Wochenenden und rund um den 24.-25. Dezember. Kaltes Wetter, möglicher Schnee. Hohe Preise rund um die Feiertage. Mindestens einmal für die Atmosphäre erleben.",
    },
    'mediterranean': {
        1: "Januar ist mild und hell am Mittelmeer (10-15°C tagsüber). Meer zu kalt zum Baden, aber Himmel oft blau. Zitronen- und Orangenbäume tragen Früchte. Touristische Nebensaison: niedrige Preise, fast leere Orte. Ideal für Kultur und Gastronomie ohne Sommermenge. Kühler Wind möglich (Mistral, Tramontana).",
        2: "Februar lässt Mandelbäume blühen, erstes Zeichen mediterranen Frühlings. Karneval in Nizza, Limoux, Sitges. Temperaturen steigen sanft (12-17°C). Meer noch frisch. Gute Zeit für Küstenwanderungen, Küstenpfade noch wenig frequentiert. Fotogenes Winterlicht.",
        3: "März bringt den mediterranen Frühling. Mimose in voller Blüte (Côte d'Azur, Andalusien). Angenehme Temperaturen (14-19°C). Erste Terrassen öffnen wieder. Meer noch kalt (14°C). Zitronenfestival in Menton. Gelegentliche Regenfälle. Gute Zeit, um die explodierende Natur vor der Hochsaison zu entdecken.",
        4: "April ist einer der besten Monate für das Mittelmeer. Spektakuläre Blüten (Glyzinien, Bougainvilleen, Olivenbäume), milde Temperaturen (16-21°C), längeres Licht. Ostern erzeugt Andrangspitze Monatsende. Meer noch frisch (15-16°C), aber meist blauer Himmel. Ideal für Kulturbesuche und Wandern.",
        5: "Mai markiert das Erwachen der Sommersaison. Temperaturen 19-25°C, erwärmendes Meer (17-19°C). Filmfestival Cannes Mitte Mai. Feigenkakteen beginnen. Noch vor dem großen Touristenansturm. Milde Abende, Tavernen-Terrasse. Ausgezeichneter Wetter/Andrangs-Kompromiss.",
        6: "Juni öffnet wirklich den mediterranen Sommer. Warmes Meer (21-23°C), lange Tage, Temperaturen 24-29°C. Noch erträglich vor Hitzewellen. Festivals reihen sich (Hellfest, Fête de la Musique, Provence Jazz). Deutlicher Preisanstieg Monatsende. Küstenglück ohne die Erstickung von Juli-August.",
        7: "Juli ist absolute Hochsaison: überfüllte Strände, Temperaturen 28-35°C, Meer bei 24-26°C, späte Strandabende. Hitzewellenrisiko im Landesinneren (Provence, Andalusien). Maximaler Andrang, höchste Preise. Restaurantreservierung am Meer obligatorisch. Ikonischer mediterraner Sommer.",
        8: "August verlängert Juli noch heißer. Häufige Hitzewellenspitzen (35-40°C in einigen Regionen). Warmes Meer (25-27°C). Maximale Menschenmenge, hohe Preise. Avignon-Festival, Calvi on the Rocks, Sziget in Ungarn. Kein Regen. Gute Idee: Vormittags Besichtigungen priorisieren, Siesta am Nachmittag.",
        9: "September gilt oft als bester Mittelmeer-Monat. Wasser noch warm (24-25°C), Menge schwindet nach dem 15., konstante Sonne, mildere Temperaturen (24-29°C). Weinlese in Provence und Andalusien. Herbstfestivals beginnen. Goldenes Licht ideal für Fotografie. Perfekter Kompromiss.",
        10: "Oktober installiert herbstliche Sanftheit. Anfang Monats noch angenehm für den Strand (Meer 22°C, Luft 22-26°C). Häufigere Regenfälle in der zweiten Monatshälfte. Allerheiligen = Andrangsspitze. Pilze, Kastanien, neues Olivenöl. Herbstfarben an Binnengebirgen. Sinkende Preise.",
        11: "November ist ruhig und kühl am Mittelmeer (13-19°C). Wind und Regen häufiger. Menge abwesend, Preise sehr niedrig. Trüffel-Saison (Provence), neues Olivenöl, junge Weine. Gute Zeit, antike Stätten ohne Menge zu besuchen (Paestum, Ostia, Tarragona). Hervorragendes Winterlicht.",
        12: "Dezember bringt mildes, aber feuchtes Klima (11-16°C). Weihnachtsmärkte in Aix, Marseille, Barcelona. Manchmal kräftige Regenfälle. Meer zu kalt zum Baden (16°C), aber bei klarem Wetter herrliche Küstenpfade. Spitzenpreise nur rund um die Feiertage, Tiefstand davor und danach.",
    },
    'tropical': {
        1: "Januar liegt mitten in der Trockenzeit in den meisten tropischen Reisezielen der Nordhalbkugel (Karibik, Südostasien, Mexiko). Konstante Sonne, wenig Regen, Temperaturen 28-32°C, erträgliche Feuchtigkeit. Touristische Hochsaison: höchste Preise, überfüllte Strände. Sehr frühe Buchung unverzichtbar.",
        2: "Februar verlängert die Trockenzeit, oft optimale Bedingungen: weniger feucht als im Januar, konstante Sonne, warmes Meer. Südhalbkugel (Bali, Polynesien, Nord-Australien) in der Regenzeit-Hochphase: tägliche tropische Schauer, aber kurz. Karneval von Rio Monatsende (Brasilien-Andrang).",
        3: "März beendet die Hochsaison in nordtropischen Reisezielen. Sehr gute Bedingungen, leicht steigende Temperaturen (29-33°C). Tauchen und Schnorcheln top (ausgezeichnete Sicht). Südhalbkugel: Ende der Regenzeit. Holi in Indien zum Frühlingsbeginn. Spring Break-Andrang in der Karibik.",
        4: "April ist ein ausgezeichneter Übergangsmonat. Nordtropen: noch trocken, hohe Temperaturen (30-34°C), vor dem Regen. Südhalbkugel (Australien, Bali): Bedingungen stabilisieren sich, Ende Regenzeit. Songkran (thailändisches Neujahr) Mitte April: Wasserfeste, starker Andrang in Südostasien.",
        5: "Mai kippt zur Regenzeit in den Nordtropen. Erste tropische Schauer am späten Tag (oft kurz). Temperaturen bleiben bei 30-33°C, ausgeprägtere Feuchtigkeit (70-85%). Preise fallen, Mengen verschwinden. Tauchen morgens noch möglich. Bali beginnt seine schöne Trockenzeit.",
        6: "Juni markiert den Beginn der Regenzeit in den Nordtropen (südostasiatischer Monsun, karibische Regenzeit). Tägliche Regenfälle, aber oft am Tagesende. Hotelpreise manchmal halbiert. Südhalbkugel (Bali, Tahiti): volle Trockenzeit, ideale Bedingungen, prächtiges Licht.",
        7: "Juli ist in vollem Monsun in Südostasien (West-Thailand, Kambodscha, Zentral-Vietnam). Karibik: Beginn der Hurrikan-Saison (noch geringes Risiko). Südhalbkugel: Bali und Polynesien top, blauer Himmel, perfekte Temperaturen (26-29°C), beste Surfbedingungen. Süd-Brasilien: milder, trockener Winter.",
        8: "August ist der feuchteste Monat im asiatischen Monsun. Intensive, aber oft lokalisierte Regenfälle. Europäische Ferien = Andrang trotz Wetter. Südhalbkugel (Bali, Nord-Australien): perfekte Bedingungen, trocken, sonnig. Höhepunkt der Trockenzeit auf den Galápagos. Esala Perahera-Festival in Sri Lanka.",
        9: "September ist Höhepunkt der karibischen Hurrikan-Saison (maximales Risiko, beobachten). Echte Tropen: starke Regenfälle. Sehr niedrige Preise, keine Menschenmenge. Südhalbkugel: Übergang Ende Trockenzeit in Süd-Südostasien. Bali Ende der schönen Saison. Oft ein guter Monat, sich vom tropischen Atlantik fernzuhalten.",
        10: "Oktober sieht die karibische Hurrikan-Saison Monatsende abklingen. Regenfälle in Südostasien werden seltener. Allmähliche Tourismus-Erholung. Preise noch niedrig. Indien: Ende des Monsuns, Diwali Monatsende (Lichterfest). Bali: Übergang zur Regenzeit (Monatsende).",
        11: "November markiert die Rückkehr der Trockenzeit in den Nordtropen. Bedingungen verbessern sich schnell, Tauchen wird wieder ausgezeichnet. Mengen noch abwesend, niedrige Preise. Gutes Fenster vor dem Dezember-Rush. Thailand: Loy Krathong (Lichterfest auf Wasser). Südhalbkugel beginnt Regenzeit.",
        12: "Dezember startet die tropische Hochsaison (Nordhalbkugel). Sonne kehrt zurück, perfekte Temperaturen (28-31°C), warmes Meer. Weihnachtsferien: höchste Preise, überfüllte Strände. Reservierungen weit im Voraus. Südhalbkugel: Bali, Nord-Australien in der Regenzeit-Hochphase. Australischer Karneval und pazifische Feste.",
    },
    'oceanic': {
        1: "Januar ist das Herz des ozeanischen Winters: Temperaturen 4-9°C, häufige Regenfälle, Wind. Kurze Tage (Sonnenaufgang 8-9 Uhr, Sonnenuntergang 16-17 Uhr). Gemütliche Atmosphäre: Pubs, Brauereien, Museen, Theater. Tourismuspreise am niedrigsten. Ausgezeichnet für Kulturstädte (London, Dublin, Edinburgh, Vancouver) abseits der Menge.",
        2: "Februar bleibt winterlich, doch Licht kehrt zurück. Valentinstag und City-Break-Angebote. Winterstürme noch aktiv im Nordatlantik. Erste Frühlingszeichen Monatsende (Schneeglöckchen, frühe Narzissen). Karneval in Köln, Rotterdam. Sehr geringer Andrang. Ideal, Innenstädte ohne Menschenmenge zu entdecken.",
        3: "März startet den ozeanischen Frühling. Frühe Blüten in Gärten (Kamelien, Magnolien). Temperaturen noch kühl (7-12°C). Typischer Nieselregen, aber episodisch. Paris-Marathon (Monatsende, normalerweise April). St. Patrick's Day 17. März (Dublin und irische Städte: großer Andrang). Licht verlängert sich deutlich.",
        4: "April entfaltet den Frühling auf der Atlantikseite. Tulpen (Niederlande, Keukenhof), Narzissen, erste Kirschblüten. Temperaturen 10-15°C, häufige Schauer (typischer April). Ostern variiert je nach Jahr (Andrang und Preise). Gute Zeit für Stadttourismus vor der Sommerhochsaison.",
        5: "Mai ist wahrscheinlich der beste Monat für ozeanische Ziele: spektakuläre Blüten, milde Temperaturen (13-18°C), lange Tage, weniger Regen als im April. Chelsea Flower Show in London. Eurovisionsfinale. Vor dem Sommer-Rush. Parks und Gärten in Höchstform.",
        6: "Juni bietet die längsten Tage des Jahres (Sonnenwende 21. Juni, in Schottland fast durchgehend Sonne im Juli). Milde Temperaturen (15-20°C). Rosensaison in englischen Parks. Wimbledon startet Ende Juni. Noch gemäßigtes Klima, Sommermenge stellt sich allmählich ein. Ausgezeichnet für Abendspaziergänge.",
        7: "Juli ist der wärmste Monat (18-23°C Höchstwerte). Sehr variables Wetter auf der Atlantikseite: abwechselnd Sonne/Regen. Sommer-Open-Air-Festivals (Glastonbury Ende Juni, Hyde Park Summer Concerts). Starker Touristenandrang. Angenehme Abende draußen. Pazifischer Nordwesten: trocken und sonnig, optimale Bedingungen.",
        8: "August bleibt sommerlich, aber oft regnerischer als Juli im atlantischen Europa. Edinburgh im Festival (Fringe, Tattoo): maximaler Andrang in der Stadt. Pazifischer Nordwesten (Vancouver, Seattle): perfekte Bedingungen, trocken und warm (22-26°C). Regen steigen in Irland und Schottland.",
        9: "September ist eine ausgezeichnete Zeit an der Ozeanküste. Noch warm (15-19°C), sinkender Andrang, goldenes Licht. Weinlese in einigen Regionen. London Fashion Week Mitte September. Erste Herbstfarben Monatsende. Ideal für Kulturbesuche. Gemäßigte Regenfälle.",
        10: "Oktober installiert den Herbst. Flammende Farben in Parks (Hyde Park, Stanley Park Vancouver). Sinkende Temperaturen (10-14°C), häufigere Regenfälle. Halloween sehr ausgeprägt (angelsächsische Kulturen). Sinkender Andrang. Morgennebel auf der Themse. Suppen- und Porter-Saison im Pub.",
        11: "November ist der grauste und regenreichste ozeanische Monat des Jahres. Temperaturen 6-10°C, kurze Tage, häufige Regenfälle. Bonfire Night 5. November in Großbritannien (Feuerwerk). Black Friday Monatsende. Sehr wenig Tourismus. Intime Atmosphäre in Pubs und Theatern.",
        12: "Dezember bringt Weihnachtsgeist in ozeanische Städte: Märkte (Edinburgh, Hyde Park Winter Wonderland), spektakuläre Beleuchtungen (Oxford Street), Outdoor-Eisbahnen. Kaltes und regnerisches Wetter (4-9°C). Starker Andrang rund um die Feiertage. Hohe Preise Mitte-Ende des Monats.",
    },
    'alpine': {
        1: "Januar ist das Herz der alpinen Skisaison. Schneedecke generell optimal nach Dezember-Schneefällen. Kalte Temperaturen (-5 bis -15°C in Höhenlagen). Kurze Tage, aber Qualitätslicht. Punktueller Andrang in Schulferien (Zonen in Frankreich gestaffelt). Hohe Resortpreise, Schneeverhältnisse oft am besten.",
        2: "Februar ist der Spitzenmonat der Skisaison: maximale Schneedecke, oft stabiles Wetter, längere Tage. Europäische Schulferien gestaffelt (alle französischen Zonen + Deutschland + UK + Schweiz): Andrang- und Preisspitze. Beste Skibedingungen. Mittleres bis hohes Lawinenrisiko, Vorsicht außerhalb der Pisten.",
        3: "März kombiniert guten Schnee mit Frühlingssonne. Schnell länger werdende Tage, intensives Licht in Höhenlagen. Frühlingsferien Monatsende (Zonen). Frühlings-Skifahren mit tiefem Schnee morgens, weicher am Nachmittag. Preise leicht sinkend Ende März. Erhöhte Lawinenrisiken bei Tauwetter.",
        4: "April markiert den Übergang. Hochgelegene Resorts (über 2000 m) bleiben mit angenehmem Frühlings-Skifahren offen. Täler: deutliches Tauwetter, schnelle Schmelze. Ostern im Andrangspeak falls im April. Viele tiefer gelegene Resorts schließen Mitte April. Gletschersaison (Tignes, Zermatt, Hintertux) geht weiter.",
        5: "Mai ist Zwischenzeit: Schnee schmilzt in mittleren Höhen, Wanderungen oberhalb 1800 m noch unpraktisch. Spektakuläre Blüten in Tälern und Alpendörfern (Enziane, Anemonen, Rhododendren). Resorts geschlossen, Sommer noch nicht gestartet. Wasserfälle mit vollem Durchfluss. Wenige Leute, gute Zeit für authentische Alpendörfer.",
        6: "Juni öffnet die Wander- und Bergsaison. Alpenseen noch kalt, Schneeschmelze im Gange, spektakuläre Wasserfälle. Etagenblüten: Rhododendren in voller Pracht. Hütten öffnen schrittweise. Höhentrails noch verschneit oberhalb 2500 m. Erste Klettersteige zugänglich. Sonnenwende und Bergfeuerfeste.",
        7: "Juli ist Hochsommer in den Alpen. Alle Wanderwege zugänglich. Alpenseen bei 15-18°C (Bad für Tapfere). Bergmusik-Festivals. Hütten voll: Wochen vorher buchen. Tour de France oft Mitte Juli durch die Alpen. Starker Andrang, aber weite Berge.",
        8: "August verlängert alpine Hochsaison. Europäische Ferien = Wanderer, Bergsteiger, Familien. Top-Bedingungen in Höhe (10-25°C). Häufige Nachmittags-Gewitter: früher Aufbruch empfohlen. Edelweiß blüht. Genepi-Ernte. Monatsende: erste Höhenfröste kündigen Herbst an.",
        9: "September ist ein ausgezeichneter Bergmonat: sinkender Andrang, noch angenehme Temperaturen (12-22°C), stabile Bedingungen, goldenes Licht. Lärchen beginnen Monatsende gelb zu werden. Hütten noch bis Mitte Oktober offen. Ideal für lange Wanderungen und zugängliche Gipfel. Pilze.",
        10: "Oktober installiert alpinen Herbst. Spektakuläre Lärchenfarben (strahlendes Gold) und Buchen im Tal. Erste Schneefälle in Höhenlagen. Hütten schließen schrittweise. Wanderungen in mittleren Höhen noch zugänglich. Hirschbrunft im Wald. Tiefste Preise zwischen den Saisons.",
        11: "November ist absolute Nebensaison. Instabile Bedingungen: Schnee, Regen, Nebel. Resorts bereiten Eröffnung vor (Mitte bis Ende November je nach Schnee). Fußwanderungen begrenzt. Reduzierte Aktivität in Alpendörfern. Gute Zeit für Liebhaber absoluter Ruhe und lokaler Gastronomie.",
        12: "Dezember startet offiziell die Skisaison. Schrittweise Resort-Eröffnungen (um den 15.). Weihnachtsmärkte in Alpendörfern (Bayern, Tirol). Weihnachtsferien: Andrangsspitze, Maximalpreise, Schnee meist vorhanden. Silvester im Resort, festliche Atmosphäre. 6 Monate vorher buchen.",
    },
}


# ─────────────────────────────────────────────────────────────────────────────
# Lookup function
# ─────────────────────────────────────────────────────────────────────────────

_BY_LANG = {
    'fr': INSIGHTS_FR,
    'en': INSIGHTS_EN,
    'en-us': INSIGHTS_EN_US,
    'es': INSIGHTS_ES,
    'de': INSIGHTS_DE,
}


def get_monthly_insight(climate: str, month: int, lang: str = 'fr') -> str:
    """Retourne le paragraphe d'insight pour un climat/mois/langue donnés.

    Args:
        climate: 'alpine' | 'tropical' | 'mediterranean' | 'oceanic' | 'continental'
        month: 1-12
        lang: 'fr' | 'en' | 'en-us' | 'es' | 'de'

    Returns:
        Paragraphe (~400-500 chars) ou chaîne vide si introuvable.
    """
    lang_dict = _BY_LANG.get(lang, INSIGHTS_FR)
    climate_dict = lang_dict.get(climate, lang_dict.get('continental', {}))
    return climate_dict.get(month, '')
