#!/usr/bin/env python3
"""Add 100 new destinations to destinations.csv.
Replaces duplicates (kotor, addis-abeba, riyad, lombok, guilin, chengdu, turks-et-caicos)
with: budva, gondar, labuan-bajo, zhangjiajie, lijiang, wadi-rum, trogir, taormina, siena
"""
import csv, os

DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV_PATH = os.path.join(DIR, 'data', 'destinations.csv')

existing = set()
with open(CSV_PATH, encoding='utf-8-sig') as f:
    for r in csv.DictReader(f):
        existing.add(r['slug_fr'])
print(f"Existing: {len(existing)} destinations")

# (slug_fr, slug_en, nom_fr, nom_bare, pays, flag, prep, lat, lon, tropical,
#  hero_sub_fr, booking_id, nom_en, country_en, hero_sub_en, monthly, mountain)
NEW = [
    # ── FRANCE (3) ──
    ("la-rochelle","la-rochelle","La Rochelle","La Rochelle","France","fr","à",46.16,-1.15,False,
     "La Rochelle, cité maritime de l'Atlantique — vieux port emblématique, tours médiévales et île de Ré à portée de pont.",
     -1461476,"La Rochelle","France",
     "La Rochelle, Atlantic maritime city — iconic old harbour, medieval towers and Île de Ré just across the bridge.",True,False),
    ("val-d-isere","val-d-isere","Val d'Isère","Val d'Isère","France","fr","à",45.45,6.98,False,
     "Val d'Isère, station mythique des Alpes — domaine Espace Killy, ski de classe mondiale et vie nocturne en altitude.",
     -1457280,"Val d'Isère","France",
     "Val d'Isère, legendary Alpine resort — Espace Killy ski area, world-class skiing and high-altitude après-ski.",True,True),
    ("nantes","nantes","Nantes","Nantes","France","fr","à",47.22,-1.55,False,
     "Nantes, cité créative de l'estuaire — Machines de l'île, château des ducs de Bretagne et vignoble muscadet.",
     -1461448,"Nantes","France",
     "Nantes, creative city on the estuary — Machines de l'île, Château des Ducs de Bretagne and Muscadet vineyards.",True,False),

    # ── EUROPE SUD & MÉDITERRANÉE (14) ──
    ("marbella","marbella","Marbella","Marbella","Espagne","es","à",36.51,-4.88,False,
     "Marbella, perle de la Costa del Sol — plages dorées, vieille ville andalouse et vie nocturne glamour.",
     -398331,"Marbella","Spain",
     "Marbella, jewel of the Costa del Sol — golden beaches, Andalusian old town and glamorous nightlife.",True,False),
    ("sorrente","sorrento","Sorrente","Sorrente","Italie","it","à",40.63,14.37,False,
     "Sorrente, balcon sur le golfe de Naples — falaises, citronniers et porte d'entrée vers Capri et Amalfi.",
     -126690,"Sorrento","Italy",
     "Sorrento, balcony over the Bay of Naples — clifftop views, lemon groves and gateway to Capri and the Amalfi Coast.",True,False),
    ("lac-bled","lake-bled","le lac de Bled","Lac de Bled","Slovénie","si","au",46.37,14.10,False,
     "Le lac de Bled, joyau alpin de Slovénie — île baroque, château perché et eaux émeraude au pied des Juliens.",
     -2587800,"Lake Bled","Slovenia",
     "Lake Bled, Slovenia's Alpine gem — island church, clifftop castle and emerald waters beneath the Julian Alps.",True,False),
    ("cannes","cannes","Cannes","Cannes","France","fr","à",43.55,7.02,False,
     "Cannes, capitale du cinéma et de la Croisette — plages privées, palais des festivals et îles de Lérins à 15 minutes.",
     -1461388,"Cannes","France",
     "Cannes, capital of cinema and the Croisette — private beaches, Festival Palace and Lérins Islands 15 minutes away.",True,False),
    ("larnaca","larnaca","Larnaca","Larnaca","Chypre","cy","à",34.92,33.63,False,
     "Larnaca, porte d'entrée de Chypre — promenade Finikoudes, lac salé aux flamants roses et plongée sur épaves.",
     -697939,"Larnaca","Cyprus",
     "Larnaca, gateway to Cyprus — Finikoudes promenade, flamingo salt lake and world-famous wreck diving.",True,False),
    ("piran","piran","Piran","Piran","Slovénie","si","à",45.53,13.57,False,
     "Piran, bijou vénitien sur l'Adriatique slovène — ruelles médiévales, place Tartini et couchers de soleil.",
     -2604157,"Piran","Slovenia",
     "Piran, Venetian gem on Slovenia's Adriatic coast — medieval lanes, Tartini Square and sunsets over the sea.",True,False),
    ("ravello","ravello","Ravello","Ravello","Italie","it","à",40.65,14.61,False,
     "Ravello, terrasse sur la côte amalfitaine — jardins suspendus, concerts classiques et panoramas vertigineux.",
     -128066,"Ravello","Italy",
     "Ravello, terrace above the Amalfi Coast — hanging gardens, classical concerts and breathtaking panoramas.",True,False),
    ("peloponnese","peloponnese","le Péloponnèse","Péloponnèse","Grèce","gr","dans",37.51,22.37,False,
     "Le Péloponnèse, berceau de la Grèce antique — Olympie, Mycènes, théâtre d'Épidaure et plages sauvages.",
     -3249068,"Peloponnese","Greece",
     "The Peloponnese, cradle of ancient Greece — Olympia, Mycenae, Epidaurus theatre and wild beaches.",True,False),
    ("ohrid","ohrid","Ohrid","Ohrid","Macédoine du Nord","mk","à",41.12,20.80,False,
     "Ohrid, perle des Balkans — lac millénaire classé UNESCO, églises byzantines et plages loin du tourisme de masse.",
     -5268912,"Ohrid","North Macedonia",
     "Ohrid, pearl of the Balkans — UNESCO-listed ancient lake, Byzantine churches and gentle beaches.",True,False),
    ("alacati","alacati","Alaçatı","Alaçatı","Turquie","tr","à",38.28,26.37,False,
     "Alaçatı, village de charme égéen — maisons de pierre, windsurf de classe mondiale et vignobles d'Urla.",
     -1770100,"Alaçatı","Turkey",
     "Alaçatı, charming Aegean village — stone houses, world-class windsurfing and Urla vineyards.",True,False),
    ("funchal","funchal","Funchal","Funchal","Portugal","pt","à",32.65,-16.91,False,
     "Funchal, capitale de Madère — jardin tropical, marchés colorés et levadas dans un éternel printemps.",
     -563753,"Funchal","Portugal",
     "Funchal, capital of Madeira — tropical gardens, colourful markets and levada walks in eternal spring.",True,False),
    ("budva","budva","Budva","Budva","Monténégro","me","à",42.29,18.84,False,
     "Budva, riviera du Monténégro — vieille ville fortifiée, plages de galets et vie nocturne adriatique animée.",
     -92516,"Budva","Montenegro",
     "Budva, Montenegro's riviera — fortified old town, pebble beaches and lively Adriatic nightlife.",True,False),
    ("trogir","trogir","Trogir","Trogir","Croatie","hr","à",43.52,16.25,False,
     "Trogir, musée à ciel ouvert de Dalmatie — ville-île médiévale classée UNESCO, cathédrale romane et port vénitien.",
     -2113490,"Trogir","Croatia",
     "Trogir, open-air museum of Dalmatia — UNESCO medieval island-town, Romanesque cathedral and Venetian harbour.",True,False),
    ("taormina","taormina","Taormina","Taormina","Italie","it","à",37.85,15.29,False,
     "Taormina, terrasse sur l'Etna et la mer Ionienne — théâtre grec antique, panoramas spectaculaires et dolce vita sicilienne.",
     -127248,"Taormina","Italy",
     "Taormina, terrace above Etna and the Ionian Sea — ancient Greek theatre, spectacular views and Sicilian dolce vita.",True,False),
    ("siena","siena","Sienne","Sienne","Italie","it","à",43.32,11.33,False,
     "Sienne, cœur médiéval de la Toscane — Piazza del Campo, Palio légendaire et collines du Chianti alentour.",
     -125504,"Siena","Italy",
     "Siena, medieval heart of Tuscany — Piazza del Campo, legendary Palio and surrounding Chianti hills.",True,False),

    # ── EUROPE NORD & CENTRALE (5) ──
    ("göteborg","gothenburg","Göteborg","Göteborg","Suède","se","à",57.71,11.97,False,
     "Göteborg, deuxième ville de Suède — archipel accessible, scène foodie scandinave et ambiance décontractée.",
     -2129869,"Gothenburg","Sweden",
     "Gothenburg, Sweden's second city — accessible archipelago, Scandinavian food scene and laid-back vibes.",True,False),
    ("innsbruck","innsbruck","Innsbruck","Innsbruck","Autriche","at","à",47.26,11.39,False,
     "Innsbruck, capitale du Tyrol — vieille ville baroque au pied des Alpes, ski olympique et Bergisel.",
     -1739429,"Innsbruck","Austria",
     "Innsbruck, capital of Tyrol — baroque old town at the foot of the Alps, Olympic skiing and Bergisel.",True,True),
    ("ghent","ghent","Gand","Gand","Belgique","be","à",51.05,3.72,False,
     "Gand, cité médiévale flamande — canaux, Agneau mystique de Van Eyck et scène culturelle vibrante.",
     -1438561,"Ghent","Belgium",
     "Ghent, medieval Flemish city — canals, Van Eyck's Ghent Altarpiece and vibrant cultural scene.",True,False),
    ("hallstatt","hallstatt","Hallstatt","Hallstatt","Autriche","at","à",47.56,13.65,False,
     "Hallstatt, village lacustre du Salzkammergut — maisons pastel, mines de sel antiques et panorama alpin.",
     -5268000,"Hallstatt","Austria",
     "Hallstatt, lakeside village in Salzkammergut — pastel houses, ancient salt mines and Alpine panorama.",True,False),
    ("lviv","lviv","Lviv","Lviv","Ukraine","ua","à",49.84,24.03,False,
     "Lviv, joyau baroque de l'Ukraine — cafés légendaires, architecture Habsbourg et culture vibrante.",
     -2208003,"Lviv","Ukraine",
     "Lviv, baroque gem of western Ukraine — legendary coffee culture, Habsburg architecture and vibrant arts.",True,False),

    # ── AFRIQUE DU NORD (3) ──
    ("tanger","tangier","Tanger","Tanger","Maroc","ma","à",35.77,-5.80,False,
     "Tanger, porte de l'Afrique — médina légendaire, cap Spartel et vue sur le détroit de Gibraltar.",
     -21035,"Tangier","Morocco",
     "Tangier, gateway to Africa — legendary medina, Cape Spartel and views across the Strait of Gibraltar.",True,False),
    ("merzouga","merzouga","Merzouga","Merzouga","Maroc","ma","à",31.08,-4.01,False,
     "Merzouga, porte du Sahara — dunes de l'Erg Chebbi, nuits étoilées et camps berbères authentiques.",
     -6035019,"Merzouga","Morocco",
     "Merzouga, gateway to the Sahara — Erg Chebbi dunes, starlit desert nights and authentic Berber camps.",True,False),
    ("assouan","aswan","Assouan","Assouan","Égypte","eg","à",24.09,32.90,False,
     "Assouan, porte de la Nubie — felouques sur le Nil, temple de Philae et ambiance paisible du sud égyptien.",
     -73356,"Aswan","Egypt",
     "Aswan, gateway to Nubia — feluccas on the Nile, Philae Temple and peaceful southern Egypt atmosphere.",True,False),

    # ── AFRIQUE OUEST & CENTRALE (5) ──
    ("freetown","freetown","Freetown","Freetown","Sierra Leone","sl","à",8.48,-13.23,True,
     "Freetown, entre plages et collines — Lumley Beach, péninsule tropicale et histoire vibrante.",
     -5270000,"Freetown","Sierra Leone",
     "Freetown, between beaches and hills — Lumley Beach, tropical peninsula and vibrant history.",True,False),
    ("ouagadougou","ouagadougou","Ouagadougou","Ouagadougou","Burkina Faso","bf","à",12.37,-1.52,True,
     "Ouagadougou, capitale culturelle de l'Afrique de l'Ouest — FESPACO, artisanat et hospitalité sahélienne.",
     -5270001,"Ouagadougou","Burkina Faso",
     "Ouagadougou, cultural capital of West Africa — FESPACO film festival, crafts and Sahelian hospitality.",True,False),
    ("cotonou","cotonou","Cotonou","Cotonou","Bénin","bj","à",6.37,2.39,True,
     "Cotonou, porte du Bénin — Ganvié la Venise africaine, marché Dantokpa et plages de l'Atlantique.",
     -5270002,"Cotonou","Benin",
     "Cotonou, gateway to Benin — Ganvié the African Venice, Dantokpa market and Atlantic beaches.",True,False),
    ("lome","lome","Lomé","Lomé","Togo","tg","à",6.13,1.22,True,
     "Lomé, capitale du Togo en bord de mer — Grand Marché, plages de cocotiers et golfe de Guinée.",
     -5270003,"Lomé","Togo",
     "Lomé, Togo's seaside capital — Grand Marché, coconut palm beaches and Gulf of Guinea atmosphere.",True,False),
    ("douala","douala","Douala","Douala","Cameroun","cm","à",4.05,9.77,True,
     "Douala, capitale économique du Cameroun — ville portuaire, Mont Cameroun et culture urbaine foisonnante.",
     -5270004,"Douala","Cameroon",
     "Douala, economic capital of Cameroon — port city, Mount Cameroon nearby and thriving urban culture.",True,False),

    # ── AFRIQUE EST (5) ──
    ("arusha","arusha","Arusha","Arusha","Tanzanie","tz","à",-3.37,36.68,False,
     "Arusha, porte des safaris — Serengeti, Ngorongoro et Kilimandjaro partent tous d'ici.",
     -2587801,"Arusha","Tanzania",
     "Arusha, safari gateway — Serengeti, Ngorongoro and Kilimanjaro all start from here.",True,False),
    ("gondar","gondar","Gondar","Gondar","Éthiopie","et","à",12.60,37.47,False,
     "Gondar, Camelot d'Afrique — château impérial de Fasil Ghebbi, églises peintes et montagnes du Simien.",
     -5270005,"Gondar","Ethiopia",
     "Gondar, Africa's Camelot — Fasil Ghebbi imperial castle, painted churches and Simien Mountains.",True,False),
    ("lalibela","lalibela","Lalibela","Lalibela","Éthiopie","et","à",12.03,39.04,False,
     "Lalibela, Jérusalem africaine — 11 églises monolithiques taillées dans le roc, classées UNESCO.",
     -5270006,"Lalibela","Ethiopia",
     "Lalibela, African Jerusalem — 11 monolithic rock-hewn churches, UNESCO World Heritage Site.",True,False),
    ("jinja","jinja","Jinja","Jinja","Ouganda","ug","à",0.42,33.21,True,
     "Jinja, source du Nil — rafting, bungee et gorilles de Bwindi accessibles.",
     -5270007,"Jinja","Uganda",
     "Jinja, source of the Nile — rafting, bungee and Bwindi gorillas within reach.",True,False),
    ("lamu","lamu","Lamu","Lamu","Kenya","ke","à",-2.27,40.90,True,
     "Lamu, île swahilie intemporelle — ruelles de corail, boutres et plages désertes sans voiture.",
     -5270008,"Lamu","Kenya",
     "Lamu, timeless Swahili island — coral lanes, dhow boats and car-free deserted beaches.",True,False),

    # ── AFRIQUE AUSTRALE (4) ──
    ("livingstone","livingstone","Livingstone","Livingstone","Zambie","zm","à",-17.84,25.86,False,
     "Livingstone, côté zambien des chutes Victoria — brume arc-en-ciel, safaris au Zambèze et bungee.",
     -5270009,"Livingstone","Zambia",
     "Livingstone, Zambian side of Victoria Falls — rainbow mist, Zambezi safaris and gorge bungee.",True,False),
    ("maun","maun","Maun","Maun","Botswana","bw","à",-19.99,23.42,False,
     "Maun, porte du delta de l'Okavango — safaris en mokoro, faune exceptionnelle et wilderness pure.",
     -5270010,"Maun","Botswana",
     "Maun, gateway to the Okavango Delta — mokoro safaris, exceptional wildlife and pure wilderness.",True,False),
    ("tofo","tofo","Tofo","Tofo","Mozambique","mz","à",-23.75,35.54,True,
     "Tofo, paradis balnéaire du Mozambique — raies manta, requins-baleines et plages infinies.",
     -5270011,"Tofo","Mozambique",
     "Tofo, Mozambique's beach paradise — manta rays, whale sharks and endless Indian Ocean beaches.",True,False),
    ("etosha","etosha","Etosha","Etosha","Namibie","na","à",-18.80,16.33,False,
     "Etosha, grand parc de Namibie — pan de sel blanc et points d'eau où convergent lions et éléphants.",
     -5270012,"Etosha","Namibia",
     "Etosha, Namibia's great park — white salt pan and waterholes where lions and elephants converge.",True,False),

    # ── MOYEN-ORIENT (5) ──
    ("ras-al-khaimah","ras-al-khaimah","Ras al-Khaimah","Ras al-Khaimah","Émirats Arabes Unis","ae","à",25.79,55.94,False,
     "Ras al-Khaimah, l'émirat nature — Jebel Jais, désert et plages loin de l'agitation de Dubaï.",
     -5270013,"Ras al-Khaimah","United Arab Emirates",
     "Ras al-Khaimah, the nature emirate — Jebel Jais, desert and beaches away from Dubai's bustle.",True,False),
    ("aqaba","aqaba","Aqaba","Aqaba","Jordanie","jo","à",29.53,35.01,False,
     "Aqaba, accès jordanien à la mer Rouge — récifs coralliens, plongée et 330 jours de soleil par an.",
     -5270014,"Aqaba","Jordan",
     "Aqaba, Jordan's Red Sea access — coral reefs, diving and 330 days of sunshine per year.",True,False),
    ("salalah","salalah","Salalah","Salalah","Oman","om","à",17.02,54.09,False,
     "Salalah, perle verte d'Oman — mousson khareef transformant le désert en oasis de juin à septembre.",
     -5270015,"Salalah","Oman",
     "Salalah, Oman's green pearl — khareef monsoon turning desert into oasis from June to September.",True,False),
    ("al-ula","al-ula","AlUla","AlUla","Arabie Saoudite","sa","à",26.62,37.92,False,
     "AlUla, trésor archéologique d'Arabie — Hegra UNESCO, formations rocheuses et oasis millénaire.",
     -5270016,"AlUla","Saudi Arabia",
     "AlUla, Arabia's archaeological treasure — UNESCO Hegra, rock formations and ancient desert oasis.",True,False),
    ("wadi-rum","wadi-rum","Wadi Rum","Wadi Rum","Jordanie","jo","à",29.57,35.42,False,
     "Wadi Rum, désert lunaire de Jordanie — falaises de grès rouge, camps bédouins et ciels étoilés de Lawrence d'Arabie.",
     -5270017,"Wadi Rum","Jordan",
     "Wadi Rum, Jordan's lunar desert — red sandstone cliffs, Bedouin camps and Lawrence of Arabia's starry skies.",True,False),

    # ── ASIE SUD-EST (8) ──
    ("raja-ampat","raja-ampat","Raja Ampat","Raja Ampat","Indonésie","id","à",-0.23,130.52,True,
     "Raja Ampat, épicentre mondial de la biodiversité marine — 1 500 espèces de poissons et lagons turquoise.",
     -5270018,"Raja Ampat","Indonesia",
     "Raja Ampat, global epicentre of marine biodiversity — 1,500 fish species and turquoise lagoons.",True,False),
    ("yogyakarta","yogyakarta","Yogyakarta","Yogyakarta","Indonésie","id","à",-7.80,110.36,True,
     "Yogyakarta, cœur culturel de Java — Borobudur, Prambanan, batik et volcans.",
     -2594920,"Yogyakarta","Indonesia",
     "Yogyakarta, cultural heart of Java — Borobudur, Prambanan, batik and volcanoes.",True,False),
    ("labuan-bajo","labuan-bajo","Labuan Bajo","Labuan Bajo","Indonésie","id","à",-8.49,119.88,True,
     "Labuan Bajo, porte du parc national de Komodo — dragons, plongée et plage rose de Flores.",
     -5270019,"Labuan Bajo","Indonesia",
     "Labuan Bajo, gateway to Komodo National Park — dragons, diving and Flores' pink beach.",True,False),
    ("chiang-rai","chiang-rai","Chiang Rai","Chiang Rai","Thaïlande","th","à",19.91,99.83,True,
     "Chiang Rai, nord profond de la Thaïlande — Temple Blanc, Triangle d'Or et montagnes brumeuses.",
     -75891,"Chiang Rai","Thailand",
     "Chiang Rai, Thailand's deep north — White Temple, Golden Triangle and misty mountains.",True,False),
    ("ninh-binh","ninh-binh","Ninh Binh","Ninh Binh","Viêt Nam","vn","à",20.25,105.97,True,
     "Ninh Binh, baie d'Halong terrestre — pitons karstiques, rizières et pagodes entre rivières et grottes.",
     -5270020,"Ninh Binh","Vietnam",
     "Ninh Binh, Ha Long Bay on land — karst peaks, rice paddies and pagodas between rivers and caves.",True,False),
    ("coron","coron","Coron","Coron","Philippines","ph","à",12.00,120.20,True,
     "Coron, paradis de plongée — épaves japonaises, lacs d'eau douce et lagons de Palawan.",
     -5270021,"Coron","Philippines",
     "Coron, diving paradise — Japanese shipwrecks, freshwater lakes and hidden Palawan lagoons.",True,False),
    ("battambang","battambang","Battambang","Battambang","Cambodge","kh","à",13.10,103.20,True,
     "Battambang, Cambodge authentique — architecture coloniale, bamboo train et campagne khmère.",
     -5270022,"Battambang","Cambodia",
     "Battambang, authentic Cambodia — colonial architecture, bamboo train and Khmer countryside.",True,False),
    ("luzon","luzon","Luzon Nord","Luzon Nord","Philippines","ph","en",17.10,121.55,True,
     "Luzon Nord — rizières en terrasses de Banaue, grottes de Sagada et Vigan colonial.",
     -5270023,"Northern Luzon","Philippines",
     "Northern Luzon — Banaue rice terraces, Sagada caves and colonial Vigan.",True,False),

    # ── ASIE EST (5) ──
    ("nara","nara","Nara","Nara","Japon","jp","à",34.69,135.80,False,
     "Nara, première capitale du Japon — cerfs sacrés, grand Bouddha de Todai-ji et temples millénaires.",
     -5270024,"Nara","Japan",
     "Nara, Japan's first capital — sacred free-roaming deer, Todai-ji Great Buddha and ancient temples.",True,False),
    ("kaohsiung","kaohsiung","Kaohsiung","Kaohsiung","Taïwan","tw","à",22.63,120.30,True,
     "Kaohsiung, deuxième ville de Taïwan — art urbain, temples et marchés de nuit.",
     -5270025,"Kaohsiung","Taiwan",
     "Kaohsiung, Taiwan's second city — urban art, temples and night markets.",True,False),
    ("zhangjiajie","zhangjiajie","Zhangjiajie","Zhangjiajie","Chine","cn","à",29.12,110.48,False,
     "Zhangjiajie, montagnes Avatar — piliers de grès vertigineux, pont de verre et forêts primaires du Hunan.",
     -5270026,"Zhangjiajie","China",
     "Zhangjiajie, Avatar mountains — vertiginous sandstone pillars, glass bridge and Hunan's pristine forests.",True,False),
    ("nagasaki","nagasaki","Nagasaki","Nagasaki","Japon","jp","à",32.75,129.88,False,
     "Nagasaki, port cosmopolite du Kyūshū — influences hollandaises et chinoises, Glover Garden et Gunkanjima.",
     -5270027,"Nagasaki","Japan",
     "Nagasaki, cosmopolitan port of Kyūshū — Dutch and Chinese heritage, Glover Garden and Gunkanjima.",True,False),
    ("lijiang","lijiang","Lijiang","Lijiang","Chine","cn","à",26.87,100.23,False,
     "Lijiang, cité naxi du Yunnan — vieille ville UNESCO, montagne du Dragon de Jade et gorge du Saut du Tigre.",
     -5270028,"Lijiang","China",
     "Lijiang, Naxi city of Yunnan — UNESCO old town, Jade Dragon Snow Mountain and Tiger Leaping Gorge.",True,False),

    # ── ASIE SUD (5) ──
    ("hampi","hampi","Hampi","Hampi","Inde","in","à",15.33,76.46,True,
     "Hampi, ruines de Vijayanagara — temples sculptés, blocs granitiques surréalistes et rizières lunaires.",
     -5270029,"Hampi","India",
     "Hampi, ruins of Vijayanagara — carved temples, surreal granite boulders and lunar rice paddies.",True,False),
    ("kochi","kochi","Kochi","Kochi","Inde","in","à",9.93,76.26,True,
     "Kochi, porte du Kerala — filets chinois de Fort Cochin, backwaters et épices.",
     -5270030,"Kochi","India",
     "Kochi, gateway to Kerala — Chinese fishing nets of Fort Cochin, backwaters and spices.",True,False),
    ("bhutan","bhutan","le Bhoutan","Bhoutan","Bhoutan","bt","au",27.47,89.64,False,
     "Le Bhoutan, royaume du bonheur — Nid du Tigre, vallées himalayennes et culture bouddhiste préservée.",
     -5270031,"Bhutan","Bhutan",
     "Bhutan, kingdom of happiness — Tiger's Nest, Himalayan valleys and preserved Buddhist culture.",True,False),
    ("ella","ella","Ella","Ella","Sri Lanka","lk","à",6.87,81.05,True,
     "Ella, perle des collines du Sri Lanka — train panoramique, plantations de thé et Little Adam's Peak.",
     -5270032,"Ella","Sri Lanka",
     "Ella, gem of Sri Lanka's hill country — scenic train, tea plantations and Little Adam's Peak.",True,False),
    ("pokhara","pokhara","Pokhara","Pokhara","Népal","np","à",28.21,83.99,False,
     "Pokhara, porte de l'Annapurna — lac Phewa, vue himalayenne et départ des treks mythiques.",
     -5270033,"Pokhara","Nepal",
     "Pokhara, gateway to Annapurna — Phewa Lake, Himalayan views and legendary trek starting point.",True,False),

    # ── ASIE CENTRALE (2) ──
    ("boukhara","bukhara","Boukhara","Boukhara","Ouzbékistan","uz","à",39.77,64.42,False,
     "Boukhara, ville sainte de la route de la soie — minarets millénaires, bazars et architecture islamique.",
     -5270034,"Bukhara","Uzbekistan",
     "Bukhara, holy city of the Silk Road — ancient minarets, bazaars and dazzling Islamic architecture.",True,False),
    ("khiva","khiva","Khiva","Khiva","Ouzbékistan","uz","à",41.38,60.36,False,
     "Khiva, cité fortifiée figée dans le temps — Ichan-Kala UNESCO, minarets turquoise et caravansérails.",
     -5270035,"Khiva","Uzbekistan",
     "Khiva, fortified city frozen in time — UNESCO Ichan-Kala, turquoise minarets and caravanserais.",True,False),

    # ── ÉTATS-UNIS (8) ──
    ("san-antonio","san-antonio","San Antonio","San Antonio","États-Unis","us","à",29.42,-98.49,False,
     "San Antonio, cœur texan — River Walk, Alamo historique et culture tex-mex authentique.",
     20123906,"San Antonio","United States",
     "San Antonio, heart of Texas — River Walk, historic Alamo and authentic Tex-Mex culture.",True,False),
    ("sedona","sedona","Sedona","Sedona","États-Unis","us","à",34.87,-111.76,False,
     "Sedona, cathédrale de roche rouge d'Arizona — vortex spirituels, randonnées et couchers de soleil irréels.",
     -5270036,"Sedona","United States",
     "Sedona, Arizona's red rock cathedral — spiritual vortexes, desert hikes and unreal sunsets.",True,False),
    ("anchorage","anchorage","Anchorage","Anchorage","États-Unis","us","à",61.22,-149.90,False,
     "Anchorage, porte de l'Alaska — glaciers, grizzlys, aurores boréales et wilderness ultime.",
     -5270037,"Anchorage","United States",
     "Anchorage, gateway to Alaska — glaciers, grizzly bears, northern lights and ultimate wilderness.",True,False),
    ("savannah-ga","savannah-ga","Savannah","Savannah","États-Unis","us","à",32.08,-81.09,False,
     "Savannah, perle du Sud profond — chênes drapés de mousse, squares historiques et charme sudiste.",
     20070067,"Savannah","United States",
     "Savannah, pearl of the Deep South — Spanish moss-draped oaks, historic squares and Southern charm.",True,False),
    ("napa-valley","napa-valley","Napa Valley","Napa Valley","États-Unis","us","à",38.50,-122.27,False,
     "Napa Valley, terre de vins californienne — 400 domaines, restaurants étoilés et montgolfières.",
     -5270038,"Napa Valley","United States",
     "Napa Valley, California wine country — 400 wineries, Michelin restaurants and sunrise hot air balloons.",True,False),
    ("jackson-hole","jackson-hole","Jackson Hole","Jackson Hole","États-Unis","us","à",43.48,-110.76,False,
     "Jackson Hole, vallée sauvage du Wyoming — ski légendaire, Grand Teton et Yellowstone à 1h.",
     -5270039,"Jackson Hole","United States",
     "Jackson Hole, Wyoming's wild valley — legendary skiing, Grand Teton and Yellowstone 1 hour away.",True,True),
    ("memphis","memphis","Memphis","Memphis","États-Unis","us","à",35.15,-90.05,False,
     "Memphis, berceau du blues et du rock'n'roll — Beale Street, Graceland et barbecue légendaire.",
     20057756,"Memphis","United States",
     "Memphis, birthplace of blues and rock'n'roll — Beale Street, Graceland and legendary barbecue.",True,False),
    ("maui","maui","Maui","Maui","États-Unis","us","à",20.80,-156.32,True,
     "Maui, joyau hawaïen — route de Hana, volcan Haleakalā et plages de sable noir.",
     -5270040,"Maui","United States",
     "Maui, Hawaiian jewel — Road to Hana, Haleakalā volcano and black sand beaches.",True,False),

    # ── CARAÏBES (4) ──
    ("dominique","dominica","la Dominique","Dominique","Dominique","dm","en",15.41,-61.37,True,
     "La Dominique, île nature des Caraïbes — forêt tropicale, sources chaudes et plongée volcanique.",
     -5270041,"Dominica","Dominica",
     "Dominica, nature island of the Caribbean — tropical forest, hot springs and volcanic diving.",True,False),
    ("bonaire","bonaire","Bonaire","Bonaire","Pays-Bas caribéens","bq","à",12.14,-68.26,True,
     "Bonaire, paradis des plongeurs — récifs accessibles depuis la plage, flamants roses et alizés.",
     -5270042,"Bonaire","Caribbean Netherlands",
     "Bonaire, divers' paradise — shore-accessible reefs, flamingos and trade winds.",True,False),
    ("grenadines","grenadines","les Grenadines","Grenadines","Saint-Vincent-et-les-Grenadines","vc","aux",13.01,-61.23,True,
     "Les Grenadines, chapelet d'îles préservées — Tobago Cays, voiliers et plages de sable blanc.",
     -5270043,"Grenadines","Saint Vincent and the Grenadines",
     "The Grenadines, string of pristine islands — Tobago Cays, sailing and white sand beaches.",True,False),
    ("roatan","roatan","Roatán","Roatán","Honduras","hn","à",16.32,-86.53,True,
     "Roatán, île caribéenne du Honduras — deuxième barrière de corail au monde et plongée exceptionnelle.",
     -5270044,"Roatán","Honduras",
     "Roatán, Honduras' Caribbean island — world's second-largest barrier reef and exceptional diving.",True,False),

    # ── MEXIQUE & CENTRALE (3) ──
    ("guanajuato","guanajuato","Guanajuato","Guanajuato","Mexique","mx","à",21.02,-101.26,False,
     "Guanajuato, ville colorée coloniale — ruelles souterraines, Callejón del Beso et momies célèbres.",
     -5270045,"Guanajuato","Mexico",
     "Guanajuato, colourful colonial city — underground tunnels, Callejón del Beso and famous mummies.",True,False),
    ("san-cristobal","san-cristobal","San Cristóbal de las Casas","San Cristóbal de las Casas","Mexique","mx","à",16.74,-92.64,False,
     "San Cristóbal de las Casas, cœur du Chiapas — villages indigènes, forêts de nuages et marchés à 2 200 m.",
     -5270046,"San Cristóbal de las Casas","Mexico",
     "San Cristóbal de las Casas, heart of Chiapas — indigenous villages, cloud forests and markets at 2,200m.",True,False),
    ("granada-nicaragua","granada-nicaragua","Granada","Granada (Nicaragua)","Nicaragua","ni","à",11.93,-85.96,True,
     "Granada, plus ancienne ville coloniale du continent — architecture colorée, lac Nicaragua et volcan Mombacho.",
     -5270047,"Granada","Nicaragua",
     "Granada, oldest colonial city on the continent — colourful architecture, Lake Nicaragua and Mombacho Volcano.",True,False),

    # ── AMÉRIQUE DU SUD (6) ──
    ("cartagena-col","cartagena-colombia","Carthagène des Indes","Carthagène des Indes","Colombie","co","à",10.39,-75.51,True,
     "Carthagène des Indes, perle des Caraïbes colombiennes — ville fortifiée, îles du Rosaire et salsa.",
     -5270048,"Cartagena","Colombia",
     "Cartagena, pearl of the Colombian Caribbean — walled city, Rosario Islands and salsa.",True,False),
    ("la-paz-bolivie","la-paz-bolivia","La Paz","La Paz (Bolivie)","Bolivie","bo","à",-16.50,-68.15,False,
     "La Paz, plus haute capitale du monde — marchés vertigineux, Vallée de la Lune et Salar d'Uyuni.",
     -5270049,"La Paz","Bolivia",
     "La Paz, highest capital in the world — vertiginous markets, Moon Valley and Uyuni Salt Flats.",True,False),
    ("mendoza","mendoza","Mendoza","Mendoza","Argentine","ar","à",-32.89,-68.83,False,
     "Mendoza, capitale du Malbec — vignobles au pied des Andes, Aconcagua et rafting.",
     -5270050,"Mendoza","Argentina",
     "Mendoza, Malbec capital — vineyards at the foot of the Andes, Aconcagua and gorge rafting.",True,False),
    ("manaus","manaus","Manaus","Manaus","Brésil","br","à",-3.12,-60.02,True,
     "Manaus, porte de l'Amazonie — rencontre des eaux, jungle et opéra Belle Époque.",
     -5270051,"Manaus","Brazil",
     "Manaus, gateway to the Amazon — meeting of the waters, jungle and Belle Époque opera house.",True,False),
    ("sucre","sucre","Sucre","Sucre","Bolivie","bo","à",-19.04,-65.26,False,
     "Sucre, ville blanche de Bolivie — capitale constitutionnelle à 2 800 m et douceur de vivre andine.",
     -5270052,"Sucre","Bolivia",
     "Sucre, white city of Bolivia — constitutional capital at 2,800m and Andean joie de vivre.",True,False),
    ("cusco-ville","cusco-city","Cusco","Cusco","Pérou","pe","à",-13.52,-71.97,False,
     "Cusco, ancienne capitale inca à 3 400 m — Plaza de Armas, Vallée Sacrée et Machu Picchu.",
     -5270053,"Cusco","Peru",
     "Cusco, former Inca capital at 3,400m — Plaza de Armas, Sacred Valley and Machu Picchu.",True,False),

    # ── OCÉANIE (8) ──
    ("wellington","wellington","Wellington","Wellington","Nouvelle-Zélande","nz","à",-41.29,174.78,False,
     "Wellington, capitale la plus cool du monde — café culture, Te Papa et vent de Cook Strait.",
     -5270054,"Wellington","New Zealand",
     "Wellington, coolest little capital — café culture, Te Papa museum and Cook Strait wind.",True,False),
    ("christchurch","christchurch","Christchurch","Christchurch","Nouvelle-Zélande","nz","à",-43.53,172.64,False,
     "Christchurch, porte des Alpes du Sud — ville renée, Canterbury Plains et Arthur's Pass.",
     -5270055,"Christchurch","New Zealand",
     "Christchurch, gateway to the Southern Alps — reborn city, Canterbury Plains and Arthur's Pass.",True,False),
    ("brisbane","brisbane","Brisbane","Brisbane","Australie","au","à",-27.47,153.03,False,
     "Brisbane, métropole subtropicale — South Bank, koalas et portes de la Gold Coast.",
     -5270056,"Brisbane","Australia",
     "Brisbane, subtropical metropolis — South Bank, koalas and gateway to the Gold Coast.",True,False),
    ("whitsundays","whitsundays","les Whitsundays","Whitsundays","Australie","au","aux",-20.28,148.95,True,
     "Les Whitsundays, joyau de la Grande Barrière — Whitehaven Beach et voile entre 74 îles.",
     -5270057,"Whitsundays","Australia",
     "The Whitsundays, Great Barrier Reef gem — Whitehaven Beach and sailing between 74 islands.",True,False),
    ("uluru","uluru","Uluru","Uluru","Australie","au","à",-25.34,131.04,False,
     "Uluru, cœur sacré de l'Australie — monolithe rouge, Kata Tjuta et ciel étoilé de l'Outback.",
     -5270058,"Uluru","Australia",
     "Uluru, sacred heart of Australia — red monolith, Kata Tjuta and Outback starry skies.",True,False),
    ("moorea","moorea","Moorea","Moorea","Polynésie française","pf","à",-17.53,-149.83,True,
     "Moorea, île sœur de Tahiti — baies spectaculaires, montagnes volcaniques et lagon bleu.",
     -5270059,"Moorea","French Polynesia",
     "Moorea, Tahiti's sister island — spectacular bays, volcanic mountains and blue lagoon.",True,False),
    ("iles-cook","cook-islands","les îles Cook","Îles Cook","Îles Cook","ck","aux",-21.24,-159.78,True,
     "Les îles Cook, Polynésie authentique — lagon d'Aitutaki, hospitalité maorie et vie insulaire.",
     -5270060,"Cook Islands","Cook Islands",
     "The Cook Islands, authentic Polynesia — Aitutaki lagoon, Maori hospitality and island life.",True,False),
    ("papouasie","papua-new-guinea","la Papouasie-Nouvelle-Guinée","Papouasie-Nouvelle-Guinée","Papouasie-Nouvelle-Guinée","pg","en",-6.31,147.18,True,
     "La Papouasie-Nouvelle-Guinée, dernière frontière — 800 langues, tribus des Hautes Terres et plongée vierge.",
     -5270061,"Papua New Guinea","Papua New Guinea",
     "Papua New Guinea, last frontier — 800 languages, Highland tribes and pristine diving.",True,False),

    # ── MACARONÉSIE (2) ──
    ("sao-miguel","sao-miguel","São Miguel","São Miguel","Portugal","pt","à",37.75,-25.68,False,
     "São Miguel, île verte des Açores — lacs de cratère, sources thermales et pâturages émeraude.",
     -5270062,"São Miguel","Portugal",
     "São Miguel, green island of the Azores — crater lakes, hot springs and emerald pastures.",True,False),
    ("sal","sal","Sal","Sal","Cap-Vert","cv","à",16.73,-22.93,True,
     "Sal, île balnéaire du Cap-Vert — Santa Maria, salines de Pedra de Lume et kitesurf.",
     -5270063,"Sal","Cape Verde",
     "Sal, Cape Verde's beach island — Santa Maria, Pedra de Lume salt flats and kitesurfing.",True,False),

    # ── DIVERS HAUTE VALEUR (4) ──
    ("mongolie","mongolia","la Mongolie","Mongolie","Mongolie","mn","en",47.92,106.92,False,
     "La Mongolie, terre des steppes infinies — yourtes nomades, désert de Gobi et festival Naadam.",
     -5270064,"Mongolia","Mongolia",
     "Mongolia, land of endless steppes — nomadic yurts, Gobi Desert and Naadam Festival.",True,False),
    ("zanzibar-ville","stone-town","Stone Town","Stone Town","Tanzanie","tz","à",-6.16,39.19,True,
     "Stone Town, cœur historique de Zanzibar — dédale de ruelles, palais des sultans et portes sculptées UNESCO.",
     -5270065,"Stone Town","Tanzania",
     "Stone Town, historic heart of Zanzibar — labyrinth of lanes, sultans' palaces and UNESCO carved doors.",True,False),
    ("socotra","socotra","Socotra","Socotra","Yémen","ye","à",12.47,53.87,True,
     "Socotra, Galápagos de l'océan Indien — arbres dragon, plages vierges et biodiversité unique.",
     -5270066,"Socotra","Yemen",
     "Socotra, Galápagos of the Indian Ocean — dragon blood trees, pristine beaches and unique biodiversity.",True,False),
    ("svalbard","svalbard","le Svalbard","Svalbard","Norvège","no","au",78.23,15.65,False,
     "Le Svalbard, archipel arctique — ours polaires, glaciers et soleil de minuit au bout du monde.",
     -5270067,"Svalbard","Norway",
     "Svalbard, Arctic archipelago — polar bears, glaciers and midnight sun at the edge of the world.",True,False),
]

# ── Validate & append ──
dupes = [e[0] for e in NEW if e[0] in existing]
if dupes:
    print(f"⚠️  DUPLICATES: {dupes}")
    NEW = [e for e in NEW if e[0] not in existing]

print(f"Adding {len(NEW)} new destinations")

with open(CSV_PATH, 'a', encoding='utf-8', newline='') as f:
    writer = csv.writer(f)
    for entry in NEW:
        writer.writerow(entry)
        existing.add(entry[0])

print(f"✅ Total destinations: {len(existing)}")
