"""Batch 14 : 22 avis FR Tier 2 stations ski moyennes."""
import json

PATH = 'data/avis_annuel.json'

AVIS_BATCH14_FR = {
    "megeve:fr": "Megève, en Haute-Savoie : 3000 habitants à 1100m, fondée en 1916 par Noémie de Rothschild comme alternative française à Saint-Moritz, station-village au charme préservé (interdiction de construire en bétons immeubles, architecture chalets traditionnels savoyards strictement réglementée). <strong>Août est mon mois préféré</strong> (8.1/10) : 11-23°C, 45% de pluie en orages d'altitude, randonnée alpine, golf 18 trous, festival d'opéra et de musique baroque. <strong>De juin à septembre</strong>, comptez 4-23°C : saison estivale active. <strong>De décembre à mars</strong>, comptez -5/8°C et 42-46% de précipitations souvent neige : c'est la haute saison ski. <strong>Pistes</strong> : 445 km Évasion Mont-Blanc (Megève + Saint-Gervais + Combloux + La Giettaz + Praz-sur-Arly), altitude moyenne pour la Haute-Savoie (1100-2350m, donc enneigement parfois moyen avant Noël et après Pâques). <strong>Mont d'Arbois</strong>, <strong>Côte 2000</strong>, <strong>Rochebrune</strong> (3 massifs séparés, navettes gratuites). Megève est moins technique que Val d'Isère ou Tignes, plus douce et familiale, classe haut de gamme. <strong>Public</strong> : aristocratie française et belge, familles aisées, ambiance plus discrète que Courchevel. <strong>Hôtels</strong> : <strong>Les Fermes de Marie</strong> (Sibuet, 5* relais & chateaux), <strong>Le Four Seasons Megève</strong> (5*+ ouvert 2017), <strong>Les Loges Blanches</strong>, <strong>Mont-Blanc</strong> (palace historique), 250-2500€/nuit en haute saison. <strong>Tester</strong> tartiflette, fondue savoyarde, raclette, diots, génépi, vins de Savoie. <strong>Logistique</strong> : Megève à 1h15 de Genève en voiture (l'aéroport de Genève est l'accès le plus rapide pour la Haute-Savoie depuis Paris).",

    "morzine:fr": "Morzine, dans les Portes du Soleil : 3000 habitants à 1000m, l'une des plus grandes stations village de France (architecture chalets en bois, pas de bétons), reliée à Avoriaz par téléphérique. <strong>Août est mon mois préféré</strong> (8.2/10) : 13-23°C, 40% de pluie, randonnée et VTT (Morzine = capitale française du VTT de descente avec Crankworx). <strong>De juin à septembre</strong>, comptez 5-23°C : saison estivale très active (parmi les stations alpines les plus dynamiques en été), Pass'Portes du Soleil VTT en juin avec 600 km de pistes. <strong>De décembre à mars</strong>, comptez -4/6°C et 42-47% de précipitations souvent neige : c'est la haute saison ski. <strong>Pistes</strong> : 600 km Portes du Soleil (12 stations reliées dont Morzine + Avoriaz + Châtel côté français, Champéry + Champoussin + Les Crosets côté suisse), 1 seul ski pass, l'un des plus grands domaines skiables au monde. <strong>Pleney</strong> et <strong>Nyon-Pointe de Nyon</strong> = 2 versants principaux à Morzine, accessibles par téléphérique depuis le centre village. <strong>Avoriaz</strong> à 15 min en téléphérique (station-village construite en bois en 1966 par Jacques Labro, sans voitures, navettes en calèches). <strong>Public</strong> : Britanniques très nombreux (40% de la clientèle hivernale), familles, snowboarders. Plus accessible que Megève en termes de prix. <strong>Hôtels</strong> : Hôtel Le Tremplin, La Bergerie, Mountain Mavericks (chalets britanniques) - 100-500€/nuit. <strong>Tester</strong> tartiflette, raclette, fondue, diots aux pommes. <strong>Logistique</strong> : Morzine à 1h15 de Genève en voiture/taxi (transferts touristiques courants), à 80 km de la frontière suisse.",

    "la-clusaz:fr": "La Clusaz, en Haute-Savoie : 1900 habitants à 1100m, station-village authentique de la <strong>chaîne des Aravis</strong> (Aiguille de Borderan, Mont Charvin), à 30 min d'Annecy. Souvent surnommée \"la station qui a gardé son âme\" (architecture chalets bois et lauze, vie villageoise toute l'année, fromagerie reblochon AOP). <strong>Juillet-août sont mes mois préférés</strong> (8.2/10) : 12-23°C, 43-47% de pluie en orages, randonnée Aravis, lac d'Annecy à 30 min, base de loisirs aux Confins. <strong>De décembre à mars</strong>, comptez -4/6°C et 40-46% de précipitations souvent neige : c'est la haute saison ski. <strong>Pistes</strong> : 132 km La Clusaz + Le Grand-Bornand voisin (1 seul ski pass), 84 pistes, dénivelé 1500m, altitude 1100-2600m, 4 massifs (Beauregard, L'Etale, L'Aiguille, La Balme - le plus haut). <strong>Hors-piste</strong> : combe du Fernuy, Combe de Borderan. La Clusaz est <strong>moins chère que Megève</strong> et <strong>moins technique que Tignes/Val d'Isère</strong>, idéale familles et débutants-intermédiaires. <strong>Public</strong> : Lyonnais, Annéciens en weekends, familles françaises, peu de Britanniques (contraire de Morzine). <strong>Hôtels</strong> : Au Cœur du Village (5*), Beauregard (4*), 150-600€/nuit. <strong>Reblochon AOP</strong> = fromage signature des Aravis (visite ferme à La Ferme du Reblochon). <strong>Tester</strong> tartiflette à base de reblochon (origine ici), fondue au reblochon, diots, vins de Savoie. <strong>Logistique</strong> : La Clusaz à 30 min d'Annecy, 1h de Genève, accessible en bus depuis la gare TGV d'Annecy.",

    "les-gets:fr": "Les Gets, dans les Portes du Soleil : 1300 habitants à 1170m, station-village voisine de Morzine reliée par les remontées (Mont Chéry et Chavannes-Ranfolly), village au charme savoyard préservé. <strong>Août est mon mois préféré</strong> (8.0/10) : 12-22°C, 44% de pluie en orages, randonnée et VTT (les Portes du Soleil = capitale européenne du VTT). <strong>De juin à septembre</strong>, comptez 4-22°C : saison estivale active, golf 18 trous, lac aux Écoles. <strong>De décembre à mars</strong>, comptez -5/4°C et 43-48% de précipitations souvent neige : c'est la haute saison ski. <strong>Pistes</strong> : 600 km Portes du Soleil (idem Morzine, voir ci-dessus), 145 pistes au total, 197 remontées, dénivelé 2300m. Les Gets a son propre versant (<strong>Mont Chéry</strong> moins fréquenté, ombragé, idéal débutants en début d'après-midi) et accède aux 11 autres stations via les <strong>Chavannes-Ranfolly</strong>. <strong>Public</strong> : familles françaises et britanniques (les Britanniques sont très nombreux dans les Portes du Soleil, école PCC), ambiance plus calme que Morzine, plus chic que Châtel. <strong>Hôtels</strong> : <strong>The Alpina Eclectic Hotel</strong> (4*+), <strong>Crychar</strong> (4*), Marmotte, 150-700€/nuit. <strong>Musée des Mécaniques</strong> à musique (collection unique de pianos mécaniques et orgues de Barbarie XVIIIe-XIXe). <strong>Tester</strong> tartiflette, fondue, croziflette, diots, vin de Savoie. <strong>Logistique</strong> : Les Gets à 1h15 de Genève en voiture, accessible par navettes depuis la gare TGV de Genève, situé à 5 min en voiture de Morzine.",

    "flaine:fr": "Flaine, dans le <strong>Grand Massif</strong> : 1600m, station altitude (la plus haute du Grand Massif), <strong>architecture brutaliste signée Marcel Breuer</strong> (architecte du Bauhaus, élève de Mies van der Rohe), ouverte en 1969 = sujet de polémique architecturale (béton brut au cœur des Alpes, considérée la plus laide ou la plus visionnaire selon les avis). <strong>Août est mon mois préféré</strong> (8.2/10) : 11-22°C, 39% de pluie en orages, randonnée alpine. <strong>De juin à septembre</strong>, comptez 4-22°C : saison estivale courte. <strong>De décembre à mars</strong>, comptez -6/5°C et 41-48% de précipitations souvent neige : c'est la haute saison ski, très bon enneigement grâce à l'altitude. <strong>Pistes</strong> : 265 km Grand Massif (Flaine + Samoëns + Morillon + Sixt + Les Carroz, 1 seul ski pass), altitude 700-2500m, dénivelé 1800m. <strong>Pistes signature</strong> : <strong>Cascades</strong> (l'une des plus longues pistes vertes au monde, 14 km depuis Tête des Lindars 2480m jusqu'à Sixt 770m, accessible aux débutants !), <strong>Combe de Gers</strong> (face nord ombragée, neige conservée). <strong>Hors-piste</strong> : Combe du Fer-à-Cheval, Aiguille du Plan Praz. <strong>Public</strong> : familles, scolaires (Flaine accueille beaucoup de classes de neige grâce aux résidences UCPA), ambiance fonctionnelle plutôt que chic. <strong>Hôtels</strong> : Totem (architecture Breuer signature, Hotel Le Refuge du Golf, Hotel Aujon), 100-400€/nuit. <strong>Sculptures</strong> : Picasso (\"Tête de femme\"), Vasarely, Dubuffet exposées en plein air dans la station. <strong>Tester</strong> tartiflette, fondue. <strong>Logistique</strong> : Flaine à 1h15 de Genève (parking obligatoire au pied de la station, accès piétonnier seulement pour les voitures), navettes Magny-Cluses-Flaine depuis la gare TGV.",

    "les-deux-alpes:fr": "Les Deux Alpes, dans l'Oisans : 1650m, station-village construite dans les années 50 (architecture années 50-60 caractéristique, pas de chalets traditionnels), reliée par téléphérique au <strong>glacier 3200m</strong> (le plus grand glacier skiable d'Europe en été). <strong>Juillet est mon mois préféré</strong> (7.8/10) : 9-19°C, 38% de pluie, <strong>ski d'été sur le glacier</strong> (la station est ouverte de fin juin à fin août pour le ski et snowboard d'été, l'une des seules au monde). <strong>De décembre à avril</strong>, comptez -9/10°C et 38-65% de précipitations souvent neige : c'est la haute saison ski. <strong>Pistes</strong> : 220 km Les Deux Alpes (97 pistes, 49 remontées), reliée à <strong>Alpe d'Huez</strong> par téléphérique seulement (pas par pistes), dénivelé record 2300m (le plus important d'Europe entre 1300m et 3600m glacier de Mont-de-Lans). <strong>Pistes mythiques</strong> : descente du glacier (16 km depuis 3600m), Sarenne (l'une des plus longues d'Europe à 16 km, à Alpe d'Huez voisine). <strong>Hors-piste</strong> : Vallée Blanche (à ne pas confondre avec celle de Chamonix), Combe de la Selle. <strong>Public</strong> : freeriders et freestylers (snowpark de référence européenne en été), Néerlandais et Britanniques nombreux, jeunes (vie nocturne dynamique). <strong>Hôtels</strong> : Côte Brune, Edelweiss, Souleil'Or, 150-600€/nuit. <strong>La Grave</strong> à 30 min (la station hors-piste mythique, 1 seul téléphérique non damé jusqu'à 3550m, paradis du freeride mondial sans pistes balisées, dangerosité élevée). <strong>Tester</strong> tartiflette, fondue, vin du Diois. <strong>Logistique</strong> : Les Deux Alpes à 1h30 de Grenoble en voiture, route en lacets jusqu'à 1650m.",

    "les-menuires:fr": "Les Menuires, dans les <strong>Trois Vallées</strong> : 1850m, station-village construite dans les années 60-70 (architecture béton type \"machine à skier\"), souvent considérée comme \"la moins chère des 3 Vallées\" face à Courchevel/Méribel/Val Thorens, mais avec accès au plus grand domaine skiable au monde (600 km). <strong>Juillet-août sont mes mois préférés</strong> (7.9/10) : 7-20°C, 37-38% de pluie en orages, randonnée alpine, VTT, mais Les Menuires reste avant tout une station hivernale (beaucoup d'hôtels et restos fermés en été). <strong>De décembre à avril</strong>, comptez -10/6°C et 36-58% de précipitations souvent neige : c'est la haute saison ski, l'une des stations les plus enneigées des Alpes françaises grâce à l'altitude. <strong>Pistes 3 Vallées</strong> : 600 km au total, accès direct depuis Les Menuires vers Val Thorens (10 min en télésiège) et Méribel (20 min en téléphérique). <strong>La Masse</strong> = pic local (2804m, panorama Mont Blanc). <strong>Public</strong> : familles aisées françaises et néerlandaises, snowboarders (Snowpark Béranger), <strong>contraste avec Val Thorens</strong> festive et Méribel chic. <strong>Architecture</strong> : station rénovée depuis les années 2000 avec quartier <strong>Reberty 1850</strong> en architecture chalet (plus chic), tandis que <strong>La Croisette</strong> central reste années 70. <strong>Hôtels</strong> : Le Kaya (4*), L'Ours Blanc, Les Loges Vanoise (4*), 150-700€/nuit. <strong>Tester</strong> tartiflette, fondue savoyarde, raclette, beaufort. <strong>Logistique</strong> : Les Menuires à 2h15 de Lyon en voiture, train Paris-Moûtiers + bus 50 min.",

    "madonna-di-campiglio:fr": "Madonna di Campiglio, dans le <strong>Trentin italien</strong> : 700 habitants à 1550m au cœur des <strong>Brenta Dolomites</strong> (UNESCO 2009, paysages dolomitiques signature), réputée comme la \"Saint-Moritz italienne\" pour son chic et ses tarifs. <strong>Août est mon mois préféré</strong> (7.3/10) : 9-19°C, 70% de pluie en orages d'altitude, randonnée Brenta, via ferrata. <strong>De juin à septembre</strong>, comptez 5-19°C : saison estivale active (climbing, escalade dans les Brenta = berceau de l'escalade italienne, Cesare Maestri). <strong>De décembre à avril</strong>, comptez -11/7°C et 26-44% de précipitations souvent neige : c'est la haute saison ski. <strong>Pistes</strong> : 156 km Skiarea Campiglio Dolomiti di Brenta (Madonna + Pinzolo + Folgarida + Marilleva, 1 seul ski pass), reliée à <strong>Dolomiti Superski</strong> par bus navettes (1200 km de pistes dans 12 stations dolomitiques, 1 seul forfait). <strong>3 Tre</strong> (slalom de Coupe du Monde mythique fin décembre sur la piste Canalone Miramonti, l'une des pistes les plus connues du circuit). <strong>Pistes</strong> : Spinale, 5 Laghi, Pradalago, Grostè (3000m, Brenta panorama). <strong>Hors-piste</strong> Brenta (avec guide). <strong>Public</strong> : aristocratie italienne (Milanais, Vénitiens), familles aisées italiennes, plus chic que Cortina. <strong>Hôtels</strong> : <strong>Hotel DV Chalet</strong>, <strong>Hotel Alpen Suite</strong>, <strong>Lefay Resort & Spa</strong> (5*+), 200-2000€/nuit en haute saison. <strong>Carlo Magno Hotel</strong> = palace historique. <strong>Tester</strong> canederli, polenta, casunziei, speck, vins Trentin (Pinot Bianco, Müller-Thurgau). <strong>Logistique</strong> : Madonna à 2h30 de Milan ou Vérone en voiture, à 4h de Munich.",

    "crans-montana:fr": "Crans-Montana, station ski et golf suisse premium dans le <strong>Valais</strong> : 5000 habitants permanents à 1500m sur un plateau ensoleillé, fondée en 1893 (l'une des plus anciennes stations alpines), accessible par funiculaire depuis Sierre dans la vallée. <strong>Août est mon mois préféré</strong> (8.1/10) : 10-21°C, 34% de pluie, randonnée alpine, <strong>Omega European Masters de golf</strong> début septembre (l'une des étapes du Tour Européen de golf, sur le Severiano Ballesteros Course 18 trous). <strong>De juin à septembre</strong>, comptez 6-21°C : saison estivale très active (golf, randonnée, lac de Crans, parapente). <strong>De décembre à mars</strong>, comptez -8/4°C et 37-43% de précipitations souvent neige : c'est la haute saison ski. <strong>Pistes</strong> : 140 km Crans-Montana (60 pistes, 22 remontées), altitude 1500-3000m (Plaine Morte glacier), dénivelé 1500m. <strong>Plaine Morte</strong> (3000m, glacier accessible en téléphérique depuis Violettes, ski d'été possible jusqu'à juillet en bonne année). <strong>Pistes</strong> : Crans-Montana est plus orientée balades-douceur que défi technique (pistes larges, ensoleillement record en Valais), idéale familles et seniors. <strong>Public</strong> : aristocratie suisse alémanique et romande, Belges et Néerlandais en hiver, nombreux résidents permanents (Crans-Montana est aussi une zone résidentielle 4 saisons). <strong>Hôtels</strong> : <strong>LeCrans Hotel & Spa</strong> (5*+), <strong>Guarda Golf</strong> (5*+), <strong>Royal Hotel</strong>, 200-2500€/nuit. <strong>Caves de la Montagne</strong> (vins de Sierre, fendant et Petite Arvine). <strong>Tester</strong> raclette, fondue moitié-moitié (Vacherin Fribourgeois + Gruyère), Tartare de viande séchée, vins valaisans. <strong>Logistique</strong> : Crans-Montana à 2h de Genève (Sierre en train + funiculaire 12 min, ou route).",

    "grindelwald:fr": "Grindelwald, station-village suisse au pied de l'<strong>Eiger</strong> (3970m, célèbre face nord de 1800m d'altitude, l'une des grandes parois alpines avec le Cervin et les Grandes Jorasses) : 4000 habitants à 1000m dans le canton de Berne (Oberland bernois). <strong>Août est mon mois préféré</strong> (7.8/10) : 13-23°C, 59% de pluie en orages, randonnée alpine, panorama unique sur Eiger-Mönch-Jungfrau (Big Three des Alpes bernoises). <strong>De juin à septembre</strong>, comptez 6-23°C : saison estivale très active (climbing, randonnée, parapente, Bachalpsee lac d'altitude photogénique). <strong>De décembre à mars</strong>, comptez -1/8°C et 47-55% de précipitations souvent neige : c'est la haute saison ski. <strong>Pistes</strong> : 100 km Jungfrau Ski Region (Grindelwald + Wengen + Mürren, 1 seul ski pass), accessible par train (Wengernalpbahn, l'une des rares stations sans voitures pour Wengen). <strong>Pistes signatures</strong> : <strong>Lauberhorn</strong> à Wengen voisine (descente de Coupe du Monde mi-janvier, l'une des plus longues du circuit 4,5 km). <strong>Eiger Express</strong> (téléphérique inauguré 2020, 15 min jusqu'à Eigergletscher 2300m, accès au <strong>Jungfraujoch</strong> 3454m \"Top of Europe\" via tunnel ferroviaire datant 1912). <strong>First</strong> (téléphérique, randonnée Bachalpsee, First Cliff Walk, tyrolienne). <strong>Public</strong> : Britanniques très nombreux historiquement (Grindelwald a été \"découvert\" par les Britanniques au XIXe siècle), Asiatiques en visite journée pour Jungfraujoch. <strong>Hôtels</strong> : Belvedere Swiss Quality, Sunstar Alpine, Hotel Spinne, 150-800€/nuit. <strong>Tester</strong> rösti, raclette, fondue, Älplermagronen. <strong>Logistique</strong> : Grindelwald à 1h30 de Berne en train via Interlaken, 3h de Zürich.",

    "interlaken:fr": "Interlaken, ville suisse entre les <strong>lacs de Brienz et Thoune</strong> dans l'Oberland bernois : 6000 habitants à 568m, base touristique principale pour visiter Jungfraujoch et l'Oberland (Grindelwald, Wengen, Mürren à 30-45 min). <strong>Août est mon mois préféré</strong> (8.1/10) : 16-25°C, 49% de pluie, terrasses, croisières sur les 2 lacs (Brienz et Thoune), parapente (Interlaken = capitale mondiale du parapente avec atterrissage central sur Höhematte le pré central). <strong>De juin à septembre</strong>, c'est la haute saison touristique : 14-25°C, climat tempéré par les lacs. <strong>De décembre à mars</strong>, comptez 1-9°C et 45-54% de précipitations souvent neige : ski sur les stations voisines (Grindelwald 30 min, Mürren 45 min), à Interlaken même peu de neige (568m), marché de Noël Bahnhofstrasse. <strong>Sites majeurs</strong> : <strong>Höhematte</strong> (grand pré central avec vue Jungfrau-Mönch-Eiger), <strong>Harder Kulm</strong> (1322m, funiculaire 8 min, vue panoramique sur les 2 lacs et l'Oberland), <strong>Schynige Platte</strong> (2076m, train à crémaillère depuis Wilderswil, panorama jardin botanique alpin), <strong>Lac de Thoune</strong> (croisières en bateau à vapeur Blümlisalp 1906), <strong>Lac de Brienz</strong> (croisières vers Iseltwald + Giessbachfälle cascade), <strong>Trümmelbachfälle</strong> à 30 min (10 cascades intra-glaciaires accessibles en ascenseur). <strong>Activités</strong> : <strong>parapente biplace</strong> depuis Beatenberg ou Niederhorn (atterrissage à Höhematte, 200 CHF), <strong>canyoning</strong> dans Saxetenbach, <strong>rafting</strong>, <strong>Jungfraujoch</strong> en train (3h aller-retour, 220 CHF). <strong>Tester</strong> rösti, raclette, fondue, viande des Grisons. <strong>Logistique</strong> : Interlaken à 2h de Zürich, 1h de Berne en train.",

    "wengen:fr": "Wengen, station ski-village suisse <strong>sans voitures</strong> (accessible uniquement par train à crémaillère Wengernalpbahn 1893 depuis Lauterbrunnen) : 1300 habitants à 1274m, vue spectaculaire sur la Jungfrau (4158m). <strong>Août est mon mois préféré</strong> (7.6/10) : 12-20°C, 51% de pluie en orages d'altitude, randonnée alpine, vues depuis le perron Mannlichen 2230m. <strong>De juin à septembre</strong>, comptez 5-20°C : saison estivale active. <strong>De décembre à mars</strong>, comptez -4/6°C et 47-53% de précipitations souvent neige : c'est la haute saison ski. <strong>Pistes</strong> : 100 km Jungfrau Ski Region (Wengen + Grindelwald + Mürren, 1 seul ski pass), altitude 944-2486m, dénivelé 1500m. <strong>Pistes signatures</strong> : <strong>Lauberhorn</strong> = la plus longue piste de Coupe du Monde de descente au monde (4,5 km, dénivelé 1028m, vitesse maximale 160 km/h sur le Hundschopf saut, course mi-janvier weekend depuis 1930), <strong>Männlichen-Kleine Scheidegg</strong> (descente facile et photogénique avec Eiger en arrière-plan). <strong>Hors-piste</strong> Tschuggen, Innerwengen. <strong>Public</strong> : Britanniques traditionnellement très présents (Downhill Only Club fondé en 1925 par 12 Britanniques), Suisses alémaniques, ambiance familiale et calme. <strong>Hôtels</strong> : Beausite Park (4*), Hotel Regina (4*), Hotel Belvedere, Eiger Selfness, 150-700€/nuit. <strong>Pas de circulation automobile dans le village</strong> = atmosphère unique, transports en luge à bagages. <strong>Tester</strong> rösti, fondue, Älplermagronen, Engadiner Nusstorte (gâteau aux noix). <strong>Logistique</strong> : Wengen à 30 min d'Interlaken en train (Lauterbrunnen + Wengernalpbahn), pas de route possible en voiture jusqu'au village.",

    "mayrhofen:fr": "Mayrhofen, station ski autrichienne dans le <strong>Zillertal</strong> (Tyrol) : 4000 habitants à 630m (basse altitude pour le village, mais accès aux glaciers Hintertux à 30 min en bus), village traditionnel tyrolien aux balcons fleuris l'été et aux Stuben en hiver. <strong>Août est mon mois préféré</strong> (8.0/10) : 14-25°C, 56% de pluie en orages d'altitude, randonnée Zillertal Alps, VTT. <strong>De juin à septembre</strong>, comptez 7-25°C : saison estivale très active (Zillertal = capitale autrichienne du VTT, Bike-Up festival mi-septembre). <strong>De décembre à avril</strong>, comptez -4/14°C et 43-67% de précipitations souvent neige : c'est la haute saison ski. <strong>Pistes</strong> : 142 km Mayrhofen-Hippach (4e plus grand domaine du Tyrol), 60 pistes, 57 remontées, altitude 630-2500m. <strong>Pistes mythiques</strong> : <strong>Harakiri</strong> (78% de pente, la piste damée la plus raide d'Autriche, l'une des plus raides au monde, à Penken). <strong>Hintertux Glacier</strong> à 30 min en bus (Tuxer Ferner, ouvert toute l'année 365 jours/365, l'un des seuls glaciers européens skiable en été). <strong>Snowboarding</strong> : Mayrhofen est l'une des stations de référence européenne pour le freestyle (Snowpark Penken). <strong>Après-ski</strong> : Mo's, Brücke, Ice Bar = institutions festives autrichiennes. <strong>Public</strong> : Britanniques très nombreux, Néerlandais, Allemands, fêtes nocturnes énormes (Mayrhofen rivalise avec Ischgl pour l'after-ski). <strong>Hôtels</strong> : Hotel Edenlehen, Elisabethhotel (4*+), Hotel Strass, 100-500€/nuit. <strong>Tester</strong> Tiroler Gröstl, Käsespätzle, Kaiserschmarrn, Apfelstrudel, schnaps Stroh 80°. <strong>Logistique</strong> : Mayrhofen à 1h30 d'Innsbruck en voiture, train direct depuis Innsbruck via Jenbach + Zillertalbahn.",

    "schladming:fr": "Schladming, station ski autrichienne dans le <strong>Land de Styrie</strong> : 7000 habitants à 745m, ville-station qui a accueilli les <strong>Championnats du Monde de Ski Alpin 2013</strong>. Plus authentique et moins festive que les stations tyroliennes (Mayrhofen, Ischgl, St. Anton). <strong>Août est mon mois préféré</strong> (7.8/10) : 14-24°C, 60% de pluie en orages d'altitude, randonnée dans le <strong>Dachstein</strong> (2995m, point culminant de Styrie). <strong>De juin à septembre</strong>, comptez 6-24°C : saison estivale active. <strong>De décembre à avril</strong>, comptez -4/13°C et 42-69% de précipitations souvent neige : c'est la haute saison ski. <strong>Pistes</strong> : 230 km <strong>Ski Amadé</strong> (Schladming-Dachstein partie de Ski Amadé, le plus grand domaine d'Autriche : 760 km de pistes répartis sur 5 régions Schladming + Salzburger Sportwelt + Hochkönig + Gastein + Großarltal, 1 seul ski pass valable dans tout). <strong>Schladming-Dachstein 4-Mountain Skipass</strong> : 4 montagnes reliées (Hauser Kaibling, Planai, Hochwurzen, Reiteralm) pour 123 km en propre. <strong>Planai</strong> = sommet emblématique avec descente World Cup nocturne <strong>Nightrace</strong> (slalom de nuit fin janvier, l'une des courses les plus regardées au monde, 50 000 spectateurs au stade illuminé). <strong>Dachstein Glacier</strong> (2700m, ski d'été et automne, ski randonnée toute l'année). <strong>Public</strong> : Allemands en majorité, Néerlandais, familles autrichiennes, ambiance plus calme que le Tyrol. <strong>Hôtels</strong> : Falkensteiner Hotel Schladming (4*+), Hotel Stadttor, 100-400€/nuit. <strong>Tester</strong> Schweinsbraten (rôti de porc), Steirisches Kürbiskernöl (huile de pépins de courge styrienne, AOC), Apfelstrudel. <strong>Logistique</strong> : Schladming à 1h15 de Salzburg en voiture/train, à 2h30 de Vienne.",

    "ischgl:fr": "Ischgl, station ski autrichienne dans le <strong>Paznaun Valley</strong> (Tyrol) : 1600 habitants à 1377m, station ultra-festive surnommée \"l'Ibiza des Alpes\" (tristement célèbre comme épicentre européen du Covid-19 en mars 2020 = des milliers de skieurs européens contaminés). Reliée à <strong>Samnaun</strong> en Suisse par les remontées (Silvretta Arena = ski transfrontalier sans formalité douanière, achats hors-taxe en Suisse). <strong>Août est mon mois préféré</strong> (7.7/10) : 10-22°C, 58% de pluie en orages d'altitude, randonnée Paznaun, VTT. <strong>De juin à septembre</strong>, comptez 4-22°C : saison estivale calme. <strong>De décembre à avril</strong>, comptez -8/6°C et 42-64% de précipitations souvent neige : c'est la haute saison ski, l'une des plus enneigées d'Autriche. <strong>Pistes</strong> : 239 km Silvretta Arena (Ischgl + Samnaun, 1 seul ski pass), altitude 1377-2872m, dénivelé 1500m, 45 remontées modernes (Ischgl est connue pour ses télésièges chauffants et capots, l'un des parcs de remontées les plus modernes d'Europe). <strong>Idalp</strong> = plateau central à 2300m, accès direct par téléphérique depuis le village (15 min). <strong>Top of the Mountain Concert</strong> = ouverture/clôture de saison fin novembre/début mai avec un grand concert d'artistes internationaux gratuit en plein air (Mariah Carey, Kylie Minogue, Bon Jovi, Robbie Williams, Elton John, James Blunt ont joué). <strong>Après-ski</strong> : Pacha, Trofana Alm, Niki's Stadl, Schatzi Bar = institutions de fête autrichiennes (ambiance jusqu'à 22-23h, prix x3 vs ailleurs). <strong>Public</strong> : Allemands et Britanniques en majorité, jeunes 25-45, plus festif que sportif. <strong>Hôtels</strong> : Trofana Royal (5*+), Hotel Madlein (5*), Yscla, 200-1500€/nuit. <strong>Tester</strong> Kasspatzln, Tiroler Gröstl, Glühwein, Stroh 80. <strong>Logistique</strong> : Ischgl à 1h30 d'Innsbruck en voiture/bus.",

    "zell-am-see:fr": "Zell am See, station autrichienne dans le <strong>SalzburgerLand</strong> : 10 000 habitants à 757m sur le bord du <strong>Zeller See</strong> (lac de 4,5 km², température baignable 22°C en juillet-août), au pied du <strong>Schmittenhöhe</strong> (1965m). Combinaison unique lac + ski. <strong>Août est mon mois préféré</strong> (8.1/10) : 14-25°C, 50% de pluie, baignade dans le lac, terrasses, croisières en bateau, paragliding depuis Schmittenhöhe (atterrissage à proximité du lac). <strong>De juin à septembre</strong>, c'est la haute saison touristique estivale : 7-25°C, climat agréable, beaucoup de touristes du Moyen-Orient (Saoudiens, Émiratis qui fuient la canicule de Dubai-Riyad pour le frais alpestre). <strong>De décembre à avril</strong>, comptez -4/14°C et 40-51% de précipitations souvent neige : c'est la haute saison ski. <strong>Pistes</strong> : 408 km <strong>Ski Alpin Card</strong> (Schmittenhöhe + Kitzsteinhorn glacier de Kaprun voisin + Saalbach-Hinterglemm + Zell am See-Kaprun, 1 seul ski pass), 138 remontées, altitude 757-3029m (Kitzsteinhorn glacier, ski toute l'année quasiment). <strong>Schmittenhöhe</strong> a son propre domaine (77 km), mais l'intérêt majeur est l'accès au glacier <strong>Kitzsteinhorn</strong> (2 vallées plus loin, navette gratuite 30 min) qui garantit la neige toute la saison. <strong>Public</strong> : familles européennes en hiver, touristes du Golfe en été, Britanniques aussi nombreux. <strong>Hôtels</strong> : Grand Hotel Zell am See (4*+), Salzburgerhof (5*), Mavida, 150-1000€/nuit. <strong>Tester</strong> Kaiserschmarrn, Wiener Schnitzel, Salzburger Nockerl. <strong>Logistique</strong> : Zell am See à 1h15 de Salzburg en voiture/train.",

    "mont-tremblant:fr": "Mont-Tremblant, station ski québécoise dans les <strong>Laurentides</strong> : 9000 habitants à 200m d'altitude (le sommet du Mont-Tremblant culmine à 875m), à 130 km au nord de Montréal. <strong>L'une des stations les plus connues de l'est canadien et nord-américain</strong>, renommée pour son village piétonnier reconstruit en 1991 (Intrawest) avec architecture pseudo-européenne très réussie. <strong>Juillet est mon mois préféré</strong> (8.2/10) : 16-25°C, 49% de pluie, mais Mont-Tremblant est avant tout une destination hivernale. <strong>De juin à septembre</strong>, comptez 5-25°C : saison estivale active (golf 36 trous Le Géant et Le Diable, randonnée, mountain bike, baignade lac Tremblant). <strong>De décembre à mars</strong>, comptez -15/2°C et 41-47% de précipitations souvent neige (4-5m/saison) : c'est la haute saison ski. <strong>Pistes</strong> : 102 pistes, 14 remontées, dénivelé 645m (modeste comparé aux Alpes mais excellent pour l'Amérique du Nord), 4 versants (Sud principal, Nord, Soleil, Edge). Conditions caractéristiques : <strong>froid sec extrême</strong> (-25°C en janvier-février, lait de poule sur le visage gelé en quelques minutes), neige fraîche presque garantie (climat continental rigoureux), <strong>icy patches</strong> (plaques de glace) typiques. <strong>Public</strong> : Québécois en majorité, Américains du Nord-Est (Boston, NY), Européens en quête d'expérience nord-américaine. <strong>Tremblant Pedestrian Village</strong> : 50+ restos et boutiques, vie nocturne animée, ambiance village européen ressuscité. <strong>Hôtels</strong> : Fairmont Tremblant (5*), Hôtel Quintessence (5*+ au bord du lac), Westin, 150-800 CAD/nuit. <strong>Tester</strong> poutine, sirop d'érable, tourtière, bière micro-brasserie québécoise (La Diable). <strong>Logistique</strong> : Mont-Tremblant à 1h30 de Montréal en voiture (autoroute 15 nord puis 117), aéroport Mont-Tremblant International (YTM, vols saisonniers).",

    "hakuba:fr": "Hakuba, vallée japonaise dans la <strong>préfecture de Nagano</strong> (Alpes japonaises) : 9000 habitants à 700-1200m, ville-vallée qui a accueilli les épreuves alpines des <strong>JO d'hiver de Nagano 1998</strong>. Composée de 10 stations distinctes reliées par navettes gratuites avec un seul forfait. <strong>Juin est mon mois préféré</strong> (7.6/10) : 14-23°C, 58% de pluie en orages, randonnée alpine japonaise, mais Hakuba est avant tout une destination hivernale. <strong>De juin à septembre</strong>, comptez 9-29°C : saison estivale calme (au-dessus de 1500m climat agréable, en fond de vallée 700m chaud-humide). <strong>De décembre à mars</strong>, comptez -6/8°C et 51-73% de précipitations souvent neige (10m/saison, parmi les stations les plus enneigées au monde, climat \"Japan Powder\" légendaire) : c'est la haute saison ski. <strong>10 stations Hakuba Valley</strong> : Happo-One (la principale, 26 pistes, ex-piste de descente JO 1998), Hakuba 47 et Goryu (snowboarders), Tsugaike (familiale, snowpark), Iwatake, Sanosaka, Norikura, Cortina (vue Mont Yari), Hakuba Highland, Goryu Toomi. 1 forfait Hakuba Valley pour 200+ km de pistes. <strong>Hors-piste</strong> légendaire : <strong>Hakuba Backcountry</strong> attire les freeriders du monde entier (Australiens en majorité, eux qui ont popularisé le Japan Powder), guides obligatoires (avalanches fatales chaque saison). <strong>Onsen</strong> caractéristiques : Mimizuku no Yu, Daionji, Hakuba Shio no Michi (rotenburo bains extérieurs avec vue sur les sommets enneigés). <strong>Public</strong> : Japonais en majorité, Australiens (40% des étrangers), Singapouriens, Européens en croissance. <strong>Hôtels</strong> : Hakuba Tokyu, Hotel Gracery, ryokans traditionnels (200-1500€/nuit). <strong>Tester</strong> ramen miso, soba locales, sake Nagano. <strong>Logistique</strong> : Hakuba à 4h en train+bus de Tokyo (Shinkansen Nagano + bus 1h), à 1h en voiture de Nagano.",

    "furano:fr": "Furano, ville d'Hokkaido à 200 km au nord-est de Sapporo : 22 000 habitants au cœur d'Hokkaido (île nord du Japon), célèbre pour ses <strong>champs de lavande</strong> en juillet-août (les plus grands d'Asie, à voir à la <strong>Farm Tomita</strong>) et sa station ski hivernale réputée. <strong>Juillet est mon mois préféré</strong> (8.1/10) : 17-26°C, 48% de pluie, c'est la pleine saison touristique estivale (lavande en pleine floraison du 20 juin au 20 août, pic mi-juillet à mi-août, foules de touristes japonais et asiatiques pour photos). <strong>De juin à septembre</strong>, comptez 5-26°C : haute saison estivale (champs de fleurs colorés Patchwork de la nature, golf, vélo). <strong>De décembre à mars</strong>, comptez -11/3°C et 48-74% de précipitations souvent neige (12m/saison, parmi les stations les plus enneigées au monde après Niseko, \"Japan Powder\" légendaire) : c'est la haute saison ski. <strong>Pistes</strong> : 23 pistes Furano Ski Resort (gérée par Prince Hotels), altitude 235-1074m, dénivelé 839m, accès en télécabine 8 min depuis le village. <strong>Hors-piste</strong> Furano (avec guide, crossroads des Australiens), <strong>Furano Backcountry</strong> très réputé. <strong>Asahi-dake</strong> à 1h (volcan le plus haut d'Hokkaido 2291m, ski randonnée). <strong>Tester</strong> melon de Furano (le melon le plus cher du Japon, peut atteindre 200€ pour 1 melon de qualité supérieure), cantaloup melon ice cream, asperges blanches, fromage Furano (rare au Japon), sake d'Hokkaido. <strong>Public</strong> : Japonais et Asiatiques en majorité (été lavande), Australiens et Européens en hiver (ski). <strong>Hôtels</strong> : New Furano Prince Hotel, Furano Natulux Hotel, ryokans avec onsen. <strong>Logistique</strong> : Furano à 2h de Sapporo en train (depuis Sapporo Chitose Airport + train Asahikawa + train Furano), à 1h de l'aéroport régional Asahikawa.",

    "nozawa-onsen:fr": "Nozawa Onsen, station ski-village japonais dans la <strong>préfecture de Nagano</strong> : 3500 habitants à 600m, l'une des plus traditionnelles du Japon (\"village du onsen\" littéralement). 13 sources thermales gratuites publiques (\"soto-yu\") gérées par les habitants depuis le VIIIe siècle. <strong>Août est mon mois préféré</strong> (8.1/10) : 21-28°C, 53% de pluie, mais Nozawa Onsen est avant tout une destination hivernale et de bains. <strong>De juin à septembre</strong>, comptez 10-28°C : saison estivale très calme, traditions traditionnelles (Dosojin Fire Festival le 15 janvier mais préparation toute l'année). <strong>De décembre à mars</strong>, comptez -4/3°C et 53-79% de précipitations souvent neige (10m/saison, parmi les stations les plus enneigées du Japon) : c'est la haute saison ski. <strong>Pistes</strong> : 40 pistes Nozawa Onsen Ski Resort, altitude 565-1650m, dénivelé 1085m, 21 remontées. <strong>Hors-piste</strong> : Nozawa offre un excellent terrain de freeride avec accès via le Soyuyama et Yamabiko Field. <strong>13 sources thermales publiques</strong> gratuites (onsen \"soto-yu\") dans les ruelles du village, accessibles aux résidents du village et aux visiteurs (laisser une petite donation 100¥), température 40-50°C, séparées par sexe. Les plus connues : <strong>O-Yu</strong> (centrale, architecture bois traditionnelle XIXe), <strong>Asagama-no-Yu</strong> (la plus chaude). <strong>Dosojin Fire Festival</strong> le 15 janvier (l'un des 3 grands festivals du feu du Japon, hommes de 25 et 42 ans en duel rituel pour défendre une structure en bois géante contre les villageois qui tentent de l'incendier, spectaculaire). <strong>Public</strong> : Japonais en majorité (Tokyoïtes en weekends), Australiens en croissance, atmosphère beaucoup plus traditionnelle que Niseko (moins anglophone). <strong>Hôtels</strong> : ryokans traditionnels (Yumoto, Nakajimaya), Auberges modernes (Hotel Haus St. Anton), 100-500€/nuit. <strong>Tester</strong> nozawana (légume traditionnel mariné), soba, ramen miso Nagano, sake Hokujo. <strong>Logistique</strong> : Nozawa Onsen à 3h de Tokyo (Shinkansen Nagano 1h45 + bus 1h15), à 1h en bus de Nagano.",

    "revelstoke:fr": "Revelstoke, station ski en Colombie-Britannique (Canada) dans les <strong>Selkirk Mountains</strong> : 7500 habitants à 450m, ville étape historique sur la voie ferrée transcontinentale Canadian Pacific (1885). Station ski moderne ouverte en 2007, déjà parmi les meilleures d'Amérique du Nord pour les freeriders. <strong>Juillet-août sont mes mois préférés</strong> (8.9/10) : 13-26°C, 27-35% de pluie, randonnée Selkirk Mountains, kayak sur Columbia River, mountain bike. <strong>De juin à septembre</strong>, comptez 4-26°C : saison estivale très active (Revelstoke est aussi un hub aventure été : VTT, kayak, escalade, randonnée). <strong>De décembre à mars</strong>, comptez -6/6°C et 56-61% de précipitations souvent neige (12-15m/saison, parmi les plus enneigées d'Amérique du Nord) : c'est la haute saison ski. <strong>Pistes Revelstoke Mountain Resort</strong> : 75 pistes, 5 remontées, <strong>dénivelé record d'Amérique du Nord 1713m</strong> (le plus important du continent), altitude 512-2225m. <strong>Cat skiing et heli skiing</strong> : Revelstoke est l'un des spots mondiaux pour le heli-ski (hors-piste depuis hélicoptère, 30 000-100 000m de dénivelé/jour avec guide, prix 800-2000$/jour). <strong>CMH Heli Skiing</strong> = pionnier mondial du heli-ski depuis 1965. <strong>Public</strong> : freeriders avancés du monde entier, professionnels du ski, peu de débutants (Revelstoke est connue pour ses pistes engagées noires et expert). <strong>Hôtels</strong> : Sutton Place Hotel Revelstoke Mountain Resort, Best Western Plus, lodges privés à proximité, 150-600 CAD/nuit. <strong>Glacier National Park</strong> à proximité (Rogers Pass, 4-5m de neige/an, route fermée régulièrement avalanches). <strong>Tester</strong> bison, saumon Sockeye, bières micro-brasseries (Mt. Begbie Brewing). <strong>Logistique</strong> : Revelstoke à 6h de Vancouver en voiture, 4h de Calgary, aéroport régional + transfert.",

    "stowe:fr": "Stowe, station ski historique dans le <strong>Vermont</strong> (USA) : 4500 habitants à 220m d'altitude (le sommet Mount Mansfield culmine à 1340m, point culminant du Vermont), surnommée \"la capitale du ski de l'Est américain\" depuis les années 1930-40. Plus authentique et plus accessible que Vail/Aspen mais moins enneigée. <strong>Juillet est mon mois préféré</strong> (8.3/10) : 16-26°C, 48% de pluie, randonnée Long Trail (sentier de longue distance traversant le Vermont), été doux, festivals (Stowe Performing Arts Series). <strong>De septembre à octobre</strong>, c'est la <strong>saison du foliage</strong> (couleurs d'automne) : 0-21°C, 30-43% de pluie, l'une des destinations légendaires d'Amérique du Nord pour observer les feuilles dorées et rouges (érables sucriers, bouleaux). Pic mi-octobre. <strong>De décembre à mars</strong>, comptez -12/4°C et 46-51% de précipitations souvent neige (5-7m/saison, neige conservée par les températures glaciales) : c'est la haute saison ski. <strong>Pistes Stowe Mountain Resort</strong> (gérée par Vail Resorts depuis 2017, partie de l'Epic Pass) : 116 pistes, 13 remontées, dénivelé 720m, 2 sommets reliés (Mount Mansfield + Spruce Peak). <strong>Pistes mythiques</strong> : <strong>Front Four</strong> (les 4 pistes mythiques difficiles : Goat, Lift Line, National, Starr - les plus exigeantes de l'Est américain). <strong>Stowe Recreation Path</strong> = 8 km de piste cyclable/piétonne dans la vallée, l'une des plus belles d'Amérique du Nord. <strong>Public</strong> : Bostoniens, New-Yorkais (Stowe est l'une des stations préférées des familles aisées de la côte Est), héritage skiers historiques (von Trapp Family de \"La Mélodie du Bonheur\" qui se sont installés ici après leur fuite d'Autriche en 1938). <strong>Hôtels</strong> : <strong>Trapp Family Lodge</strong> (5*, fondé par les von Trapp 1942, maintenant brewery aussi), Stowe Mountain Lodge, Topnotch Resort, 200-1000$/nuit. <strong>Tester</strong> Vermont maple syrup (le meilleur sirop d'érable au monde selon les Vermonters), Ben & Jerry's ice cream (origine à Burlington voisin), bières craft Vermont (The Alchemist Heady Topper, Hill Farmstead = bières les plus prisées au monde). <strong>Logistique</strong> : Stowe à 5h de Boston en voiture, 6h de NY, aéroport Burlington (BTV) à 50 min."
}

with open(PATH, encoding='utf-8') as f:
    data_existing = json.load(f)

before = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

data_existing['_version'] = '2.5'
data_existing['_updated'] = '2026-04-28'

for k, v in AVIS_BATCH14_FR.items():
    data_existing[k] = v

after = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data_existing, f, ensure_ascii=False, indent=2)

print(f"Avis FR avant : {before}")
print(f"Avis FR après : {after}")
print(f"Nouveaux : {after - before}")

# Audit immédiat
import re
patterns_check = [
    ('em-dash', r'—'), ('guillemets', r'[«»]'),
    ('attendez-vous', r'attendez-vous à'),
    ('parfait', r'\bparfait[es]*\b'),
    ('fenêtre', r'\bfenêtre[s]?\b'),
    ('saturé', r'\bsatur[eéa]\w*\b'),
    ('se mérite', r'\bse méri[tes]+\b'),
    ('magique', r'\bmagiques?\b'),
    ('Si vous X:', r'Si vous \w+ : '),
    ('iconique', r'\biconique[s]?\b'),
    ('antithèse', r'antithèse'),
    ('mythique', r'\bmythique[s]?\b'),
    ('emblématique', r'\bemblématique[s]?\b'),
    ('authentique', r'\bauthentique[s]?\b'),
    ('féérique', r'\bféérique[s]?\b'),
    ("c'est aussi", r"[Cc]'est aussi"),
    ('à monitorer', r'à monitorer'),
    ('à éviter', r'à éviter'),
]

print("\n=== Audit batch 14 ===")
issues_total = 0
for slug in AVIS_BATCH14_FR.keys():
    plain = re.sub(r'<[^>]+>', '', data_existing[slug])
    issues = []
    for label, p in patterns_check:
        n = len(re.findall(p, plain))
        if n > 0:
            issues.append(f"{label}={n}")
            issues_total += n
    flag = "OK" if not issues else "PB " + ", ".join(issues)
    print(f"  {slug:<22} {len(plain.split()):>3}m {flag}")
print(f"\nTotal issues : {issues_total}")
