"""Batch 16 : 20 avis FR Tier 2 USA restants + Amérique latine + Caraïbes."""
import json

PATH = 'data/avis_annuel.json'

AVIS_BATCH16_FR = {
    # === USA restants (7) ===
    "anchorage:fr": "Anchorage, plus grande ville de l'<strong>Alaska</strong> : 290 000 habitants (40% de la population de l'État, qui en compte 730 000 sur 1,7 million de km² - une densité comparable à la Sibérie). Située au fond du <strong>Cook Inlet</strong>, entourée par les Chugach Mountains et le Knik Arm. Hub aérien, base pour explorer l'Alaska sauvage. <strong>Juin-juillet sont mes mois préférés</strong> (7.9/10) : 10-20°C, 30-37% de pluie, c'est le \"jour sans fin\" (19h de lumière au solstice du 21 juin, jamais nuit complète), randonnée, kayak, observation des baleines, pêche au saumon. <strong>De juin à août</strong>, c'est la haute saison touristique : 7-20°C, prix hôteliers x3-x4 (croisières Inside Passage, Denali NP). <strong>De novembre à mars</strong>, comptez -10/2°C et 30-44% de précipitations souvent neige : c'est la haute saison pour les <strong>aurores boréales</strong> (visibles 200 nuits/an, mais Anchorage est moins bien placée que Fairbanks plus au nord), nuit polaire courte (5-6h de lumière en décembre). Iditarod (course de chiens de traîneau, 1600 km Anchorage-Nome, départ début mars). <strong>Sites majeurs</strong> : <strong>Anchorage Museum</strong> (histoire alaskaine, art autochtone), <strong>Tony Knowles Coastal Trail</strong> (18 km de piste cyclable côtière, observation moose et beluga), <strong>Earthquake Park</strong> (mémorial du tremblement de terre du Vendredi Saint 1964, magnitude 9,2, le 2e plus puissant jamais enregistré). <strong>Excursions</strong> : <strong>Denali National Park</strong> à 4h de route (Mt. Denali 6190m, le plus haut sommet d'Amérique du Nord, ours grizzly, élans), <strong>Kenai Fjords National Park</strong> à 2h30 (croisière depuis Seward, glaciers, baleines à bosse), <strong>Wasilla</strong> (ville natale de Sarah Palin), <strong>Talkeetna</strong> (village base d'expéditions Denali). <strong>Tester</strong> saumon sauvage (king salmon le plus prestigieux), halibut, reindeer sausage, Alaska beer. Vol direct depuis Seattle/Portland (3h30).",

    "asheville:fr": "Asheville, en Caroline du Nord : 95 000 habitants à 660m d'altitude au cœur des <strong>Blue Ridge Mountains</strong> (chaîne sud des Appalaches), réputée pour son ambiance bohème (\"the new Portland\"), ses brasseries craft (la plus grande densité par habitant des USA), et sa scène artistique. <strong>Juin est mon mois préféré</strong> (8.7/10) : 15-27°C, 42% de pluie, températures clémentes grâce à l'altitude. <strong>De mai à octobre</strong>, c'est la haute saison touristique : 8-29°C, climat doux. <strong>Octobre</strong> = saison du <strong>foliage</strong> spectaculaire (Blue Ridge Parkway = l'une des plus belles routes panoramiques d'Amérique du Nord pour les couleurs d'automne, pic mi-octobre), <strong>foule extrême</strong> sur les viewpoints, prix hôteliers x3. <strong>De juillet à août</strong>, comptez 17-29°C avec 47-53% de pluie : chaud, orages d'après-midi caractéristiques. <strong>De décembre à février</strong>, comptez -3/12°C : froid mais doux pour les Appalaches, neige légère possible. <strong>Sites majeurs</strong> : <strong>Biltmore Estate</strong> (la plus grande maison privée des USA, 16 622 m², 250 pièces, construite par George Vanderbilt 1889-1895, copie de château français, jardins par Frederick Law Olmsted créateur de Central Park, vignoble - la plus grande visite d'Amérique du Nord, billet 80$+, à réserver), <strong>Blue Ridge Parkway</strong> (754 km de route panoramique, sans publicité ni feu rouge, panoramas, accès depuis Asheville), <strong>Great Smoky Mountains National Park</strong> à 1h30 (UNESCO, le plus visité des USA, 12 millions de visiteurs/an), <strong>Mount Mitchell</strong> (2037m, le plus haut sommet à l'est du Mississippi). <strong>Centre-ville</strong> : architecture art déco rare (Pack Square, Grove Arcade), Asheville Brewers Trail (35+ brasseries dont Wicked Weed et Highland Brewing). <strong>Tester</strong> Carolina barbecue (vinegar-based), trout farm, biscuits and gravy, bières craft. Aéroport Asheville Regional, mais souvent on vole vers Charlotte/Atlanta + 2h de route.",

    "outer-banks:fr": "Outer Banks (\"OBX\"), chaîne de barrier islands de Caroline du Nord : 320 km de longues îles sablonneuses étroites séparant l'Atlantique du continent, 60 000 habitants permanents (population x10 en été), berceau de l'<strong>aviation moderne</strong> (les frères Wright ont effectué le 1er vol motorisé contrôlé à Kitty Hawk le 17 décembre 1903). <strong>Juin est mon mois préféré</strong> (8.7/10) : 24-25°C, 31% de pluie, mer à 24°C. <strong>De juin à septembre</strong>, c'est la haute saison touristique : 19-28°C, prix hôteliers x4-x5, locations de maisons sur la plage 2000-10000$/semaine, plages bondées (mais 200 km de plage = espace pour tous). <strong>De juillet-août chutent à 6.9/10</strong> à cause de la chaleur (25-28°C) et risque cyclonique débutant. <strong>De septembre à novembre</strong>, c'est la saison cyclonique active (la côte est USA est particulièrement exposée, les OBX sont surnommées \"<em>Graveyard of the Atlantic</em>\" pour les milliers de naufrages historiques + ouragans modernes). <strong>De décembre à mars</strong>, comptez 7-15°C et 28-38% de pluie : doux pour la côte est, beaucoup d'établissements ferment. <strong>Sites majeurs</strong> : <strong>Wright Brothers National Memorial</strong> (Kitty Hawk Hill, lieu exact du 1er vol, monument de granit 18m, hangar reconstitué), <strong>Cape Hatteras National Seashore</strong> (113 km de plages préservées, le plus haut phare en briques des USA 63m), <strong>Cape Hatteras Lighthouse</strong> (1870, déplacé de 880m vers l'intérieur en 1999 face à l'érosion côtière, 268 marches), <strong>Bodie Island Lighthouse</strong>, <strong>Currituck Beach Lighthouse</strong>, <strong>Jockey's Ridge State Park</strong> (les plus hautes dunes mobiles de la côte Est, 30m, parapente sandboarding), <strong>Roanoke Island</strong> et <strong>Lost Colony</strong> (la 1ère colonie anglaise d'Amérique 1587, disparue mystérieusement, théâtre en plein air l'été), <strong>Ocracoke Island</strong> (île préservée accessible uniquement en ferry, repaire historique du pirate Edward Teach \"Barbe Noire\"). <strong>Activités</strong> : surf (la côte est USA = capitale du surf hors Hawaï/Californie), kitesurf à Hatteras, parapente, fishing pier, mustang wild horses (Corolla, descendants des chevaux espagnols XVIe). <strong>Tester</strong> seafood (clam chowder version OBX, oysters, soft-shell crab), hush puppies (boules de pain frites). Aéroport Norfolk (Virginie) à 1h30 ou Raleigh-Durham à 3h.",

    "portland:fr": "Portland, dans l'Oregon (USA) : 650 000 habitants en aire urbaine, sur la <strong>rivière Willamette</strong> (qui traverse la ville et se jette dans le Columbia 30 km au nord). Ville hipster de référence des USA depuis les années 2000 (\"Keep Portland Weird\", emblème du mouvement \"slow living\" et craft beer américain), parcs urbains les plus étendus du pays. <strong>Juillet est mon mois préféré</strong> (9.9/10) : 14-28°C, seulement 7% de pluie (climat méditerranéen estival typique du Pacifique nord-ouest, étés secs et tempérés, hivers doux et pluvieux). <strong>D'août</strong> reste excellent (9.5/10). <strong>De juin à septembre</strong>, c'est la haute saison touristique : 12-29°C. <strong>De novembre à mars</strong>, comptez 2-11°C et 58-61% de pluie : doux mais grisâtre (Portland a la réputation d'être l'une des villes les plus pluvieuses des USA, ce qui est exagéré : Seattle, Mobile, Miami reçoivent en réalité plus de précipitations annuelles - mais Portland a effectivement plus de jours pluvieux). <strong>Sites majeurs</strong> : <strong>Powell's City of Books</strong> (la plus grande librairie indépendante au monde, 1,6 million de livres sur 5 étages, 6300 m²), <strong>Pearl District</strong> (ex-quartier industriel reconverti en zone branchée), <strong>Forest Park</strong> (l'un des plus grands parcs urbains des USA, 2000 hectares de forêt), <strong>Washington Park</strong> (Rose Garden = roseraie de 10 000 rosiers, Japanese Garden = l'un des plus beaux jardins japonais hors Japon selon des classements japonais), <strong>Portland Saturday Market</strong> (depuis 1974, le plus grand marché artisanal en plein air des USA), <strong>International Rose Test Garden</strong> (Portland est la \"City of Roses\"). <strong>Brasseries craft</strong> : Portland est l'une des capitales mondiales de la bière artisanale (70+ brasseries en ville, 250+ dans la métropole), citons Deschutes, Cascade, Hopworks, Breakside. <strong>Excursions</strong> : <strong>Mount Hood</strong> à 1h (3429m, volcan, ski toute l'année à Timberline Lodge), <strong>Multnomah Falls</strong> à 30 min (188m, l'une des cascades les plus connues du Pacifique nord-ouest), <strong>Columbia River Gorge</strong>, <strong>Willamette Valley</strong> (vins Pinot Noir réputés). <strong>Tester</strong> Voodoo Doughnuts (donut shop), food carts (1 des meilleures scènes street food USA, 500+ chariots), salmon, IPA. Aéroport PDX (régulièrement classé meilleur aéroport USA).",

    "saint-augustine:fr": "Saint Augustine, en Floride : 14 000 habitants, fondée par les Espagnols en 1565 (\"<em>San Agustín</em>\"), <strong>la plus ancienne ville d'origine européenne fondée et continuellement occupée des USA</strong> (42 ans avant Jamestown 1607 et 55 ans avant Plymouth 1620). Centre historique préservé, ambiance espagnole coloniale unique en Amérique du Nord. <strong>Mai est mon mois préféré</strong> (8.4/10) : 21-27°C, 28% de pluie, fin du printemps avec températures parfaites. <strong>D'avril à juin et octobre-novembre</strong> sont les meilleures saisons : 18-29°C, climat doux. <strong>De juin à septembre</strong>, comptez 24-30°C : chaleur lourde et humide, risque cyclonique réel (côte est de Floride exposée), prix hôteliers réduits. <strong>De décembre à février</strong>, comptez 11-22°C : doux pour la Floride, snowbirds américains nombreux (les Canadiens et habitants du nord-est USA fuient l'hiver). <strong>Sites majeurs</strong> : <strong>Castillo de San Marcos</strong> (la plus vieille forteresse en pierre des USA, construite 1672-1695 par les Espagnols en coquina = pierre tendre composée de coquillages, qui absorbe les boulets de canon plutôt que de se fissurer, intacte après 33 sièges, parc national), <strong>Vieille ville espagnole</strong> (Saint George Street rue piétonne, casas coloniales reconstituées, Plaza de la Constitución la plus vieille place urbaine des USA), <strong>Lightner Museum</strong> (anciennement Hôtel Alcazar 1888, art déco), <strong>Flagler College</strong> (anciennement Ponce de Leon Hotel 1888, Henry Flagler magnat du chemin de fer, architecture hispano-mauresque luxueuse, vitraux Tiffany, visite guidée), <strong>Lighthouse Museum</strong> (phare 1874, 219 marches), <strong>St. Augustine Distillery</strong>, <strong>Fountain of Youth Archaeological Park</strong> (légende de la fontaine de jouvence cherchée par Juan Ponce de León 1513, premier débarquement européen sur le continent). <strong>Plages</strong> : <strong>St. Augustine Beach</strong> et <strong>Anastasia State Park</strong> (sable doux, dunes). <strong>Excursions</strong> : <strong>Daytona Beach</strong> à 1h, <strong>Orlando</strong> à 2h (parcs Disney). <strong>Tester</strong> minorcan clam chowder (chowder épicé local), datil pepper, fried shrimp. À 1h30 de Jacksonville, 2h d'Orlando.",

    "san-antonio:fr": "San Antonio, dans le Texas : 1,5 million d'habitants (7e plus grande ville USA), fondée par les Espagnols en 1718, ville \"hispanique\" la plus historique des USA après Saint Augustine. Lieu de la <strong>bataille de l'Alamo</strong> (23 février-6 mars 1836, l'événement fondateur de l'identité texane, 187 défenseurs texans tués par les troupes mexicaines de Santa Anna). <strong>Octobre est mon mois préféré</strong> (8.7/10) : 19-29°C, 25% de pluie, températures idéales après la canicule estivale. <strong>D'avril à juin et octobre-novembre</strong> sont les meilleures saisons : 13-30°C. <strong>De juillet-août chutent à 5.8-5.9/10</strong> à cause de la chaleur extrême (25-36°C, parfois 40°C+), humidité oppressante typique du Texas. <strong>De décembre à février</strong>, comptez 6-21°C : doux pour le sud, mais variations brutales possibles (norther winds qui peuvent faire chuter de 20°C en quelques heures). <strong>Sites majeurs</strong> : <strong>The Alamo</strong> (mission franciscaine espagnole 1718 transformée en forteresse 1835, restaurée en monument depuis 1905 par les Daughters of the Republic of Texas, 2,5 millions de visiteurs/an, l'un des sites les plus chargés émotionnellement de l'histoire américaine, gratuit), <strong>San Antonio Missions National Historical Park</strong> (UNESCO 2015, 4 missions espagnoles + l'Alamo, 12 km à parcourir à vélo le long de la San Antonio River : Concepción, San José, San Juan, Espada), <strong>River Walk</strong> (\"Paseo del Río\", 24 km de promenade aménagée le long de la rivière 1 niveau sous la rue, restos, bars, gondoles, ouvert 1939-41 dans le cadre du New Deal, l'un des projets urbains les plus réussis des USA), <strong>Tower of the Americas</strong> (227m, vue panoramique), <strong>Pearl District</strong> (ex-brasserie reconvertie en zone gastronomique branchée), <strong>Mercado</strong> (Market Square, le plus grand marché mexicain hors Mexique). <strong>Fiesta San Antonio</strong> (10 jours fin avril, festival annuel depuis 1891 célébrant l'héritage hispanique). <strong>Excursions</strong> : <strong>Hill Country</strong> au nord-ouest (paysages collinaires, vins texans, lavendaraies, Fredericksburg ville fondée par Allemands), <strong>Austin</strong> à 1h30. <strong>Tester</strong> Tex-Mex (origine du genre), barbecue texan, breakfast tacos, margaritas (la \"Texan margarita\" frozen serait inventée à San Antonio en 1971).",

    "santa-fe:fr": "Santa Fe, capitale du <strong>Nouveau-Mexique</strong> (USA) : 85 000 habitants à 2200m d'altitude (la 2e capitale d'État la plus élevée des USA, après Cheyenne Wyoming), fondée par les Espagnols en 1610 (\"<em>La Villa Real de la Santa Fe de San Francisco de Asís</em>\"), <strong>la plus ancienne capitale d'État des USA</strong>. Architecture <em>Pueblo Revival</em> uniformément adobe (terre crue) imposée par règlement urbain depuis 1957, cocktail unique d'influences hispano-indien-Pueblo. <strong>Juin est mon mois préféré</strong> (9.4/10) : 14-28°C, 14% de pluie, températures idéales avant les orages d'été. <strong>De mai à octobre</strong>, c'est la haute saison touristique : 8-29°C, climat sec d'altitude. <strong>De juillet à août</strong>, comptez 15-29°C avec 23-28% de pluie : orages d'après-midi caractéristiques (\"monsoon season\" typique du sud-ouest USA, foudre dangereuse). <strong>De novembre à mars</strong>, comptez -6/12°C : froid sec d'altitude, neige possible (Santa Fe Ski Basin à 30 min, parmi les stations ski de plus haute altitude des USA, 4000m), <strong>Christmas in Santa Fe</strong> très célébré (farolitos lampions en papier sur les toits adobe, signature visuelle de la ville). <strong>Sites majeurs</strong> : <strong>Plaza de Santa Fe</strong> (place centrale espagnole 1610, marché aux vendeurs amérindiens chaque jour sous le Palace of the Governors), <strong>Palace of the Governors</strong> (1610, le plus vieux bâtiment public continuellement utilisé des USA), <strong>Cathédrale Saint-François-d'Assise</strong> (1869, French Romanesque dans un sea d'adobe), <strong>Loretto Chapel</strong> (escalier en spirale \"miraculeux\" sans support central, 1878), <strong>Canyon Road</strong> (1 km de galeries d'art, 100+ galeries, l'une des plus fortes concentrations d'art aux USA), <strong>Santa Fe Opera</strong> (juillet-août, salle en plein air design Polshek 1998, l'un des opéras les plus prestigieux des USA), <strong>Georgia O'Keeffe Museum</strong> (peintre signature du Sud-Ouest américain qui a vécu et peint à Abiquiu). <strong>Excursions</strong> : <strong>Taos</strong> à 1h30 (Pueblo Taos UNESCO, vivable depuis 1000 ans, ski Taos), <strong>Bandelier National Monument</strong> à 1h (habitations falaises Pueblo XIIe-XVe), <strong>Carlsbad Caverns</strong> à 5h (UNESCO, grottes), <strong>White Sands</strong> à 4h (dunes de gypse blanc). <strong>Indian Market</strong> de Santa Fe (3e weekend d'août, le plus grand marché d'art amérindien au monde, 1000 artistes). <strong>Tester</strong> green chile (sauce signature néo-mexicaine, sur tout - red ou green selon préférence, Christmas = les 2), enchiladas, posole, sopaipillas, vins du Nouveau-Mexique.",

    # === Argentine/Chili/Brésil/Uruguay/Colombie tier 2 (8) ===
    "rosario:fr": "Rosario, 3e ville d'<strong>Argentine</strong> : 1,3 million d'habitants sur le <strong>Río Paraná</strong> dans la province de Santa Fe à 300 km au nord-ouest de Buenos Aires. Ville portuaire industrielle souvent négligée par les touristes mais riche d'histoire : <strong>ville natale de Che Guevara</strong> (né le 14 juin 1928, maison transformée en mémorial discret) et <strong>Lionel Messi</strong> (né le 24 juin 1987, club d'enfance Newell's Old Boys = sa première équipe). Climat <strong>subtropical humide</strong> de la Pampa argentine. <strong>Novembre est mon mois préféré</strong> (9.1/10) : 16-27°C, 23% de pluie, c'est le printemps austral, tout fleurit. <strong>De décembre à mars</strong>, c'est l'été austral : 18-31°C, parfois caniculaire (37°C+), prix hôteliers réduits car les Argentins partent à la côte (Mar del Plata). <strong>D'avril à mai et septembre-octobre</strong> sont les meilleures saisons : 10-27°C. <strong>De juin à août</strong>, c'est l'hiver austral : 7-18°C, 14-20% de pluie, doux pour l'hémisphère sud. <strong>Sites majeurs</strong> : <strong>Monumento Histórico Nacional a la Bandera</strong> (Monument National au Drapeau, 1957, le drapeau argentin a été créé ici en 1812 par Manuel Belgrano face au Paraná, ascenseur jusqu'au sommet pour panorama), <strong>Costanera</strong> (promenade le long du Paraná, plages fluviales La Florida en été), <strong>Parque de la Independencia</strong> (le plus grand parc urbain argentin), <strong>Catedral Basílica</strong>, <strong>Plaza 25 de Mayo</strong> (place principale), <strong>Pasaje Juramento</strong> (passage piéton XIXe), <strong>Museo Castagnino + Macro</strong> (art moderne dans silo à grains reconverti coloré), <strong>Estadio Marcelo Bielsa</strong> (Newell's Old Boys, club d'enfance de Messi). <strong>Excursions</strong> : <strong>Iles du Paraná</strong> en bateau (delta avec villages de pêcheurs), <strong>Buenos Aires</strong> à 4h en bus, <strong>Córdoba</strong> à 5h. <strong>Tester</strong> asado (grillade argentine), choripán, mate, fernet con coca (boisson nationale), helado (glace italienne argentine), milanesa.",

    "valparaiso:fr": "Valparaíso, ville portuaire du Chili : 300 000 habitants à 110 km à l'ouest de Santiago sur le <strong>Pacifique</strong>, classée UNESCO 2003 pour son ensemble historique unique en Amérique latine. Ville construite sur 42 collines (\"<em>cerros</em>\") avec maisons en bois et tôle ondulée colorées, accessibles par <strong>15 funiculaires</strong> historiques (\"<em>ascensores</em>\") datant XIXe-XXe (8 encore en service, 7 en restauration). Capitale culturelle du Chili (poètes Pablo Neruda et Vicente Huidobro y ont vécu). <strong>Janvier est mon mois préféré</strong> (8.8/10) : 14-20°C, 2% de pluie, c'est l'été austral, ciel dégagé constant. <strong>De novembre à mars</strong>, c'est la haute saison touristique : 11-20°C, climat méditerranéen idéal. <strong>De juin à août</strong>, c'est l'hiver austral : 9-14°C, 16-22% de pluie, doux mais ciel souvent gris. <strong>Sites majeurs</strong> : <strong>Cerro Concepción et Cerro Alegre</strong> (les 2 collines les plus touristiques, ruelles pavées, street art exceptionnel - Valparaíso est l'une des capitales mondiales du street art, des fresques murales partout), <strong>La Sebastiana</strong> (maison-musée de Pablo Neruda, vue panoramique sur la baie, l'une des 3 maisons du poète après <strong>Isla Negra</strong> et <strong>La Chascona à Santiago</strong>), <strong>Ascensor Concepción</strong> (1883, le plus vieux funiculaire encore en service du Chili), <strong>Plaza Sotomayor</strong> (place principale en bord de port avec le Monumento a los Héroes de Iquique), <strong>Mercado Cardonal</strong> (marché central pittoresque), <strong>Museo de Bellas Artes</strong> (Palacio Baburizza), <strong>Plaza Aníbal Pinto</strong>, <strong>Reloj Turri</strong> (horloge anglaise), <strong>Iglesia Anglicana San Pablo</strong>. <strong>Festivals</strong> : <strong>Año Nuevo</strong> (le 31 décembre, l'un des plus grands feux d'artifice au monde sur la baie, 1 million de spectateurs sur les collines). <strong>Viña del Mar</strong> à 10 min en métro (\"<em>la Ciudad Jardín</em>\", la \"vraie\" station balnéaire chic du Chili, plages, casino, festival de chansons en février qui réunit toute l'Amérique latine). <strong>Excursions</strong> : <strong>Isla Negra</strong> à 1h (maison de Pablo Neruda en bord de Pacifique), <strong>Santiago</strong> à 1h30. <strong>Tester</strong> chorrillana (frites avec viande/oignon/oeuf), pichanga (street food), pastel de jaiba (gâteau de crabe), vins du Maipo et Casablanca.",

    "porto-alegre:fr": "Porto Alegre, capitale du <strong>Rio Grande do Sul</strong> dans le sud du Brésil : 1,4 million d'habitants au confluent de 5 rivières formant le Lago Guaíba. Climat <strong>subtropical</strong> contrairement au Brésil tropical, ambiance \"<em>gaúcho</em>\" (cowboy sud-américain) qui rappelle l'Argentine ou l'Uruguay voisins (le mate est consommé au quotidien comme à Buenos Aires, traditions équestres). <strong>Décembre est mon mois préféré</strong> (8.7/10) : 19-29°C, 34% de pluie, c'est le début de l'été austral. <strong>De novembre à mars</strong>, c'est l'été austral : 17-30°C, 32-41% de pluie, parfois caniculaire (38°C+ avec humidité oppressante). <strong>D'avril à mai et septembre-octobre</strong> sont les meilleures saisons : 14-24°C. <strong>De juin à août</strong>, c'est l'hiver austral : 10-21°C, doux mais ciel souvent gris. <strong>Sites majeurs</strong> : <strong>Mercado Público</strong> (1869, marché central XIXe en architecture portugaise), <strong>Casa de Cultura Mario Quintana</strong> (centre culturel ex-Hôtel Majestic Art Nouveau), <strong>Praça da Matriz</strong> (place historique avec Catedral Metropolitana), <strong>Parque Farroupilha</strong> (\"Parque da Redenção\", parc central de 37 hectares, marché artisanal le dimanche), <strong>Usina do Gasômetro</strong> (ex-centrale à gaz reconvertie en centre culturel, vue signature sur le coucher du soleil sur le Lago Guaíba - les Gaúchos disent que Porto Alegre a \"le plus beau coucher du soleil au monde\"), <strong>Mémorial du Rio Grande do Sul</strong>, <strong>Jardim Botânico</strong>. <strong>Excursions</strong> : <strong>Gramado</strong> à 2h (ville bavaroise dans la Serra Gaúcha, ambiance Noël toute l'année avec marché Natal Luz, tourisme intérieur brésilien massif), <strong>Canela</strong> (Cascata do Caracol), <strong>Bento Gonçalves</strong> et <strong>Vale dos Vinhedos</strong> (région viticole brésilienne, immigration italienne XIXe), <strong>Côte Atlantique</strong> à 2h (Torres, Capão da Canoa). <strong>Tester</strong> churrasco (le vrai churrasco gaúcho, pas brésilien tropical : viande au sel sur épée, tradition cowboy), chimarrão (mate gaúcho), arroz carreteiro, dulce de leche, vins de Vale dos Vinhedos.",

    "natal-bresil:fr": "Natal, capitale du <strong>Rio Grande do Norte</strong> dans le <strong>Nordeste</strong> du Brésil : 900 000 habitants sur la côte atlantique au point le plus proche d'Afrique des Amériques. <strong>La ville la plus ensoleillée du Brésil</strong> (300+ jours par an), surnommée \"Cidade do Sol\". Réputée pour ses dunes mobiles spectaculaires (Genipabu) et sa plage urbaine Ponta Negra signature. <strong>Septembre-octobre sont mes mois préférés</strong> (8.2/10) : 23-29°C, 34-36% de pluie, c'est la saison la plus sèche. <strong>De septembre à février</strong>, c'est la haute saison touristique : 23-30°C, 32-49% de pluie, brises de l'Atlantique constantes. <strong>De mars à juin</strong>, c'est la saison des pluies (\"<em>inverno do Nordeste</em>\" ironiquement appelé hiver bien que températures stables 23-29°C) : 65-75% de précipitations, mais averses brèves d'après-midi typiques. <strong>Sites majeurs</strong> : <strong>Praia de Ponta Negra</strong> (plage urbaine signature avec <strong>Morro do Careca</strong> = dune-falaise de sable de 120m de hauteur tombant directement sur la plage, signature visuelle de Natal), <strong>Forte dos Reis Magos</strong> (XVIe portugais en forme d'étoile à 5 pointes, à l'embouchure du Rio Potengi, fondation officielle de Natal le 25 décembre 1599), <strong>Centro Histórico</strong> (Cidade Alta, architecture coloniale portugaise XVIIe-XVIIIe : Catedral Velha, Igreja do Bom Jesus das Dores, Palácio Felipe Camarão), <strong>Parque das Dunas</strong> (1170 hectares de dunes mobiles dans la ville même, sentiers protégés). <strong>Excursions plages et dunes</strong> (l'attraction majeure de Natal) : <strong>Genipabu</strong> à 30 min au nord (les fameuses dunes mobiles du Brésil = paysage iconique pour publicités, <em>buggy ride</em> avec bugueiros locaux, sandboarding, lac d'eau douce du Pititinga, dromadaires en bord de mer ramenés des Canaries), <strong>Praia da Pipa</strong> à 1h30 au sud (l'une des plus belles plages du Brésil selon de nombreux classements, falaises rouges, dauphins, ambiance bohème), <strong>São Miguel do Gostoso</strong>, <strong>Galinhos</strong>. <strong>Tester</strong> moqueca de camarão, carne de sol, tapioca avec coco/banane/fromage coalho, água de coco. Vol direct depuis Lisbonne, ou via São Paulo/Recife.",

    "manaus:fr": "Manaus, capitale de l'<strong>Amazonas</strong> au cœur de l'Amazonie brésilienne : 2,2 millions d'habitants au confluent du <strong>Rio Negro</strong> et du <strong>Rio Solimões</strong> (les 2 fleuves se rejoignent pour former l'Amazone proprement dit, le \"<strong>Encontro das Águas</strong>\" = phénomène spectaculaire des 2 fleuves coulant côte à côte sans se mélanger sur 6 km en raison de différences de température/densité/PH). Ville portuaire surgi de la jungle au XIXe siècle pendant le boom du caoutchouc (1879-1912), capitale mondiale du caoutchouc et l'une des villes les plus riches au monde à cette époque (avant l'effondrement causé par la culture asiatique du caoutchouc). <strong>Juin est mon mois préféré</strong> (6.9/10) : 24-30°C, 62% de pluie. Manaus ne dépasse jamais 6.9/10 (climat équatorial pluvieux constant). <strong>De juin à novembre</strong>, c'est la saison \"sèche\" (relative) : 24-32°C, 31-64% de pluie, basses eaux de l'Amazone (terres exondées, plages fluviales, chemins de jungle accessibles). <strong>De décembre à mai</strong>, c'est la saison des pluies : 24-30°C, 76-88% de précipitations, hautes eaux qui montent à +12m, jungle inondée (\"<em>igapó</em>\"), navigation possible dans la canopée. <strong>Sites majeurs Manaus</strong> : <strong>Teatro Amazonas</strong> (1896, opéra italien Belle Époque construit en pleine jungle pour le boom du caoutchouc, dôme couvert de 36 000 tuiles aux couleurs du drapeau brésilien fabriquées en France, scène ouverte sur la place avec phonola = parquet en bois sur amortisseurs en caoutchouc local pour ne pas perturber les performances, festival d'opéra annuel en mai), <strong>Mercado Adolpho Lisboa</strong> (1882, copie des Halles de Paris en miniature, structure en fer, marché aux poissons amazoniens géants pirarucu/tambaqui), <strong>Encontro das Águas</strong> (excursion en bateau 5h, le must absolu de Manaus). <strong>Excursions Amazonie</strong> : Manaus est la base pour <strong>séjours en jungle</strong> (lodges 3-5 jours dans la canopée, observation faune toucans/aras/singes/paresseux/caïmans/dauphins roses/anacondas, prix 200-1500€/nuit selon standing, lodges de référence : Anavilhanas Jungle Lodge dans archipel fluvial UNESCO, Juma Amazon Lodge). <strong>Important</strong> : Manaus n'est accessible que par avion ou par bateau (4 jours depuis Belém en cargo passager, expérience unique du voyage amazonien classique). Pas de routes terrestres vers le reste du Brésil. <strong>Tester</strong> tambaqui (poisson amazonien), tucumã (palmier amazonien), açaí natural (le vrai açaí, base de cassis amer, pas le smoothie sucré occidental), guaraná Antártica (soft drink local).",

    "montevideo:fr": "Montevideo, capitale de l'<strong>Uruguay</strong> : 1,3 million d'habitants (40% de la population du pays, qui en compte 3,4 millions sur 176 000 km² - l'un des pays les moins peuplés d'Amérique du Sud), sur le <strong>Río de la Plata</strong> face à Buenos Aires (à 200 km en hydrofoil 2h15). L'Uruguay = la \"Suisse de l'Amérique latine\" (stable politiquement, classes moyennes développées, sécurité, légalisations progressistes : le 1er pays à légaliser la marijuana 2013, mariage gay 2013, divorce 1907). <strong>Janvier est mon mois préféré</strong> (9.0/10) : 20-26°C, 27% de pluie, c'est l'été austral, températures parfaites grâce aux brises atlantiques. <strong>De novembre à mars</strong>, c'est la haute saison : 16-26°C. <strong>D'avril à mai et septembre-octobre</strong> sont les transitions : 11-22°C. <strong>De juin à août</strong>, c'est l'hiver austral : 9-15°C, 25-29% de pluie, doux mais venté. <strong>Sites majeurs</strong> : <strong>Ciudad Vieja</strong> (vieille ville XVIIIe-XIXe, dédale de ruelles, Puerta de la Ciudadela ancienne porte fortifiée, Mercado del Puerto = marché central reconverti en parrillas restos asado), <strong>Plaza Independencia</strong> (place principale qui sépare ville haute coloniale et ville basse moderne, statue de José Artigas héros national + son mausolée souterrain, Palacio Salvo 1928 = ex-plus haut bâtiment d'Amérique du Sud 100m), <strong>Teatro Solís</strong> (1856, salle d'opéra historique), <strong>Catedral Metropolitana</strong>, <strong>Rambla de Montevideo</strong> (22 km de promenade le long du Río de la Plata, l'une des plus longues promenades urbaines en bord de mer au monde), <strong>Estadio Centenario</strong> (1930, lieu de la 1ère Coupe du Monde de football remportée par l'Uruguay sur sa pelouse, musée du football), <strong>Pocitos</strong> et <strong>Carrasco</strong> (quartiers résidentiels chics avec plages urbaines fluviales). <strong>Excursions</strong> : <strong>Punta del Este</strong> à 2h (la grande station balnéaire chic latino-américaine, voir avis dédié), <strong>Colonia del Sacramento</strong> à 2h (UNESCO, ville coloniale portugaise XVIIe), <strong>Cabo Polonio</strong> à 4h (village hors-grille électrique en bord d'océan, lions de mer). <strong>Tester</strong> asado (le vrai asado uruguayen, de longues heures lentes), chivito (sandwich emblématique uruguayen avec steak/jambon/œuf/bacon/laitue/tomate/mayonnaise), dulce de leche (origine controversée Uruguay/Argentine), mate (le mate national uruguayen plus que partout, les Uruguayens marchent partout avec leur thermos d'eau chaude et calabaza), vins Tannat (cépage signature uruguayen).",

    "punta-del-este:fr": "Punta del Este, station balnéaire chic d'<strong>Uruguay</strong> : 10 000 habitants permanents (population x10-x20 en haute saison de fin décembre à mi-février). \"<strong>Saint-Tropez de l'Amérique du Sud</strong>\", repaire estival des élites argentines, brésiliennes et uruguayennes (les Argentins fortunés y ont leurs résidences secondaires, c'est l'une des destinations balnéaires les plus chères d'Amérique latine). <strong>Janvier est mon mois préféré</strong> (9.0/10) : 19-26°C, 25% de pluie, c'est le pic de l'été austral. <strong>De décembre à février</strong>, c'est la pleine haute saison : prix hôteliers x5-x8 (Conrad Hotel & Casino 800-3000$/nuit), restos complets, plages bondées. <strong>De mars à mai</strong>, c'est l'<strong>arrière-saison</strong> idéale (mer encore chaude, prix divisés par 3, foule disparue, c'est l'un des meilleurs moments). <strong>De juin à octobre</strong>, c'est l'hiver austral : 8-21°C, beaucoup d'établissements ferment, ville quasi-déserte (5000 habitants permanents sur place). <strong>Sites majeurs</strong> : <strong>La Mano de Punta del Este</strong> (\"Los Dedos\", la sculpture la plus connue d'Uruguay, 5 doigts géants émergeant du sable de Playa Brava, créée 1982 par Mario Irarrázabal), <strong>Casapueblo</strong> (à Punta Ballena 15 km, hôtel-musée-résidence créé par l'artiste Carlos Páez Vilaró 1958, architecture méditerranéenne en chaux blanche cubiste construite intuitivement sans plans, rituel \"<em>Ceremonia del Sol</em>\" = lecture poétique au coucher du soleil sur la terrasse), <strong>Phare de Punta del Este</strong> (1860, sur la pointe entre les 2 océans \"Playa Brava\" Atlantique avec vagues fortes et \"Playa Mansa\" Río de la Plata calme), <strong>Casa Pueblo</strong>. <strong>Plages</strong> : <strong>La Brava</strong> (côté océan Atlantique, vagues, surfeurs), <strong>La Mansa</strong> (côté Río de la Plata, calme, familles), <strong>José Ignacio</strong> à 30 min au nord (le \"hidden gem\" plus chic et discret, fréquenté par Shakira et autres célébrités). <strong>Vie nocturne</strong> : Conrad Hotel & Casino, Ovo Beach Lounge. <strong>Excursions</strong> : <strong>Isla de Lobos</strong> en bateau (île aux 250 000 lions de mer), <strong>La Barra</strong> village hippie chic, <strong>Punta Ballena</strong>. <strong>Tester</strong> chivito, asado, vins Tannat, dulce de leche, calamares fritos.",

    "providencia:fr": "Providencia, île colombienne dans la <strong>mer des Caraïbes</strong> à 800 km au nord-ouest de la Colombie continentale et 200 km à l'est du Nicaragua : 5000 habitants sur 17 km², l'une des destinations les plus authentiques et préservées des Caraïbes. Île voisine de la plus connue <strong>San Andrés</strong> (40 min en bateau ou 20 min en avion). <strong>Avril est mon mois préféré</strong> (8.6/10) : 24-25°C, 19% de pluie, c'est la saison sèche idéale. <strong>De janvier à avril</strong>, c'est la saison sèche : 24-25°C, 22-45% de pluie, mer turquoise, tradewinds constants. <strong>De juin à novembre</strong>, c'est la saison cyclonique : 49-83% de précipitations, mais peu de typhons en réalité (l'île est un peu hors trajectoire principale). <strong>L'ouragan Iota en novembre 2020</strong> a dévasté Providencia (98% des bâtiments endommagés ou détruits), reconstruction en cours depuis 2021. <strong>Sites majeurs</strong> : <strong>Plage Manchineel Bay</strong> (Bahía Manzanillo, l'une des plus belles plages de Colombie selon de nombreux classements, sable blanc, eau turquoise, peu fréquentée), <strong>Plage de South West Bay</strong> (sud-ouest), <strong>Crab Cay</strong> (\"Cayo Cangrejo\", îlot relié par 100m de mer turquoise à la nage, sortie en bateau classique, snorkeling), <strong>Morgan's Head</strong> (formation rocheuse en forme de tête du pirate Henry Morgan qui aurait utilisé Providencia comme base au XVIIe), <strong>The Peak</strong> (point culminant 360m, randonnée 1h30, panorama 360° sur l'île et la mer), <strong>Old Providence McBean Lagoon National Park</strong> (mangroves, observation oiseaux). <strong>Culture</strong> : île anglophone (descendants de pirates britanniques et esclaves d'origine africaine, créole anglais parlé localement même si l'espagnol est officiel depuis l'annexion à la Colombie 1822), ambiance Caraïbes plus que latino-américaine. <strong>Plongée</strong> : la <strong>3e plus grande barrière de corail du monde</strong> entoure Providencia (UNESCO Réserve de Biosphère Seaflower 2000), 30 sites de plongée, requins-marteaux possibles. <strong>Tester</strong> rondón (plat traditionnel caribéen mijoté avec poisson/coco/banane plantain), pâté de fruits de mer, langouste grillée, jonny cake (pain traditionnel). <strong>Logistique</strong> : vol Bogotá-San Andrés direct (3h) puis vol San Andrés-Providencia (20 min, petit avion 19 places), pas de vol direct depuis Europe.",

    # === Caraïbes/Antilles (1) ===
    "saint-vincent:fr": "Saint-Vincent, île principale de l'État indépendant <strong>Saint-Vincent-et-les-Grenadines</strong> (membre du Commonwealth) : 100 000 habitants (110 000 dans tout le pays incluant les Grenadines), île volcanique active (<strong>La Soufrière</strong> 1234m a éclaté en avril 2021 avec évacuation de 20 000 personnes, dernière éruption majeure 1979). Capitale Kingstown. Plus authentique et moins touristique que Sainte-Lucie ou Barbade voisines. <strong>Avril est mon mois préféré</strong> (8.3/10) : 25-28°C, 36% de pluie, fin de la saison sèche. <strong>De décembre à avril</strong>, c'est la haute saison touristique : 24-28°C, 36-44% de pluie, mer à 26°C, tradewinds constants. <strong>De juin à novembre</strong>, c'est la saison cyclonique : 61-72% de précipitations, risque ouragans (Saint-Vincent est dans la trajectoire classique des cyclones). <strong>Sites majeurs Saint-Vincent</strong> : <strong>La Soufrière</strong> (1234m, randonnée 6h aller-retour, volcan toujours actif, dernière éruption avril 2021, accès parfois fermé pour activité sismique), <strong>Cascade de Dark View</strong> et <strong>Trinity Falls</strong>, <strong>Botanical Gardens of Kingstown</strong> (le plus vieux jardin botanique des Amériques, fondé 1765, l'arbre à pain originel apporté par Captain Bligh \"Mutiny on the Bounty\" 1793 est encore vivant), <strong>Fort Charlotte</strong> (XVIIIe britannique, panorama sur Kingstown), <strong>Owia Salt Pond</strong> (piscine naturelle marine côté Atlantique). <strong>Mais surtout les Grenadines</strong> = l'attraction majeure : 32 îles et îlots au sud, paradis caribéen pour navigation à voile : <strong>Bequia</strong> (la plus grande des Grenadines, 5000 habitants, ambiance authentique, Princess Margaret Beach), <strong>Mustique</strong> (île privée luxe, Mick Jagger et Bryan Adams y ont leurs villas, pub Basil's Bar mythique), <strong>Mayreau</strong> (la plus petite des Grenadines, plage Salt Whistle Bay paradisiaque), <strong>Tobago Cays</strong> (5 îlots inhabités au cœur d'un récif corallien protégé, eau turquoise, snorkeling avec tortues vertes, photo signature de carte postale caribéenne). <strong>Pirates des Caraïbes</strong> : tournage en 2003 et 2006 (Wallilabou Bay = plage du film). <strong>Tester</strong> arrowroot (Saint-Vincent = leader mondial), callaloo soup, breadfruit, rhum Sunset Very Strong (84,5% le plus fort du monde, vendu uniquement aux résidents). <strong>Logistique</strong> : Saint-Vincent à 1h30 en avion de Barbade (souvent escale), aéroport international Argyle ouvert 2017.",

    # === Mexique (1) ===
    "puerto-escondido:fr": "Puerto Escondido (\"Le Port Caché\"), village de pêcheurs sur la côte Pacifique d'<strong>Oaxaca</strong> au Mexique : 50 000 habitants, célèbre pour sa <strong>Playa Zicatela</strong> qui produit le \"<strong>Mexican Pipeline</strong>\" = l'une des plus grosses vagues du monde (jusqu'à 6m+, considérée parmi les 10 plus grosses vagues mondiales avec Pipeline Hawaii, Teahupoo Tahiti, Nazaré Portugal). Surfers du monde entier viennent de mai à septembre pour les compétitions WSL. Ambiance bohème, surfers, backpackers, beaucoup moins développé que Cancún ou Tulum. <strong>Janvier-février-mars-avril sont mes mois préférés</strong> (6.9/10) : 21-32°C, 2-4% de pluie, c'est la saison sèche. Puerto Escondido ne dépasse jamais 6.9/10 (climat tropical chaud + saison cyclonique pacifique). <strong>De novembre à avril</strong>, c'est la haute saison touristique : 21-32°C, climat sec, mer plus calme (mais Zicatela reste vague). <strong>De mai à octobre</strong>, c'est la saison des pluies : 21-36% à 78% de précipitations, mais aussi <strong>saison des grosses vagues sur Zicatela</strong> (paradoxe : la haute saison surfers correspond à la basse saison touristique grand public). Saison cyclonique pacifique de juin à novembre. <strong>Plages</strong> : <strong>Zicatela</strong> (la grande, longue, vagues énormes, danger pour baigneurs non-surfers), <strong>Carrizalillo</strong> (petite crique de cliff dive, escalier 167 marches, eau calme idéale baignade et débutants surf, photogénique), <strong>Manzanillo</strong> (eau calme, snorkeling), <strong>Bacocho</strong> (calme, pélicans), <strong>Puerto Angelito</strong>. <strong>Activités</strong> : <strong>surf</strong> (école pour débutants à Carrizalillo ou La Punta Zicatela, leçon 30€), <strong>turtle release</strong> (libération de bébés tortues le soir, Vivemar association de conservation), <strong>bioluminescent lagoon</strong> à Manialtepec à 30 min (lagune phosphorescente la nuit, à voir nouvelle lune), <strong>swimming with dolphins</strong>. <strong>Adventure tours</strong> : <strong>Mazunte</strong> à 1h (ex-village de pêcheurs de tortues reconverti en village hippie New Age, plage Mermejita), <strong>San Agustinillo</strong> (entre Mazunte et Zipolite), <strong>Zipolite</strong> (plage nudiste mexicaine, ambiance hippie depuis les années 70). <strong>Tester</strong> mole oaxaqueño (la sauce signature d'Oaxaca, 7 variantes), tlayuda, mezcal artisanal d'Oaxaca, ceviche, fish tacos. <strong>Logistique</strong> : vol direct depuis Mexico City (1h15), vol via Oaxaca city, ou bus 6h depuis Oaxaca. Vol depuis Europe via Mexico City obligatoire.",

    # === Equateur (1) ===
    "cuenca-equateur:fr": "Cuenca, 3e ville d'<strong>Équateur</strong> dans la sierra andine : 330 000 habitants à 2560m d'altitude, classée UNESCO 1999 pour son centre historique colonial espagnol bien préservé. Considérée comme la ville la plus européenne d'Équateur (plus que Quito), réputée pour sa qualité de vie (l'une des destinations préférées des retraités américains et canadiens en Amérique latine, communauté expat de 5000+ personnes). <strong>Août est mon mois préféré</strong> (7.3/10) : 8-19°C, 66% de pluie. Cuenca a un climat constant toute l'année (températures stables 8-20°C grâce à l'altitude, peu de variations saisonnières), variations principales sur les précipitations. <strong>D'août à janvier</strong>, c'est la saison \"sèche\" relative : 8-20°C, 66-83% de pluie, soleil le matin/orages d'après-midi typiques de la sierra andine équatoriale. <strong>De février à juillet</strong>, c'est la saison plus pluvieuse : 8-19°C, 73-93% de précipitations. <strong>Sites majeurs</strong> : <strong>Centro Histórico</strong> (UNESCO, dédale de ruelles pavées, architecture coloniale espagnole XVIe-XVIIIe), <strong>Cathédrale Nouvelle</strong> (\"<em>Catedral Nueva</em>\", Inmaculada Concepción 1885-1967, dômes bleu et blanc signatures de Cuenca, vue panoramique depuis les terrasses), <strong>Cathédrale Ancienne</strong> (1557, devenue musée), <strong>Plaza Calderón</strong> (place principale entre les 2 cathédrales), <strong>Mercado 10 de Agosto</strong> (marché central, étage du haut = food court avec hornado spécialité de Cuenca), <strong>Río Tomebamba</strong> (rivière qui traverse la ville, sentier El Barranco le long avec maisons colorées suspendues sur la falaise), <strong>Barrio Las Herrerías</strong> (quartier des forgerons), <strong>Museo del Banco Central Pumapungo</strong> (ruines Inca-Cañari, jardin ethnobotanique), <strong>Museo de las Conceptas</strong>. <strong>Industrie du Panama Hat</strong> : Cuenca est en réalité la <strong>vraie capitale mondiale du Panama Hat</strong> (le célèbre chapeau en paille de toquilla, malgré son nom est fabriqué en Équateur depuis le XVIe siècle, exporté via le Canal de Panama au XIXe = origine du nom trompeur), visites des fabriques Homero Ortega et K. Dorfzaun. <strong>Excursions</strong> : <strong>Parc National Cajas</strong> à 30 min (paramo andin, 270 lacs glaciaires, randonnée altitude 3000-4500m, lamas), <strong>Ingapirca</strong> à 2h (les plus importantes ruines Inca d'Équateur, mais modeste comparé au Pérou), <strong>Cordillera Real</strong>. <strong>Tester</strong> cuy (cochon d'Inde rôti, plat traditionnel andin), hornado (porc rôti à la Cuenca, le plus connu d'Équateur), locro de papas (soupe de pommes de terre), morocho (boisson de maïs blanc).",

    # === Bolivie (1) ===
    "sucre:fr": "Sucre, capitale constitutionnelle de la <strong>Bolivie</strong> (la capitale administrative étant La Paz, dualisme constitutionnel unique au monde) : 280 000 habitants à 2810m d'altitude. Classée UNESCO 1991 pour son centre historique colonial blanc immaculé (\"<em>la Ciudad Blanca</em>\", règlement urbain qui impose le badigeon blanc à toutes les maisons depuis le XIXe siècle, signature visuelle). Plus accessible et moins haut que La Paz (3650m), souvent recommandée comme premier arrêt en Bolivie pour s'acclimater à l'altitude. <strong>Août est mon mois préféré</strong> (8.4/10) : 6-21°C, 12% de pluie, c'est la saison sèche, ciel bleu intense permanent. <strong>De juin à octobre</strong>, c'est la saison sèche : 6-22°C, 7-22% de pluie, températures stables grâce à l'altitude (été aux Andes paradoxalement = saison sèche, pas chaude). <strong>De décembre à mars</strong>, c'est la saison des pluies : 10-20°C, 49-77% de pluie, ciel souvent couvert. <strong>Climat constant grâce à l'altitude équatoriale</strong> : températures stables 6-22°C toute l'année, variations principales sur les précipitations. <strong>Sites majeurs</strong> : <strong>Plaza 25 de Mayo</strong> (place principale, pavillon central, palais du Gouvernement de Chuquisaca), <strong>Casa de la Libertad</strong> (musée où l'indépendance bolivienne a été déclarée le 6 août 1825, signée par Simón Bolívar), <strong>Catedral Metropolitana</strong> (mélange Renaissance, baroque et néoclassique XVIe-XIXe), <strong>Iglesia y Convento de San Felipe Neri</strong> (vue panoramique depuis le toit), <strong>Museo de la Recoleta</strong> (couvent franciscain XVIIe converti en musée, vue depuis la place de la Recoleta), <strong>Mercado Central</strong> (marché traditionnel, jus de fruits frais, food stalls), <strong>Cementerio General</strong> (l'un des plus beaux cimetières d'Amérique latine, mausolées luxueux), <strong>Tarabuco</strong> à 2h le dimanche (marché ethnique Yampara, l'un des plus colorés d'Amérique du Sud). <strong>Excursions</strong> : <strong>Parque Cretácico</strong> à 5 km (\"Cal Orck'o\", la plus grande concentration de traces de dinosaures au monde, 12 000 traces de 8 espèces sur 1,5 km de paroi calcaire verticale révélée par érosion d'une carrière de ciment), <strong>Potosí</strong> à 3h (UNESCO, ancien centre d'argent colonial, mines du <em>Cerro Rico</em> visite poignante des mineurs en activité), <strong>Salar d'Uyuni</strong> à 8h (le plus grand désert de sel au monde, l'une des destinations bolivienne signature, tour 3 jours classique Uyuni-San Pedro de Atacama). <strong>Tester</strong> salteñas (chausson de viande sucré-épicé), api con pastel (boisson maïs violet chaude + chausson), chuño (pomme de terre déshydratée andine), llajwa (sauce piquante traditionnelle).",

    # === Paraguay (1) ===
    "asuncion:fr": "Asunción, capitale du <strong>Paraguay</strong> : 525 000 habitants (2 millions en aire urbaine) sur la rive est du <strong>Río Paraguay</strong> face à l'Argentine. Fondée en 1537 par les Espagnols, l'une des plus anciennes capitales d'Amérique du Sud (\"Madre de Ciudades\" = \"Mère des Villes\" car d'autres villes comme Buenos Aires ont été fondées par des expéditions parties d'Asunción). Capitale très peu touristique d'un des pays les moins visités d'Amérique du Sud (mais aussi l'un des moins chers, idéal pour budget restreint). <strong>Septembre est mon mois préféré</strong> (8.9/10) : 17-28°C, 25% de pluie, c'est le printemps austral. <strong>D'avril à septembre</strong>, c'est l'hiver austral : 14-29°C, 18-38% de pluie, climat doux supportable. <strong>De novembre à mars</strong>, c'est l'été austral chaud : 21-33°C avec 36-40% de pluie : chaleur extrême (parfois 42°C+ avec humidité écrasante typique du Chaco paraguayen), prix hôteliers réduits. <strong>Sites majeurs</strong> : <strong>Palacio de los López</strong> (palais présidentiel sur la Plaza Constitución, architecture européenne XIXe construit pour le président Francisco Solano López qui n'a jamais pu y vivre - mort dans la guerre désastreuse de la Triple Alliance 1864-1870 qui a détruit le Paraguay), <strong>Catedral Metropolitana</strong> (XIXe), <strong>Panteón Nacional de los Héroes</strong> (mausolée des héros nationaux dont le président Solano López et Carlos Antonio López), <strong>Casa de la Independencia</strong> (où l'indépendance du Paraguay a été déclarée le 14 mai 1811), <strong>Museo del Barro</strong> (le meilleur musée d'art populaire et indigène du Paraguay, magnifique collection de textiles ñandutí, masques et art guaraní contemporain), <strong>Manzana de la Rivera</strong> (quartier rénové autour de la place avec maisons coloniales), <strong>Mercado 4</strong> (marché chaotique gigantesque, ambiance authentique de l'Amérique du Sud non-touristique). <strong>Costanera</strong> (promenade le long du Río Paraguay, plages urbaines fluviales). <strong>Excursions</strong> : <strong>Mission jésuite de Trinidad</strong> et <strong>Jesús de Tavarangue</strong> à 4h (UNESCO, ruines de réductions jésuites XVIIe-XVIIIe, 30 ruines au total dans le Sud paraguayen et nord argentin <em>The Mission</em> film de Roland Joffé 1986), <strong>Pantanal paraguayen</strong> au nord. <strong>Tester</strong> chipa (pain au manioc et fromage, le pain national), sopa paraguaya (paradoxalement \"<em>la seule soupe solide au monde</em>\" car c'est en réalité un pain de maïs salé), tereré (mate froid à la place chaud comme en Argentine/Uruguay, parfait pour la chaleur du Paraguay), asado, chipa guazú."
}

with open(PATH, encoding='utf-8') as f:
    data_existing = json.load(f)

before = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

data_existing['_version'] = '2.7'
data_existing['_updated'] = '2026-04-28'

for k, v in AVIS_BATCH16_FR.items():
    data_existing[k] = v

after = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data_existing, f, ensure_ascii=False, indent=2)

print(f"Avis FR avant : {before}")
print(f"Avis FR après : {after}")
print(f"Nouveaux : {after - before}")

# Audit immédiat
import re
patterns_check = [
    ('em-dash', r'—'), ('guillemets', r'[«»]'),
    ('attendez-vous', r'attendez-vous à'),
    ('parfait', r'\bparfait[es]*\b'),
    ('fenêtre', r'\bfenêtre[s]?\b'),
    ('saturé', r'\bsatur[eéa]\w*\b'),
    ('se mérite', r'\bse méri[tes]+\b'),
    ('magique', r'\bmagiques?\b'),
    ('Si vous X:', r'Si vous \w+ : '),
    ('iconique', r'\biconique[s]?\b'),
    ('antithèse', r'antithèse'),
    ('mythique', r'\bmythique[s]?\b'),
    ('emblématique', r'\bemblématique[s]?\b'),
    ('authentique', r'\bauthentique[s]?\b'),
    ('féérique', r'\bféérique[s]?\b'),
    ("c'est aussi", r"[Cc]'est aussi"),
    ('à monitorer', r'à monitorer'),
    ('à éviter', r'à éviter'),
]

print("\n=== Audit batch 16 ===")
issues_total = 0
for slug in AVIS_BATCH16_FR.keys():
    plain = re.sub(r'<[^>]+>', '', data_existing[slug])
    issues = []
    for label, p in patterns_check:
        n = len(re.findall(p, plain))
        if n > 0:
            issues.append(f"{label}={n}")
            issues_total += n
    flag = "OK" if not issues else "PB " + ", ".join(issues)
    print(f"  {slug:<22} {len(plain.split()):>3}m {flag}")
print(f"\nTotal issues : {issues_total}")
