"""Batch 13 : 21 avis FR Tier 2 capitales européennes secondaires."""
import json

PATH = 'data/avis_annuel.json'

AVIS_BATCH13_FR = {
    "bratislava:fr": "Bratislava, capitale slovaque : 475 000 habitants sur le Danube, vieille ville baroque compacte (à voir en 1 journée), souvent combinée avec Vienne (1h en train) ou Budapest (2h30). <strong>Juillet est mon mois préféré</strong> (9.2/10) : 18-28°C, 30% de pluie, terrasses sur Hlavné námestie, croisières Danube. <strong>D'août</strong> reste excellent (9.1/10). <strong>De juin à septembre</strong>, c'est la haute saison : 13-28°C, 27-36% de pluie. <strong>De novembre à mars</strong>, comptez -2/9°C et 23-32% de pluie : froid sec continental, marché de Noël sur Hlavné námestie fin novembre-décembre (l'un des plus authentiques d'Europe centrale, sans la foule de Vienne ou Prague), prix x2. <strong>Sites majeurs</strong> : <strong>Vieille ville</strong> compacte (Hlavné námestie place principale, fontaine de Maximilien), <strong>Château de Bratislava</strong> (sur la colline, vue panoramique sur le Danube et l'Autriche-Hongrie au loin), <strong>Cathédrale Saint-Martin</strong> (ancien lieu de couronnement des rois de Hongrie), <strong>Porte Saint-Michel</strong> (seule porte médiévale conservée), <strong>Pont SNP</strong> (Most Slovenského Národného Povstania, surnommé \"UFO\" pour sa tour-restaurant en soucoupe volante), <strong>Devín Castle</strong> (ruines slaves à 15 min en bus, confluent Danube-Morava). <strong>Quartier juif</strong> Židovská. <strong>Tester</strong> bryndzové halušky (gnocchis au fromage de brebis, plat national), kapustnica (soupe au chou et saucisse), Tatratea (liqueur). Bratislava est moins chère que Vienne ou Prague (bière 1,5-2€, repas 8-15€).",

    "sofia:fr": "Sofia, capitale bulgare : 1,3 million d'habitants à 550m d'altitude au pied du <strong>mont Vitosha</strong> (2290m, accessible en téléphérique pour ski en hiver et randonnée en été). Mélange architectural unique : ruines romaines, mosquée ottomane, cathédrale orthodoxe, immeubles communistes. <strong>Juillet est mon mois préféré</strong> (9.6/10) : 17-28°C, 19% de pluie, températures parfaites grâce à l'altitude. <strong>De juin à septembre</strong>, c'est la haute saison : 13-28°C, climat continental sec et chaud. <strong>De décembre à mars</strong>, comptez -3/13°C et 25-36% de pluie : froid sec, ski possible sur Vitosha à 30 min en bus. <strong>Sites majeurs</strong> : <strong>Cathédrale Saint-Alexandre-Nevski</strong> (la signature de Sofia, néo-byzantine 1912, dôme doré, l'une des plus grandes cathédrales orthodoxes au monde, intérieur à voir), <strong>Église Sainte-Sophie</strong> (à côté, l'origine du nom de la ville, IVe siècle), <strong>Vitosha Boulevard</strong> (rue piétonne principale), <strong>Saint-Georges Rotunda</strong> (la plus vieille église préservée de Sofia, IVe siècle, romaine), <strong>Mosquée Banya Bashi</strong> (XVIe, l'une des plus vieilles mosquées d'Europe), <strong>Synagogue de Sofia</strong> (3e plus grande sépharade d'Europe), <strong>Musée National d'Histoire</strong> (à Boyana, trésors thraces). <strong>Boyana Church</strong> (UNESCO, fresques médiévales bulgares à 20 min). <strong>Excursions</strong> : <strong>Monastère de Rila</strong> à 2h (UNESCO, fresques colorées, le monument national), <strong>Plovdiv</strong> à 1h45 (vieille ville UNESCO). <strong>Tester</strong> banitsa (chausson au fromage), kebapche, shopska salata (salade nationale), rakia (eau-de-vie aux fruits), yaourt bulgare (origine ici). Capitale parmi les moins chères d'Europe.",

    "bucarest:fr": "Bucarest, capitale roumaine : 1,8 million d'habitants, surnommée le \"Petit Paris des Balkans\" (architecture Belle Époque française XIXe). Marqué par 50 ans de communisme (Ceaușescu) puis transition démocratique parfois chaotique. <strong>Juillet-août sont mes mois préférés</strong> (9.1/10) : 19-31°C, 17-26% de pluie, terrasses dans Lipscani vieille ville. <strong>Septembre</strong> reste excellent (9.1/10) avec 26°C en moyenne. <strong>De juin à septembre</strong>, c'est la haute saison : 15-31°C, 14-38% de pluie. <strong>De novembre à mars</strong>, comptez -3/11°C et 22-31% de pluie : froid sec continental, marché de Noël sur Piața Constituției et Piața Universității. <strong>Sites majeurs</strong> : <strong>Palatul Parlamentului</strong> (Maison du Peuple, le plus grand bâtiment civil au monde après le Pentagone, 365 000 m², construit par Ceaușescu 1984-1989, 3500 personnes y travaillent encore, visite guidée 50 min, 80 lei), <strong>Centre historique Lipscani</strong> (rues piétonnes, restos, bars, vie nocturne), <strong>Athénée Roumain</strong> (salle de concert 1888, néoclassique), <strong>Biserica Stavropoleos</strong> (petite église XVIIIe en plein centre), <strong>Musée du Village</strong> (en plein air, maisons traditionnelles roumaines de toutes les régions), <strong>Curtea Veche</strong> (Vieille Cour, ruines de Vlad Țepeș alias Dracula), <strong>Cișmigiu Park</strong> (parc central). <strong>Excursions</strong> : <strong>Sinaia et Castel Peleș</strong> à 2h (résidence d'été des rois roumains), <strong>Brașov et Castel Bran</strong> à 3h (\"château de Dracula\", très touristique), <strong>Sibiu</strong> à 4h (cité saxonne UNESCO). <strong>Tester</strong> mititei (saucisses), sarmale (chou farci), mămăligă (polenta), țuică (eau-de-vie de prune), vins roumains (Murfatlar, Cotnari).",

    "belgrade:fr": "Belgrade, capitale serbe : 1,2 million d'habitants au confluent <strong>Danube-Sava</strong>, ville rebâtie 44 fois selon la légende (carrefour stratégique entre Orient et Occident). Vie nocturne mondiale (splavovi = barges-clubs sur la Sava), ambiance bohème post-yougoslave. <strong>Août est mon mois préféré</strong> (9.1/10) : 19-30°C, 21% de pluie, festivals d'été (Belgrade Beer Fest, EXIT à Novi Sad voisin). <strong>Juin-juillet</strong> restent excellents (8.9-9.0/10). <strong>De juin à septembre</strong>, c'est la haute saison : 15-30°C, climat continental sec. <strong>De novembre à mars</strong>, comptez -2/12°C et 31-35% de pluie : froid sec, mais Belgrade est connue pour faire la fête toute l'année (kafanas musique tzigane). <strong>Sites majeurs</strong> : <strong>Forteresse de Kalemegdan</strong> (ruines bétonnées, parc public au confluent Danube-Sava, vue panoramique sur la Nouvelle Belgrade et le coucher de soleil), <strong>Knez Mihailova</strong> (rue piétonne principale), <strong>Quartier bohème Skadarlija</strong> (kafanas et restos traditionnels avec orchestre tzigane), <strong>Cathédrale Saint-Sava</strong> (l'une des plus grandes églises orthodoxes au monde, mosaïques en cours d'achèvement depuis 1985), <strong>Maison des Fleurs</strong> (mausolée de Tito, dirigeant de la Yougoslavie communiste 1953-1980), <strong>Beton Hala</strong> (bord de la Sava, restos branchés). <strong>Vie nocturne</strong> : <strong>splavovi</strong> (barges-clubs flottantes sur la Sava et le Danube, Freestyler/20-44/Lasta, ambiance jusqu'à 5h, prix abordables), bars à Cetinjska (ancienne brasserie reconvertie en quartier festif). <strong>Excursions</strong> : <strong>Novi Sad</strong> à 1h (ville culturelle, Petrovaradin Fortress, EXIT Festival début juillet), <strong>Subotica</strong> à 2h30 (Art Nouveau hongrois). <strong>Tester</strong> ćevapi (saucisses), pljeskavica (steak haché), karadjordjeva šnicla, rakija šljivovica (eau-de-vie de prune).",

    "sarajevo:fr": "Sarajevo, capitale de la Bosnie-Herzégovine : 275 000 habitants dans une vallée encaissée des Dinariques. Carrefour culturel unique en Europe : <strong>4 religions cohabitent dans un rayon de 200m</strong> (mosquée Gazi Husrev-bey, cathédrale catholique, cathédrale orthodoxe, synagogue Ashkénaze). Lieu de l'attentat de Sarajevo (1914, déclencheur 1ère Guerre mondiale) et siège terrible de 1992-1996 (1425 jours, 11 541 morts). <strong>Juillet-août sont mes mois préférés</strong> (8.8-8.9/10) : 16-27°C, 32-37% de pluie, terrasses dans le Baščaršija. <strong>De juin à septembre</strong>, c'est la haute saison : 12-27°C, climat continental tempéré par l'altitude (550m). <strong>De décembre à mars</strong>, comptez -4/10°C et 38-44% de pluie/neige : froid hivernal, ski sur les pentes du <strong>Mont Bjelašnica</strong> et <strong>Jahorina</strong> (sites des JO 1984). <strong>Sites majeurs</strong> : <strong>Baščaršija</strong> (vieux bazar ottoman, dédale de ruelles, mosquée Gazi Husrev-Bey, fontaine Sebilj), <strong>Pont latin</strong> et <strong>Musée de Sarajevo 1878-1918</strong> (lieu exact de l'assassinat de l'archiduc François-Ferdinand le 28 juin 1914), <strong>Tunnel de l'Espoir</strong> (Tunnel d'Espoir 800m sous l'aéroport, seul lien avec l'extérieur durant le siège, musée poignant), <strong>Cimetière sur les collines</strong> (impressionnant nombre de tombes 1992-1996), <strong>Mont Trebević</strong> (téléphérique reconstruit 2018, vue panoramique, ancien circuit de bobsleigh JO 1984 abandonné devenu spot graffiti urbain), <strong>Avenue des Sniper Alley</strong> (la rue principale Bulevar Meše Selimovića où les snipers serbes tiraient sur les civils). <strong>Tester</strong> ćevapi (chez Ćevabdžinica Željo, le plus connu), burek, baklava, café bosniaque (servi à la turque). Sarajevo reste l'une des destinations les moins chères d'Europe.",

    "zagreb:fr": "Zagreb, capitale croate : 800 000 habitants, ville austro-hongroise éloignée du tourisme balnéaire dalmate (souvent simple escale avant Plitvice ou Dubrovnik). Pourtant l'une des capitales d'Europe centrale les plus charmantes et les moins chères. <strong>Juillet est mon mois préféré</strong> (9.2/10) : 18-28°C, 29% de pluie, terrasses, festivals (INmusic Festival fin juin, Zagreb Summer Evenings). <strong>D'août</strong> reste excellent (9.0/10). <strong>De juin à septembre</strong>, c'est la haute saison : 14-28°C, 29-49% de pluie. <strong>De décembre à mars</strong>, comptez -2/13°C et 28-32% de pluie : froid sec continental, <strong>Advent à Zagreb</strong> (marché de Noël élu meilleur d'Europe 3 années de suite 2016-2018, novembre-janvier, patinoire sur place du Roi Tomislav). <strong>Sites majeurs</strong> : <strong>Vieille ville Gornji Grad</strong> (Ville Haute, accessible par funiculaire le plus court au monde 66m), <strong>Cathédrale</strong> (néo-gothique, restauration en cours après séisme 2020), <strong>Église Saint-Marc</strong> (toit en tuiles colorées avec armoiries de Zagreb-Croatie-Slavonie-Dalmatie), <strong>Place Ban Jelačić</strong> (place principale), <strong>Marché Dolac</strong> (marché central coloré, parasols rouges signature), <strong>Musée des Relations Brisées</strong> (collection d'objets liés à des ruptures amoureuses, original et touchant), <strong>Mirogoj</strong> (cimetière monumental, l'un des plus beaux d'Europe), <strong>Tunnel Grič</strong> (abri anti-aérien WWII transformé en passage souterrain). <strong>Excursions</strong> : <strong>Plitvice</strong> à 2h, <strong>Samobor</strong> à 30 min (kremšnita, pâtisserie traditionnelle). <strong>Tester</strong> štrukli (pâtisserie au fromage), grah (haricots), pálinka, vins continentaux (Graševina). Zagreb à 2h de Vienne, 4h de Budapest et Munich.",

    "ljubljana:fr": "Ljubljana, capitale slovène : 290 000 habitants, l'une des plus petites et des plus charmantes capitales d'Europe (\"la verte\" - European Green Capital 2016, centre piéton sans voitures depuis 2008). <strong>Juillet est mon mois préféré</strong> (9.0/10) : 16-28°C, 35% de pluie, terrasses sur la Ljubljanica, festivals (Ljubljana Summer Festival juillet-août). <strong>De juin à septembre</strong>, c'est la haute saison : 12-28°C, climat continental tempéré. <strong>De décembre à mars</strong>, comptez -4/12°C et 29-39% de pluie/neige : froid sec, ski sur Krvavec ou Vogel à 1h, marché de Noël (Festive December) charmant en bord de rivière. <strong>Sites majeurs</strong> : <strong>Vieille ville</strong> (à pied, autour de Mestni trg place principale), <strong>Triple Pont</strong> (Tromostovje, signature de Plečnik 1932, 3 ponts en éventail au cœur de la ville), <strong>Pont des Dragons</strong> (Zmajski most, 4 dragons gardiens emblématiques de Ljubljana), <strong>Château de Ljubljana</strong> (sur la colline, accessible en funiculaire ou à pied 15 min, vue panoramique sur les Alpes), <strong>Marché Central</strong> (Plečnik, néoclassique en bord de rivière), <strong>Mételkova</strong> (squat artistique alternatif, ex-caserne militaire, vie nocturne underground). <strong>Excursions</strong> : <strong>Lac de Bled</strong> à 50 min (\"l'image carte postale slovène\", église sur île, château perché), <strong>Lac de Bohinj</strong> à 1h30 (plus sauvage, parc national Triglav), <strong>Grottes de Postojna</strong> à 50 min (24 km de galeries, train souterrain, plus visitées d'Europe), <strong>Predjama Castle</strong> (château incrusté dans une falaise XIIIe). <strong>Côte adriatique</strong> à 1h30 (Piran ville médiévale vénitienne). <strong>Tester</strong> potica (gâteau roulé), idrijski žlikrofi (raviolis), kranjska klobasa (saucisse), vin Refošk.",

    "tallinn:fr": "Tallinn, capitale estonienne : 450 000 habitants sur le golfe de Finlande, vieille ville médiévale UNESCO la mieux conservée d'Europe du Nord (XIIIe-XVIe). Estonie hyper-numérique (e-residency, e-government modèle mondial depuis 1991). <strong>Juin est mon mois préféré</strong> (8.2/10) : 12-20°C, 37% de pluie, journées de 18h en juin (jamais nuit complète au solstice d'été = \"valged ööd\" nuits blanches), terrasses. <strong>De juin à août</strong>, c'est la haute saison touristique : 14-21°C, croisières Baltique très nombreuses (Helsinki à 2h en ferry, Stockholm à 16h en ferry de nuit). <strong>De novembre à mars</strong>, comptez -3/4°C et 34-50% de précipitations souvent neige : <strong>Tallinn sous la neige</strong> est <strong>spectaculaire</strong> (toits enneigés, marché de Noël sur Raekoja plats considéré l'un des plus charmants d'Europe), jours à 6h de lumière fin décembre. <strong>Sites majeurs</strong> : <strong>Vieille ville</strong> (UNESCO, divisée en Toompea ville haute et Vanalinn ville basse) : <strong>Raekoja plats</strong> (Place de l'Hôtel de Ville, marché de Noël depuis 1441), <strong>Cathédrale Alexandre-Nevsky</strong> (russe orthodoxe sur Toompea), <strong>Tour Kiek in de Kök</strong>, <strong>Plateforme Kohtuotsa</strong> (panorama signature sur les toits rouges et la mer), <strong>Tour de Saint-Olaf</strong> (Oleviste, 124m, ascenseur en bois, vue), <strong>Pikk Hermann</strong> (forteresse Toompea, drapeau estonien hissé chaque matin). <strong>Quartier de Kalamaja</strong> (ex-pêcheurs, maintenant branché, vieilles maisons en bois, Telliskivi creative city), <strong>Patarei</strong> (ancienne prison soviétique sinistre). <strong>Excursions</strong> : <strong>Helsinki</strong> en 2h en ferry (excursion journée populaire), <strong>Lahemaa National Park</strong> à 1h (forêts, manoirs baltes). <strong>Tester</strong> verivorst (boudin de Noël), kohuke (fromage cottage en barre), liqueur Vana Tallinn.",

    "riga:fr": "Riga, capitale lettone : 615 000 habitants sur la Baltique, plus grande ville des pays baltes. Vieille ville médiévale UNESCO + 800 immeubles <strong>Art Nouveau</strong> (jugendstil, la plus grande concentration au monde, à voir notamment rue Alberta). <strong>Juin est mon mois préféré</strong> (8.4/10) : 12-22°C, 41% de pluie, journées de 17h en juin (presque nuit blanche au solstice). <strong>De juin à août</strong>, c'est la haute saison touristique : 14-22°C. <strong>De novembre à mars</strong>, comptez -3/6°C et 35-48% de précipitations souvent neige : marché de Noël sur Doma laukums (le sapin de Noël public a été inventé à Riga en 1510, les Letnos défendent l'origine contre les revendications de Tallinn), jours à 7h de lumière fin décembre. <strong>Sites majeurs</strong> : <strong>Vieille ville</strong> (UNESCO, Doma laukums place de la cathédrale, Maison des Têtes Noires guilde marchande médiévale reconstruite après destruction WWII), <strong>Cathédrale luthérienne de Riga</strong> (XIIIe, l'une des plus grandes des pays baltes), <strong>Église Saint-Pierre</strong> (123m, ascenseur pour la vue), <strong>Bastion des Suédois</strong> (porte médiévale jaune signature), <strong>Trois Frères</strong> (3 maisons médiévales adjacentes, les plus vieilles de Riga), <strong>Quartier Art Nouveau</strong> (rue Alberta = la plus belle, immeubles d'Mikhaïl Eisenstein père du réalisateur), <strong>Marché Central de Riga</strong> (5 anciens hangars de zeppelin Première Guerre mondiale, l'un des plus grands marchés d'Europe), <strong>Monument de la Liberté</strong> (1935, gardé 24/7). <strong>Quartier Maskavas</strong> (ex-quartier juif/russe, plus authentique). <strong>Excursions</strong> : <strong>Jūrmala</strong> à 25 min en train (station balnéaire baltique, plage longue), <strong>Sigulda</strong> à 1h (\"Suisse de Lettonie\", Gauja Valley, château de Turaida). <strong>Tester</strong> riga sprats (sardines fumées en boîte), pīrāgi (pâté), Black Balsam (liqueur amère 45° à base de 24 plantes, signature lettone).",

    "vilnius:fr": "Vilnius, capitale lituanienne : 590 000 habitants, vieille ville baroque UNESCO (la plus grande d'Europe centrale et orientale, 360 hectares). Catholique fervente (95% de Lituaniens catholiques, contraste avec les voisins luthériens estoniens et lettons). <strong>Juin est mon mois préféré</strong> (8.4/10) : 13-23°C, 40% de pluie, journées longues, terrasses sur la Vilnia. <strong>De juin à août</strong>, c'est la haute saison touristique : 14-23°C. <strong>De novembre à mars</strong>, comptez -4/6°C et 31-49% de précipitations souvent neige : marché de Noël sur Cathedral Square considéré parmi les plus charmants d'Europe, plus continentale que Riga ou Tallinn. <strong>Sites majeurs</strong> : <strong>Vieille ville</strong> (UNESCO, dédale baroque exceptionnel) : <strong>Cathédrale et Place de la Cathédrale</strong> (Katedros aikštė, néoclassique blanche, clocher séparé), <strong>Tour de Gediminas</strong> (sur la colline, fondation de Vilnius en 1323, panorama, funiculaire 2 min), <strong>Église Saint-Anne</strong> (gothique flamboyant en briques rouges, Napoléon a voulu la ramener à Paris dans la paume de sa main), <strong>Église Saint-Pierre-et-Saint-Paul</strong> (intérieur baroque le plus exubérant des pays baltes, 2000 sculptures stuc), <strong>Université de Vilnius</strong> (1579, l'une des plus vieilles d'Europe centrale, complexe de cours intérieures), <strong>Quartier Užupis</strong> (\"république autoproclamée\" indépendante depuis le 1er avril 1997, constitution affichée en plusieurs langues, ambiance bohème montmartroise), <strong>Porte de l'Aurore</strong> (Aušros vartai, seule porte préservée de l'enceinte médiévale, icône miraculeuse Vierge Marie). <strong>Holocaust history</strong> : ghetto de Vilnius préservé (\"Jérusalem du Nord\" avant 1939, 60 000 Juifs assassinés). <strong>Excursions</strong> : <strong>Trakai</strong> à 30 min (château insulaire en briques rouges sur lac), <strong>Kernavė</strong> à 1h (capitale médiévale UNESCO). <strong>Tester</strong> cepelinai (boulettes de pomme de terre fourrées), kibinai (chausson), bière lituanienne (Švyturys).",

    "tirana:fr": "Tirana, capitale albanaise : 600 000 habitants, métamorphosée depuis la fin du communisme isolationniste d'Enver Hoxha (1944-1985 : Albanie était le pays le plus fermé d'Europe, plus que la Corée du Nord aujourd'hui, 173 000 bunkers paranoïaques construits). <strong>Juin est mon mois préféré</strong> (9.4/10) : 18-28°C, 22% de pluie, températures parfaites avant la canicule. <strong>Juillet-août chutent à 6.9/10</strong> à cause de la chaleur (20-32°C), mais ouverture de la côte (Saranda à 4h, Riviera albanaise méconnue mais belle). <strong>D'avril à juin et septembre-octobre</strong> sont les meilleurs compromis. <strong>De décembre à février</strong>, comptez 3-13°C et 35-39% de pluie : doux pour les Balkans. <strong>Sites majeurs</strong> : <strong>Place Skanderbeg</strong> (Sheshi Skënderbej, place principale rénovée 2017 sans voitures, statue du héros national), <strong>Mosquée Et'hem Bey</strong> (XVIIIe, fresques rares pour une mosquée), <strong>Tour de l'Horloge</strong> (XIXe), <strong>Pyramide de Tirana</strong> (ex-musée Enver Hoxha 1988, design de la fille du dictateur, abandonnée puis réhabilitée 2023 en centre culturel/jeunesse), <strong>Bunk'Art 1 et Bunk'Art 2</strong> (anciens bunkers anti-atomiques de Hoxha transformés en musées sur le communisme et la persécution, très impressionnants), <strong>Maison aux feuilles</strong> (House of Leaves, ancien siège secret services secrets, musée surveillance), <strong>Mont Dajti</strong> (téléphérique 15 min, vue panoramique sur la ville, restos en altitude). <strong>Quartier Blloku</strong> (ex-réservé à la nomenklatura communiste, maintenant zone hipster, restos, nightlife). <strong>Excursions</strong> : <strong>Krujë</strong> à 30 min (forteresse de Skanderbeg, vues), <strong>Berat</strong> à 2h (UNESCO, \"ville aux mille fenêtres\"), <strong>Côte Riviera albanaise</strong> à 4-5h (Saranda, Ksamil, Himara - alternative bon marché à la Croatie). <strong>Tester</strong> tavë kosi, byrek, raki. Vol direct Paris-Tirana en 2h45, capitale parmi les moins chères d'Europe.",

    "pristina:fr": "Pristina, capitale du Kosovo : 200 000 habitants, jeune capitale (indépendance 2008, reconnue par 100 États dont la France, contestée par la Serbie et la Russie). Pas la plus jolie mais l'une des plus jeunes d'Europe (60% de la population a moins de 25 ans). <strong>Juillet est mon mois préféré</strong> (9.1/10) : 17-28°C, 26% de pluie, terrasses. <strong>D'août</strong> reste excellent (9.0/10). <strong>De juin à septembre</strong>, c'est la haute saison : 13-29°C, climat continental sec. <strong>De février à mars chutent à 1.9-2.0/10</strong> à cause d'humidité, ciel gris, températures basses. <strong>De novembre à mars</strong>, comptez -2/13°C : froid hivernal continental. <strong>Sites majeurs</strong> : <strong>Statue de Bill Clinton</strong> (\"hero of Kosovo\" pour avoir lancé les bombardements OTAN 1999 qui ont mis fin au conflit, boulevard Bill Clinton), <strong>Bibliothèque Nationale</strong> (architecture brutaliste 1982 polarisante, recouverte de 99 dômes blancs et grilles métalliques, l'une des plus laides au monde selon certains classements - donc à voir), <strong>Cathédrale Mère Teresa</strong> (catholique, en cours d'achèvement, dédiée à la sainte d'origine albanaise), <strong>Newborn Monument</strong> (lettres NEWBORN repeintes chaque année selon un thème, érigées le jour de l'indépendance 17 février 2008), <strong>Mosquée du Sultan Mehmet Fatih</strong> (XVe, ottomane), <strong>Bazaar</strong> (Old Bazaar). <strong>Excursions</strong> : <strong>Prizren</strong> à 1h30 (la \"vraie\" capitale culturelle du Kosovo, vieille ville ottomane charmante), <strong>Monastère de Visoki Dečani</strong> (UNESCO, monastère orthodoxe serbe protégé par la KFOR, frescoes XIVe), <strong>Rugovo Canyon</strong> près de Peja (canyon, ski en hiver). <strong>Tester</strong> burek, ćevapi, flija (gâteau de crêpes), raki (eau-de-vie de prune). Capitale parmi les moins chères d'Europe (bière 1€, repas 5-10€).",

    "skopje:fr": "Skopje, capitale de la Macédoine du Nord : 540 000 habitants, ville natale de <strong>Mère Teresa</strong>. Reconstruite après le séisme dévastateur de 1963 (1100 morts) puis transformée par le mégalomaniaque projet \"Skopje 2014\" du gouvernement Gruevski (statues monumentales kitsch, façades néo-classiques colle au polystyrène recouvrant des bâtiments brutalistes). Ville fascinante par son chaos urbain. <strong>Juin est mon mois préféré</strong> (9.3/10) : 17-30°C, 21% de pluie, températures parfaites avant la canicule. <strong>Juillet-août restent bons</strong> (8.9-9.0/10) malgré la chaleur (19-32°C). <strong>De juin à septembre</strong>, c'est la haute saison : 16-32°C, climat continental sec. <strong>De décembre à mars</strong>, comptez -2/14°C : froid sec. <strong>Sites majeurs</strong> : <strong>Place de Macédoine</strong> (Plostad Makedonija, statue géante d'Alexandre le Grand 22m \"Warrior on a Horse\", controverse historique avec la Grèce), <strong>Pont de Pierre</strong> (XVe ottoman, reliant la place macédonienne à la vieille ville), <strong>Vieux Bazar (Stara Čaršija)</strong> (l'un des plus grands bazars ottomans des Balkans, dédale de ruelles pavées, mosquées XVe-XVIIe), <strong>Forteresse de Kale</strong> (ruines byzantines sur une colline, vue panoramique), <strong>Mosquée Mustafa Pacha</strong>, <strong>Maison Mémorielle Mère Teresa</strong> (sur le lieu exact de sa naissance 1910, baptisée à 1 jour, partie de Skopje à 18 ans), <strong>Mont Vodno</strong> (avec téléphérique pour la <strong>Croix du Millénaire</strong> 66m érigée en 2002, vue panoramique). <strong>Excursions</strong> : <strong>Canyon Matka</strong> à 30 min (canyon, monastère, kayak, grottes), <strong>Lac Ohrid</strong> à 3h (UNESCO, l'un des plus vieux lacs au monde 4 millions d'années). <strong>Tester</strong> tavče gravče (haricots), ajvar (purée poivrons rouges), kebapi, rakija (eau-de-vie). Capitale moins chère d'Europe.",

    "ohrid:fr": "Ohrid, ville de Macédoine du Nord sur le <strong>lac Ohrid</strong> (UNESCO double inscription naturelle ET culturelle, l'un des seuls sites mixtes au monde) : 42 000 habitants, lac de 358 km² partagé avec l'Albanie, l'un des plus vieux lacs au monde (4 millions d'années) et des plus profonds d'Europe (288m). <strong>Juillet est mon mois préféré</strong> (9.6/10) : 19-28°C, 16% de pluie, températures parfaites, baignade dans le lac (eau à 24°C). <strong>D'août</strong> reste excellent (9.3/10). <strong>De juin à septembre</strong>, c'est la haute saison touristique : 15-28°C, locaux macédoniens en majorité (Ohrid = la \"Riviera macédonienne\"). <strong>De décembre à mars</strong>, comptez 1-11°C et 25-37% de pluie : doux pour les Balkans, ambiance hivernale calme. <strong>Sites majeurs</strong> : <strong>Église Saint-Jean de Kaneo</strong> (XIIIe, perchée sur falaise au-dessus du lac, l'une des images les plus connues de Macédoine), <strong>Vieille ville</strong> (rues pavées XIIe-XIIIe, maisons traditionnelles macédoniennes en bois), <strong>Église Sainte-Sophie</strong> (XIe, fresques byzantines exceptionnelles), <strong>Théâtre antique</strong> (4e siècle av JC, hellénistique puis romain, encore utilisé pour le Festival d'été d'Ohrid juillet-août), <strong>Monastère Saint-Naoum</strong> à 30 km (au sud, fondé par le disciple de Cyrille et Méthode, sources de Saint-Naoum source de la rivière Drim), <strong>Forteresse Samuel</strong> (Xe, panorama sur la vieille ville et le lac), <strong>Bay of Bones</strong> (musée subaquatique reconstituant un village néolithique sur pilotis). <strong>Activités</strong> : croisières sur le lac (vers Saint-Naoum 4h), baignade à Lagadin/Trpejca, randonnée Mont Galičica (parc national entre Ohrid et lac Prespa). <strong>Tester</strong> Belvica (poisson endémique du lac, 17 espèces uniques au monde), tavče gravče, ajvar, vins macédoniens (Tikveš). Vol direct Wizz Air vers Ohrid, ou via Skopje (2h30 en bus).",

    "luxembourg:fr": "Luxembourg-Ville, capitale du Grand-Duché de Luxembourg : 130 000 habitants (700 000 dans le pays), siège de plusieurs institutions européennes (Cour de Justice de l'UE, Cour des Comptes), centre financier majeur (banques, fonds d'investissement). Ville bilingue français/luxembourgeois/allemand, l'un des PIB par habitant les plus élevés au monde. <strong>Juillet est mon mois préféré</strong> (8.3/10) : 14-23°C, 30% de pluie, températures clémentes. <strong>De juin à septembre</strong>, c'est la haute saison : 11-23°C, climat océanique tempéré. <strong>De novembre à mars</strong>, comptez 0-9°C et 38-47% de pluie : froid sec à humide, marché de Noël (Wantermaart) sur la place d'Armes et place Guillaume II fin novembre-décembre. <strong>Sites majeurs</strong> : <strong>Vieille ville</strong> (UNESCO, perchée sur un plateau au-dessus des gorges de l'Alzette et de la Pétrusse, paysage urbain unique en Europe, à découvrir au coucher du soleil depuis le pont Adolphe), <strong>Casemates du Bock</strong> (UNESCO, 23 km de galeries souterraines creusées dans le rocher au XVIIe siècle, refuge anti-aérien WWII), <strong>Palais Grand-Ducal</strong> (résidence officielle du Grand-Duc Henri, relève de la garde l'été), <strong>Cathédrale Notre-Dame</strong> (XVIIe), <strong>Place d'Armes</strong>, <strong>Quartier Grund</strong> (en bas dans la vallée, ambiance villageoise au pied des falaises, restos au bord de l'Alzette), <strong>Quartier Kirchberg</strong> (ville moderne européenne, MUDAM Musée d'Art Moderne dans bâtiment Pei), <strong>Mémorial de la Solidarité</strong> (Gëlle Fra, statue dorée signature). <strong>Excursions Petite Suisse luxembourgeoise</strong> au nord-est (Mullerthal, gorges, randonnées), <strong>Vianden</strong> au nord (château médiéval), <strong>Vallée de la Moselle</strong> (vins blancs Riesling/Gewurztraminer/Pinot). <strong>Tester</strong> Judd mat Gaardebounen (collier de porc fumé), Gromperekichelcher (galettes de pomme de terre), bières Diekirch/Bofferding. Très chère (l'une des capitales les plus coûteuses d'Europe).",

    "bergen:fr": "Bergen, deuxième ville de Norvège : 290 000 habitants sur la côte ouest, surnommée la \"Porte des Fjords\" (point de départ pour Geirangerfjord, Sognefjord, Hardangerfjord). Aussi appelée la \"ville la plus pluvieuse d'Europe\" (200-300 jours de pluie/an, 2300 mm/an). <strong>Juin est mon mois préféré</strong> (7.1/10) : 9-16°C, 53% de pluie, journées longues. <strong>De juin à août</strong>, c'est la haute saison : 9-17°C, 53-66% de pluie (la chance d'avoir une journée sans pluie est faible toute l'année). Bergen ne dépasse jamais 7.1/10 (climat océanique très humide). <strong>De septembre à mars</strong>, comptez -1/10°C et 56-68% de précipitations (souvent neige en hiver) : Bergen sous la pluie ou la neige a son charme particulier. <strong>De novembre à mars</strong>, jours à 6-7h de lumière, mais aurores boréales rares à cette latitude (60°N, plus au sud que Tromsø). <strong>Sites majeurs</strong> : <strong>Bryggen</strong> (UNESCO, quartier hanséatique XIVe, maisons en bois colorées sur le port, l'image emblématique de Bergen, plusieurs incendies au cours des siècles, rebâti à l'identique), <strong>Marché aux poissons (Fisketorget)</strong> (en bord de port, depuis 1276, fruits de mer frais), <strong>Funiculaire Fløibanen</strong> (8 min pour Mont Fløyen 320m, vue panoramique sur les fjords et la ville), <strong>Téléphérique Ulriksbanen</strong> (Mont Ulriken 643m, vue à 360°), <strong>Cathédrale Saint-Olaf</strong> (XIIe), <strong>Hanseatic Museum</strong> (vie des marchands hanséatiques). <strong>Excursions fjords</strong> : <strong>Norway in a Nutshell</strong> (combo train + bateau + bus depuis Bergen vers Flåm/Sognefjord, journée complète 1500-2000 NOK), <strong>croisière Geirangerfjord</strong> (UNESCO, 5h en ferry), <strong>Hardangerfjord</strong> (3e plus long fjord du monde). <strong>Tester</strong> fiskesuppe (soupe de poisson), bacalao, brunost (fromage brun caractéristique de Norvège). Très chère (Norvège = l'un des pays les plus chers au monde, repas 30-60€, bière 8-12€).",

    "aarhus:fr": "Aarhus, deuxième ville du Danemark : 290 000 habitants sur la côte est de Jutland, vibrante ville étudiante (40 000 étudiants, 30% de la population), <strong>Capitale Européenne de la Culture 2017</strong>. Plus jeune et plus accessible que Copenhague pour découvrir le Danemark moderne. <strong>Juin est mon mois préféré</strong> (7.9/10) : 12-19°C, 40% de pluie, journées de 18h en juin. <strong>De juin à août</strong>, c'est la haute saison touristique : 12-20°C, 40-46% de pluie, plages au nord (Bellevue) et sud (Marselisborg Forest). <strong>De novembre à mars</strong>, comptez 1-8°C et 37-46% de précipitations souvent neige : ambiance hygge danoise (concept de cocooning), marchés de Noël à la place de l'hôtel de ville. <strong>Sites majeurs</strong> : <strong>ARoS Aarhus Kunstmuseum</strong> (musée d'art moderne, signature de l'arc-en-ciel <strong>\"Your Rainbow Panorama\"</strong> d'Olafur Eliasson sur le toit, panorama 360° à travers verre coloré), <strong>Den Gamle By</strong> (\"Vieille Ville\", musée en plein air avec 75 maisons historiques danoises XVIe-XXe transportées et reconstituées), <strong>Cathédrale d'Aarhus</strong> (la plus longue d'Europe du Nord 93m, XIIIe), <strong>Moesgaard Museum</strong> (musée de la préhistoire et de l'âge des Vikings, architecture impressionnante avec toit en herbe), <strong>Quartier Latin</strong> (vieille ville médiévale, ruelles charmantes, restos), <strong>Aarhus Street Food</strong> (food court populaire), <strong>Marselisborg Slot</strong> (résidence d'été de la famille royale, parc public). <strong>Île de Samsø</strong> à 1h30 en ferry (île 100% énergies renouvelables depuis 2007). <strong>Skagen</strong> à 2h30 (extrême nord du Danemark, point de rencontre 2 mers Skagerrak et Kattegat). <strong>Tester</strong> smørrebrød (tartines danoises), wienerbrød (pâtisseries), bières craft danoises (Aarhus a 30+ brasseries artisanales).",

    "goteborg:fr": "Göteborg (Gothenburg), 2e ville de Suède : 600 000 habitants sur la côte ouest, ville portuaire avec 21 km de canaux (planifiée par les Néerlandais au XVIIe). Plus accessible et moins chère que Stockholm, ambiance plus décontractée et créative (Volvo y a son siège). <strong>Juin est mon mois préféré</strong> (7.9/10) : 12-19°C, 43% de pluie, journées de 18h, terrasses sur les canaux. <strong>De juin à août</strong>, c'est la haute saison touristique : 12-20°C, 43-55% de pluie. <strong>Novembre à mars</strong>, comptez -1/7°C et 46-57% de précipitations souvent neige : marché de Noël à <strong>Liseberg</strong> mi-novembre à fin décembre (l'un des plus grands de Scandinavie, parc d'attractions transformé en marché féérique avec 5 millions de lumières). <strong>Sites majeurs</strong> : <strong>Liseberg</strong> (le plus grand parc d'attractions de Scandinavie, fondé 1923, montagnes russes Helix, Balder en bois en tête des classements mondiaux), <strong>Haga</strong> (vieux quartier ouvrier piéton, maisons en bois, kanelbullar = brioches à la cannelle géantes chez Café Husaren), <strong>Skansen Kronan</strong> (forteresse XVIIe sur colline, vue panoramique), <strong>Marché de poisson Feskekôrka</strong> (\"Église des poissons\", architecture néo-gothique étonnante 1874), <strong>Götaplatsen</strong> (place avec statue de Poséidon de Carl Milles), <strong>Universeum</strong> (centre de sciences avec animaux, populaire avec familles), <strong>Avenyn</strong> (avenue principale Kungsportsavenyn). <strong>Excursions</strong> : <strong>Archipel de Göteborg</strong> (20 îles accessibles en ferry, sans voiture pour les plus nombreuses, idéal en été), <strong>Marstrand</strong> à 1h (île forteresse, voile), <strong>Smögen</strong> (village de pêcheurs colorés). <strong>Tester</strong> västkustsallad (salade de fruits de mer), kanelbullar, gravlax, surströmming (hareng fermenté = expérience olfactive choc), bière craft suédoise. Plus accessible que Stockholm en termes de prix (-15-20%).",

    "bilbao:fr": "Bilbao, 4e ville d'Espagne et capitale du Pays basque : 350 000 habitants, ville industrielle reconvertie en capitale culturelle depuis l'ouverture du <strong>Musée Guggenheim</strong> en 1997 (architecture Frank Gehry, \"effet Bilbao\" = catalyseur urbain mondial). <strong>Août est mon mois préféré</strong> (8.6/10) : 17-25°C, 30% de pluie, températures clémentes (\"verde\" pour son climat plus humide que la Méditerranée espagnole). <strong>Juillet</strong> reste excellent (8.5/10). <strong>De juin à septembre</strong>, c'est la haute saison touristique : 15-25°C, festivals (Aste Nagusia mi-août, fête patronale, 9 jours de fête, course de vaches, txosnas tentes basques avec sidra et pintxos). <strong>De novembre à février</strong>, comptez 6-15°C et 47-55% de pluie : doux pour l'Espagne, climat océanique humide (le Pays basque reçoit 1200 mm/an). <strong>Sites majeurs</strong> : <strong>Musée Guggenheim Bilbao</strong> (Frank Gehry 1997, architecture déconstructiviste en titane, \"Puppy\" sculpture florale géante de Jeff Koons à l'entrée, l'un des musées les plus visités d'Espagne), <strong>Casco Viejo</strong> (vieille ville, Las Siete Calles = 7 rues médiévales, Cathédrale Santiago, Plaza Nueva avec ses arcades), <strong>Mercado de la Ribera</strong> (le plus grand marché couvert d'Europe, art déco), <strong>Funicular de Artxanda</strong> (3 min vers Mont Artxanda 226m, vue panoramique sur Bilbao), <strong>Pont de Vizcaya</strong> à Portugalete (UNESCO, premier pont transbordeur au monde 1893). <strong>Excursions Pays basque</strong> : <strong>San Sebastián</strong> à 1h (Donostia, La Concha plage), <strong>Guernica</strong> à 30 min (bombardée par l'aviation allemande en 1937, immortalisée par Picasso), <strong>San Juan de Gaztelugatxe</strong> à 35 min (île-îlot avec ermitage et 241 marches, Game of Thrones \"Dragonstone\"). <strong>Tester</strong> pintxos (\"tapas basques\" sur tranche de pain pour 1,5-3€/pièce, bar-hopping dans Casco Viejo), bacalao al pil pil, txuleta (côte de boeuf 1kg), txakoli (vin blanc local pétillant servi de haut), sidra basque.",

    "salamanque:fr": "Salamanque, dans le nord-ouest de l'Espagne : 145 000 habitants, ville universitaire (l'<strong>une des plus vieilles d'Europe</strong>, 1218, 3e plus ancienne université d'Europe après Bologne et Oxford), centre historique UNESCO en grès doré (\"piedra de Villamayor\" qui prend une couleur mordorée au coucher du soleil). <strong>Juillet est mon mois préféré</strong> (9.5/10) : 16-30°C, 6% de pluie, températures parfaites grâce à l'altitude (800m). <strong>D'août</strong> reste excellent (9.3/10). <strong>De juin à septembre</strong>, c'est la haute saison : 12-30°C, climat continental sec et chaud. <strong>D'octobre à mai</strong>, comptez 0-20°C : printemps long et frais (rentrée universitaire dynamise la ville septembre-juin), neige possible décembre-février. <strong>De décembre à février</strong>, comptez 0-13°C et 23-26% de pluie : froid sec, ambiance feu de cheminée dans les bars, terrasses sur Plaza Mayor avec couvertures et chauffages. <strong>Sites majeurs</strong> : <strong>Plaza Mayor</strong> (XVIIIe, baroque churrigueresque, l'une des plus belles places d'Espagne, l'épicentre social des Salamantins le soir), <strong>Université de Salamanque</strong> (façade plateresque 1529, jeu : trouver la \"grenouille sur le crâne\" = porte-bonheur des étudiants), <strong>Vieille et Nouvelle Cathédrales</strong> (adjacentes, romane XIIe + gothique XVIe, repérer l'astronaute et le faune avec ice-cream sculptés au XXe lors d'une restauration), <strong>Casa de las Conchas</strong> (façade ornée de 300 coquilles Saint-Jacques sculptées XVe), <strong>Ieronimites</strong>, <strong>Ponte Romano</strong> (pont romain Ier siècle, 26 arches), <strong>Couvent de San Esteban</strong>, <strong>Convento de las Dueñas</strong> (cloître plateresque). <strong>Tester</strong> jamón ibérico de bellota (région de Guijuelo voisine = l'AOC la plus prestigieuse d'Espagne), hornazo (gâteau salé jambon-chorizo), farinato (saucisse de pain), vins Rueda et Toro voisins. À 2h30 de Madrid en train AVE.",

    "tolede:fr": "Tolède, dans le centre de l'Espagne : 85 000 habitants, ancienne capitale de l'Espagne wisigothique puis musulmane puis chrétienne (capitale jusqu'en 1561 quand Philippe II la déplace à Madrid), <strong>UNESCO 1986</strong>. \"Ville des 3 cultures\" (chrétienne, juive, musulmane qui ont cohabité du VIIIe au XVe siècle). <strong>Juin est mon mois préféré</strong> (9.2/10) : 17-30°C, 13% de pluie, températures parfaites avant la canicule de juillet-août. <strong>Septembre</strong> reste excellent (9.0/10). <strong>De juin à septembre</strong>, c'est la haute saison touristique : 12-35°C, mais aussi <strong>foule extrême</strong> en milieu de journée (Tolède = excursion classique journée depuis Madrid à 30 min en train AVE, 8 millions de visiteurs/an pour 85 000 habitants). <strong>De juillet-août chutent à 6.9/10</strong> à cause de la chaleur extrême (21-35°C, parfois 42°C, intérieur du Plateau de la Meseta). <strong>De décembre à février</strong>, comptez 2-14°C et 18-23% de pluie : froid sec hivernal, mais Tolède en hiver = ambiance médiévale spectaculaire sans foule. <strong>Sites majeurs</strong> : <strong>Cathédrale Sainte-Marie</strong> (gothique français XIIIe-XVe, l'une des plus impressionnantes d'Espagne, retables, sacristie avec 18 Greco), <strong>Alcázar</strong> (forteresse perchée, architecture militaire Renaissance, défaite républicaine en 1936 = épisode mythifié par les franquistes), <strong>Quartier juif (Judería)</strong> (synagogue Santa María la Blanca XIIe avec arches mauresques, synagogue del Tránsito XIVe avec musée séfarade, l'une des deux dernières synagogues médiévales préservées d'Espagne avec Cordoue), <strong>Iglesia de Santo Tomé</strong> (Enterrement du Comte d'Orgaz, chef-d'œuvre du Greco 1586), <strong>Maison-Musée du Greco</strong> (artiste crétois mort à Tolède en 1614), <strong>Mosquée Cristo de la Luz</strong> (Xe, l'une des seules mosquées préservées dans l'Espagne chrétienne), <strong>Pont d'Alcántara</strong> (romain) et <strong>Pont de San Martín</strong> (médiéval), <strong>Mirador del Valle</strong> (panorama signature sur la ville fortifiée encerclée par le Tage). <strong>Tester</strong> mazapán de Toledo (massepain depuis le XIIe), perdrix à la tolédane, queso manchego."
}

with open(PATH, encoding='utf-8') as f:
    data_existing = json.load(f)

before = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

data_existing['_version'] = '2.4'
data_existing['_updated'] = '2026-04-28'

for k, v in AVIS_BATCH13_FR.items():
    data_existing[k] = v

after = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data_existing, f, ensure_ascii=False, indent=2)

print(f"Avis FR avant : {before}")
print(f"Avis FR après : {after}")
print(f"Nouveaux : {after - before}")

# Audit immédiat
import re
patterns_check = [
    ('em-dash', r'—'), ('guillemets', r'[«»]'),
    ('attendez-vous', r'attendez-vous à'),
    ('parfait', r'\bparfait[es]*\b'),
    ('fenêtre', r'\bfenêtre[s]?\b'),
    ('saturé', r'\bsatur[eéa]\w*\b'),
    ('se mérite', r'\bse méri[tes]+\b'),
    ('magique', r'\bmagiques?\b'),
    ('Si vous X:', r'Si vous \w+ : '),
    ('iconique', r'\biconique[s]?\b'),
    ('antithèse', r'antithèse'),
    ('mythique', r'\bmythique[s]?\b'),
    ('emblématique', r'\bemblématique[s]?\b'),
    ('authentique', r'\bauthentique[s]?\b'),
    ('féérique', r'\bféérique[s]?\b'),
    ("c'est aussi", r"[Cc]'est aussi"),
    ('à monitorer', r'à monitorer'),
    ('à éviter', r'à éviter'),
]

print("\n=== Audit batch 13 ===")
issues_total = 0
for slug in AVIS_BATCH13_FR.keys():
    plain = re.sub(r'<[^>]+>', '', data_existing[slug])
    issues = []
    for label, p in patterns_check:
        n = len(re.findall(p, plain))
        if n > 0:
            issues.append(f"{label}={n}")
            issues_total += n
    flag = "OK" if not issues else "PB " + ", ".join(issues)
    print(f"  {slug:<22} {len(plain.split()):>3}m {flag}")
print(f"\nTotal issues : {issues_total}")
