"""Batch 19 : 19 avis FR Tier 2 Asie centrale + Caucase + Russie + Iran + Mongolie."""
import json

PATH = 'data/avis_annuel.json'

AVIS_BATCH19_FR = {
    # === Asie centrale (6) ===
    "astana:fr": "Astana (renommée brièvement Nur-Sultan 2019-2022 en l'honneur de Nazarbayev puis re-renommée Astana en 2022 après sa chute), capitale du <strong>Kazakhstan</strong> depuis 1997 : 1,3 million d'habitants au cœur des steppes kazakhes à 350m d'altitude. Capitale planifiée intégralement créée ex nihilo (transférée d'Almaty pour des raisons sismiques et géopolitiques), architecture futuriste signée Norman Foster et autres archistars - ville-vitrine du pétrodollar kazakh. <strong>Juillet-août sont mes mois préférés</strong> (8.9/10) : 14-26°C, 26-34% de pluie, c'est l'été continental court. <strong>De juin à août</strong>, c'est la haute saison touristique : 12-26°C, climat sec et chaud. <strong>De décembre à février</strong>, comptez -16/-7°C : froid continental extrême avec vents glaciaux des steppes (parfois -40°C en janvier-février, l'une des capitales les plus froides au monde après Oulan-Bator), peu de tourisme. <strong>De septembre-mai</strong>, températures fluctuant énormément : -16/+21°C selon la saison. <strong>Sites majeurs</strong> (essentiellement architectures contemporaines spectaculaires) : <strong>Bayterek Tower</strong> (97m, signature de la ville construite en 1997 année du transfert de capitale, plate-forme observation 105m avec moulage doré de la main de Nazarbayev pour photo signature), <strong>Khan Shatyr</strong> (\"tente du Khan\", Norman Foster 2010, plus grande tente au monde 150m de haut, mall+jardins+plage tropicale intérieure pour échapper au climat continental), <strong>Pyramide de la Paix et de la Réconciliation</strong> (Norman Foster 2006, 77m, salle de concert pour rassemblements interreligieux), <strong>Mosquée Hazret Sultan</strong> (la plus grande d'Asie centrale 2012, 17 000 places), <strong>Cathédrale orthodoxe russe</strong>, <strong>Quartier de la rive gauche</strong> ultra-moderne. <strong>Excursions</strong> : <strong>Lac Borovoye/Burabay</strong> à 250 km au nord (\"Suisse kazakhe\", paysages lacustres et formations rocheuses, station thermale soviétique). <strong>Logistique</strong> : Astana à 3h en avion de Moscou, vol direct Astana-Paris saisonnier Air Astana. <strong>Tester</strong> beshbarmak (plat national : viande de cheval ou mouton bouillie sur pâtes plates), kazy (saucisse de cheval), kymyz (lait fermenté de jument), shubat (lait fermenté de chamelle), thé noir avec lait, vodka.",

    "bichkek:fr": "Bichkek, capitale du <strong>Kirghizstan</strong> : 1 million d'habitants à 800m d'altitude au pied des <strong>Monts Tian Shan</strong> (5000m visibles depuis la ville), ancienne capitale soviétique de la République kirghize (Frunze 1926-1991, retour au nom historique Bichkek après l'indépendance de l'URSS). Ville la plus accessible et bohème d'Asie centrale (visa gratuit pour Européens 60 jours, atmosphère décontractée). <strong>Juin-août sont mes mois préférés</strong> (8.9-9.3/10) : 16-32°C, 15-23% de pluie, c'est l'été continental. <strong>De mai à septembre</strong>, c'est la haute saison touristique : 12-32°C, climat sec et ensoleillé idéal. <strong>De décembre à février</strong>, comptez -5/3°C et 23-28% de pluie : hiver froid continental, mais ski possible à Karakol et Chimgan voisins. <strong>Sites majeurs</strong> (Bichkek est avant tout une base pour explorer le pays, peu de monuments en eux-mêmes) : <strong>Place Ala-Too</strong> (centre, statue de Manas héros épique national qui a remplacé la statue de Lénine), <strong>Bazar Osh</strong> (immense marché, spécialités d'Asie centrale, fruits secs), <strong>Musée d'Histoire</strong> (\"Lénine Museum\" historiquement, héritage soviétique massif), <strong>Cathédrale Sainte-Résurrection</strong>, <strong>Parc Panfilov</strong>, <strong>Maison Blanche</strong> (Parlement). <strong>Excursions majeures du Kirghizstan</strong> : <strong>Lac Issyk-Köl</strong> à 4h (2e plus grand lac alpin au monde après Titicaca, 6200 km², 700m de profondeur, jamais gelé malgré l'altitude 1600m grâce à sa salinité, plages côté nord à Cholpon-Ata, randonnée côté sud à Karakol), <strong>Vallée de Karakol</strong> et <strong>Pic Lénine</strong> (7134m, l'un des seuls 7000 \"facilement\" accessibles, ascension 3 semaines avec acclimatation), <strong>Pic Khan Tengri</strong> (7010m), <strong>Yourtes des nomades kirghizes</strong> (séjour chez l'habitant en haute pâture jailoo, traite des juments, kymyz lait fermenté), <strong>Song-Köl</strong> (lac d'altitude 3016m, yourtes nomades estivales). <strong>Tester</strong> beshbarmak (plat national à base de cheval ou mouton), laghman (nouilles épaisses sautées), manty (raviolis cuits vapeur), plov (riz pilaf), shashlik (brochettes), kymyz, vodka kirghize.",

    "samarcande:fr": "Samarcande, ville mythique de la <strong>Route de la Soie</strong> en <strong>Ouzbékistan</strong> : 540 000 habitants. <strong>UNESCO 2001</strong> pour son centre historique (\"Samarcande - Carrefour des cultures\"), capitale de l'empire de <strong>Tamerlan</strong> Timur le Boiteux 1370-1405. Patrimoine architectural islamique parmi les plus spectaculaires au monde (mosaïques bleu turquoise et dorure géométriques signature timuride). <strong>Mai et septembre sont mes mois préférés</strong> (9.2-9.3/10) : 14-30°C, 3-25% de pluie, températures idéales avant/après la canicule estivale. <strong>D'avril à mai et septembre-octobre</strong>, ce sont les meilleures saisons : 8-30°C, climat sec idéal. <strong>De juin à août</strong>, c'est la canicule : 19-36°C, 1-5% de pluie (climat continental aride, désert du Kyzyl Kum à proximité). <strong>De novembre à mars</strong>, comptez -1/16°C et 17-39% de pluie : froid continental, neige possible. <strong>Sites majeurs</strong> : <strong>Place du Régistan</strong> (\"l'endroit sablonneux\", l'une des places les plus spectaculaires au monde, ensemble de 3 madrasas du XVe-XVIIe : <strong>Ulugh Beg</strong> 1417, <strong>Sher-Dor</strong> 1636 \"des lions tigres signature\" image-carte postale d'Ouzbékistan, <strong>Tilya-Kori</strong> 1660 \"recouverte d'or\" la plus richement décorée), <strong>Nécropole de Shah-i-Zinda</strong> (avenue funéraire XIIe-XVe siècle, l'un des plus beaux ensembles d'architecture islamique au monde, mausolées avec mosaïques bleues, lieu de pèlerinage), <strong>Mausolée Gour Emir</strong> (\"Tombeau de l'émir\", lieu de sépulture de Tamerlan + ses fils, dôme bleu turquoise de Samarcande typique 38m), <strong>Mosquée Bibi-Khanym</strong> (1399-1404, ancienne plus grande mosquée du monde construite par Tamerlan en l'honneur de sa femme préférée), <strong>Observatoire d'Ulugh Beg</strong> (1429, sextant de 40m découvert en 1908, le petit-fils de Tamerlan a calculé la longueur de l'année astronomique avec une précision moderne). <strong>Excursions</strong> : <strong>Boukhara</strong> à 4h en train (UNESCO, voir avis dédié), <strong>Khiva</strong> à 11h (UNESCO, voir avis dédié), <strong>Tachkent</strong> capitale (déjà couverte). <strong>Tester</strong> plov ouzbek (riz pilaf au mouton, plat national), shashlik, manty, samsa (samosa frit), choucroute karakoum, thé vert chinois.",

    "boukhara:fr": "Boukhara, 2e ville-musée d'<strong>Ouzbékistan</strong> sur la <strong>Route de la Soie</strong> : 280 000 habitants. <strong>UNESCO 1993</strong> pour son centre historique (\"Boukhara - Citadelle sacrée\"), réputée comme la ville la plus traditionnelle d'Asie centrale (140 monuments classés). Berceau de figures islamiques majeures comme Ibn Sina (Avicenne, médecin et philosophe Xe-XIe). <strong>Septembre est mon mois préféré</strong> (9.2/10) : 16-31°C, 0% de pluie, températures idéales après l'été. <strong>De mai et septembre-octobre</strong>, ce sont les meilleures saisons : 8-32°C, climat sec idéal. <strong>De juin à août</strong>, c'est la canicule : 22-40°C (juillet souvent 42°C+), évitez juillet (3.9/10). <strong>De novembre à mars</strong>, comptez -2/15°C et 13-20% de pluie : froid continental, peu de touristes mais charme préservé. <strong>Sites majeurs</strong> : <strong>Citadelle Ark</strong> (forteresse depuis le Ve siècle, dernière résidence des émirs de Boukhara jusqu'en 1920, 80% détruite par bombardement soviétique 1920, partiellement restaurée), <strong>Poï Kalon</strong> (\"piédestal du Grand\", complexe central avec <strong>Minaret Kalon</strong> 47m construit en 1127, l'un des seuls monuments épargnés par Genghis Khan en 1220 \"trop beau pour être détruit\", <strong>Mosquée Kalon</strong> 12 000 places, <strong>Madrasa Mir-i-Arab</strong> XVIe encore en activité), <strong>Madrasa Ulugbek</strong>, <strong>Madrasa Abdul Aziz Khan</strong>, <strong>Lab-i-Hauz</strong> (place centrale autour d'un bassin XVIIe, atmosphère traditionnelle, salons de thé sous mûriers), <strong>Mausolée des Samanides</strong> (Xe siècle, l'un des plus vieux et plus beaux monuments d'Asie centrale, briques cuites sans glaçure formant motifs géométriques, considéré chef-d'œuvre architectural islamique), <strong>Tcharsu</strong> (4 dômes du bazar XVIe-XVIIe : Toki Sarrofon changeurs d'argent, Toki Telpak Furushon vendeurs de bonnets, Toki Zargaron bijoutiers - encore en activité aujourd'hui), <strong>Palais d'été de Sitorai Mokhi-Khosa</strong> à 5 km. <strong>Logistique</strong> : Boukhara à 4h en train rapide depuis Tachkent. <strong>Tester</strong> plov ouzbek, shashlik, manty, samsa, halva, vodka ouzbèke, thé vert.",

    "khiva:fr": "Khiva, 3e ville-musée d'<strong>Ouzbékistan</strong> sur la <strong>Route de la Soie</strong> : 90 000 habitants au cœur du désert de <strong>Kyzyl Kum</strong>, à 35 km de la frontière turkmène. <strong>UNESCO 1990</strong> pour son <strong>Itchan Kala</strong> (vieille ville fortifiée), considérée comme la ville-musée la plus intacte d'Asie centrale (vieille ville entièrement préservée intra-muros, presque comme une scène de cinéma figée XIXe). <strong>Septembre est mon mois préféré</strong> (9.6/10) : 15-28°C, 2% de pluie, températures idéales après la canicule. <strong>De mai et septembre-octobre</strong>, ce sont les meilleures saisons : 8-30°C, 2-13% de pluie. <strong>De juin à août</strong>, c'est la canicule extrême : 22-38°C (juillet 38°C+), évitez juillet (3.9/10). <strong>De novembre à mars</strong>, comptez -3/11°C et 6-13% de pluie : froid continental sec. <strong>Sites majeurs</strong> (presque tous concentrés dans l'Itchan Kala fortifiée 26 hectares, 2 km de remparts en pisé) : <strong>Kalta Minor</strong> (\"minaret court\", 1851, devait être 70m mais resté à 26m car le khan Mohammad Amin est mort avant son achèvement, signature de Khiva avec sa céramique turquoise), <strong>Madrasa Mohammed Amin Khan</strong> (1855, à côté du Kalta Minor, reconvertie en hôtel), <strong>Citadelle Kuhna Ark</strong> (résidence des khans XVIIe), <strong>Mosquée Djouma</strong> (XVIIIe, charpente sur 213 colonnes en bois de l'ormeau noir sculptées, atmosphère hors du temps), <strong>Madrasa Islom-Khoja et son Minaret</strong> (1910, 56m, le plus haut de Khiva, ascension 118 marches étroites, panorama 360°), <strong>Palais Tash Hauli</strong> (1830-1838, harem du khan, 163 chambres, ouvrages bois sculpté et céramique), <strong>Mausolée de Pakhlavan Mahmud</strong> (poète et lutteur 1247-1326, vénéré comme saint local), <strong>Toza Bog Palace</strong>. <strong>Logistique</strong> : Khiva à 11h en train depuis Tachkent (train de nuit), 1h en avion à Urgench voisin + taxi 30 min. Combinaison classique \"Route de la Soie\" : Tachkent + Samarcande + Boukhara + Khiva = 8-10 jours. <strong>Tester</strong> shivit oshi (pâtes vertes à l'aneth signature de Khiva), tukhum-barak (raviolis aux œufs), plov, samsa, thé vert.",

    "achgabat:fr": "Achgabat (Ashgabat), capitale du <strong>Turkménistan</strong> : 1,2 million d'habitants au pied des <strong>Monts Kopet Dag</strong> à la frontière iranienne. Capitale exceptionnellement étrange (régime ultra-autoritaire post-soviétique, culte de la personnalité de Saparmurat Niyazov \"Türkmenbaşy\" 1990-2006 puis Berdimuhamedov, surnommée \"capitale du marbre blanc\" : 543 bâtiments en marbre blanc 4,5 millions de m², record du monde Guinness 2013). Pays parmi les moins ouverts au tourisme (visa très difficile, guide obligatoire, accès limité). <strong>Septembre est mon mois préféré</strong> (9.2/10) : 20-31°C, 1% de pluie, températures idéales après la canicule. <strong>De mai et septembre-octobre</strong>, ce sont les meilleures saisons : 12-31°C, 1-9% de pluie, climat sec idéal. <strong>De juin à août</strong>, c'est la canicule extrême : 24-38°C (juillet 38°C+), totalement déconseillé. <strong>De décembre à février</strong>, comptez 1-11°C : doux. <strong>Sites majeurs</strong> (essentiellement architecture grandiloquente du régime) : <strong>Monument à la Neutralité</strong> (75m, statue dorée du président Türkmenbaşy au sommet qui pivotait pour suivre le soleil jusqu'en 2010 quand elle a été déplacée par son successeur), <strong>Mosquée de Türkmenbaşy Ruhy</strong> (15 km au sud, la plus grande d'Asie centrale, 10 000 places, intérieur entièrement marbre, le Coran et les paroles du \"Ruhnama\" livre du président Niyazov gravés ensemble sur les murs - ce qui a choqué le monde islamique), <strong>Palais présidentiel</strong>, <strong>Yntalanan Yyly</strong> (Wedding Palace bizarre, cube géant 70m surmonté d'un globe terrestre), <strong>Independence Park</strong> (statues massives de héros nationaux), <strong>Quartier de marbre blanc</strong>. <strong>Excursions</strong> : <strong>Cratère de gaz Darvaza</strong> à 270 km dans le désert du Karakoum (\"Porte de l'Enfer\", 70m de diamètre, brûle continuellement depuis 1971 quand des géologues soviétiques ont mis le feu pour brûler les gaz toxiques après effondrement d'un trou de forage - bizarrement encore actif 50 ans après ; spectacle nocturne fantastique, visite organisée 4x4 avec guide depuis Achgabat 5h), <strong>Konye-Urgench</strong> (UNESCO, ruines médiévales), <strong>Nisa</strong> (UNESCO, ruines parthes), <strong>Avaza</strong> (côte caspienne, station balnéaire), <strong>Mary et Merv</strong> (UNESCO, ancienne capitale Seldjoukides). <strong>Tester</strong> plov turkmène, shashlik, dograma (soupe pain-mouton-oignon), gutab (crêpes), thé vert.",

    # === Caucase (3) ===
    "tbilissi:fr": "Tbilissi, capitale de la <strong>Géorgie</strong> : 1,1 million d'habitants à 380m d'altitude dans une vallée du fleuve Mtkvari (Kura) au pied de l'<strong>antique Caucase</strong>. Fondée au Ve siècle par le roi Vakhtang Ier qui aurait découvert les sources thermales locales lors d'une partie de chasse (le faisan tué tomba dans une source d'eau chaude et fut cuit instantanément - origine du nom \"Tbilissi\" = \"chaud\"). Capitale géorgienne aux multiples civilisations : géorgienne, persane, ottomane, russe, soviétique. <strong>Juin est mon mois préféré</strong> (9.0/10) : 18-28°C, 32% de pluie, températures idéales avant la canicule. <strong>De mai à juin et septembre</strong>, ce sont les meilleures saisons : 13-28°C, 16-44% de pluie. <strong>D'août chute à 8.7/10</strong> à cause de la chaleur (21-32°C), <strong>juillet 6.9/10</strong>. <strong>De décembre à mars</strong>, comptez 0-13°C et 17-35% de pluie : froid hivernal continental, neige possible. <strong>Sites majeurs</strong> : <strong>Vieille ville (Old Tbilissi)</strong> (atmosphère unique, balcons en bois sculpté caractéristiques, ruelles tortueuses, ascenseur depuis Rike Park), <strong>Forteresse Narikala</strong> (IVe siècle, panorama signature sur la ville, accessible par téléphérique 2,2 km depuis Rike Park), <strong>Église Metekhi</strong> (XIIIe, sur falaise au-dessus de la rivière, statue équestre du roi Vakhtang Ier), <strong>Cathédrale Sameba</strong> (Sainte-Trinité, 2002-2004, la plus grande cathédrale orthodoxe du Caucase), <strong>Bains soufrés Abanotubani</strong> (\"quartier des bains\", architecture en briques avec dômes, expérience traditionnelle géorgienne avec masseur kissi 30-50€), <strong>Pont de la Paix</strong> (passerelle moderne contemporaine 2010 controversée), <strong>Avenue Roustaveli</strong> (Champs-Élysées géorgiens, opéra, parlement, hôtels grand luxe), <strong>Quartier de Sololaki</strong> (XIXe immeubles bourgeois en cours de gentrification), <strong>Marché de Dezerter Bazaar</strong> (épices, fromages, fruits, vins). <strong>Excursions</strong> : <strong>Mtskheta</strong> à 20 min (UNESCO, ancienne capitale jusqu'au Ve siècle, monastère Jvari et cathédrale Svetitskhoveli), <strong>Kazbegi/Stepantsminda</strong> à 3h (Mont Kazbek 5047m, église de Tsminda Sameba 2170m photo signature de Géorgie sur le balcon de la haute Caucase), <strong>Sighnaghi</strong> à 2h (\"ville de l'amour\", région viticole de Kakhétie, vins en qvevri amphores enterrées méthode 8000 ans UNESCO). <strong>Tester</strong> khinkali (raviolis géorgiens), khachapuri (pain au fromage, particulièrement adjarian en forme de bateau avec œuf au plat), satsivi (poulet sauce noix), tkemali (sauce prune), vins géorgiens (saperavi rouge, rkatsiteli blanc), tchatcha (eau-de-vie de marc).",

    "baku:fr": "Bakou (Bakı), capitale de l'<strong>Azerbaïdjan</strong> : 2,3 millions d'habitants sur la côte caspienne. Surnommée \"Dubaï du Caucase\" depuis le boom pétrolier post-2000 (architectures futuristes Flame Towers + Heydar Aliyev Centre). Géopolitiquement à la croisée de la Russie, de l'Iran et de la Turquie - culture turc-azérie + héritage musulman chiite + influence persane + russification soviétique. <strong>Juin est mon mois préféré</strong> (9.6/10) : 20-29°C, 8% de pluie, températures idéales avant la canicule estivale. <strong>De mai à juin et septembre-octobre</strong>, ce sont les meilleures saisons : 9-29°C, 15-23% de pluie. <strong>De juillet-août chutent à 6.9/10</strong> à cause de la chaleur (23-32°C avec humidité de la Caspienne). <strong>De décembre à mars</strong>, comptez 3-11°C et 20-25% de pluie : doux mais venté (Bakou est l'une des villes les plus venteuses au monde, son nom signifie \"ville des vents\" en persan). <strong>Sites majeurs</strong> : <strong>Vieille ville Içeri Şeher</strong> (UNESCO 2000, fortifiée XIIe-XVe, dédale ruelles), <strong>Tour de la Vierge</strong> (Maiden Tower, XIIe, 28m, mystère architectural - aucune fonction connue, légende de la princesse qui se serait jetée du sommet plutôt que d'épouser son père), <strong>Palais des Shirvanshahs</strong> (UNESCO, XIIIe-XVIe, mausolée et bains), <strong>Heydar Aliyev Centre</strong> (Zaha Hadid 2012, architecture organique signature de l'architecte irako-britannique, expositions, prix Design of the Year 2014), <strong>Flame Towers</strong> (3 tours de 190m en forme de flammes 2012, illuminations LED nocturnes spectaculaires, hôtels Fairmont + résidences + bureaux), <strong>Boulevard maritime</strong> (Bulvar, promenade en bord de Caspienne 16 km, parcs, restaurants), <strong>Musée Azerbaïdjanais des Tapis</strong> (architecture en forme de tapis enroulé), <strong>Marché Yashil Bazar</strong>. <strong>Excursions</strong> : <strong>Yanar Dag</strong> (\"Montagne ardente\" à 25 km, flammes naturelles brûlant continuellement depuis l'antiquité dues aux émanations gaz souterrain, donné le surnom de \"Pays du Feu\" à l'Azerbaïdjan), <strong>Temple du Feu d'Atashgah</strong> (Surakhani, ancien lieu de culte zoroastrien et hindou XVIIe-XIXe, flammes éternelles maintenues par gaz depuis 2007 après tarissement naturel), <strong>Volcans de boue de Gobustan</strong> (UNESCO 2007, plus grande concentration de volcans de boue au monde 350+, gravures rupestres préhistoriques 6000 ans). <strong>Tester</strong> plov azéri (riz pilaf safrané), kebab, dolma (feuilles de vigne farcies), qutab (crêpes), pakhlava (baklava local), tcha (thé) servi en armudu verre tulipe, vins de Shamakhi.",

    "yerevan:fr": "Erevan (Yerevan), capitale de l'<strong>Arménie</strong> : 1 million d'habitants à 990m d'altitude sur le plateau arménien, vue spectaculaire sur le <strong>Mont Ararat</strong> (5137m, sommet sacré pour les Arméniens où se serait posée l'Arche de Noé selon Genèse, paradoxalement situé en territoire turc depuis 1920 - nostalgie permanente). Plus ancienne capitale au monde encore habitée selon datation (forteresse Erebouni 782 av JC, soit 30 ans avant la fondation de Rome). Pays multi-millénaire (1er pays au monde adopta le christianisme comme religion d'État en 301 ap JC). <strong>Juin et septembre sont mes mois préférés</strong> (9.4/10) : 16-30°C, 11-16% de pluie, températures idéales. <strong>De mai et septembre-octobre</strong>, ce sont les meilleures saisons : 10-28°C, 11-40% de pluie. <strong>De juillet-août chutent à 6.9/10</strong> à cause de la chaleur (21-34°C, climat continental). <strong>De décembre à mars</strong>, comptez -4/12°C et 19-35% de pluie : froid sec hivernal, neige possible. <strong>Sites majeurs</strong> : <strong>Place de la République</strong> (cœur de la ville, ensemble architectural néo-arménien soviétique signé Alexandre Tamanian 1924 qui a redessiné Erevan en plan radial concentrique avec immeubles en tuf rose volcanique signature), <strong>Cascade</strong> (escalier monumental 572 marches, jardin de sculptures contemporaines en plein air avec Botero, Lynn Chadwick), <strong>Matenadaran</strong> (\"dépôt aux manuscrits\", l'un des plus importants centres mondiaux de manuscrits anciens, 17 000 manuscrits dont enluminures arméniennes religieuses XIIe-XVe), <strong>Mémorial du Génocide Arménien</strong> (\"Tsitsernakaberd\", obligatoire pour comprendre l'identité arménienne, 1,5 million de morts 1915-1923, négationnisme turc continue à empoisonner la diplomatie), <strong>Cathédrale Saint-Grégoire-l'Illuminateur</strong> (1997-2001, la plus grande cathédrale arménienne au monde), <strong>Marché GUM</strong> (épices, fruits secs), <strong>Brandy Yerevan factory</strong> (Ararat brandy, le brandy préféré de Churchill et Staline). <strong>Excursions</strong> : <strong>Etchmiadzin</strong> à 20 min (UNESCO, siège de l'Église apostolique arménienne 301, équivalent du Vatican), <strong>Garni</strong> à 1h (temple grec-romain Ier siècle, le seul temple gréco-romain encore debout dans l'ex-URSS, restauré dans les 1970s), <strong>Geghard</strong> (UNESCO, monastère médiéval partiellement creusé dans la roche), <strong>Lac Sevan</strong> (1900m d'altitude, plus grand lac alpin du Caucase). <strong>Tester</strong> dolma arménien (feuilles de vigne farcies), khorovats (BBQ traditionnel à la viande d'agneau), lavash (pain plat UNESCO), khash (soupe pieds de bœuf hivernale), Ararat brandy, vins arméniens (Areni - 6100 ans de viticulture, plus vieille cave à vin au monde découverte ici).",

    # === Russie (6) ===
    "sotchi:fr": "Sotchi, station balnéaire russe sur la <strong>côte de la mer Noire</strong> dans le <strong>kraï de Krasnodar</strong> : 410 000 habitants. Climat subtropical humide unique en Russie (le seul du pays), surnommée la \"Riviera russe\". A accueilli les <strong>JO d'hiver de 2014</strong> (les plus chers de l'histoire estimés 50 milliards de $, controverse sur la corruption massive et conditions de travail), Coupe du Monde de Football 2018, F1 jusqu'en 2021 (annulé suite à l'invasion de l'Ukraine). <strong>Août est mon mois préféré</strong> (9.0/10) : 22-28°C, 26% de pluie, mer à 25°C, températures idéales. <strong>De juin à septembre</strong>, c'est la haute saison touristique balnéaire : 18-28°C, mer chaude, plages bondées de Russes (Sotchi est la principale station estivale russe depuis l'ère soviétique). <strong>De décembre à février</strong>, comptez 3-12°C et 43-49% de pluie : hiver doux pour la Russie (parfois 15°C en janvier), mais ski sur les hauteurs voisines à <strong>Krasnaya Polyana</strong> (35 km, 1500-2300m, complexe Rosa Khutor des JO 2014, l'une des stations ski russes les plus modernes). <strong>Sites majeurs Sotchi-ville</strong> : <strong>Promenade en bord de mer</strong>, <strong>Parc Riviera</strong> (depuis 1898, jardin botanique, allée des magnolias), <strong>Cathédrale Saint-Michel-Archange</strong> (1874-1891, néo-byzantine), <strong>Mont Akhun</strong> (663m, tour panoramique 1936), <strong>Dendrarium</strong> (jardin botanique alpin), <strong>Stade olympique Fisht</strong> (Coupe du Monde 2018), <strong>Sochi Park</strong> (parc thématique russe). <strong>Excursions</strong> : <strong>Krasnaya Polyana</strong> à 35 min (ski, randonnée d'été), <strong>Plateau d'Lago-Naki</strong>, <strong>Cascades de Verticulina</strong>, <strong>Caucase</strong> randonnée. <strong>Public</strong> : Sotchi reste une destination essentiellement russe (Européens deviennent rares depuis 2022 sanctions, vols directs UE-Sotchi quasi inexistants), atmosphère post-soviétique nostalgique encore présente. <strong>Tester</strong> shashlik géorgien-russe (héritage culturel proche), khachapuri (pain au fromage géorgien populaire à Sotchi), pelmeni, blinis, vodka.",

    "kazan:fr": "Kazan, capitale de la <strong>République du Tatarstan</strong> en <strong>Russie</strong> : 1,3 million d'habitants à 800 km à l'est de Moscou sur la rive de la <strong>Volga</strong>. Cité multiculturelle unique en Russie : 50% Tatars musulmans + 45% Russes orthodoxes cohabitent en harmonie depuis 5 siècles (modèle d'intégration religieuse mis en avant par les autorités). Capitale historique du Khanat de Kazan (1438-1552 conquête par Ivan le Terrible), 3e ville de Russie pour son importance économique. <strong>Juillet est mon mois préféré</strong> (8.7/10) : 16-25°C, 29% de pluie, c'est l'été continental court. <strong>De juin à août</strong>, c'est la haute saison touristique : 13-25°C, 22-29% de pluie, climat agréable. <strong>De décembre à février</strong>, comptez -13/-5°C et 36-38% de pluie souvent neige (1m+/saison) : hiver continental rigoureux mais charme féerique avec le Kremlin enneigé, marchés de Noël russe-tatar mixte unique. <strong>Sites majeurs</strong> : <strong>Kremlin de Kazan</strong> (UNESCO 2000, ensemble fortifié unique au monde mêlant architecture orthodoxe et musulmane, 16 hectares), <strong>Mosquée Kul Sharif</strong> (dans l'enceinte du Kremlin, 2005, reconstitution moderne de la mosquée détruite par Ivan le Terrible en 1552, 4 minarets de 58m, l'une des plus grandes d'Europe), <strong>Cathédrale de l'Annonciation</strong> (XVIe, à côté de la mosquée, symbole de la cohabitation), <strong>Tour Söyembikä</strong> (XVIIe, tour penchée 58m de la dynastie Söyembikä), <strong>Rue Bauman</strong> (artère piétonne avec bâtiments historiques, restaurants, boutiques), <strong>Lac Kaban</strong> (légende du trésor du khan englouti dans ses eaux), <strong>Quartier des Vieilles Tatar Sloboda</strong> (architecture traditionnelle tatare préservée), <strong>Cathédrale orthodoxe de Saint-Pierre-et-Saint-Paul</strong> (1726). <strong>Excursions</strong> : <strong>Sviyazhsk</strong> (UNESCO 2017, île monastique fondée par Ivan le Terrible 1551 comme base pour conquérir Kazan, accessible par bateau ou route), <strong>Bolghar</strong> (UNESCO 2014, ancienne capitale Bulgares de la Volga IXe-XVe). <strong>Logistique</strong> : Kazan à 1h en avion de Moscou, 11h en train de nuit (Sapsan rapide ou train traditionnel), 2 vols quotidiens. <strong>Tester</strong> chak-chak (dessert tatar miel-frit), echpochmak (chausson triangulaire viande-pomme de terre), peremyach, kystyby, tatar tea avec lait.",

    "vladivostok:fr": "Vladivostok, capitale de l'<strong>Extrême-Orient russe</strong> sur la <strong>mer du Japon</strong> : 600 000 habitants à 9300 km de Moscou (le terminus oriental du Transsibérien le plus long voyage en train continu au monde 6 jours/7 nuits), à 100 km de la frontière chinoise et 700 km de Tokyo. Atmosphère unique \"San Francisco russe\" (collines, baie spectaculaire, ponts suspendus, mélange culturel asiatique-russe). Ville fermée aux étrangers jusqu'en 1992 (base militaire de la flotte du Pacifique). <strong>Juillet est mon mois préféré</strong> (7.7/10) : 18-21°C, 31% de pluie, fin de la saison fraîche océanique. Vladivostok ne dépasse jamais 7.7/10 (climat océanique aux brumes persistantes). <strong>De juin à septembre</strong>, c'est la saison touristique : 12-23°C, 29-49% de précipitations, climat doux estival. <strong>De décembre à février</strong>, comptez -14/-4°C et 6-11% de pluie : froid sec hivernal extrême avec vents glaciaux de Sibérie, mer parfois prise par les glaces (rare). <strong>Sites majeurs</strong> : <strong>Pont du Roi-Russe Russky</strong> (Russky Bridge, 2012, le plus long pont à haubans au monde 1104m d'envergure principal, l'un des symboles de la modernisation russe), <strong>Pont Zolotoï</strong> (\"Pont d'Or\", 2012, sur la baie de la Corne d'Or), <strong>Île Russky</strong> (campus universitaire FEFU 2012, sites APEC Summit 2012 - Vladivostok était autrefois interdite aux étrangers et le sommet APEC 2012 a justifié des investissements infrastructure massifs), <strong>Rue Svetlanskaya</strong> (artère historique principal centre, immeubles XIXe-XXe), <strong>Phare de Tokarevsky</strong> (1904, sur péninsule, lieu de sépulture des chats blancs sauvages locaux), <strong>Funiculaire</strong> (1959, le seul de Russie hors Moscou-Saint-Pétersbourg), <strong>Sous-marin musée S-56</strong> (sous-marin WWII transformé en musée), <strong>Musée Arseniev</strong>. <strong>Excursions</strong> : <strong>Russky Island Aquarium</strong> (l'un des plus grands aquariums au monde 2016), <strong>Plage Shamora</strong> à 30 min (la principale plage urbaine), <strong>Réserve Land of the Leopard</strong> (à 100 km, dernière population mondiale du léopard de l'Amour 100 individus). <strong>Logistique</strong> : Vladivostok à 8h en avion de Moscou, vol direct depuis Séoul/Tokyo/Pékin. Le <strong>Transsibérien</strong> arrive à Vladivostok après 9300 km depuis Moscou (parmi les voyages en train les plus mythiques au monde). <strong>Tester</strong> pelmeni, ukha (soupe de poisson), poisson cru et sushis (influence japonaise et coréenne forte), saumon de Sakhaline, vodka.",

    "novossibirsk:fr": "Novossibirsk, 3e ville de <strong>Russie</strong> et capitale de la <strong>Sibérie</strong> : 1,6 million d'habitants à 3300 km à l'est de Moscou sur le fleuve <strong>Ob</strong>, sur la ligne du Transsibérien. Ville jeune (fondée en 1893 lors de la construction du Transsibérien), surnommée \"Capitale scientifique de Sibérie\" grâce à <strong>Akademgorodok</strong> (\"Cité des Académiciens\" 1957, complexe scientifique soviétique avec 35 instituts de recherche). <strong>Juin-juillet sont mes mois préférés</strong> (8.3-8.5/10) : 12-24°C, 32-39% de pluie, c'est l'été continental court. <strong>De juin à août</strong>, c'est la haute saison touristique : 6-24°C, 31-39% de pluie, climat doux. <strong>De décembre à février</strong>, comptez -19/-10°C et 25-41% de précipitations souvent neige : hiver continental sibérien extrême (parfois -40°C, blizzard). <strong>Sites majeurs</strong> : <strong>Théâtre d'Opéra et de Ballet</strong> (1945, le plus grand théâtre opéra de Russie, plus grand qu'au Bolchoï de Moscou ou au Mariinsky de Saint-Pétersbourg, 1700 places, dôme caractéristique), <strong>Cathédrale de l'Ascension</strong>, <strong>Place Lénine</strong> (avec statue de Lénine et bronze de Staline), <strong>Pont du Métro</strong> (le plus long pont métro au monde 2145m, connecte les 2 rives de l'Ob), <strong>Akademgorodok</strong> (à 30 km au sud, université d'État de Novossibirsk NSU, instituts de recherche en mathématiques, physique nucléaire, géologie, archéologie), <strong>Musée du Transsibérien et des Chemins de Fer</strong>, <strong>Zoo de Novossibirsk</strong> (l'un des plus grands de Russie). <strong>Excursions</strong> : <strong>Tomsk</strong> à 4h (ancienne capitale historique XIXe avec architecture en bois unique), <strong>Lac Karakol</strong> dans l'Altaï à 8h (lac d'altitude paradisiaque), <strong>Belokurikha</strong> (station thermale soviétique), <strong>Téléski Sheregesh</strong> à 5h dans les monts Kuznetsk Alatau (la principale station ski de Sibérie occidentale). <strong>Logistique</strong> : Novossibirsk à 4h en avion de Moscou, 50h en train (le 3e arrêt important du Transsibérien Moscou-Vladivostok après Iekaterinbourg), aéroport Tolmatchovo. <strong>Tester</strong> pelmeni sibériens (origine probable de Sibérie), pirogues, ukha sibérienne (soupe poisson de l'Ob), bortsch, vareniki, omul (poisson endémique du lac Baïkal), vodka, kvass.",

    "irkoutsk:fr": "Irkoutsk, ville sibérienne sur le <strong>fleuve Angara</strong> à 70 km du <strong>lac Baïkal</strong> : 620 000 habitants à 5000 km à l'est de Moscou. Surnommée le \"Paris de la Sibérie\" au XIXe siècle (architecture en bois sculpté caractéristique préservée, théâtres). Ancienne ville d'exil pour les <strong>Décembristes</strong> (officiers nobles révoltés en décembre 1825 contre le tsar Nicolas Ier, exilés ici avec leurs femmes - les épouses ont apporté la culture salonnière européenne en Sibérie). Base d'accès au <strong>lac Baïkal</strong>. <strong>Juin-juillet sont mes mois préférés</strong> (8.2/10) : 11-25°C, 34-36% de pluie, c'est l'été continental court. <strong>De juin à août</strong>, c'est la haute saison touristique pour le Baïkal : 6-25°C, 32-36% de pluie, climat agréable. <strong>De décembre à février</strong>, comptez -23/-10°C et 8-15% de pluie : hiver continental sibérien extrême (parfois -45°C en janvier), mais le <strong>Baïkal entièrement gelé</strong> permet expéditions sur la glace bleue cristalline (épaisseur 1m+) en mars - phénomène spectaculaire unique au monde. <strong>Sites majeurs Irkoutsk</strong> : <strong>Maisons en bois sculpté du XIXe</strong> (quartier 130 Kvartal entièrement reconstruit-restauré 2011, atmosphère traditionnelle), <strong>Maison-musée des Décembristes Volkonsky et Trubetskoy</strong> (poignants mémoriaux des familles d'exil), <strong>Cathédrale de l'Épiphanie</strong> (XVIIIe, baroque sibérien), <strong>Église polonaise</strong> (Polish Catholic Church, héritage des exilés polonais en Sibérie), <strong>Marché central</strong> (fruits secs, omul fumé), <strong>Promenade en bord de l'Angara</strong>. <strong>LE site majeur : <strong>Lac Baïkal</strong></strong> à 70 km à l'est : <strong>plus profond lac au monde</strong> 1642m, <strong>plus vieux lac au monde</strong> 25 millions d'années, <strong>20% des eaux douces de surface mondiales</strong>, UNESCO 1996, faune endémique unique (phoque nerpa = seul phoque d'eau douce au monde, omul). 2 bases principales : <strong>Listvyanka</strong> à 70 km (la plus accessible, museum baïkalien, marché aux poissons fumés), <strong>Île d'Olkhon</strong> à 5h en bus + ferry (la plus grande île du lac, paysages chamaniques bouriates, rocher signature Shamanka), <strong>Bolshie Koty</strong> (randonnée Grand Trail Baïkalskaya). <strong>Logistique</strong> : Irkoutsk à 6h en avion de Moscou, 78h en train Transsibérien depuis Moscou. <strong>Tester</strong> omul fumé du Baïkal (poisson endémique, à acheter en sortie de fumoirs traditionnels à Listvyanka), pelmeni sibériens, vareniki, sagudaï (sashimi sibérien d'omul), pinia (boisson cèdre).",

    "ekaterinbourg:fr": "Iekaterinbourg (Yekaterinburg), 4e ville de <strong>Russie</strong> sur le versant asiatique de l'<strong>Oural</strong> (frontière naturelle Europe-Asie, monument-obélisque à 30 km de la ville matérialise cette frontière) : 1,5 million d'habitants. Capitale historique de l'industrie minière et métallurgique russe depuis Pierre le Grand (1723). Tristement célèbre pour le <strong>massacre de la famille impériale Romanov</strong> dans la nuit du 16-17 juillet 1918 par les bolchéviks (Tsar Nicolas II + sa femme + leurs 5 enfants + 4 servants exécutés au sous-sol de la maison Ipatiev, démolie en 1977 par Boris Eltsine alors premier secrétaire du Parti à Sverdlovsk - ironie de l'histoire). <strong>Juillet est mon mois préféré</strong> (8.2/10) : 14-23°C, 37% de pluie, c'est l'été continental court. <strong>De juin à août</strong>, c'est la haute saison touristique : 11-23°C, 28-40% de pluie. <strong>De décembre à février</strong>, comptez -16/-8°C et 17-20% de pluie souvent neige : hiver continental rigoureux. <strong>Sites majeurs</strong> : <strong>Église-sur-le-Sang-Versé</strong> (Khram-na-Krovi, 2003, néo-byzantine construite à l'emplacement de la maison Ipatiev où les Romanov furent assassinés, lieu de pèlerinage orthodoxe et impérial), <strong>Monastère Ganina Yama</strong> (à 15 km, complexe de 7 chapelles construit en 2000 à l'endroit où les corps des Romanov furent jetés dans une mine - canonisés \"saints porte-passion\" par l'Église orthodoxe russe en 2000, devenus icônes du nationalisme russe contemporain), <strong>Place de 1905</strong> (centre, monument à Lénine), <strong>Boris Eltsine Centre</strong> (musée moderne 2015 dédié au 1er président de la Russie post-soviétique 1991-1999, controversé car raconte l'effondrement de l'URSS du point de vue eltsinien), <strong>Vysotsky Skyscraper</strong> (188m, observation deck panoramique), <strong>Cathédrale Saint-Jean-le-Précurseur</strong>, <strong>Quartier littéraire</strong>, <strong>Monument du clavier d'ordinateur</strong> (sculpture humoristique 2005). <strong>Excursions</strong> : <strong>Frontière Europe-Asie</strong> à 30 km (obélisque, photo signature pieds dans 2 continents), <strong>Réserve Olen'i Ruchi</strong> (\"ruisseaux des cerfs\", 100 km au nord, paysages oural taïga), <strong>Verkhoturye</strong> à 4h (\"Jérusalem orthodoxe de l'Oural\"). <strong>Logistique</strong> : Iekaterinbourg à 2h en avion de Moscou, 26h en train Transsibérien (1er grand arrêt après Moscou), aéroport Koltsovo. <strong>Tester</strong> pelmeni de l'Oural (origine régionale revendiquée), shashlik, draniki, blinis, kvas, vodka.",

    # === Iran (2) ===
    "teheran:fr": "Téhéran, capitale de l'<strong>Iran</strong> : 9 millions d'habitants (15 millions en aire urbaine) à 1200m d'altitude au pied des <strong>Monts Elbourz</strong> (sommet Damavand 5610m, plus haut volcan d'Asie). Capitale depuis 1796 sous la dynastie Qadjar. Mégapole moderne aux contradictions saisissantes : régime théocratique conservateur depuis 1979 (Révolution islamique) face à une jeunesse urbaine éduquée (60% de la population a moins de 35 ans, contestations régulières). Tourisme limité depuis sanctions internationales (visa accessible mais sentiment occidental d'aller en pays \"interdit\"). <strong>Mai est mon mois préféré</strong> (9.2/10) : 17-30°C, 13% de pluie, températures idéales avant la canicule. <strong>D'avril-mai et septembre-octobre</strong>, ce sont les meilleures saisons : 12-32°C, 1-22% de pluie. <strong>De juin à août</strong>, c'est la canicule extrême : 23-38°C (parfois 42°C), pollution atmosphérique étouffante (Téhéran est l'une des villes les plus polluées au monde, smog persistant en hiver également). <strong>De décembre à février</strong>, comptez 0-11°C et 18-26% de pluie : froid sec, neige possible, ski sur les hauteurs voisines à <strong>Dizin</strong> et <strong>Shemshak</strong> (50 min de Téhéran, 3600m d'altitude, parmi les meilleures stations ski du Moyen-Orient). <strong>Sites majeurs</strong> : <strong>Palais du Golestan</strong> (UNESCO 2013, ancienne résidence Qadjar XIXe, 17 monuments dans un jardin persan, mosaïques signatures), <strong>Palais Saadabad</strong> (au nord dans les hauteurs, ancienne résidence d'été du shah), <strong>Palais Niavaran</strong> (dernière résidence du shah Mohammad Reza Pahlavi avant l'exil 1979), <strong>Trésor des Joyaux Nationaux</strong> (sous la Banque Centrale, l'une des plus impressionnantes collections de bijoux royaux au monde : trône de paons en or 26000 pierres précieuses, diamant Darya-ye Noor 182 carats l'un des plus gros diamants roses au monde), <strong>Bazar de Téhéran</strong> (le plus grand bazar couvert au monde 10 km de ruelles), <strong>Musée National Archéologique</strong> (collections perse antique et achéménide), <strong>Tour Azadi</strong> (\"Liberté\", 1971 commémorant 2500 ans d'empire perse), <strong>Tour Milad</strong> (435m, 6e tour la plus haute au monde 2008), <strong>Quartier de Tajrish</strong> au nord (chic et moderne, restos et cafés). <strong>Excursions</strong> : <strong>Mont Damavand</strong> (5610m, ascension 3 jours), <strong>Caspienne</strong> à 3h, <strong>Qom</strong> ville sainte chiite à 2h, <strong>Ispahan</strong> à 5h en bus (UNESCO, voir avis dédié). <strong>Tester</strong> chelo kabab (riz safrané + brochettes), ghormeh sabzi, fessenjan (poulet sauce noix-grenade), sangak (pain), thé persan tchaï, doogh (yaourt salé pétillant).",

    "ispahan:fr": "Ispahan (Esfahan), ville historique d'<strong>Iran</strong> : 2,2 millions d'habitants à 1590m d'altitude au cœur du plateau iranien. Capitale de l'empire safavide sous Shah Abbas Ier (1598-1629), apogée artistique et architectural de la civilisation persane. Le proverbe persan dit \"Ispahan moitié du monde\" (\"Esfahan, nesf-e jahan\") tellement elle était considérée comme spectaculaire au XVIIe siècle. <strong>Mai est mon mois préféré</strong> (9.4/10) : 15-30°C, 7% de pluie, températures idéales avant la canicule. <strong>D'avril-mai et septembre-octobre</strong>, ce sont les meilleures saisons : 4-33°C, 0-18% de pluie, climat sec idéal. <strong>De juin à août</strong>, c'est la canicule : 20-38°C (juillet 38°C+), évitez juillet (3.8/10). <strong>De décembre à février</strong>, comptez -3/14°C et 11-15% de pluie : doux journée, frais nuit, neige possible. <strong>Sites majeurs</strong> : <strong>Place Naghsh-e Jahan</strong> (\"Image du Monde\", UNESCO 1979, l'une des plus grandes places au monde 89 000 m² 510×165m, conçue par Shah Abbas I 1598-1629, 4 monuments majeurs sur ses côtés - photo signature des voyages en Iran), <strong>Mosquée du Shah / Mosquée de l'Imam</strong> (côté sud de la place, 1611-1638, considérée chef-d'œuvre de l'architecture islamique mondiale, dôme bleu turquoise 54m de hauteur, mosaïques 7 couleurs uniques au monde, écho parfait sous le dôme central), <strong>Mosquée Sheikh Lotfollah</strong> (côté est, 1602-1619, mosquée privée des femmes du harem royal, sans minaret ni cour, dôme couleur sable rosée changeante au coucher du soleil), <strong>Palais Ali Qapu</strong> (côté ouest, 1597, terrasse-balcon où le shah recevait les ambassadeurs étrangers), <strong>Bazar Qeysarieh</strong> (côté nord), <strong>Mosquée Jameh / Mosquée du Vendredi</strong> (UNESCO 2012, à 2 km, couvre 1300 ans d'évolution architecturale islamique du VIIIe au XVIIIe siècle, l'une des plus anciennes mosquées d'Iran), <strong>Pont Khaju</strong> (1650, 24 arches au-dessus de la rivière Zayandeh, atmosphère unique au coucher du soleil avec chants traditionnels en sous-arche), <strong>Pont Si-o-se Pol</strong> (\"33 arches\", 1602, 298m, plus long pont du genre au monde), <strong>Cathédrale Vank</strong> (à Jolfa quartier arménien, 1655, cathédrale arménienne apostolique avec fresques bibliques uniques mêlant influences perses et européennes). <strong>Tester</strong> beryani esfahani (plat local, agneau effiloché et pain plat), faloodeh (sorbet), gaz (nougat persan, signature ispahane), sohan (caramel safran-pistache), thé persan tchaï.",

    # === Mongolie (1) ===
    "mongolie:fr": "La Mongolie, pays enclavé entre <strong>Russie au nord</strong> et <strong>Chine au sud</strong> : 3,4 millions d'habitants sur 1 564 116 km² (densité parmi les plus faibles au monde, 2 hab/km²). Capitale <strong>Oulan-Bator</strong>, l'une des plus froides au monde. 30% de la population reste nomade en yourtes (ger), pratique l'élevage extensif (moutons, chèvres, chevaux, yaks, chameaux de Bactriane). Berceau de l'<strong>empire mongol de Gengis Khan</strong> (XIIIe siècle, plus grand empire continental de l'histoire). <strong>Juin-août sont mes mois préférés</strong> (8.1-8.5/10) : 9-25°C, 31-40% de pluie, c'est l'été continental court. <strong>De juin à septembre</strong>, c'est la haute saison touristique : 4-25°C, climat clément, paysages verts (\"saison des fleurs\"), <strong>Naadam Festival</strong> mi-juillet (3 jours de tir à l'arc + lutte traditionnelle bökh + courses de chevaux d'enfants 30 km, fête nationale UNESCO patrimoine immatériel 2010). <strong>De décembre à février</strong>, comptez -23/-9°C et 2-7% de pluie souvent neige : hiver continental extrême (parfois -40°C, -50°C dans les zones reculées, blizzard, dzud catastrophes climatiques tuant millions de bétail). <strong>Régions à connaître</strong> : <strong>Désert de Gobi</strong> au sud (1,3 million de km², chameaux de Bactriane à 2 bosses, dunes de sable Khongor 100m, oasis Yolyn Am gorge glacée même en été, fossiles dinosaures découverts par Roy Chapman Andrews dans les 1920s ont inspiré Indiana Jones), <strong>Vallée de l'Orkhon</strong> (UNESCO 2004, vallée historique des empereurs mongols, ancienne capitale Karakorum XIIIe siècle aujourd'hui ruinée), <strong>Lac Khövsgöl</strong> (\"Mère Mongolie\" ou \"Perle Bleue\", 2e plus grand lac de Mongolie, 2% des eaux douces mondiales, eaux pures, peuple Tsaatan éleveur de rennes au nord), <strong>Steppes mongoles</strong> centrale (paysages infinis, séjour chez l'habitant nomade en yourte = expérience signature de Mongolie), <strong>Parc national de Terelj</strong> à 70 km d'Oulan-Bator (\"Mongolie facile\", paysages spectaculaires Turtle Rock, statue équestre géante de Gengis Khan 40m la plus grande statue équestre au monde 2008), <strong>Monastère Erdene Zuu</strong> à Karakorum (le plus ancien monastère bouddhiste de Mongolie 1585), <strong>Oulan-Bator</strong> (capitale, déjà couverte). <strong>Tester</strong> khorkhog (mouton cuit avec pierres chaudes dans contenant métallique, plat traditionnel nomade), buuz (raviolis cuits vapeur, équivalent mongol des dim sum), khuushuur (chausson frit), aïrag (lait fermenté de jument, alcoolisé), suutei tsai (thé au lait salé), vodka mongole Chinggis (du nom de Gengis Khan).",

    # === Bonus station ski Caucase (1) ===
    "bakuriani:fr": "Bakouriani (Bakuriani), station ski et villégiature en <strong>Géorgie</strong> dans la région de Samtskhe-Javakheti : 2500 habitants à <strong>1700m d'altitude</strong> sur le versant nord du <strong>Petit Caucase</strong>. L'une des plus anciennes stations ski post-soviétiques de Géorgie (créée à l'époque soviétique pour la nomenklatura), récemment modernisée. A accueilli les <strong>Championnats du Monde Junior de ski alpin 2023</strong>. <strong>Août est mon mois préféré</strong> (8.3/10) : 12-22°C, 36% de pluie, c'est l'été clément en altitude (échappatoire à la chaleur de Tbilissi à 200 km en bas). <strong>De juin à septembre</strong>, c'est la haute saison estivale : 8-22°C, randonnée, VTT, balades à cheval. <strong>De décembre à mars</strong>, c'est la haute saison ski : -8/4°C, 35-52% de pluie souvent neige (3-4m/saison, neige soufflée par les vents du Caucase). <strong>Pistes Bakuriani</strong> : 4 zones reliées (Didveli, Kokhta, Mitarbi, Tatra), 30 km de pistes balisées, 6 remontées modernes (télésièges débrayables), altitude 1700-2700m, dénivelé 1000m, terrain idéal débutants-intermédiaires, beaucoup d'espace freeride hors-piste. Tarifs ski 30-50€/jour (parmi les moins chers d'Europe). <strong>Public</strong> : essentiellement Géorgiens (école nationale de ski), Russes en hivernage hors-saison, Israéliens nombreux (vol direct depuis Tel Aviv), de plus en plus d'Européens à la recherche d'alternatives bon marché aux Alpes. <strong>Sites locaux</strong> : <strong>Forêt Bakuriani</strong> (épicéas), <strong>Mont Sakvelo</strong> (3001m, randonnée d'été), <strong>Lac Tabatskuri</strong> à 30 min (lac d'altitude 2000m, baignade en juillet-août), <strong>Borjomi</strong> à 30 min (station thermale légendaire géorgienne, source d'eau minérale Borjomi exportée mondialement, parc d'État Borjomi-Kharagauli National Park - le plus grand parc d'Europe). <strong>Logistique</strong> : Bakuriani à 3h de Tbilissi en voiture/marshrutka (route panoramique vers Borjomi puis montée 30 km en lacets), train historique \"Kukushka\" depuis Borjomi 2h sur ligne étroite 1899 = expérience nostalgique unique au monde. <strong>Tester</strong> khinkali géorgiens fumants après ski (raviolis 18 plis spécialité de Bakouriani), khachapuri, gomi (polenta), satsivi, vins géorgiens, tchatcha (eau-de-vie locale, idéale grog d'après-ski)."
}

with open(PATH, encoding='utf-8') as f:
    data_existing = json.load(f)

before = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

data_existing['_version'] = '2.9'
data_existing['_updated'] = '2026-04-28'

for k, v in AVIS_BATCH19_FR.items():
    data_existing[k] = v

after = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data_existing, f, ensure_ascii=False, indent=2)

print(f"Avis FR avant : {before}")
print(f"Avis FR après : {after}")
print(f"Nouveaux : {after - before}")

# Audit immédiat
import re
patterns_check = [
    ('em-dash', r'—'), ('guillemets', r'[«»]'),
    ('attendez-vous', r'attendez-vous à'),
    ('parfait', r'\bparfait[es]*\b'),
    ('fenêtre', r'\bfenêtre[s]?\b'),
    ('saturé', r'\bsatur[eéa]\w*\b'),
    ('se mérite', r'\bse méri[tes]+\b'),
    ('magique', r'\bmagiques?\b'),
    ('Si vous X:', r'Si vous \w+ : '),
    ('iconique', r'\biconique[s]?\b'),
    ('antithèse', r'antithèse'),
    ('mythique', r'\bmythique[s]?\b'),
    ('emblématique', r'\bemblématique[s]?\b'),
    ('authentique', r'\bauthentique[s]?\b'),
    ('féérique', r'\bféérique[s]?\b'),
    ("c'est aussi", r"[Cc]'est aussi"),
    ('à monitorer', r'à monitorer'),
    ('à éviter', r'à éviter'),
]

print("\n=== Audit batch 19 ===")
issues_total = 0
for slug in AVIS_BATCH19_FR.keys():
    plain = re.sub(r'<[^>]+>', '', data_existing[slug])
    issues = []
    for label, p in patterns_check:
        n = len(re.findall(p, plain))
        if n > 0:
            issues.append(f"{label}={n}")
            issues_total += n
    flag = "OK" if not issues else "PB " + ", ".join(issues)
    print(f"  {slug:<22} {len(plain.split()):>3}m {flag}")
print(f"\nTotal issues : {issues_total}")
