"""
Batch 4 : 29 avis FR Top mondial 91-120.
Application stricte de docs/regles_avis_annuels.md DÈS la rédaction :
- 0 em-dash, 0 guillemets typo, 0 apostrophe courbe
- 0 'attendez-vous à', 0 'parfait', 0 'fenêtre', 0 'sature'
- 0 'magique', 'iconique', 'mythique', 'emblématique', 'authentique', 'féérique'
- 0 'se mérite', 0 'C'est aussi', 0 'antithèse', 0 'Si vous X :'

Tier 4 fallback : mbabane (Eswatini).
Particularité : 27 stations de ski sur 30 -- format 2 saisons (ski hiver / été montagne).
"""
import json

PATH = 'data/avis_annuel.json'
data = json.load(open(PATH, encoding='utf-8'))

AVIS_BATCH4_FR = {
    "bansko:fr": "Bansko, c'est la station de ski la moins chère d'Europe : Bulgarie, Pirin Mountains, prix 30-50% moins élevés que les Alpes. Forfait journée à 30-40€, repas en station à 10-15€. <strong>Juillet est mon mois préféré</strong> (9.3/10) : 14-26°C, 18% de pluie, bon pour les randonnées dans le parc national du Pirin. <strong>De décembre à mars</strong>, comptez -3/8°C : c'est la saison ski, neige garantie grâce à l'altitude (gondola jusqu'à 2600m). Le domaine reste petit (75 km de pistes) mais bien adapté aux familles et débutants. <strong>Festivals jazz et opera</strong> en été dans la vieille ville (architecture Renaissance bulgare des XVIIIe et XIXe siècles). Sofia à 2h30 en bus, Plovdiv à 3h. Vols charter directs depuis Europe en saison ski. Population qui passe de 8000 habitants à 30 000 en haute saison.",

    "sestriere:fr": "Sestrière fait partie de la <strong>Voie Lactée</strong>, un des plus grands domaines transfrontaliers franco-italiens : 400 km de pistes en liaison avec Montgenèvre, Sansicario et Claviere. Hôte des Olympiques d'hiver de Turin 2006. <strong>Juillet-août sont mes mois préférés</strong> (8.0/10) : 6-19°C, 26-30% de pluie en orages d'après-midi, bon pour la randonnée et le VTT. <strong>De décembre à avril</strong>, comptez -11/3°C : saison ski, neige fiable grâce à l'altitude (2035m, l'une des plus hautes stations italiennes). Climat continental sec, pistes orientées principalement nord. <strong>De mai et octobre-novembre</strong>, c'est l'intersaison creuse : station semi-fermée. Turin à 1h30 en voiture, Briançon à 1h via le col du Montgenèvre. La station a vieilli architecturalement, moins charmante que Cortina ou Bormio, mais le ski reste excellent et les forfaits restent abordables.",

    "shimla:fr": "Shimla, capitale de l'Himachal Pradesh, est l'ex-capitale d'été du Raj britannique. À 2200m d'altitude, climat tempéré qui en fait une échappatoire à la chaleur indienne. Le <strong>Kalka-Shimla Railway</strong> (UNESCO) reste le moyen le plus charmant d'arriver. <strong>Mai est mon mois préféré</strong> (8.3/10) : 12-24°C, 43% de pluie, lumière douce sur le Mall et Christ Church. <strong>De juin à août</strong>, c'est la mousson : 56-93% de précipitations, brouillards qui s'accrochent aux pins, glissements de terrain possibles sur la route principale. <strong>De décembre à février</strong>, comptez -1/13°C : possibilité de neige (rare mais photogénique). Beaucoup d'Indiens y vont pour voir la neige pour la première fois. Octobre-novembre restent une excellente saison sèche. Beaucoup de logements coloniaux convertis en heritage hotels (Wildflower Hall, Oberoi Cecil). Comptez 8h depuis Delhi en voiture ou 12h en train.",

    "telluride:fr": "Telluride, c'est l'ex-ville minière du Colorado devenue station de ski isolée et chic : seule la route 145 y mène, pas d'autoroute. Vallée encaissée à 2660m, dominée par les San Juan Mountains. <strong>Juin-juillet sont mes mois préférés</strong> (8.1-8.3/10) : 3-22°C, 30-51% de pluie en orages. Bon pour les festivals (Telluride Film Festival, Bluegrass) et la randonnée vers Bridal Veil Falls (la plus haute du Colorado). <strong>De décembre à mars</strong>, comptez -12/3°C : c'est la saison ski, neige sèche, foules limitées vs Vail ou Aspen, pistes hors-piste accessibles depuis le Gold Hill. <strong>La gondola gratuite</strong> entre la ville et Mountain Village reste l'unique au monde gérée comme transport public. <strong>D'octobre-novembre et avril-mai</strong>, c'est l'intersaison : tout se ferme, météo capricieuse. Vol direct Telluride Regional Airport (peu de fréquences) ou Montrose à 1h30. Hôtels ski-in-ski-out à 500-2000$/nuit en haute saison.",

    "tignes:fr": "Tignes, à 2100m d'altitude, fait partie de l'<strong>Espace Killy</strong> avec Val-d'Isère : 300 km de pistes, glacier de la Grande Motte qui permet le ski d'été (ouvert généralement juin à juillet selon enneigement). <strong>Juillet est mon mois préféré</strong> (7.5/10) : 7-16°C, 42% de pluie, bon pour rando, VTT, lac de Tignes (sports nautiques en altitude). <strong>De décembre à avril</strong>, comptez -11/3°C : c'est la grande saison ski, neige garantie grâce à l'altitude. Le <strong>Tignes Le Lac</strong> est l'épicentre, Val Claret plus moderne, Le Lavachet plus calme. <strong>D'octobre à novembre et mai</strong>, c'est l'intersaison : station fermée. Tignes a une architecture brutaliste des années 60-70 que beaucoup trouvent laide. Pour le charme savoyard, préférer Val-d'Isère voisin (liaison ski). Bourg-Saint-Maurice à 30 min en navette, gare TGV depuis Paris en 4h30 (Eurostar Snow direct depuis Londres en hiver).",

    "vail:fr": "Vail, c'est la plus grande station de ski sous une seule montagne aux États-Unis : 2400 hectares, 7 back bowls (vallées hors-piste de classe mondiale). Style village tyrolien artificiel construit dans les années 60. <strong>Juillet est mon mois préféré</strong> (8.5/10) : 7-24°C, 41% de pluie en orages, bon pour la randonnée vers Booth Falls ou le Vail Pass. <strong>De décembre à mars</strong>, comptez -12/4°C : saison ski culte. Vail Pass peut fermer en cas de tempête (route I-70 vers Denver). Tarifs parmi les plus chers du Colorado : forfait journée 200$+ aux portes, hôtels 500-1500$/nuit. Le passe Epic d'Vail Resorts donne accès à 70+ stations dans le monde. <strong>D'avril à mai et octobre-novembre</strong>, c'est l'intersaison : station semi-fermée. Le village garde une vie culturelle (Vail Dance Festival, Bravo!) en été. Denver à 2h30 de route via I-70 (souvent congestionnée le dimanche après-midi en hiver).",

    "val-thorens:fr": "Val Thorens, c'est <strong>la plus haute station d'Europe</strong> (2300m), au bout des 3 Vallées (600 km de pistes, le plus grand domaine skiable du monde). Neige garantie de novembre à mai. <strong>Juillet est mon mois préféré</strong> (7.4/10) : 6-16°C, 46% de pluie, bon pour la randonnée vers le Lac du Lou ou la Cime Caron (3200m). <strong>De décembre à avril</strong>, comptez -11/3°C : la grande saison ski, accès aux 3 Vallées via les remontées (Méribel et Courchevel à ski). <strong>D'octobre à novembre et mai</strong>, c'est l'intersaison : station fermée. Architecture pure années 70-80 (béton apparent, immeubles ski-in-ski-out), pas de charme savoyard mais service ski parmi les plus fluides au monde. Moûtiers gare TGV à 1h en navette, Eurostar Ski direct Londres en hiver. Population x10 en saison (300 résidents permanents pour 3000+ saisonniers).",

    "breckenridge:fr": "Breckenridge, ex-ville minière du Colorado (1860, ruée vers l'or), garde sa Main Street historique. Station de ski culte avec 5 montagnes à 2900m d'altitude. <strong>Juillet est mon mois préféré</strong> (8.0/10) : 5-21°C, 47% de pluie en orages, randonnée vers les Mohawk Lakes ou le Quandary Peak (4350m, l'un des 14ers les plus accessibles du Colorado). <strong>De décembre à mars</strong>, comptez -16/-2°C : saison ski, neige sèche garantie. Le sommet Imperial Express dépasse 4000m, le plus haut d'Amérique du Nord. <strong>D'avril à mai et octobre-novembre</strong>, c'est l'intersaison : tout se ferme, ville fantôme. Différence vs Vail : Main Street vraiment historique (pas un faux-village), prix légèrement moins fous (forfait à 150-180$). Le passe Epic donne accès. Denver à 2h via I-70, mêmes embouteillages le dimanche soir d'hiver.",

    "jackson-hole:fr": "Jackson Hole, Wyoming, c'est la station de ski extrême par excellence : Corbet's Couloir (entrée par sauts de 3-6m), 50% des pistes black ou double-black diamond. Vallée glaciaire dominée par les Tetons. <strong>Juillet est mon mois préféré</strong> (9.8/10) : 10-27°C, 11% de pluie, accès maximal au <strong>parc national de Grand Teton</strong> et au <strong>parc de Yellowstone</strong> à 1h30 (geysers, Old Faithful, faune). <strong>De décembre à mars</strong>, comptez -12/0°C : saison ski. La Tram (téléphérique) qui monte au Rendezvous Peak (3185m) reste l'expérience signature. Snow King au coeur du village pour les débutants. <strong>D'avril à mai et novembre</strong>, c'est l'intersaison : Yellowstone fermé, station fermée. Hôtels en ville (Wort Hotel, Snow King Resort) plus abordables que les lodges privés à Teton Village (1000-3000$/nuit en haute saison). Vol direct Jackson Hole Airport ou Salt Lake City à 5h de route.",

    "la-plagne:fr": "La Plagne, à 2100m d'altitude, fait partie de <strong>Paradiski</strong> avec Les Arcs : 425 km de pistes, glacier de Bellecôte à 3250m, dénivelé de 1600m skiables. L'une des plus grandes stations françaises en termes de capacité d'accueil. <strong>Juillet-août sont mes mois préférés</strong> (7.4-7.5/10) : 7-17°C, 38-47% de pluie, bon pour la rando et les sports d'eau au Lac de Plagne. <strong>De décembre à avril</strong>, comptez -11/3°C : grande saison ski, neige garantie. <strong>La piste olympique de bobsleigh</strong> (J.O. d'Albertville 1992) reste ouverte au public en hiver. La station regroupe 11 villages (Plagne Centre, Plagne Bellecôte, Plagne Soleil, Belle Plagne, Aime 2000, Plagne Villages, etc.) au design varié. <strong>D'octobre à novembre et mai</strong>, c'est l'intersaison creuse. Aime gare TGV à 30 min en navette, Eurostar Ski depuis Londres en hiver.",

    "lake-louise:fr": "Lake Louise, c'est le lac émeraude d'altitude le plus photographié du Canada : eau turquoise (sédiments glaciaires), Château Lake Louise Fairmont en arrière-plan, glacier Victoria au fond. À 1730m d'altitude dans le parc national de Banff. <strong>Juillet-août sont mes mois préférés</strong> (8.0/10) : 9-20°C, 37-46% de pluie, accès aux randonnées Lake Agnes Tea House, Plain of Six Glaciers, Big Beehive. <strong>De décembre à mars</strong>, comptez -14/0°C : saison ski. Le domaine Lake Louise Ski Resort (4200 hectares) reste l'un des plus grands d'Amérique du Nord. Le lac gèle complètement en hiver pour patiner. <strong>De novembre à mai</strong>, c'est aussi la période des canadian rockies sous neige. Les foules d'été (jusqu'à 15 000 visiteurs/jour au lac) imposent un système de bus payant Parks Canada depuis Banff. Banff town à 50 km au sud, Calgary à 2h en voiture.",

    "les-arcs:fr": "Les Arcs, à 1600-2000m d'altitude, partagent le domaine <strong>Paradiski</strong> avec La Plagne : 425 km de pistes, liaison via le téléphérique Vanoise Express (le plus grand au monde). Architecture signée Charlotte Perriand dans les années 60-70 (lignes pures, intégration au paysage), restée fonctionnelle et pas mal vieillie. <strong>Juillet-août sont mes mois préférés</strong> (7.5-7.6/10) : 6-18°C, 42-49% de pluie, bon pour la randonnée vers l'Aiguille Rouge (3226m, téléphérique d'été). <strong>De décembre à avril</strong>, comptez -11/4°C : grande saison ski, neige garantie. Les 4 stations (Arc 1600, Arc 1800, Arc 1950, Arc 2000) ont chacune leur ambiance. Arc 1950 est la plus récente et la plus chic. <strong>D'octobre à novembre et mai</strong>, c'est l'intersaison creuse. Bourg-Saint-Maurice gare TGV directe depuis Paris (4h30) puis funiculaire d'Arc 1600 en 7 minutes (l'un des plus courts d'Europe).",

    "serre-chevalier:fr": "Serre Chevalier (1200-2800m), c'est le <strong>plus grand domaine du Sud des Alpes</strong> : 250 km de pistes, 4 villages (Briançon, Chantemerle, Villeneuve, Le Monêtier-les-Bains). Climat plus ensoleillé que les Alpes du Nord (Briançon revendique 300 jours/an de soleil). <strong>Juillet-août sont mes mois préférés</strong> (8.5/10) : 9-22°C, 27-35% de pluie, bon pour la randonnée vers le Pic de Rochebrune ou les lacs de Serre-Chevalier. <strong>De décembre à mars</strong>, comptez -9/3°C : saison ski. Climat plus stable que dans les Alpes du Nord (moins de fronts atlantiques). <strong>Briançon</strong> (UNESCO Vauban) reste la base culturelle, plus haute ville d'Europe à 1326m. Les <strong>Grands Bains du Monêtier</strong> (eaux thermales sulfureuses) après une journée de ski. Marseille à 4h en voiture, Turin à 2h via le col du Montgenèvre. Gare TGV Oulx (Italie) en option pour les voyageurs venant de Paris-Lyon.",

    "steamboat-springs:fr": "Steamboat Springs, Colorado, c'est la station ski historique : 1900 m d'altitude, neige légère et abondante (le terme \"<strong>champagne powder</strong>\" a été inventé ici). Vraie ville de 12 000 habitants (pas une station artificielle). <strong>Juillet est mon mois préféré</strong> (9.6/10) : 12-29°C, 11% de pluie, bon pour la randonnée vers Fish Creek Falls et la baignade dans les <strong>hot springs</strong> naturels (Strawberry Park, Old Town Hot Springs). <strong>De décembre à mars</strong>, comptez -10/1°C : saison ski culte. Le domaine Steamboat Resort (1300 hectares) est moins étendu que Vail ou Park City mais la qualité de neige reste réputée parmi les meilleures du monde. <strong>De novembre à avril</strong>, c'est aussi la saison des concerts au Strings Music Festival. Vol direct Yampa Valley Airport (Hayden) à 30 minutes ou Denver à 3h de route via Rabbit Ears Pass.",

    "banff:fr": "Banff, c'est le coeur du <strong>parc national de Banff</strong> dans les Rocheuses canadiennes : 6641 km², lacs glaciaires, faune (ours, élans, mouflons, wapitis). 3 stations de ski accessibles : Sunshine Village, Lake Louise, Mt Norquay. <strong>Juillet-août sont mes mois préférés</strong> (8.4-8.5/10) : 8-22°C, 32-37% de pluie, bon pour Moraine Lake, le Plain of Six Glaciers, la <strong>Icefields Parkway</strong> (route panoramique de 230 km vers Jasper). <strong>De décembre à mars</strong>, comptez -14/-3°C : grande saison ski avec le passe SkiBig3 qui couvre les 3 stations. La ville de Banff (8800 habitants) reste limitée en taille (parc national protégé). <strong>De novembre à mai</strong>, attention au verglas sur la TransCanada Highway 1. Calgary à 1h30 de route, l'aéroport principal. Beaucoup d'hôtels historiques (Banff Springs, Château Lake Louise) au luxe édouardien.",

    "gulmarg:fr": "Gulmarg, dans le <strong>Cachemire indien</strong>, abrite la <strong>plus haute télécabine du monde</strong> : 3979m au sommet du Mont Apharwat. Ski back-country sauvage, peu de pistes balisées. <strong>Septembre est mon mois préféré</strong> (7.3/10) : 8-18°C, 57% de pluie résiduelle de la mousson, fleurs sauvages dans les prairies. <strong>De janvier à mars</strong>, comptez -8/3°C : saison ski. Conditions exceptionnelles pour le freeride (jusqu'à 14m de neige par saison certains hivers), mais les freeriders avertis seulement (pas de patrouille systématique, avalanches fréquentes). <strong>Le contexte sécuritaire du Cachemire</strong> reste à vérifier avant tout voyage : permis spéciaux peuvent être requis selon les périodes, présence militaire visible. Vols depuis Delhi vers Srinagar puis 2h de route. Logement dans des hôtels en bois style chalet, prix abordables (50-150€/nuit). Période d'ouverture variable selon les hivers et la situation politique.",

    "jasna:fr": "Jasna, dans les Basses Tatras slovaques, c'est la plus grande station de ski du pays : 50 km de pistes, sommet Chopok à 2024m. Tarifs parmi les plus bas d'Europe centrale (forfait journée 35-50€). <strong>Août est mon mois préféré</strong> (7.3/10) : 7-16°C, 49% de pluie, bon pour la randonnée dans le parc national des Basses Tatras. <strong>De décembre à mars</strong>, comptez -12/0°C : saison ski. Neige fiable grâce à l'altitude et au climat continental. La station appartient au groupe Tatry Mountain Resorts (qui possède aussi Vysoké Tatry à proximité). <strong>De novembre et avril</strong>, c'est l'intersaison creuse. Bratislava à 4h en voiture, vol direct Poprad-Tatry depuis Cracovie ou Vienne. Idéal pour un week-end ski à petit prix depuis l'Europe de l'Ouest. Cuisine locale (bryndzové halušky : gnocchis au fromage de brebis) à découvrir dans les koliba (chalets traditionnels).",

    "shahdag:fr": "Shahdag, c'est la station de ski récente d'Azerbaïdjan, ouverte en 2012 dans le Caucase à 1900m d'altitude. Ambition : faire du Caucase Sud une destination ski abordable. <strong>Juillet est mon mois préféré</strong> (5.4/10) : 5-13°C, 53% de pluie, climat alpin frais. <strong>De décembre à mars</strong>, comptez -15/-3°C : c'est la saison ski. Domaine encore limité (30 km de pistes) mais en expansion. Forfait journée à 25-35€, hôtels 4-5 étoiles à 80-150€/nuit. <strong>D'avril à novembre</strong>, station quasi déserte hors saison ski. La logistique reste basique : peu de vols directs, il faut généralement passer par Bakou puis 3h de route vers le nord. Population locale azerbaïdjanaise et russe principalement. Pour les voyageurs en quête de ski hors des sentiers battus, à des prix imbattables. Note : nos données climat reflètent les zones d'altitude où l'été reste très frais (climat alpin).",

    "valle-nevado:fr": "Valle Nevado, à 1h30 de Santiago du Chili, c'est la station de ski sud-américaine la plus accessible pour les Européens. Hémisphère sud : ouverte de juin à octobre, idéal pour les Européens qui veulent skier en été. <strong>Janvier-février sont mes mois préférés</strong> (7.5-7.6/10) : 7-16°C, 31-38% de pluie, été austral, bon pour la randonnée d'altitude. <strong>De juin à septembre</strong>, comptez -5/3°C : saison ski. À 3000m d'altitude, exposition Sud (versant froid en hémisphère sud), neige fiable. Le domaine partagé Tres Valles (avec La Parva et El Colorado) atteint 100 km de pistes, le plus grand d'Amérique du Sud. <strong>D'avril à mai et octobre-novembre</strong>, c'est l'intersaison : route fermée aux non-résidents, station fermée. Santiago à 1h30 par route en lacets (50 virages serrés). Comptez 700-1500€ pour 6 jours all-inclusive en saison ski. Mendoza (Argentine) accessible côté est mais col fermé en hiver.",

    "alpe-dhuez:fr": "L'Alpe d'Huez, à 1860m d'altitude dans l'Isère, c'est <strong>la station ensoleillée des Alpes françaises</strong> : 300 jours/an de soleil revendiqués. La <strong>Sarenne</strong> (16 km, 2000m de dénivelé) reste l'une des plus longues pistes noires d'Europe. <strong>Juillet-août sont mes mois préférés</strong> (7.8-7.9/10) : 8-19°C, 35-38% de pluie, célèbre étape du Tour de France (les 21 virages). <strong>De décembre à avril</strong>, comptez -8/3°C : saison ski, neige fiable malgré l'orientation sud-ouest grâce à l'altitude. Le glacier de Sarenne offre du ski d'été certaines années. <strong>De novembre et mai</strong>, c'est l'intersaison. Architecture années 60-70 critiquée (immeubles bétonnés), mais l'avantage du ski-in-ski-out reste réel. Grenoble à 1h30, gare TGV à 2h. La station fait partie du Grand Domaine de l'Alpe d'Huez avec Auris, Vaujany, Oz-en-Oisans (250 km de pistes au total).",

    "andorre:fr": "L'Andorre, micro-État des Pyrénées entre France et Espagne, vit du tourisme ski et du duty-free. 2 grands domaines : <strong>Grandvalira</strong> (210 km de pistes, le plus grand des Pyrénées) et <strong>Vallnord</strong> (90 km). Forfaits 30-40% moins chers que les Alpes. <strong>Juillet-août sont mes mois préférés</strong> (8.9-9.0/10) : 14-26°C, 27-29% de pluie, randonnée dans les vallées d'Ordino et de Sorteny. <strong>De décembre à mars</strong>, comptez -2/10°C en vallée et -10/0°C en altitude : saison ski. Ambiance familiale, beaucoup d'écoles de ski francophones. Les <strong>Caldea</strong> à Andorre-la-Vieille (centre thermal le plus grand d'Europe du Sud) après une journée de ski. <strong>D'octobre à novembre et mai</strong>, c'est l'intersaison. Pas d'aéroport : Toulouse, Barcelone et Lerida (Espagne) en 2-3h de route. Achats détaxés (alcool, parfums, tabac, électronique) qui attirent autant que le ski. Population : 80 000 habitants, 8 millions de visiteurs/an.",

    "big-white:fr": "Big White, en Colombie-Britannique au Canada, c'est la station de ski connue pour la qualité de sa neige : <strong>poudreuse profonde et sèche</strong>, snowghosts (sapins recouverts de givre) sur les sommets. À 1755m d'altitude. Station famille, pas chic comme Whistler. <strong>Juillet est mon mois préféré</strong> (8.3/10) : 7-21°C, 22% de pluie, bon pour le VTT au Big White Bike Park et la randonnée vers Rhonda Lake. <strong>De décembre à mars</strong>, comptez -12/0°C : saison ski culte. La station intégrée (tout est ski-in-ski-out) facilite la vie des familles. Pistes plutôt larges et balisées. <strong>D'avril à novembre</strong>, station semi-fermée. Kelowna à 1h de route, l'aéroport principal. La région d'Okanagan en été (juillet-septembre) compense avec lacs, vignobles et fruits frais. Forfait journée à 100-130 CAD, plus accessible que Whistler ou Banff.",

    "killington:fr": "Killington, dans le Vermont, c'est <strong>la plus grande station de ski de l'Est américain</strong> : 6 montagnes interconnectées, 155 pistes. Saison particulièrement longue (octobre à mai certaines années) grâce à un système de canons à neige avancé. <strong>Juillet est mon mois préféré</strong> (7.7/10) : 11-20°C, 48% de pluie, bon pour la randonnée vers le Killington Peak et Camel's Hump. <strong>De décembre à mars</strong>, comptez -16/-2°C : saison ski. La station accueille la <strong>Coupe du monde de ski alpin féminine fin novembre</strong> (slalom géant Killington Cup), 1ère étape américaine. <strong>D'avril à mai et octobre-novembre</strong>, c'est l'intersaison creuse, sauf début saison Coupe du monde. Vermont en automne (foliage, mi-septembre à mi-octobre) reste une autre raison de venir : couleurs des érables. Boston à 3h de route, NYC à 4h30. Plus accessible aux New-yorkais que les Rocheuses du Colorado.",

    "livigno:fr": "Livigno, vallée alpine italienne reculée près de la frontière suisse, c'est une <strong>zone duty-free</strong> historique (alcool, parfums, essence à -50%). Station ski composée de 2 domaines (Mottolino et Carosello) reliés. <strong>Juillet est mon mois préféré</strong> (7.7/10) : 8-19°C, 47% de pluie, bon pour le VTT (Livigno Bike Park, l'un des meilleurs d'Europe). <strong>De décembre à avril</strong>, comptez -12/2°C : saison ski. Snowparks réputés (Mottolino accueille le X Games Real Snow). <strong>De novembre et mai</strong>, c'est l'intersaison. Accès uniquement par routes de col (Tunnel del Munt la Schera depuis la Suisse en hiver, ou par Bormio depuis l'Italie). Pas de gare de train. Aéroport le plus proche : Milan-Bergame à 4h. La <strong>vallée a accueilli les Olympiques d'hiver de Milan-Cortina en 2026</strong> pour les épreuves freestyle et snowboard. Forfaits ski moins chers que dans les autres stations alpines italiennes.",

    "oukaimeden:fr": "Oukaïmeden, c'est la <strong>plus haute station de ski d'Afrique</strong> : 3268m au sommet, à 75 km de Marrakech (1h30 de route via la vallée de l'Ourika). Domaine modeste (10 km de pistes, 1 télécabine, 6 téléskis) mais expérience unique. <strong>Juillet est mon mois préféré</strong> (8.6/10) : 14-23°C, 28% de pluie, bon pour la randonnée vers le Toubkal (4167m, plus haut sommet d'Afrique du Nord). <strong>De janvier à mars</strong>, comptez -3/7°C en station, neige possible mais aléatoire (certaines saisons sans neige du tout, dépendant des précipitations atlantiques). <strong>D'avril à novembre</strong>, station quasi déserte. Atouts : skier puis dîner couscous le soir à Marrakech, dépaysement total, prix bas (forfait journée 15-20€). Limites : équipement vieillissant, neige incertaine, pas adapté aux skieurs confirmés. Pour les enfants berbères de la vallée, c'est une période de revenus complémentaires (proposent location de luge, cours).",

    "saas-fee:fr": "Saas-Fee, c'est <strong>le \"village des glaciers\" suisse</strong> dans le Valais : 1800m d'altitude, entouré de 13 sommets de plus de 4000m (Dom, Allalinhorn, Täschhorn). Village sans voiture (parking obligatoire à l'entrée). <strong>Juillet est mon mois préféré</strong> (7.6/10) : 9-19°C, 54% de pluie, bon pour la randonnée vers le Mittelallalin (3500m, accessible par funiculaire) et le restaurant tournant Allalin. <strong>De décembre à avril</strong>, comptez -9/2°C : saison ski. Ski d'été permanent sur le glacier du Fee (l'un des rares au monde). <strong>De novembre et mai</strong>, c'est l'intersaison. Architecture chalets traditionnels, contrairement aux stations bétonnées françaises voisines. Population : 1700 résidents permanents. Accès par train depuis Brigue (1h en bus) ou voiture par le tunnel du Saint-Bernard depuis l'Italie. Prix suisses élevés (250-500 CHF/nuit pour un 4 étoiles, forfait journée 80-90 CHF).",

    "val-gardena:fr": "Val Gardena (Gröden en allemand), dans les Dolomites italiennes du Sud-Tyrol, c'est l'une des vallées de ski les plus charmantes des Alpes : 3 villages tyroliens (Ortisei, Santa Cristina, Selva di Val Gardena), liaison Sella Ronda (boucle de 26 km à ski). <strong>Juillet-août sont mes mois préférés</strong> (4.6-4.8/10) : 6-16°C en altitude, 63-65% de pluie, bon pour la randonnée vers les <strong>Tre Cime di Lavaredo</strong> et le Sassolungo. <strong>De décembre à avril</strong>, comptez -11/3°C : grande saison ski, neige fiable grâce à l'altitude et au climat continental dolomitique. La <strong>Coupe du monde Saslong</strong> (descente messieurs) chaque décembre. <strong>De mai et octobre-novembre</strong>, c'est l'intersaison creuse. Sud-tyrolien (langues : ladin, allemand, italien). Cuisine fusion entre tyrolien et italien (canederli, speck, strudel). Bolzano à 30 min, Venise à 3h. Aéroport Innsbruck à 2h30 par route (col du Brenner).",

    "whistler:fr": "Whistler-Blackcomb, c'est <strong>la plus grande station de ski d'Amérique du Nord</strong> : 3300 hectares, 200 pistes, 2 montagnes reliées par le PEAK 2 PEAK Gondola (téléphérique le plus long sans pilier intermédiaire au monde). Hôte des Olympiques d'hiver 2010. <strong>Juillet-août sont mes mois préférés</strong> (8.8/10) : 12-24°C, 24-28% de pluie, bon pour le VTT au Whistler Bike Park (le meilleur du monde) et les randonnées vers Garibaldi Lake. <strong>De décembre à mars</strong>, comptez -3/5°C : saison ski. Climat océanique du Pacifique : neige humide et abondante (jusqu'à 12m par hiver), parfois pluie en bas (vallée à 670m). <strong>De novembre, octobre et mai</strong>, météo très variable, parfois pluvieuse. Vancouver à 2h de route via la Sea-to-Sky Highway (l'une des plus belles routes du monde). La station appartient au passe Epic d'Vail Resorts. Village piéton très bien aménagé, prix élevés (300-800 CAD/nuit en haute saison).",

    "asmara:fr": "Asmara, capitale de l'Érythrée, est inscrite à l'<strong>UNESCO pour son architecture moderniste italienne</strong> des années 1930 : 4000 bâtiments Art déco, Rationalist, Futurist (Cinema Impero, Fiat Tagliero). À 2300m d'altitude, climat doux toute l'année. <strong>Septembre est mon mois préféré</strong> (8.7/10) : 13-24°C, 13% de pluie, fin de la saison des pluies. <strong>De juillet à août</strong>, c'est la saison des pluies : 65-67% de précipitations, journées grises mais températures restent agréables (14-22°C). <strong>De décembre à mai</strong>, ciel généralement dégagé, climat printanier permanent. L'accès à l'Érythrée reste compliqué : visa difficile à obtenir (situation politique tendue avec l'Éthiopie voisine, isolement diplomatique), permis de circuler hors d'Asmara requis, peu d'agences de voyage internationales. Vols via Le Caire, Doha ou Addis-Abeba (quand la frontière est ouverte). Pour les voyageurs préparés, expérience rare et architecture unique en Afrique."
}

print(f"Préparé : {len(AVIS_BATCH4_FR)} avis")

with open(PATH, encoding='utf-8') as f:
    data_existing = json.load(f)

before = len([k for k in data_existing if not k.startswith('_')])

data_existing['_version'] = '1.6'
data_existing['_updated'] = '2026-04-27'

for k, v in AVIS_BATCH4_FR.items():
    data_existing[k] = v

after = len([k for k in data_existing if not k.startswith('_')])

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data_existing, f, ensure_ascii=False, indent=2)

print(f"Avis FR avant : {before}")
print(f"Avis FR après : {after}")
print(f"Nouveaux : {after - before}")

# Audit immédiat patterns LLM
import re
patterns_check = [
    ('em-dash', r'—'),
    ('guillemets', r'[«»]'),
    ('apostrophe courbe', '\u2019'),
    ('attendez-vous', r'attendez-vous à'),
    ('parfait', r'\bparfait[es]*\b'),
    ('fenêtre', r'\bfenêtre[s]?\b'),
    ('saturé', r'\bsatur[eéa]\w*\b'),
    ('se mérite', r'\bse méri[tes]+\b'),
    ('magique', r'\bmagiques?\b'),
    ('Si vous X:', r'Si vous \w+ : '),
    ('iconique', r'\biconique[s]?\b'),
    ('antithèse', r'antithèse'),
    ('mythique', r'\bmythique[s]?\b'),
    ('emblématique', r'\bemblématique[s]?\b'),
    ('authentique', r'\bauthentique[s]?\b'),
    ('féérique', r'\bféérique[s]?\b'),
    ("c'est aussi", r"[Cc]'est aussi"),
    ('à monitorer', r'à monitorer'),
    ('à éviter', r'à éviter'),
]

print("\n=== Audit batch 4 ===")
issues_total = 0
for slug in AVIS_BATCH4_FR.keys():
    plain = re.sub(r'<[^>]+>', '', data_existing[slug])
    issues = []
    for label, p in patterns_check:
        n = len(re.findall(p, plain))
        if n > 0:
            issues.append(f"{label}={n}")
            issues_total += n
    flag = "OK" if not issues else "PB " + ", ".join(issues)
    print(f"  {slug:<28} {len(plain.split()):>3}m {flag}")
print(f"\nTotal issues : {issues_total}")
