"""Batch 10 : 29 avis FR Tier 1 Asie SE + Inde + Japon."""
import json

PATH = 'data/avis_annuel.json'
data = json.load(open(PATH, encoding='utf-8'))

AVIS_BATCH10_FR = {
    "hiroshima:fr": "Hiroshima est l'une des destinations historiques majeures du Japon : la ville reconstruite après le bombardement atomique du 6 août 1945 (140 000 morts à terme). <strong>Mai est mon mois préféré</strong> (8.2/10) : 13-22°C, 30% de pluie, températures clémentes avant la mousson. <strong>De juin à mi-juillet</strong>, c'est le tsuyu (saison des pluies, 46% de précipitations). <strong>Juillet-août chutent à 6.9/10</strong> à cause de la canicule humide (23-31°C). <strong>Septembre-octobre</strong> sont mes vrais bons compromis (8.0-8.1/10) : 14-28°C, ciel dégagé, momiji débute en novembre. <strong>De décembre à février</strong>, comptez 0-11°C : froid sec, ciel souvent dégagé, foules réduites. <strong>Sites majeurs</strong> : <strong>Mémorial de la Paix d'Hiroshima</strong> (UNESCO, ancien Hall de promotion industrielle préservé en ruines), <strong>Musée Mémorial de la Paix</strong> (très éprouvant émotionnellement, témoignages, objets fondus, 200¥), <strong>Parc Mémorial de la Paix</strong> (cénotaphe, dôme), <strong>Château d'Hiroshima</strong> (reconstruit 1958). <strong>Miyajima</strong> à 45 min en train + ferry : <strong>torii flottant</strong> du sanctuaire Itsukushima (UNESCO, image emblématique), daims sacrés, mont Misen accessible en téléphérique. <strong>Tester</strong> okonomiyaki style Hiroshima (différent d'Osaka, en couches), huîtres locales (saison hiver), momiji manjū. À 1h30 d'Osaka en Shinkansen.",

    "okinawa:fr": "Okinawa, archipel subtropical au sud du Japon : 160 îles, 1,5 million d'habitants, culture distincte (royaume des Ryūkyū jusqu'en 1879), bases militaires américaines (75% des bases US au Japon ici). <strong>Octobre-novembre sont mes mois préférés</strong> (8.0-8.2/10) : 21-28°C, 37-45% de pluie, mer encore à 26°C, fin de la saison des typhons. <strong>De juin à septembre</strong>, c'est la saison chaude/humide : 45-75% de précipitations, taux d'humidité oppressant (24-30°C), <strong>typhons fréquents</strong> (une dizaine par saison, peuvent paralyser les ferries inter-îles plusieurs jours). <strong>De décembre à mars</strong>, comptez 15-21°C : doux mais souvent nuageux, mer à 22°C (encore baignable pour les Européens). <strong>Sites majeurs</strong> : <strong>Naha</strong> (capitale, château Shuri ex-palais royal Ryūkyū UNESCO, brûlé en 2019, reconstruction en cours), <strong>Kokusai-dori</strong> (rue commerçante), <strong>Cap Manzamo</strong>. <strong>Iles à explorer</strong> : <strong>Ishigaki</strong> (plage Kabira Bay), <strong>Iriomote</strong> (jungle subtropicale), <strong>Taketomi</strong> (village traditionnel à vélo), <strong>Miyako</strong> (plages parmi les plus belles du Japon). <strong>Plongée</strong> spots mondiaux (Yonaguni avec ses ruines sous-marines mystérieuses). <strong>Tester</strong> sōki soba (nouilles au porc), gōyā champurū (concombre amer sauté), awamori (alcool de riz). Vol direct depuis Tokyo (2h30) ou Osaka (2h).",

    "nikko:fr": "Nikko, à 130 km au nord de Tokyo, c'est le sanctuaire de Tokugawa Ieyasu (fondateur du shogunat Edo) : 100 temples et sanctuaires UNESCO. <strong>Août est mon mois préféré</strong> (7.3/10) : 20-26°C, 90% de pluie, températures clémentes en altitude (Nikko à 600m). <strong>De juin à septembre</strong>, c'est la saison la plus humide (62-90% de précipitations), brouillards fréquents qui rendent les sanctuaires mystérieux. <strong>D'octobre à novembre</strong> est la saison du <strong>momiji</strong> (couleurs d'automne, pic mi-octobre à mi-novembre selon altitude), pic touristique absolu, prix x2-x3. <strong>De décembre à mars</strong>, comptez -5/8°C et 36-49% de précipitations souvent neige : cascades partiellement gelées (Kegon-no-Taki), Lake Chuzenji isolé. <strong>D'avril à mai</strong>, comptez 4-18°C : printemps tardif, derniers cerisiers en altitude. <strong>Sites majeurs</strong> : <strong>Tōshōgū</strong> (sanctuaire le plus orné du Japon, mausolée Ieyasu, sculpture des 3 singes \"ne rien voir, ne rien entendre, ne rien dire\"), <strong>Rinnōji</strong> (3 grands bouddhas), <strong>Futarasan-jinja</strong>, <strong>Pont sacré Shinkyō</strong> (rouge laqué). <strong>Lake Chuzenji</strong> à 1h en bus avec route en lacets (Iroha Zaka, 48 virages = 48 syllabes japonaises), <strong>Kegon Falls</strong> (97m). <strong>Yumoto Onsen</strong> (sources thermales). Excursion journée depuis Tokyo (2h en train) possible mais nuit recommandée.",

    "hakone:fr": "Hakone, à 80 km au sud-ouest de Tokyo, c'est la station thermale la plus connue du Japon : vue sur le Mont Fuji par temps clair, sources chaudes (onsen), lac Ashi. <strong>Août est mon mois préféré</strong> (7.7/10) : 18-24°C, 58% de pluie, températures fraîches en altitude (Hakone à 700m). <strong>Juillet-septembre</strong> sont les mois les plus agréables (7.3-7.7/10) avec 56-62% de précipitations en orages d'après-midi. <strong>De décembre à mars</strong>, comptez -6/7°C : possibilité de neige, Mont Fuji visible plus souvent (ciel sec), onsen sous la neige (expérience marquante). <strong>D'avril à juin</strong>, comptez 3-19°C avec 49-61% de pluie : printemps tardif, brumes fréquentes. <strong>Sites majeurs</strong> : <strong>Hakone Shrine</strong> (torii rouge dans le lac Ashi, photo très instagrammée), <strong>Owakudani</strong> (vallée volcanique, accès parfois fermé selon activité, kuro-tamago œufs noirs cuits dans soufre), <strong>Hakone Open Air Museum</strong> (sculptures dont Picasso), <strong>Hakone Ropeway</strong> (téléphérique), <strong>croisière sur lac Ashi</strong> en bateau pirate. <strong>Hakone Free Pass</strong> (5000-7000¥/2 jours) : transport illimité entre tous les sites + train depuis Tokyo. <strong>Onsen ryokan</strong> : Yamanochaya, Gora Kadan, Hakone Ginyu (200-800€/nuit avec repas). <strong>Tester</strong> kaiseki ryori dans ryokan, soba locales. Excursion journée depuis Tokyo possible (1h30 en train Romance Car) mais 1 nuit en ryokan recommandée pour l'expérience onsen complète.",

    "nara:fr": "Nara fut la première capitale fixe du Japon (710-784) avant Kyoto : 350 000 habitants, 8 sites UNESCO, daims sacrés en liberté (1300 cerfs sika dans le parc). <strong>Mai est mon mois préféré</strong> (8.1/10) : 13-24°C, 39% de pluie, températures parfaites avant la mousson. <strong>De juin à mi-juillet</strong>, c'est le tsuyu (saison des pluies). <strong>Juillet-août chutent à 6.9/10</strong> à cause de la canicule humide (23-32°C). <strong>D'octobre à novembre</strong>, momiji possible, 14-22°C, ciel dégagé. <strong>De décembre à février</strong>, comptez 0-11°C : froid sec, parc Nara désertique, daims plus calmes. <strong>Sites majeurs</strong> : <strong>Tōdai-ji</strong> (Daibutsu = Grand Bouddha de bronze 15m, l'une des plus grandes statues bouddhistes au monde, le bâtiment lui-même est l'une des plus grandes structures en bois du monde), <strong>Kasuga Taisha</strong> (3000 lanternes en pierre et bronze, illuminées 2 fois par an au Mantoro en février et août), <strong>Kōfuku-ji</strong> (pagode 50m, 2e plus haute du Japon), <strong>Hōryū-ji</strong> à 30 min (UNESCO, plus vieux bâtiments en bois debout au monde, 607 ap JC), <strong>Nara Park</strong> (cerfs vénérés comme messagers des dieux, biscuits shika senbei en vente, attention ils peuvent être insistants). <strong>Naramachi</strong> (vieille ville commerçante). <strong>Tester</strong> kakinoha-zushi (sushi enveloppé dans feuille de kaki), narazuke (légumes au saké). Excursion journée depuis Kyoto (45 min en train) ou Osaka (35 min) très facile.",

    "sapporo:fr": "Sapporo est la 5e ville du Japon : capitale d'Hokkaido, 1,9 million d'habitants, ville moderne en damier (rare au Japon), bière éponyme. <strong>Juillet est mon mois préféré</strong> (8.2/10) : 18-25°C, 40% de pluie, températures parfaites quand le reste du Japon est étouffant, festivals (Sapporo Summer Festival fin juillet, Sapporo Bon Odori août). <strong>De décembre à mars</strong>, comptez -10/4°C et 40-52% de précipitations (souvent neige abondante, Sapporo reçoit 5m de neige/an, parmi les plus enneigées au monde) : c'est la saison du <strong>Sapporo Snow Festival</strong> (1ère semaine de février, Odori Park, sculptures de glace géantes, 2 millions de visiteurs), du ski à Niseko (2h en bus), Furano (2h30) ou plus proche Teine (1h). <strong>Sites majeurs</strong> : <strong>Tour de l'horloge</strong> (1878, symbole de la ville), <strong>Mont Moiwa</strong> (téléphérique pour la vue sur la ville la nuit, parmi les 3 meilleurs panoramas nocturnes du Japon avec Hakodate et Nagasaki), <strong>Susukino</strong> (quartier divertissement), <strong>Hokkaido University</strong> (campus historique avec route en peuplier), <strong>Otaru</strong> à 30 min (canal romantique, verrerie). <strong>Tester</strong> ramen miso style Sapporo (chez Sumire ou Aji no Sanpei), <strong>Genghis Khan</strong> (mouton grillé, plat local), bière Sapporo (musée et brasserie visitables). Vol direct Tokyo-Sapporo en 1h30, train Hokkaido Shinkansen (4h depuis Tokyo).",

    "fukuoka:fr": "Fukuoka, 5e ville du Japon par taille, capitale économique de Kyushu : 1,6 million d'habitants, climat plus doux que le Honshu, base pour explorer le sud. <strong>Mai est mon mois préféré</strong> (8.0/10) : 15-23°C, 37% de pluie, températures parfaites avant la mousson, derniers cerisiers (sakura mi-mars à début avril). <strong>De juin à mi-juillet</strong>, c'est le tsuyu. <strong>Juillet-août chutent à 6.9/10</strong> à cause de la canicule humide (24-32°C). <strong>D'octobre à novembre</strong>, comptez 10-22°C avec 28-36% de pluie : ciel dégagé, momiji. <strong>De décembre à février</strong>, comptez 3-11°C : doux pour le Japon (climat plus subtropical), neige rare. <strong>Sites majeurs</strong> : <strong>Ōhori Park</strong> (étang central, jardin japonais), <strong>Fukuoka Castle</strong> (ruines, Maizuru Park), <strong>Kushida Shrine</strong>, <strong>Canal City Hakata</strong> (centre commercial). <strong>Yatai</strong> = stands de rue caractéristiques de Fukuoka, ouverts le soir le long de la rivière Naka et à Tenjin (150 stands), spécialité de la ville. <strong>Excursions</strong> : <strong>Dazaifu</strong> à 30 min (sanctuaire Tenmangu pour les étudiants), <strong>Yufuin</strong> à 2h (onsen village au pied du Yufu), <strong>Beppu</strong> à 2h30 (8 \"enfers\" thermaux), <strong>Nagasaki</strong> à 2h en Shinkansen. <strong>Tester</strong> Hakata ramen (origine ici, Ichiran et Ippudo nés à Fukuoka), motsunabe (tripes), mentaiko (œufs de cabillaud épicés). Très accessible depuis Séoul (1h en avion), Shanghai, Taipei.",

    "nagasaki:fr": "Nagasaki, 2e ville à avoir subi un bombardement atomique le 9 août 1945 (74 000 morts), garde une histoire singulière au Japon : <strong>seul port ouvert aux Européens (Hollandais et Portugais) pendant l'isolement Edo</strong> (1639-1854), influence chrétienne unique au Japon. <strong>Octobre est mon mois préféré</strong> (8.2/10) : 18-23°C, 27% de pluie, températures parfaites avant l'hiver. <strong>De juin à mi-juillet</strong>, c'est le tsuyu. <strong>Juillet-août chutent à 6.9/10</strong> à cause de la canicule. <strong>De décembre à février</strong>, comptez 5-12°C et 28-35% de pluie : doux grâce à l'effet maritime, ciel parfois dégagé. <strong>Sites majeurs</strong> : <strong>Atomic Bomb Museum</strong> (mémorial du bombardement), <strong>Peace Park</strong> (statue de la paix), <strong>Hypocenter Park</strong>, <strong>Glover Garden</strong> (maison du marchand écossais Thomas Glover XIXe, vue panoramique sur le port), <strong>Oura Cathedral</strong> (UNESCO, plus vieille église en bois du Japon, 1864), <strong>Dejima</strong> (île artificielle où les Hollandais étaient confinés), <strong>Chinatown Shinchi</strong>, <strong>Mont Inasa</strong> (vue panoramique nocturne, parmi les 3 meilleurs du Japon). <strong>Excursions</strong> : <strong>Hashima/Gunkanjima</strong> en bateau (île charbonnière abandonnée, UNESCO, James Bond Skyfall), <strong>Hirado</strong> (ancienne base portugaise). <strong>Lantern Festival</strong> en février chinois (15 jours, plus de 15 000 lanternes). <strong>Tester</strong> Nagasaki champon (nouilles fusion sino-japonaise), castella (gâteau d'origine portugaise), turc-rice. À 2h en Shinkansen de Fukuoka.",

    "niseko:fr": "Niseko est la station de ski la plus connue du Japon : <strong>15m de neige par an</strong> (parmi les plus enneigées au monde), poudreuse légendaire (\"Japow\" = Japan powder), 2 millions de visiteurs par saison, fortement fréquentée par Australiens, Hong-Kongais et Singapouriens. <strong>Juillet est mon mois préféré</strong> (8.0/10) : 17-25°C, 47% de pluie, randonnée en montagnes, mais Niseko est avant tout une destination hiver. <strong>De décembre à mars</strong>, comptez -9/4°C et 47-79% de précipitations (neige) : c'est la haute saison ski, prix hôteliers x4-x5, Hirafu = village principal complet, réservation 6 mois avant. <strong>De novembre et avril</strong> sont les intersaisons : ouverture des pistes mi-novembre, fermeture début mai, pistes encore skiables au printemps. <strong>De mai à octobre</strong>, station ouverte pour activités été : VTT, golf, randonnée vers Mont Yotei (1898m, le \"Fuji d'Hokkaido\"), rafting sur Shiribetsu River. <strong>Stations</strong> : 4 zones reliées par Niseko United pass (Hirafu, Hanazono, Niseko Village, Annupuri), 2191 ha, 30 remontées, dénivelé 1000m. <strong>Hors-piste</strong> légendaire (back-country en cat ski ou heli ski via guides locaux). <strong>Onsen</strong> caractéristiques d'Hokkaido (rotenburo extérieurs sous la neige). <strong>Tester</strong> Hokkaido seafood, ramen miso, mochi. Vol direct Tokyo (Sapporo Chitose) puis 2h en bus ou train + transfert (services privés depuis aéroport).",

    "delhi:fr": "Delhi (New Delhi + Old Delhi) est la capitale de l'Inde : 32 millions d'habitants en aire urbaine (parmi les plus grandes au monde), ville chaotique aux contrastes extrêmes. <strong>Mars est mon mois préféré</strong> (8.8/10) : 16-30°C, 12% de pluie, fin de l'hiver doux avant la canicule. <strong>De février à mars</strong>, comptez 11-30°C : températures parfaites pour le tourisme. <strong>D'avril à juin</strong>, c'est la canicule pré-mousson : 22-39°C (parfois 47°C en mai), poussière, ciel jaunâtre. <strong>De juillet à septembre</strong>, c'est la mousson : 39-73% de précipitations, inondations possibles, taux d'humidité oppressant. <strong>De novembre à janvier</strong>, comptez 8-27°C : haute saison touristique, mais aussi <strong>pollution atmosphérique extrême</strong> (AQI 300-500+ en novembre, ciel jaune/gris, masques nécessaires). <strong>Sites majeurs</strong> : <strong>Old Delhi</strong> (Jama Masjid plus grande mosquée d'Inde, Red Fort UNESCO, Chandni Chowk marché chaotique), <strong>New Delhi</strong> (Connaught Place, India Gate, Rashtrapati Bhavan), <strong>Humayun's Tomb</strong> (UNESCO, modèle du Taj Mahal), <strong>Qutub Minar</strong> (UNESCO, 73m), <strong>Lotus Temple</strong> (Bahá'í), <strong>Akshardham</strong> (temple hindou monumental). <strong>Sécurité</strong> : éviter de se déplacer seule la nuit (femmes), Uber/Ola plus sûrs que rickshaws/taxis. <strong>Tester</strong> chaat (street food), butter chicken (origine ici), parathas chez Paranthe Wali Gali, kebabs chez Karim's. Base pour le <strong>Triangle d'or</strong> (Delhi-Agra-Jaipur, 5-7 jours).",

    "jaipur:fr": "Jaipur, capitale du Rajasthan, est la \"Ville Rose\" : 3 millions d'habitants, vieille ville fortifiée peinte en rose en 1876 pour la visite du Prince of Wales. Une étape majeure du <strong>Triangle d'or</strong> Delhi-Agra-Jaipur. <strong>Février-mars sont mes mois préférés</strong> (8.9/10) : 13-31°C, 3-9% de pluie, températures parfaites, lumière dorée sur les murailles. <strong>De novembre à février</strong>, comptez 9-27°C : haute saison touristique, ciel dégagé. <strong>D'avril à juin</strong>, c'est la canicule pré-mousson : 23-40°C (parfois 45°C), impossible de visiter en milieu de journée. <strong>De juillet à septembre</strong>, c'est la mousson : 41-69% de précipitations, mais températures plus supportables (24-33°C). <strong>Sites majeurs</strong> : <strong>City Palace</strong> (palais royal toujours occupé, musée), <strong>Hawa Mahal</strong> (\"palais des vents\", 953 fenêtres de pierre rose, photo signature), <strong>Jantar Mantar</strong> (UNESCO, observatoire astronomique XVIIIe avec instruments géants), <strong>Amber Fort</strong> à 11 km (forteresse XVIe sur colline, montée à dos d'éléphant ou jeep, mirror palace), <strong>Nahargarh Fort</strong> (vue panoramique sur la ville au coucher du soleil), <strong>Jal Mahal</strong> (palais sur lac). <strong>Bazars</strong> : Johari Bazaar (bijoux), Bapu Bazaar (textiles), pierre semi-précieuses partout. <strong>Tester</strong> dal baati churma, laal maas (curry de chèvre épicé), kachori. Octobre-novembre et mars sont les meilleurs compromis foule/météo.",

    "udaipur:fr": "Udaipur est la \"Venise du Rajasthan\" : ville romantique entourée de 7 lacs, la plus chargée d'amour et d'élégance du Rajasthan. <strong>Février est mon mois préféré</strong> (9.4/10) : 13-27°C, 1% de pluie, températures parfaites, lumière dorée sur le lac Pichola. <strong>De novembre à mars</strong>, comptez 10-31°C : haute saison touristique, climat optimal. <strong>D'avril à juin</strong>, c'est la canicule pré-mousson : 22-37°C (parfois 42°C), supportable grâce à l'altitude (598m) mais éprouvante. <strong>De juillet à septembre</strong>, c'est la mousson : 47-72% de précipitations, mais paysages verdoyants (rare pour le Rajasthan), lacs pleins. <strong>Sites majeurs</strong> : <strong>City Palace</strong> (le plus grand palais du Rajasthan, complexe de 11 palais sur 244m de long, dynastie Mewar continue depuis 728), <strong>Lake Pichola</strong> (croisière au coucher du soleil), <strong>Lake Palace</strong> (palais blanc flottant au milieu du lac, hôtel Taj 5*+, accès non-clients impossible), <strong>Jagmandir Island</strong> (autre île-palais, accessible en bateau), <strong>Saheliyon-ki-Bari</strong> (jardins des dames d'honneur), <strong>Monsoon Palace</strong> (sur la colline Sajjangarh, vue panoramique au coucher du soleil). <strong>Eklingji et Nagda Temples</strong> à 22 km (millénaires). <strong>Tester</strong> dal baati churma, gatte ki sabzi, malpua. <strong>Octopussy</strong> de James Bond (1983) tourné ici (Lake Palace dans le film). Vol direct depuis Delhi (1h15) ou train de nuit depuis Delhi/Mumbai. Octobre-novembre et mars-avril sont les vrais bons compromis tourisme/météo.",

    "varanasi:fr": "Varanasi (Bénarès, Kashi) est l'une des villes les plus anciennes habitées en continu au monde (3000 ans), ville sainte de l'hindouisme sur le Gange. <strong>Février est mon mois préféré</strong> (8.8/10) : 14-26°C, 6% de pluie, températures parfaites. <strong>De novembre à mars</strong>, c'est la haute saison : 10-31°C, brume matinale sur le Gange (atmosphérique pour les ghats). <strong>D'avril à juin</strong>, c'est la canicule extrême : 24-39°C (parfois 47°C), impossible. <strong>De juillet à septembre</strong>, c'est la mousson : 77-84% de précipitations, le Gange déborde, ghats inondés, navigation difficile. <strong>Sites majeurs</strong> : <strong>Ghats sur le Gange</strong> (88 ghats sur 7 km, escaliers descendant à la rivière) : <strong>Dashashwamedh Ghat</strong> (le principal, Ganga Aarti cérémonie tous les soirs à la tombée du jour, 45 min très spirituelle), <strong>Manikarnika Ghat</strong> (ghat de crémation principal, bûchers funéraires en continu, photos interdites), <strong>Assi Ghat</strong> (sud, plus calme). <strong>Promenade en barque à l'aube</strong> (5h du matin) sur le Gange = expérience indispensable, voir les hindous se baigner et faire leurs prières. <strong>Vieille ville</strong> labyrinthe de ruelles autour de Vishwanath Temple. <strong>Sarnath</strong> à 10 km (où Bouddha a fait son premier sermon, ruines, musée). <strong>Logistique</strong> : Varanasi est intense, sale, chaotique - dépaysement extrême assumé. Hôtels avec vue Ganges (Ganges View, BrijRama Palace). <strong>Tester</strong> kachori sabzi, lassi chez Blue Lassi, paan. Vol direct depuis Delhi (1h30).",

    "agra:fr": "Agra abrite le <strong>Taj Mahal</strong> (UNESCO), monument le plus visité d'Inde : 7 millions de visiteurs/an. Mausolée construit 1632-1653 par l'empereur moghol Shah Jahan en hommage à sa femme Mumtaz Mahal morte en couches. <strong>Février est mon mois préféré</strong> (8.5/10) : 12-25°C, 6% de pluie, températures parfaites, brume matinale qui sublime le Taj. <strong>De novembre à mars</strong>, c'est la haute saison : 8-31°C. <strong>D'avril à juin</strong>, c'est la canicule extrême : 23-39°C (parfois 47°C), impossible de visiter en milieu de journée. <strong>De juillet à septembre</strong>, c'est la mousson : 46-73% de précipitations, ciel souvent gris (Taj moins photogénique). <strong>Sites majeurs</strong> : <strong>Taj Mahal</strong> (entrée 1300 INR pour étrangers, ouvert lever-coucher du soleil sauf vendredi, accès lever du soleil OBLIGATOIRE pour la lumière dorée et éviter foule, 4 jours/mois ouvert nuit autour pleine lune), <strong>Agra Fort</strong> (UNESCO, fort moghol XVIe-XVIIe, vue sur le Taj depuis Musamman Burj où Shah Jahan a fini ses jours emprisonné par son fils Aurangzeb), <strong>Itimad-ud-Daulah</strong> (\"baby Taj\", précurseur du Taj plus délicat), <strong>Mehtab Bagh</strong> (jardin de l'autre côté de la Yamuna pour vue Taj au coucher du soleil), <strong>Fatehpur Sikri</strong> à 40 km (UNESCO, ancienne capitale moghole abandonnée). <strong>Logistique</strong> : Agra à 3h de Delhi en train Gatimaan Express, étape obligatoire du <strong>Triangle d'or</strong>. Une journée suffit. <strong>Tester</strong> petha (douceur locale).",

    "goa:fr": "Goa, ancienne colonie portugaise (1510-1961) : la plus petite état indien (3700 km²), 2 millions d'habitants, plages, héritage colonial portugais, cuisine fusion, ambiance hippie persistante. <strong>De novembre à février</strong> (6.9/10) : 20-32°C, 0-17% de pluie, mer à 28°C, c'est la haute saison touristique. Goa ne dépasse jamais 7/10 (climat trop chaud-humide pour atteindre l'excellent). <strong>De juin à septembre</strong>, c'est la mousson : 87-99% de précipitations, plages désertes, beaucoup d'hôtels et restos ferment, mais aussi paysages les plus verdoyants et rivières en crue. <strong>D'octobre à mai</strong>, climat sec stable avec haute saison décembre-janvier (Européens en hivernage), prix hôteliers x3-x4. <strong>Goa du Nord vs Goa du Sud</strong> : Nord (Anjuna, Vagator, Baga, Calangute, Arambol) plus festif, marché aux puces hippie d'Anjuna le mercredi, ambiance backpackers ; Sud (Palolem, Agonda, Patnem) plus calme, plages sauvages, retraites yoga. <strong>Sites majeurs</strong> : <strong>Old Goa</strong> (UNESCO, Basilique Bom Jesus avec reliques de Saint François Xavier, Cathédrale Sé), <strong>Panaji/Panjim</strong> (capitale, quartier latin Fontainhas), <strong>Dudhsagar Falls</strong> (cascade 310m, tour 4×4 + train), <strong>Spice Plantations</strong>. <strong>Tester</strong> vindaloo, xacuti, fish curry rice (plat national local), pão (pain portugais), feni (alcool de noix de cajou). Vol direct depuis Paris à Goa-Mopa (nouvel aéroport, ouvert 2023).",

    "kerala:fr": "Le Kerala, dans le sud-ouest de l'Inde : 35 millions d'habitants, classé <strong>\"Top 10 destinations à voir dans la vie\"</strong> par National Geographic Traveler. Plages, backwaters, plantations de thé/cardamome, ayurveda. <strong>Janvier est mon mois préféré</strong> (6.8/10) : 23-34°C, 11% de pluie. Kerala ne dépasse jamais 7/10 (climat équatorial humide constant). <strong>De juin à septembre</strong>, c'est la mousson du sud-ouest : 85-98% de précipitations, paysages verts intenses, ayurvediques recommandent cette saison pour les cures (climat humide ouvre les pores). <strong>D'octobre à novembre</strong>, deuxième mousson (du nord-est) : 55-86% de précipitations. <strong>De décembre à mars</strong>, c'est la haute saison touristique : 23-32°C, climat sec relatif. <strong>D'avril à mai</strong>, comptez 25-37°C : chaleur étouffante avant la mousson. <strong>Sites majeurs</strong> : <strong>Backwaters d'Alleppey/Kumarakom</strong> (réseau de canaux, croisière 1-2 nuits en houseboat \"kettuvallam\" 100-300€), <strong>Kochi/Cochin</strong> (Fort Kochi, filets de pêche chinois, synagogue Paradesi, quartier juif), <strong>Munnar</strong> (plantations de thé en altitude 1600m, frais, randonnées), <strong>Périyar Wildlife Sanctuary</strong> (éléphants, tigres rares), <strong>Varkala</strong> et <strong>Kovalam</strong> (plages avec falaises). <strong>Theyyam</strong> (rituels danse-transe nord Kerala, oct-mai). <strong>Tester</strong> sadya (repas traditionnel sur feuille de bananier), Kerala fish curry, appam, puttu. <strong>Cure ayurvédique</strong> 7-21 jours dans resort spécialisé. Aéroport principal Kochi/Trivandrum. Climat équatorial = hors saison cyclonique principale.",

    "jodhpur:fr": "Jodhpur, la \"Ville Bleue\" : 1,1 million d'habitants, capitale du désert du Thar, dominée par la forteresse Mehrangarh perchée sur un piton de 122m. <strong>Février est mon mois préféré</strong> (9.5/10) : 14-28°C, 1% de pluie, températures parfaites, lumière dorée sur les murs bleus de Brahmins. <strong>De novembre à mars</strong>, c'est la haute saison : 10-30°C, climat sec idéal. <strong>D'avril à juin</strong>, c'est la canicule extrême : 25-41°C (parfois 49°C, l'une des villes les plus chaudes d'Inde), impossible. <strong>De juillet à septembre</strong>, c'est la mousson : 21-48% de précipitations (faibles pour l'Inde), températures plus supportables (25-35°C). <strong>Sites majeurs</strong> : <strong>Mehrangarh Fort</strong> (UNESCO World Monuments Watch, l'un des plus grands forts d'Inde, 121m sur la falaise, 7 portes, palais intérieur extraordinaire avec Phool Mahal et Sheesh Mahal, musée), <strong>Jaswant Thada</strong> (mausolée en marbre blanc XIXe), <strong>Umaid Bhawan Palace</strong> (palais Art Déco 1929-1943, dernier palais indien construit, partiellement converti en hôtel Taj 5*+ et résidence du Maharaja actuel), <strong>Clock Tower / Sardar Market</strong> (vieux bazar, épices et omelettes chez Omelette Shop), <strong>Brahmpuri</strong> (vieille ville bleue, ruelles labyrinthiques). <strong>Bishnoi Villages</strong> à 30 km (excursion communautés rurales écologistes). <strong>Tester</strong> mawa kachori, mirchi vada, makhaniya lassi. Octobre-novembre et mars sont les meilleurs compromis tourisme/météo.",

    "jaisalmer:fr": "Jaisalmer, la \"Ville Dorée\" : 78 000 habitants, citadelle en grès jaune au cœur du désert du Thar près de la frontière pakistanaise, l'une des rares forteresses encore habitées au monde. <strong>Novembre est mon mois préféré</strong> (9.2/10) : 17-29°C, 1% de pluie, températures parfaites pour le désert. <strong>De novembre à février</strong>, c'est la haute saison : 9-27°C, climat idéal. <strong>De mars à juin</strong>, c'est la canicule extrême : 19-41°C (parfois 49°C), désert à 50°C, impossible. <strong>Juillet est le pire mois</strong> (2.1/10) : 28-38°C avec 24% de mousson légère, taux d'humidité monstrueux pour le désert. <strong>Sites majeurs</strong> : <strong>Sonar Quila/Golden Fort</strong> (l'une des seules \"living forts\" au monde, 5000 personnes y vivent encore, mais surfréquentation menace ses fondations), <strong>Patwon Ki Haveli</strong> (5 havelis somptueusement sculptées), <strong>Salim Singh Ki Haveli</strong>, <strong>Nathmal Ki Haveli</strong>, <strong>Jain Temples</strong> (XIIe-XVIIe siècles dans le fort), <strong>Gadi Sagar Lake</strong> (à pied du fort, atmosphérique au coucher du soleil). <strong>Excursions désert</strong> : <strong>Sam Sand Dunes</strong> à 42 km (les plus connues mais touristiques, balade à dos de chameau, nuit en tente luxe \"glamping\"), <strong>Khuri Sand Dunes</strong> à 50 km (plus authentiques, moins fréquentées). <strong>Tester</strong> ker sangri (légumes du désert), bajre ki roti, ghotua ladoo. <strong>Logistique</strong> : train de nuit depuis Jodhpur (5h) ou Delhi (15h), pas d'aéroport commercial direct. Octobre et mars sont les meilleurs compromis.",

    "rajasthan:fr": "Le Rajasthan, le plus grand État indien (342 000 km²) : 80 millions d'habitants, terre des Maharajas, désert du Thar, palais, forteresses, traditions colorées. <strong>Février-mars sont mes mois préférés</strong> (8.9/10) : 13-31°C, 3-9% de pluie, températures parfaites. <strong>De novembre à mars</strong>, c'est la haute saison touristique : 9-27°C, climat sec idéal. <strong>D'avril à juin</strong>, c'est la canicule extrême : 23-40°C (parfois 49°C dans le désert), impossible de visiter. <strong>De juillet à septembre</strong>, c'est la mousson légère : 41-69% de précipitations, paysages verts inhabituels pour la région. <strong>Itinéraires classiques</strong> : <strong>Triangle d'or</strong> Delhi-Agra-Jaipur (5-7 jours), <strong>Boucle royale</strong> Delhi-Jaipur-Pushkar-Udaipur-Jodhpur-Jaisalmer-Bikaner-Delhi (15-21 jours). <strong>Villes principales</strong> : Jaipur (\"rose\"), Udaipur (\"blanche\"), Jodhpur (\"bleue\"), Jaisalmer (\"dorée\"), <strong>Pushkar</strong> (ville sainte hindoue, festival des chameaux en novembre), <strong>Bikaner</strong> (Junagarh Fort, temple aux rats Karni Mata). <strong>Parcs nationaux</strong> : <strong>Ranthambore</strong> (tigres du Bengale, octobre-juin, jeeps réservées 90 jours avant), <strong>Sariska</strong> (alternative moins fréquentée). <strong>Festivals</strong> : Holi (mars, fête des couleurs), Diwali (octobre-novembre), Pushkar Camel Fair (novembre, 50 000 chameaux). <strong>Tester</strong> dal baati churma, gatte ki sabzi, ker sangri, lassi de Jodhpur. Octobre-novembre et mars-avril sont les meilleurs compromis tourisme/météo.",

    "chiang-mai:fr": "Chiang Mai est la capitale culturelle du nord de la Thaïlande : 130 000 habitants intra-muros, 200 temples, ancienne capitale du royaume Lan Na (1296-1558). <strong>Janvier est mon mois préféré</strong> (9.1/10) : 17-28°C, 13% de pluie, température parfaite, ciel dégagé. <strong>De novembre à février</strong>, c'est la haute saison : 18-30°C, climat sec idéal. <strong>De mars à mai</strong>, c'est la <strong>burning season</strong> (saison des brûlis agricoles) : qualité de l'air catastrophique (AQI 200-500+), chaleur (24-36°C), à éviter pour les sensibles aux voies respiratoires. <strong>De juin à octobre</strong>, c'est la mousson : 60-96% de précipitations en averses d'après-midi, paysages verts. <strong>Sites majeurs</strong> : <strong>Vieille ville</strong> entourée de douves (carré de 1,5 km), 30 temples dont <strong>Wat Phra Singh</strong>, <strong>Wat Chedi Luang</strong> (ruines majestueuses), <strong>Wat Suan Dok</strong>, <strong>Doi Suthep</strong> (temple de montagne à 15 km, 309 marches, vue panoramique sur Chiang Mai). <strong>Marchés de nuit</strong> : Sunday Walking Street (la plus connue), Saturday Walking Street, Night Bazaar (touristique mais incontournable). <strong>Activités</strong> : <strong>cours de cuisine thaï</strong> (Thai Farm Cooking School, Asia Scenic), <strong>massages thaï</strong> écoles (Thai Massage School Old Medicine), <strong>elephant sanctuaries éthiques</strong> (Elephant Nature Park, à privilégier sur les fermes touristiques avec dressage), <strong>treks</strong> dans les villages tribaux (Karen, Hmong, Akha, Lahu) au nord. <strong>Yi Peng Lantern Festival</strong> en novembre (lanternes envoyées dans le ciel, l'une des plus belles fêtes au monde). <strong>Tester</strong> khao soi, sai oua, kanom jeen.",

    "phuket:fr": "Phuket, la plus grande île de Thaïlande (576 km²), capitale balnéaire du sud-ouest : 400 000 habitants, plages, vie nocturne (Patong), base pour les îles Andaman. <strong>De novembre à février</strong> (6.9/10) : 24-32°C, 24-35% de pluie, mer à 28°C. C'est la haute saison touristique sèche. Phuket ne dépasse jamais 7/10 (climat tropical chaud-humide constant). <strong>De mai à octobre</strong>, c'est la mousson du sud-ouest : 69-91% de précipitations, mer agitée (drapeaux rouges fréquents, baignade dangereuse à Patong), beaucoup de bateaux ne sortent plus. <strong>De mars à avril</strong>, comptez 26-32°C et 35-62% de pluie : chaleur croissante avant la mousson. <strong>Plages</strong> : <strong>Patong</strong> (la plus connue, vie nocturne intense, ladyboys, Bangla Road, à éviter pour qui cherche le calme), <strong>Karon</strong> et <strong>Kata</strong> (familiales), <strong>Surin</strong> et <strong>Bang Tao</strong> (plus chics), <strong>Naiharn</strong> (au sud, plus authentique), <strong>Freedom Beach</strong> (accessible à pied seulement). <strong>Excursions majeures</strong> : <strong>Phi Phi Islands</strong> en speedboat 1h (Maya Bay où La Plage avec DiCaprio fut tournée, fermée 2018-2022 pour récupération corallienne, accès limité depuis), <strong>James Bond Island</strong> (Khao Phing Kan), <strong>Phang Nga Bay</strong> en kayak, <strong>Similan Islands</strong> (plongée nov-mai, fermées en mousson), <strong>Racha Yai et Racha Noi</strong> (snorkeling). <strong>Vieille ville Phuket Town</strong> = architecture sino-portugaise. <strong>Tester</strong> som tam, pad thaï, fruits de mer, mango sticky rice. Vol direct Bangkok-Phuket en 1h.",

    "krabi:fr": "Krabi est la province balnéaire du sud-ouest thaïlandais, alternative à Phuket plus authentique : Ao Nang (station principale), Railay (péninsule de calcaire accessible uniquement en bateau), Koh Lanta. <strong>De novembre à février</strong> (6.9/10) : 22-31°C, 31-46% de pluie, mer à 28°C, c'est la haute saison sèche. Krabi ne dépasse jamais 7/10 (climat tropical chaud-humide constant). <strong>De mai à octobre</strong>, c'est la mousson du sud-ouest : 75-92% de précipitations, mer agitée, beaucoup de bateaux interrompus. <strong>De mars à avril</strong>, comptez 23-34°C avec 42-75% de pluie : chaleur étouffante. <strong>Sites majeurs</strong> : <strong>Railay Beach</strong> (péninsule accessible uniquement en bateau depuis Ao Nang 15 min, 4 plages : West, East, Phra Nang, Tonsai - mecque de l'escalade en grimpe sur falaises calcaires, plus de 700 voies), <strong>Phra Nang Cave Beach</strong> (l'une des plus belles plages au monde selon de nombreux classements), <strong>Ao Nang</strong> (station principale, hôtels et restos), <strong>4 Islands tour</strong> (Phra Nang Cave, Koh Tup, Chicken Island, Koh Poda en longtail), <strong>Hong Islands tour</strong> (lagune intérieure spectaculaire), <strong>Emerald Pool et Hot Springs</strong> à Khao Phra Bang Khram. <strong>Koh Phi Phi</strong> à 2h en ferry depuis Krabi. <strong>Koh Lanta</strong> au sud (île plus calme, longue plage, plongée à Hin Daeng/Hin Muang). <strong>Tiger Cave Temple</strong> (Wat Tham Sua, 1237 marches pour la vue). <strong>Tester</strong> tom yum, massaman curry, fruits de mer locaux. Vol direct Bangkok-Krabi en 1h15.",

    "koh-samui:fr": "Koh Samui, 2e plus grande île de Thaïlande (228 km²) dans le golfe de Thaïlande : 60 000 habitants, plus chic que Phuket, plages familiales, base pour Koh Phangan (Full Moon Party) et Koh Tao (plongée). <strong>De janvier à août</strong> (6.6-6.9/10) : 24-31°C, 35-67% de pluie. Koh Samui ne dépasse jamais 7/10 (climat équatorial constant). <strong>D'octobre à décembre</strong>, c'est la saison des pluies : 63-88% de précipitations (Koh Samui a sa propre saison des pluies inversée par rapport à Phuket grâce à sa position dans le golfe de Thaïlande). <strong>De février à mai</strong>, c'est la saison la plus sèche : 35-49% de précipitations, mer à 28°C. <strong>Plages</strong> : <strong>Chaweng</strong> (la plus connue, animée, hôtels, vie nocturne), <strong>Lamai</strong> (2e plus animée, alternative plus calme), <strong>Bophut</strong> (Fisherman's Village charmant le vendredi soir), <strong>Maenam</strong> (familiale), <strong>Choeng Mon</strong> (calme, chic). <strong>Sites majeurs</strong> : <strong>Big Buddha</strong> (statue de 12m sur petite île reliée au nord), <strong>Wat Plai Laem</strong> (temple chinois coloré), <strong>Na Muang Waterfalls</strong>, <strong>Hin Ta Hin Yai</strong> (rochers en forme de \"grand-père/grand-mère\" suggestifs). <strong>Excursions</strong> : <strong>Ang Thong Marine Park</strong> (42 îles, snorkeling, kayak), <strong>Koh Phangan</strong> à 30 min en ferry (Full Moon Party à Haad Rin Beach les nuits de pleine lune, plages plus paradisiaques que Samui), <strong>Koh Tao</strong> à 1h30 (plongée moins chère du monde, plus de 50 sites). <strong>Tester</strong> tom kha gai, fruits de mer.",

    "baie-halong:fr": "La <strong>Baie d'Halong</strong> (UNESCO 1994) est l'image carte postale du Vietnam : 1969 îles karstiques de calcaire émergent sur 1500 km² dans le golfe du Tonkin. <strong>Novembre est mon mois préféré</strong> (8.6/10) : 20-26°C, 25% de pluie, ciel dégagé après la mousson, températures clémentes. <strong>D'octobre à mars</strong>, c'est la haute saison : 16-28°C, 15-38% de pluie, certaines journées peuvent être brumeuses (visibilité réduite, surtout janvier-février, mais aussi atmosphérique pour la photographie). <strong>De mai à août</strong>, c'est la saison des typhons et de la mousson : 63-87% de précipitations, températures chaudes (25-31°C), risque réel de tempêtes (croisières annulées plusieurs jours). <strong>D'avril à mai</strong>, comptez 22-29°C : transition humide. <strong>Croisières</strong> : <strong>1 nuit (2 jours)</strong> = circuit standard \"classic\", on voit l'essentiel mais court (50-150€/personne), <strong>2 nuits (3 jours)</strong> = circuit recommandé pour vraiment apprécier (Bai Tu Long Bay moins fréquentée, kayak, grottes, pêche nocturne, 200-500€), <strong>3 nuits</strong> = pour passionnés. <strong>Cat Ba Island</strong> à explorer 2-3 jours en plus (parc national, randonnées). <strong>Sites majeurs</strong> : <strong>Sung Sot Cave</strong> (\"grotte des surprises\"), <strong>Ti Top Island</strong> (panorama), <strong>Lan Ha Bay</strong> (alternative moins fréquentée à l'est, près de Cat Ba), <strong>Bai Tu Long Bay</strong> (au nord-est, encore plus calme, croisières premium). <strong>Logistique</strong> : 3h30 en bus depuis Hanoi (autoroute), embarquement à Tuan Chau Marina ou Halong City. <strong>Tester</strong> fruits de mer locaux, cha muc (rouleaux de calmar). Avril et septembre sont les meilleurs compromis foule/météo.",

    "maldives:fr": "Les Maldives, c'est l'archipel paradis par excellence : <strong>1192 îles coralliennes</strong> sur 26 atolls dans l'océan Indien, dont 200 habitées et 150 transformées en resorts privés. Pays le plus plat au monde (altitude max 2,4m). <strong>De janvier à avril</strong> (6.9/10) : 26-29°C, 35-54% de pluie, mer à 28°C, c'est la haute saison sèche, période de la mousson sèche du nord-est. Les Maldives ne dépassent jamais 7/10 (climat équatorial constant). <strong>De mai à novembre</strong>, c'est la mousson humide du sud-ouest : 46-76% de précipitations en averses brèves mais intenses, mer parfois agitée. <strong>De décembre à mars</strong>, c'est la haute saison touristique : prix hôteliers x2-x3, demande forte (vacances européennes scolaires). <strong>Logistique</strong> : <strong>Vol direct Paris-Malé en 10h</strong>. Depuis Malé, transfert vers le resort : <strong>hydravion</strong> pour les atolls éloignés (200-500$/personne aller-retour, vol scénique en lui-même), <strong>speedboat</strong> pour les atolls proches (50-100$), <strong>vol intérieur</strong> + speedboat pour les atolls extrêmes. <strong>Resorts privés</strong> : 1 île = 1 resort, prix 300€/nuit (basique) à 5000€+/nuit (Soneva Jani, Cheval Blanc Randheli, One&Only Reethi Rah). <strong>Bungalows sur pilotis</strong> caractéristiques, plongée et snorkeling parmi les meilleurs au monde (raies mantas, requins-baleines, tortues). <strong>Malé</strong> (capitale) à 200 000 habitants, escale possible. <strong>Maafushi</strong> = île locale accessible en ferry public depuis Malé (alternative budget). <strong>Tester</strong> mas huni (petit-déjeuner local), garudhiya (soupe de poisson), roshi.",

    "sri-lanka:fr": "Le Sri Lanka, ex-Ceylan : 22 millions d'habitants, île tropicale au sud de l'Inde, 8 sites UNESCO, plages, jungle, plantations de thé, temples bouddhistes. <strong>Février est mon mois préféré</strong> (8.1/10) : 22-29°C, 45% de pluie, climat sec relatif. <strong>2 moussons</strong> : <strong>du sud-ouest (yala) de mai à septembre</strong> (côte ouest et sud + intérieur), et <strong>du nord-est (maha) d'octobre à janvier</strong> (côte est). On peut donc trouver beau temps quelque part toute l'année. <strong>Côté sud-ouest (Colombo, Galle, Mirissa, plantations de thé)</strong> : visiter de décembre à avril. <strong>Côté est (Trincomalee, Arugam Bay, Pasikuda)</strong> : visiter d'avril à septembre. <strong>Sites majeurs</strong> : <strong>Sigiriya</strong> (UNESCO, forteresse-rocher 200m, fresques, jardins, lever du soleil mythique), <strong>Polonnaruwa</strong> et <strong>Anuradhapura</strong> (UNESCO, anciennes capitales bouddhistes, ruines), <strong>Kandy</strong> (Temple de la Dent de Bouddha), <strong>Plantations de thé</strong> autour de Nuwara Eliya et Ella (train scénique Kandy-Ella en 7h, l'un des plus beaux trajets ferroviaires au monde), <strong>Yala National Park</strong> (léopards, plus haute densité au monde), <strong>Galle</strong> (UNESCO, ville coloniale néerlandaise fortifiée), <strong>Mirissa</strong> (plage, observation des baleines bleues novembre-avril), <strong>Adam's Peak</strong> (2243m, ascension nocturne pour le lever du soleil, décembre-mai). <strong>Tester</strong> rice & curry (plat national, plein de petits plats), kottu, hoppers, string hoppers, thé de Ceylan. Vol direct Paris-Colombo en 10h.",

    "katmandou:fr": "Katmandou, capitale du Népal : 1 million d'habitants en ville, 2,5 en aire urbaine. À 1400m d'altitude dans une vallée montagneuse, 7 sites UNESCO. Reconstruite après le séisme dévastateur d'avril 2015 (9000 morts, 600 000 maisons détruites). <strong>Avril est mon mois préféré</strong> (8.2/10) : 14-25°C, 42% de pluie, températures parfaites, rhododendrons en fleurs. <strong>De mars à mai</strong>, c'est la haute saison des treks (8.0-8.2/10) : 10-26°C, ciel dégagé sur les sommets le matin (Everest, Annapurnas). <strong>De juin à septembre</strong>, c'est la mousson : 90-100% de précipitations, sangsues sur les sentiers, sommets cachés, mais paysages les plus verts (rare période pour visiter Mustang et Dolpo, vallées dans l'ombre pluviométrique). <strong>D'octobre à novembre</strong>, c'est la 2e haute saison de trek (8.0-8.1/10) : 10-24°C, ciel le plus dégagé de l'année après la mousson, mais foules sur l'Annapurna et l'Everest BC. <strong>De décembre à février</strong>, comptez 5-19°C : froid en altitude, treks difficiles au-dessus de 4000m. <strong>Sites majeurs</strong> : <strong>Durbar Square</strong> (centre historique, partiellement détruit en 2015), <strong>Pashupatinath</strong> (temple hindou, crémations sur les ghats), <strong>Boudhanath Stupa</strong> (l'un des plus grands stupas bouddhistes au monde, quartier tibétain), <strong>Swayambhunath</strong> (\"Monkey Temple\", stupa sur colline), <strong>Patan</strong> et <strong>Bhaktapur</strong> (cités-États médiévales). <strong>Treks classiques</strong> au départ : <strong>Annapurna Circuit</strong> (15-21 jours), <strong>Annapurna Base Camp</strong> (10-14 jours), <strong>Everest Base Camp</strong> (12-16 jours, vol Lukla). <strong>Tester</strong> momos, dal bhat, sel roti.",

    "ubud:fr": "Ubud est le cœur culturel de Bali (Indonésie) : 80 000 habitants, à 35 km au nord de Denpasar, dans les rizières en terrasses, capitale du yoga, du wellness et de la spiritualité hindoue balinaise. Popularisé par <strong>Mange Prie Aime</strong> (Eat Pray Love) avec Julia Roberts en 2010. <strong>Août est mon mois préféré</strong> (7.6/10) : 21-27°C, 73% de pluie. Ubud reste plus humide que les côtes balinaises (1500m d'altitude relative, montagne). <strong>De mai à octobre</strong>, c'est la saison sèche relative : 49-81% de précipitations. <strong>De novembre à mars</strong>, c'est la saison des pluies : 71-93% de précipitations en averses violentes d'après-midi (matinées souvent ensoleillées). <strong>D'avril à juin et septembre à octobre</strong> sont les vrais bons compromis foule/météo. <strong>Sites majeurs</strong> : <strong>Tegalalang Rice Terraces</strong> (rizières en terrasses photogéniques mais touristiques, <strong>Jatiluwih à 1h plus authentique et UNESCO</strong>), <strong>Sacred Monkey Forest</strong> (700 macaques, attention aux objets), <strong>Saraswati Temple</strong> (lotus pond), <strong>Goa Gajah</strong> (\"grotte de l'éléphant\"), <strong>Tirta Empul</strong> (temple aux sources sacrées, rituel de purification), <strong>Mt. Batur</strong> (volcan 1717m, ascension nocturne pour lever du soleil au sommet, 4h). <strong>Activités</strong> : <strong>cours de cuisine balinaise</strong>, <strong>yoga retreats</strong> (Yoga Barn, Radiantly Alive), <strong>massages traditionnels</strong>, <strong>rafting sur Ayung River</strong>. <strong>Marché central</strong> Ubud Art Market. <strong>Tester</strong> nasi campur, babi guling (cochon de lait), sate lilit, jamu (boisson herbale traditionnelle).",

    "lombok:fr": "Lombok, l'île voisine de Bali (à 35 km à l'est) : 4700 km², 4 millions d'habitants, plus calme et moins touristique que Bali, plages parmi les plus sauvages d'Indonésie, dominée par le <strong>volcan Rinjani</strong> (3726m, 2e plus haut d'Indonésie). <strong>Juillet-août sont mes mois préférés</strong> (8.3/10) : 21-29°C, 40-44% de pluie, c'est la saison sèche. <strong>De mai à septembre</strong>, c'est la saison sèche : 40-67% de précipitations. <strong>De novembre à mars</strong>, c'est la saison des pluies : 84-91% de précipitations en averses violentes. <strong>D'avril à juin</strong>, comptez 22-30°C avec 51-71% de pluie : intersaison. <strong>Sites majeurs</strong> : <strong>Mount Rinjani</strong> (ascension 2-4 jours, camping au lac de cratère Segara Anak 2000m, lever du soleil au sommet, accessible uniquement avec guide certifié, fermé en saison des pluies décembre-mars), <strong>Gili Islands</strong> à 25 min en bateau depuis Bangsal Harbour (3 îlots paradisiaques sans voitures : <strong>Gili Trawangan</strong> festif, <strong>Gili Air</strong> familial, <strong>Gili Meno</strong> romantique), <strong>plages du sud</strong> (Kuta Lombok village surf, Tanjung Aan plage croissant turquoise, Mawun, Selong Belanak), <strong>Sembalun Valley</strong> (rizières en terrasses au pied du Rinjani), <strong>Senaru et Tiu Kelep Waterfalls</strong>. <strong>Sasak culture</strong> = peuple indigène majoritaire à Lombok (musulman, distinct des Balinais hindous), villages traditionnels Sade et Ende. <strong>Tester</strong> ayam taliwang (poulet épicé), plecing kangkung, sate rembiga. <strong>Sécurité</strong> : tremblement de terre majeur en août 2018 (500 morts) - reconstruction depuis. Vol direct depuis Singapour, Bali (25 min), Jakarta."
}

with open(PATH, encoding='utf-8') as f:
    data_existing = json.load(f)

before = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

data_existing['_version'] = '2.1'
data_existing['_updated'] = '2026-04-28'

for k, v in AVIS_BATCH10_FR.items():
    data_existing[k] = v

after = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data_existing, f, ensure_ascii=False, indent=2)

print(f"Avis FR avant : {before}")
print(f"Avis FR après : {after}")
print(f"Nouveaux : {after - before}")

# Audit immédiat
import re
patterns_check = [
    ('em-dash', r'—'), ('guillemets', r'[«»]'),
    ('attendez-vous', r'attendez-vous à'),
    ('parfait', r'\bparfait[es]*\b'),
    ('fenêtre', r'\bfenêtre[s]?\b'),
    ('saturé', r'\bsatur[eéa]\w*\b'),
    ('se mérite', r'\bse méri[tes]+\b'),
    ('magique', r'\bmagiques?\b'),
    ('Si vous X:', r'Si vous \w+ : '),
    ('iconique', r'\biconique[s]?\b'),
    ('antithèse', r'antithèse'),
    ('mythique', r'\bmythique[s]?\b'),
    ('emblématique', r'\bemblématique[s]?\b'),
    ('authentique', r'\bauthentique[s]?\b'),
    ('féérique', r'\bféérique[s]?\b'),
    ("c'est aussi", r"[Cc]'est aussi"),
    ('à monitorer', r'à monitorer'),
    ('à éviter', r'à éviter'),
]

print("\n=== Audit batch 10 ===")
issues_total = 0
for slug in AVIS_BATCH10_FR.keys():
    plain = re.sub(r'<[^>]+>', '', data_existing[slug])
    issues = []
    for label, p in patterns_check:
        n = len(re.findall(p, plain))
        if n > 0:
            issues.append(f"{label}={n}")
            issues_total += n
    flag = "OK" if not issues else "PB " + ", ".join(issues)
    print(f"  {slug:<22} {len(plain.split()):>3}m {flag}")
print(f"\nTotal issues : {issues_total}")
