"""Batch 8 : 30 avis FR Tier 1 Amérique latine + Caraïbes."""
import json

PATH = 'data/avis_annuel.json'
data = json.load(open(PATH, encoding='utf-8'))

AVIS_BATCH8_FR = {
    "rio-de-janeiro:fr": "Rio est l'une des villes les plus spectaculaires au monde : 6 millions d'habitants entre montagnes (Pão de Açúcar, Corcovado) et mer (Copacabana, Ipanema, Leblon). <strong>Septembre est mon mois préféré</strong> (8.6/10) : 20-26°C, 28% de pluie, fin de l'hiver austral, températures idéales sans la chaleur étouffante. <strong>De décembre à mars</strong>, comptez 23-30°C et 42-48% de pluie : été austral pic touristique, mer à 25°C, mais aussi <strong>Carnaval</strong> (4 jours avant le mardi gras, dates variables février-mars), prix x4-x5, hôtels complets 6 mois à l'avance. <strong>De mai à août</strong> (hiver austral), comptez 18-25°C : températures fraîches le matin, parfait pour les randonnées (Pedra Bonita, Dois Irmãos). <strong>Sites majeurs</strong> : <strong>Christ Rédempteur</strong> au Corcovado (train cogue depuis Cosme Velho), <strong>Pão de Açúcar</strong> (téléphérique 2 tronçons), <strong>Escadaria Selarón</strong> (Lapa), <strong>Jardim Botânico</strong>, <strong>Niterói et son MAC</strong> (Niemeyer) en ferry. <strong>Quartiers</strong> : Copacabana (touristique), Ipanema (chic, baignade plus agréable), Leblon (haut de gamme), Santa Teresa (artistique sur les hauteurs), Lapa (nightlife). <strong>Sécurité</strong> : favelas demandent guide local, plages OK en journée, vigilance la nuit. <strong>Tester</strong> feijoada (le samedi tradition), churrasco, açaí bowl, caipirinha (origine ici).",

    "cusco:fr": "Cusco est l'ancienne capitale inca à 3400m d'altitude : <strong>l'altitude se ressent dès l'arrivée</strong> (souffle court, mal de tête possible, nuit difficile la 1ère nuit). <strong>Juillet est mon mois préféré</strong> (8.0/10) : 4-18°C, 10% de pluie, c'est la saison sèche, ciel dégagé, mais aussi le pic touristique. <strong>De juin à août</strong>, comptez 4-18°C avec 7-25% de pluie : la saison sèche idéale pour le trek du Chemin de l'Inca (réservation obligatoire 6 mois avant via les agences agréées). <strong>De décembre à mars</strong>, c'est la saison des pluies : 85-95% de précipitations, le Chemin de l'Inca ferme tout février pour entretien. Machu Picchu reste accessible toute l'année. <strong>Sites majeurs</strong> : <strong>Plaza de Armas</strong> (cathédrale, Compañia de Jesús), <strong>Coricancha</strong> (temple inca devenu couvent dominicain), <strong>Sacsayhuamán</strong> (forteresse inca aux pierres polygonales), <strong>San Blas</strong> (quartier artistique), <strong>Mercado San Pedro</strong> (jus de fruits, alpaca). <strong>Vallée Sacrée</strong> à 1h : Pisac (marché du dimanche), Ollantaytambo, Maras (salines), Moray (terrasses agricoles inca). <strong>Acclimatation</strong> : 2-3 jours avant tout effort, hydratation, mate de coca. Vol Lima-Cusco 1h. <strong>Tester</strong> ceviche, lomo saltado, cuy (cochon d'Inde, plat traditionnel), pisco sour.",

    "machu-picchu:fr": "Machu Picchu, à 2400m d'altitude, est le site archéologique inca le plus iconique au monde : 6000 visiteurs/jour limités par billets horodatés. <strong>Juillet est mon mois préféré</strong> (7.9/10) : 11-21°C, 34% de pluie, saison sèche péruvienne, ciel généralement dégagé. <strong>De juin à août</strong>, c'est le pic touristique : <strong>billets à réserver 3-4 mois avant</strong>, prix d'environ 50-200$ selon circuit (3 circuits différents depuis 2024). <strong>De décembre à mars</strong>, c'est la saison des pluies : 83-98% de précipitations, brume fréquente (peut bloquer la vue, mais aussi rendre le site mystérieux), Chemin de l'Inca fermé tout février. <strong>Avril-mai et septembre-octobre</strong> sont les vrais bons compromis : foule réduite, météo encore acceptable, prix légèrement en retrait. <strong>Logistique</strong> : vol Lima-Cusco, train Cusco-Aguas Calientes (3h30 par PeruRail Vistadome ou Inca Rail Premium, 60-200$ aller), bus Aguas Calientes-Machu Picchu (12$ aller-retour, 25 min). Compter minimum 1 nuit à Aguas Calientes (Machupicchu Pueblo) pour entrée à 6h. <strong>Huayna Picchu</strong> ou <strong>Montaña Machu Picchu</strong> = ascension supplémentaire (réservation séparée, capacité limitée). Guide local obligatoire depuis 2017 (50-150$/groupe).",

    "la-paz:fr": "La Paz est la capitale (administrative) de la Bolivie : 3650m d'altitude, l'aéroport (El Alto) est à 4150m, le plus haut au monde. <strong>L'altitude se ressent immédiatement</strong> : essoufflement, mal de tête, sommeil perturbé. <strong>Août est mon mois préféré</strong> (7.7/10) : 1-16°C, 11% de pluie, saison sèche andine, ciel clair. <strong>De mai à août</strong> est la saison sèche : températures fraîches mais stables. <strong>De décembre à mars</strong>, c'est la saison des pluies : 60-69% de précipitations, certaines pistes du Salar de Uyuni et de la mort impraticables. <strong>Sites majeurs</strong> : <strong>Mi Teleférico</strong> (réseau de téléphériques urbains, le plus grand au monde, 30 km, panorama unique), <strong>Marché des Sorcières</strong> (Mercado de las Brujas, fœtus de lama traditionnels), <strong>Plaza Murillo</strong>, <strong>Iglesia de San Francisco</strong>, <strong>Vallée de la Lune</strong> (paysages d'érosion à 30 min). <strong>Excursions</strong> : <strong>Salar de Uyuni</strong> à Uyuni (10h en bus de nuit, 3-4 jours en 4×4 avec hébergement basique, 200-400$), <strong>Lac Titicaca</strong> et Copacabana (3h en bus, 3812m d'altitude), <strong>Route de la Mort</strong> à VTT depuis La Cumbre (4670m → 1180m, agences à La Paz pour ~80$). <strong>Tester</strong> salteñas (chausson traditionnel), api con pasteles, llama steak.",

    "galapagos:fr": "Les Galápagos, c'est l'archipel équatorien à 1000 km du continent : 13 îles principales, 200 espèces endémiques (Darwin y a inspiré sa théorie de l'évolution en 1835). <strong>Janvier est mon mois préféré</strong> (7.8/10) : 22-26°C, 68% de pluie en averses brèves, mer plus chaude (24°C). <strong>De décembre à mai</strong>, c'est la saison chaude/humide : ciel souvent ensoleillé entre averses, mer calme et chaude (26°C), idéal pour la plongée. <strong>De juin à novembre</strong>, c'est la saison sèche/froide : courant Humboldt qui amène la fraîcheur (18-23°C), brume \"garúa\" fréquente, mer agitée et froide (18-22°C, combinaison utile pour plonger). C'est aussi la saison des manchots et albatros (Española). <strong>Logistique</strong> : vol Quito ou Guayaquil → Baltra ou San Cristóbal (2h, 350-500$ aller-retour). Frais d'entrée parc national 200$ + carte de transit 20$. <strong>Croisières</strong> 4-8 jours (1500-5000$ par personne) ou <strong>séjour land-based</strong> (Santa Cruz/Puerto Ayora ou San Cristóbal/Baquerizo Moreno) avec excursions journées (200-400$/personne). <strong>Faune</strong> : iguanes marins, tortues géantes (Centre Charles Darwin), otaries, fous à pieds bleus, raies mantas, requins-marteaux. <strong>Sites</strong> : Bartolomé (Pinnacle Rock), Floreana (corespondance Post Office Bay), Española (albatros avril-décembre), Genovesa (oiseaux). Tourisme contrôlé : 240 000 visiteurs/an max.",

    "quito:fr": "Quito, capitale équatorienne : 2850m d'altitude, vieille ville coloniale UNESCO la mieux préservée d'Amérique du Sud (1978). <strong>Juillet-août sont mes mois préférés</strong> (7.7/10) : 7-19°C, 32-36% de pluie, saison sèche équatoriale, ciel dégagé. <strong>De janvier à mai</strong>, c'est la saison des pluies : 79-93% de précipitations en averses d'après-midi (matinées souvent ensoleillées). <strong>L'altitude se ressent</strong> : monter doucement les pentes raides du Vieux-Quito, hydratation. <strong>Sites majeurs</strong> : <strong>Centre historique</strong> (Plaza Grande, Cathédrale, La Compañía de Jesús couverte d'or, San Francisco), <strong>El Panecillo</strong> (statue Vierge en aluminium 41m, vue sur la vallée), <strong>TelefériQo</strong> (téléphérique vers Cruz Loma à 4100m), <strong>Mitad del Mundo</strong> (monument à l'équateur géographique, à 30 min, deux versions : monument officiel et le site INRG \"vrai\" équateur). <strong>Otavalo marché</strong> à 2h le samedi (le plus grand marché indigène d'Amérique du Sud). <strong>Cotopaxi</strong> (volcan 5897m) à 1h30 pour ascension (1 nuit refuge José Rivas). <strong>Sécurité</strong> : Vieux-Quito demande vigilance la nuit (Mariscal/La Mariscal touristique avec animation soirée). Quito sert souvent de transit avant/après Galápagos. <strong>Tester</strong> ceviche de chochos, llapingachos, locro de papa, hornado.",

    "antigua-guatemala:fr": "Antigua Guatemala, ancienne capitale coloniale UNESCO : 1500m d'altitude, ruines baroques d'églises (séismes du XVIIIe siècle), volcans actifs en arrière-plan (Fuego, Acatenango, Agua). <strong>Février-mars sont mes mois préférés</strong> (9.1/10) : 13-27°C, 12-19% de pluie, saison sèche idéale, ciel dégagé pour voir les éruptions du Fuego. <strong>De mai à octobre</strong>, c'est la saison des pluies : 78-92% de précipitations en averses d'après-midi, mais matinées souvent ensoleillées. <strong>De novembre à avril</strong>, saison sèche, jacarandas en fleurs (mars-avril). <strong>Sites majeurs</strong> : <strong>Plaza Mayor</strong> et Cathédrale Santiago (en ruines), <strong>Iglesia de la Merced</strong> (jaune coloré), <strong>Ruinas Iglesia de San Francisco</strong>, <strong>Convento de Capuchinas</strong>, <strong>Cerro de la Cruz</strong> (vue panoramique sur la ville et le volcan Agua). <strong>Excursions volcans</strong> : <strong>Acatenango</strong> (3976m, ascension 6h, bivouac, vue sur Fuego en éruption permanente), <strong>Pacaya</strong> (2500m, ascension 2h, lave coulante, marshmallows grillés). <strong>Marchés</strong> : Mercado Municipal et marchés artisanaux (Chichicastenango à 2h le jeudi/dimanche). <strong>Lac Atitlán</strong> à 2h (l'un des plus beaux du monde selon Aldous Huxley, 3 volcans en arrière-plan, villages mayas). <strong>Tester</strong> pepián (ragoût national), tamales, café guatémaltèque (parmi les meilleurs au monde).",

    "cancun:fr": "Cancun, c'est la station balnéaire mexicaine all-inclusive par excellence : Hotel Zone (zone hôtelière) construite sur une île en barre de sable de 25 km, 30 millions de visiteurs/an. <strong>Mars-avril sont mes mois préférés</strong> (8.7-8.8/10) : 23-29°C, 25-30% de pluie, mer turquoise à 25°C, fin de la haute saison américaine. <strong>De juin à octobre</strong>, c'est la saison cyclonique : 53-75% de pluie, risque réel d'ouragans (Wilma 2005 et catégorie 5+ historiques), Spring Break américain mars (foule étudiante débridée). <strong>De décembre à février</strong> est la pleine haute saison nord-américaine : 22-27°C, 33-45% de pluie, prix hôteliers x3, plages de Hotel Zone bondées. <strong>Sites majeurs</strong> : <strong>Plages</strong> Playa Delfines (gratuite, recommandée), Playa Tortugas (publique avec animation), <strong>El Mirador</strong> pour la vue. <strong>Excursions majeures</strong> : <strong>Chichén Itzá</strong> (UNESCO) à 2h (foule à éviter, partir 6h ou aller de Valladolid), <strong>Tulum</strong> et <strong>Coba</strong> (ruines), <strong>cenotes</strong> (Ik Kil, Dos Ojos, Gran Cenote, baignade dans cavernes calcaires), <strong>Isla Mujeres</strong> en ferry 25 min (snorkeling, plage Norte), <strong>Xcaret/Xel-Ha</strong> (parcs aquatiques touristiques). <strong>Sargasse</strong> : algues brunes qui s'échouent en quantités variables d'avril à août depuis 2014 (sites web pour vérifier l'état des plages avant de réserver). <strong>Tester</strong> cochinita pibil (Yucatán), poisson tikin xic, marquesitas (street food sucrée).",

    "playa-del-carmen:fr": "Playa del Carmen est la station balnéaire alternative à Cancun (1h au sud) : ville à taille humaine, ambiance européenne, bohème-chic, base pour explorer la Riviera Maya. <strong>Mars est mon mois préféré</strong> (8.9/10) : 24-28°C, 27% de pluie, mer à 25°C, fin de la haute saison américaine. <strong>De juin à octobre</strong>, c'est la saison cyclonique : 46-72% de pluie, risque ouragans, sargasse possible. <strong>De décembre à février</strong>, comptez 22-27°C : haute saison européenne et américaine, prix hôteliers x2-x3. <strong>Sites majeurs</strong> : <strong>5e Avenue (Quinta Avenida)</strong> piétonne sur 20 blocs (boutiques, restos, bars), <strong>Playa Mamitas</strong> (animation), <strong>Playa Punta Esmeralda</strong> (cenote dans la mer, plus calme). <strong>Excursions</strong> depuis Playa : <strong>Tulum</strong> (45 min en collectivo ou bus ADO), <strong>Cenotes</strong> à explorer (Gran Cenote, Cenote Azul, Dos Ojos, Cenote Calavera), <strong>Isla Cozumel</strong> en ferry 45 min depuis le port (snorkeling sur la barrière Mésoaméricaine, 2e plus grande au monde après l'Australie), <strong>Sian Ka'an</strong> (réserve UNESCO), <strong>Xcaret</strong>. <strong>Akumal</strong> à 30 min pour nager avec les tortues. <strong>Tester</strong> tacos al pastor, ceviche, mezcal. Devenue très digital nomad : coworkings, scènes café, communauté française importante. Réservations Tulum à 4-6 mois en haute saison.",

    "tulum:fr": "Tulum a connu une explosion touristique depuis 2015 : ex-village de pêcheurs devenu destination Instagram et bohème-luxe. <strong>Mars est mon mois préféré</strong> (8.7/10) : 24-28°C, 34% de pluie, mer turquoise à 25°C. <strong>De mai à octobre</strong>, c'est la saison des pluies/cyclones : 31-74% de précipitations, sargasse possible (algues brunes échouées). <strong>De décembre à février</strong>, comptez 22-28°C : haute saison, hôtels boutique-luxe à 300-1500$/nuit (Be Tulum, Azulik, Casa Malca). <strong>Sites majeurs</strong> : <strong>Ruines mayas de Tulum</strong> (XIIIe-XVe siècle, l'un des rares sites mayas en bord de mer, partir tôt avant la chaleur et la foule), <strong>Plage Paradise</strong> (gratuite, l'une des plus belles du Mexique), <strong>Cenotes</strong> (Gran Cenote, Cenote Calavera, Cenote Crystal, Cenote Dos Ojos pour la plongée), <strong>Sian Ka'an</strong> (réserve UNESCO de 5300 km², lagunes, mangroves). <strong>Cobá</strong> à 45 min (ruines mayas dans la jungle, vélo recommandé pour traverser le site). <strong>Hotel Zone</strong> : 10 km de route entre la ville et la plage, location de vélo conseillée (5-10$/jour). <strong>Bohème spots</strong> : Hartwood (resto culte, 6 mois de réservation, 500$+ pour 2), Nomade (yoga retreat). <strong>Tester</strong> mezcal, ceviche, fish tacos. Sécurité : récente recrudescence de violence liée aux cartels (2023-2024), à vérifier. Aéroport <strong>Tulum International</strong> ouvert en décembre 2023 (avant : Cancún 2h).",

    "merida:fr": "Mérida est la capitale du Yucatán : 1 million d'habitants, ville coloniale espagnole construite sur les ruines de la cité maya T'ho. <strong>Janvier est mon mois préféré</strong> (8.6/10) : 19-28°C, 18% de pluie, climat doux après l'été infernal. <strong>De mars à août</strong>, comptez 22-36°C : chaleur extrême du Yucatán intérieur (parfois 42°C), Méridois qui sortent après 19h, plazas se réveillent au soir. <strong>De juin à octobre</strong>, c'est la saison des pluies : 39-57% de précipitations, mais répit relatif de la chaleur. <strong>Sites majeurs</strong> : <strong>Plaza Grande</strong> (Catedral San Idelfonso, Casa de Montejo, Palacio Municipal), <strong>Paseo de Montejo</strong> (avenue inspirée des Champs-Élysées, mansions XIXe), <strong>Mercado Lucas de Galvez</strong>, <strong>Gran Museo del Mundo Maya</strong>. <strong>Excursions</strong> : <strong>Chichén Itzá</strong> à 1h30 (UNESCO, lever de soleil pour éviter foule et chaleur), <strong>Uxmal</strong> à 1h (UNESCO, ruines puuc moins fréquentées que Chichén), <strong>Izamal</strong> à 1h (\"ville jaune\", couvent franciscain XVIe), <strong>Cenotes</strong> de Cuzamá (3 cenotes en train à mules), <strong>Celestún</strong> à 2h (flamants roses). <strong>Vendredi soir</strong> : musique en plein air sur Plaza Grande gratuite. <strong>Tester</strong> cochinita pibil (porc mariné dans achiote, cuit dans la terre), poc chuc, papadzules, sopa de lima, marquesitas. Devenue destination digital nomad croissante depuis 2020.",

    "puerto-vallarta:fr": "Puerto Vallarta est la station balnéaire chic de la côte Pacifique mexicaine : Sierra Madre Occidental qui plonge dans la mer, 250 000 habitants. <strong>Avril est mon mois préféré</strong> (9.5/10) : 18-27°C, 0% de pluie, mer à 24°C, températures parfaites avant l'été chaud. <strong>De novembre à mai</strong>, c'est la saison sèche : 0-8% de pluie, ciel constant, période américaine et canadienne (Snowbirds). <strong>De juin à octobre</strong>, c'est la saison des pluies/cyclones : 43-85% de précipitations, chaleur humide (24-31°C), risque cyclonique modéré (côté Pacifique moins exposé que Atlantique). <strong>Sites majeurs</strong> : <strong>Malecón</strong> (promenade en bord de mer de 1,5 km, sculptures, Los Arcos), <strong>Zona Romántica</strong> (vieille ville, Playa Los Muertos), <strong>Iglesia de Nuestra Señora de Guadalupe</strong> (église signature avec couronne en cuivre), <strong>Mercado Municipal</strong>. <strong>Plages</strong> : Playa Los Muertos (centre, animée), Conchas Chinas (plus calme), <strong>Yelapa</strong> (village accessible uniquement par bateau, 45 min, très tranquille). <strong>Sayulita</strong> à 45 min (village surfeur bohème), <strong>Marietas Islands</strong> en bateau (Playa Escondida, accès limité 116 visiteurs/jour), <strong>Sierra Madre</strong> pour canopy/zipline. <strong>Tester</strong> ceviche tostadas, birria de res, agua de jamaica. Communauté LGBT importante (Pride en mai). Vol direct depuis Paris-Mexico-PVR.",

    "patagonie:fr": "La Patagonie argentine, c'est l'extrême sud du continent sud-américain : steppes infinies, glaciers (Perito Moreno), montagnes (Fitz Roy, Cerro Torre), bout du monde (Ushuaia). <strong>Janvier est mon mois préféré</strong> (7.9/10) : 8-19°C, 31% de pluie, été austral, journées de 17h, glaciers accessibles, treks praticables (W et O à Torres del Paine côté chilien). <strong>Décembre-février</strong> sont la haute saison touristique : prix x2-x3, refuges complets 6 mois à l'avance pour Torres del Paine. <strong>De juin à août</strong> (hiver austral), comptez -1/4°C avec 18-21% de pluie : froid intense, mais c'est la saison de ski à Cerro Castor (Ushuaia) ou Cerro Catedral (Bariloche). Beaucoup d'hôtels et restos ferment hors saison. <strong>Octobre-novembre et mars-avril</strong> sont les vrais bons compromis : météo encore acceptable, foules réduites, prix en retrait. <strong>Sites majeurs</strong> : <strong>El Calafate</strong> (base pour Perito Moreno, navette au glacier, navigation Spegazzini), <strong>El Chaltén</strong> (capitale du trek argentin, Laguna de los Tres au pied du Fitz Roy 11 km, Laguna Torre 9 km), <strong>Ushuaia</strong> (\"fin du monde\", parc national Tierra del Fuego, Beagle Channel), <strong>Puerto Madryn</strong> (Péninsule Valdés, baleines juin-décembre, manchots, orques). Côté chilien : <strong>Torres del Paine</strong> (W trek 4-5 jours, O trek 7-9 jours). <strong>Tester</strong> asado argentin, cordero patagonico, vin Malbec.",

    "iguazu:fr": "Iguazu, ce sont les chutes les plus impressionnantes au monde (UNESCO) : 275 cataractes sur 2,7 km, 80m de haut, frontière Argentine-Brésil. <strong>Septembre est mon mois préféré</strong> (8.8/10) : 18-28°C, 28% de pluie, débit puissant après les pluies du sud, températures clémentes. <strong>De juin à août</strong> est la haute saison touristique : 15-28°C, 19-31% de pluie, idéal pour visiter mais foules massives. <strong>De décembre à février</strong> (été austral), comptez 23-32°C et 47-54% de pluie : chaleur étouffante (humidité tropicale), mais débit maximum après les pluies. <strong>Côté argentin</strong> (parc national Iguazú, 80% des chutes) : 3 circuits (Inférieur 1300m, Supérieur 1750m, Garganta del Diablo 1100m, train écologique inclus). Compter 1 journée complète. Pueblo Puerto Iguazú comme base. <strong>Côté brésilien</strong> (Foz do Iguaçu) : 1 seule passerelle panoramique de 1200m, vue d'ensemble plus spectaculaire mais expérience plus brève (3h). <strong>Aller voir les 2 côtés</strong> est l'idéal (compter 3 jours minimum). <strong>Excursions</strong> : <strong>Macuco Safari</strong> côté brésilien (bateau qui passe sous les chutes), <strong>Gran Aventura</strong> côté argentin (équivalent), <strong>vol en hélicoptère</strong> depuis le Brésil (160$, interdit côté argentin pour préserver la faune). <strong>Triple frontière</strong> Argentine-Brésil-Paraguay (Ciudad del Este pour le shopping détaxé). Aéroports : IGR (Argentine) et IGU (Brésil), 30 min de bus jusqu'aux parcs. Vol depuis Buenos Aires en 1h30.",

    "salvador-de-bahia:fr": "Salvador (de Bahia) est l'âme africaine du Brésil : 3 millions d'habitants, 1ère capitale du Brésil (jusqu'en 1763), héritage afro-brésilien (capoeira, candomblé, bossa nova). <strong>Octobre est mon mois préféré</strong> (8.2/10) : 24-28°C, 54% de pluie, fin de la saison humide. <strong>De mai à août</strong> (hiver austral), comptez 22-26°C et 71-80% de pluie : ciel souvent gris, mer agitée, mais températures supportables et prix réduits. <strong>De décembre à mars</strong> (été austral), comptez 25-29°C : chaleur tropicale, mer à 28°C, mais aussi <strong>Carnaval de Salvador</strong> (le plus grand au monde en termes de personnes, 6 jours en février, blocos afro Olodum/Ilê Aiyê dans les rues, prix x4). <strong>Sites majeurs</strong> : <strong>Pelourinho</strong> (UNESCO, vieille ville coloniale colorée, Largo do Pelourinho), <strong>Igreja de São Francisco</strong> (rococo couverte d'or, l'une des plus belles d'Amérique latine), <strong>Elevador Lacerda</strong> (ascenseur 72m entre ville haute et basse), <strong>Mercado Modelo</strong> (artisanat afro-brésilien). <strong>Plages</strong> : Porto da Barra (urbaine), Ondina, Stella Maris (plus loin). <strong>Itacaré</strong> et <strong>Morro de São Paulo</strong> à 2-4h pour des plages sauvages. <strong>Sécurité</strong> : Pelourinho touristique de jour mais demande vigilance la nuit, éviter sacs visibles, ne pas s'aventurer dans les favelas sans guide. <strong>Tester</strong> moqueca de peixe, acarajé (boules de niébé frites), feijoada, caipirinha. Capoeira et candomblé en spectacle public régulier.",

    "punta-cana:fr": "Punta Cana est la station balnéaire all-inclusive par excellence des Caraïbes : 60 km de plages de cocotiers à l'est de la République dominicaine. <strong>Mars est mon mois préféré</strong> (8.2/10) : 23-27°C, 52% de pluie, mer à 26°C. <strong>De juin à novembre</strong>, c'est la saison cyclonique : 64-78% de précipitations, risque ouragans (route principale Caraïbes), mais hors trajectoire principale en Punta Cana (côté Atlantique-est). <strong>De décembre à avril</strong>, comptez 23-29°C : haute saison nord-américaine et canadienne, prix hôteliers x2-x3. <strong>Sites majeurs</strong> : <strong>Plages</strong> Bávaro, Cabeza de Toro, El Cortecito (la plus animée), Macao (plus sauvage). <strong>Hoyo Azul</strong> (cenote turquoise à Scape Park), <strong>Saona</strong> et <strong>Catalina</strong> (excursions catamaran à des îlots-cartes postales), <strong>Isla Saona</strong> (pic touristique, départ depuis Bayahibe). <strong>Excursions ATV/buggy</strong> dans la campagne, <strong>plongée</strong> sur la côte est. <strong>Bavaro</strong> et <strong>Higüey</strong> sont les zones touristiques. <strong>Las Terrenas</strong> (Péninsule de Samaná) à 2h offre une atmosphère plus européenne et moins all-inclusive (importante communauté française). <strong>Santo Domingo</strong> à 2h (UNESCO, première ville européenne des Amériques 1496). <strong>Tester</strong> mangú (banane plantain), pollo guisado, sancocho, mama juana (rhum-vin-épices). Culture all-inclusive très dominante : peu d'incitation à sortir des resorts. Vol direct depuis Paris en 9h.",

    "medellin:fr": "Medellín, en Colombie, est passée de \"ville la plus dangereuse au monde\" (1991, 6500 homicides/an) à modèle d'urbanisme social (téléphériques pour les comunas, métro). <strong>Janvier est mon mois préféré</strong> (8.1/10) : 16-26°C, 51% de pluie, climat printanier permanent (la ville est appelée \"la ciudad de la eterna primavera\" car à 1500m d'altitude). <strong>De juin à août</strong>, comptez 16-27°C avec 57-74% de pluie : climat doux constant. <strong>De février à mai et septembre à novembre</strong>, ce sont les saisons des pluies : 70-89% de précipitations en averses d'après-midi (matinées souvent ensoleillées). <strong>Sites majeurs</strong> : <strong>Comuna 13</strong> (ex-quartier le plus violent, transformé par street art et escaliers mécaniques en plein air, tour guidé recommandé), <strong>Plaza Botero</strong> (23 sculptures de Fernando Botero), <strong>Museo de Antioquia</strong>, <strong>Pueblito Paisa</strong> (réplique de village antiochiens sur Cerro Nutibara), <strong>El Poblado</strong> (quartier branché, restos, nightlife à Parque Lleras), <strong>Laureles</strong> (alternative plus locale et calme). <strong>Excursions</strong> : <strong>Guatapé</strong> à 2h (pierres colorées, El Peñón à 740 marches pour la vue panoramique), <strong>Santa Fe de Antioquia</strong> à 1h30 (ville coloniale), <strong>Café triangle</strong> à 4h (haciendas, plantations de café UNESCO). <strong>Tester</strong> bandeja paisa (plat copieux : haricots, riz, viande, plantain, oeuf), arepas, chocolate caliente. Importante destination digital nomad : coworkings, communauté internationale.",

    "bahamas:fr": "Les Bahamas, c'est l'archipel de 700 îles à 80 km de la Floride : Nassau (capitale), Paradise Island (Atlantis Resort), Exumas (cochons nageurs). <strong>Mars est mon mois préféré</strong> (8.7/10) : 22-26°C, 27% de pluie, mer à 25°C, fin de la haute saison américaine. <strong>De juin à novembre</strong>, c'est la saison cyclonique : 58-66% de précipitations, risque ouragans réel (Dorian 2019 catégorie 5 a dévasté les Abacos). <strong>De décembre à mai</strong>, comptez 21-28°C : haute saison nord-américaine, prix hôteliers x2-x3. <strong>Sites majeurs</strong> : <strong>Nassau</strong> (capitale, Atlantis Resort à Paradise Island, Queen's Staircase, Pirates Museum), <strong>Junkanoo</strong> (carnaval bahaméen, 26 décembre et 1er janvier). <strong>Iles à explorer</strong> : <strong>Exumas</strong> (Pig Beach pour les cochons nageurs viraux, Thunderball Grotto où James Bond a tourné, Iguana Cay), <strong>Eleuthera</strong> (Pink Sands Beach, falaises Glass Window), <strong>Andros</strong> (la plus grande île, plongée Tongue of the Ocean, blue holes), <strong>Bimini</strong> (la plus proche de la Floride, Hemingway y vécut). <strong>Cruisers</strong> : Nassau est l'un des ports les plus fréquentés au monde par les croisières (plusieurs paquebots/jour). <strong>Tester</strong> conch fritters/salad (lambis), Bahama Mama cocktail, rock lobster. Devises : USD accepté partout (Bahamian dollar parité 1:1). Vol depuis Paris via Miami ou Atlanta.",

    "jamaique:fr": "La Jamaïque, terre du reggae (Bob Marley), du rhum, du Blue Mountain Coffee. <strong>Janvier est mon mois préféré</strong> (8.6/10) : 20-29°C, 30% de pluie, fin de la haute saison américaine. <strong>De juin à octobre</strong>, c'est la saison cyclonique : 67-81% de précipitations, risque ouragans réel. <strong>De décembre à avril</strong>, comptez 20-30°C : haute saison touristique nord-américaine, prix x2-x3. <strong>Sites majeurs</strong> : <strong>Negril</strong> (Seven Mile Beach, falaises Rick's Café au coucher du soleil), <strong>Montego Bay</strong> (touristique, all-inclusive, Doctor's Cave Beach), <strong>Ocho Rios</strong> (Dunn's River Falls 180m de cascades à grimper, Mystic Mountain bobsleigh), <strong>Port Antonio</strong> (côte est plus authentique, Blue Lagoon, Reach Falls), <strong>Kingston</strong> (capitale, Bob Marley Museum à Hope Road, Trench Town pour les fans), <strong>Blue Mountains</strong> (cafés mondialement réputés, Blue Mountain Peak 2256m, ascension 4h pour le lever du soleil). <strong>Sécurité</strong> : <strong>Kingston demande vigilance</strong> (certains quartiers à éviter), all-inclusive resorts généralement sécurisés, transports privés recommandés. <strong>Tester</strong> jerk chicken/pork (épice traditionnelle jerk), ackee and saltfish (plat national), patties, rum punch. <strong>Culture rasta</strong> : visible partout, marijuana décriminalisée (2 onces) mais pas légale. Vol direct Paris-Montego Bay (compagnies charter en saison).",

    "porto-rico:fr": "Porto Rico est un territoire américain dans les Caraïbes : 3 millions d'habitants, espagnol officiel + anglais, dollar US, plages, forêt tropicale (El Yunque). <strong>Janvier est mon mois préféré</strong> (8.3/10) : 22-28°C, 47% de pluie, fin de la haute saison américaine, températures clémentes. <strong>De juin à novembre</strong>, c'est la saison cyclonique : 56-74% de précipitations, risque ouragans réel (Maria 2017 catégorie 4 a dévasté l'île). <strong>De décembre à avril</strong>, comptez 22-29°C : haute saison américaine, prix x2-x3. <strong>Sites majeurs</strong> : <strong>San Juan</strong> (capitale, Vieux San Juan UNESCO, El Morro et San Cristóbal forts espagnols XVIe), <strong>El Yunque National Forest</strong> (la seule forêt tropicale du système US National Forests, Mount Britton 1075m, La Mina Falls), <strong>Vieques</strong> et <strong>Culebra</strong> (îles à 1h en ferry depuis Fajardo, plages Flamenco Beach et Playa Carlos Rosario les plus belles), <strong>Bioluminescent Bay</strong> à Vieques (Mosquito Bay, l'une des plus brillantes au monde, kayak nocturne), <strong>Ponce</strong> (vieille ville coloniale, parc Toro Negro), <strong>Camuy</strong> (caves de calcaire). <strong>Cuisine</strong> : mofongo (plantain écrasé), arroz con gandules, tostones, lechón asado, piña colada (cocktail inventé à San Juan en 1954). <strong>Bacardí</strong> (rhum, distillerie visitable près de San Juan). Vol direct Paris-San Juan en 9h.",

    "saint-lucie:fr": "Sainte-Lucie est une île volcanique des Caraïbes orientales : 600 km², 180 000 habitants, francophone par tradition (créole influencé par le français malgré l'indépendance britannique en 1979). Marquée par les <strong>Pitons</strong> (UNESCO, 2 sommets coniques de 700m et 800m). <strong>Mars-avril sont mes mois préférés</strong> (8.5/10) : 22-29°C, 41-46% de pluie, mer à 26°C. <strong>De juin à novembre</strong>, c'est la saison cyclonique : 60-73% de précipitations, risque ouragans (Tomas 2010 a marqué). <strong>De décembre à mai</strong>, comptez 21-28°C : haute saison touristique, prix hôteliers x2-x3. <strong>Sites majeurs</strong> : <strong>Pitons</strong> (Gros Piton 798m randonnable en 2-3h, Petit Piton 743m réservé alpinistes), <strong>Sulphur Springs</strong> à Soufrière (\"seul drive-in volcano du monde\"), <strong>Diamond Botanical Gardens</strong> et waterfalls, <strong>Anse Chastanet</strong> (resort luxe et plage), <strong>Marigot Bay</strong> (\"la plus belle baie des Caraïbes\" selon James Michener). <strong>Plages</strong> : Reduit Beach (Rodney Bay, animée), Anse des Sables (Vieux Fort), Anse Cochon (snorkeling). <strong>Soufrière</strong> = base pour explorer les Pitons. <strong>Castries</strong> = capitale, port croisière, marché. <strong>Saint-Lucia Jazz Festival</strong> en mai (l'un des plus connus des Caraïbes). <strong>Tester</strong> green fig and saltfish (plat national), accras de morue, cassava bread, rhum local. Sainte-Lucie est très réputée pour les voyages de noce (resorts romantiques type Sandals).",

    "turks-et-caicos:fr": "Turks-et-Caïcos sont un territoire britannique d'outre-mer : 8 îles principales, 38 000 habitants, plages parmi les plus blanches au monde (Grace Bay régulièrement #1 dans les classements). <strong>Mars est mon mois préféré</strong> (9.0/10) : 24-26°C, 21% de pluie, mer turquoise à 25°C, fin de la haute saison nord-américaine. <strong>De juin à novembre</strong>, c'est la saison cyclonique : 30-54% de précipitations, risque ouragans (Irma et Maria 2017 ont dévasté). <strong>De décembre à mai</strong>, comptez 24-27°C : haute saison touristique américaine, prix hôteliers très élevés (5 étoiles 600-2000$/nuit). <strong>Sites majeurs</strong> : <strong>Grace Bay Beach</strong> (12 km de plage à Providenciales, l'image emblématique), <strong>Chalk Sound</strong> (lagune turquoise spectaculaire), <strong>Conch Bar Caves</strong> à Middle Caicos, <strong>Salt Cay</strong> (île historique des marais salants, baleines à bosse en migration janvier-mars). <strong>Activités</strong> : plongée et snorkeling (3e plus grande barrière corallienne au monde), <strong>kitesurf</strong> à Long Bay, observation des baleines à bosse. <strong>Iles</strong> : Providenciales (la plus touristique avec aéroport principal), Grand Turk (capitale Cockburn Town), North/Middle Caicos (plus calmes), Salt Cay (la plus authentique). <strong>Économie</strong> : tourisme luxe + offshore banking. <strong>Tester</strong> conch (lambis) sous toutes formes, hominy grits. Vol direct Providenciales depuis Paris via Londres-Miami. Pas d'impôts sur revenu = destination favorite des nababs américains.",

    "aruba:fr": "Aruba fait partie des ABC islands (Aruba-Bonaire-Curaçao) : 32 km de longueur, 110 000 habitants, dépendance néerlandaise autonome, hors zone cyclonique (sud des Caraïbes). <strong>Février-mars sont mes mois préférés</strong> (8.6/10) : 25-29°C, 34-38% de pluie, alizés constants, mer à 27°C. <strong>De septembre à décembre</strong>, comptez 26-32°C avec 28-65% de précipitations : seule période où des averses sont fréquentes (mais souvent brèves). <strong>De décembre à avril</strong>, c'est la haute saison touristique américaine : prix hôteliers x2-x3. <strong>Toute l'année</strong> est praticable car hors zone ouragan : avantage majeur vs autres Caraïbes. <strong>Sites majeurs</strong> : <strong>Eagle Beach</strong> (régulièrement classée plage #2-3 des Caraïbes après Grace Bay), <strong>Palm Beach</strong> (plus animée, hôtels en bord), <strong>Arikok National Park</strong> (40% de l'île, paysages désertiques avec cactus, peintures rupestres, Natural Pool, Conchi), <strong>Oranjestad</strong> (capitale colorée néerlandaise), <strong>Baby Beach</strong> (lagune calme au sud), <strong>California Lighthouse</strong>, <strong>Alto Vista Chapel</strong>. <strong>Activités</strong> : kitesurf et windsurf à Fisherman's Hut (alizés constants), plongée (épave SS Antilla), 4×4 dans Arikok. <strong>Devise</strong> : AWG (florin) mais USD accepté partout, papiamento (créole local) + néerlandais + anglais + espagnol parlés. <strong>Tester</strong> keshi yena, pastechi, balashi (bière locale). Vol direct depuis Amsterdam (8h) ou via Curaçao.",

    "curacao:fr": "Curaçao est la plus grande des ABC islands : 444 km², 160 000 habitants, capitale Willemstad inscrite UNESCO pour son architecture coloniale néerlandaise (façades pastel). Hors zone cyclonique. <strong>Mars est mon mois préféré</strong> (8.6/10) : 25-29°C, 32% de pluie, alizés constants, mer à 26°C. <strong>De novembre à janvier</strong>, comptez 26-30°C avec 49-73% de précipitations : seule période vraiment humide. <strong>De février à octobre</strong>, climat sec stable. <strong>Toute l'année</strong> praticable. <strong>Sites majeurs</strong> : <strong>Willemstad</strong> (UNESCO, Punda et Otrobanda séparés par le Sint Anna Bay et le pont flottant Queen Emma Bridge), <strong>Christoffel National Park</strong> (Mount Christoffel 372m, point culminant), <strong>Shete Boka National Park</strong> (côte sauvage, blowholes), <strong>Hato Caves</strong>, <strong>Curaçao Sea Aquarium</strong>. <strong>Plages</strong> : <strong>Playa Kenepa Grandi</strong> (Grote Knip, classée parmi les plus belles des Caraïbes), <strong>Cas Abao</strong> (plage et plongée), <strong>Mambo Beach</strong> (animée), <strong>Playa Lagun</strong>. <strong>Activités</strong> : <strong>plongée</strong> (réputée mondiale, accessible directement de la plage, épave Tugboat), snorkeling. <strong>Curaçao Liqueur</strong> (visite distillerie Senior, liqueur aux écorces d'oranges Laraha), <strong>Klein Curaçao</strong> en bateau (île déserte). <strong>Tester</strong> stoba (ragoût), funchi (polenta), keshi yena, blue Curaçao cocktail. Néerlandais + papiamento + anglais + espagnol. Vol direct Amsterdam (10h).",

    "antigua:fr": "Antigua-et-Barbuda est un État indépendant des Petites Antilles : 280 km², 100 000 habitants. <strong>365 plages</strong> sur Antigua, c'est la promesse marketing (\"une plage par jour\"). <strong>Mars est mon mois préféré</strong> (8.4/10) : 24-28°C, 51% de pluie, mer à 25°C. <strong>De juin à novembre</strong>, c'est la saison cyclonique : 58-73% de précipitations, risque ouragans réel (Irma 2017 a dévasté Barbuda à 90%). <strong>De décembre à mai</strong>, comptez 24-29°C : haute saison touristique américaine et britannique. <strong>Sites majeurs</strong> : <strong>Nelson's Dockyard</strong> (UNESCO, base navale britannique XVIIIe restaurée à English Harbour, l'unique chantier naval géorgien encore en service au monde), <strong>Shirley Heights</strong> (vue panoramique sur English Harbour, soirées dimanche avec barbecue et orchestre steel band), <strong>Devil's Bridge</strong> (pont naturel rocheux à l'est), <strong>Pillars of Hercules</strong>. <strong>Plages</strong> : <strong>Half Moon Bay</strong> (en croissant), <strong>Dickenson Bay</strong> (animée, hôtels), <strong>Pigeon Point Beach</strong>, <strong>Darkwood Beach</strong>. <strong>Saint John's</strong> = capitale, port de croisière, marché. <strong>Antigua Sailing Week</strong> fin avril (l'une des plus prestigieuses régates au monde). <strong>Barbuda</strong> à 90 min en ferry : encore plus calme, Frigate Bird Sanctuary (5000 oiseaux nicheurs). <strong>Tester</strong> fungie (polenta, plat national), pepperpot, conch, ducana. Devise : Eastern Caribbean Dollar (XCD), USD accepté. Vol direct Londres/Frankfurt/Atlanta.",

    "bonaire:fr": "Bonaire est la plus petite et la plus calme des ABC islands : 290 km², 20 000 habitants, déclarée \"Marine Park\" en 1979 (l'une des premières au monde). Hors zone cyclonique. <strong>Mars est mon mois préféré</strong> (8.6/10) : 25-28°C, 39% de pluie, mer à 26°C. <strong>De septembre à décembre</strong>, comptez 26-31°C avec 31-72% de précipitations. <strong>De janvier à août</strong>, climat sec stable. <strong>Toute l'année</strong> est praticable car hors zone ouragan. <strong>Bonaire est avant tout une destination plongée</strong> : 86 sites accessibles directement depuis la plage (drive-in diving avec marqueurs en bord de route), réserve marine intégrale, biodiversité exceptionnelle (plus de 350 espèces de poissons), parmi les meilleurs spots au monde pour la plongée \"shore diving\" (sans bateau). <strong>Sites majeurs</strong> : <strong>Washington-Slagbaai National Park</strong> (40% de l'île au nord, paysages désertiques, point culminant Brandaris 240m, 4×4 nécessaire), <strong>Kralendijk</strong> (capitale colorée, taille village), <strong>Lac Bay</strong> (lagune protégée, kitesurf et windsurf, vents constants), <strong>Pekelmeer Sanctuary</strong> (flamants roses, plus grand site de nidification du sud des Caraïbes), <strong>Salt pans</strong> (marais salants colorés rose/bleu/blanc), <strong>Klein Bonaire</strong> (îlot inhabité accessible en eau-taxi). <strong>Tester</strong> goat stew, fish soup. Néerlandais + papiamento + anglais. Beaucoup moins touristique qu'Aruba ou Curaçao, ambiance dive resort. Vol direct depuis Amsterdam ou via Curaçao.",

    "dominique:fr": "La Dominique est l'\"île nature\" des Caraïbes : 750 km², 70 000 habitants, montagneuse (Morne Diablotin 1447m), volcanique, 365 rivières, forêts tropicales primaires. À ne pas confondre avec la République dominicaine. <strong>Mai est mon mois préféré</strong> (8.6/10) : 23-28°C, 41% de pluie, mer à 27°C. <strong>De juin à novembre</strong>, c'est la saison cyclonique : 59-74% de précipitations, risque ouragans réel (Maria 2017 a dévasté l'île à 90%). <strong>De janvier à avril</strong>, comptez 21-27°C : haute saison touristique. <strong>Sites majeurs</strong> : <strong>Morne Trois Pitons National Park</strong> (UNESCO, paysages volcaniques), <strong>Boiling Lake</strong> (lac d'eau bouillante, 2e plus grand au monde, randonnée 12h aller-retour, exigeante), <strong>Trafalgar Falls</strong> (cascades jumelles), <strong>Emerald Pool</strong> (bassin émeraude dans la forêt), <strong>Champagne Reef</strong> (bulles volcaniques sous-marines, snorkeling), <strong>Sari Sari Falls</strong>, <strong>Middleham Falls</strong>. <strong>Roseau</strong> = capitale, marché. <strong>Carib Territory</strong> à l'est (réserve des derniers descendants kalinago, peuple amérindien préhispanique). <strong>Whale watching</strong> (cachalots toute l'année, l'un des rares spots au monde avec présence permanente). <strong>Pas de tourisme de masse</strong> : pas de gros all-inclusive, hôtels eco-lodges et guesthouses. <strong>Tester</strong> mountain chicken (en fait grenouille géante, espèce protégée maintenant), callaloo, sancocho, rhum local Macoucherie. Vol via Antigua, Barbade ou Sainte-Lucie + petit avion 30 min.",

    "cayman-islands:fr": "Les Iles Caïmans sont un territoire britannique d'outre-mer : 3 îles (Grand Cayman, Cayman Brac, Little Cayman), 65 000 habitants, paradis fiscal (l'un des plus grands centres bancaires offshore au monde). <strong>Janvier-février sont mes mois préférés</strong> (8.0/10) : 25-28°C, 37-47% de pluie, mer à 26°C, alizés constants. <strong>De juin à octobre</strong>, c'est la saison cyclonique : 53-68% de précipitations, risque ouragans réel (Ivan 2004 catégorie 4 a dévasté). <strong>De décembre à mars</strong>, comptez 25-28°C : haute saison américaine, prix hôteliers très élevés (paradis fiscal = clientèle aisée). <strong>Sites majeurs</strong> : <strong>Seven Mile Beach</strong> (plage emblématique de Grand Cayman, classée parmi les plus belles des Caraïbes), <strong>Stingray City</strong> (banc de sable où on nage avec des raies pastenagues semi-domestiquées, excursion bateau), <strong>Bioluminescent Bay</strong> à Rum Point (plancton bioluminescent la nuit), <strong>Hell</strong> (formation rocheuse calcaire noire avec poste de Hell Town), <strong>George Town</strong> (capitale, port de croisière, duty-free shopping). <strong>Cayman Brac</strong> = falaises, plongée. <strong>Little Cayman</strong> = la plus calme (170 habitants), Bloody Bay Wall pour la plongée. <strong>Plongée</strong> : parmi les meilleurs spots au monde (Bloody Bay Wall, Kittiwake épave). <strong>Tester</strong> conch fritters, turtle stew (élevage Cayman Turtle Centre). Devise : Cayman Dollar (KYD = 1,20 USD). Vol direct depuis Londres ou Miami. Très cher (paradis fiscal).",

    "bermudes:fr": "Les Bermudes sont un territoire britannique d'outre-mer dans l'Atlantique Nord (à 1000 km de la Caroline du Nord, plus proche d'Halifax que de Miami) : 138 îles, 64 000 habitants. <strong>Mai est mon mois préféré</strong> (8.3/10) : 21-22°C, 35% de pluie, mer à 21°C (plus fraîche qu'aux Caraïbes), fin du printemps. <strong>De juin à août</strong>, comptez 24-28°C : été agréable, mer à 26°C. <strong>De septembre à novembre</strong>, c'est la saison des ouragans : 49-54% de précipitations, risque réel (Bermudes hors trajectoire principale Caraïbes mais peuvent être touchées). <strong>De décembre à avril</strong>, comptez 18-22°C et 34-49% de pluie : trop frais pour la baignade (mer à 18-20°C), mais hôtels à prix divisés par 3, golfs en pleine activité. <strong>Sites majeurs</strong> : <strong>Hamilton</strong> (capitale, Front Street colorée), <strong>Royal Naval Dockyard</strong> (West End, port de croisière, National Museum of Bermuda), <strong>St. George's</strong> (UNESCO, ancienne capitale fondée 1612, plus vieille colonie anglaise continue d'Amérique), <strong>Crystal Caves</strong> (grottes de calcaire spectaculaires), <strong>Horseshoe Bay Beach</strong> (sable rose emblématique), <strong>Tobacco Bay</strong> (snorkeling). <strong>Plages</strong> à <strong>sable rose</strong> : caractéristique des Bermudes (foraminifères). <strong>Plongée</strong> : 300+ épaves dans les eaux bermudiennes (\"capitale mondiale de la plongée d'épaves\"). <strong>Bermuda Triangle</strong> = sujet folklorique, pas de réalité touristique. <strong>Tester</strong> fish chowder (national dish), rum swizzle, dark 'n' stormy. Hors zone Caraïbe = devise BMD (parité 1:1 avec USD). Très cher : paradis fiscal/financier.",

    "florianopolis:fr": "Florianópolis (\"Floripa\" pour les Brésiliens) est la capitale de l'État de Santa Catarina au sud du Brésil : île principale (Ilha de Santa Catarina) reliée au continent par 2 ponts, 500 000 habitants, 42 plages, surf, ambiance jeune/branchée. <strong>Avril est mon mois préféré</strong> (8.1/10) : 20-25°C, 42% de pluie, fin de l'été austral, températures clémentes. <strong>De décembre à mars</strong> (été austral), comptez 22-28°C : pic touristique brésilien et argentin (Argentins viennent en masse, prix hôteliers x3-x4, plages bondées). <strong>De juin à août</strong> (hiver austral), comptez 14-21°C et 21-28% de pluie : frais (parfois fraîches matinées), mais soleil souvent au rendez-vous, prix divisés par 3, ambiance plus calme et locale. <strong>Sites majeurs</strong> : <strong>Plages</strong> Joaquina (surf, dunes), Praia Mole (animée, jeunes), Praia da Galheta (naturiste), Lagoinha do Leste (sauvage, accessible 1h de marche), <strong>Praia dos Ingleses</strong> (familiale), <strong>Barra da Lagoa</strong> (charmante), <strong>Lagoa da Conceição</strong> (lagune au centre, kitesurf, soirées). <strong>Centre historique</strong> côté continent (Mercado Público, Catedral). <strong>Île de Anhatomirim</strong> (forteresse, dauphins). <strong>Surf</strong> : Florianópolis accueille régulièrement des étapes du World Surf League. <strong>Tester</strong> ostras (huîtres locales, l'île est l'un des plus grands producteurs du Brésil), camarão na moranga (crevettes dans citrouille), açaí. Très importante destination digital nomad du Brésil."
}

with open(PATH, encoding='utf-8') as f:
    data_existing = json.load(f)

before = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

data_existing['_version'] = '2.0'
data_existing['_updated'] = '2026-04-27'

for k, v in AVIS_BATCH8_FR.items():
    data_existing[k] = v

after = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data_existing, f, ensure_ascii=False, indent=2)

print(f"Avis FR avant : {before}")
print(f"Avis FR après : {after}")
print(f"Nouveaux : {after - before}")

# Audit immédiat
import re
patterns_check = [
    ('em-dash', r'—'), ('guillemets', r'[«»]'),
    ('attendez-vous', r'attendez-vous à'),
    ('parfait', r'\bparfait[es]*\b'),
    ('fenêtre', r'\bfenêtre[s]?\b'),
    ('saturé', r'\bsatur[eéa]\w*\b'),
    ('se mérite', r'\bse méri[tes]+\b'),
    ('magique', r'\bmagiques?\b'),
    ('Si vous X:', r'Si vous \w+ : '),
    ('iconique', r'\biconique[s]?\b'),
    ('antithèse', r'antithèse'),
    ('mythique', r'\bmythique[s]?\b'),
    ('emblématique', r'\bemblématique[s]?\b'),
    ('authentique', r'\bauthentique[s]?\b'),
    ('féérique', r'\bféérique[s]?\b'),
    ("c'est aussi", r"[Cc]'est aussi"),
    ('à monitorer', r'à monitorer'),
    ('à éviter', r'à éviter'),
]

print("\n=== Audit batch 8 ===")
issues_total = 0
for slug in AVIS_BATCH8_FR.keys():
    plain = re.sub(r'<[^>]+>', '', data_existing[slug])
    issues = []
    for label, p in patterns_check:
        n = len(re.findall(p, plain))
        if n > 0:
            issues.append(f"{label}={n}")
            issues_total += n
    flag = "OK" if not issues else "PB " + ", ".join(issues)
    print(f"  {slug:<22} {len(plain.split()):>3}m {flag}")
print(f"\nTotal issues : {issues_total}")
