"""Batch 11 : 30 avis FR Tier 1 restants prioritaires (Moyen-Orient + Afrique Nord + Stations ski premium + Iles)."""
import json

PATH = 'data/avis_annuel.json'
data = json.load(open(PATH, encoding='utf-8'))

AVIS_BATCH11_FR = {
    "dubai:fr": "Dubai, c'est l'extravagance urbaine au cœur du désert : 3,5 millions d'habitants (90% expatriés), Burj Khalifa (828m, plus haut bâtiment au monde), Palm Jumeirah, malls climatisés. <strong>Mars est mon mois préféré</strong> (9.1/10) : 19-28°C, 7% de pluie, mer à 24°C, températures parfaites avant la canicule. <strong>De juin à septembre chutent à 2.2-3.5/10</strong> à cause de la chaleur extrême (26-43°C, parfois 50°C, humidité saturée le long du Golfe) : tout se passe en intérieur climatisé, plages désertes la journée, prix hôteliers réduits de 50%. <strong>De novembre à avril</strong>, c'est la haute saison : 17-32°C, prix x3, hôtels 5*+ complets. <strong>Sites majeurs</strong> : <strong>Burj Khalifa</strong> (At The Top 124e/148e étage, ou 152e/154e plus chers, réservation 2 semaines avant), <strong>Dubai Mall</strong> (1200 boutiques, aquarium, fontaines musicales), <strong>Old Dubai</strong> (Bastakia quartier historique, abra traversée du Creek pour 1 dirham), <strong>Palm Jumeirah</strong> (Atlantis, monorail), <strong>Burj Al Arab</strong> (l'unique hôtel \"7 étoiles\"), <strong>Souk de l'Or</strong> et <strong>Souk des Épices</strong> à Deira. <strong>Excursions désert</strong> : Dune bashing, dîner bédouin, sandboarding (200-400 AED). <strong>Tester</strong> shawarma, machbous, dattes Medjool, café arabe avec cardamome. Vol direct Paris en 7h.",

    "abu-dhabi:fr": "Abu Dhabi, capitale des Émirats arabes unis : 1,5 million d'habitants, plus calme et culturellement plus développée que Dubai (à 90 min de route). <strong>Décembre est mon mois préféré</strong> (9.2/10) : 17-27°C, 4% de pluie, températures parfaites, mer à 23°C. <strong>De juin à septembre chutent à 3.0-3.6/10</strong> à cause de la chaleur extrême (28-43°C, parfois 50°C, humidité saturée). <strong>De novembre à mars</strong>, c'est la haute saison : 15-30°C, prix x2-x3, événements culturels (Abu Dhabi Festival, Formule 1 fin novembre/début décembre). <strong>Sites majeurs</strong> : <strong>Sheikh Zayed Grand Mosque</strong> (l'une des plus grandes mosquées au monde, 40 000 fidèles, 96 colonnes, plus grand tapis et lustre Swarovski au monde, gratuite, abaya prêtée pour les femmes), <strong>Louvre Abu Dhabi</strong> (architecture Jean Nouvel, dôme métallique signature, partenariat avec Louvre Paris), <strong>Qasr Al Watan</strong> (palais présidentiel ouvert au public depuis 2019), <strong>Yas Island</strong> (Ferrari World, Yas Marina Circuit F1, Warner Bros World), <strong>Saadiyat Island</strong> (Louvre + futur Guggenheim Frank Gehry), <strong>Corniche</strong> (8 km de promenade en bord de mer). <strong>Empty Quarter (Liwa)</strong> à 2h pour le désert le plus pur. <strong>Tester</strong> luqaimat, harees, machbous. Vol direct Paris en 7h.",

    "le-caire:fr": "Le Caire, capitale égyptienne : 22 millions d'habitants en aire urbaine (la plus grande ville d'Afrique et du Moyen-Orient), chaos, dépaysement extrême, civilisation millénaire. <strong>Avril est mon mois préféré</strong> (9.4/10) : 15-30°C, 2% de pluie, températures parfaites pour visiter les pyramides. <strong>De novembre à avril</strong>, c'est la haute saison : 9-30°C, climat sec idéal. <strong>De juin à août</strong> chutent à 3.9-6.9/10 à cause de la canicule (22-38°C, parfois 45°C), <strong>khamsin</strong> (vent de sable) en avril-mai. <strong>De septembre à octobre</strong>, comptez 19-36°C : températures qui retombent. <strong>Sites majeurs</strong> : <strong>Plateau de Gizeh</strong> (3 pyramides Khéops/Khéphren/Mykérinos, Sphinx, à 30 min du centre, billets séparés pour entrer dans Khéops), <strong>Musée Égyptien</strong> place Tahrir (en cours de transfert vers le <strong>Grand Egyptian Museum</strong> près des pyramides, ouverture progressive depuis 2024, le plus grand musée d'archéologie au monde), <strong>Khan El-Khalili</strong> (souk historique XIVe), <strong>Citadelle de Saladin</strong> et Mosquée de Mohamed Ali, <strong>Vieux Caire copte</strong>, <strong>Mosquée Ibn Tulun</strong> (la plus ancienne du Caire, 879). <strong>Saqqara</strong> à 30 km (pyramide à degrés de Djoser, la plus ancienne du monde, 2700 av JC), <strong>Memphis</strong>. <strong>Sécurité</strong> : police touristique présente partout, harcèlement verbal courant pour les femmes. <strong>Tester</strong> kushari (plat national), foul, ta'meya (falafel égyptien), om ali. Vol direct Paris en 4h45.",

    "louxor:fr": "Louxor (ex-Thèbes), c'est la \"capitale historique de l'Égypte ancienne\" : 500 000 habitants sur les deux rives du Nil, sites pharaoniques les plus impressionnants au monde. <strong>Mars est mon mois préféré</strong> (8.8/10) : 14-29°C, 1% de pluie, température parfaite pour visiter les temples (chaleur encore supportable). <strong>De novembre à mars</strong>, c'est la haute saison : 9-29°C, climat sec idéal. <strong>De mai à septembre chutent à 3.2-3.3/10</strong> à cause de la canicule extrême (24-42°C, parfois 50°C en juillet-août, désert à proximité), température au sol dans la Vallée des Rois insupportable après 11h. <strong>Sites majeurs rive est</strong> : <strong>Temple de Karnak</strong> (le plus grand complexe religieux jamais construit, 134 colonnes géantes de la salle hypostyle, son et lumière le soir), <strong>Temple de Louxor</strong> (relié à Karnak par l'avenue des sphinx restaurée en 2021, magnifique le soir illuminé). <strong>Rive ouest</strong> : <strong>Vallée des Rois</strong> (62 tombeaux royaux dont Toutânkhamon, billet pour 3 tombeaux + supplément pour Toutânkhamon/Séthi I/Ramsès VI), <strong>Vallée des Reines</strong> (Néfertari), <strong>Temple d'Hatchepsout</strong> (Deir el-Bahari, 3 terrasses), <strong>Colosses de Memnon</strong>. <strong>Croisière sur le Nil</strong> Louxor-Assouan (3-4 nuits, l'une des expériences classiques d'Égypte, dahabieh à voile = version premium). <strong>Montgolfière</strong> au lever du soleil sur la Vallée des Rois (100-150€). <strong>Sécurité</strong> : Louxor reste parmi les villes les plus sûres d'Égypte (police touristique partout). Vol direct Le Caire-Louxor en 1h.",

    "marrakech:fr": "Marrakech (la \"ville rouge\" pour ses remparts en pisé), capitale touristique du Maroc : 950 000 habitants, Médina UNESCO, dunes du Sahara à 8h en voiture. <strong>Mai est mon mois préféré</strong> (9.3/10) : 15-30°C, 12% de pluie, températures parfaites. <strong>De juillet à août chutent à 3.9/10</strong> à cause de la canicule extrême (21-39°C, parfois 47°C, ressenti 50°C+) : impossible de visiter en milieu de journée, locaux qui sortent après 21h. <strong>De décembre à février</strong>, comptez 6-22°C : doux en journée mais frais le soir (riads ne sont pas chauffés), bonne période pour les sportifs (semi-marathon en janvier, Marrakech ouvre sa saison golf hivernal). <strong>Sites majeurs</strong> : <strong>Place Jemaa el-Fna</strong> (UNESCO patrimoine immatériel, charmeurs de serpents, conteurs, montreurs de singes, le soir transformée en gigantesque restaurant à ciel ouvert), <strong>Souks</strong> (épices, cuir, tapis, métaux), <strong>Mosquée Koutoubia</strong> (XIIe, sœur de la Giralda de Séville), <strong>Palais Bahia</strong> (XIXe, mosaïques), <strong>Tombeaux saadiens</strong>, <strong>Madrasa Ben Youssef</strong>, <strong>Jardin Majorelle</strong> (Yves Saint Laurent), <strong>Médersa Ben Youssef</strong>. <strong>Excursions</strong> : <strong>Atlas</strong> en jour (vallée de l'Ourika, Imlil, ascension Toubkal 4167m), <strong>Essaouira</strong> à 2h30 (côte atlantique, ambiance hippie), <strong>Désert de Merzouga/Erg Chebbi</strong> à 8h (2-3 jours en 4×4 avec nuit en bivouac). <strong>Tester</strong> tagines, couscous (le vendredi traditionnellement), pastilla, thé à la menthe. Vol direct Paris en 3h30.",

    "fes:fr": "Fès (Fez), capitale spirituelle du Maroc : 1,1 million d'habitants, 2 médinas UNESCO (Fès el-Bali fondée en 789 et Fès el-Jdid). La <strong>plus vieille ville médiévale habitée au monde</strong>, dédale de 9000 ruelles. <strong>Mai est mon mois préféré</strong> (9.4/10) : 14-28°C, 16% de pluie, températures parfaites. <strong>De juillet à août chutent à 3.9/10</strong> à cause de la canicule (20-38°C, parfois 45°C). <strong>De décembre à février</strong>, comptez 6-19°C : doux mais frais le soir, riads non chauffés. <strong>Sites majeurs</strong> : <strong>Médersa Bou Inania</strong> (XIVe, mérinide, l'une des plus belles d'Afrique du Nord), <strong>Université Quaraouiyine</strong> (859, plus vieille université en activité au monde selon UNESCO), <strong>Tannerie Chouara</strong> (UNESCO, panorama des cuves de teinture depuis les terrasses des marchands de cuir, brin de menthe contre l'odeur), <strong>Place Seffarine</strong> (place des chaudronniers), <strong>Bab Boujeloud</strong> (porte bleue d'entrée principale de la médina), <strong>Palais Royal</strong> (façade aux 7 portes). <strong>Quartier des potiers et tanneries</strong>, <strong>quartier juif (Mellah)</strong>, <strong>tombeaux mérinides</strong> (vue panoramique sur la médina au coucher du soleil). <strong>Logistique</strong> : <strong>se perdre dans la médina est inévitable</strong>, guide local recommandé pour la première fois (200-400 MAD/journée). <strong>Volubilis</strong> (UNESCO, ruines romaines) à 1h, <strong>Meknès</strong> (UNESCO, capitale impériale Moulay Ismaïl) à 1h, <strong>Chefchaouen</strong> à 4h. <strong>Tester</strong> pastilla au pigeon, harira, méchoui, msemen. Vol direct Paris-Fès en 3h.",

    "wadi-rum:fr": "Wadi Rum (\"Vallée de la Lune\"), c'est le désert de la Jordanie : 720 km² de paysages martiens (utilisé pour Lawrence d'Arabie 1962, Seul sur Mars 2015, Star Wars Rogue One et Rise of Skywalker, Dune 2021). <strong>Octobre est mon mois préféré</strong> (9.5/10) : 15-28°C, 2% de pluie, températures parfaites pour le désert. <strong>De septembre à novembre et mars-mai</strong> sont les meilleures périodes : 8-31°C, climat sec idéal. <strong>De juin à août</strong>, comptez 20-34°C : chaleur intense en journée (45°C+ possible), mais nuits fraîches dans le désert (15-20°C). <strong>De décembre à février</strong>, comptez 4-16°C : journées agréables mais nuits glaciales (parfois 0°C, neige rare mais possible), beaucoup de camps fonctionnent quand même avec chauffage. <strong>Activités</strong> : <strong>tour 4×4</strong> demi-journée ou journée (Lawrence Spring, Khazali Canyon, Burdah Bridge, dunes rouges, pétroglyphes nabatéens, 30-60€), <strong>balade à dos de chameau</strong> 1-3h, <strong>randonnée</strong> sur Jebel Khash ou Jebel Burdah, <strong>escalade</strong> (Wadi Rum est un spot d'escalade mondial sur grès). <strong>Nuit en camp bédouin</strong> = expérience indispensable : <strong>camp Bédouin classique</strong> (40-80€/nuit, tentes basiques, repas zarb cuit dans la terre), <strong>bubble tents</strong> (\"Mars camps\", domes transparents pour observer les étoiles, 100-300€/nuit). <strong>Logistique</strong> : Wadi Rum à 4h en bus de Amman, 1h de Petra, 1h d'Aqaba. Compter 2 jours/1 nuit minimum. Tour communautaire avec famille bédouine plutôt que tour-opérateur classique. <strong>Tester</strong> zarb, mansaf (plat national jordanien), thé à la sauge.",

    "cappadoce:fr": "La Cappadoce, en Anatolie centrale (Turquie) : paysages géologiques uniques (\"cheminées de fées\", tufs volcaniques sculptés par l'érosion), villes troglodytes UNESCO. <strong>Juillet est mon mois préféré</strong> (9.6/10) : 15-30°C, 3% de pluie, températures parfaites, ciel dégagé pour les <strong>vols en montgolfière au lever du soleil</strong> (l'expérience signature, 150-300€/personne). <strong>D'avril à octobre</strong>, c'est la haute saison : 5-31°C, vols en montgolfière praticables (mais météo capricieuse, 30-50% des vols annulés en intersaison). <strong>De décembre à mars</strong>, comptez -3/12°C avec 25-37% de précipitations souvent neige : Cappadoce sous la neige est <strong>spectaculaire</strong> (paysages féériques mais vols montgolfière souvent annulés, hôtels chauffés mais frais), prix divisés par 3. <strong>Sites majeurs</strong> : <strong>Göreme Open Air Museum</strong> (UNESCO, monastères et églises rupestres byzantines IXe-XIIe avec fresques), <strong>Vallées de randonnée</strong> : Vallée de l'Amour (formes phalliques), Vallée Rouge, Vallée Rose (au coucher du soleil), Vallée d'Ihlara (gorge de 14 km), <strong>Villes souterraines</strong> de Derinkuyu (8 niveaux, jusqu'à 20 000 personnes pouvaient s'y réfugier) ou Kaymakli, <strong>Uçhisar</strong> (forteresse rocheuse, vue panoramique), <strong>Avanos</strong> (poterie sur la rivière Halys), <strong>Pasabag</strong> (cheminées de fées avec chapeaux). <strong>Logistique</strong> : vol Istanbul-Kayseri (1h15) + 1h de transfert vers Göreme/Ürgüp. Hôtels troglodytes uniques (Museum Hotel, Sultan Cave Suites). 3-4 jours minimum pour bien profiter. <strong>Tester</strong> testi kebab (cuit dans cruche d'argile), gözleme.",

    "chefchaouen:fr": "Chefchaouen (la \"perle bleue\" du Rif marocain) : 40 000 habitants à 600m d'altitude dans les montagnes du nord, médina entièrement peinte en bleu (tradition juive du XVe siècle, popularisée par les réfugiés andalous). Devenue un phénomène Instagram depuis 2015. <strong>Juin est mon mois préféré</strong> (9.6/10) : 16-28°C, 12% de pluie, températures parfaites en altitude (10°C de moins qu'à Marrakech). <strong>De mai à septembre</strong>, c'est la haute saison : 12-34°C, climat doux grâce à l'altitude. <strong>De juillet à août</strong>, températures plus chaudes (19-34°C) mais supportables. <strong>De décembre à mars</strong>, comptez 5-16°C et 27-32% de pluie : froid pour le Maroc, riads non chauffés, mais médina sans foule (août = pic touristique avec 80% de touristes nationaux). <strong>Sites majeurs</strong> : <strong>Plaza Uta el-Hammam</strong> (place principale avec Kasbah XVe et son musée d'ethnographie, point de départ pour photographier les ruelles bleues), <strong>Plaza el-Makhzen</strong>, <strong>Grande Mosquée</strong> (visite extérieure uniquement), <strong>Quartier Souika</strong> (souk principal), <strong>Petit Tanguer</strong> et <strong>Bab Onsar</strong> (sources d'eau pour comprendre l'origine de la ville), <strong>Mosquée espagnole</strong> sur la colline (vue panoramique au coucher du soleil, 30 min de marche). <strong>Excursions</strong> : <strong>Akchour</strong> à 30 min (cascades, randonnée vers le Pont de Dieu), <strong>Talassemtane Park</strong> (cèdres et singes magot). <strong>Logistique</strong> : Chefchaouen accessible en bus depuis Tanger (3h), Fès (4h), pas d'aéroport (le plus proche : Tanger ou Tétouan). <strong>Tester</strong> tagines au poulet et citron confit, fromages de chèvre locaux, harira. Cannabis cultivé dans la région du Rif (origine du \"haschisch chefchaouen\", vente illégale mais omniprésente).",

    "zermatt:fr": "Zermatt, station de ski premium suisse au pied du <strong>Cervin</strong> (Matterhorn 4478m, le sommet le plus iconique des Alpes) : 5800 habitants, village sans voitures (taxis électriques, calèches), accessible uniquement en train depuis Täsch. <strong>Juillet est mon mois préféré</strong> (8.0/10) : 9-19°C, 36% de pluie, randonnée alpine en haute saison estivale. <strong>De juin à septembre</strong>, comptez 6-19°C : saison estivale randonnée (Cinq Lacs, Riffelsee avec reflet Cervin), VTT, escalade. <strong>De décembre à avril</strong>, comptez -7/2°C et 35-42% de précipitations souvent neige : c'est la haute saison ski (322 km de pistes reliées Zermatt-Cervinia transfrontalier Italie, ski d'été possible toute l'année à Plateau Rosa 3883m). <strong>De mai et octobre-novembre</strong> sont les intersaisons : peu de neige et peu de randos, beaucoup d'hôtels ferment 4-6 semaines. <strong>Sites majeurs</strong> : <strong>Gornergrat</strong> (3089m, train à crémaillère depuis 1898, panorama 29 sommets >4000m, vue Cervin/Mont Rose), <strong>Klein Matterhorn</strong> (3883m, plus haute station téléphérique d'Europe, glacier ski toute l'année), <strong>Sunnegga-Rothorn</strong> (panoramique côté lacs), <strong>Five Lakes Walk</strong> (5 lacs avec reflets du Cervin), <strong>Bahnhofstrasse</strong> (rue principale, hôtels palaces depuis 1854). <strong>Logistique</strong> : Zermatt à 3h30 de Genève en train (changement Visp). Très cher : repas resto 30-60€, ski pass 80€/jour, hôtels 150-1000€/nuit. <strong>Tester</strong> raclette, fondue, cervelas. <strong>Cervin</strong> ascension par les guides locaux (1500€/personne, 4 jours d'acclimatation, niveau alpinisme avancé).",

    "verbier:fr": "Verbier, station ski premium suisse au cœur des 4 Vallées : 3000 habitants permanents (15 000 en saison), village authentique (vieux chalets en bois) à 1500m. Réputée pour ses pistes engagées et son hors-piste légendaire. <strong>Août est mon mois préféré</strong> (7.8/10) : 9-20°C, 44% de pluie en orages, randonnée et VTT (DH Verbier festival mondial fin juillet/début août). <strong>De juin à septembre</strong>, comptez 6-20°C : saison estivale, paragliding, golf 18 trous (Les Esserts, le plus haut d'Europe à 1800m), Verbier Festival musique classique mi-juillet à début août. <strong>De décembre à avril</strong>, comptez -8/4°C et 43-58% de précipitations souvent neige : c'est la haute saison ski (412 km de pistes 4 Vallées Verbier+Nendaz+Veysonnaz+Thyon+La Tzoumaz). <strong>Hors-piste</strong> mondial : <strong>Vallon d'Arbi</strong>, <strong>Stairway to Heaven</strong>, <strong>Mont-Fort</strong> (3330m, sommet du domaine, glacier). <strong>Xtreme Verbier</strong> (compétition freeride en mars-avril, finale du Freeride World Tour, sur le Bec des Rosses face nord, l'une des descentes hors-piste les plus dingues au monde). <strong>Logistique</strong> : Verbier à 2h de Genève en voiture, 3h en train + bus depuis Le Châble. Très cher : repas resto 30-50€, ski pass 70€/jour, hôtels 200-800€/nuit en haute saison. <strong>Public</strong> : ski elite européen et britannique (Verbier surnommée \"Britney's playground\" pour la jet-set anglaise), Adolescents royaux suédois et belges. <strong>Tester</strong> raclette valaisanne, fondue moitié-moitié, vin valaisan (Fendant, Petite Arvine).",

    "courchevel:fr": "Courchevel, station de ski premium française : 4 villages en altitude (Courchevel 1850 le plus chic, 1650 Moriond, 1550 Village, 1300 Le Praz), partie des <strong>Trois Vallées</strong> (le plus grand domaine skiable au monde avec 600 km de pistes reliées : Courchevel + Méribel + Val Thorens). <strong>Juillet est mon mois préféré</strong> (7.6/10) : 8-19°C, 54% de pluie en orages d'altitude, randonnée et VTT. <strong>De juin à septembre</strong>, comptez 4-19°C : saison estivale (mais Courchevel est avant tout hivernale, beaucoup d'établissements fermés). <strong>De décembre à avril</strong>, comptez -9/6°C et 40-67% de précipitations souvent neige : c'est la haute saison ski. <strong>Courchevel 1850</strong> = capitale mondiale du luxe ski : 8 hôtels 5*+ Palaces (Cheval Blanc, Les Airelles, K2 Palace), 8 restos étoilés Michelin (record mondial pour une station), boutiques Hermès, Louis Vuitton, Cartier, hélicoptères pour Genève. Russes et Saoudiens en clientèle dominante depuis 2000. <strong>Pistes</strong> : 150 km Courchevel seul, 600 km 3 Vallées, dénivelé 1900m, 102 remontées. <strong>Saulire</strong> (2700m, panorama Mont Blanc), descente sur Méribel par la <strong>Dou des Lanches</strong>. <strong>Aéroport altiport</strong> Courchevel = l'une des pistes d'atterrissage les plus dangereuses au monde (525m, en pente), réservé jets privés. <strong>Tester</strong> tartiflette, génépi, fromages savoyards (Beaufort, Reblochon). <strong>Logistique</strong> : Courchevel à 2h de Lyon en voiture, train Paris-Moûtiers + bus 30 min ou taxi. Très cher : ski pass 75€/jour, hôtels 300-3000€/nuit en haute saison.",

    "val-d-isere:fr": "Val d'Isère, station ski premium française : 1850m, 1600 habitants permanents, fondée en 1934 par les pionniers du ski Émile Allais et Charles Diebold. Reliée à Tignes par <strong>l'Espace Killy</strong> (300 km de pistes, du nom de Jean-Claude Killy né ici, triple champion olympique 1968). <strong>Août est mon mois préféré</strong> (7.7/10) : 8-19°C, 42% de pluie en orages, randonnée alpine, ski d'été sur le glacier du Pisaillas (à mi-juin à mi-juillet). <strong>De décembre à avril</strong>, comptez -10/6°C et 41-58% de précipitations souvent neige : c'est la haute saison ski, l'une des plus enneigées des Alpes (8m/an), <strong>Critérium de la Première Neige</strong> (Coupe du Monde alpin) début décembre. <strong>Pistes Espace Killy</strong> : 78 pistes (300 km), dénivelé 1900m, 88 remontées, glacier de la Grande Motte 3450m côté Tignes. <strong>Pistes mythiques</strong> : <strong>Face de Bellevarde</strong> (descente JO Albertville 1992 hommes, l'une des plus dures au monde), <strong>OK Piste</strong> (slalom géant). <strong>Hors-piste</strong> : Tour du Charvet, Vallon des Aiguilles, accessible avec guide. <strong>Public</strong> : skieurs sportifs (techniciens), Britanniques très nombreux, ambiance plus authentique que Courchevel mais aussi très chère. <strong>Architecture</strong> : centre village respecte le style savoyard (chalets en pierre, bois, lauze) après l'erreur béton des années 70. <strong>Tester</strong> tartiflette, fondue, croziflette, vin de Savoie. <strong>Logistique</strong> : Val d'Isère à 3h de Lyon en voiture (route en lacets), train Paris-Bourg-Saint-Maurice + bus 1h30. Hôtels 200-1500€/nuit en haute saison.",

    "meribel:fr": "Méribel, station ski française au cœur des <strong>Trois Vallées</strong> : 1700m, 1900 habitants permanents, fondée en 1938 par le Britannique Peter Lindsay (architecture chalets traditionnels savoyards strictement réglementés). Considérée comme \"la station la plus authentique des 3 Vallées\". <strong>Juillet est mon mois préféré</strong> (8.0/10) : 10-21°C, 47% de pluie en orages, randonnée alpine, VTT, golf (18 trous, l'un des plus beaux d'Europe à 1700m). <strong>De juin à septembre</strong>, comptez 6-21°C : saison estivale tranquille (peu de touristes hors saison ski). <strong>De décembre à avril</strong>, comptez -8/5°C et 39-66% de précipitations souvent neige : c'est la haute saison ski. <strong>Pistes 3 Vallées</strong> : 600 km au total, Méribel = 150 km en propre, position centrale idéale pour basculer sur Courchevel ou Val Thorens dans la même journée. <strong>Saulire</strong> (2700m, frontière naturelle avec Courchevel). <strong>Snowpark Plattières</strong> (l'un des meilleurs des Alpes). <strong>JO Albertville 1992</strong> : Méribel a accueilli les épreuves de hockey féminin (Patinoire Olympique encore en service). <strong>Public</strong> : familles aisées françaises et britanniques (Méribel a la plus grande communauté britannique des Alpes françaises avec Val d'Isère). Plus chic que Val Thorens, moins ostentatoire que Courchevel. <strong>Hôtels</strong> : Le Coucou, Le Mont Vallon, Allodis (4-5*, 200-1500€/nuit). <strong>Tester</strong> diots aux pommes, beaufort, génépi. <strong>Logistique</strong> : Méribel à 2h de Lyon, train Paris-Moûtiers + bus 35 min.",

    "st-anton:fr": "St. Anton am Arlberg, station ski autrichienne : 2500 habitants à 1300m, considérée comme le <strong>berceau du ski alpin moderne</strong> (Hannes Schneider y a fondé la première école de ski moderne en 1907, technique \"Arlberg\" qui a révolutionné l'apprentissage). Reliée à Lech-Zürs-Stuben par <strong>Ski Arlberg</strong> (305 km de pistes reliées, le plus grand domaine d'Autriche). <strong>Août est mon mois préféré</strong> (7.5/10) : 12-21°C, 66% de pluie en orages d'altitude. <strong>De décembre à avril</strong>, comptez -6/7°C et 44-69% de précipitations souvent neige : c'est la haute saison ski, l'une des plus enneigées d'Autriche (8m/an), <strong>après-ski légendaire</strong> (Krazy Kanguruh, MooserWirt = bars de réputation mondiale, ambiance jusqu'à 22h après l'effort). <strong>Pistes mythiques</strong> : <strong>Stuben Albona</strong> (versant nord ombragé, neige conservée), <strong>Valluga</strong> (2811m, accessible en téléphérique pour skieurs avec guide uniquement, ski freeride légendaire). <strong>Hors-piste</strong> : Backside, Maroitäli, Schindlerkar (avec guide obligatoire). <strong>St. Christoph</strong> au-dessus de St. Anton = village quasi désert avec hôtel Arlberg Hospiz (5* historique). <strong>Public</strong> : skieurs sportifs et techniciens (notion de \"piste rouge à St. Anton = noire ailleurs\"), Britanniques, Allemands. Moins chic que Lech ou Verbier, plus festif. <strong>Logistique</strong> : St. Anton à 1h30 de Innsbruck en train, 2h de Zürich. Hôtels 150-500€/nuit, ski pass 70€/jour. <strong>Tester</strong> Tiroler Gröstl, Käsespätzle, Kaiserschmarrn, schnaps.",

    "kitzbuhel:fr": "Kitzbühel, station ski autrichienne : 8500 habitants à 760m (basse altitude), village médiéval coloré encore intact (\"la perle des Alpes\"). Réputée mondialement pour la <strong>Hahnenkamm</strong> (la descente de Coupe du Monde la plus dangereuse au monde, mi-janvier). <strong>Août est mon mois préféré</strong> (7.8/10) : 13-24°C, 57% de pluie en orages, randonnée, VTT, golf (4 parcours dont l'Eichenheim 18 trous). <strong>De décembre à avril</strong>, comptez -6/9°C et 41-50% de précipitations souvent neige : c'est la haute saison ski, mais altitude basse = enneigement parfois capricieux (canons à neige nécessaires en début de saison, glaciers à proximité = Kitzsteinhorn 2-3 vallées plus loin). <strong>Pistes</strong> : 233 km KitzSki (Kitzbühel-Kirchberg-Jochberg-Pass Thurn), dénivelé 1500m. <strong>Hahnenkamm</strong> (1665m, descente \"Streif\" 3312m, dénivelé 860m, vitesse 145 km/h sur la Mausefalle, fauve les meilleurs descendeurs au monde, mi-janvier weekend). <strong>Pistes mythiques</strong> : Streif (la fameuse, classée noire mais ouverte aux skieurs hors événement), Ganslern. <strong>Hors-piste</strong> avec guide : Bichlalm, Kitzbüheler Horn. <strong>Vieille ville médiévale</strong> XVIe (l'une des mieux conservées des Alpes), boutiques de luxe, gastronomie étoilée. <strong>Public</strong> : aristocratie autrichienne et allemande, Britanniques. <strong>Tester</strong> Wiener Schnitzel, Kaiserschmarrn, Apfelstrudel, glühwein. <strong>Logistique</strong> : Kitzbühel à 1h30 de Innsbruck, 1h30 de Salzburg, gare directe Vienne. Hôtels 150-1000€/nuit (Hotel zur Tenne, Gasthof Pension Eckart).",

    "lech:fr": "Lech am Arlberg, station ski autrichienne ultra-chic : 1500 habitants à 1450m, <strong>quotas de skieurs limités</strong> à 14 000 par jour (l'une des seules stations au monde avec quota volontaire pour préserver l'expérience). Reliée à Zürs-St. Anton par Ski Arlberg (305 km). <strong>Juillet est mon mois préféré</strong> (5.3/10) : 9-19°C, 65% de pluie en orages d'altitude. Lech reste avant tout une station hivernale. <strong>De décembre à avril</strong>, comptez -8/5°C et 42-68% de précipitations souvent neige : c'est la haute saison ski, l'une des plus enneigées d'Europe (10m/an, Arlberg = le \"berceau de la neige\"). <strong>Pistes</strong> : 305 km Ski Arlberg avec Zürs-St. Anton-Stuben, 87 remontées. <strong>White Ring</strong> = circuit de 22 km à skier en boucle (Lech-Zürs-Zug-Lech), record du monde de skieurs en circuit annuel. <strong>Hors-piste</strong> : Mehlsack, Madloch, Roggspitze (avec guide). <strong>Pistes mythiques</strong> : Schindlergrat, Auenfeldjet (téléphérique entre Lech et Warth pour 340 km de pistes au total). <strong>Public</strong> : ultra-chic (Hôtels Aurelio, Almhof Schneider, Krone, 5*+, 500-3000€/nuit), aristocratie européenne et orientale, Néerlandais et Belges fortunés. <strong>Famille royale néerlandaise</strong> y vient depuis des décennies (Princesse Friso accident fatal en 2012). <strong>Wellness</strong> : tous les 5* ont leurs spas signature (cher = 100€+/séance). <strong>Tester</strong> Käsespätzle, Wiener Schnitzel. <strong>Logistique</strong> : Lech à 2h de Zürich, 1h30 d'Innsbruck.",

    "davos:fr": "Davos, station ski et ville suisse : 11 000 habitants à 1560m (la plus haute ville d'Europe), connue mondialement pour le <strong>Forum Économique Mondial</strong> mi-janvier (4 jours, chefs d'État et CEO mondiaux, sécurité maximale, ville fermée). <strong>Août est mon mois préféré</strong> (7.6/10) : 9-20°C, 53% de pluie en orages, randonnée, VTT, golf, Davos Festival musique classique. <strong>De juin à septembre</strong>, comptez 6-20°C : saison estivale très active (Davos est aussi station thermale historique, sanatoriums du XIXe pour la tuberculose). <strong>De décembre à avril</strong>, comptez -9/5°C et 40-50% de précipitations souvent neige : c'est la haute saison ski. <strong>Davos-Klosters</strong> : 320 km de pistes répartis sur 6 domaines distincts (Parsenn le principal, Jakobshorn pour le snowboard, Pischa, Madrisa, Rinerhorn, Schatzalp), 1 seul ski pass. <strong>Parsenn</strong> = piste fameuse de 12 km de descente (le record du monde de pistes longues). <strong>Davos vs Klosters</strong> : Davos plus urbaine (hôtels en immeubles), Klosters plus chic et villageoise (résidences royales britanniques). <strong>Le Magic Mountain</strong> de Thomas Mann (1924) se passe dans un sanatorium de Davos. <strong>Public</strong> : skieurs sportifs en hiver, milieu d'affaires et politique mi-janvier (Forum), curistes en été. <strong>Tester</strong> fondue, raclette, viande des Grisons (Bündnerfleisch). <strong>Logistique</strong> : Davos à 2h30 de Zürich en train (le Glacier Express passe à proximité). <strong>Patinoire</strong> de Davos = berceau du Spengler Cup (tournoi de hockey de Noël depuis 1923).",

    "cortina-dampezzo:fr": "Cortina d'Ampezzo, \"la Reine des Dolomites\" : 6000 habitants à 1224m, station ski premium italienne entourée des sommets dolomitiques (Tofana 3244m, Cinque Torri, Faloria). UNESCO depuis 2009. Co-organisera les <strong>JO d'hiver 2026</strong> avec Milan. <strong>Juillet est mon mois préféré</strong> (7.4/10) : 11-21°C, 75% de pluie en orages d'altitude, randonnée Dolomites (Tre Cime di Lavaredo l'iconique, accessible depuis Cortina), via ferrata. <strong>De juin à septembre</strong>, comptez 8-21°C : saison estivale très active, climbing, mountain bike. <strong>De décembre à avril</strong>, comptez -7/9°C et 24-50% de précipitations souvent neige : haute saison ski, mais altitude moyenne (1224m) = enneigement parfois moyen au village (canons à neige nécessaires), bonnes conditions en altitude (Tofana 2900m, Faloria). <strong>Pistes</strong> : 120 km Cortina, 1200 km Dolomiti Superski (12 stations reliées par 1 forfait), <strong>Sellaronda</strong> (circuit 26 km autour du Sella, l'une des expériences ski les plus mythiques au monde). <strong>Pistes</strong> : Olympia (descente femmes JO 1956), Vertigine (épreuves Coupe du Monde). <strong>Cinque Torri</strong> = museum à ciel ouvert sur la Première Guerre mondiale (front italo-autrichien). <strong>Public</strong> : aristocratie italienne (Veneti et Milanais), tournages cinéma (Pink Panther 1963, Cliffhanger 1993, James Bond Pour vos yeux seulement 1981). <strong>Hôtels</strong> : Cristallo Resort, Rosapetra Spa, Miramonti Majestic (5*, 200-1500€/nuit). <strong>Tester</strong> canederli, casunziei (raviolis betterave), polenta, speck, vin Lagrein. <strong>Logistique</strong> : Cortina à 2h30 de Venise en bus, 3h de Milan.",

    "ile-maurice:fr": "L'île Maurice, état insulaire de l'océan Indien : 2000 km², 1,3 million d'habitants (créoles, indiens, chinois, européens), francophone (héritage colonial), île volcanique entourée de lagons turquoise et de barrières de corail. <strong>Octobre est mon mois préféré</strong> (7.7/10) : 17-23°C, 63% de pluie. L'île Maurice ne dépasse jamais 7.7/10 (climat tropical avec pluies fréquentes). <strong>De mai à novembre</strong>, c'est l'hiver austral : 16-25°C, mer à 22-26°C, période plus sèche (58-69% de précipitations), idéale pour le surf à Le Morne, baleines à bosse mi-juillet à mi-novembre. <strong>De décembre à avril</strong>, c'est l'été austral : 20-26°C, mer à 26-28°C, mais aussi <strong>saison cyclonique</strong> (5-7 cyclones/saison, 1-2 majeurs touchent l'île). <strong>Sites majeurs</strong> : <strong>Le Morne Brabant</strong> (UNESCO, péninsule sud-ouest, montagne 556m, plage signature de Maurice avec illusion d'optique de cascade sous-marine), <strong>Chamarel</strong> (terres aux 7 couleurs, géologie unique), <strong>Black River Gorges National Park</strong> (singes macaques, randonnées), <strong>Île aux Cerfs</strong> (excursion bateau, plage paradisiaque mais bondée), <strong>Belle Mare</strong> (côte est, plages sauvages), <strong>Trou aux Biches</strong> (côte nord, station balnéaire), <strong>Port-Louis</strong> (capitale, Caudan Waterfront, marché central, jardin de Pamplemousses). <strong>Activités</strong> : kitesurf à Le Morne (vent constant), plongée (Cathedral à Flic en Flac), golf (50% des hôtels luxe ont leur parcours), nage avec dauphins à Tamarin. <strong>Tester</strong> rougail saucisse, vindaye, dholl puri, gâteau patate. <strong>Maison Eureka</strong> à Moka pour l'architecture coloniale. Vol direct Paris en 11h.",

    "seychelles:fr": "Les Seychelles, archipel de 115 îles dans l'océan Indien : 100 000 habitants (créoles), capitale Victoria à Mahé. Considéré comme l'une des destinations balnéaires les plus chères au monde. <strong>Mars est mon mois préféré</strong> (7.8/10) : 24-26°C, 60% de pluie. Les Seychelles ne dépassent jamais 7.8/10 (climat équatorial avec pluies fréquentes mais brèves). <strong>D'avril à octobre</strong>, c'est la saison sèche relative (alizés du sud-est) : 60-76% de précipitations en averses brèves, mer à 26°C. <strong>De novembre à mars</strong>, c'est la saison humide (mousson nord-ouest) : 64-80% de précipitations, mer à 28°C, plus chaude pour la baignade. <strong>Hors zone cyclonique</strong> (les Seychelles sont très près de l'équateur). <strong>3 îles principales à connaître</strong> : <strong>Mahé</strong> (capitale Victoria, plus grande île, Beau Vallon plage la plus connue, jardin botanique avec coco-fesse), <strong>Praslin</strong> (Vallée de Mai UNESCO avec coco-fesse géants endémiques, Anse Lazio régulièrement classée plus belle plage du monde, Anse Georgette), <strong>La Digue</strong> (l'image carte postale, Anse Source d'Argent avec ses rochers de granit signature, vélo seul moyen de transport). <strong>Excursions</strong> : <strong>Aldabra Atoll</strong> (UNESCO, 100 000 tortues géantes, accessible uniquement en croisière 5-10 jours, ultra-isolé), <strong>Curieuse Island</strong> (tortues géantes en semi-liberté), <strong>Coco Island Marine Park</strong> (snorkeling). <strong>Hôtels</strong> : Four Seasons Mahé, Six Senses Zil Pasyon (Félicité), North Island, Constance Lemuria (Praslin), 800-5000€/nuit. <strong>Tester</strong> kari koko, ladob, fish curry. Vol direct Paris-Mahé en 10h.",

    "reunion:fr": "La Réunion, département français d'outre-mer dans l'océan Indien : 2500 km², 870 000 habitants, île volcanique avec 3 cirques UNESCO (Mafate, Salazie, Cilaos), <strong>Piton de la Fournaise</strong> (volcan en éruption permanente). <strong>Septembre est mon mois préféré</strong> (7.3/10) : 9-16°C en montagne / 23-26°C littoral, 42% de pluie. La Réunion a 2 climats radicalement différents : Est (Au Vent) très pluvieux toute l'année, Ouest (Sous le Vent) plus sec et ensoleillé. <strong>De mai à novembre</strong>, c'est l'hiver austral : 17-23°C en montagne / 22-25°C littoral, période la plus sèche, baleines à bosse mi-juillet à mi-octobre. <strong>De décembre à avril</strong>, c'est l'été austral : 14-19°C en montagne / 24-30°C littoral, saison cyclonique (3-5 cyclones/saison), baignade très agréable mais aussi <strong>requins</strong> (interdiction de baignade en dehors des lagons protégés depuis crise requins 2011, 11 morts depuis). <strong>Sites majeurs</strong> : <strong>Piton de la Fournaise</strong> (2632m, accessible en 4×4 + randonnée 6h aller-retour, l'un des plus actifs au monde, dernière éruption sur l'enclos), <strong>Cirque de Mafate</strong> (accessible uniquement à pied, hélicoptère ou portage, GR R2 pour traverser, refuges dans îlets isolés), <strong>Cirque de Salazie</strong> (Hell-Bourg classé), <strong>Cirque de Cilaos</strong> (route aux 400 virages), <strong>Piton des Neiges</strong> (3070m, point culminant de l'océan Indien, ascension 8h aller-retour, lever du soleil mythique au sommet), <strong>Saint-Denis</strong> (capitale, architecture créole), <strong>Saint-Gilles</strong> (lagon, station balnéaire). <strong>Tester</strong> rougail saucisse, cari poulet, samoussas, rhum arrangé.",

    "majorque:fr": "Majorque (Mallorca), la plus grande des Baléares : 3640 km², 950 000 habitants, dominée par les montagnes de la Serra de Tramuntana (UNESCO). Très internationalement diverse (Allemands en majorité, Britanniques, Scandinaves, Français). <strong>Juin est mon mois préféré</strong> (9.6/10) : 20-28°C, 15% de pluie, mer à 22°C, foules encore raisonnables. <strong>Juillet-août chutent à 6.9/10</strong> à cause de la chaleur (23-32°C) et surtout de la <strong>foule estivale extrême</strong> : 18 millions de visiteurs/an, surtourisme avéré (plages bondées, embouteillages, prix x4-x5). <strong>De décembre à février</strong>, comptez 8-16°C et 19-24% de pluie : doux pour l'Espagne, beaucoup d'hôtels et restos ferment, golf en pleine activité (Européens du Nord en hivernage). <strong>Régions</strong> : <strong>Palma</strong> (capitale, Cathédrale gothique, Vieille ville, Es Baluard musée d'art moderne), <strong>Serra de Tramuntana</strong> (Sóller en train historique en bois, Valldemossa où Chopin et George Sand ont passé l'hiver 1838-39, Deià village d'artistes), <strong>Cap Formentor</strong> au nord (route en lacets vers le phare, point de vue spectaculaire), <strong>Alcudia</strong> (vieille ville romaine, plage 14 km), <strong>Cabrera Archipelago</strong> (parc national au sud, accessible en bateau), <strong>Coves del Drac</strong> (grottes avec lac souterrain et concert de musique classique), <strong>Magaluf</strong> (réputation peu enviable, jeunes Britanniques, à éviter pour qui cherche le calme). <strong>Plages</strong> : <strong>Es Trenc</strong> (sauvage, sud), <strong>Cala Mondrago</strong> (parc naturel), <strong>Cala Macarella</strong> (déjà à Minorque), <strong>Cala Deia</strong>. <strong>Tester</strong> ensaimada, tumbet, sobrasada, vins de Binissalem. Mai et septembre-octobre sont les meilleurs compromis tourisme/météo.",

    "ibiza:fr": "Ibiza, deuxième plus grande des Baléares après Majorque : 572 km², 160 000 habitants, célèbre mondialement pour la <strong>fête</strong> (clubs de Pacha, Amnesia, Ushuaïa, Hï) ET sa face cachée beaucoup plus calme (UNESCO 1999 pour la biodiversité marine, vieille ville Dalt Vila et nécropole punique). <strong>Juin est mon mois préféré</strong> (9.7/10) : 20-27°C, 8% de pluie, mer à 22°C, début de la saison clubs (mi-juin à fin septembre), foules encore raisonnables. <strong>Juillet-août chutent à 6.9/10</strong> à cause de la chaleur (23-30°C) et surtout de la <strong>foule extrême</strong> : prix x5-x10 (entrée club 60-100€, bouteille au club 300-2000€, nuits Pacha entre 100 et 500€), réservations 6 mois avant. <strong>De décembre à mars</strong>, comptez 10-17°C et 15-22% de pluie : 90% des clubs et restos ferment, île presque déserte (\"Ibiza off-season\" prisée des amateurs de calme). <strong>Sites majeurs</strong> : <strong>Dalt Vila</strong> (Eivissa, UNESCO, vieille ville fortifiée, cathédrale, panorama au coucher du soleil), <strong>Es Vedrà</strong> (rocher mythique au sud-ouest, vue depuis Cala d'Hort), <strong>Ses Salines</strong> (parc naturel, marais salants, plage longue), <strong>Cala Comte / Cala Bassa</strong> (couchers de soleil mythiques au Café Mambo et Café del Mar à San Antonio), <strong>Cala Salada / Cala Saladeta</strong>, <strong>Es Cavallet</strong> (plage gay-friendly), <strong>Cala Llonga</strong>. <strong>Formentera</strong> à 30 min en ferry (île plus calme, plages turquoise comme aux Caraïbes). <strong>Hippie market</strong> à Punta Arabí (mercredi) et Las Dalias (samedi) - héritage 60s. <strong>Tester</strong> bullit de peix, sofrit pagès, hierbas ibicencas. Mai et septembre-octobre = meilleurs compromis pour fête + météo.",

    "mykonos:fr": "Mykonos, île la plus festive et la plus chic des Cyclades : 86 km², 10 000 habitants permanents (200 000 en saison), réputée pour ses plages party (Paradise, Super Paradise) et ses villages blancs typiquement cycladiques. <strong>Juillet est mon mois préféré</strong> (9.7/10) : 23-27°C, 0% de pluie, mer à 24°C, mais aussi pic touristique absolu. <strong>De juin à septembre</strong>, c'est la haute saison : 21-28°C, prix hôteliers x4-x10 (suite au Belvedere ou Cavo Tagoo : 800-5000€/nuit), restos plage à 200-500€/personne (Scorpios, Nammos). <strong>De novembre à mars</strong>, comptez 10-18°C : 70% des hôtels et restos ferment, ferries depuis Athènes-Pirée espacés (2-3/semaine au lieu de 5-10/jour), île quasi désertée (couples grec en escapade weekend). <strong>Sites majeurs</strong> : <strong>Chora</strong> (capitale, ruelles blanches labyrinthe pour perdre les pirates au XVIe, Petite Venise = maisons sur la mer, vue couchers de soleil), <strong>Moulins de Kato Mili</strong> (4 moulins XVIe blancs sur la colline), <strong>Plages</strong> : Paradise et Super Paradise (party 24h/24 en saison, beach clubs, ambiance LGBT à Super Paradise), Psarou (très chic, Nammos), Platis Gialos (familiale), Elia, Kalafati (plus calmes), Agios Sostis (sauvage, accessible à pied, naturiste). <strong>Délos</strong> à 30 min en bateau (UNESCO, lieu de naissance d'Apollon, ruines exceptionnelles, fermé au coucher du soleil pour préservation). <strong>Tester</strong> louza (saucisson local), kopanisti (fromage piquant), amygdalota (douceurs). Mai et septembre-octobre sont les meilleurs compromis foule/météo. Vol direct Athènes-Mykonos (35 min) ou ferry depuis Le Pirée (3-5h selon catamaran).",

    "crete:fr": "La Crète est la plus grande île grecque (8300 km², 600 000 habitants) : montagnes, gorges, plages, héritage minoen 4000 ans. <strong>Juin-juillet sont mes mois préférés</strong> (9.4/10) : 20-31°C, 5-14% de pluie, mer à 24°C. <strong>Août chute à 6.9/10</strong> à cause de la canicule (22-31°C), foule estivale (Italiens, Allemands), prix x3-x4. <strong>De décembre à février</strong>, comptez 7-16°C et 37-43% de pluie : doux pour la France mais beaucoup de petits hôtels ferment, sommets enneigés (les Lefka Ori 2452m offrent même du ski au refuge Kallergi). <strong>Régions</strong> : <strong>Héraklion</strong> (capitale, base pour Knossos), <strong>La Canée (Chania)</strong> (vieille ville vénitienne, port pittoresque, considérée plus belle ville crétoise), <strong>Réthymnon</strong> (forteresse, plage), <strong>Agios Nikolaos / Elounda</strong> (zone luxe à l'est, nombreux 5*+ Domes Resorts), <strong>Sitia</strong> (extrême est, palmeraie de Vai). <strong>Sites majeurs</strong> : <strong>Knossos</strong> (palais minoen reconstruit par Sir Arthur Evans, polémique sur la \"reconstruction-fantasy\", à compléter par le Musée Archéologique d'Héraklion), <strong>Gorges de Samaria</strong> (16 km, 5-7h, ouverture mai-octobre, l'une des plus longues d'Europe, à descendre vers Agia Roumeli), <strong>Plages</strong> : Elafonissi (sable rose, lagon turquoise, surfréquentée), Balos (sable blanc, accès en bateau ou randonnée), Vai (palmeraie, plus grande d'Europe), Falasarna (couchers de soleil). <strong>Tester</strong> dakos (salade), moussaka, kalitsounia, raki crétois (eau-de-vie offerte avec fierté). <strong>Spinalonga</strong> (île ex-léproserie, sujet du livre L'île de Victoria Hislop). Mai et septembre-octobre sont les meilleurs compromis tourisme/météo.",

    "la-havane:fr": "La Havane, capitale cubaine : 2 millions d'habitants, ville-musée bloquée dans les années 50 (embargo américain depuis 1962, voitures américaines vintage, immeubles coloniaux délabrés mais charmants). <strong>Février est mon mois préféré</strong> (8.8/10) : 21-29°C, 23% de pluie, fin de la saison sèche, températures parfaites. <strong>De décembre à avril</strong>, c'est la haute saison : 20-31°C, climat sec relatif, prix hôteliers x2-x3. <strong>De juin à novembre</strong>, c'est la saison cyclonique : 51-73% de précipitations, risque ouragans réel (Irma 2017 catégorie 5 a touché Cuba), chaleur lourde (24-33°C). <strong>De mai et octobre-novembre</strong> sont les intersaisons. <strong>Sites majeurs</strong> : <strong>Habana Vieja</strong> (UNESCO, 4 places fondatrices : Plaza de la Catedral, Plaza Vieja, Plaza San Francisco, Plaza de Armas), <strong>Malecón</strong> (8 km de promenade en bord de mer, point de rendez-vous des Cubains au coucher du soleil), <strong>Capitole</strong> (réplique du Capitole de Washington), <strong>Vedado</strong> (quartier moderne 50s, hôtel Nacional, Coppelia ice cream), <strong>Miramar</strong> (ambassades, embarcadère ferry pour Floride en 1958, plus depuis), <strong>Forteresses</strong> Castillo de la Real Fuerza, Morro, Cabaña (canonnade rituelle 21h chaque soir depuis 1762). <strong>Bars</strong> Hemingway : <strong>La Bodeguita del Medio</strong> (mojito), <strong>El Floridita</strong> (daiquiri), Hemingway a vécu dans la finca Vigía à San Francisco de Paula (musée). <strong>Tester</strong> ropa vieja (boeuf effiloché), moros y cristianos, congrí, tostones, daiquiri, mojito, ron Havana Club. <strong>Sécurité</strong> : Habana Vieja sûre de jour, vigilance la nuit. Économie cubaine en grave crise (pénuries chroniques, double monnaie supprimée 2021, inflation 200%+).",

    "buenos-aires:fr": "Buenos Aires, capitale argentine : 15 millions d'habitants en aire urbaine, \"Paris d'Amérique du Sud\", héritage européen massif (Italiens et Espagnols), tango, viande, Maradona/Messi. <strong>Janvier-décembre sont mes mois préférés</strong> (9.1/10) : 21-28°C, 26-27% de pluie, été austral, journées de 14h, terrasses pleines à Palermo, asados (BBQ argentins). <strong>De juin à août</strong> (hiver austral), comptez 8-16°C et 19-26% de pluie : doux pour l'hiver mais frais (Argentins ressentent comme froid), saison de tango et opéra (Teatro Colón). <strong>D'avril à mai et septembre-novembre</strong> sont les meilleures intersaisons : 11-24°C, jacarandas en fleurs en novembre. <strong>Quartiers majeurs</strong> : <strong>San Telmo</strong> (vieux quartier bohème, marché aux antiquités le dimanche, ballades de tango en plein air), <strong>La Boca</strong> (Caminito coloré, stade Bombonera de Boca Juniors, touristique mais à voir), <strong>Recoleta</strong> (chic, cimetière où repose Eva Perón, MALBA musée d'art latino-américain), <strong>Palermo</strong> (Soho/Hollywood divisions branchées, restos, nightlife), <strong>Puerto Madero</strong> (docks réhabilités, zone moderne), <strong>Centre</strong> (Avenida 9 de Julio = \"plus large avenue du monde\" 16 voies, Obélisque, Casa Rosada, Plaza de Mayo). <strong>Tango</strong> : milongas (bars de tango pour danser, La Catedral plus authentique), spectacles touristiques (Café Tortoni). <strong>Tester</strong> asado (parilla La Cabrera, Don Julio), empanadas, choripán, dulce de leche, alfajores, vin Malbec. <strong>Football</strong> : River Plate vs Boca Juniors = Superclasico le plus passionné au monde. <strong>Tigre</strong> à 1h pour les delta du Paraná en barque. Vol direct Paris-Buenos Aires en 14h.",

    "moscou:fr": "Moscou, capitale russe : 12 millions d'habitants, mégapole d'Europe orientale, climat continental extrême. <strong>Août est mon mois préféré</strong> (8.3/10) : 14-23°C, 25% de pluie, parcs en pleine vie (Gorky Park, VDNKh), terrasses, journées de 16h. <strong>De juin à août</strong>, c'est la haute saison estivale : 12-24°C, températures parfaites. <strong>De décembre à février</strong>, comptez -9/-2°C avec 30-43% de précipitations souvent neige : vrai hiver russe, jours à 7h de lumière, mais Moscou sous la neige est <strong>magnifique</strong> (cathédrales colorées, patinoires Red Square, marchés de Noël), métro chauffé, hôtels à prix divisés par 2. <strong>De mars-avril et octobre-novembre</strong> sont les transitions difficiles (boue, ciel gris, températures variables). <strong>Sites majeurs</strong> : <strong>Place Rouge</strong> (UNESCO, <strong>Cathédrale Saint-Basile</strong> aux coupoles colorées, <strong>Mausolée Lénine</strong> encore visitable, <strong>GUM</strong> grand magasin historique), <strong>Kremlin</strong> (UNESCO, palais présidentiel, cathédrales orthodoxes, armurerie avec collection d'œufs Fabergé), <strong>Métro de Moscou</strong> (l'un des plus beaux au monde, palais souterrains marbre/mosaïques/lustres, stations Komsomolskaya, Mayakovskaya, Novoslobodskaya). <strong>Bolchoï</strong> (opéra et ballet, réservation 3 mois avant, billets 50-300€). <strong>Galerie Tretyakov</strong> (art russe), <strong>Musée Pouchkine</strong> (art occidental). <strong>Quartiers</strong> : Arbat (rue piétonne touristique), Patriarshie Prudy (chic, branché), Tverskaya (luxe). <strong>Tester</strong> bortsch, pelmeni, blinis avec caviar, vodka. <strong>Important</strong> : depuis l'invasion de l'Ukraine (février 2022), <strong>visa russe difficile à obtenir pour les Européens</strong>, vols directs Paris-Moscou suspendus (escale obligatoire via Istanbul ou Dubai), restrictions financières (cartes Visa/Mastercard non acceptées en Russie).",

    "saint-petersbourg:fr": "Saint-Pétersbourg, ancienne capitale impériale russe (1712-1918) : 5 millions d'habitants, fondée par Pierre le Grand en 1703 sur les marais de la Neva, surnommée la \"Venise du Nord\" pour ses 800 ponts et 42 îles. UNESCO 1990. <strong>Juin est mon mois préféré</strong> (8.0/10) : 12-20°C, 36% de pluie, c'est la saison des <strong>Nuits Blanches</strong> (mi-juin à mi-juillet, soleil presque jamais couché, 19h de jour, festivals nocturnes, ouverture des ponts levants 1h-5h pour laisser passer les bateaux), pic touristique. <strong>De juillet à août</strong>, comptez 14-22°C : haute saison, journées encore très longues. <strong>De décembre à mars</strong>, comptez -7/2°C avec 31-46% de précipitations souvent neige : Saint-Pétersbourg sous la neige est <strong>magnifique</strong> (palais impériaux, Neva gelée, mais jours à 5h de lumière fin décembre, dépression saisonnière courante chez les habitants). <strong>D'octobre-novembre et avril</strong>, comptez -4/9°C : transitions humides et grises. <strong>Sites majeurs</strong> : <strong>Musée de l'Ermitage</strong> (l'un des plus grands musées au monde, 3 millions d'objets, Palais d'Hiver des tsars en lui-même chef-d'œuvre), <strong>Cathédrale Saint-Sauveur sur le Sang Versé</strong> (style traditionnel russe, mosaïques), <strong>Cathédrale Saint-Isaac</strong> (4e plus grande cathédrale au monde, observatoire au sommet), <strong>Place du Palais</strong>, <strong>Perspective Nevski</strong> (4,5 km d'avenue principale), <strong>Forteresse Pierre-et-Paul</strong> (où sont enterrés les Romanov), <strong>Mariinski</strong> (opéra et ballet, prestige mondial). <strong>Excursions</strong> : <strong>Peterhof</strong> (\"Versailles russe\", fontaines spectaculaires), <strong>Tsarskoïe Selo / Pouchkine</strong> (Catherine Palace avec sa Salle d'Ambre reconstituée). <strong>Important</strong> : visa russe difficile pour les Européens depuis 2022, escales obligatoires."
}

with open(PATH, encoding='utf-8') as f:
    data_existing = json.load(f)

before = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

data_existing['_version'] = '2.2'
data_existing['_updated'] = '2026-04-28'

for k, v in AVIS_BATCH11_FR.items():
    data_existing[k] = v

after = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data_existing, f, ensure_ascii=False, indent=2)

print(f"Avis FR avant : {before}")
print(f"Avis FR après : {after}")
print(f"Nouveaux : {after - before}")

# Audit immédiat
import re
patterns_check = [
    ('em-dash', r'—'), ('guillemets', r'[«»]'),
    ('attendez-vous', r'attendez-vous à'),
    ('parfait', r'\bparfait[es]*\b'),
    ('fenêtre', r'\bfenêtre[s]?\b'),
    ('saturé', r'\bsatur[eéa]\w*\b'),
    ('se mérite', r'\bse méri[tes]+\b'),
    ('magique', r'\bmagiques?\b'),
    ('Si vous X:', r'Si vous \w+ : '),
    ('iconique', r'\biconique[s]?\b'),
    ('antithèse', r'antithèse'),
    ('mythique', r'\bmythique[s]?\b'),
    ('emblématique', r'\bemblématique[s]?\b'),
    ('authentique', r'\bauthentique[s]?\b'),
    ('féérique', r'\bféérique[s]?\b'),
    ("c'est aussi", r"[Cc]'est aussi"),
    ('à monitorer', r'à monitorer'),
    ('à éviter', r'à éviter'),
]

print("\n=== Audit batch 11 ===")
issues_total = 0
for slug in AVIS_BATCH11_FR.keys():
    plain = re.sub(r'<[^>]+>', '', data_existing[slug])
    issues = []
    for label, p in patterns_check:
        n = len(re.findall(p, plain))
        if n > 0:
            issues.append(f"{label}={n}")
            issues_total += n
    flag = "OK" if not issues else "PB " + ", ".join(issues)
    print(f"  {slug:<22} {len(plain.split()):>3}m {flag}")
print(f"\nTotal issues : {issues_total}")
