"""Batch 16 : 19 avis FR Tier 2 Amérique du Sud + Caraïbes (option C)."""
import json

PATH = 'data/avis_annuel.json'

AVIS_BATCH16_FR = {
    "belem:fr": "Belém, capitale de l'<strong>État du Pará</strong> au nord du Brésil : 1,5 million d'habitants à l'embouchure de l'<strong>Amazone</strong> sur l'Atlantique, porte d'entrée de la forêt amazonienne brésilienne. Climat équatorial humide constant toute l'année. <strong>D'août à octobre sont mes mois préférés</strong> (6.9/10) : 24-32°C, 43-52% de pluie, c'est la saison la moins humide. Belém ne dépasse jamais 6.9/10 (climat tropical extrême). <strong>De janvier à mai</strong>, c'est la saison des pluies : 90-99% de précipitations, mais averses brèves d'après-midi (90 min en moyenne) puis ciel dégagé. <strong>De juin à juillet et novembre-décembre</strong> sont les saisons intermédiaires : 56-80% de pluie. <strong>Sites majeurs</strong> : <strong>Marché Ver-o-Peso</strong> (\"voir le poids\", marché central depuis l'époque coloniale, le plus grand marché en plein air d'Amérique latine, fruits amazoniens, herbes médicinales, açaí en sirop, poissons d'eau douce dorada/tucunaré), <strong>Mangal das Garças</strong> (parc écologique avec hérons et ibis), <strong>Estação das Docas</strong> (anciens entrepôts portuaires reconvertis en restaurants/bars en bord de fleuve), <strong>Forte do Presépio</strong> (forteresse XVIIe à l'origine de la fondation de la ville en 1616), <strong>Basilique Notre-Dame de Nazareth</strong> (lieu du <strong>Círio de Nazaré</strong> 2e dimanche d'octobre, l'une des plus grandes processions catholiques au monde, 2 millions de fidèles), <strong>Théâtre da Paz</strong> (XIXe néoclassique). <strong>Excursions amazoniennes</strong> : <strong>Île de Marajó</strong> en bateau 3h (la plus grande île fluvio-marine du monde, plages, buffles, plus grande population de buffles d'Asie en dehors de l'Asie), bateau-cargo vers Manaus 4-5 jours sur l'Amazone (expérience inoubliable). <strong>Tester</strong> tucupi (jus de manioc fermenté), tacacá (soupe), maniçoba (cassoulet amazonien), açaí cremeux (consommé local salé pas comme açaí en occident), pirarucu (poisson d'eau douce géant 3m).",

    "bogota:fr": "Bogotá, capitale de la <strong>Colombie</strong> : 8 millions d'habitants à <strong>2640m d'altitude</strong> sur la cordillère andine, l'une des capitales les plus hautes au monde (après La Paz, Quito, Sucre). Climat \"d'éternel printemps\" sans saisons marquées. <strong>Septembre est mon mois préféré</strong> (8.0/10) : 8-20°C, 31% de pluie, ciel souvent dégagé. <strong>De décembre à mars</strong>, c'est la saison sèche : 8-20°C, 31-49% de pluie, températures stables (Bogotá ne sort jamais des 8-20°C, indépendamment du mois). <strong>De mars à mai et octobre-novembre</strong>, c'est la saison des pluies : 54-79% de précipitations, averses fréquentes l'après-midi. <strong>Toute l'année</strong>, l'altitude (2640m) provoque parfois <strong>soroche</strong> (mal des montagnes léger) les premiers jours - boire mate de coca local ou éviter alcool/effort initialement. <strong>Sites majeurs</strong> : <strong>La Candelaria</strong> (vieille quartier colonial, ruelles colorées avec graffitis, ambiance bohème), <strong>Plaza Bolívar</strong> (cathédrale, Palais de Justice avec pavillons, Capitole), <strong>Monserrate</strong> (3152m, funiculaire ou téléphérique 7 min, panorama 360° sur la ville et la cordillère, sanctuaire pèlerinage), <strong>Musée de l'Or</strong> (Museo del Oro, l'une des plus grandes collections au monde d'orfèvrerie précolombienne, 34 000 pièces or, l'incontournable de Bogotá), <strong>Musée Botero</strong> (œuvres de Fernando Botero offertes à la ville, peintures et sculptures rondes signature), <strong>Quartier Usaquén</strong> (marché des puces dimanche, restos branchés au nord). <strong>Excursions</strong> : <strong>Cathédrale de sel de Zipaquirá</strong> à 50 km au nord (cathédrale catholique sculptée dans une mine de sel à 200m sous terre), <strong>Lac de Guatavita</strong> (origine de la légende d'<strong>El Dorado</strong>), <strong>Vallée de Cocora</strong> à 4h en bus (palmiers à cire de 60m). <strong>Sécurité</strong> : Bogotá demande vigilance (vols à l'arraché surtout en transports publics, taxis officiels Easy Taxi/Uber recommandés). <strong>Tester</strong> ajiaco (soupe pommes de terre-poulet-maïs), arepa, tamales, café colombien (l'un des meilleurs au monde, à boire chez Juan Valdez ou Café San Alberto).",

    "bolivie:fr": "La Bolivie, pays sud-américain enclavé entre Pérou-Brésil-Paraguay-Argentine-Chili : 12 millions d'habitants, l'un des pays les plus diversifiés d'Amérique du Sud (Andes 6500m + Amazone + désert atacamien). <strong>La Paz</strong> est la capitale administrative à <strong>3640m</strong> (la plus haute capitale au monde) et <strong>Sucre</strong> la capitale constitutionnelle. <strong>D'août à novembre sont mes mois préférés</strong> (7.5-7.7/10) : 1-18°C en altitude, 7-42% de pluie, c'est la <strong>saison sèche</strong> idéale (ciel dégagé indispensable pour photos du Salar d'Uyuni). <strong>De mai à octobre</strong>, c'est la haute saison touristique : -5/17°C en altitude, 7-31% de pluie, climat sec et froid. <strong>De décembre à mars</strong>, c'est la saison des pluies : 60-69% de précipitations, mais le <strong>Salar d'Uyuni inondé devient miroir géant</strong> (un des paysages les plus spectaculaires au monde, à voir entre janvier et avril). <strong>Sites majeurs</strong> : <strong>Salar d'Uyuni</strong> (10 582 km², le plus grand désert de sel au monde à 3656m d'altitude, sortie 3 jours en 4x4 depuis Uyuni avec nuit dans hôtel de sel + Lagune Colorée + flamants roses + Lagune Verte + geysers Sol de Mañana 5000m), <strong>Lac Titicaca</strong> (3812m, partagé avec le Pérou, Île du Soleil légende d'origine inca, Copacabana sanctuaire de la Vierge), <strong>La Paz</strong> (téléphérique urbain le plus long du monde 30 km, El Alto à 4150m vue panoramique sur les Andes, Marché des Sorcières Mercado de las Brujas), <strong>Sucre</strong> (UNESCO, capitale constitutionnelle, ville blanche coloniale), <strong>Potosí</strong> (UNESCO, ancienne plus grande ville du monde XVIe-XVIIe grâce aux mines d'argent du Cerro Rico, encore en exploitation aujourd'hui dans des conditions très difficiles), <strong>Madidi National Park</strong> (l'un des parcs amazoniens les plus biodiverses au monde). <strong>Tester</strong> salteñas (chausson empanada), api (boisson chaude maïs violet), llajwa (sauce piquante), singani (eau-de-vie).",

    "caracas:fr": "Caracas, capitale du <strong>Venezuela</strong> : 2,5 millions d'habitants à 900m d'altitude dans une vallée encaissée de la <strong>Cordillera de la Costa</strong>. Le Venezuela traverse une crise politique, économique et sociale majeure depuis 2013 (hyperinflation, exode massif de 7 millions de Vénézuéliens, gouvernement Maduro contesté), Caracas est aujourd'hui considérée comme l'une des villes les plus dangereuses au monde (taux d'homicide parmi les plus élevés). <strong>Conseillers voyage</strong> : la plupart des pays occidentaux <strong>déconseillent formellement</strong> les voyages au Venezuela depuis 2017. <strong>Février est mon mois préféré</strong> (8.5/10) : 18-26°C, 27% de pluie, période la plus sèche. <strong>De décembre à avril</strong>, c'est la saison sèche : 18-27°C, 27-58% de pluie, climat agréable. <strong>De mai à novembre</strong>, c'est la saison des pluies : 49-84% de précipitations, mais températures stables (18-27°C, climat tropical d'altitude). <strong>Sites majeurs</strong> (à connaître théoriquement, prudence requise pour tout déplacement) : <strong>Plaza Bolívar</strong> (centre historique colonial), <strong>Cathédrale de Caracas</strong>, <strong>Casa Natal de Bolívar</strong> (lieu de naissance du \"Libertador\" Simón Bolívar 1783), <strong>El Ávila</strong> (Cerro El Ávila, parc national 2765m, téléphérique depuis Caracas, panorama sur la côte caribéenne), <strong>Quartier Sabana Grande</strong> (grand axe commercial), <strong>Universidad Central de Venezuela</strong> (UNESCO, architecture moderne Carlos Raúl Villanueva). <strong>Excursions principales du Venezuela</strong> : <strong>Salto Ángel</strong> dans le Parc Canaima (la plus haute chute d'eau au monde 979m, accessible en avion + bateau, expédition 3-5 jours), <strong>Île de Margarita</strong> (Caraïbes vénézuéliennes), <strong>Roraima Tepui</strong> (la \"Lost World\" qui a inspiré Conan Doyle), <strong>Los Roques</strong> (archipel corallien). <strong>Tester</strong> arepa (la version vénézuélienne, garnie), pabellón criollo (plat national : viande effilochée + riz + haricots noirs + plantain), cachapa, hallaca de Noël, ron Diplomático (l'un des meilleurs rhums au monde).",

    "cartagena-col:fr": "Carthagène des Indes (Cartagena de Indias), ville côtière de <strong>Colombie</strong> : 1 million d'habitants sur la côte caribéenne, fondée en 1533 par les Espagnols. <strong>UNESCO 1984</strong> pour son centre historique fortifié (le système de fortifications le plus complet et le plus connu d'Amérique du Sud, construit pour protéger les galions chargés d'or et d'argent contre les pirates dont Francis Drake en 1586). <strong>Janvier-mars sont mes mois préférés</strong> (6.9/10) : 24-32°C, 9-16% de pluie, c'est la saison sèche. Cartagena ne dépasse jamais 6.9/10 (climat tropical chaud-humide). <strong>De décembre à avril</strong>, c'est la haute saison touristique : 24-32°C, 9-47% de pluie. <strong>De mai à novembre</strong>, c'est la saison des pluies : 47-85% de précipitations, mais averses brèves, températures stables (25-32°C). <strong>Sites majeurs</strong> : <strong>Ciudad Amurallada</strong> (vieille ville fortifiée, dédale de ruelles colorées avec balcons fleuris, Plaza Santo Domingo, Plaza San Pedro Claver, Plaza de la Aduana), <strong>Castillo San Felipe de Barajas</strong> (XVIe-XVIIIe, plus grande forteresse espagnole d'Amérique, complexe de tunnels souterrains), <strong>Cathédrale Sainte Catherine</strong> (XVIe), <strong>Las Bóvedas</strong> (anciennes casemates militaires reconverties en boutiques d'artisanat), <strong>Quartier Getsemaní</strong> (autrefois quartier ouvrier, maintenant gentrifié et bohème, street art, restos branchés), <strong>Convento de la Popa</strong> (XVIIe, sur la colline 150m, vue panoramique). <strong>Excursions</strong> : <strong>Iles Rosario</strong> en bateau 1h (28 îles coralliennes, parc national, plages turquoise, snorkeling), <strong>Volcán de Lodo El Totumo</strong> à 50 km (volcan de boue, baignade dans la boue thérapeutique), <strong>Playa Blanca</strong> (sur Isla Barú, plage paradisiaque). <strong>Tester</strong> arepa de huevo (signature côtière), ceviche, pescado frito, lechona, sancocho de pescado, agua de panela. Vol direct depuis Paris via Bogotá. Cartagena combinée avec Carthagène-2-jours + Bogotá-2-jours + Tayrona-3-jours = circuit Colombie classique.",

    "chapada-diamantina:fr": "Chapada Diamantina, parc national au cœur du <strong>nordeste brésilien</strong> dans l'État de <strong>Bahia</strong> : 1520 km² de plateaux et canyons, ancienne région d'extraction de diamants depuis le XIXe siècle. L'un des sites de randonnée les plus connus du Brésil. <strong>Octobre est mon mois préféré</strong> (8.3/10) : 18-28°C, 49% de pluie, ciel dégagé après la saison sèche. <strong>De juillet à septembre</strong>, c'est la saison sèche : 16-27°C, 49-55% de précipitations. <strong>De novembre à mars</strong>, c'est la saison des pluies : 50-63% de précipitations, mais paysages les plus verts, cascades les plus impressionnantes. <strong>Toute l'année</strong> les températures sont stables (16-29°C grâce à l'altitude moyenne 1000m). <strong>Sites majeurs</strong> : <strong>Cachoeira da Fumaça</strong> (\"chute de la fumée\" 380m, l'une des plus hautes du Brésil, à voir d'en haut depuis le bord du plateau ou d'en bas par 2 jours de marche), <strong>Poço Azul</strong> (\"puits bleu\", grotte avec piscine d'eau cristalline éclairée par un rayon de soleil 12h-14h, snorkeling unique), <strong>Poço Encantado</strong> (similaire mais plus difficile d'accès), <strong>Vale do Pati</strong> (\"vallée du Pati\", trek 3-7 jours considéré l'un des plus beaux du Brésil, dénivelés 1000m, sources thermales, accueil chez l'habitant), <strong>Morro do Pai Inácio</strong> (1120m, accès facile 30 min, panorama signature au coucher du soleil), <strong>Lapa Doce</strong> (grottes calcaires), <strong>Cachoeira do Mosquito</strong>. <strong>Bases</strong> : <strong>Lençóis</strong> (vieille ville coloniale rose-jaune, pont en pierre, restos, base touristique principale), <strong>Mucugê</strong> (plus calme, cimetière byzantin), <strong>Igatu</strong> (anciennes mines de diamants). <strong>Logistique</strong> : Chapada Diamantina à 7h en bus de Salvador (capitale de Bahia, vols directs depuis Paris via Lisbonne), guide local fortement recommandé pour treks. <strong>Tester</strong> moqueca de peixe (poisson au lait de coco), acarajé, godó (banane verte), cachaça artisanale.",

    "chili:fr": "Le Chili, pays sud-américain : 19 millions d'habitants sur 4300 km du nord au sud (l'un des pays les plus longs au monde), de l'Atacama au désert le plus aride à la <strong>Patagonie</strong> et la <strong>Terre de Feu</strong>. 5 zones climatiques distinctes selon la latitude. Les saisons sont inversées (l'hémisphère sud). <strong>Janvier-février sont mes mois préférés</strong> (8.4/10) : 7-19°C en moyenne (Santiago), 7-11% de pluie, c'est l'été austral. <strong>De novembre à mars</strong>, c'est la haute saison touristique chilienne : 2-19°C, climat sec et chaud, idéal pour Atacama et lacs du sud. <strong>De juin à août</strong>, c'est l'hiver austral : -5/6°C, ski sur les Andes (Portillo, Valle Nevado, Farellones à 2h de Santiago), Patagonie fermée et inaccessible. <strong>Régions à connaître</strong> : <strong>Désert d'Atacama</strong> (San Pedro de Atacama, le désert le plus aride au monde, certaines zones n'ont jamais reçu de pluie enregistrée, Vallée de la Lune, Geysers du Tatio à 4300m, Salar d'Atacama, observation des étoiles à ALMA Observatory), <strong>Vallées viticoles</strong> (Casablanca, Maipo, Colchagua = vins chiliens parmi les meilleurs du monde, Carmenere cépage signature), <strong>Région des Lacs</strong> (Pucón, Frutillar, Puerto Varas, volcan Osorno conique, lac Llanquihue), <strong>Patagonie chilienne</strong> (<strong>Torres del Paine National Park</strong> = trek W 4-5 jours ou O 8-10 jours avec glaciers, lacs turquoise, guanacos, condors, parmi les paysages les plus spectaculaires au monde), <strong>Île de Pâques</strong> (UNESCO, 887 moaïs sculptés par les Rapanui, vol depuis Santiago 5h). <strong>Santiago</strong> est la capitale (déjà couvert), <strong>Valparaíso</strong> ville portuaire UNESCO (déjà couvert). <strong>Tester</strong> empanada de pino, completo (hot dog version chilienne), pastel de choclo, ceviche chilien, pisco sour (cocktail national, débat avec le Pérou pour l'origine), vins Carmenere.",

    "colombie:fr": "La Colombie, pays sud-américain à l'extrême nord-ouest du continent : 52 millions d'habitants, seul pays sud-américain avec accès à la fois Caraïbes ET Pacifique. Considérée comme la \"plus diverse\" de l'Amérique du Sud (Andes + Caraïbes + Pacifique + Amazonie + Llanos plaines orientales). Image transformée depuis 2016 (accord de paix avec les FARC, fin du conflit civil le plus long du continent), tourisme en croissance forte. <strong>Septembre est mon mois préféré</strong> (7.7/10) en zone andine : 9-18°C, 34% de pluie. <strong>D'août à septembre et décembre-février</strong>, c'est la haute saison touristique : climat varie selon altitude (chaud côtier 28°C, frais montagneux 18°C). <strong>De mars à juin et octobre-novembre</strong>, c'est la saison des pluies en zone andine. <strong>Toute l'année</strong>, l'absence de saisons marquées (à part pluies/sec) permet de visiter (Colombie = pays des \"micro-climats\" selon altitude). <strong>Régions à connaître</strong> : <strong>Bogotá</strong> (capitale 2640m, Musée de l'Or - voir avis dédié), <strong>Carthagène des Indes</strong> (Caraïbes UNESCO - voir avis dédié), <strong>Medellín</strong> (\"ville de l'éternel printemps\" 1500m, transformée depuis l'ère Pablo Escobar mort en 1993, Comuna 13 graffitis et téléphérique urbain), <strong>Cali</strong> (capitale de la salsa colombienne), <strong>Eje Cafetero</strong> (\"axe du café\", Salento, Filandia, Vallée de Cocora avec ses palmiers à cire géants 60m, fincas de café à visiter), <strong>San Andrés et Providencia</strong> (îles caribéennes 750 km au large de la côte continentale colombienne, plus proches du Nicaragua), <strong>Tayrona National Park</strong> (Caraïbes vierges, randonnée jungle vers Cabo San Juan), <strong>Amazonie colombienne</strong> (Leticia, frontière Brésil-Pérou). <strong>Sécurité</strong> : situation très améliorée depuis 2016, mais éviter les zones rurales du sud (Putumayo, Cauca, Nariño) où certains groupes dissidents persistent. Bogotá et Medellín = vigilance urbaine standard. <strong>Tester</strong> bandeja paisa, ajiaco, arepa, lechona, café Geisha, aguardiente.",

    "equateur:fr": "L'Équateur, plus petit pays andin : 18 millions d'habitants sur 283 000 km² traversés par l'<strong>équateur</strong> géographique (d'où son nom). 4 régions distinctes : <strong>Sierra</strong> andine, <strong>Costa</strong> Pacifique, <strong>Oriente</strong> amazonien, <strong>Galápagos</strong>. <strong>De juillet à septembre sont mes mois préférés</strong> (7.6-7.7/10) en altitude : 7-19°C, 32-46% de pluie, c'est la saison sèche andine. <strong>De juin à septembre</strong>, c'est la haute saison touristique pour la Sierra : 7-19°C, ciel dégagé. <strong>De novembre à mai</strong>, c'est la saison des pluies dans la Sierra : 79-93% de précipitations, paysages verts mais souvent dans le brouillard. <strong>Sur la côte</strong>, saisons inversées (sec décembre-mai, pluvieux juin-novembre). <strong>Régions à connaître</strong> : <strong>Quito</strong> (capitale 2850m, UNESCO 1978, plus grand centre historique colonial préservé d'Amérique latine, voir avis dédié), <strong>Galápagos</strong> (UNESCO 1978, archipel de 19 îles à 1000 km du continent, faune unique : tortues géantes, iguanes marins, fous à pieds bleus, pingouins de l'équateur ; Charles Darwin y a élaboré sa théorie de l'évolution en 1835 ; 8 jours de croisière minimum recommandés, prix 3000-8000€ haute saison), <strong>Cuenca</strong> (UNESCO, 3e ville, hauts cocottes coloniaux), <strong>Otavalo</strong> (à 2h de Quito, le plus grand marché indigène d'Amérique du Sud le samedi), <strong>Mitad del Mundo</strong> (\"Milieu du Monde\", monument à l'équateur 0°, photo signature en équilibre sur le ligne, mais l'équateur géographique réel est 240m plus loin par GPS moderne), <strong>Volcan Cotopaxi</strong> (5897m, l'un des volcans actifs les plus hauts au monde, ascension 2 jours), <strong>Volcan Chimborazo</strong> (6263m, le \"point le plus proche du soleil\" si on mesure depuis le centre de la Terre, bulge équatorial), <strong>Baños</strong> (\"Petite Suisse\" andine, randonnée Pailón del Diablo cascade), <strong>Amazonie équatorienne</strong> (Yasuní National Park = l'un des plus biodiverses au monde). <strong>Tester</strong> ceviche de camarón (côtier), llapingachos (galettes pomme de terre), encebollado (soupe poisson), fritada, cuy (cochon d'Inde rôti dans la Sierra).",

    "georgetown-guyana:fr": "Georgetown, capitale du <strong>Guyana</strong> (anciennement Guyane britannique, indépendant depuis 1966) : 200 000 habitants sur la côte atlantique entre Venezuela et Suriname. Petit pays anglophone (1 million d'habitants au total), souvent confondu avec la Guyane française voisine ou le Guyana = origine ethnique principale 40% Indo-Guyanais (descendants de travailleurs indiens venus après l'abolition de l'esclavage en 1838) + 30% Afro-Guyanais. <strong>Mars est mon mois préféré</strong> (7.9/10) : 25-28°C, 63% de pluie, période la plus sèche relative. <strong>De septembre à novembre</strong>, c'est la 2e saison sèche : 25-30°C, 64-78% de pluie. <strong>D'avril à juillet</strong>, c'est la saison des pluies majeure : 71-97% de précipitations, inondations possibles à Georgetown (la ville est sous le niveau de la mer, protégée par une digue Sea Wall depuis l'époque hollandaise XVIIe). <strong>De décembre à février</strong>, comptez 24-28°C avec 73-85% de pluie : 2e saison des pluies (mineure). <strong>Sites majeurs</strong> : <strong>Cathédrale Saint-George</strong> (la plus haute église en bois au monde 43m, néo-gothique 1899), <strong>Marché Stabroek</strong> (Stabroek Market, 1881, architecture en fonte avec horloge, marché central animé), <strong>Sea Wall</strong> (digue de 450 km le long de la côte, nécessaire car Georgetown est sous le niveau de la mer), <strong>Promenade Gardens</strong>, <strong>Botanical Gardens</strong>, <strong>National Museum</strong>. <strong>Excursions majeures du Guyana</strong> : <strong>Kaieteur Falls</strong> (le joyau du Guyana, chute d'eau de 226m de haut - 5x Niagara - dans la jungle vierge, accessible en avion 1h depuis Georgetown ou trek 5 jours), <strong>Iwokrama Forest</strong> (forêt protégée Atlantic-Amazon, canopée à 30m), <strong>Rupununi Savannah</strong> (savane, ranches, jaguars), <strong>Shell Beach</strong> (tortues marines pondent). <strong>Tester</strong> pepperpot (ragoût national signature, traditionnellement à base de cassareep liquide concentré de manioc), roti, curry guyanais (héritage indien), El Dorado rum (l'un des meilleurs rhums au monde, 12 et 15 ans).",

    "nassau:fr": "Nassau, capitale des <strong>Bahamas</strong> sur l'<strong>île de New Providence</strong> : 280 000 habitants (70% de la population du pays vit ici). Archipel des Bahamas = 700 îles dans l'Atlantique tropical, à 80 km à l'est de la Floride. Indépendantes depuis 1973 (royaume du Commonwealth), forte influence britannique culturelle + caribéenne afro-bahamiane. Première destination de croisière au monde. <strong>Mars est mon mois préféré</strong> (8.7/10) : 22-26°C, 27% de pluie, mer à 25°C, fin de la haute saison. <strong>De décembre à mai</strong>, c'est la haute saison touristique : 21-28°C, 27-54% de pluie, prix hôteliers x2-x3, paquebots quotidiens (Atlantis Resort, Baha Mar Resort 5*+ par milliers de chambres). <strong>De juin à novembre</strong>, c'est la saison cyclonique : 54-66% de précipitations, risque ouragans réel (Dorian a dévasté Abacos et Grand Bahama en septembre 2019, 70 morts, dégâts catastrophiques). <strong>Sites majeurs Nassau</strong> : <strong>Bay Street</strong> (rue commerçante coloniale, duty-free Cartier/Bulgari/Rolex), <strong>Parliament Square</strong> (bâtiments coloniaux roses), <strong>Fort Charlotte</strong> (XVIIIe), <strong>Pirates of Nassau Museum</strong> (Nassau était le QG du \"pirate âge d'or\" Edward Teach \"Blackbarbe\" début XVIIIe), <strong>John Watling's Distillery</strong> (rhum), <strong>Fish Fry à Arawak Cay</strong> (street food bahamian local), <strong>Cable Beach</strong> (plage longue avec hôtels), <strong>Atlantis Paradise Island</strong> (resort thématique avec aquarium et waterpark). <strong>Excursions plages</strong> : <strong>Pig Beach</strong> (Big Major Cay, Exuma, ferry/avion privé, plage avec cochons sauvages nageurs viraux Instagram), <strong>Eleuthera</strong> et <strong>Harbour Island</strong> (sable rose unique au monde Pink Sand Beach), <strong>Exuma Cays</strong> (croisière catamaran), <strong>Andros</strong> (plus grande île, blue holes, plongée). <strong>Tester</strong> conch fritters/salad/cracked, rock lobster, johnnycake, sky juice (cocktail gin coco), Kalik beer (fierté bahamian).",

    "paramaribo:fr": "Paramaribo, capitale du <strong>Suriname</strong> (ancien Suriname néerlandais, indépendant depuis 1975) : 240 000 habitants sur la rivière Suriname. <strong>UNESCO 1980</strong> pour son centre historique en bois aux maisons coloniales hollandaises XVIIe-XIXe. Pays multi-ethnique unique au monde : 27% Indo-Surinamais, 22% Marrons (descendants d'esclaves marrons), 18% Créoles, 14% Javanais, 5% Chinois, etc. Langue officielle néerlandais (seul pays du continent), mais <strong>Sranantongo</strong> langue véhiculaire afro-créole. <strong>Mars est mon mois préféré</strong> (8.0/10) : 24-28°C, 57% de pluie, fin de la petite saison sèche. <strong>De septembre à novembre</strong>, c'est la grande saison sèche : 25-32°C, 43-70% de pluie, idéal pour visiter. <strong>De décembre à février et mai-juillet</strong>, ce sont les saisons des pluies : 67-97% de précipitations, mais températures stables (24-30°C). <strong>Sites majeurs Paramaribo</strong> : <strong>Centre historique</strong> (UNESCO, plus grand ensemble d'architecture coloniale en bois aux Caraïbes, à découvrir à pied le long de la Waterkant Avenue), <strong>Fort Zeelandia</strong> (XVIIe néerlandais, musée d'histoire), <strong>Cathédrale Saints-Pierre-et-Paul</strong> (la plus grande cathédrale en bois d'Amérique latine, 1885), <strong>Mosquée Keizerstraat</strong> et <strong>Synagogue Neveh Shalom</strong> (cohabitent côte à côte, symbole multi-religieux du pays unique au monde), <strong>Marché Centraal</strong> (Market Place, 6 marchés ethniques distincts : indien, créole, javanais, chinois, marron). <strong>Excursions</strong> : <strong>Brownsberg Nature Park</strong> (forêt amazonienne à 130 km, randonnée, cascades), <strong>Galibi</strong> (réserve tortues marines à l'embouchure du Marowijne), <strong>Forêt Amazonienne</strong> (90% du territoire surinamais est forêt vierge, l'un des taux de couverture forestière les plus élevés au monde, expéditions chez les Marrons Saramaccans). <strong>Tester</strong> pom (cassolette créole), bami goreng (héritage javanais), roti curry (indien), pomtaja, Parbo Beer.",

    "perou:fr": "Le Pérou, pays andin sud-américain : 33 millions d'habitants sur 1 285 000 km² (3e plus grand d'Amérique du Sud après Brésil et Argentine). 3 régions classiques : <strong>Costa</strong> désertique (côte Pacifique avec Lima), <strong>Sierra</strong> andine (cordillère des Andes), <strong>Selva</strong> amazonienne (60% du territoire). Berceau de la <strong>civilisation inca</strong> et de cultures pré-incas (Caral, Chavín, Moche, Nazca, Wari, Chimú). <strong>Février est mon mois préféré</strong> (9.0/10) à Lima : 21-26°C, 14% de pluie, été austral sur la côte. <strong>De mai à septembre</strong>, c'est la haute saison touristique pour les Andes (notamment Machu Picchu) : 14-19°C, 0-2% de pluie en altitude, ciel dégagé. <strong>De décembre à mars</strong>, c'est la saison des pluies en altitude : Machu Picchu humide et brumeux mais paysages verts, Inca Trail fermé en février pour maintenance. <strong>Régions/sites à connaître</strong> : <strong>Lima</strong> (capitale, ville la plus peuplée, voir avis dédié), <strong>Machu Picchu</strong> (UNESCO 1983, l'un des sites les plus connus au monde, citadelle inca XVe à 2430m d'altitude redécouverte par Hiram Bingham en 1911, accès par train depuis Cusco + Aguas Calientes + bus, ou trek <strong>Inca Trail</strong> 4 jours/3 nuits, 500 visiteurs/jour limite, réservation 6 mois avant), <strong>Cusco</strong> (UNESCO, ancienne capitale inca, base pour Machu Picchu - voir avis dédié), <strong>Vallée Sacrée</strong> (Pisac, Ollantaytambo, Moray, Salineras), <strong>Lac Titicaca</strong> (3812m, partagé avec Bolivie, îles flottantes Uros en roseaux, île Taquile), <strong>Lignes de Nazca</strong> (UNESCO, géoglyphes à voir d'avion, mystères archéologiques), <strong>Arequipa</strong> (UNESCO, \"Ciudad Blanca\" en pierre volcanique blanche, base pour Cañon del Colca), <strong>Iquitos</strong> (Amazonie péruvienne, accessible uniquement en avion ou bateau), <strong>Trujillo et Chan Chan</strong> (UNESCO, plus grande cité en adobe précolombienne au monde). <strong>Tester</strong> ceviche (plat national, poisson cru mariné citron), lomo saltado, ají de gallina, anticuchos (brochettes de coeur de bœuf), pisco sour, chicha morada.",

    "port-au-prince:fr": "Port-au-Prince, capitale d'<strong>Haïti</strong> : 1 million d'habitants (3 millions en aire urbaine) sur la côte du <strong>Golfe de la Gonâve</strong>. Pays francophone et créolophone (pays créole le plus connu au monde), premier pays noir indépendant (1804 après révolte des esclaves). Marqué par le <strong>séisme catastrophique du 12 janvier 2010</strong> (200 000 morts, ville détruite à 80%, reconstruction lente et incomplète) et instabilité politique chronique (assassinat du président Moïse en juillet 2021, gangs qui contrôlent 80% de la capitale en 2024-2026). <strong>Conseillers voyage</strong> : la plupart des pays occidentaux <strong>déconseillent formellement</strong> les voyages en Haïti depuis 2022 (situation sécuritaire désastreuse, ambassades en sortie partielle). <strong>Janvier est mon mois préféré</strong> (8.7/10) : 22-31°C, 14% de pluie, fin de la saison sèche. <strong>De décembre à mars</strong>, c'est la saison sèche : 22-32°C, 13-32% de pluie. <strong>De juin à août chutent à 6.3-6.9/10</strong> à cause de la chaleur (26-35°C) et de la saison cyclonique. <strong>De juillet à octobre</strong>, c'est la saison cyclonique : 23-42% de précipitations, risque ouragans réel (Matthew 2016, Hurricane Tropical Storm Laura 2020). <strong>Sites majeurs</strong> (à connaître théoriquement, accès très restreint en 2026) : <strong>Champ de Mars</strong> (place principale, ruines du Palais Présidentiel détruit en 2010 jamais reconstruit), <strong>Cathédrale Notre-Dame</strong> (détruite en 2010, en cours de reconstruction lente), <strong>Marché en Fer</strong> (Marché Hyppolite, structure métallique 1891, restauré après 2010), <strong>Musée du Panthéon National</strong> (MUPANAH), <strong>Quartier de Pétion-Ville</strong> (sur les hauteurs au sud-est, plus sûr et résidentiel, hôtels internationaux). <strong>Sites majeurs Haïti hors capitale</strong> : <strong>Citadelle Laferrière</strong> (UNESCO, Cap-Haïtien au nord, plus grande forteresse des Amériques, construite par Henri Christophe roi d'Haïti après l'indépendance 1805-1820), <strong>Palais Sans-Souci</strong> (UNESCO), <strong>Bassin Bleu</strong> (cascades à Jacmel), <strong>Jacmel</strong> (ville coloniale française du sud, festival du carnaval). <strong>Tester</strong> griot (porc frit), riz djon-djon (champignon noir), pikliz (pickles épicés), rhum Barbancourt, kremas (liqueur de coco).",

    "portillo:fr": "Portillo, station ski chilienne dans la <strong>Cordillère des Andes</strong> : à 165 km au nord-est de Santiago à <strong>2880m d'altitude</strong>, à la frontière avec l'Argentine, l'une des plus anciennes stations ski d'Amérique du Sud (fondée 1949). 1 seul hôtel (Hotel Portillo, 5*, jaune jaune signature visible de loin sur le bord du <strong>Lago del Inca</strong>), 450 lits maximum, atmosphère exclusive type \"chalet de famille international\" plus que station alpine commerciale. <strong>Saisons inversées</strong> (hémisphère sud). <strong>Février est mon mois préféré</strong> (6.9/10) : 7-16°C, 27% de pluie, été austral, randonnée alpine, kayak sur le Lago del Inca, mais la station n'est ouverte que pour le ski en hiver. <strong>De juin à octobre</strong>, c'est la saison ski (hiver austral) : -5/9°C, 25-31% de précipitations souvent neige (10-12m/saison, l'une des plus enneigées d'Amérique du Sud grâce à l'effet barrière de la Cordillère). Portillo est célèbre pour son ski d'été pour les équipes nordiques (US Ski Team, Norwegian, Austrian, ont entraîné ici en juillet-août pendant l'été nord-américain pour préparer Coupe du Monde nord). <strong>Pistes</strong> : 35 pistes, 14 remontées (dont 5 va-et-vient \"slingshot\" rares au monde, plateforme tractée à 8 personnes pour grimper en pente raide à 70 km/h sans pylône, créés en 1961 par les fondateurs autrichiens), altitude 2600-3300m, dénivelé 700m, terrain ouvert sans arbres (ski hors-piste partout possible). <strong>Style</strong> : Portillo est ultra-exclusif, 1 seul hôtel = sentiment de \"club privé en altitude\", clientèle internationale (Brésiliens en majorité, Américains, Européens, peu de Chiliens locaux), pas de boutiques ni village. <strong>Tarif</strong> : forfaits semaine 7-jour all-inclusive 2500-5000$/personne (logement + repas + ski). <strong>Logistique</strong> : Portillo à 2h de Santiago en voiture/transfer (route serpente Andes Camino Internacional vers l'Argentine, parfois fermée pour neige), aéroport Santiago.",

    "republique-dominicaine:fr": "La République Dominicaine, pays caribéen de l'<strong>île d'Hispaniola</strong> partagée avec Haïti : 11 millions d'habitants sur 49 000 km² (les 2/3 orientaux d'Hispaniola). 1ère destination de tourisme balnéaire des Caraïbes (forfaits all-inclusive populaires depuis les 90s), surtout autour de <strong>Punta Cana</strong>. <strong>Janvier est mon mois préféré</strong> (8.5/10) : 21-28°C, 36% de pluie, fin de la saison sèche, mer à 26°C, températures idéales. <strong>De décembre à avril</strong>, c'est la haute saison touristique : 21-29°C, 36-63% de pluie, prix hôteliers x2 (resorts), réservations 3-6 mois avant pour Noël/Nouvel An. <strong>De juin à novembre</strong>, c'est la saison cyclonique : 66-77% de précipitations, risque ouragans réel (Maria et Irma en 2017 ont touché). <strong>Régions à connaître</strong> : <strong>Punta Cana</strong> (côte est, 50+ resorts all-inclusive, plage Bávaro classée parmi les meilleures du monde, golf 6 parcours signature Tom Fazio/Jack Nicklaus/Pete Dye, vol direct Paris-Punta Cana), <strong>La Romana</strong> et <strong>Bayahibe</strong> (côte sud-est, Casa de Campo resort exclusif, île de Saona excursion bateau-plage paradisiaque), <strong>Saint-Domingue</strong> (Santo Domingo, capitale, Zona Colonial UNESCO 1990 = 1ère cité européenne d'Amérique fondée en 1496 par Bartolomé Colomb frère de Christophe, première cathédrale 1512, première université 1538, première rue Calle de las Damas), <strong>Puerto Plata</strong> (côte nord, plus traditionnel et moins touristique), <strong>Samaná</strong> (presqu'île nord-est, baleines à bosse en migration janvier-mars, El Limón cascade), <strong>Pico Duarte</strong> (3098m, point culminant des Caraïbes, ascension 2-3 jours), <strong>Lac Enriquillo</strong> (lac salé sous le niveau de la mer, crocodiles américains et iguanes). <strong>Tester</strong> mangú (purée de plantain matin), sancocho (soupe), la bandera (riz blanc + haricots rouges + viande), mofongo, presidente beer, Brugal/Barceló rum.",

    "saint-georges-grenade:fr": "Saint-George's, capitale de <strong>Grenade</strong> (\"Grenada\" en anglais, à ne pas confondre avec Granada en Espagne) : 4000 habitants sur la côte sud-ouest de l'île de Grenade dans les <strong>Petites Antilles</strong> (chaîne caribéenne sud). État indépendant depuis 1974 (royaume du Commonwealth), surnommé \"l'<strong>île aux épices</strong>\" (Grenada produit 20% de la noix de muscade mondiale, 2e producteur après l'Indonésie, drapeau national orné d'une noix de muscade). Petite île 344 km², 110 000 habitants. <strong>D'avril est mon mois préféré</strong> (8.5/10) : 25-29°C, 37% de pluie, mer à 28°C, fin de la saison sèche. <strong>De janvier à mai</strong>, c'est la haute saison touristique : 24-29°C, 37-44% de pluie, période la plus agréable et sèche. <strong>De juin à novembre</strong>, c'est la saison des pluies : 65-74% de précipitations, mais températures stables (26-30°C), risque cyclonique réel (mais Grenade est plus au sud que les Antilles \"corridor cyclonique\" donc moins frappée que ses voisines plus au nord). <strong>Sites majeurs</strong> : <strong>Carénage</strong> (port en fer à cheval avec maisons rouge-jaune-bleu en pente, l'image-carte postale de la ville), <strong>Fort George</strong> (XVIIe sur promontoire, panorama, lieu de l'assassinat du Premier ministre Maurice Bishop en 1983, ce qui a déclenché l'invasion américaine la même année), <strong>Marché central</strong> (Spice Market, étals colorés d'épices : muscade, cannelle, gingembre, curcuma, fèves de cacao), <strong>Cathédrale Saint-George</strong>, <strong>Musée National</strong> (ancien fort français-britannique). <strong>Sites majeurs Grenade île</strong> : <strong>Plage Grand Anse</strong> (3 km de sable blanc, l'une des plus belles plages des Caraïbes selon de nombreux classements), <strong>Annandale Falls</strong> (cascade accessible en voiture), <strong>Concord Falls</strong>, <strong>Underwater Sculpture Park</strong> à Molinière Bay (1er parc de sculptures sous-marines au monde 2006, snorkeling/plongée), <strong>Belmont Estate</strong> (plantation cacao traditionnelle), <strong>Grand Etang National Park</strong> (forêt tropicale, lac de cratère). <strong>Tester</strong> oil down (plat national: viande + dumplings + breadfruit + lait de coco), callaloo soup, nutmeg ice cream, rum Westerhall, chocolate House (chocolaterie locale).",

    "trinidad-cuba:fr": "Trinidad, ville coloniale du centre de <strong>Cuba</strong> dans la <strong>province de Sancti Spíritus</strong> : 75 000 habitants à 6 km de la côte caraïbe. Fondée en 1514 par Diego Velázquez, c'est l'une des plus anciennes villes des Amériques. <strong>UNESCO 1988</strong> avec la Vallée de los Ingenios voisine pour l'ensemble colonial le mieux préservé de Cuba (figée dans le temps après le déclin du sucre fin XIXe). <strong>Janvier-février sont mes mois préférés</strong> (8.9/10) : 20-29°C, 14-16% de pluie, c'est la saison sèche caribéenne idéale. <strong>De novembre à avril</strong>, c'est la haute saison touristique : 20-31°C, 9-30% de pluie. <strong>De mars-avril chutent à 6.9/10</strong> à cause de la chaleur croissante. <strong>De mai à octobre</strong>, c'est la saison des pluies et cyclonique : 47-62% de précipitations. <strong>Sites majeurs</strong> : <strong>Plaza Mayor</strong> (place principale, ensemble colonial intact XVIIe-XIXe), <strong>Iglesia Parroquial de la Santísima Trinidad</strong> (XIXe, néoclassique), <strong>Museo Romántico</strong> (Casa Brunet, palais XIXe meublé d'origine), <strong>Museo Municipal</strong> (Palacio Cantero, panorama 360° depuis le clocher), <strong>Casa de la Música</strong> (escalier devant l'église, musique salsa/son live tous les soirs en plein air, l'âme cubaine), <strong>Casa de la Trova</strong> (musique traditionnelle), <strong>Plaza Carrillo</strong>, <strong>Quartier des Casitas</strong> (maisons coloniales colorées). <strong>Excursions</strong> : <strong>Valle de los Ingenios</strong> (UNESCO, vallée des anciennes plantations sucrières avec 75 raffineries XVIIIe-XIXe ruinées, Tour Manaca-Iznaga 45m construite par un planteur pour surveiller ses esclaves), <strong>Playa Ancón</strong> à 12 km (plage signature de Trinidad, eau turquoise), <strong>Topes de Collantes</strong> à 30 min (parc national montagneux 800m d'altitude, randonnée Salto del Caburní cascade), <strong>Cienfuegos</strong> à 80 km (UNESCO, ville française fondée 1819, baroque). <strong>Logistique</strong> : Trinidad à 4h en voiture de La Havane (route Carretera Central), <strong>casa particular</strong> (chez l'habitant) recommandé sur les hôtels (15-30€/nuit, expérience plus authentique). <strong>Tester</strong> ropa vieja (viande effilochée), congrí (riz noir avec haricots), canchánchara (cocktail miel-citron-rhum signature de Trinidad), Cubita coffee.",

    "uruguay:fr": "L'Uruguay, plus petit pays sud-américain hispanophone : 3,5 millions d'habitants sur 176 000 km², coincé entre l'Argentine et le Brésil. Considéré comme l'un des pays les plus stables, démocratiques et progressistes d'Amérique latine (premier pays à légaliser le mariage gay et le cannabis). Climat tempéré sans extrêmes (saisons inversées de l'hémisphère sud). <strong>Janvier est mon mois préféré</strong> (9.0/10) : 20-26°C, 27% de pluie, c'est l'été austral, plages de Punta del Este et José Ignacio en pleine effervescence avec les Argentins et Brésiliens en vacances (prix x3-x5 sur la côte en janvier-février). <strong>De décembre à mars</strong>, c'est la haute saison touristique : 18-26°C, 26-36% de pluie. <strong>D'avril à mai et septembre-novembre</strong> sont les meilleures intersaisons : 11-22°C, climat doux. <strong>De juin à août</strong>, c'est l'hiver austral : 9-15°C, 25-29% de pluie, peu de touristes, mais Montevideo reste agréable. <strong>Régions à connaître</strong> : <strong>Montevideo</strong> (capitale, voir avis dédié), <strong>Punta del Este</strong> (\"Saint-Tropez sud-américain\", station balnéaire chic depuis les 60s, casinos, pénisule entre Atlantique et Rio de la Plata, plages Brava et Mansa, Casapueblo de Carlos Paez Vilaró architecte uruguayen, prix x3-x5 en janvier-février quand les Argentines y migrent en masse), <strong>José Ignacio</strong> (à 30 min de Punta del Este, plus discret et plus chic, repaire des magnates et célébrités, plage La Mansa), <strong>Colonia del Sacramento</strong> (UNESCO, ville coloniale portugaise XVIIe en bord de Rio de la Plata, accessible en 1h en ferry depuis Buenos Aires Argentine), <strong>Cabo Polonio</strong> (village isolé sans électricité officielle ni route, accessible uniquement en 4x4 sur la plage, ambiance bohème/hippie, colonies de lions de mer), <strong>Punta del Diablo</strong> (village pêcheur surf bohème), <strong>Carmelo</strong> (vignobles uruguayens, Tannat cépage signature). <strong>Tester</strong> chivito (\"sandwich national\" boeuf-jambon-fromage-oeuf-bacon), parrillada (asado uruguayen), dulce de leche, mate (boisson partagée nationale, plus consommé qu'en Argentine), Tannat wine (cépage emblème uruguayen)."
}

with open(PATH, encoding='utf-8') as f:
    data_existing = json.load(f)

before = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

data_existing['_version'] = '2.7'
data_existing['_updated'] = '2026-04-28'

for k, v in AVIS_BATCH16_FR.items():
    data_existing[k] = v

after = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data_existing, f, ensure_ascii=False, indent=2)

print(f"Avis FR avant : {before}")
print(f"Avis FR après : {after}")
print(f"Nouveaux : {after - before}")

# Audit immédiat
import re
patterns_check = [
    ('em-dash', r'—'), ('guillemets', r'[«»]'),
    ('attendez-vous', r'attendez-vous à'),
    ('parfait', r'\bparfait[es]*\b'),
    ('fenêtre', r'\bfenêtre[s]?\b'),
    ('saturé', r'\bsatur[eéa]\w*\b'),
    ('se mérite', r'\bse méri[tes]+\b'),
    ('magique', r'\bmagiques?\b'),
    ('Si vous X:', r'Si vous \w+ : '),
    ('iconique', r'\biconique[s]?\b'),
    ('antithèse', r'antithèse'),
    ('mythique', r'\bmythique[s]?\b'),
    ('emblématique', r'\bemblématique[s]?\b'),
    ('authentique', r'\bauthentique[s]?\b'),
    ('féérique', r'\bféérique[s]?\b'),
    ("c'est aussi", r"[Cc]'est aussi"),
    ('à monitorer', r'à monitorer'),
    ('à éviter', r'à éviter'),
]

print("\n=== Audit batch 16 ===")
issues_total = 0
for slug in AVIS_BATCH16_FR.keys():
    plain = re.sub(r'<[^>]+>', '', data_existing[slug])
    issues = []
    for label, p in patterns_check:
        n = len(re.findall(p, plain))
        if n > 0:
            issues.append(f"{label}={n}")
            issues_total += n
    flag = "OK" if not issues else "PB " + ", ".join(issues)
    print(f"  {slug:<25} {len(plain.split()):>3}m {flag}")
print(f"\nTotal issues : {issues_total}")
