"""
Patch data/avis_annuel.json : ajoute 29 avis FR du batch 2 (Top mondial 31-60).
Tier 4 : mogadiscio (Somalie - sécurité) → fallback templates.
"""
import json
import os

PATH = os.path.join(os.path.dirname(__file__), '..', 'data', 'avis_annuel.json')

AVIS_BATCH2_FR = {
    "durban:fr": "Durban, c'est l'autre visage de l'Afrique du Sud : moins iconique que le Cap mais plus tropical. Climat humide subtropical, mer toujours chaude (22-26°C). <strong>Janvier reste mon mois préféré</strong> (8.6/10) malgré 38% de pluie — ces averses sont brèves, l'océan Indien chaud rattrape tout. <strong>De mai à août</strong> (hiver austral local), prévoyez 12-24°C avec 12-19% de pluie — c'est paradoxalement la meilleure saison pour les baleines à bosse au large et pour la randonnée dans les Drakensberg à 3h de route. Le <strong>Golden Mile</strong> reste praticable toute l'année (rare en Afrique). <strong>De novembre à mars</strong>, attendez-vous à 30-45% de précipitations en averses orageuses — saison cyclonique du Mozambique voisin, avec parfois des répercussions. La forte communauté indienne donne à Durban une cuisine unique (bunny chow, curry rotis), surtout dans Grey Street.",

    "san-diego:fr": "San Diego, c'est la météo californienne la plus stable du sud : <strong>nuages matinaux (May Gray, June Gloom) puis soleil l'après-midi</strong>, jamais de chaleur extrême grâce au courant froid de Californie. <strong>Juillet-août sont mes mois préférés</strong> (9.3/10) — 18-25°C, 0-2% de pluie, mer à 19-21°C (fraîche pour les Européens). <strong>De décembre à mars</strong>, prévoyez 8-17°C et 18-28% de pluie — c'est notre fenêtre humide californienne, mais cela reste portable et permet d'éviter les foules. La frontière avec Tijuana à 30 minutes ouvre sur un autre monde (passez en piéton plutôt qu'en voiture). Balboa Park (musées gratuits le mardi pour résidents), La Jolla (otaries, kayak), Coronado (plage doré, vélo) sont les classiques. Comic-Con fin juillet sature complètement la ville pendant 4 jours.",

    "amman:fr": "Amman est la base logistique idéale pour la Jordanie : aéroport international, taxis abordables, anglais largement parlé. À 800m d'altitude, climat semi-aride continental. <strong>Mai est mon mois préféré</strong> (9.7/10) — 15-28°C, 5% de pluie, lumière parfaite sur le théâtre romain et la citadelle. <strong>De juin à août</strong>, attendez-vous à 19-33°C avec 0% de pluie — chaud sec, mais portable car peu d'humidité. Les soirées restent agréables sur Rainbow Street. <strong>De décembre à février</strong>, les nuits descendent à 4°C et la neige peut bloquer la circulation 1-2 jours par hiver (la ville n'est pas équipée). Petra à 3h en bus est un classique, Wadi Rum à 4h pour 1-2 nuits en bivouac. La <strong>scène café</strong> du quartier Jabal Lweibdeh s'est développée autour des artistes et de la diaspora. Le mezze jordanien (mansaf, makluba) reste authentique loin des restos pour touristes.",

    "moshi:fr": "Moshi, c'est le camp de base du Kilimandjaro (5895m) : la majorité des trekkings démarrent ici ou à Marangu voisin. À 900m d'altitude. <strong>Septembre est mon mois préféré</strong> (9.3/10) — 18-28°C, 11% de pluie, ciel clair pour voir le Kibo enneigé depuis la ville. <strong>Mars-avril sont les longues pluies</strong> (42-87% de précipitations) — beaucoup de tour-opérateurs déconseillent l'ascension pendant cette fenêtre, sentiers boueux, visibilité réduite. <strong>Octobre-novembre</strong> ramènent les pluies courtes (25-44%), moins handicapantes mais à prendre en compte. La fenêtre <strong>juin à octobre</strong> reste la plus prisée pour le trek (saison sèche complète). Comptez 1500-3500€ pour 6-7 jours d'ascension selon l'agence et l'itinéraire (Marangu, Machame, Lemosho). La région produit aussi un excellent café arabica (visites de plantations à Materuni). Arusha à 1h30 est la base alternative pour Serengeti et Ngorongoro.",

    "kigali:fr": "Kigali surprend : ville la plus propre d'Afrique, sécurité élevée, services digital avancés. À 1500m d'altitude, climat doux toute l'année (15-27°C constant). <strong>Juillet est mon mois préféré</strong> (9.4/10) — 4% de pluie, ciel parfait. <strong>De mars à mai et octobre-décembre</strong>, attendez-vous à des saisons des pluies marquées (43-76% d'averses, surtout en avril) — souvent en fin d'après-midi, ce qui n'empêche pas les visites matinales. Le <strong>Mémorial du génocide de Gisozi</strong> reste le passage obligé pour comprendre le pays. Le quartier de Kimihurura concentre la scène café/restos. Kigali est surtout la base pour rejoindre le <strong>parc national des Volcans</strong> (3h de route) où se font les treks gorilles (1500$ le permis, à réserver 6+ mois avant). Lac Kivu à Gisenyi pour la détente. Tarifs hôtels alignés sur les capitales européennes.",

    "maputo:fr": "Maputo garde son caractère portugais Art déco et son côté méditerranéen tropical. Climat humide, été torride. <strong>Août-septembre sont mes mois préférés</strong> (9.0/10) — 16-27°C, 9-19% de pluie, soleil constant. La <strong>plage de Macaneta</strong> à 30 km est accessible toute l'année. <strong>De décembre à février</strong> (été austral), prévoyez 22-30°C avec 43-54% de précipitations — humidité pesante, risques de cyclones (Mozambique en zone de risque modéré). Inhambane et l'archipel de Bazaruto à 6-8h de route sont les vraies cartes du Mozambique. Les <strong>marchés de Janeta</strong> et la cuisine portugaise-mozambicaine (chamuças, peri-peri prawns) restent authentiques. La sécurité s'est améliorée mais reste à surveiller la nuit hors des quartiers Polana et Sommerschield. Vols directs depuis Lisbonne facilitent l'accès depuis l'Europe.",

    "loreto-mexique:fr": "Loreto, c'est la Baja California Sur version paisible : aéroport international mais tourisme de masse limité. Mer de Cortez réputée par Cousteau comme « l'aquarium du monde ». <strong>Avril est mon mois préféré</strong> (9.7/10) — 19-28°C, 1% de pluie, mer à 22°C. <strong>De juin à octobre</strong>, attendez-vous à 24-34°C avec saison des chubascos (orages tropicaux) et risque cyclonique pic en septembre. La chaleur devient écrasante (28-34°C) — la plupart des hôtels ferment partiellement. <strong>De janvier à mars</strong>, c'est la saison des baleines bleues et baleines grises au large : sorties bateau régulières depuis Loreto et Bahía Magdalena. Mer plus fraîche (16-19°C) mais sorties en mer parfaites. Les missions jésuites et le centre historique se visitent en 2h. Pour la plongée et le snorkeling, l'archipel d'Espíritu Santo offre des spots accessibles toute l'année.",

    "cabo-san-lucas:fr": "Cabo San Lucas, c'est le contraire de Loreto : tourisme américain massif, resorts all-inclusive, vie nocturne au Squid Roe et Cabo Wabo. El Arco, la formation rocheuse iconique, sépare mer de Cortez et Pacifique. <strong>Mars-avril sont mes mois préférés</strong> (9.6/10) — 18-29°C, 0% de pluie, mer à 21°C, fenêtre des baleines à bosse en migration (sorties à 80€). <strong>De juin à octobre</strong>, prévoyez 24-33°C avec saison des chubascos et risque cyclonique réel (Hurricane Odile en 2014 a marqué les esprits). Beaucoup d'hôtels appliquent des prix d'« été » sensiblement réduits. Le <strong>spring break américain en mars</strong> sature la ville pendant 3 semaines : prix hôteliers x2-x3, fêtes 24h/24, à anticiper si on cherche le calme. La Paz à 2h en voiture offre une alternative plus authentique. Sport fishing (marlin, mahi-mahi) reste l'attraction la plus distinctive.",

    "perth:fr": "Perth est la métropole la plus isolée au monde (Adelaide à 2700 km, Bali plus proche que Sydney). Climat méditerranéen sec à pluie hivernale. <strong>Décembre est mon mois préféré</strong> (9.8/10) — 18-28°C, 6% de pluie, journées de 14h. <strong>De juin à août</strong>, prévoyez 10-21°C et 43-50% de précipitations — c'est l'hiver austral, aussi humide qu'un hiver breton. <strong>Cottesloe</strong> et Scarborough sont les plages emblématiques, le ferry pour <strong>Rottnest Island</strong> (quokkas, vélo, snorkeling) est un classique du dimanche pour les locaux. <strong>Margaret River</strong> à 3h au sud (vins, surf, gourmet) mérite 2-3 jours. King's Park reste l'un des plus grands parcs urbains au monde. Janvier-mars sont aussi excellents (9.2-9.5/10), avec mer à 22°C. Vols depuis Europe via Singapour ou Doha (~24h porte-à-porte).",

    "hurghada:fr": "Hurghada vit du tourisme de plongée et des resorts all-inclusive. Mer Rouge, récifs accessibles dès la plage. Climat désertique. <strong>Avril est mon mois préféré</strong> (9.6/10) — 20-28°C, 0% de pluie, mer à 23°C. <strong>De juin à septembre</strong>, attendez-vous à 27-35°C — la chaleur sèche reste portable au bord de mer mais épuisante en excursion désert. Les bateaux de plongée partent tôt (5h-6h) pour rentrer avant midi. <strong>De décembre à février</strong>, prévoyez 14-22°C et le vent peut devenir glacial le soir — toujours possibilité de plonger en combinaison 5mm. Les sites incontournables : <strong>Giftun Islands</strong> (snorkeling), <strong>Abu Nuhas</strong> (épaves), Elphinstone Reef pour les requins-marteaux (plongeurs confirmés). La station souffre d'un développement urbain anarchique des années 2000 : choisir son resort soigneusement. Excursions à Louxor (5h de route, à programmer 1 nuit minimum sur place).",

    "johannesburg:fr": "Johannesburg vit à 1750m d'altitude : climat tempéré subtropical, jamais vraiment chaud. <strong>Septembre est mon mois préféré</strong> (9.1/10) — 10-25°C, 10% de pluie, ciel parfait. <strong>De juin à août</strong>, attendez-vous à des nuits glaciales (4-7°C) avec journées douces (17-21°C) — paradoxe d'un hiver clair et froid. <strong>De novembre à mars</strong> (été austral), prévoyez 13-26°C avec 32-55% de précipitations — orages violents en fin d'après-midi, parfois grêle. La sécurité reste un sujet : les quartiers Sandton et Rosebank concentrent l'activité touristique sécurisée, le centre-ville (downtown) demande accompagnement. Le <strong>Apartheid Museum</strong> est l'incontournable historique. Soweto se visite en tour organisé. Pretoria à 1h en train Gautrain. Joburg sert surtout de hub vers Kruger National Park (5h de route ou vol intérieur), Drakensberg, Cape Town. La cuisine fusion locale (boerewors, bunny chow importé de Durban) mérite l'arrêt.",

    "gibraltar:fr": "Gibraltar, c'est 6 km² de territoire britannique au sud de l'Espagne : Rock à 426m, singes berbères en liberté, livre sterling, conduite à droite. Climat méditerranéen marin. <strong>Juillet est mon mois préféré</strong> (9.8/10) — 20-28°C, 2% de pluie, vent de Levant qui rafraîchit. <strong>De décembre à mars</strong>, attendez-vous à 9-17°C et 28-41% de pluie — humide et venteux. <strong>Le passage de la frontière</strong> depuis La Línea (Espagne) peut prendre 5 minutes ou 2h selon l'horaire et la tension diplomatique du moment (post-Brexit, contrôles renforcés). Le téléphérique du Rock, les grottes de Saint Michael, et la traversée des fortifications du siège tiennent une journée. Les singes (Barbary macaques) sont sauvages et opportunistes — ne jamais leur montrer de nourriture. Le ferry pour Tanger (Maroc) part de Tarifa à 30 minutes en voiture. Gibraltar Airport a une piste qui traverse la route principale — phénomène curieux à observer.",

    "lanzarote:fr": "Lanzarote a été marquée par <strong>César Manrique</strong>, l'artiste qui a imposé l'urbanisme bas et blanc : pas de gratte-ciel, pas de panneaux publicitaires criards. Climat sec quasi désertique. <strong>Août est mon mois préféré</strong> (9.0/10) — 18-23°C, 5% de pluie, alizés constants. <strong>Toute l'année reste douce</strong> (12-23°C, 12-21% de pluie), c'est l'île la plus stable des Canaries. <strong>Timanfaya</strong> (paysages volcaniques quasi lunaires), le <strong>Jameos del Agua</strong> et la <strong>Cueva de los Verdes</strong> sont les passages obligés (création Manrique). <strong>Famara</strong> au nord-ouest est devenu un spot mondial de surf et de bodyboard. La Geria pour les vignes plantées dans le sable noir. Île plus petite que Tenerife, mais très diverse : 2-3 jours minimum recommandés. Le <strong>calima</strong> (vent de sable saharien) peut frapper 3-5 fois par an avec ciel ocre soudain et 28°C.",

    "mexico:fr": "Mexico City vit à 2240m d'altitude : <strong>l'altitude se ressent les premiers jours</strong> (souffle court, sommeil moins profond). Climat tempéré toute l'année malgré la latitude tropicale. <strong>Mars-avril sont mes mois préférés</strong> (9.2/10) — 11-28°C, 15-23% de pluie, jacarandas en fleurs partout dans Roma et Condesa. <strong>De juin à septembre</strong>, attendez-vous à la saison des pluies (40-88% d'averses) — quasi tous les après-midi, mais matinées souvent ensoleillées. La pollution s'améliore alors. <strong>D'octobre à février</strong>, c'est la saison sèche : ciel clair, mais pollution qui peut piquer les yeux certains jours d'inversion thermique (Pico Indice IMECA à surveiller). Roma Norte et Condesa pour la scène café et resto, Centro Histórico pour le Zócalo et les murals de Diego Rivera. <strong>Teotihuacán</strong> à 1h30 de bus. Coyoacán pour la Casa Azul (Frida Kahlo). Mexico est devenue une destination digital nomad majeure depuis 2020 : Wifi excellent, coworkings denses, mais loyers en hausse forte (+50% en 4 ans).",

    "milos:fr": "Milos est la <strong>Cyclade géologique</strong> : 70 plages, falaises blanches, paysages volcaniques. Moins fréquentée que Santorin ou Mykonos, mais ça change vite. <strong>Juin est mon mois préféré</strong> (9.8/10) — 21-27°C, 3% de pluie, mer à 22°C, prix encore raisonnables. <strong>Sarakiniko</strong> (paysage lunaire blanc), <strong>Kleftiko</strong> (grottes accessibles en bateau), Tsigrado (escalade pour descendre) sont les icônes. Klima village de pêcheurs avec ses syrmata colorés (anciens hangars à bateaux). <strong>De juillet à août</strong>, prévoyez 24-29°C avec 1-3% de pluie — pic touristique grec (les Grecs eux-mêmes vacancient en août). <strong>De novembre à mars</strong>, attendez-vous à 10-19°C et 23-37% de pluie — beaucoup de restos ferment, ferries réduits, ambiance hibernale grecque. Mai-juin et septembre-octobre restent les meilleurs compromis. Accès depuis Athènes : ferry rapide 3-4h ou vol 30 minutes (mais cher).",

    "brisbane:fr": "Brisbane est plus calme que Sydney ou Melbourne : capitale du Queensland sans les foules, fleuve qui serpente, climat subtropical. <strong>Novembre est mon mois préféré</strong> (8.7/10) — 18-28°C, 38% de pluie en averses brèves, journées de 13h. <strong>De décembre à mars</strong>, attendez-vous à 20-30°C avec 40-54% de précipitations — saison humide subtropicale, parfois inondations sévères (2011, 2022). <strong>De juin à août</strong> (hiver austral), prévoyez 10-22°C et 17-23% de pluie — climat doux quasi parfait, idéal pour South Bank, Story Bridge climb, Mount Coot-tha. Brisbane sert surtout de base : <strong>Gold Coast</strong> à 1h (Surfers Paradise, Burleigh), <strong>Sunshine Coast</strong> à 1h30 (Noosa, Glass House Mountains), <strong>Stradbroke Island</strong> et Moreton Island en ferry pour les dauphins/dugongs. La scène café Fortitude Valley et West End mérite l'exploration. Vols directs depuis Singapour, Doha, LA.",

    "paros:fr": "Paros est le bon compromis cycladique : moins iconique que Santorin, plus animée que Milos, transports faciles. <strong>Juin reste mon mois préféré</strong> (9.6/10) — 22-27°C, 5% de pluie, mer à 21°C, foules encore raisonnables. <strong>Naoussa</strong> au nord (port pittoresque, restos en bord de mer) et Parikia (capitale, ferry, Panagia Ekatontapyliani) concentrent l'animation. <strong>Antiparos</strong> juste en face en ferry de 10 minutes pour la grotte et le calme. <strong>De juillet à août</strong>, prévoyez 24-29°C, 1% de pluie, et l'envahissement touristique : meltemi (vent du nord) souffle fort, parfait pour kitesurf à Pounda. <strong>De novembre à mars</strong>, attendez-vous à 11-19°C et 20-37% de pluie — hibernation cycladique classique, beaucoup de tavernes et chambres ferment. Mai et septembre-octobre sont les vraies fenêtres équilibrées : météo encore estivale, foules réduites de 50%, tarifs en retrait. Comptez 4-5 jours pour bien apprécier.",

    "santorin:fr": "Santorin, c'est l'image qui définit la Grèce dans l'imaginaire collectif : caldeira, maisons blanches à dômes bleus, coucher de soleil sur Oia. <strong>Juillet est mon mois préféré</strong> (9.8/10) — 23-28°C, 1% de pluie, mer à 23°C. Mais c'est aussi l'icône surfréquentée des Cyclades : <strong>jusqu'à 17 000 visiteurs/jour en haute saison</strong> sur une île de 15 000 habitants. Oia au coucher du soleil = file d'attente serrée pour les meilleures positions photo. <strong>De juin et septembre</strong> sont mes vrais compromis : météo identique, foule réduite de 40%, tarifs hôtels divisés par 2. <strong>De novembre à mars</strong>, attendez-vous à 10-19°C et 24-32% de pluie — beaucoup d'hôtels et tavernes ferment, ambiance off-saison. Pour fuir la foule en saison : Akrotiri (le Pompéi grec, beaucoup moins fréquenté qu'Oia), wine tour (assyrtiko sur sols volcaniques), bain à Vlychada. Caldera-side rooms avec piscine privée à Imerovigli ou Firostefani plutôt qu'Oia : moins cher, vue identique, calme.",

    "cadix:fr": "Cadix se vante d'être <strong>la plus vieille ville d'Europe</strong> (3000 ans, fondation phénicienne). Péninsule andalouse battue par l'Atlantique. <strong>Juillet est mon mois préféré</strong> (9.7/10) — 21-29°C, 1% de pluie, mer à 22°C, plage Caleta accessible à pied du centre. <strong>Août chute à 6.9/10</strong> dans nos données : la chaleur intérieure (32-35°C ressentis) et l'humidité rendent les visites pesantes — mer à 23°C parfaite, mais centre historique brûlant. <strong>De décembre à mars</strong>, prévoyez 8-20°C et 22-37% de pluie — humide et venteux (levante), peu de tourisme, ambiance authentique. Le <strong>Carnaval de Cadix</strong> en février-mars est le 2e plus important d'Espagne après Tenerife : chirigotas et comparsas dans les rues pendant 12 jours. Excellente base pour Jerez (sherry, équitation), Tarifa (kitesurf, ferry Maroc), El Puerto de Santa María (manzanilla). Mai-juin et septembre-octobre sont les meilleurs compromis touristiques.",

    "sharm-el-sheikh:fr": "Sharm el-Sheikh est née du tourisme : station construite ex nihilo dans les années 1980 sur la pointe sud du Sinaï. Mer Rouge, récifs spectaculaires, infrastructure résolument all-inclusive. <strong>Avril est mon mois préféré</strong> (9.5/10) — 21-29°C, 1% de pluie, mer à 22°C. <strong>De juin à septembre</strong>, attendez-vous à 28-37°C — chaleur sèche supportable au bord de mer mais éprouvante en excursion. La plongée reste possible toute l'année, mais bateaux qui partent à 5h-6h pour rentrer avant la chaleur. Les sites de classe mondiale : <strong>Ras Mohammed</strong> (parc national), Tiran Island (drift dives), Shark/Yolanda Reef. <strong>De décembre à février</strong>, prévoyez 14-23°C avec un vent qui peut être glacial — combinaison 5mm pour la plongée. Naama Bay reste l'épicentre nightlife (mais sécurisée et un peu artificielle). Pour l'authentique : Dahab à 1h30 au nord (plus backpacker, moins all-inclusive). Mont Sinaï pour le lever de soleil reste un classique mystique.",

    "etosha:fr": "Etosha, c'est le parc safari emblématique de Namibie : 22 000 km² autour d'un immense lac salé asséché qui devient blanc éblouissant. <strong>Mai est mon mois préféré</strong> (9.4/10) — 15-29°C, 1% de pluie, animaux concentrés autour des points d'eau permanents (Okaukuejo, Halali, Namutoni). <strong>Toute la saison sèche d'avril à août</strong> est excellente pour le safari : visibilité maximale, animaux prévisibles aux waterholes. Les <strong>nuits à Okaukuejo waterhole</strong> (illuminé jusqu'à minuit) restent une expérience rare : éléphants, rhinocéros noirs, lions qui défilent à 30m. <strong>De septembre à décembre</strong>, attendez-vous à 18-36°C — la chaleur devient écrasante en milieu de journée (3 sorties safari : aube, fin de journée, nuit). <strong>De janvier à mars</strong> (saison des pluies), animaux dispersés, certaines pistes impraticables, mais paysages verts photogéniques et baby season. Hébergement : 3 camps NWR à l'intérieur du parc (à réserver 6 mois avant en haute saison) ou lodges privés en périphérie.",

    "cordoba-argentine:fr": "Córdoba est la 2e ville d'Argentine, université jésuite la plus ancienne d'Amérique du Sud (1613, UNESCO). Ville étudiante, sierras autour. <strong>Novembre est mon mois préféré</strong> (9.0/10) — 16-28°C, 33% de pluie, jacarandas en fleurs comme à Buenos Aires. <strong>De juin à août</strong> (hiver austral), prévoyez 5-19°C et 5-8% de pluie — sec et frais, idéal pour les randonnées dans les Sierras de Córdoba (Cerro Champaquí à 2790m). <strong>De décembre à février</strong>, attendez-vous à 19-30°C et 31-44% d'averses orageuses — chaleur supportable à l'altitude (400m), orages violents en fin d'après-midi. La <strong>Manzana Jesuítica</strong> et les estancias jésuites de la région (Alta Gracia, Santa Catalina, Jesús María) sont l'attraction culturelle majeure. Alta Gracia abrite la maison du Che Guevara. Mendoza à 11h en bus, Buenos Aires à 1h en avion. Les sierras chiquitanas (Capilla del Monte, La Cumbrecita) attirent les Argentins en weekend.",

    "gold-coast:fr": "La Gold Coast, c'est la côte de Brisbane : 70 km de plages, hauts buildings sur le front de mer, theme parks (Movie World, Sea World, Wet'n'Wild), surf de classe mondiale. <strong>Novembre est mon mois préféré</strong> (8.6/10) — 19-26°C, 38% de pluie en averses brèves, mer à 23°C. <strong>De décembre à mars</strong>, prévoyez 21-28°C avec 43-57% de précipitations — saison humide subtropicale, risque cyclonique réel (jusqu'à 1 par an). Méduses irukandji possibles (rare mais sérieux). <strong>De juin à août</strong>, prévoyez 13-21°C et 19-23% de pluie — c'est l'hiver austral local, idéal pour le surf à Snapper Rocks ou Kirra (vagues les plus régulières du monde) et la randonnée dans le hinterland (Lamington National Park, Springbrook). <strong>Surfers Paradise</strong> est le cœur touristique mais aussi le plus criard : pour le calme, Burleigh Heads, Coolangatta, Currumbin. Schoolies Week en novembre (jeunes diplômés) à éviter pour les familles.",

    "lisbonne:fr": "Lisbonne a explosé touristiquement depuis 2015 : Brexit, expats, digital nomades, croisières. La ville garde sa douceur de vivre malgré les loyers en flambée. <strong>Juillet-août sont mes mois préférés</strong> (9.7/10) — 18-28°C, 2-3% de pluie, terrasses en soirée jusqu'à minuit. <strong>De décembre à mars</strong>, attendez-vous à 9-17°C et 25-36% de pluie — atlantique, vent humide, mais ciel souvent clair entre les averses. C'est la fenêtre des fado authentiques dans Alfama (les troupes commerciales fonctionnent toute l'année, mais les vraies maisons de fado vibrent en hiver). Le tram 28 reste iconique mais saturé en saison : préférer le 15 (Belém) ou le 18 (moins touristique). Cascais et Sintra à 30 minutes en train. <strong>Sintra-Pena</strong> est devenu un classique : y aller en semaine et tôt (réservation obligatoire). La scène <strong>pastéis de nata</strong> dépasse Belém : Manteigaria (Chiado) reste mon préféré. Mai-juin et septembre-octobre sont les meilleurs compromis foule/météo.",

    "le-cap:fr": "Cape Town est régulièrement classée plus belle ville du monde : Table Mountain à pic, Cape Point, vignobles à 30 minutes (Stellenbosch, Franschhoek). Climat méditerranéen austral. <strong>Janvier-février sont mes mois préférés</strong> (9.2-9.3/10) — 17-25°C, 8-10% de pluie, journées longues, mer à 18-19°C (côté Atlantique froid, côté False Bay 21°C). <strong>De juin à août</strong> (hiver austral), prévoyez 10-17°C et 34-40% de pluie — humide, ciel souvent gris, ferry/téléphérique vers Robben Island et Table Mountain souvent annulés pour vent. <strong>Le téléphérique de Table Mountain</strong> ferme régulièrement pour conditions météo : avoir un plan B. <strong>Le Cap des Aiguilles</strong> à 2h30 est le vrai sud de l'Afrique. Les <strong>baleines franches australes</strong> visitent Hermanus de juin à novembre (1h30). Sécurité : les townships demandent guide, le centre-ville et Camps Bay restent sécurisés. <strong>Stellenbosch</strong> et Franschhoek pour la wine route (Pinotage, Chenin blanc). Boulders Beach pour les manchots du Cap.",

    "formentera:fr": "Formentera, c'est la sœur calme d'Ibiza : pas d'aéroport, accès uniquement par ferry depuis Ibiza (30 minutes). Île plate (longueur 19 km), idéale en vélo. Plages turquoise type Caraïbes. <strong>Juillet est mon mois préféré</strong> (9.7/10) — 24-26°C, 1% de pluie, mer à 25°C. <strong>De juillet à août</strong>, attendez-vous à un envahissement total : Italiens et Français de luxe, prix x3, restos saturés. <strong>Plages mythiques</strong> : Ses Illetes (régulièrement classée parmi les plus belles d'Europe), Cala Saona, Migjorn. <strong>De novembre à mars</strong>, prévoyez 13-19°C et 17-28% de pluie — l'île hiberne presque totalement : 80% des restos et hôtels ferment. Mai-juin et septembre-octobre sont les vrais compromis : météo encore parfaite, vélo agréable, et possibilité de profiter des plages quasi seul. Pas de vie nocturne (à l'inverse d'Ibiza) : c'est une destination contemplation, pas fête. Faro de la Mola pour le coucher de soleil.",

    "nairobi:fr": "Nairobi vit à 1700m d'altitude : climat doux toute l'année (13-28°C), pas de canicule africaine, mais pluies marquées. <strong>Février est mon mois préféré</strong> (9.0/10) — 15-28°C, 28% de pluie. <strong>D'avril à mai et octobre-décembre</strong>, attendez-vous aux saisons des pluies (43-86% d'averses, surtout en avril) — pistes des parcs nationaux peuvent devenir difficiles. La fenêtre <strong>juin à octobre</strong> reste la meilleure pour les safaris : <strong>Masai Mara</strong> avec la grande migration (juillet-septembre), <strong>Amboseli</strong> avec le Kilimandjaro en arrière-plan. La sécurité demande vigilance (Westlands, Karen, Lavington = quartiers sécurisés ; éviter le centre-ville la nuit). Le <strong>David Sheldrick Wildlife Trust</strong> (orphelinat éléphants) ouvre 1h/jour à 11h. Nairobi National Park est unique : safari avec skyline en arrière-plan. Karen district (du nom de Karen Blixen) garde le charme colonial avec Giraffe Centre voisin. Bus aéroport peu fiable : Uber ou taxi recommandé.",

    "funchal:fr": "Funchal est la capitale de Madère : île portugaise volcanique de l'Atlantique, à 1000 km du Portugal continental. Climat subtropical doux toute l'année. <strong>Juillet-août sont mes mois préférés</strong> (9.4/10) — 20-27°C, 10-12% de pluie, mer à 22°C. <strong>De décembre à février</strong>, prévoyez 13-19°C et 31-35% de pluie — le côté nord de l'île reste humide quasi toute l'année (laurisilve UNESCO), le sud (Funchal, Calheta) est nettement plus sec. Le réseau des <strong>levadas</strong> (canaux d'irrigation aménagés en sentiers) couvre toute l'île : 25 de Fontes, Caldeirão Verde, Levada do Caldeirão sont les classiques. Le téléphérique de Monte (gardens) et la descente en luge en osier (carros de cesto) restent emblématiques. <strong>Câmara de Lobos</strong> (village de pêcheurs immortalisé par Churchill). Le vin de Madère se déguste à toutes les bodegas du centre. Pico Ruivo (1862m) accessible en 1h30 de marche depuis Pico do Arieiro pour le lever de soleil au-dessus des nuages.",

    "livingstone:fr": "Livingstone, côté zambien des chutes Victoria, offre un accès plus calme et nature que Victoria Falls (côté Zimbabwe). <strong>Mai est mon mois préféré</strong> (9.4/10) — 14-27°C, 0% de pluie, fenêtre juste après les pluies où les chutes sont à pleine puissance. <strong>D'avril à juillet</strong>, c'est la saison des hautes eaux : volume maximum (10 millions de litres/seconde en pic), mais brume tellement dense qu'on ne voit parfois rien depuis le bord — le Devil's Pool sur Livingstone Island est fermé pendant cette période. <strong>D'août à octobre</strong> (saison sèche, basses eaux), c'est l'inverse : visibilité parfaite, bain dans le <strong>Devil's Pool</strong> (piscine naturelle au bord du précipice, 100€), mais débit visuellement moins impressionnant. <strong>De novembre à mars</strong> (saison des pluies), attendez-vous à 20-31°C et 35-69% de précipitations — chaleur humide, certains lodges ferment, mais paysages reverdis. Chobe National Park au Botswana à 2h pour les éléphants en abondance. Vol depuis Lusaka, Johannesburg ou Nairobi."
}

print(f"Préparé : {len(AVIS_BATCH2_FR)} avis")

with open(PATH, encoding='utf-8') as f:
    data = json.load(f)

before = len([k for k in data if not k.startswith('_')])

data['_version'] = '1.3'
data['_updated'] = '2026-04-27'

for k, v in AVIS_BATCH2_FR.items():
    data[k] = v

after = len([k for k in data if not k.startswith('_')])

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Avis FR avant : {before}")
print(f"Avis FR après : {after}")
print(f"Nouveaux : {after - before}")
