"""Batch 6 : 30 avis FR Tier 1 Asie + Amérique du Nord majeurs."""
import json

PATH = 'data/avis_annuel.json'
data = json.load(open(PATH, encoding='utf-8'))

AVIS_BATCH6_FR = {
    "hong-kong:fr": "Hong Kong est la mégapole verticale par excellence : 7 millions d'habitants, 8000 gratte-ciels (plus que Manhattan), et 70% du territoire qui reste en parcs naturels. <strong>Octobre-novembre sont mes mois préférés</strong> (8.3-8.4/10) : 19-27°C, 21-36% de pluie, taux d'humidité enfin supportable. <strong>De juin à septembre</strong>, c'est la mousson : 70-91% de précipitations, taux d'humidité oppressant (90%), risque de typhons (signal T8 ou T10 = ville à l'arrêt). <strong>De décembre à février</strong>, comptez 14-22°C : frais et sec, mois idéal pour la randonnée (Dragon's Back, Lantau Peak). <strong>Tour du Peak</strong> en tram (vues classiques), <strong>Star Ferry</strong> Central-Tsim Sha Tsui (1$, l'un des moins chers et plus mémorables au monde), <strong>Temple Street Night Market</strong> à Yau Ma Tei. Pour la cuisine : dim sum chez Tim Ho Wan (étoilé Michelin le moins cher au monde), wonton noodles chez Mak's Noodle. Lantau pour le Big Buddha et le village de pêcheurs Tai O. Macao à 1h en ferry pour les casinos.",

    "shanghai:fr": "Shanghai joue son rôle de capitale économique de la Chine moderne : skyline futuriste de Pudong, héritage colonial du Bund, 26 millions d'habitants. <strong>Mai et octobre sont mes mois préférés</strong> (8.0/10) : 16-25°C, 25-37% de pluie, températures clémentes entre canicule estivale et hiver humide. <strong>Juillet-août</strong> sont oppressants (26-32°C, humidité saturée), <strong>Shanghainais qui partent en vacances</strong> : ville étrangement plus calme. <strong>De décembre à février</strong>, comptez 2-11°C et 20-31% de pluie : froid humide qui pénètre, jours souvent gris. <strong>Le Bund</strong> au coucher du soleil pour les contrastes architecturaux Est-Ouest, <strong>Yu Garden</strong> et la vieille ville, <strong>Pudong</strong> (tour Shanghai 632m, observatoire), <strong>Concession française</strong> pour l'ambiance villageoise et les cafés branchés. <strong>Tester</strong> xiaolongbao chez Din Tai Fung ou Jia Jia Tang Bao, hairy crab (saison automne uniquement). Métro très efficace, Maglev de l'aéroport Pudong (430 km/h, 8 min jusqu'à Longyang). Visa 144h gratuit pour transit possible.",

    "pekin:fr": "Pékin (Beijing) concentre 3000 ans d'histoire impériale : Cité Interdite, Temple du Ciel, Grande Muraille à proximité. <strong>Mai est mon mois préféré</strong> (9.0/10) : 15-28°C, 15% de pluie, ciel le plus dégagé de l'année, jardins du Yiheyuan en fleurs. <strong>De juin à août</strong>, comptez 22-33°C avec mousson en juillet (38-48% de pluie) et chaleur lourde. <strong>De décembre à février</strong>, comptez -6/6°C : froid sec, ciel souvent dégagé, mais smog parfois pesant en cas d'inversion thermique (vérifier l'AQI avant de sortir). Le <strong>chauffage central</strong> démarre le 15 novembre. <strong>Sites majeurs</strong> : Cité Interdite (réservation obligatoire, 1h-2h queue sinon), Temple du Ciel (matin pour voir les locaux pratiquer le tai-chi), Place Tian'anmen, Grande Muraille à Mutianyu (moins fréquentée que Badaling, accessible en 2h). <strong>Hutongs</strong> (vieilles ruelles) autour de Houhai et Nanluoguxiang. <strong>Tester</strong> canard laqué chez Da Dong, jianbing au petit-déjeuner. Septembre-octobre sont les vrais bons compromis tourisme/météo.",

    "singapour:fr": "Singapour est la cité-État ultra-moderne par excellence : 6 millions d'habitants, 100% urbain, mais 47% d'espaces verts. Climat équatorial = il fait chaud et humide TOUTE l'année (24-30°C constants). <strong>Février est mon mois préféré</strong> (6.9/10) : 24-30°C, 68% de pluie, début de la mousson sèche du nord-est. <strong>D'avril à mai et de novembre à janvier</strong>, ce sont les saisons des moussons : 80-93% de précipitations en averses brèves mais intenses (souvent fin d'après-midi). Singapour ne dépasse jamais 6.9/10 : climat trop humide pour atteindre l'excellent. <strong>Sites majeurs</strong> : Gardens by the Bay (Supertrees, dômes climatisés), Marina Bay Sands (piscine à 200m de hauteur, payante en haut), Sentosa (île parc), Universal Studios. <strong>Hawker centres</strong> pour la cuisine (Maxwell, Lau Pa Sat, Newton) : chicken rice, chili crab, laksa, char kway teow à 4-7$. <strong>Quartiers</strong> : Chinatown, Little India, Kampong Glam (arabe). Très cher hors hawkers : repas resto 30-60$, hôtel 4* 200-400$. Vol direct depuis Paris en 13h.",

    "seoul:fr": "Séoul concentre 50% de la population sud-coréenne (25 millions en aire urbaine). <strong>Mai et juin sont mes mois préférés</strong> (8.4-8.5/10) : 12-27°C, 27-34% de pluie, fin du printemps avec azalées et roses au Changgyeonggung. <strong>De juillet à août</strong>, c'est la mousson (changma) : 52-56% de précipitations, taux d'humidité oppressant. <strong>De décembre à février</strong>, comptez -6/3°C et 10-16% de pluie : froid sec, ski possible à 1h en bus (Yongpyong, Vivaldi Park). <strong>Octobre-novembre</strong> sont mes vrais bons compromis : 9-25°C, ciel clair, momiji dans les palais et les hutongs. <strong>Sites majeurs</strong> : 5 palais Joseon (Gyeongbokgung, Changdeokgung avec son Secret Garden, Changgyeonggung, Deoksugung, Gyeonghuigung), Bukchon Hanok Village, Insadong, DMZ (zone démilitarisée à 1h, tour obligatoire). <strong>Quartiers</strong> : Gangnam (luxe, K-pop), Hongdae (étudiant), Itaewon (international), Myeongdong (shopping). <strong>Tester</strong> bibimbap, samgyeopsal (barbecue coréen), tteokbokki, soju. T-money card pour métro/bus.",

    "busan:fr": "Busan est la 2e ville coréenne et le plus grand port du pays : 3,4 millions d'habitants, 7 plages, 4 marchés de poissons. <strong>Mai-juin sont mes mois préférés</strong> (8.2/10) : 13-26°C, 28-38% de pluie, bonne température pour la plage de Haeundae sans la foule estivale. <strong>De juillet à septembre</strong>, comptez 20-30°C et 38-53% de précipitations : saison des typhons (Maemi 2003 a marqué les esprits), mais aussi le <strong>Busan International Film Festival</strong> début octobre. <strong>De décembre à février</strong>, comptez -3/8°C et 12-18% de pluie : froid sec, mer trop froide pour la baignade mais randonnées sur les sentiers de Haeundae et de Galmet. <strong>Sites majeurs</strong> : Haeundae et Gwangalli pour les plages urbaines, <strong>Gamcheon Culture Village</strong> (le \"Santorin coréen\", maisons colorées), <strong>Jagalchi Fish Market</strong> (le plus grand de Corée), <strong>Beomeosa</strong> (temple bouddhiste majeur), pont Diamond Bridge la nuit. <strong>Tester</strong> milmyeon (nouilles froides spécialité), seafood porridge, dwaeji gukbap. Vol direct depuis Paris ou via Seoul en KTX (2h30).",

    "kuala-lumpur:fr": "Kuala Lumpur est la capitale malaisienne, ville cosmopolite (Malais, Chinois, Indiens), avec ses Petronas Twin Towers (452m). <strong>Janvier-février sont mes mois préférés</strong> (5.9-6.0/10) : 24-32°C, 64-77% de pluie, c'est la saison sèche du nord-est, taux d'humidité plus supportable. <strong>De mars à mai et octobre à novembre</strong>, ce sont les moussons : 76-96% de précipitations en averses tropicales d'après-midi. KL ne dépasse jamais 6/10 : climat équatorial trop chaud-humide. <strong>Sites majeurs</strong> : <strong>Petronas Twin Towers</strong> (skybridge au 41e étage et observatoire au 86e, réservation obligatoire), <strong>Batu Caves</strong> (272 marches, statue géante de Murugan dorée), <strong>KL Tower</strong> (vue à 360°), <strong>Chinatown</strong> Petaling Street, <strong>Little India</strong> Brickfields. <strong>Hawker culture</strong> mais moins développée qu'à Singapour ou Penang. <strong>Tester</strong> nasi lemak (plat national), char kway teow, satay, durian (saison juin-août, odeur très forte). KL est moins chère que Singapour : repas 4-8 RM (1-2€) en hawker, hôtel 4* 50-100€. Vol direct Paris en 13h.",

    "siem-reap:fr": "Siem Reap est la base pour visiter <strong>Angkor Wat</strong>, le plus grand complexe religieux du monde (400 km²). <strong>Janvier est mon mois préféré</strong> (6.9/10) : 22-31°C, 7% de pluie, c'est la saison sèche, taux d'humidité acceptable. Siem Reap ne dépasse jamais 7/10 : climat tropical chaud constant. <strong>De mai à octobre</strong>, c'est la mousson : 76-91% de précipitations en averses violentes, mais paysages plus verts (rizières, Tonlé Sap inondé), foules réduites de 60%, prix divisés par 2. <strong>D'avril à mai</strong>, c'est la chaleur écrasante (26-35°C) avant la mousson : éprouvante pour les visites de temples. <strong>Sites Angkor</strong> : Angkor Wat (lever de soleil mythique mais bondé, alternative coucher de soleil au Pre Rup), Bayon (visages), Ta Prohm (envahi par la jungle, Tomb Raider), Banteay Srei à 1h (le plus délicat). <strong>Pass Angkor</strong> : 37$/jour, 62$/3 jours, 72$/7 jours. <strong>Pub Street</strong> en ville pour la nightlife (touristique). <strong>Tonlé Sap</strong> et les villages flottants (Kompong Phluk vs Chong Khneas plus cliché). Tester amok (curry de poisson), lok lak.",

    "phnom-penh:fr": "Phnom Penh, capitale cambodgienne, garde la mémoire douloureuse des Khmers rouges (1975-1979) qui ont assassiné 1,7 million de personnes. <strong>Janvier-février sont mes mois préférés</strong> (6.9/10) : 23-33°C, 11-12% de pluie, saison sèche, taux d'humidité acceptable. <strong>De mai à octobre</strong>, c'est la mousson : 79-93% de précipitations en averses violentes (souvent fin d'après-midi). Phnom Penh ne dépasse jamais 7/10 : climat tropical constant. <strong>D'avril à mai</strong>, c'est la chaleur écrasante (26-35°C). <strong>Sites incontournables (mémoriels)</strong> : <strong>Tuol Sleng (S-21)</strong> ancien lycée transformé en prison de torture par les Khmers rouges, <strong>Choeung Ek Killing Fields</strong> à 15 km (mémorial des charniers). Visiter ces deux sites en une matinée (très éprouvant émotionnellement). <strong>Sites royaux</strong> : Palais royal et Pagode d'argent, Musée National (sculptures khmères). <strong>Riverfront</strong> (Sisowath Quay) au coucher du soleil. <strong>Marché central</strong> (Phsar Thmei, art déco 1937). Vie nocturne sur Bassac Lane. Tester amok, lok lak, num pang. À 6h en bus de Siem Reap, 5h de Ho Chi Minh.",

    "luang-prabang:fr": "Luang Prabang est l'ancienne capitale royale du Laos, classée UNESCO : 33 temples, architecture coloniale française, fleuve Mékong. <strong>Décembre est mon mois préféré</strong> (9.2/10) : 17-28°C, 11% de pluie, ciel dégagé, lumière dorée sur les toits dorés. <strong>Novembre à février</strong> sont la haute saison : 16-31°C, peu de pluie. <strong>De mai à octobre</strong>, c'est la mousson : 35-90% de précipitations, mais paysages verts. <strong>D'avril à mai</strong>, c'est la chaleur étouffante (24-35°C) et la pollution agricole (brûlis). <strong>Sites incontournables</strong> : <strong>Cérémonie du tak bat à l'aube</strong> (procession de 200 moines en tunique safran qui collectent les offrandes, vers 5h30-6h, très silencieuse, ne pas perturber), <strong>Mont Phousi</strong> (300 marches, vue 360° au coucher du soleil), <strong>Wat Xieng Thong</strong> (le plus beau temple, 1560), <strong>Royal Palace Museum</strong>. <strong>Cascades de Kuang Si</strong> à 30 km (eau turquoise, baignade possible, sanctuaire d'ours). <strong>Marché de nuit</strong> textile/artisanat. Croisière sur le Mékong vers les <strong>grottes de Pak Ou</strong>. Vol direct depuis Bangkok ou Hanoi.",

    "hanoi:fr": "Hanoi, capitale vietnamienne, garde son charme colonial français mêlé à l'animation asiatique : 6 millions d'habitants, 8 millions de scooters. <strong>Octobre-novembre sont mes mois préférés</strong> (7.8-8.1/10) : 19-29°C, 28-44% de pluie, températures clémentes, lumière dorée sur le lac Hoan Kiem. <strong>De juin à août</strong>, c'est la mousson : 60-80% de précipitations, taux d'humidité oppressant (90%), chaleur (26-33°C). <strong>De décembre à mars</strong>, comptez 15-26°C : crachin caractéristique (peu intense mais persistant), température fraîche le matin. <strong>Sites majeurs</strong> : <strong>Vieille ville (36 rues)</strong> où chaque rue était dédiée à un métier (rue de la soie, du papier, etc.), <strong>Lac Hoan Kiem</strong> et son temple, <strong>Mausolée Ho Chi Minh</strong>, <strong>Temple de la Littérature</strong> (1er université du Vietnam), <strong>Quartier français</strong>. Théâtre de marionnettes sur l'eau (spectacle authentique). <strong>Tester</strong> pho bo (chez Pho Gia Truyen), bun cha (Obama l'a popularisé chez Bun Cha Huong Lien), banh mi, café aux oeufs. <strong>Baie d'Halong</strong> à 3h30 en bus pour 1-3 jours en croisière. <strong>Sapa</strong> à 6h en train de nuit pour les rizières en terrasses.",

    "ho-chi-minh:fr": "Ho Chi Minh-Ville (ex-Saigon) est la capitale économique du Vietnam : 9 millions d'habitants, dynamisme tropical, héritage français. <strong>Janvier-février sont mes mois préférés</strong> (6.9/10) : 23-34°C, 13-14% de pluie, c'est la saison sèche, mais HCMV ne dépasse jamais 7/10 (climat tropical chaud constant). <strong>De mai à novembre</strong>, c'est la mousson : 64-98% de précipitations en averses tropicales d'après-midi (souvent 30 min puis ciel clair). <strong>Mars-avril</strong> = pic de chaleur (25-35°C). <strong>Sites majeurs</strong> : <strong>Tunnels de Cu Chi</strong> à 2h (réseau souterrain Viêt-cong, très étroit), <strong>Musée des vestiges de la guerre</strong> (Musée des Crimes de guerre), <strong>Cathédrale Notre-Dame</strong> (briques de Toulouse), <strong>Poste centrale</strong> (Eiffel), <strong>Palais de la Réunification</strong>. <strong>Quartier 1</strong> pour le centre business, <strong>Quartier 4</strong> pour les food streets, <strong>Cholon</strong> pour le Chinatown et le marché Binh Tay. <strong>Tester</strong> pho (différent du Hanoi), banh xeo (crêpes croustillantes), com tam (riz cassé), café au lait condensé. <strong>Mékong delta</strong> à 2h pour les marchés flottants (Cai Be plus authentique que Cai Rang).",

    "hoi-an:fr": "Hoi An est l'ancien comptoir marchand UNESCO du centre Vietnam : maisons jaunes japonaises et chinoises, lanternes colorées, plage à 5 km. <strong>Février est mon mois préféré</strong> (7.9/10) : 20-25°C, 49% de pluie, fin de saison sèche avant la chaleur. <strong>De mars à mai</strong>, comptez 22-32°C et 25-44% de pluie : doux, idéal pour la plage An Bang. <strong>De septembre à décembre</strong>, c'est la saison des pluies/typhons : 65-85% de précipitations, inondations possibles dans la vieille ville (la rivière Thu Bon déborde, la ville devient navigable en pirogue, photogénique mais perturbant). <strong>D'avril à août</strong>, ciel souvent dégagé mais chaleur (26-34°C). <strong>Sites majeurs</strong> : Pont japonais couvert, Maison Tan Ky, Assembly Hall des Cantonais, Marché central. <strong>Plein de tailleurs</strong> (sur-mesure en 24-48h, costume 80-150$, qualité variable). <strong>Cours de cuisine</strong> très populaires (chez Madame Vy, Red Bridge). <strong>My Son</strong> à 1h (ruines hindoues Cham). <strong>Plage An Bang</strong> ou Cua Dai (érosion sévère depuis 2010). <strong>Tester</strong> cao lau (spécialité), white rose (raviolis), banh mi Phuong (le meilleur du Vietnam selon Bourdain).",

    "taipei:fr": "Taipei est la capitale de Taïwan : 7 millions en aire urbaine, dominée par la Taipei 101 (508m, 2e plus haute tour à sa construction en 2004). <strong>Avril est mon mois préféré</strong> (7.9/10) : 19-26°C, 48% de pluie, températures douces avant la mousson. <strong>De mai à septembre</strong>, c'est la saison chaude et humide : 47-70% de précipitations, taux d'humidité saturé (90%), saison des typhons. <strong>De décembre à février</strong>, comptez 14-20°C et 39-45% de pluie : doux mais grisâtre (pluie fine persistante). <strong>Sites majeurs</strong> : <strong>Taipei 101</strong> (observatoire au 89e étage), <strong>Chiang Kai-shek Memorial Hall</strong> (relève de garde toutes les heures), <strong>Longshan Temple</strong>, <strong>Temple Bao'an</strong>, <strong>Beitou</strong> (sources thermales en métro). <strong>Marchés de nuit</strong> sont la signature taiwanaise : Shilin (le plus grand mais touristique), Raohe (plus authentique), Ningxia (cuisine traditionnelle). <strong>Tester</strong> beef noodle soup (plat national), xiaolongbao chez Din Tai Fung (origine taiwanaise), bubble tea, stinky tofu, mango shaved ice. <strong>Yangmingshan National Park</strong> au nord pour les sources chaudes et les fleurs de cerisiers (mars). <strong>Jiufen</strong> et <strong>Shifen</strong> à 1h en train pour les villages perchés.",

    "mumbai:fr": "Mumbai (Bombay), capitale économique de l'Inde : 22 millions d'habitants, Bollywood, Marine Drive le \"collier de la reine\". <strong>Janvier-février sont mes mois préférés</strong> (8.9/10) : 19-31°C, 0-2% de pluie, hiver tropical doux. <strong>De juin à septembre</strong>, c'est la mousson : 87-100% de précipitations en juillet (l'une des plus violentes au monde, 2400mm en 3 mois), inondations massives, transports paralysés. <strong>De mars à mai</strong>, comptez 23-33°C et chaleur lourde sur la côte. <strong>D'octobre à décembre</strong>, comptez 20-32°C et 0-40% de pluie : retour à la normale. <strong>Sites majeurs</strong> : <strong>Gateway of India</strong> (1924), <strong>Taj Mahal Palace Hotel</strong> (cible des attentats 2008), <strong>Marine Drive</strong> au coucher du soleil, <strong>grottes d'Elephanta</strong> (UNESCO, 1h en bateau), <strong>Dhobi Ghat</strong> (laverie à ciel ouvert avec 7000 lavandiers), <strong>gare CST</strong> (UNESCO). <strong>Bandra</strong> et <strong>Juhu</strong> pour les célébrités Bollywood. <strong>Slums tour</strong> à Dharavi (1 million d'habitants au km², controversé). <strong>Tester</strong> vada pav (street food), pav bhaji, butter chicken, biryani. Sécurité acceptable de jour. Vol direct depuis Paris en 9h.",

    "new-york:fr": "New York, c'est l'expérience urbaine ultime : 8,5 millions d'habitants à Manhattan-Bronx-Brooklyn-Queens-Staten Island. <strong>Juin reste mon mois préféré</strong> (8.6/10) : 17-26°C, 36% de pluie, parcs en pleine vie (Central Park, Prospect Park), terrasses, festivals (SummerStage, Shakespeare in the Park). <strong>Juillet-août</strong> sont chauds et humides (20-30°C, parfois canicule à 35°C+), New-yorkais qui fuient aux Hamptons en weekend. <strong>De décembre à février</strong>, comptez -3/6°C et 31-35% de pluie/neige : froid mordant en cas de blizzards, mais Noël magique (sapin Rockefeller Center, vitrines de Saks et Bergdorf). <strong>Septembre-octobre</strong> sont mes vrais bons compromis : 11-25°C, ciel dégagé, indian summer, foliage à Central Park fin octobre. <strong>Sites majeurs</strong> : Times Square, Empire State, Top of the Rock, Brooklyn Bridge à pied, MoMA, Met, Statue de la Liberté + Ellis Island, 9/11 Memorial. <strong>Quartiers</strong> : SoHo, West Village, Williamsburg (Brooklyn), Lower East Side. <strong>Tester</strong> bagel chez Russ & Daughters, pizza chez Joe's ou Roberta's, deli chez Katz's. Subway 24h/24. Eviter taxis hors aéroport (Uber/Lyft moins chers).",

    "chicago:fr": "Chicago est la 3e ville américaine, capitale du Midwest, ville architecturale majeure (où le gratte-ciel a été inventé en 1885). <strong>Juillet est mon mois préféré</strong> (8.6/10) : 19-27°C, 40% de pluie en orages, festivals (Lollapalooza fin juillet, Taste of Chicago), terrasses et plages du lac Michigan. <strong>D'août à septembre</strong>, comptez 16-26°C : températures encore agréables, foliage à partir d'octobre. <strong>De décembre à février</strong>, comptez -5/3°C : la \"Windy City\" mérite son nom, vents glaciaux du lac, blizzards possibles, journées à 9h de lumière. Mais marchés de Noël (Christkindlmarket) et patinoire Millennium Park. <strong>D'avril à mai</strong>, comptez 4-18°C et 39-46% de pluie : transition variable. <strong>Sites majeurs</strong> : <strong>Cloud Gate (le \"Bean\")</strong> au Millennium Park, <strong>Willis Tower Skydeck</strong> et <strong>360 Chicago Tilt</strong> pour la vue, <strong>Art Institute of Chicago</strong> (Hopper, Picasso, Seurat), <strong>Architecture River Cruise</strong> (vrai must), <strong>Navy Pier</strong>. <strong>Quartiers</strong> : Wicker Park, Logan Square, Hyde Park (Obama). <strong>Tester</strong> deep-dish pizza chez Lou Malnati's, Chicago hot dog, beef sandwich. Comédie au Second City (Bill Murray, Tina Fey).",

    "boston:fr": "Boston est la plus européenne des grandes villes américaines : pavés, briques rouges, université Harvard à Cambridge. <strong>Août reste mon mois préféré</strong> (8.8/10) : 18-28°C, 34% de pluie, parcs en pleine vie, plages de Cape Cod accessibles. <strong>Juillet</strong> est aussi excellent (8.6/10) avec le 4 juillet (feux d'artifice sur la Charles River). <strong>Septembre-octobre</strong> sont mes vrais bons compromis : 9-23°C, foliage spectaculaire en Nouvelle-Angleterre (pic mi-octobre, faire la route de Vermont depuis Boston). <strong>De décembre à mars</strong>, comptez -5/8°C : froid sec, neige fréquente (blizzards possibles), Boston Marathon le 3e lundi d'avril (Patriots' Day). <strong>Sites majeurs</strong> : <strong>Freedom Trail</strong> (4 km, 16 sites historiques de la Révolution américaine), <strong>Faneuil Hall et Quincy Market</strong>, <strong>Beacon Hill</strong> (quartier historique avec lampadaires à gaz), <strong>Harvard et MIT</strong> à Cambridge (visite du campus), <strong>Fenway Park</strong> (le plus vieux stade de baseball en activité, 1912). <strong>Quartiers</strong> : North End (cuisine italienne, Mike's Pastry pour cannolis), Back Bay, South End. <strong>Tester</strong> clam chowder, lobster roll (chez Neptune Oyster), Boston cream pie. Cape Cod et îles (Martha's Vineyard, Nantucket) à 2h en été.",

    "san-francisco:fr": "San Francisco joue sur la fraîcheur de son microclimat : courant de Californie + Pacifique = 12-22°C toute l'année. <strong>Juin-septembre sont mes mois préférés</strong> (8.3-8.4/10) : 12-19°C, 0-4% de pluie. <strong>Le Karl the Fog</strong> (brouillard côtier) caractéristique entre dans la baie en fin de journée même en plein été (Mark Twain : \"l'hiver le plus froid que j'aie passé fut un été à San Francisco\"). <strong>De décembre à mars</strong>, comptez 8-14°C et 29-36% de pluie : c'est la saison humide, ciel souvent gris. <strong>Sites majeurs</strong> : <strong>Golden Gate Bridge</strong> (vélo de Sausalito en fin d'après-midi), <strong>Alcatraz</strong> (réservation 2-3 mois avant en haute saison), <strong>cable cars</strong> sur Powell-Hyde, <strong>Lombard Street</strong> (la rue la plus tortueuse), <strong>Coit Tower</strong>, <strong>Painted Ladies</strong> à Alamo Square, <strong>Mission District</strong> pour les murals. <strong>Quartiers</strong> : Mission (Latino), Castro (LGBT historique, parade fin juin), Haight-Ashbury (hippie 60s), North Beach (italien). <strong>Tester</strong> sourdough chez Boudin (depuis 1849), Mission burrito chez La Taqueria, Dungeness crab. Napa et Sonoma Valley à 1h30 pour les vignobles.",

    "seattle:fr": "Seattle est la ville du Pacifique Nord-Ouest : Microsoft, Amazon, Starbucks, grunge (Nirvana, Pearl Jam), pluie. <strong>Juillet-août sont mes mois préférés</strong> (9.0-9.3/10) : 14-24°C, 11-16% de pluie, ciel enfin dégagé après l'hiver pluvieux, Mont Rainier visible depuis la ville. <strong>De novembre à mars</strong>, comptez 2-10°C et 52-60% de précipitations (réputation justifiée : 940mm/an mais surtout en pluie fine continue de 6 semaines, pas de gros orages). <strong>D'avril à mai</strong>, comptez 4-18°C : ciel s'éclaircit progressivement. <strong>Sites majeurs</strong> : <strong>Pike Place Market</strong> (premier Starbucks 1971, poissonniers qui lancent les saumons), <strong>Space Needle</strong> (184m, l'image emblématique de l'Expo 1962), <strong>Chihuly Garden and Glass</strong> (œuvres en verre de Dale Chihuly), <strong>MoPOP Museum</strong> (musique pop), <strong>Gas Works Park</strong> pour la vue. <strong>Quartiers</strong> : Capitol Hill (LGBT, alternatif), Fremont (\"république de Fremont\", excentrique), Ballard (scandinave). <strong>Tester</strong> les salmon, oysters, coffee partout. <strong>Mont Rainier</strong> (4392m) à 2h, <strong>Olympic Peninsula</strong> et sa rainforest à 3h, <strong>Vancouver</strong> à 3h. Vol direct depuis Paris.",

    "washington:fr": "Washington DC est la capitale fédérale : 700 000 habitants, mais 6 millions en aire urbaine. Centre-ville monumental autour du National Mall. <strong>Juin reste mon mois préféré</strong> (8.6/10) : 18-29°C, 41% de pluie, mais aussi humidité montante. <strong>Juillet-août chutent à 6.9/10</strong> à cause de la chaleur humide étouffante (21-31°C, ressenti 38°C+). <strong>De décembre à février</strong>, comptez -2/10°C : froid sec, parfois blizzards. <strong>Mars-avril</strong> est la saison des cerisiers (cherry blossoms autour du Tidal Basin, cadeau japonais de 1912, pic vers 1er-7 avril, Cherry Blossom Festival), pic touristique majeur. <strong>Septembre-octobre</strong> sont mes vrais bons compromis : 10-26°C, ciel dégagé, foliage. <strong>Sites majeurs (gratuits)</strong> : <strong>National Mall</strong> avec Lincoln Memorial, Washington Monument (562 marches), Capitol, White House (réservation via congressman), <strong>Smithsonian Museums</strong> (19 musées tous gratuits : Air and Space, American History, Natural History, African American History), <strong>Holocaust Memorial Museum</strong>, <strong>Arlington Cemetery</strong>. <strong>Georgetown</strong> pour le côté charmant. <strong>Tester</strong> half-smoke chez Ben's Chili Bowl. Métro efficace. À 4h en train de NYC (Acela), 1h de Baltimore.",

    "nashville:fr": "Nashville, capitale du Tennessee, est la \"Music City\" : capitale mondiale de la country music, 180 studios d'enregistrement, Grand Ole Opry depuis 1925. <strong>Septembre-octobre sont mes mois préférés</strong> (8.3-8.5/10) : 12-29°C, 26-32% de pluie, températures parfaites, foliage en Tennessee. <strong>De juin à août</strong>, comptez 20-32°C : chaud et humide, mais c'est la saison des concerts en plein air et des festivals (CMA Fest début juin, Bonnaroo à 1h en juin). <strong>De décembre à février</strong>, comptez -1/13°C et 35-46% de pluie : doux pour le sud mais grisâtre. <strong>D'avril à mai</strong> : températures parfaites, fleurs partout. <strong>Sites majeurs</strong> : <strong>Country Music Hall of Fame</strong>, <strong>Ryman Auditorium</strong> (Mère de la Country, ex-Grand Ole Opry), <strong>Grand Ole Opry House</strong> (concert tous les soirs), <strong>Honky Tonks</strong> sur Broadway (Tootsie's, Robert's Western World, gratuits, musique live de 10h à 3h), <strong>RCA Studio B</strong> (où Elvis a enregistré 200 chansons). <strong>Tester</strong> Hot Chicken (Prince's ou Hattie B's, pimenté niveau \"shut the cluck up\"), BBQ chez Martin's, biscuits chez Loveless Cafe. <strong>Vanderbilt</strong> et <strong>Belle Meade Plantation</strong> pour le contexte historique sud.",

    "austin:fr": "Austin, capitale du Texas, est la \"Live Music Capital of the World\" : 250 venues musicaux, festival SXSW. <strong>Octobre est mon mois préféré</strong> (8.7/10) : 18-29°C, 27% de pluie, chaleur qui retombe enfin après l'été, ACL Festival (Austin City Limits) début octobre. <strong>De juin à septembre</strong>, comptez 23-36°C : chaleur brutale (souvent 38-40°C en juillet-août), Austinians qui vivent en climatisation, sortent après 21h. <strong>De décembre à février</strong>, comptez 6-20°C : doux pour le Texas mais journées courtes, parfois neige rare. <strong>Mars-avril</strong> est le pic touristique avec <strong>SXSW</strong> (mi-mars, 10 jours, prix x4) et les bluebonnets en fleurs (état flower du Texas). <strong>Sites majeurs</strong> : <strong>Texas State Capitol</strong> (le plus grand des USA, 5m plus haut que celui de Washington), <strong>South Congress Avenue</strong> (boutiques, restos), <strong>Barton Springs</strong> (sources naturelles, 20°C toute l'année), <strong>Lady Bird Lake</strong> pour le kayak/SUP. <strong>Bats du Congress Avenue Bridge</strong> au coucher du soleil (mars-octobre, 1,5 million de chauves-souris). <strong>Tester</strong> brisket chez Franklin BBQ (queue de 4h+), tacos breakfast chez Veracruz, ice cream chez Amy's. Comté de Hill Country et vignobles à 1h.",

    "nouvelle-orleans:fr": "La Nouvelle-Orléans est l'une des villes américaines les plus singulières : héritage français/espagnol/africain/créole, jazz né ici (Louis Armstrong), cuisine cajun, Mardi Gras. <strong>Octobre est mon mois préféré</strong> (8.6/10) : 20-27°C, 28% de pluie, fin de la chaleur étouffante, festivals (Voodoo Festival fin octobre). <strong>De juin à septembre</strong>, comptez 24-31°C : chaud, humide, risque cyclonique réel (Katrina 2005, Ida 2021). <strong>De décembre à février</strong>, comptez 8-20°C : doux, parfait pour visiter sans foule. <strong>Mardi Gras</strong> (date variable février-mars, 2 semaines de festivités, pic le mardi avant le Carême) = pic touristique absolu, prix x4-x5, foule massive sur Bourbon Street. <strong>Sites majeurs</strong> : <strong>French Quarter (Vieux Carré)</strong>, <strong>Jackson Square</strong> et la cathédrale Saint-Louis, <strong>Bourbon Street</strong> (touristique), <strong>Frenchmen Street</strong> (jazz authentique, locaux), <strong>Garden District</strong> (maisons antebellum, tombeau d'Anne Rice), <strong>Cimetière Saint Louis n°1</strong> (tombeau de Marie Laveau, vaudou). <strong>Tester</strong> beignets au Café du Monde, gumbo, jambalaya, po'boy chez Domilise's, étouffée. Tour des plantations à 1h (Oak Alley, Whitney Plantation pour la perspective des esclaves).",

    "miami:fr": "Miami est la porte tropicale des USA : Latine (60% Hispaniques, surtout Cubains), plages, Art Déco, culture cubaine. <strong>Mars-avril sont mes mois préférés</strong> (8.5/10) : 20-28°C, 33-42% de pluie, mer à 24°C, fin de la haute saison touristique. <strong>De juin à octobre</strong>, c'est la saison cyclonique : 65-81% de précipitations, taux d'humidité oppressant (90%), risque réel d'ouragans (catégorie 4-5 possibles, Andrew 1992 a marqué les esprits). <strong>De décembre à février</strong> est la pleine haute saison : 18-26°C, 36-41% de pluie, prix hôteliers x3-x4, plages de South Beach pleines. <strong>Sites majeurs</strong> : <strong>South Beach</strong> et son <strong>Art Deco District</strong> (800 bâtiments années 30, Ocean Drive), <strong>Wynwood Walls</strong> (street art mondial), <strong>Little Havana</strong> (Calle Ocho, Domino Park, cigars chez El Crédito), <strong>Vizcaya</strong> (palais italien sur la baie). <strong>Spring Break américain</strong> mars = ambiance fête. <strong>Everglades National Park</strong> à 1h (alligators, airboat tour), <strong>Key West</strong> à 4h en voiture (Hemingway House). <strong>Tester</strong> Cuban sandwich, ceviche, stone crab claws (saison oct-mai chez Joe's), arepas, key lime pie.",

    "orlando:fr": "Orlando est la capitale mondiale des parcs d'attractions : Walt Disney World (4 parcs), Universal Studios (3 parcs), SeaWorld, Legoland. <strong>Mars-avril sont mes mois préférés</strong> (8.8/10) : 16-29°C, 25-31% de pluie, températures parfaites pour les parcs avant la chaleur estivale. <strong>De juin à septembre</strong>, comptez 23-31°C avec 73-84% de précipitations : chaleur lourde, orages quotidiens en fin d'après-midi (les parcs ferment temporairement, prévoir poncho), risque cyclonique. <strong>De décembre à février</strong>, comptez 10-25°C : haute saison touristique américaine (vacances scolaires, Christmas, Spring Break), prix hôteliers x2-x3. <strong>Walt Disney World</strong> = 4 parcs (Magic Kingdom, EPCOT, Hollywood Studios, Animal Kingdom) sur 110 km², compter 4-5 jours minimum, billets 100-200$/jour, application MyDisneyExperience indispensable, FastPass Genie+ payant 15-25$. <strong>Universal Studios</strong> + Islands of Adventure = 2 parcs (Wizarding World of Harry Potter, montagnes russes), 1-2 jours, billets 100-180$/jour. <strong>Hors parcs</strong> : Kennedy Space Center à 1h (lancements visibles depuis la ville). Tarif supérieur en Spring Break (mars), Thanksgiving, Noël, été. Septembre-octobre offrent les meilleurs prix mais météo plus risquée.",

    "las-vegas:fr": "Las Vegas est l'oasis de jeux et de divertissement en plein désert du Mojave : 40 millions de visiteurs/an, 150 000 chambres d'hôtels. <strong>Avril est mon mois préféré</strong> (9.5/10) : 14-27°C, 5% de pluie, températures idéales pour les piscines et les excursions désert. <strong>De juin à août chutent à 3.9/10</strong> à cause de la chaleur extrême (24-41°C, parfois 47°C, 2e ville la plus chaude des USA après Death Valley) : sortir devient pénible, mais les hôtels sont climatisés. <strong>De décembre à février</strong>, comptez 4-14°C : froid sec, soirées glaciales, mais bons prix hôteliers. <strong>D'octobre</strong>, comptez 15-28°C : autre excellente période (9.3/10). <strong>Sites majeurs</strong> : <strong>Le Strip</strong> (Las Vegas Boulevard, 6 km, 15 méga-resorts thématiques : Bellagio, Venetian, Caesars, Wynn, MGM Grand). <strong>Spectacles Cirque du Soleil</strong> (8 spectacles différents permanents), résidences musicales (Adele, U2 Sphere). <strong>Old Vegas</strong> à Fremont Street pour l'authentique. <strong>Excursions</strong> : Grand Canyon West (4h aller-retour), Hoover Dam (1h), Death Valley (2h, à éviter en été), Red Rock Canyon (30 min). Vol depuis Paris via NY ou LA. Buffets à volonté (institution locale). Tarifs fluctuent énormément (week-end x2-x3, conventions).",

    "montreal:fr": "Montréal est la 2e ville francophone au monde après Paris : île au confluent du Saint-Laurent, mélange français/anglais/multiculturel. <strong>Juillet est mon mois préféré</strong> (8.7/10) : 18-27°C, 39% de pluie, festivals (Festival International de Jazz de Montréal début juillet, Just for Laughs mi-juillet, Osheaga musique début août), terrasses partout. <strong>De décembre à mars</strong>, comptez -12/4°C et 39-44% de précipitations (souvent neige) : véritable hiver avec -20°C et blizzards possibles. C'est aussi quand la <strong>ville souterraine</strong> (RÉSO, 33 km de tunnels) prend tout son sens. Carnaval de Québec à 3h. <strong>Septembre-octobre</strong> sont mes vrais bons compromis : 7-22°C, foliage spectaculaire au Mont-Royal, Mont-Tremblant à 1h30. <strong>Sites majeurs</strong> : <strong>Vieux-Montréal</strong> (Place Jacques-Cartier, Notre-Dame), <strong>Mont-Royal</strong> (Belvédère Kondiaronk pour la vue), <strong>Marché Jean-Talon</strong> (le plus grand d'Amérique du Nord), <strong>Plateau Mont-Royal</strong> (escaliers extérieurs caractéristiques), <strong>Mile End</strong> (jewish bagels). <strong>Tester</strong> bagel chez St-Viateur ou Fairmount, smoked meat chez Schwartz's, poutine, tourtière, sirop d'érable (cabane à sucre en mars). Métro efficace.",

    "toronto:fr": "Toronto est la plus grande ville du Canada : 6,5 millions en aire urbaine, l'une des plus diverses au monde (50% nés à l'étranger). <strong>Juillet-août sont mes mois préférés</strong> (8.7-8.8/10) : 18-26°C, 32-36% de pluie, terrasses, festivals (Caribana fin juillet, TIFF début septembre), îles de Toronto en ferry pour la baignade. <strong>De décembre à mars</strong>, comptez -6/3°C et 31-41% de précipitations (souvent neige) : froid avec lake-effect snow, mais le PATH (29 km de tunnels souterrains) connecte tous les bâtiments du centre. <strong>Septembre-octobre</strong> sont mes vrais bons compromis : 8-22°C, foliage en Ontario, Niagara à 1h30. <strong>Sites majeurs</strong> : <strong>CN Tower</strong> (553m, EdgeWalk pour les courageux), <strong>Royal Ontario Museum</strong>, <strong>Distillery District</strong> (briques victoriennes), <strong>St. Lawrence Market</strong>, <strong>quartiers ethniques</strong> : Chinatown, Little Italy, Greektown, Koreatown. <strong>Sport</strong> : Maple Leafs (NHL), Raptors (NBA), Blue Jays (MLB) à Rogers Centre. <strong>Niagara Falls</strong> à 1h30 (côté canadien plus impressionnant), <strong>Niagara-on-the-Lake</strong> pour les vins de glace, <strong>Algonquin Park</strong> à 3h pour la nature. Vol direct depuis Paris en 8h.",

    "vancouver:fr": "Vancouver est la ville la plus accessible aux Européens sur la côte Pacifique du Canada : Pacifique d'un côté, montagnes (North Shore Mountains) de l'autre. <strong>Juillet est mon mois préféré</strong> (9.1/10) : 15-22°C, 15% de pluie, ciel enfin dégagé, baignade au Kits Beach et English Bay, randonnée à Grouse Mountain. <strong>De novembre à mars</strong>, comptez 1-9°C et 55-65% de précipitations : ville réputée la plus pluvieuse du Canada (1200mm/an), mais aussi quand <strong>Whistler</strong> (à 2h) ouvre sa saison ski. <strong>Mai-juin et septembre</strong> sont les meilleurs compromis. <strong>Sites majeurs</strong> : <strong>Stanley Park</strong> (1000 acres, plus grand que Central Park, totem poles), <strong>Granville Island</strong> (marché public, microbrasseries), <strong>Capilano Suspension Bridge</strong> (à 70m au-dessus du canyon), <strong>Gastown</strong> (Steam Clock, premier quartier), <strong>Grouse Mountain</strong> (téléphérique pour la vue). <strong>Quartiers</strong> : Yaletown (luxe), Kitsilano (hippie/yoga), Commercial Drive (italien). <strong>Tester</strong> sushi (Vancouver = capitale nord-américaine du sushi), salmon, ramen au Marutama, Korean BBQ à Coquitlam. <strong>Vancouver Island</strong> (Victoria) à 1h30 en ferry, Whistler à 2h en voiture. Vol direct depuis Paris en 9h."
}

with open(PATH, encoding='utf-8') as f:
    data_existing = json.load(f)

before = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

data_existing['_version'] = '1.8'
data_existing['_updated'] = '2026-04-27'

for k, v in AVIS_BATCH6_FR.items():
    data_existing[k] = v

after = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data_existing, f, ensure_ascii=False, indent=2)

print(f"Avis FR avant : {before}")
print(f"Avis FR après : {after}")
print(f"Nouveaux : {after - before}")

# Audit immédiat
import re
patterns_check = [
    ('em-dash', r'—'), ('guillemets', r'[«»]'),
    ('attendez-vous', r'attendez-vous à'),
    ('parfait', r'\bparfait[es]*\b'),
    ('fenêtre', r'\bfenêtre[s]?\b'),
    ('saturé', r'\bsatur[eéa]\w*\b'),
    ('se mérite', r'\bse méri[tes]+\b'),
    ('magique', r'\bmagiques?\b'),
    ('Si vous X:', r'Si vous \w+ : '),
    ('iconique', r'\biconique[s]?\b'),
    ('antithèse', r'antithèse'),
    ('mythique', r'\bmythique[s]?\b'),
    ('emblématique', r'\bemblématique[s]?\b'),
    ('authentique', r'\bauthentique[s]?\b'),
    ('féérique', r'\bféérique[s]?\b'),
    ("c'est aussi", r"[Cc]'est aussi"),
    ('à monitorer', r'à monitorer'),
    ('à éviter', r'à éviter'),
]

print("\n=== Audit batch 6 ===")
issues_total = 0
for slug in AVIS_BATCH6_FR.keys():
    plain = re.sub(r'<[^>]+>', '', data_existing[slug])
    issues = []
    for label, p in patterns_check:
        n = len(re.findall(p, plain))
        if n > 0:
            issues.append(f"{label}={n}")
            issues_total += n
    flag = "OK" if not issues else "PB " + ", ".join(issues)
    print(f"  {slug:<22} {len(plain.split()):>3}m {flag}")
print(f"\nTotal issues : {issues_total}")
