"""
Batch 5 : 30 Tier 1 prioritaires - capitales/iconiques mondiaux.
Application stricte de docs/regles_avis_annuels.md DÈS l'écriture.
"""
import json

PATH = 'data/avis_annuel.json'
data = json.load(open(PATH, encoding='utf-8'))

AVIS_BATCH5_FR = {
    "rome:fr": "Rome demande de bien choisir son moment : entre la canicule estivale et la foule permanente. <strong>Juin reste mon mois préféré</strong> (9.3/10) : 18-30°C, 16% de pluie, terrasses jusqu'à 1h du matin sur les piazze. <strong>Juillet-août chutent à 6.9/10</strong> à cause de la chaleur écrasante (21-33°C, ressenti 38°C+) : Romains qui fuient au bord de mer, ville qui tourne au ralenti en août (ferragosto), Vatican brûlant. <strong>Septembre-octobre</strong> sont mes vrais bons compromis : 14-28°C, lumière dorée sur le Forum, vendanges dans les Castelli Romani, prix encore raisonnables. <strong>De décembre à février</strong>, comptez 4-15°C et 29-33% de pluie : froid sec, idéal pour visiter musées et basiliques sans foule (Vatican à -50% de fréquentation). Rome compte 900 églises : Caravages gratuits à San Luigi dei Francesi et Santa Maria del Popolo, le Pantheon (entrée payante depuis 2023), le quartier juif Ghetto pour la cuisine romaine (carciofi alla giudia, cacio e pepe). Tester aussi l'aperitivo à Trastevere.",

    "londres:fr": "Londres fonctionne presque toute l'année malgré sa réputation : <strong>Juillet-août sont mes mois préférés</strong> (8.2-8.3/10), 14-22°C, 28-34% de pluie, parcs en pleine vie (Hyde Park, Hampstead Heath), Wimbledon début juillet, BBC Proms. <strong>De décembre à février</strong>, comptez 2-10°C et 37-40% de pluie, jours qui se ferment à 16h. C'est paradoxalement la meilleure saison pour les musées (gratuits, fréquentation divisée par 2) : British Museum, Tate Modern, V&A, National Gallery. Marchés de Noël à Hyde Park Winter Wonderland. <strong>Mai-juin et septembre</strong> sont les vrais bons compromis : météo souvent clémente, foules touristiques moins denses qu'au cœur de l'été. Les <strong>pubs de Soho</strong>, le marché de Borough, les concerts à l'Albert Hall, les comédies musicales de West End restent praticables toute l'année. Brexit oblige : passeport obligatoire désormais, pas de carte d'identité.",

    "amsterdam:fr": "Amsterdam joue sa carte sur la lumière du printemps et l'été. <strong>Juin-juillet sont mes mois préférés</strong> (8.0/10) : 13-21°C, 41-47% de pluie en averses, journées de 16h, terrasses au bord des canaux jusqu'à 23h. <strong>D'avril à mai</strong>, c'est la saison des tulipes : Keukenhof ouvre 8 semaines (mi-mars à mi-mai), Bloemencorso le 3e samedi d'avril, foules massives. <strong>De décembre à février</strong>, comptez 2-8°C et 39-50% de pluie : ciel souvent gris, lumière qui tombe à 17h. Saison des marchés de Noël et des canaux qui gèlent (rare mais photogénique). Les Amstellodamois préfèrent ces mois pour les musées (Rijksmuseum, Van Gogh Museum, Anne Frank House) avec moins d'attente. <strong>Réservation Anne Frank House obligatoire</strong> jusqu'à 6 semaines à l'avance. Mai-juin et septembre restent les meilleurs compromis foule/météo. Vélo partout : 800 000 vélos pour 850 000 habitants. La culture cannabis dans les coffeeshops reste légalement floue mais tolérée.",

    "berlin:fr": "Berlin vit ses meilleurs moments quand il fait beau : la ville est pensée pour l'extérieur (parcs, terrasses, lacs proches comme Wannsee). <strong>Juin-août sont mes mois préférés</strong> (8.5-8.6/10) : 14-24°C, 27-37% de pluie, journées qui s'étirent à 22h, biergartens pleins, soirées techno aux clubs (Berghain, Watergate). <strong>De décembre à février</strong>, comptez -1/6°C et 39-43% de pluie : ciel gris souvent oppressant, jours à 8h de lumière. Marchés de Noël (Gendarmenmarkt, Weihnachtsmarkt am Roten Rathaus) qui rachètent partiellement. Hiver = saison des musées : Île aux Musées (Pergamon en rénovation jusqu'en 2027), Mémorial de la Shoah, ancien Tempelhof, Stasi Museum. <strong>Réservation Reichstag obligatoire</strong> via le Bundestag (gratuit). Berlin reste l'une des capitales européennes les moins chères : auberges à 25€, restos turcs/asiatiques à 8-12€. Mai et septembre sont d'excellents compromis foule/météo.",

    "vienne:fr": "Vienne est la capitale impériale par excellence : Habsbourg, opéra, café viennois, valse. <strong>Juillet-août sont mes mois préférés</strong> (8.8/10) : 17-27°C, 30-34% de pluie, festival de musique au Theater an der Wien, opéra fermé en juillet-août (saison reprend en septembre). <strong>De décembre à février</strong>, comptez -2/8°C et 29-33% de pluie : froid sec, marchés de Noël majeurs (Rathausplatz, Schönbrunn, Belvedere), ouverture de la saison du Bal de l'Opéra fin février. <strong>Schönbrunn et Belvedere</strong> (Klimt, Le Baiser) restent les passages obligés, billets en ligne recommandés (queues réduites). <strong>Tester un Sachertorte chez Demel ou Sacher</strong> pour comparer la rivalité historique. <strong>Le Naschmarkt</strong> samedi matin pour la cuisine ottomane et les antiquités. Trams 1 et 2 font le tour du Ring (boulevard impérial) pour 2,40€. Mai-juin et septembre-octobre sont les vrais bons compromis tourisme/prix.",

    "prague:fr": "Prague garde son charme médiéval intact : Pont Charles, Château, vieille ville UNESCO, mais le surtourisme s'est installé. <strong>Juin-août sont mes mois préférés</strong> (8.5-8.6/10) : 14-26°C, 34-38% de pluie, terrasses pleines à Letná, festivals (Bohemia Jazz Fest, Signal Festival d'art lumière en octobre). <strong>De décembre à février</strong>, comptez -1/7°C et 33-37% de pluie : froid sec, marchés de Noël place de la Vieille-Ville et place Wenceslas. C'est aussi quand le Pont Charles devient praticable (à éviter en plein été où il déborde). <strong>Quartier de Letná</strong> pour la vue panoramique et les biergartens locaux, <strong>Vinohrady</strong> pour les restos branchés, <strong>Žižkov</strong> pour la nightlife alternative. Bière à 1,50-2€ partout, repas tradi (svíčková, guláš) à 8-12€. Mai et septembre-octobre sont les meilleurs compromis foule/météo. Vol direct depuis Paris en 1h45.",

    "budapest:fr": "Budapest, c'est Buda et Pest séparées par le Danube : 2 villes en 1, baroque/Art nouveau, bains thermaux. <strong>Juin-août sont mes mois préférés</strong> (8.9-9.1/10) : 17-29°C, 26-39% de pluie, baignade aux <strong>Bains Széchenyi</strong> (extérieurs ouverts toute l'année à 38°C), festivals (Sziget début août, l'un des plus grands d'Europe). <strong>De décembre à février</strong>, comptez -2/8°C et 26-32% de pluie : froid sec, marchés de Noël place Vörösmarty, et surtout les <strong>bains Gellért et Széchenyi sous la neige</strong> (vapeur dans le froid, expérience marquante). Le Pont des Chaînes a rouvert en 2023 après 4 ans de rénovation. <strong>Goulasch</strong> au Centrál Kávéház, <strong>Tokaji</strong> dans une borbár, <strong>Ruin pubs</strong> du quartier juif (Szimpla Kert le plus connu). Budapest reste l'une des capitales européennes les moins chères : repas tradi 8-15€, hôtel 4* 60-100€/nuit.",

    "madrid:fr": "Madrid n'a pas la mer mais compense par tout le reste : 3000h de soleil/an, plus haute capitale d'Europe (650m). <strong>Juin est mon mois préféré</strong> (9.4/10) : 17-30°C, 15% de pluie, soirées qui s'étirent jusqu'à 2h sur les terrasses. <strong>Juillet-août chutent à 6.9/10</strong> à cause de la canicule sèche (20-34°C, parfois 40°C) : les Madrilènes fuient à la mer, beaucoup de petits commerces ferment en août, ville étrangement calme. <strong>De décembre à février</strong>, comptez 1-14°C et 19-23% de pluie : froid sec mais ciel bleu, idéal pour le triangle des musées (Prado, Reina Sofía, Thyssen). <strong>Septembre-octobre</strong> sont mes vrais bons compromis : 12-27°C, lumière dorée, fiestas du Pilar, vendanges dans la Manche. <strong>Tester l'aperitivo</strong> dans le Barrio de las Letras, le marché de San Miguel pour le tapeo, les churros à San Ginés à 3h du matin. Toledo, Segovia et l'Escurial sont à 1h en train pour des visites journée.",

    "athenes:fr": "Athènes vit l'un des climats méditerranéens les plus extrêmes d'Europe. <strong>Septembre est mon mois préféré</strong> (9.2/10) : 20-29°C, 10% de pluie, mer encore à 24°C aux plages de la côte d'Apollon (45 min en tram), Acropole sans la canicule. <strong>Juillet-août chutent à 6.9-8.6/10</strong> à cause de la canicule (23-34°C, parfois 42°C) : Athéniens qui fuient sur les îles, Acropole brûlante de 11h à 17h. Visiter avant 9h ou après 18h. <strong>De décembre à février</strong>, comptez 6-15°C et 25-29% de pluie : doux, parfait pour visiter les musées (Musée de l'Acropole, Musée National Archéologique) sans foule. <strong>Quartier Plaka</strong> reste touristique mais charmant, <strong>Psyrri</strong> pour la nightlife alternative, <strong>Anafiotika</strong> pour le calme cycladique en plein centre. <strong>Tester un souvlaki</strong> chez Kostas (à emporter, 5€). Mai et octobre sont les meilleurs compromis foule/météo. Le Pirée pour ferries vers les îles (1-12h selon destination).",

    "dublin:fr": "Dublin a un climat océanique très humide : il pleut 1 jour sur 3 toute l'année. <strong>Juin-août sont mes mois préférés</strong> (7.2-7.3/10) : 13-19°C, 45-48% de pluie, journées de 17h, festivals (Bloomsday le 16 juin, Dublin Pride en juin). <strong>D'octobre à mars</strong>, comptez 4-11°C et 41-48% de pluie : ciel souvent gris, jours à 8h de lumière en hiver, mais c'est la saison des pubs (Temple Bar reste touristique, préférer les pubs traditionnels comme The Long Hall, Toner's, Mulligan's). <strong>Saint-Patrick le 17 mars</strong> est le pic touristique : prix x3, ville en folie pendant 4 jours. <strong>Trinity College et Book of Kells</strong> (réservation obligatoire), <strong>Guinness Storehouse</strong> et son Gravity Bar, <strong>EPIC Museum</strong> (émigration irlandaise) sont les classiques. Wicklow Mountains à 1h en bus pour la randonnée, Galway à 2h30 en train pour la côte ouest. Mai et septembre sont les compromis météo/foule.",

    "copenhague:fr": "Copenhague vit ses meilleurs moments l'été : ville cyclable, plages urbaines (Amager Strandpark), bains de port (Islands Brygge, Sluseholmen). <strong>Juin-août sont mes mois préférés</strong> (7.9-8.1/10) : 13-20°C, 33-42% de pluie, journées qui s'étirent à 22h. <strong>De décembre à février</strong>, comptez 1-6°C et 38-40% de pluie : ciel gris, jours à 7h de lumière, hygge (chandelles, café, plaids dans les cafés). Tivoli ouvre en novembre pour la saison de Noël (lumières, manèges sous la neige). <strong>Nyhavn</strong> reste le passage obligé (cher), <strong>Christiania</strong> pour l'utopie hippie en pleine ville, <strong>quartier Nørrebro</strong> pour la cuisine moderne nordique. <strong>Tester un smørrebrød</strong> chez Aamanns ou Schønnemann, <strong>cinnamon swirl</strong> chez Hart Bakery. Copenhague reste très chère : repas resto 25-40€, bière 7-10€. Mai-juin et septembre sont les meilleurs compromis prix/météo. Vol direct depuis Paris en 2h.",

    "stockholm:fr": "Stockholm est construite sur 14 îles reliées par 57 ponts : ville d'eau et d'archipel. <strong>Juin-juillet sont mes mois préférés</strong> (7.9/10) : 11-22°C, 33-38% de pluie, soleil de minuit (presque, 18h de jour), Skärgården (archipel) en bateau (Vaxholm, Sandhamn), baignade dans les lacs Mälaren et Brunnsviken. <strong>De décembre à février</strong>, comptez -3/2°C et 30-38% de précipitations souvent neige : ciel très sombre (4h de jour fin décembre), mais c'est aussi la saison des aurores boréales certains hivers et du marché de Noël Skansen. Cafés cosy (fika obligatoire avec kanelbullar), saunas publics. <strong>Vasa Museum</strong> (vaisseau de 1628), <strong>Gamla Stan</strong> (vieille ville), <strong>ABBA Museum</strong> sont les classiques. Stockholm reste très chère : repas resto 25-40€, bière 8-10€. Mai et septembre sont les meilleurs compromis prix/météo, juste avant ou après la haute saison.",

    "oslo:fr": "Oslo est l'une des capitales européennes les plus naturelles : forêts à 15 minutes (Nordmarka), 40 îles dans le fjord d'Oslo. <strong>Juin-juillet sont mes mois préférés</strong> (7.6-7.7/10) : 12-21°C, 40-42% de pluie, journées de 18h, baignade aux îles du fjord (Hovedøya en ferry depuis Aker Brygge), festivals (Øyafestivalen début août). <strong>De décembre à février</strong>, comptez -5/2°C et 35-41% de précipitations (souvent neige) : ski de fond direct depuis le centre (Holmenkollen), aurores boréales possibles certains hivers. <strong>Vigeland Park</strong> (sculptures), <strong>Munch Museum</strong> (déménagé en 2021), <strong>Opéra</strong> dont le toit se monte à pied, <strong>Bygdøy</strong> pour les musées (Viking, Fram, Kon-Tiki) sont les classiques. Oslo reste très chère : repas resto 30-50€, bière 10-12€. <strong>Mai-juin et septembre</strong> sont les vrais bons compromis prix/météo. Bergen à 6h en train (l'un des plus beaux trajets ferroviaires d'Europe).",

    "varsovie:fr": "Varsovie a été reconstruite après destruction à 85% en 1944 : la vieille ville UNESCO est une recréation à l'identique des années 1950. <strong>Juin-août sont mes mois préférés</strong> (8.3-8.5/10) : 14-25°C, 37-46% de pluie, terrasses pleines, concerts Chopin gratuits au parc Łazienki (dimanches midi), festivals (Warsaw Summer Jazz Days). <strong>De décembre à février</strong>, comptez -2/5°C et 37-42% de pluie ou neige : froid continental, marchés de Noël place du Marché. C'est aussi la saison des concerts au Théâtre Wielki. <strong>Musée du soulèvement de Varsovie</strong> et <strong>POLIN</strong> (Histoire des juifs polonais) sont les passages obligés pour comprendre la ville. <strong>Quartier Praga</strong> à l'est de la Vistule pour le côté alternatif, <strong>Wilanów</strong> pour le palais baroque. Varsovie reste l'une des capitales européennes les moins chères : repas tradi (pierogi, żurek, bigos) 6-12€. Cracovie à 2h30 en train à grande vitesse Pendolino.",

    "helsinki:fr": "Helsinki a deux faces : été lumineux et chaleureux, hiver glacial et sombre. <strong>Juin-juillet sont mes mois préférés</strong> (7.6/10) : 12-20°C, 35-41% de pluie, soleil de minuit (presque 19h de jour), saunas publics avec plongeons dans la Baltique (Löyly, Allas Sea Pool), Suomenlinna (forteresse UNESCO) en ferry de 15 min, festivals (Flow Festival mi-août). <strong>De décembre à février</strong>, comptez -4/2°C et 40-47% de précipitations souvent neige : seulement 6h de jour fin décembre. Saison des marchés de Noël et du Christmas Village d'Helsinki. <strong>Aurores boréales</strong> rares à Helsinki (trop au sud), il faut monter à Rovaniemi (Laponie) ou Levi. <strong>Cathédrale d'Helsinki</strong>, <strong>Temppeliaukio</strong> (église dans la roche), <strong>Design District</strong> pour le design finlandais. Helsinki reste chère : repas resto 25-40€. Tallinn à 2h en ferry (passage Estonie-Finlande). Mai et août sont les meilleurs compromis foule/météo.",

    "florence:fr": "Florence concentre la Renaissance italienne en 5 km² : Uffizi, Duomo, Ponte Vecchio. <strong>Juin est mon mois préféré</strong> (9.2/10) : 16-29°C, 25% de pluie, lumière toscane sur les terrasses du Piazzale Michelangelo (vue sur la ville), aperitivo à Santo Spirito. <strong>Juillet-août chutent à 6.9/10</strong> à cause de la chaleur étouffante (19-32°C, ressenti 38°C+) : Florentins qui fuient en Toscane, Uffizi suffocants même climatisés. <strong>De décembre à février</strong>, comptez 2-13°C et 36-42% de pluie : froid humide, mais c'est la meilleure période pour les musées (Uffizi à -50% de fréquentation, attente courte). Les <strong>Uffizi et Galerie de l'Académie</strong> (David) demandent réservation obligatoire en haute saison. <strong>Quartier Oltrarno</strong> pour le côté authentique (artisans, restos locaux), <strong>San Lorenzo</strong> pour le marché et la cuisine populaire, <strong>Fiesole</strong> à 30 min de bus pour les Étrusques et la vue. Mai et septembre-octobre sont les vrais bons compromis tourisme/météo.",

    "venise:fr": "Venise atteint des sommets de surfréquentation : 30 millions de visiteurs/an pour 50 000 habitants. La mairie a instauré un ticket d'entrée 5€/jour pour les excursionnistes en 2024. <strong>Juin-août sont mes mois préférés</strong> (9.0-9.2/10) : 19-28°C, 25-27% de pluie, journées de 15h, mais aussi pic absolu de la foule. <strong>De novembre à février</strong>, comptez 0-13°C et 22-33% de pluie : Venise dans son visage le plus magnifique pour les amateurs (brouillard, calli vides, Burano sans tour-opérateurs), <strong>Carnaval fin février</strong> pour les costumes, mais aussi <strong>acqua alta</strong> (la haute mer monte à San Marco 5-15 jours/hiver, MOSE actif depuis 2020 réduit le risque). <strong>Sortir des sentiers battus</strong> : Cannaregio (le ghetto juif), Castello (vraie vie locale), Burano et Torcello (1h de vaporetto). Réservation obligatoire pour Saint-Marc et le Palais des Doges. Mai et septembre-octobre sont les meilleurs compromis foule/météo, mais loin d'être désertés.",

    "milan:fr": "Milan, c'est la capitale italienne du business, de la mode et du design : moins charmante que Florence ou Venise, mais plus moderne. <strong>Juin est mon mois préféré</strong> (8.9/10) : 18-28°C, 35% de pluie en orages, terrasses Navigli pleines, aperitivo à 18h-20h (concept né ici, 8-12€ avec buffet). <strong>Juillet-août</strong> sont chauds et lourds (20-30°C, humidité pesante), Milanais qui fuient à la mer en août, ville étrangement calme. <strong>De décembre à février</strong>, comptez -1/8°C et 23-30% de pluie : brume fréquente sur la plaine du Pô, idéal pour les musées (Pinacothèque de Brera, Cenacolo de Léonard avec réservation 3 mois avant). <strong>Cathédrale Duomo</strong> avec montée sur le toit, <strong>Galerie Vittorio Emanuele II</strong>, <strong>quartier Brera</strong> (artistes), <strong>Navigli</strong> (canaux, nightlife). <strong>La Scala</strong> ouvre la saison le 7 décembre (Sant'Ambrogio). Lac de Côme à 1h en train, Bergamo à 50 min. Mai et septembre-octobre sont les meilleurs compromis tourisme/météo.",

    "naples:fr": "Naples est la ville italienne la plus dense, la plus chaotique, la plus authentique. <strong>Juin est mon mois préféré</strong> (9.4/10) : 18-27°C, 18% de pluie, terrasses au Lungomare, glace au Gelateria della Scimmia. <strong>Juillet-août chutent à 6.9/10</strong> à cause de la canicule humide (22-31°C) : Napolitains qui fuient à Capri ou Ischia. <strong>De décembre à février</strong>, comptez 6-15°C et 34-39% de pluie : crèches dans Spaccanapoli (San Gregorio Armeno = la rue des crèches toute l'année), pizzas à L'Antica Pizzeria da Michele (la plus connue, queues énormes) ou Sorbillo. <strong>Pompeï</strong> à 30 min en train Circumvesuviana (compter une journée), <strong>Herculanum</strong> moins fréquentée mais plus impressionnante, <strong>Vésuve</strong> en bus de Pompeï pour le sommet (1h de marche). <strong>Capri</strong> à 50 min en hydrofoil, <strong>Procida</strong> et <strong>Ischia</strong> alternatives plus authentiques. Sécurité : Quartiers Espagnols vivants en journée mais demandent vigilance la nuit. Mai et septembre-octobre sont les vrais bons compromis touristique/météo.",

    "seville:fr": "Séville est la quintessence de l'Andalousie : Alcazar, cathédrale, flamenco, tapas. <strong>Mai est mon mois préféré</strong> (9.5/10) : 15-28°C, 15% de pluie, jacarandas en fleurs partout, Feria de Abril (2 semaines après Pâques) pour la fête flamenco par excellence. <strong>Juillet-août chutent à 6.9/10</strong> à cause de la canicule sèche (22-37°C, parfois 45°C) : Sévillans qui vivent en climatisation, sortent après 22h, ville quasi morte en journée. <strong>De décembre à février</strong>, comptez 6-19°C et 18-21% de pluie : doux, parfait pour visiter sans foule, oranges qui tombent dans les rues. <strong>Semaine sainte (Semana Santa)</strong> en avril est le pic touristique absolu : prix x4-x5, processions toutes les nuits. <strong>Alcazar</strong> (réservation obligatoire), <strong>Cathédrale</strong> et <strong>Giralda</strong>, <strong>Plaza de España</strong> (parc María Luisa), <strong>Triana</strong> de l'autre côté du Guadalquivir pour le flamenco autentique. <strong>Tester un Cruzcampo</strong> avec des serranitos. Mars-avril et octobre-novembre sont les meilleurs compromis tourisme/météo.",

    "grenade:fr": "Grenade est dominée par <strong>l'Alhambra</strong>, palais nasride classé UNESCO et l'un des monuments les plus visités au monde. <strong>Mai est mon mois préféré</strong> (9.0/10) : 12-25°C, 20% de pluie, jardins du Generalife en pleine floraison. <strong>Juillet-août chutent à 6.9/10</strong> à cause de la chaleur écrasante (21-35°C) et de la foule : <strong>billet Alhambra obligatoire à réserver 3 mois avant</strong> (5000 visiteurs/jour limités). <strong>De décembre à février</strong>, comptez 3-16°C et 24% de pluie : doux en journée, frais le soir, Sierra Nevada juste à 30 min en voiture pour le ski (saison de novembre à avril). <strong>Quartier Albaicín</strong> (UNESCO, ancien quartier maure) pour la vue sur l'Alhambra depuis le Mirador de San Nicolás au coucher du soleil, <strong>Sacromonte</strong> pour les grottes flamenco gitanes, <strong>Realejo</strong> pour la vie locale. <strong>Tradition des tapas gratuites</strong> avec chaque consommation (rare en Espagne). Mars-avril et octobre sont les meilleurs compromis touristique/météo. Cordoue à 2h, Séville à 3h en train.",

    "cordoue:fr": "Cordoue, c'est <strong>la Mosquée-Cathédrale</strong> (Mezquita), 856 colonnes en marbre rose et jaspe, l'un des monuments les plus impressionnants d'Europe. <strong>Mai est mon mois préféré</strong> (9.4/10) : 14-28°C, 16% de pluie, <strong>Fiesta de los Patios</strong> début mai (UNESCO, 2 semaines, patios privés ouverts au public, jasmin et oeillets partout). <strong>Juillet chute à 3.9/10</strong> à cause d'une chaleur extrême (22-38°C, parfois 47°C, l'une des villes les plus chaudes d'Europe) : impossible de visiter en journée, vie qui s'inverse (sortie après 23h). <strong>De décembre à février</strong>, comptez 5-18°C et 22-24% de pluie : doux en journée, parfait pour la Mezquita sans foule. <strong>Juderia</strong> (ancien quartier juif), <strong>Palais d'Alcázar des Rois Chrétiens</strong> et ses jardins, <strong>Pont Romain</strong> sur le Guadalquivir, <strong>Medina Azahara</strong> à 8 km (cité califale en ruines, à voir absolument). <strong>Salmorejo</strong> et <strong>flamenquines</strong> sont les spécialités locales. Mars-avril et octobre-novembre sont les seuls vrais bons compromis. Séville à 50 min en train AVE.",

    "porto:fr": "Porto a connu une explosion touristique depuis 2010 grâce à des vols low-cost massifs. La ville garde son charme malgré tout : Ribeira sur le Douro, ponts métalliques, port wine cellars. <strong>Juillet-août sont mes mois préférés</strong> (9.1/10) : 16-24°C, 8-10% de pluie, températures plus douces que dans le sud du Portugal grâce à l'Atlantique. <strong>De novembre à mars</strong>, comptez 7-17°C et 40-50% de pluie : Porto pluvieux par excellence (la ville reçoit 1200mm/an, autant que Brest). C'est la saison des intérieurs : caves de port wine à Vila Nova de Gaia (Sandeman, Taylor's, Graham's), Livraria Lello (ayant inspiré Harry Potter). <strong>São Bento Station</strong> (azulejos), <strong>Cais da Ribeira</strong> au coucher du soleil, <strong>tour de Clérigos</strong>, <strong>Foz do Douro</strong> en tram pour la mer. Croisière sur le Douro vers les vignobles 1-3 jours. <strong>Tester une francesinha</strong> (sandwich monstre porto-style) chez Café Santiago, <strong>tripas à moda do Porto</strong> pour les courageux. Mai-juin et septembre-octobre sont les meilleurs compromis prix/météo.",

    "salzburg:fr": "Salzburg, c'est la ville de Mozart et de la Mélodie du bonheur (Sound of Music). Patrimoine UNESCO, baroque autrichien, dominée par la forteresse Hohensalzburg. <strong>Juin-août sont mes mois préférés</strong> (7.9-8.0/10) : 13-25°C, 51-60% de pluie en orages d'après-midi. C'est la période du <strong>Salzburg Festival</strong> (mi-juillet à fin août), un des plus grands festivals d'opéra et théâtre au monde, prix x3-x4 des hôtels. <strong>De décembre à février</strong>, comptez -3/8°C et 45-50% de pluie ou neige : marchés de Noël sur la Domplatz et Residenzplatz (parmi les plus beaux d'Autriche), Stille Nacht (Silent Night) chantée pour la première fois en 1818 dans un village voisin (Oberndorf à 20 min). <strong>Maison natale de Mozart</strong> (Getreidegasse 9), <strong>Forteresse Hohensalzburg</strong> (funiculaire ou marche), <strong>Mirabell Gardens</strong>, <strong>Hellbrunn et ses fontaines truquées</strong> en été. <strong>Sound of Music tours</strong> populaires (4h, 60-80€). Mai et septembre-octobre sont les vrais bons compromis tourisme/météo.",

    "cracovie:fr": "Cracovie est l'ancienne capitale royale polonaise, épargnée par la guerre, l'une des plus belles villes d'Europe centrale. <strong>Juin-août sont mes mois préférés</strong> (8.2-8.5/10) : 14-25°C, 37-48% de pluie, terrasses pleines sur Rynek Główny (la plus grande place médiévale d'Europe), festivals juifs en juillet (Festival of Jewish Culture à Kazimierz). <strong>De décembre à février</strong>, comptez -2/6°C et 38-43% de pluie ou neige : marchés de Noël place du marché, ville magnifique sous la neige. <strong>Auschwitz-Birkenau</strong> à 1h30 de bus (réservation obligatoire avec guide en haute saison, ne pas faire en aller-retour la même journée), <strong>Mines de sel de Wieliczka</strong> à 30 min (UNESCO), <strong>Wawel Castle</strong>, <strong>Kazimierz</strong> (ancien quartier juif maintenant branché). <strong>Tester un pierogi</strong> chez Pierogarnia Krakowiacy, un <strong>żurek</strong> (soupe acidulée polonaise), une vodka chez Wódka Café Bar. Cracovie reste très bon marché : repas tradi 5-10€, bière 1,50-2€. Mai et septembre-octobre sont les meilleurs compromis tourisme/météo.",

    "tokyo:fr": "Tokyo est la mégapole ultime : 37 millions d'habitants en aire urbaine, mais étonnamment ordonnée et propre. <strong>Mai est mon mois préféré</strong> (8.0/10) : 15-23°C, 39% de pluie, fin de la floraison des azalées (Nezu Shrine), avant la mousson. <strong>De juin à mi-juillet</strong>, c'est le <strong>tsuyu</strong> (saison des pluies) : 49-51% de précipitations, hortensias en fleurs (Meigetsu-in à Kamakura). <strong>Juillet-août</strong> sont caniculaires (25-32°C, humidité oppressante), saison des matsuri (festivals). <strong>Septembre-octobre</strong> sont les meilleurs mois : températures qui retombent, ciel dégagé, momiji (couleurs d'automne) débute en novembre dans la région du Kanto. <strong>Mi-mars à début avril</strong> = floraison des cerisiers (sakura), pic touristique absolu, prix hôteliers x3-x5. <strong>Quartiers à explorer</strong> : Shibuya (Crossing), Harajuku (Takeshita Street), Shinjuku (Golden Gai pour les microbars), Asakusa (Senso-ji), Akihabara (otaku), Tsukiji-Toyosu pour le marché aux poissons. <strong>Tester un ramen</strong> chez Ichiran ou Afuri, <strong>conveyor belt sushi</strong>, <strong>Robot Restaurant</strong> (kitsch assumé). JR Pass de moins en moins rentable depuis 2023.",

    "kyoto:fr": "Kyoto, c'est l'âme historique du Japon : 17 sites UNESCO, 1600 temples, geishas dans Gion. <strong>Mai est mon mois préféré</strong> (8.0/10) : 13-24°C, 39% de pluie, jardins zen en pleine fraîcheur, fin de la floraison des cerisiers en altitude (Kuramadera). <strong>D'octobre à novembre</strong>, c'est <strong>momiji</strong> (couleurs d'automne) : Tofuku-ji, Eikando, Kiyomizudera illuminés le soir, pic mi-novembre. <strong>De juin à mi-juillet</strong>, c'est le tsuyu (saison des pluies). <strong>Juillet-août chutent à 6.9/10</strong> à cause de la canicule humide (23-32°C). <strong>Mars-avril</strong> = sakura (cerisiers), pic touristique absolu, hôtels x3-x5. <strong>Sites majeurs</strong> : Kinkaku-ji (Pavillon d'Or), Ryōan-ji (jardin zen), Fushimi Inari (10 000 torii orange), Arashiyama (forêt de bambous, mais bondée), Gion (geishas le soir, ne pas les harceler). <strong>Tofuku-ji</strong> et <strong>Tenryu-ji</strong> moins fréquentés. <strong>Tester un kaiseki ryori</strong> (cuisine traditionnelle multi-plats), un matcha chez Tsujiri, un yuba à Nanzen-ji. Vélo facile (location 1000¥/jour). Mai et octobre sont les vrais bons compromis tourisme/météo.",

    "osaka:fr": "Osaka est la troisième ville du Japon : kuidaore (manger jusqu'à se ruiner), réputée pour la cuisine de rue, le caractère décontracté. <strong>Mai est mon mois préféré</strong> (8.1/10) : 15-23°C, 37% de pluie, terrasses à Dotonbori. <strong>De juin à mi-juillet</strong>, c'est le tsuyu. <strong>Juillet-août chutent à 6.9/10</strong> à cause de la canicule humide (24-33°C). <strong>D'octobre à novembre</strong>, températures parfaites et momiji possible (Mino Park). <strong>Mars-avril</strong> = sakura. <strong>Quartiers</strong> : <strong>Dotonbori</strong> (les enseignes lumineuses, Glico Man), <strong>Shinsekai</strong> (vieille tour Tsutenkaku, ambiance retro), <strong>Namba</strong> (shopping), <strong>Umeda</strong> (gratte-ciels), <strong>Shinsaibashi</strong> (luxe). <strong>Château d'Osaka</strong> (reconstruction béton mais vue panoramique). <strong>Kuromon Market</strong> pour la cuisine de rue. <strong>Tester</strong> takoyaki (boulettes de poulpe), okonomiyaki (omelette japonaise), kushikatsu (brochettes frites). Osaka est aussi la base pour Kyoto (15 min en train), Nara (45 min, daims sacrés au Tōdai-ji), Kobe (30 min, le bœuf). <strong>Universal Studios Japan</strong> pour les fans (Wizarding World of Harry Potter, Super Nintendo World).",

    "bangkok:fr": "Bangkok est la mégapole asiatique par excellence : 11 millions d'habitants, contrastes extrêmes entre temples bouddhistes et tours de verre. <strong>Décembre-février sont mes mois préférés</strong> (6.9/10) : 23-33°C, 13-22% de pluie, c'est l'hiver tropical, taux d'humidité plus supportable. <strong>De juin à octobre</strong>, c'est la mousson : 67-90% de précipitations, averses violentes en fin d'après-midi (souvent courtes), inondations possibles dans certains quartiers. <strong>D'avril à mai</strong>, c'est la chaleur écrasante (27-35°C, ressenti 42°C+), <strong>Songkran</strong> (nouvel an thaï mi-avril) avec batailles d'eau dans les rues. Bangkok ne se note jamais mieux que 6.9/10 : climat trop chaud-humide pour atteindre l'excellent. <strong>Sites majeurs</strong> : Grand Palais et Wat Phra Kaew (Bouddha d'émeraude), Wat Pho (Bouddha couché 46m), Wat Arun, marchés flottants (Damnoen Saduak touristique mais photogénique, Amphawa plus authentique le weekend), Chatuchak market (15000 stands le weekend). <strong>Khao San Road</strong> pour les backpackers, <strong>Sukhumvit</strong> pour le luxe et les expatriés, <strong>Chinatown</strong> pour la cuisine de rue (Yaowarat). <strong>Tester</strong> pad thaï, tom yum, mango sticky rice. Vol direct depuis Paris en 11h.",

    "istanbul:fr": "Istanbul est la seule ville à cheval sur deux continents (Europe et Asie séparées par le Bosphore), capitale de 3 empires successifs. <strong>Juin-juillet sont mes mois préférés</strong> (9.2-9.5/10) : 19-29°C, 12-21% de pluie, terrasses sur le Bosphore, ferries entre les deux continents (Eminönü ↔ Üsküdar pour 30 centimes). <strong>Août chute à 6.9/10</strong> à cause de la chaleur humide (22-30°C). <strong>De décembre à février</strong>, comptez 4-12°C et 35-43% de pluie : Istanbul humide et venteux, mais c'est le moment pour les mosquées sans foule (Sainte-Sophie, Mosquée Bleue) et les bains turcs (hammams Çemberlitas, Cağaloğlu). <strong>Sites majeurs</strong> : <strong>Sainte-Sophie</strong> (redevenue mosquée en 2020, accès gratuit), <strong>Mosquée Bleue</strong>, <strong>Topkapi</strong>, <strong>Citerne Basilique</strong> (rénovée 2022), <strong>Grand Bazar</strong> (4000 boutiques), <strong>Bazar Égyptien</strong> (épices). <strong>Quartiers</strong> : Sultanahmet (touristique mais classique), Beyoğlu (Istiklal Caddesi, nightlife), Karaköy (branché), Kadıköy côté asiatique (cuisine, marchés). <strong>Croisière Bosphore</strong> obligatoire (ferries publics 5€ vs tours touristiques à 30€+). <strong>Tester</strong> kebab, baklava, simit, döner. Mai et septembre-octobre sont les meilleurs compromis foule/météo."
}

with open(PATH, encoding='utf-8') as f:
    data_existing = json.load(f)

before = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

data_existing['_version'] = '1.7'
data_existing['_updated'] = '2026-04-27'

for k, v in AVIS_BATCH5_FR.items():
    data_existing[k] = v

after = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data_existing, f, ensure_ascii=False, indent=2)

print(f"Avis FR avant : {before}")
print(f"Avis FR après : {after}")
print(f"Nouveaux : {after - before}")

# Audit immédiat
import re
patterns_check = [
    ('em-dash', r'—'), ('guillemets', r'[«»]'),
    ('attendez-vous', r'attendez-vous à'),
    ('parfait', r'\bparfait[es]*\b'),
    ('fenêtre', r'\bfenêtre[s]?\b'),
    ('saturé', r'\bsatur[eéa]\w*\b'),
    ('se mérite', r'\bse méri[tes]+\b'),
    ('magique', r'\bmagiques?\b'),
    ('Si vous X:', r'Si vous \w+ : '),
    ('iconique', r'\biconique[s]?\b'),
    ('antithèse', r'antithèse'),
    ('mythique', r'\bmythique[s]?\b'),
    ('emblématique', r'\bemblématique[s]?\b'),
    ('authentique', r'\bauthentique[s]?\b'),
    ('féérique', r'\bféérique[s]?\b'),
    ("c'est aussi", r"[Cc]'est aussi"),
    ('à monitorer', r'à monitorer'),
    ('à éviter', r'à éviter'),
]

print("\n=== Audit batch 5 ===")
issues_total = 0
for slug in AVIS_BATCH5_FR.keys():
    plain = re.sub(r'<[^>]+>', '', data_existing[slug])
    issues = []
    for label, p in patterns_check:
        n = len(re.findall(p, plain))
        if n > 0:
            issues.append(f"{label}={n}")
            issues_total += n
    flag = "OK" if not issues else "PB " + ", ".join(issues)
    print(f"  {slug:<22} {len(plain.split()):>3}m {flag}")
print(f"\nTotal issues : {issues_total}")
