"""Batch 9 : 28 avis FR Tier 1 Océanie + Pacifique."""
import json

PATH = 'data/avis_annuel.json'
data = json.load(open(PATH, encoding='utf-8'))

AVIS_BATCH9_FR = {
    "sydney:fr": "Sydney, plus grande ville d'Australie : 5,3 millions d'habitants, baie iconique avec l'Opéra (Jørn Utzon, 1973) et le Harbour Bridge. <strong>Décembre est mon mois préféré</strong> (8.6/10) : 18-25°C, 34% de pluie, été austral, journées de 14h, plages bondées (Bondi, Coogee, Manly). <strong>De juin à août</strong> (hiver austral), comptez 7-18°C : doux mais pluie fréquente, baignade fraîche (mer à 17°C). C'est aussi quand les baleines à bosse migrent au large (juin-octobre, observation depuis Cape Solander ou North Head). <strong>Septembre-novembre</strong> sont mes vrais bons compromis : 10-23°C, jacarandas en fleurs en novembre (Kirribilli notamment), New Year's Eve à Sydney = feu d'artifice mythique sur le Harbour Bridge. <strong>Sites majeurs</strong> : <strong>Opéra de Sydney</strong> (visite intérieure ou opéra/concert), <strong>Bridge Climb</strong> (escalade du Harbour Bridge), <strong>Royal Botanic Garden</strong>, <strong>The Rocks</strong> (quartier historique), <strong>Bondi to Coogee Coastal Walk</strong> (6 km en bord de falaise). <strong>Manly</strong> en ferry depuis Circular Quay (30 min, l'un des plus beaux trajets ferries au monde). <strong>Blue Mountains</strong> à 2h (Three Sisters, randonnée). <strong>Tester</strong> meat pies, vegemite, flat white (origine ici), barramundi, kangaroo steak. Sydney New Year's Eve attire 1 million de spectateurs.",

    "melbourne:fr": "Melbourne, capitale culturelle de l'Australie : 5 millions d'habitants, ville sportive (Australian Open en janvier), café-culture mondiale, ruelles couvertes de street art. <strong>Février est mon mois préféré</strong> (8.9/10) : 15-25°C, 21% de pluie, été austral. <strong>De juin à août</strong> (hiver austral), comptez 7-14°C avec 37-42% de pluie : froid pour l'Australie, jours courts (9h de soleil), mais c'est aussi la saison de ski au <strong>Mount Buller</strong> à 3h. <strong>Décembre-mars</strong> sont la haute saison touristique. <strong>Melbourne a la réputation des \"4 saisons en une journée\"</strong> : prévoir veste même en plein été. <strong>Sites majeurs</strong> : <strong>Federation Square</strong>, <strong>Hosier Lane</strong> (street art le plus connu), <strong>Queen Victoria Market</strong> (depuis 1878), <strong>Melbourne Cricket Ground</strong> (MCG, 100 000 places), <strong>St Kilda</strong> (plage urbaine, manchots à Pier au crépuscule). <strong>Quartiers branchés</strong> : Fitzroy (Brunswick St), Brunswick (Sydney Rd), Carlton (Lygon St quartier italien). <strong>Great Ocean Road</strong> à 1h30 (12 Apostles, route panoramique 250 km), <strong>Yarra Valley</strong> à 1h (vins, Domaine Chandon), <strong>Mornington Peninsula</strong> à 1h30 (sources thermales, vins). <strong>Tester</strong> flat white dans les laneway cafes (Brother Baba Budan, Patricia, Seven Seeds), Vietnamese pho à Richmond (Victoria St). Melbourne et Sydney = rivalité historique amicale.",

    "cairns:fr": "Cairns, dans le tropical north Queensland, est la base d'accès à la <strong>Grande Barrière de Corail</strong> (UNESCO, plus grand récif corallien au monde, 2300 km, visible depuis l'espace). <strong>Août-octobre sont mes mois préférés</strong> (8.7/10) : 18-29°C, 23-31% de pluie, saison sèche tropicale. <strong>De novembre à avril</strong>, c'est la saison humide : 40-75% de précipitations, cyclones possibles (catégorie 5 historiques), méduses irukandji (très dangereuses, baignade interdite ou en combinaison stinger). <strong>De mai à octobre</strong>, c'est la saison touristique idéale : ciel clair, mer calme, visibilité maximale pour la plongée. <strong>Sites majeurs</strong> : <strong>Grande Barrière</strong> (sortie bateau journée 150-250$, plongée ou snorkeling à Hastings Reef, Michaelmas Cay, Agincourt Reef), <strong>Daintree Rainforest</strong> (UNESCO, plus vieille forêt tropicale au monde 180 millions d'années), <strong>Cape Tribulation</strong> (où la forêt rencontre le récif), <strong>Kuranda</strong> en Skyrail (téléphérique 7,5 km au-dessus de la canopée), <strong>Atherton Tablelands</strong> (plateaux, cascades, lacs de cratère). <strong>Cairns Esplanade Lagoon</strong> (piscine artificielle gratuite en bord de mer, baignade sécurisée toute l'année). Cairns ne dispose pas de plages baignables en ville (mer à 30 min). <strong>Tester</strong> barramundi, mud crab, kangaroo. Vol direct depuis Singapour, escale Sydney.",

    "adelaide:fr": "Adelaide, capitale de l'Australie-Méridionale : 1,3 million d'habitants, ville plus calme que Sydney/Melbourne, design urbain britannique avec ceinture verte (Adelaide Park Lands), capitale des vins australiens. <strong>Janvier est mon mois préféré</strong> (9.6/10) : 16-28°C, 14% de pluie, été austral idéal. <strong>De juin à août</strong> (hiver austral), comptez 8-14°C et 43-44% de pluie : froid et humide pour l'Australie. <strong>Décembre-mars</strong> sont la haute saison festivalière : <strong>Adelaide Festival of Arts</strong> et <strong>Fringe Festival</strong> (le 2e plus grand festival d'arts au monde après Edinburgh) en février-mars. <strong>Sites majeurs</strong> : <strong>Adelaide Central Market</strong> (depuis 1869), <strong>Art Gallery of South Australia</strong>, <strong>Adelaide Botanic Garden</strong>, <strong>North Terrace</strong> (musées). <strong>Plages</strong> : Glenelg (en tram depuis le centre), Henley Beach. <strong>Excursions vins</strong> : <strong>Barossa Valley</strong> à 1h (Shiraz, Penfolds Grange), <strong>McLaren Vale</strong> à 45 min (Shiraz, Cabernet), <strong>Adelaide Hills</strong> (Pinot Noir, Chardonnay), <strong>Clare Valley</strong> à 2h (Riesling). <strong>Kangaroo Island</strong> à 2h en ferry (faune endémique, Remarkable Rocks, Seal Bay). <strong>Coober Pedy</strong> à 8h (ville opale souterraine). <strong>Tester</strong> pie floater (tourte sur soupe de pois cassés, plat local), German pastries (Hahndorf village allemand). Adelaide est moins fréquentée par les Européens que Sydney/Melbourne, plus authentique.",

    "darwin:fr": "Darwin, capitale du Top End : porte d'accès au <strong>Kakadu National Park</strong> (UNESCO) et au <strong>Litchfield National Park</strong>, climat tropical extrême. <strong>Juillet est mon mois préféré</strong> (9.2/10) : 21-30°C, 3% de pluie, c'est la saison sèche (Dry Season), idéale pour visiter. <strong>De mai à octobre</strong>, c'est la Dry Season : ciel constant, températures supportables (22-32°C), tous les sites accessibles. <strong>De décembre à mars</strong>, c'est la Wet Season (mousson tropicale) : 71-86% de précipitations, orages quotidiens, températures lourdes (26-32°C, ressenti 40°C+ avec humidité), risque cyclonique réel. Beaucoup de pistes du Kakadu fermées en wet (Jim Jim Falls, Twin Falls inaccessibles). <strong>Avril et novembre</strong> = build-up/build-down, transitions humides oppressantes. <strong>Sites majeurs</strong> : <strong>Kakadu National Park</strong> (à 3h, art rupestre aborigène à Ubirr et Nourlangie, crocodiles à Yellow Water Cruise), <strong>Litchfield National Park</strong> (à 1h30, baignade dans les piscines naturelles : Florence Falls, Buley Rockhole, Wangi Falls), <strong>Mindil Beach Sunset Market</strong> (jeudi-dimanche en saison sèche), <strong>Crocosaurus Cove</strong> (\"Cage of Death\" pour nager avec un crocodile). <strong>Cuisine asiatique</strong> très présente (proximité Indonésie). Vol depuis Bali en 2h30 (plus proche que Sydney). Population 130 000 : ville à taille humaine.",

    "hobart:fr": "Hobart, capitale de la Tasmanie : 250 000 habitants, ville la plus méridionale d'Australie, climat océanique frais, Mont Wellington (1271m) qui domine la ville. <strong>Janvier est mon mois préféré</strong> (8.5/10) : 13-22°C, 26% de pluie, été austral. <strong>De juin à août</strong> (hiver austral), comptez 4-13°C : froid avec parfois neige sur le Mont Wellington (rare en ville). <strong>Mars-avril</strong> sont mes vrais bons compromis : 11-20°C, foules touristiques réduites, foliage en Tasmanie. <strong>Sites majeurs</strong> : <strong>MONA</strong> (Museum of Old and New Art, l'un des musées d'art contemporain les plus avant-gardistes au monde, accès en ferry catamaran depuis le centre), <strong>Mont Wellington</strong> (route ou Pinnacle Track de marche), <strong>Salamanca Market</strong> (samedi matin, marché historique sur Salamanca Place), <strong>Battery Point</strong> (quartier historique XIXe). <strong>Excursions Tasmanie</strong> : <strong>Cradle Mountain</strong> et son Lake St Clair National Park (Overland Track 6 jours), <strong>Bay of Fires</strong> (côte est, plages aux rochers oranges spectaculaires), <strong>Wineglass Bay</strong> (Freycinet National Park), <strong>Port Arthur</strong> (ancien bagne UNESCO). <strong>Tester</strong> Tasmanian salmon, oysters, scallops, whisky de Tasmanie (Sullivans Cove). Vol direct Sydney/Melbourne en 1h30. Tasmanie devient destination food&drink majeure.",

    "uluru:fr": "Uluru (anciennement Ayers Rock) est le rocher emblématique du centre rouge australien : 348m de hauteur, 9,4 km de circonférence, classé UNESCO. <strong>Septembre est mon mois préféré</strong> (9.4/10) : 13-28°C, 8% de pluie, températures parfaites avant l'été infernal. <strong>De décembre à février</strong>, c'est l'été désertique : 23-38°C avec parfois 45°C, mouches partout (filets de tête recommandés), nombreux décès de touristes par déshydratation chaque année. <strong>De juin à août</strong> (hiver austral), comptez 6-20°C : nuits glaciales (parfois -5°C), journées idéales pour la randonnée. <strong>Avril-mai et septembre-octobre</strong> sont les vrais bons compromis. <strong>L'ascension d'Uluru est interdite depuis 2019</strong> (respect du sacré aborigène Anangu). Le tour à pied (10,6 km autour) reste ouvert. <strong>Sites majeurs</strong> : <strong>Uluru</strong> au lever et coucher du soleil (couleurs spectaculaires), <strong>Kata Tjuta</strong> (Mont Olga à 30 km, formation de 36 dômes, randonnée Walpa Gorge ou Valley of the Winds), <strong>Field of Light</strong> (installation Bruce Munro, 50 000 lumières), <strong>Cultural Centre</strong> aborigène. <strong>Logistique</strong> : aéroport Ayers Rock Airport, navette ou voiture vers le resort Yulara (seul hébergement, pas d'hébergement libre dans le parc). Compter 1500-3000$ pour 3-4 jours all-inclusive depuis Sydney/Melbourne. Site sacré : ne pas photographier certaines parties (panneaux indicatifs).",

    "whitsundays:fr": "Les Whitsundays sont 74 îles tropicales du Queensland au cœur de la Grande Barrière de Corail : Whitehaven Beach (sable blanc à 98% silice, parmi les plus belles plages du monde), Heart Reef (récif en forme de cœur). <strong>Octobre est mon mois préféré</strong> (8.8/10) : 22-25°C, 23% de pluie, fin de la saison sèche, mer calme, visibilité maximale. <strong>De novembre à avril</strong>, c'est la saison humide : 40-66% de précipitations, cyclones possibles (catégorie 5 historiques), méduses irukandji (combinaison stinger ou plage en filet). <strong>De mai à octobre</strong>, c'est la saison sèche : 23-40% de pluie, idéal. <strong>Activités majeures</strong> : <strong>Whitehaven Beach</strong> (excursion bateau depuis Airlie Beach, 7 km de sable blanc, Hill Inlet pour la photo aérienne signature des tourbillons), <strong>Heart Reef</strong> (uniquement vu d'avion ou hélicoptère, vols panoramiques 200-400$), <strong>plongée et snorkeling</strong> (sorties journée ou liveaboard 3-7 jours), <strong>Hamilton Island</strong> et <strong>Hayman Island</strong> (resorts luxe), <strong>Daydream Island</strong>. <strong>Airlie Beach</strong> = base sur le continent (animation, lagune artificielle car pas de plage urbaine baignable due aux crocs/méduses). <strong>Catamaran cruises</strong> 2-3 jours (300-700$) très populaires. <strong>Tester</strong> coral trout, mud crab, prawns. Vol depuis Brisbane vers Hamilton Island ou Whitsunday Coast (Proserpine).",

    "auckland:fr": "Auckland est la plus grande ville de Nouvelle-Zélande : 1,7 million d'habitants (1/3 du pays), \"City of Sails\" (1 voilier pour 4 habitants), construite sur 50 volcans dormants. <strong>Janvier-février sont mes mois préférés</strong> (8.2-8.3/10) : 18-23°C, 39-40% de pluie, été austral, baignade aux plages de l'East Coast (Mission Bay, Takapuna). <strong>De juin à août</strong> (hiver austral), comptez 10-16°C avec 42-48% de précipitations : doux pour l'hémisphère sud mais humide. <strong>Auckland a un climat \"4 saisons en une journée\"</strong> typique de la Nouvelle-Zélande. <strong>Sites majeurs</strong> : <strong>Sky Tower</strong> (328m, plus haute structure de l'hémisphère sud, SkyJump pour les courageux), <strong>Auckland Domain</strong> et War Memorial Museum, <strong>Viaduct Harbour</strong> (port refait pour l'America's Cup), <strong>Devonport</strong> (en ferry 12 min, charme villageois). <strong>Excursions</strong> : <strong>Waiheke Island</strong> à 40 min en ferry (vins, plages, restos), <strong>Rangitoto Island</strong> (volcan jeune 600 ans, randonnée vers le sommet), <strong>Hobbiton</strong> à 2h30 (set du Seigneur des Anneaux à Matamata), <strong>Coromandel Peninsula</strong> à 2h (Cathedral Cove, Hot Water Beach pour creuser sa propre piscine chaude à marée basse). <strong>Tester</strong> hangi (cuisine maorie cuite dans la terre), pavlova, hokey pokey ice cream, NZ wines (Sauvignon blanc Marlborough). Auckland est généralement le point de départ ou d'arrivée des road trips néo-zélandais.",

    "wellington:fr": "Wellington, capitale néo-zélandaise : 215 000 habitants, ville la plus venteuse au monde (\"Windy Welly\", vent annuel moyen 27 km/h), café-culture intense, scène culturelle. <strong>Janvier-février sont mes mois préférés</strong> (8.1-8.3/10) : 15-20°C, 26% de pluie, été austral. <strong>De juin à août</strong> (hiver austral), comptez 9-13°C et 41-43% de pluie : doux mais humide et venteux, jours à 9h de lumière. <strong>Sites majeurs</strong> : <strong>Te Papa</strong> (Musée National, gratuit, l'un des meilleurs musées d'Océanie), <strong>Mont Victoria</strong> (vue sur la baie), <strong>Cable Car</strong> jusqu'à Kelburn et le Botanic Garden, <strong>Cuba Street</strong> (rue piétonne bohème, cafés), <strong>Weta Workshop</strong> (effets spéciaux du Seigneur des Anneaux, du Hobbit, d'Avatar : visite 30 min). <strong>Wellington Movie Tour</strong> sur les sets du Seigneur des Anneaux. <strong>Zealandia</strong> (sanctuaire éco-restauré, faune néo-zélandaise). <strong>Marlborough vineyards</strong> à 3h (en ferry vers South Island, capitale du Sauvignon blanc), <strong>Kapiti Coast</strong> à 1h, <strong>Martinborough wineries</strong> à 1h30 (Pinot Noir). <strong>Inter-Islander Ferry</strong> Wellington-Picton (3h30, Cook Strait, traversée parmi les plus belles au monde). <strong>Tester</strong> flat white, fish and chips, hokey pokey. Wellington a la plus forte densité de cafés/restos par habitant au monde.",

    "christchurch:fr": "Christchurch, capitale du Canterbury en South Island : 380 000 habitants, ville la plus \"anglaise\" de Nouvelle-Zélande, tragiquement marquée par les <strong>séismes de septembre 2010 et février 2011</strong> (185 morts, 50% du centre détruit). Reconstruction toujours en cours. <strong>Janvier-février sont mes mois préférés</strong> (8.3/10) : 13-21°C, 25-28% de pluie, été austral. <strong>De juin à août</strong> (hiver austral), comptez 4-12°C : froid sec, neige possible sur les Port Hills. <strong>Sites majeurs</strong> : <strong>Cathedral Square</strong> (Cathédrale en cours de restauration depuis le séisme, projet de 10 ans), <strong>Cardboard Cathedral</strong> (Shigeru Ban, cathédrale temporaire 2013), <strong>185 Empty Chairs Memorial</strong> (mémorial des victimes du séisme), <strong>Botanic Gardens</strong>, <strong>Christchurch Tram</strong>. <strong>Quake City</strong> (musée sur les séismes). <strong>Excursions</strong> : <strong>Akaroa</strong> à 1h30 (péninsule de Banks, ex-colonie française, dauphins Hector), <strong>Arthur's Pass</strong> à 2h30 (route panoramique vers la côte ouest), <strong>Kaikoura</strong> à 2h30 (whale watching, baleines toute l'année), <strong>Mount Hutt</strong> et autres stations de ski en hiver. Christchurch est le point de départ classique des road trips de l'île du sud (vers Queenstown via Wanaka, ou via la côte ouest et Franz Josef Glacier). Vol direct depuis Sydney/Melbourne.",

    "queenstown:fr": "Queenstown est la <strong>capitale mondiale de l'aventure</strong> : entourée des Remarkables Mountains, sur le lac Wakatipu, c'est ici que le bungee jumping commercial est né (1988, Kawarau Bridge). <strong>Janvier-février sont mes mois préférés</strong> (8.0/10) : 12-21°C, 36-38% de pluie, été austral, randonnée Routeburn Track et Milford Track (Great Walks, réservation 6+ mois avant). <strong>De juin à août</strong> (hiver austral), comptez 2-8°C : c'est la saison ski, 4 stations (Coronet Peak, The Remarkables, Cardrona, Treble Cone à Wanaka), neige fiable. <strong>Mai et septembre-octobre</strong> sont les intersaisons : ski qui finit ou commence, randonnée pas encore au point. <strong>Activités</strong> : <strong>Bungee jumping</strong> (Kawarau Bridge 43m original, Nevis 134m le plus haut), <strong>Shotover Jet</strong> (jet boat dans les canyons), <strong>Skyline Gondola</strong> et luge, <strong>parapente</strong>, <strong>vol panoramique</strong> vers Milford Sound (45 min, l'un des plus beaux trajets aériens au monde). <strong>Excursions</strong> : <strong>Milford Sound</strong> à 4h en bus puis bateau (\"8e merveille du monde\" selon Kipling), <strong>Glenorchy</strong> à 45 min (paradis sets Lord of the Rings), <strong>Arrowtown</strong> (ex-village ruée vers l'or), <strong>Wanaka</strong> à 1h (\"Queenstown sans le tourisme de masse\"). <strong>Fergburger</strong> = institution locale (queue de 30 min). Très cher : hôtels 200-500$/nuit, repas 25-40$. Aéroport très fréquenté en saison ski (juillet-août).",

    "rotorua:fr": "Rotorua est la capitale géothermique néo-zélandaise : 75 000 habitants, geysers, sources chaudes, mares de boue, odeur de soufre permanente. Capitale aussi de la culture maorie en North Island. <strong>Janvier-février sont mes mois préférés</strong> (8.1-8.3/10) : 14-23°C, 39-41% de pluie, été austral. <strong>De juin à août</strong> (hiver austral), comptez 5-13°C et 39-43% de pluie : froid et humide, mais c'est aussi quand les sources chaudes prennent tout leur sens (vapeur dans le froid). <strong>Sites majeurs</strong> : <strong>Te Puia</strong> (Pohutu Geyser jusqu'à 30m, marae maori, kiwi house), <strong>Wai-O-Tapu Thermal Wonderland</strong> (Champagne Pool, Lady Knox Geyser à 10h15 chaque jour), <strong>Hell's Gate</strong> (mares de boue), <strong>Polynesian Spa</strong> (sources thermales en bord de lac), <strong>Whakarewarewa</strong> (village maori vivant), <strong>Hangi et concert maori</strong> (cuisine traditionnelle dans la terre + danse). <strong>Activités outdoor</strong> : <strong>Redwoods Forest</strong> (marche dans la canopée Redwoods Treewalk, VTT mondialement connu), <strong>Mountain biking</strong> (Whakarewarewa Forest, l'un des meilleurs spots VTT au monde). <strong>Wai-O-Tapu</strong> à 30 min, <strong>Lake Taupo</strong> à 1h (le plus grand lac de NZ, cratère volcanique), <strong>Tongariro Alpine Crossing</strong> à 1h30 (l'une des plus belles randonnées au monde, 19,4 km). <strong>Tester</strong> hangi, kiwifruit (originaire ici à Te Puke à 1h). Odeur de soufre quasi permanente : on s'y habitue.",

    "taupo:fr": "Lake Taupo est le plus grand lac de Nouvelle-Zélande : 616 km² (2 fois la taille de Singapour), formé par l'éruption du super-volcan Taupo il y a 1800 ans (l'une des plus grandes des derniers 5000 ans). <strong>Janvier est mon mois préféré</strong> (7.9/10) : 13-22°C, 33% de pluie, été austral, baignade dans le lac (eau à 18-20°C en été). <strong>De juin à août</strong> (hiver austral), comptez 4-11°C avec 40-44% de pluie : froid, ski possible à <strong>Whakapapa</strong> et <strong>Tūroa</strong> sur le Mont Ruapehu (2 plus grandes stations de NZ). <strong>Sites majeurs</strong> : <strong>Huka Falls</strong> (cascade puissante, 220 000 litres/seconde), <strong>Craters of the Moon</strong> (zone géothermique gratuite), <strong>Tongariro National Park</strong> (UNESCO, 3 volcans actifs : Ruapehu, Ngauruhoe = Mount Doom du Seigneur des Anneaux, Tongariro), <strong>Tongariro Alpine Crossing</strong> (19,4 km, l'une des meilleures randonnées au monde, à faire avec navette point à point), <strong>sky dive Taupo</strong> (la moins chère pour le saut en parachute en NZ, 200-400$). <strong>Hot Water Beach</strong> au lac, <strong>Maori rock carvings</strong> à Mine Bay (uniquement accessibles en bateau). <strong>Trout fishing</strong> mondialement réputé (truite arc-en-ciel et brune). Taupo = base centrale pour explorer Tongariro National Park. À 1h de Rotorua, 4h d'Auckland, 5h de Wellington.",

    "bay-of-islands:fr": "Bay of Islands, dans le Northland néo-zélandais : 144 îles, eau turquoise, base historique de la fondation de la Nouvelle-Zélande (Treaty of Waitangi 1840 entre Maoris et Couronne britannique). <strong>Janvier est mon mois préféré</strong> (8.4/10) : 17-24°C, 39% de pluie, été austral subtropical (climat plus chaud que Auckland). <strong>De juin à août</strong> (hiver austral), comptez 10-16°C avec 37-43% de pluie : doux pour la NZ. <strong>Sites majeurs</strong> : <strong>Waitangi Treaty Grounds</strong> (le lieu fondateur du pays, marae, musée), <strong>Russell</strong> (\"première capitale\", ferry depuis Paihia), <strong>Paihia</strong> (centre touristique), <strong>Hole in the Rock</strong> (excursion bateau, arche rocheuse percée), <strong>dolphin tours</strong> (dauphins toute l'année), <strong>Cape Reinha</strong> à 3h (point le plus septentrional accessible de NZ, où les âmes maories quittent le monde). <strong>90 Mile Beach</strong> (en réalité 90 km, accessible en bus 4×4 sur le sable). <strong>Activités</strong> : voile (sortie catamaran journée 100-150$, excursion 3 jours 500$), <strong>plongée</strong> (épave du Rainbow Warrior coulé par la France à Matauri Bay), kayak. <strong>Tester</strong> snapper (poisson local), kiwi fruit, hokey pokey ice cream. Bay of Islands = destination tropical NZ pour les Néo-zélandais (vacances scolaires de janvier). Vol direct Auckland-Bay of Islands (Kerikeri) en 35 min, ou 3h de route.",

    "nouvelle-zelande:fr": "La Nouvelle-Zélande est l'un des plus beaux pays au monde : 5 millions d'habitants pour 268 000 km² (la France métropolitaine fait 552 000 km²), 30 fois plus de moutons que d'habitants. <strong>Janvier-février sont mes mois préférés</strong> (8.1-8.2/10) : 15-20°C en moyenne nationale, été austral, journées longues, randonnées Great Walks (Milford Track, Routeburn Track, Tongariro Alpine Crossing) accessibles. <strong>De juin à août</strong> (hiver austral), comptez 4-13°C : froid avec neige en altitude, c'est la saison ski (Queenstown, Wanaka, Mt Ruapehu). <strong>Mars-avril et octobre-novembre</strong> sont les meilleurs compromis. <strong>Climat \"4 saisons en une journée\"</strong> : prévoir veste chaude/imperméable même en plein été. <strong>Top sites</strong> : <strong>Milford Sound</strong> (Fjordland), <strong>Aoraki/Mount Cook</strong> (3724m, plus haut sommet), <strong>Lake Tekapo</strong> (Church of the Good Shepherd, ciel étoilé Dark Sky), <strong>Glaciers Franz Josef et Fox</strong>, <strong>Rotorua/Taupo</strong> (geysers), <strong>Wellington</strong>, <strong>Auckland</strong>, <strong>Bay of Islands</strong>, <strong>Hobbiton</strong>, <strong>Wanaka</strong>. <strong>Logistique</strong> : compter <strong>3-4 semaines minimum</strong> pour voir l'essentiel (2 îles), road trip en camping-car ou voiture (gauche), distances raisonnables. Vols intérieurs : Air NZ, Jetstar. Vol direct Paris-Auckland en 24-26h (via Singapour ou Doha). Saisons inversées hémisphère sud.",

    "tahiti:fr": "Tahiti, île principale de la <strong>Polynésie française</strong> : 200 000 habitants, capitale Papeete, base d'arrivée pour Bora Bora, Moorea et autres îles. <strong>Août est mon mois préféré</strong> (7.8/10) : 23-27°C, 65% de pluie, saison sèche relative. <strong>De mai à octobre</strong>, c'est la saison sèche : 65-78% de précipitations (mais souvent en averses brèves), température 23-28°C, mer à 26°C, alizés rafraîchissants. <strong>De novembre à avril</strong>, c'est la saison humide : 78-94% de précipitations, chaleur lourde (24-29°C), risque cyclonique réel (Olaf 2005, Oli 2010). Tahiti ne dépasse jamais 8/10 : climat tropical océanique humide constant. <strong>Sites majeurs Tahiti</strong> : <strong>Papeete</strong> (marché central, scène culturelle), <strong>Lagonarium et Musée Gauguin</strong>, <strong>Trou du Souffleur</strong> à Arahoho, <strong>cascades de Faaruumai</strong>, <strong>Teahupoo</strong> (vague de surf mythique au sud, étape mondiale du World Surf League, lieu des épreuves de surf des JO Paris 2024 sur Tahiti), <strong>Lavatubes</strong>. <strong>Tahiti</strong> sert principalement de transit (1-2 jours suffisent) avant de rejoindre les vraies destinations carte postale : <strong>Bora Bora</strong>, <strong>Moorea</strong>, <strong>Rangiroa</strong>, <strong>Fakarava</strong>, <strong>Marquises</strong>. <strong>Tester</strong> poisson cru au lait de coco (plat national), poke, mahi-mahi grillé, fei (banane locale). Vol Paris-Papeete via Los Angeles (24h) ou Vancouver (22h). Devise : franc Pacifique (XPF, 119,33 XPF = 1 EUR fixe).",

    "bora-bora:fr": "Bora Bora est l'image carte postale ultime de la Polynésie française : île volcanique de 30 km² entourée d'un lagon turquoise et d'un récif corallien. Pic du Mont Otemanu (727m). <strong>Août est mon mois préféré</strong> (8.0/10) : 22-23°C, 40% de pluie, saison sèche, mer à 26°C, alizés constants. <strong>De mai à octobre</strong>, c'est la saison sèche relative : 40-61% de précipitations, températures 21-25°C, idéale pour la plongée. <strong>De novembre à avril</strong>, c'est la saison humide : 56-84% de précipitations, chaleur lourde, risque cyclonique. <strong>Bora Bora reste la plus chère destination paradisiaque au monde</strong> : bungalows sur pilotis 800-3000€/nuit, vol Papeete-Bora Bora 200-400€ aller-retour. Resorts emblématiques : Four Seasons, St. Regis, Conrad, Le Méridien. <strong>Activités</strong> : <strong>snorkeling</strong> dans le lagon (raies pastenagues, raies léopards, requins-pointes-noires non dangereux), <strong>plongée</strong> sur les passes (raies mantas, requins gris), <strong>tour du lagon</strong> en bateau avec arrêt motus (îlots), <strong>jet ski tour</strong> autour de l'île, <strong>survol en hydravion</strong> ou hélicoptère pour la vue aérienne emblématique du lagon. <strong>Vaitape</strong> = village principal sur l'île (boutiques, marché, restos hors-resort). <strong>Tester</strong> poisson cru au lait de coco, mahi mahi. Lune de miel ultime mais comptez 8000-15000€ pour 7-10 jours en couple.",

    "moorea:fr": "Moorea, en forme de cœur, est l'île sœur de Tahiti à 30 min en ferry de Papeete : plus authentique et moins chère que Bora Bora, mais tout aussi spectaculaire. Mont Tohivea (1207m), baies signature Cook et Opunohu. <strong>Juillet-août sont mes mois préférés</strong> (8.3/10) : 23-26°C, 40-42% de pluie, saison sèche, mer à 25°C. <strong>De mai à octobre</strong>, c'est la saison sèche : 40-54% de précipitations, températures 23-28°C, alizés rafraîchissants. <strong>De novembre à avril</strong>, c'est la saison humide : 56-78% de précipitations, chaleur lourde, risque cyclonique (rare). <strong>Sites majeurs</strong> : <strong>Belvédère</strong> (vue panoramique sur les baies de Cook et Opunohu, accès en voiture par les ananas), <strong>Magic Mountain</strong> (autre vue, accès 4×4), <strong>Lagon</strong> (snorkeling avec raies, requins-pointes-noires, tortues), <strong>Tour du lagon</strong> en bateau (excursion classique, arrêt motus), <strong>nage avec dauphins et baleines</strong> (juillet-octobre, baleines à bosse). <strong>Tiki Village</strong> (spectacle culturel polynésien). <strong>Plongée</strong> mondiale (Tiki Diving, Bathys Diving). Tour de l'île à vélo ou scooter (60 km en 4h). Hôtels et pensions familiales bien moins chers que Bora Bora (200-800€/nuit). <strong>Tester</strong> poisson cru, ma'a tinito, ananas Moorea. Le ferry Aremiti depuis Papeete (5 fois/jour, 30 min, 15-20€) rend Moorea très accessible.",

    "polynesie:fr": "La <strong>Polynésie française</strong> couvre 5 archipels sur 5 millions de km² (la taille de l'Europe) : 118 îles, 280 000 habitants. <strong>Août est mon mois préféré</strong> (7.7/10) : 23-27°C, 65% de pluie, saison sèche. <strong>De mai à octobre</strong> est la saison sèche relative (alizés constants, mer plus calme), <strong>de novembre à avril</strong> est la saison humide (cyclones possibles). <strong>Les 5 archipels</strong> : <strong>Iles de la Société</strong> (Tahiti, Moorea, Bora Bora, Raiatea, Huahine, Maupiti, les plus visitées), <strong>Tuamotu</strong> (atolls, plongée mondiale Rangiroa et Fakarava), <strong>Marquises</strong> (Hiva Oa où Gauguin et Brel sont enterrés, Nuku Hiva, paysages de cathédrales rocheuses, isolées et sauvages), <strong>Australes</strong> (Rapa, Raivavae, baleines à bosse), <strong>Gambier</strong> (Mangareva, perles noires, le plus reculé). <strong>Activités majeures</strong> : plongée (passes des atolls Tuamotu = parmi les meilleures au monde, raies mantas, requins-marteaux, requins-tigres), surf (Teahupoo à Tahiti = vague mythique, JO Paris 2024 ici), nage avec baleines à bosse (juillet-octobre dans plusieurs archipels), randonnée (Marquises). <strong>Air Tahiti</strong> dessert toutes les îles (Air Tahiti Pass 60-200€ entre îles). Comptez 3-4 semaines minimum pour voir 2-3 archipels. Vol direct Paris-Papeete via LA ou via Tokyo. <strong>Tester</strong> poisson cru au lait de coco, ma'a tinito, fei.",

    "fidji:fr": "Les Fidji sont un archipel de 333 îles dans le Pacifique sud : 900 000 habitants, 2 grandes îles (Viti Levu où se trouve la capitale Suva, Vanua Levu), des centaines d'îles plus petites (Mamanuca et Yasawa Islands pour le tourisme). <strong>Juin est mon mois préféré</strong> (7.7/10) : 17-22°C, 47% de pluie, saison sèche austral (Dry Season). <strong>De mai à octobre</strong>, c'est la saison sèche : 47-60% de précipitations, températures 16-25°C, mer à 25-26°C. <strong>De novembre à avril</strong>, c'est la saison humide (Wet Season) : 75-94% de précipitations, chaleur lourde (20-26°C), risque cyclonique réel (Winston 2016 catégorie 5 a tué 44 personnes). <strong>Sites majeurs</strong> : <strong>Mamanuca Islands</strong> (les plus accessibles depuis Nadi, day trips en bateau), <strong>Yasawa Islands</strong> (plus sauvages, plus loin), <strong>Coral Coast</strong> (côte sud de Viti Levu, hôtels), <strong>Suva</strong> (capitale), <strong>Garden of the Sleeping Giant</strong> (jardin botanique). <strong>Activités</strong> : plongée (parmi les meilleures au monde, soft corals magnifiques), <strong>cérémonie kava</strong> (boisson traditionnelle racine de poivrier, accueillie dans les villages), surf (Cloudbreak à Tavarua mondialement réputée). <strong>Cuisine</strong> influence indo-fidjienne (40% de Fidjiens d'origine indienne héritage colonial britannique) : kokoda (poisson cru au lait de coco), rourou (taro), curry. Vol direct depuis Sydney/Auckland en 3h, depuis Los Angeles en 11h.",

    "iles-cook:fr": "Les Iles Cook sont un archipel de 15 îles néo-zélandais en libre association : 17 000 habitants, capitale Avarua sur Rarotonga (l'île principale). État indépendant mais citoyenneté néo-zélandaise. <strong>Novembre est mon mois préféré</strong> (8.2/10) : 21-22°C, 38% de pluie, saison sèche. <strong>De mai à octobre</strong>, c'est la saison sèche : 36-56% de précipitations, températures 20-25°C, alizés constants. <strong>De novembre à avril</strong>, c'est la saison humide : 51-66% de précipitations, chaleur lourde, risque cyclonique (Pat 2010). <strong>Sites majeurs</strong> : <strong>Rarotonga</strong> (île principale, 32 km de circonférence, randonnée Cross-Island Track de 6h), <strong>Aitutaki</strong> à 50 min en avion (lagune turquoise spectaculaire avec 15 motus, considérée l'une des plus belles du Pacifique sud), <strong>Atiu</strong> (grottes calcaires, café local), <strong>Mangaia</strong> (la plus vieille île du Pacifique). <strong>Activités</strong> : plongée et snorkeling, kayak dans la lagune d'Aitutaki, randonnée à Rarotonga, observation oiseaux marins. <strong>Marché de Punanga Nui</strong> à Avarua le samedi. Communauté maorie cook (langue cook islands maori). <strong>Cuisine</strong> : ika mata (poisson cru au lait de coco, version Cook), poké (taro), poisson grillé. Vol direct depuis Auckland en 4h (Air New Zealand) ou Los Angeles. Très bon rapport qualité/prix vs Polynésie française : moitié moins cher, ambiance plus relax. Devise : NZ Dollar.",

    "rarotonga:fr": "Rarotonga est l'île principale des Iles Cook : 67 km², 14 000 habitants, montagne centrale (Te Manga 653m), boucle routière de 32 km autour de l'île. <strong>Novembre est mon mois préféré</strong> (8.2/10) : 21-22°C, 38% de pluie, saison sèche. <strong>De mai à octobre</strong> est la saison sèche relative (36-56% de précipitations). <strong>De novembre à avril</strong>, c'est la saison humide (51-66%). <strong>Sites majeurs</strong> : <strong>Plages</strong> Muri Beach (la plus connue, lagune calme, kayak vers les motus), Aro'a Beach (snorkeling), Black Rock Beach (coucher de soleil), <strong>Cross-Island Track</strong> (randonnée 6h à travers l'île, Te Rua Manga \"Aiguille\" comme point culminant), <strong>Punanga Nui Market</strong> à Avarua (le samedi matin, marché alimentaire/artisanat), <strong>Avana Lagoon</strong> (sortie pour Aitutaki en bateau). <strong>Activités</strong> : <strong>tour de l'île en bus</strong> (système de bus circulaire \"clockwise/anticlockwise\", 1 toutes les 30 min), location de scooter (60 NZ$/jour) ou voiture, plongée et snorkeling. <strong>Cultural Village</strong> (spectacle culture maorie cook). <strong>Marae</strong> (sites sacrés ancestraux). Hébergement : pas de gros resort all-inclusive style Maldives, plutôt des bungalows et hôtels familiaux à 100-300 NZ$/nuit. <strong>Tester</strong> ika mata, taro, ananas local. Vol Auckland-Rarotonga 4h, prix abordables. Rarotonga = principale alternative low-cost à Tahiti.",

    "vanuatu:fr": "Vanuatu est un archipel de 83 îles dans le Pacifique sud : 320 000 habitants, capitale Port Vila sur Efate, ex-condominium franco-britannique des Nouvelles-Hébrides (indépendance 1980). Volcans actifs accessibles aux touristes. <strong>Juin-juillet sont mes mois préférés</strong> (8.3/10) : 22-26°C, 37-39% de pluie, saison sèche austral. <strong>De mai à octobre</strong>, c'est la saison sèche relative : 36-55% de précipitations, températures 21-27°C. <strong>De novembre à avril</strong>, c'est la saison humide : 55-85% de précipitations, chaleur lourde, risque cyclonique très élevé (Pam 2015 catégorie 5 a dévasté, Harold 2020 aussi). <strong>Sites majeurs</strong> : <strong>Mont Yasur</strong> sur l'île de Tanna (volcan actif accessible jusqu'au cratère, expérience unique au monde, éruptions visibles toutes les minutes, partir au coucher du soleil pour la lave incandescente), <strong>Champagne Beach</strong> à Espiritu Santo (plage classée parmi les plus belles du monde), <strong>Million Dollar Point</strong> (épaves matériel militaire US WWII jeté à la mer en 1945, plongée), <strong>SS President Coolidge</strong> (l'une des plus grandes épaves accessibles en plongée loisir au monde). <strong>Cultural villages</strong> mélanésiens. <strong>Land diving</strong> à Pentecost (mai-juin, ancêtre du bungee jumping, hommes plongent depuis tour en bois avec lianes attachées aux chevilles). <strong>Tester</strong> kava (boisson traditionnelle), poisson cru, lap lap (pudding traditionnel). Vol depuis Brisbane/Sydney en 3h, escale obligatoire Auckland depuis Europe.",

    "samoa:fr": "Samoa (anciennement Samoa occidentales) est un État indépendant du Pacifique sud : 200 000 habitants, capitale Apia sur Upolu, 10 îles. À ne pas confondre avec American Samoa (territoire US). <strong>Juin-août sont mes mois préférés</strong> (6.9/10) : 24-28°C, 73-76% de pluie, saison sèche relative. Climat équatorial humide = Samoa ne dépasse jamais 7/10. <strong>De mai à octobre</strong>, c'est la saison sèche relative : 73-86% de précipitations. <strong>De novembre à avril</strong>, c'est la saison humide : 88-95% de précipitations, chaleur lourde, risque cyclonique (Evan 2012, Gita 2018). <strong>Sites majeurs</strong> : <strong>To Sua Ocean Trench</strong> (piscine naturelle dans une falaise effondrée, l'image iconique de Samoa), <strong>Lalomanu Beach</strong> (plage), <strong>Robert Louis Stevenson Museum</strong> (l'auteur de L'Île au Trésor a vécu et est enterré ici à Vailima), <strong>Cratère Lake Lanoto'o</strong>, <strong>Cape Mulinu'u</strong> (le \"premier point du monde\" à voir le soleil après changement de date 2011). <strong>Iles à explorer</strong> : Upolu (la principale avec Apia), Savai'i (la plus grande, lave fields, blowholes Alofaaga). <strong>Cultural villages</strong> : fa'a Samoa = mode de vie traditionnel encore très vivant, dimanche jour sacré (tout fermé). <strong>Cuisine</strong> : palusami (taro et lait de coco), oka (poisson cru), umu (cuisson dans la terre). Vol depuis Auckland (4h) ou Brisbane. Beaucoup moins touristique que Fidji/Tahiti, ambiance authentique.",

    "tonga:fr": "Tonga est le seul royaume polynésien encore monarchique : 100 000 habitants, capitale Nuku'alofa sur Tongatapu. 169 îles dont 36 habitées. <strong>Juin-juillet sont mes mois préférés</strong> (8.2/10) : 21-25°C, 34-36% de pluie, saison sèche austral, mer à 25°C. <strong>De mai à octobre</strong>, c'est la saison sèche : 34-53% de précipitations, températures 21-27°C. <strong>De novembre à avril</strong>, c'est la saison humide : 53-86% de précipitations, chaleur lourde, risque cyclonique (Harold 2020, Gita 2018, Yasa 2020). <strong>Tonga est mondialement connu pour la nage avec baleines à bosse</strong> : <strong>juillet-octobre</strong>, les baleines à bosse migrent depuis l'Antarctique vers le lagon protégé pour mettre bas et reproduire. C'est l'un des très rares endroits au monde où la nage avec les baleines est légale et réglementée (groupe de 4 max + guide, permis exigé, distance respectée). Comptez 200-400$/jour pour cette expérience (Vava'u, l'archipel principal pour cette activité). <strong>Sites majeurs</strong> : <strong>Tongatapu</strong> (capitale, marché Talamahu, palais royal vue extérieure), <strong>Vava'u</strong> (archipel le plus pittoresque, 50 îles, baleines, voile, plongée), <strong>Ha'apai</strong> (très tranquille), <strong>'Eua</strong> (randonnée). <strong>Mapu'a 'a Vaca</strong> (blowholes spectaculaires sur 5 km de côte), <strong>Ha'amonga 'a Maui Trilithon</strong> (Stonehenge polynésien). <strong>Tester</strong> 'umu (cuisson dans la terre), lu sipi (mouton dans feuilles taro). Vol depuis Auckland (3h) ou Fidji.",

    "palau:fr": "Palau est un archipel de 340 îles dans le Pacifique nord-ouest : 18 000 habitants, capitale Ngerulmud (la moins peuplée au monde). État indépendant en libre association avec les USA depuis 1994. <strong>Mars est mon mois préféré</strong> (6.4/10) : 25-28°C, 68% de pluie, saison sèche relative. Palau ne dépasse jamais 6,5/10 : climat équatorial humide constant. <strong>De février à avril</strong>, c'est la saison sèche relative : 68-82% de précipitations. <strong>De mai à novembre</strong>, c'est la saison humide : 86-97% de précipitations, chaleur lourde (25-29°C). Pas de saison cyclonique (Palau est hors zone). <strong>Palau est mondialement réputée pour la plongée</strong> : <strong>Rock Islands Southern Lagoon</strong> (UNESCO, paysage marin de 250 îles calcaires en forme de champignons recouvertes de jungle), <strong>Blue Corner</strong> (l'un des 5 meilleurs sites de plongée au monde, requins gris en banc), <strong>German Channel</strong> (raies mantas), <strong>Jellyfish Lake</strong> (lac où l'on peut nager au milieu de millions de méduses non urticantes). <strong>Activités</strong> : plongée (700-1500$ pour 4-7 jours), kayak dans Rock Islands (excursion journée 100-200$). <strong>Sites historiques</strong> : épaves WWII (Palau a été un théâtre de combat majeur, bataille de Peleliu en 1944). <strong>Tester</strong> coconut crab, fish stew, taro. Vol obligatoire via Manille, Taipei ou Tokyo. Coût total élevé : 4000-6000€ pour 8 jours plongée tout compris.",

    "noumea:fr": "Nouméa est la capitale de la <strong>Nouvelle-Calédonie</strong> (territoire français d'outre-mer du Pacifique sud) : 100 000 habitants, ambiance \"Nice du Pacifique\", communauté multiculturelle (Européens, Mélanésiens kanaks, Polynésiens, Asiatiques). <strong>Novembre est mon mois préféré</strong> (8.5/10) : 21-27°C, 43% de pluie, fin du printemps austral, mer à 24°C. <strong>De mai à novembre</strong> est la saison sèche relative : 33-47% de précipitations, températures 17-26°C. <strong>De décembre à avril</strong>, c'est la saison humide : 50-70% de précipitations, chaleur lourde (24-29°C), risque cyclonique (Niran 2021). <strong>Sites majeurs</strong> : <strong>Anse Vata</strong> (plage urbaine principale, animée), <strong>Baie des Citrons</strong> (autre plage urbaine), <strong>Centre Culturel Tjibaou</strong> (Renzo Piano, dédié à la culture kanak), <strong>Marché de Nouméa</strong> (Port Moselle, le matin). <strong>Excursions</strong> : <strong>Ile aux Canards</strong> (sentier sous-marin balisé, accessible en navette 5 min), <strong>Ilot Maître</strong> (resort sur îlot), <strong>Phare Amédée</strong> (sortie journée). Le <strong>lagon calédonien</strong> est le plus grand lagon fermé du monde (UNESCO, 24 000 km²) : plongée et snorkeling sur la 2e plus grande barrière de corail au monde. <strong>Iles Loyauté</strong> à 1h en avion (Lifou, Maré, Ouvéa pour la plus belle plage). <strong>Grande Terre</strong> (île principale) : Yaté pour la nature, Rivière Bleue, Mont Panié. <strong>Tester</strong> bougna (plat kanak traditionnel), bichique. Vol direct Paris-Nouméa via Tokyo en 24h (Aircalin). Cher (île française du Pacifique), mais très belle destination."
}

with open(PATH, encoding='utf-8') as f:
    data_existing = json.load(f)

before = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

data_existing['_version'] = '2.1'
data_existing['_updated'] = '2026-04-27'

for k, v in AVIS_BATCH9_FR.items():
    data_existing[k] = v

after = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data_existing, f, ensure_ascii=False, indent=2)

print(f"Avis FR avant : {before}")
print(f"Avis FR après : {after}")
print(f"Nouveaux : {after - before}")

# Audit immédiat
import re
patterns_check = [
    ('em-dash', r'—'), ('guillemets', r'[«»]'),
    ('attendez-vous', r'attendez-vous à'),
    ('parfait', r'\bparfait[es]*\b'),
    ('fenêtre', r'\bfenêtre[s]?\b'),
    ('saturé', r'\bsatur[eéa]\w*\b'),
    ('se mérite', r'\bse méri[tes]+\b'),
    ('magique', r'\bmagiques?\b'),
    ('Si vous X:', r'Si vous \w+ : '),
    ('iconique', r'\biconique[s]?\b'),
    ('antithèse', r'antithèse'),
    ('mythique', r'\bmythique[s]?\b'),
    ('emblématique', r'\bemblématique[s]?\b'),
    ('authentique', r'\bauthentique[s]?\b'),
    ('féérique', r'\bféérique[s]?\b'),
    ("c'est aussi", r"[Cc]'est aussi"),
    ('à monitorer', r'à monitorer'),
    ('à éviter', r'à éviter'),
]

print("\n=== Audit batch 9 ===")
issues_total = 0
for slug in AVIS_BATCH9_FR.keys():
    plain = re.sub(r'<[^>]+>', '', data_existing[slug])
    issues = []
    for label, p in patterns_check:
        n = len(re.findall(p, plain))
        if n > 0:
            issues.append(f"{label}={n}")
            issues_total += n
    flag = "OK" if not issues else "PB " + ", ".join(issues)
    print(f"  {slug:<22} {len(plain.split()):>3}m {flag}")
print(f"\nTotal issues : {issues_total}")
