"""Batch 7 : 30 avis FR Tier 1 France/Italie/Espagne/Portugal."""
import json

PATH = 'data/avis_annuel.json'
data = json.load(open(PATH, encoding='utf-8'))

AVIS_BATCH7_FR = {
    "nice:fr": "Nice est la capitale de la Côte d'Azur : 350 000 habitants, climat méditerranéen le plus stable de France métropolitaine. <strong>Juillet est mon mois préféré</strong> (9.7/10) : 21-28°C, 8% de pluie, mer à 24°C, Promenade des Anglais en pleine vie. <strong>Août</strong> reste excellent (9.4/10) mais foules massives, prix hôteliers x2-x3. <strong>De décembre à février</strong>, comptez 5-14°C et 20-23% de pluie : doux pour la France métropolitaine, mais ciel plus changeant. C'est aussi le carnaval mi-février (l'un des 3 plus grands au monde avec Rio et Venise, 12 jours). <strong>Mai et septembre-octobre sont les vrais bons compromis</strong> : météo excellente, foules réduites de 50%, tarifs en retrait. <strong>Vieux Nice</strong> (Cours Saleya pour le marché provençal et la fleur), <strong>Colline du Château</strong> pour la vue, <strong>MAMAC</strong> et <strong>Musée Matisse</strong> à Cimiez. <strong>Tester</strong> socca (galette de pois chiche) chez Chez Pipo, salade niçoise (la vraie sans pommes de terre), pissaladière. À 30 min : Eze (village perché), Monaco, Cap Ferrat. Aéroport très bien connecté à toute l'Europe.",

    "cannes:fr": "Cannes vit deux vies : la station balnéaire de la Croisette et le village de pêcheurs du Vieux-Port (Suquet). <strong>Juillet est mon mois préféré</strong> (9.7/10) : 21-29°C, 8% de pluie, mer à 25°C, plages publiques bondées. <strong>Le Festival de Cannes</strong> mi-mai = pic touristique absolu : prix hôteliers x5, Croisette fermée à la circulation, palaces complets 6 mois à l'avance. <strong>Août</strong> excellent (9.4/10) mais foules. <strong>De décembre à février</strong>, comptez 6-14°C et 21-23% de pluie : doux, parfait pour visiter sans foule, plages désertes mais agréables. <strong>Sites majeurs</strong> : <strong>La Croisette</strong> et ses palaces (Carlton, Martinez, Majestic), <strong>Suquet</strong> (vieille ville sur la colline avec le Musée du Masque de Fer), <strong>Forville</strong> (marché provençal authentique tous les matins sauf lundi), <strong>Iles de Lérins</strong> en bateau (15 min vers Sainte-Marguerite, où le Masque de Fer fut emprisonné, 30 min vers Saint-Honorat avec ses moines cisterciens). <strong>Tester</strong> bouillabaisse, socca. <strong>Antibes</strong> et <strong>Mougins</strong> à 30 min, <strong>Grasse</strong> (parfumeries) à 20 min. Mai et septembre-octobre sont les meilleurs compromis touristique/météo.",

    "marseille:fr": "Marseille, la plus vieille ville de France (600 av JC, fondation phocéenne) : 870 000 habitants, mer, soleil, mistral et caractère bien trempé. <strong>Juillet est mon mois préféré</strong> (9.9/10) : 20-28°C, 4% de pluie, ciel d'une stabilité remarquable. <strong>Août</strong> excellent (9.7/10) mais Marseillais qui partent en vacances, ville plus calme. <strong>De décembre à février</strong>, comptez 5-13°C et 20-25% de pluie : doux pour la France, mistral fréquent (vent du nord-ouest qui dégage le ciel mais glace l'air). <strong>Sites majeurs</strong> : <strong>Vieux-Port</strong>, <strong>Notre-Dame de la Garde</strong> (la Bonne Mère, vue à 360°), <strong>MUCEM</strong> (musée des civilisations méditerranéennes, architecture remarquable), <strong>Le Panier</strong> (vieux quartier coloré), <strong>Calanques</strong> (parc national, Sormiou et Morgiou en voiture, En Vau et Sugiton en kayak ou randonnée). <strong>Iles du Frioul et château d'If</strong> en navette (Comte de Monte-Cristo). <strong>Tester</strong> bouillabaisse à Chez Fonfon ou Le Miramar (cher), pizza chez Chez Sauveur, navettes (biscuits parfumés à la fleur d'oranger). Cassis et ses calanques à 30 min en train. Mai-juin et septembre-octobre sont les meilleurs compromis tourisme/météo.",

    "biarritz:fr": "Biarritz, la station balnéaire chic du Pays basque français : ex-station impériale (Eugénie de Montijo), capitale du surf en Europe (depuis 1957). <strong>Juillet est mon mois préféré</strong> (8.5/10) : 18-23°C, 32% de pluie, températures parfaites, surfeurs partout. <strong>Août</strong> reste excellent (8.4/10) mais foules massives. <strong>De juin à septembre</strong> est la haute saison : 16-24°C, mer à 19-22°C, prix hôteliers x2-x3. <strong>De novembre à mars</strong>, comptez 6-15°C et 44-52% de pluie : océanique humide, mais c'est la saison des grosses houles atlantiques pour les surfeurs confirmés (vagues 3-5m). <strong>Sites majeurs</strong> : <strong>Grande Plage</strong>, <strong>Plage de la Côte des Basques</strong> (spot surf historique), <strong>Rocher de la Vierge</strong>, <strong>Hôtel du Palais</strong> (5 étoiles emblématique), <strong>Phare de Biarritz</strong>. <strong>Aquarium</strong> (Cité de l'Océan). <strong>Tester</strong> piperade, axoa de veau, gâteau basque. <strong>Saint-Jean-de-Luz</strong> à 20 min (plus authentique village basque), <strong>San Sebastián</strong> à 1h en Espagne (pintxos, plage de la Concha). Mai-juin et septembre sont les meilleurs compromis foule/météo. Vol direct Paris en 1h30, gare TGV directe.",

    "bordeaux:fr": "Bordeaux a connu sa renaissance depuis 2007 (rénovation des quais, tramway, LGV qui met Paris à 2h). UNESCO pour la \"belle endormie\" devenue branchée. <strong>Juillet est mon mois préféré</strong> (9.2/10) : 17-27°C, 25% de pluie, terrasses sur la Place de la Bourse, longueur des journées. <strong>Août</strong> excellent (9.0/10) mais Bordelais qui partent à l'océan. <strong>De décembre à février</strong>, comptez 4-12°C et 36-45% de pluie : océanique, ciel souvent gris, mais c'est la saison des huîtres (du Bassin d'Arcachon), des marchés de Noël et de la dégustation des grands crus dans les châteaux. <strong>Sites majeurs</strong> : <strong>Place de la Bourse</strong> et son Miroir d'eau (le plus grand au monde), <strong>Cité du Vin</strong> (musée moderne, dégustation panoramique au 8e), <strong>Grand Théâtre</strong>, <strong>Tour Pey-Berland</strong>, <strong>quartier Saint-Pierre</strong> (vieux Bordeaux), <strong>Darwin</strong> (rive droite branchée). <strong>Route des vins</strong> : Saint-Émilion (UNESCO, à 40 min en train), Médoc (Pauillac, Margaux), Sauternes. <strong>Tester</strong> canelés chez Baillardran, entrecôte bordelaise, lamproie. <strong>Bassin d'Arcachon</strong> et <strong>Dune du Pilat</strong> à 1h.",

    "corse:fr": "La Corse, l'\"île de Beauté\" : 8000 km², 350 000 habitants, montagnes (Monte Cinto 2706m) qui plongent dans la Méditerranée. <strong>Juillet est mon mois préféré</strong> (8.9/10) : 15-24°C, 23% de pluie, mer à 24°C aux plages de Palombaggia, Rondinara, Saleccia. <strong>Août</strong> excellent (8.7/10) mais foules massives, prix x3, ferries complets, autoroutes maritimes saturées. <strong>De décembre à mars</strong>, comptez -1/8°C en montagne et 6-15°C en plaine : ski possible au Capanelle ou Vergio (mais peu fiable), randonnée hivernale impossible en altitude. <strong>Sites majeurs</strong> : <strong>Bonifacio</strong> (citadelle perchée sur falaise calcaire), <strong>Calvi</strong> (citadelle génoise), <strong>Bastia</strong> (place Saint-Nicolas), <strong>Ajaccio</strong> (maison de Napoléon), <strong>Calanques de Piana</strong> (UNESCO), <strong>Désert des Agriates</strong>, <strong>GR20</strong> (l'un des trekkings les plus difficiles d'Europe, 16 étapes, juin-octobre). <strong>Plages</strong> : Palombaggia, Rondinara, Saleccia, Lotu (accessibles uniquement en bateau ou 4×4). <strong>Tester</strong> charcuterie corse (lonzu, coppa, prisuttu), brocciu, fiadone, vin de Patrimonio ou Ajaccio. Mai-juin et septembre-octobre sont les vrais bons compromis foule/météo.",

    "cote-azur:fr": "La Côte d'Azur s'étend de Cassis à Menton, soit 200 km de littoral varié. <strong>Juillet est mon mois préféré</strong> (9.7/10) : 21-28°C, 8% de pluie, ciel constant, mer à 24°C. <strong>Août</strong> excellent (9.3/10) mais c'est aussi le pic touristique absolu : prix x2-x4, autoroute A8 saturée, plages payantes prises d'assaut. <strong>De décembre à février</strong>, comptez 5-14°C et 20-23% de pluie : doux pour la France, ciel souvent dégagé, palmiers et orangers en pleine forme. <strong>Carnaval de Nice</strong> mi-février, <strong>Fête du Citron de Menton</strong> en février-mars. <strong>Villes majeures</strong> : Nice, Cannes, Saint-Tropez, Monaco, Menton, Antibes, Saint-Paul-de-Vence (village d'art), Eze (village perché). <strong>Plages</strong> : la plupart sont de galets (sauf Pampelonne, Antibes). <strong>Calanques de Cassis</strong> et <strong>Massif de l'Estérel</strong> pour la nature. <strong>Yachting</strong> : Saint-Tropez et Monaco concentrent l'activité (Yacht Show Monaco fin septembre). <strong>Tester</strong> ratatouille, daube provençale, tarte tropézienne, salade niçoise. Mai-juin et septembre sont les vrais bons compromis tourisme/météo.",

    "provence:fr": "La Provence couvre 4 départements : Vaucluse, Bouches-du-Rhône, Var, Alpes-de-Haute-Provence. <strong>Juin est mon mois préféré</strong> (9.3/10) : 17-29°C, 21% de pluie, lavande qui démarre sa floraison sur le plateau de Valensole (mi-juin à mi-juillet, pic vers le 14 juillet selon les années). <strong>Juillet-août</strong> sont caniculaires (19-33°C, parfois 40°C+) : Provençaux qui se réfugient dans la fraîcheur intérieure des vieilles maisons en pierre, mistral fréquent (vent du nord-ouest, dessèche tout). <strong>De décembre à février</strong>, comptez 2-14°C et 20-26% de pluie : doux pour la France, ciel souvent dégagé, oliviers verts. <strong>Sites majeurs</strong> : <strong>Avignon</strong> (Palais des Papes, Pont Saint-Bénézet, Festival en juillet), <strong>Aix-en-Provence</strong> (cours Mirabeau, Cézanne), <strong>Arles</strong> (arènes romaines, Van Gogh), <strong>Les Baux-de-Provence</strong>, <strong>Gordes</strong> et <strong>Roussillon</strong> (villages perchés du Luberon), <strong>Sénanque</strong> (abbaye cistercienne avec lavande), <strong>Mont Ventoux</strong> (Tour de France). <strong>Tester</strong> ratatouille, aïoli, tapenade, calissons d'Aix, vin AOC Châteauneuf-du-Pape, Gigondas, Bandol. Mai et septembre-octobre sont les meilleurs compromis tourisme/météo (lavande encore visible début juillet).",

    "annecy:fr": "Annecy, la \"Venise des Alpes\" : 130 000 habitants, lac alpin (le plus pur d'Europe selon les analyses), montagnes autour (La Tournette 2351m). <strong>Juillet-août sont mes mois préférés</strong> (8.8-8.9/10) : 16-27°C, 31-35% de pluie, baignade au lac (eau à 22°C en plein été), parapente depuis Le Semnoz, Tour du Lac à vélo (40 km). <strong>De décembre à février</strong>, comptez 0-10°C et 39-45% de pluie ou neige : ski à La Clusaz, Le Grand-Bornand ou Megève (45 min). <strong>Le Festival International du Film d'Animation</strong> mi-juin (l'un des plus grands au monde) anime la ville. <strong>Sites majeurs</strong> : <strong>Vieille ville</strong> avec ses canaux et le Palais de l'Île, <strong>Château d'Annecy</strong>, <strong>Pont des Amours</strong>, <strong>marchés du dimanche matin</strong> (très réputé). <strong>Lac d'Annecy</strong> : balade en bateau, plages publiques (Albigny gratuite, Impérial payante), villages pittoresques (Talloires, Veyrier-du-Lac). <strong>Tester</strong> tartiflette, fondue savoyarde, omble chevalier (poisson du lac). <strong>Genève</strong> à 45 min en voiture, <strong>Chamonix</strong> à 1h. Mai-juin et septembre sont les meilleurs compromis foule/météo. Vol direct Genève ou Lyon, TGV depuis Paris (3h45).",

    "strasbourg:fr": "Strasbourg, capitale de l'Alsace et siège du Parlement européen : 280 000 habitants, mélange culturel franco-allemand (annexée 4 fois en 75 ans entre 1870 et 1945). <strong>Juillet est mon mois préféré</strong> (8.7/10) : 16-26°C, 38% de pluie, terrasses Petite-France, croisières sur l'Ill. <strong>Août</strong> excellent (8.6/10). <strong>De novembre à mars</strong>, comptez 0-9°C et 36-43% de pluie ou neige : froid continental, mais c'est l'apogée touristique avec le <strong>Marché de Noël (Christkindelsmärik)</strong> du dernier vendredi de novembre au 24 décembre = le plus ancien de France (1570) et l'un des plus grands d'Europe. Prix hôteliers x3 pendant cette période. <strong>Sites majeurs</strong> : <strong>Cathédrale Notre-Dame</strong> (142m, plus haute du monde au XVe siècle, horloge astronomique, plateforme à 332 marches pour la vue), <strong>Petite-France</strong> (UNESCO, maisons à colombages sur les canaux), <strong>Palais Rohan</strong>, <strong>quartier européen</strong> (Parlement, Conseil de l'Europe). <strong>Tester</strong> choucroute (chez Chez Yvonne ou Maison Kammerzell), tarte flambée (\"flammkueche\"), bredele aux marchés de Noël, vin d'Alsace (Riesling, Gewurztraminer). <strong>Route des Vins d'Alsace</strong> à 30 min, <strong>Colmar</strong> à 30 min en train.",

    "amalfi:fr": "La Côte amalfitaine, classée UNESCO, c'est 50 km de route en lacets entre Salerne et Sorrente : Positano, Amalfi, Ravello, accrochés aux falaises. <strong>Juin est mon mois préféré</strong> (9.5/10) : 19-28°C, 18% de pluie, mer à 23°C, citronniers (limoncello local) en pleine production. <strong>Juillet-août chutent à 6.9/10</strong> à cause de la chaleur étouffante (22-31°C, ressenti 38°C+) et surtout de la <strong>foule extrême</strong> : route Amalfi-Positano bouchée 4-6h en jour, ferries plus rapides (Salerne-Amalfi-Positano), prix hôteliers x4-x5. <strong>De décembre à février</strong>, comptez 6-15°C et 37-45% de pluie : beaucoup d'hôtels et restos ferment, ferries réduits, mais ambiance désertée magnifique pour les amateurs de calme. <strong>Sites majeurs</strong> : <strong>Positano</strong> (le village le plus photogénique), <strong>Amalfi</strong> (cathédrale Sant'Andrea, République Maritime au Moyen Âge), <strong>Ravello</strong> (Villa Cimbrone, Villa Rufolo, Festival de musique en été), <strong>Sentier des Dieux</strong> (rando 7 km Bomerano-Nocelle, panorama exceptionnel). <strong>Tester</strong> sfogliatelle, scialatielli, limoncello, mozzarella di bufala. <strong>Capri</strong> à 30 min en hydrofoil. Mai et septembre-octobre sont les vrais bons compromis tourisme/météo.",

    "cinque-terre:fr": "Cinque Terre, c'est 5 villages de pêcheurs UNESCO accrochés aux falaises de la Riviera ligure : Monterosso, Vernazza, Corniglia, Manarola, Riomaggiore. <strong>Juillet est mon mois préféré</strong> (9.1/10) : 18-26°C, 24% de pluie, mer à 22°C. <strong>Août</strong> excellent (8.8/10) mais surfréquentation : <strong>3 millions de visiteurs/an</strong> sur 5 villages totalisant 4000 habitants, sentier Bleu (le SVA fameux Manarola-Riomaggiore alias \"Via dell'Amore\") fermé depuis 2012 (rouverture en cours), beaucoup de villages limitent l'accès. <strong>De novembre à mars</strong>, comptez 3-13°C et 39-48% de pluie : beaucoup d'hôtels et restos ferment, sentiers parfois fermés pour glissements de terrain (sept 2012, oct 2018 ont été dévastateurs). <strong>Mai-juin et septembre-octobre</strong> sont les vrais bons compromis. <strong>Train Cinque Terre Express</strong> qui dessert les 5 villages = solution la plus pratique (5€ trajet ou pass jour 18,50€). <strong>Randonnées</strong> : sentier Sentiero Azzurro (50€ permis Cinque Terre Card), Sentiero Verde-Azzurro plus haut. <strong>Tester</strong> pesto genovese, focaccia, anchois de Monterosso, sciacchetrà (vin de paille). <strong>La Spezia</strong> à 10 min en train pour les hôtels moins chers et plus calmes.",

    "capri:fr": "Capri, l'île chic de la baie de Naples : 10 km², 13 000 habitants permanents, 2,5 millions de visiteurs/an. <strong>Juillet est mon mois préféré</strong> (9.6/10) : 24-26°C, 5% de pluie, mer à 24°C, mais aussi pic absolu de la foule : ferries depuis Naples ou Sorrente bondés, prix hôteliers x4-x5 (palaces 1500-3000€/nuit). <strong>De juin à septembre</strong>, l'île voit défiler le jet-set international, paparazzi à Marina Grande au débarquement des stars. <strong>De novembre à mars</strong>, comptez 11-18°C et 32-52% de pluie : 70% des restos et hôtels ferment, ferries réduits, ambiance villageoise authentique. <strong>Sites majeurs</strong> : <strong>Grotta Azzurra</strong> (entrée en barque, lumière électrique reflétée par le calcaire blanc), <strong>Faraglioni</strong> (3 rochers signature de l'île), <strong>Villa San Michele</strong> (du Suédois Axel Munthe à Anacapri), <strong>Monte Solaro</strong> (589m, télésiège depuis Anacapri), <strong>Villa Jovis</strong> (Tibère y a vécu ses 10 dernières années). <strong>Piazzetta</strong> (Capri ville, jet-set en aperitivo). <strong>Tester</strong> insalata caprese (origine ici), ravioli capresi, torta caprese (gâteau au chocolat-amandes). <strong>Anacapri</strong> est plus calme que Capri ville. Mai et septembre-octobre sont les meilleurs compromis foule/météo.",

    "sicile:fr": "La Sicile est la plus grande île de la Méditerranée : 25 000 km², 5 millions d'habitants, 3000 ans d'histoire (Grecs, Romains, Arabes, Normands, Espagnols, Bourbons). <strong>Juin est mon mois préféré</strong> (9.4/10) : 16-30°C, 13% de pluie, températures parfaites avant la canicule. <strong>Juillet chute à 6.9/10</strong> à cause de la chaleur extrême (18-34°C, parfois 45°C dans l'intérieur). <strong>De décembre à février</strong>, comptez 2-13°C et 25-29% de pluie : doux à Palerme, frais en montagne (Etna sous la neige). <strong>Sites majeurs</strong> : <strong>Palerme</strong> (Cattedrale, Cappella Palatina, marché Vucciria), <strong>Agrigente et la Vallée des Temples</strong> (UNESCO, mieux conservés qu'en Grèce), <strong>Syracuse</strong> et Ortygia (théâtre grec utilisé tous les étés), <strong>Taormine</strong> (théâtre grec face à l'Etna et la mer), <strong>Etna</strong> (3300m, plus haut volcan actif d'Europe, accessible par 4×4 + télécabine), <strong>Cefalù</strong> (plage et cathédrale normande), <strong>Iles Éoliennes</strong> en hydrofoil (Lipari, Stromboli volcan en éruption permanente). <strong>Tester</strong> arancini, cannoli, granita, pasta alla Norma, caponata, vin Nero d'Avola, Marsala. Mai et septembre-octobre sont les vrais bons compromis tourisme/météo. Vol direct Paris-Catane ou Paris-Palerme.",

    "sardaigne:fr": "La Sardaigne, deuxième plus grande île de Méditerranée : 24 000 km², 1,6 million d'habitants. Plages parmi les plus belles d'Europe, intérieur sauvage et préservé. <strong>Juin est mon mois préféré</strong> (9.3/10) : 16-30°C, 17% de pluie, mer à 22°C, début de la haute saison. <strong>Juillet chute à 6.9/10</strong> à cause de la chaleur (20-34°C, parfois 42°C). <strong>Août</strong> reste très bon (8.6/10) mais foules massives, surtout Costa Smeralda. <strong>De décembre à février</strong>, comptez 4-14°C et 27-32% de pluie : doux mais pluvieux, beaucoup d'hôtels ferment. <strong>Sites majeurs</strong> : <strong>Costa Smeralda</strong> (créée par l'Aga Khan en 1962, jet-set, Porto Cervo), <strong>La Maddalena archipel</strong> (Caprera), <strong>Cagliari</strong> (capitale, quartier Castello), <strong>Alghero</strong> (catalano-italienne, falaises de Capo Caccia et grottes de Neptune), <strong>Bosa</strong> (village coloré), <strong>Costa Verde</strong> (sauvage), <strong>Barbagia</strong> (intérieur, traditions pastorales). <strong>Plages</strong> : Cala Goloritzé, Spiaggia di La Pelosa, Spiaggia di Tuerredda. <strong>Sentier Selvaggio Blu</strong> (l'un des plus difficiles d'Europe, 7 jours). <strong>Nuraghi</strong> (constructions mégalithiques 1500 av JC, UNESCO Su Nuraxi). <strong>Tester</strong> porceddu (cochon de lait), pane carasau, pecorino sardo, mirto. Mai et septembre-octobre sont les meilleurs compromis tourisme/météo.",

    "toscane:fr": "La Toscane, c'est l'image de l'Italie classique : collines avec cyprès, vignobles, villages perchés, Renaissance à Florence. <strong>Juin est mon mois préféré</strong> (9.2/10) : 16-29°C, 25% de pluie, paysages avant la sécheresse estivale, foules encore raisonnables. <strong>Juillet-août chutent à 6.9/10</strong> à cause de la chaleur étouffante (19-32°C, ressenti 38°C+) : Toscans qui fuient à la mer, intérieur étouffant. <strong>De décembre à février</strong>, comptez 2-13°C et 36-42% de pluie : doux pour visiter Florence, Sienne, Pise sans foule. <strong>Septembre-octobre</strong> est mon vrai bon compromis : 12-26°C, vendanges (Chianti, Brunello di Montalcino, Vino Nobile di Montepulciano), truffe blanche en novembre. <strong>Sites majeurs</strong> : <strong>Florence</strong> (UNESCO, déjà couvert), <strong>Sienne</strong> (Piazza del Campo, Palio les 2 juillet et 16 août), <strong>Pise</strong> (Tour penchée, Piazza dei Miracoli), <strong>San Gimignano</strong> (UNESCO, 14 tours médiévales), <strong>Lucques</strong> (remparts intacts), <strong>Volterra</strong> (Étrusques), <strong>Val d'Orcia</strong> (UNESCO, Pienza, Montalcino, Montepulciano). <strong>Costa Etrusca</strong> (Castiglioncello, Bolgheri pour le Sassicaia). <strong>Tester</strong> bistecca alla fiorentina, pici, ribollita, pappardelle al cinghiale, gelato. Mai et septembre-octobre sont les vrais bons compromis.",

    "lac-come:fr": "Le lac de Côme, en forme de Y inversé, 50 km de long, profondeur 410m (l'un des plus profonds d'Europe). George Clooney et villas hollywoodiennes (Bellagio surtout). <strong>Juillet-août sont mes mois préférés</strong> (8.4/10) : 21-28°C, 43-50% de pluie en orages d'après-midi, baignade dans le lac (eau à 24°C). <strong>De décembre à février</strong>, comptez 4-11°C et 24-30% de pluie : ciel souvent gris (brume sur le lac), beaucoup de villas et restos ferment. <strong>Sites majeurs</strong> : <strong>Côme</strong> (Duomo, funiculaire à Brunate pour la vue), <strong>Bellagio</strong> (perle du lac, jardins de Villa Melzi et Villa Serbelloni), <strong>Varenna</strong> (charmant village, Villa Monastero), <strong>Tremezzo</strong> (Villa Carlotta, jardins italiens), <strong>Villa del Balbianello</strong> à Lenno (utilisée dans Star Wars épisode II et James Bond Casino Royale). <strong>Bateaux Navigazione Lago di Como</strong> qui desservent tous les villages. <strong>Tester</strong> risotto al pesce persico, missoltini (poisson séché), polenta uncia, fromages locaux (Bitto). <strong>Milan</strong> à 1h en train, <strong>Suisse</strong> (Lugano) à 30 min en voiture. Mai-juin et septembre-octobre sont les meilleurs compromis foule/météo.",

    "pouilles:fr": "Les Pouilles, le talon de la botte italienne : 800 km de littoral, oliviers millénaires, trulli, baroque salentino. <strong>Juin est mon mois préféré</strong> (9.3/10) : 19-28°C, 26% de pluie, mer à 23°C, foules encore raisonnables. <strong>Juillet-août</strong> restent excellents (8.9/10) mais foules massives, prix x3, Italiens en vacances. <strong>De décembre à février</strong>, comptez 4-14°C et 29-34% de pluie : doux pour l'Italie, beaucoup d'hôtels ferment, mais c'est la saison des huiles d'olive nouvelles. <strong>Sites majeurs</strong> : <strong>Alberobello</strong> (UNESCO, 1500 trulli, maisons en pierre sèche à toit conique), <strong>Lecce</strong> (\"Florence du Sud\", baroque salentino), <strong>Polignano a Mare</strong> (perché sur falaise calcaire), <strong>Ostuni</strong> (la \"ville blanche\"), <strong>Matera</strong> (juste à côté en Basilicate, voir avis dédié), <strong>Bari</strong> (vieille ville, basilique San Nicola, fameuse pour Père Noël), <strong>Otranto</strong> et <strong>Gallipoli</strong> (côte adriatique sud). <strong>Salento</strong> et ses plages (Pescoluse \"Maldives du Salento\", Punta Prosciutto). <strong>Tester</strong> orecchiette aux cime di rapa, focaccia barese, burrata (origine ici à Andria), pasticciotto, vin Primitivo et Negroamaro. Aéroports : Bari et Brindisi, vols low-cost depuis Paris. Mai et septembre-octobre sont les vrais bons compromis.",

    "matera:fr": "Matera, capitale européenne de la culture 2019, c'est l'une des plus vieilles villes habitées au monde (9000 ans) : les <strong>Sassi</strong> (UNESCO), troglodytes creusés dans le tuf calcaire. <strong>Juin est mon mois préféré</strong> (8.7/10) : 17-29°C, 27% de pluie, lumière dorée sur les Sassi au coucher du soleil. <strong>Juillet chute à 6.9/10</strong> à cause de la chaleur (21-34°C, parfois 42°C, intérieur du sud italien). <strong>Août</strong> reste bon (8.2/10) mais chaud et foules. <strong>De novembre à mars</strong>, comptez 3-15°C et 19-32% de pluie : doux, parfait pour visiter sans foule, ambiance hivernale singulière sur les Sassi (Pasolini y avait tourné l'Évangile selon saint Matthieu en 1964 pour son aspect biblique, Mel Gibson La Passion du Christ en 2004, Mary Magdalene en 2017). <strong>Sites majeurs</strong> : <strong>Sassi di Matera</strong> (Sasso Caveoso plus authentique, Sasso Barisano restauré), <strong>Cathédrale</strong>, <strong>Casa Grotta</strong> (maison troglodyte reconstituée), <strong>Cripte rupestres</strong> (chapelles byzantines troglodytes). <strong>Belvédère Murgia Timone</strong> de l'autre côté du canyon pour la vue panoramique. <strong>Hôtels troglodytes</strong> dans les Sassi (Sextantio Le Grotte della Civita, Locanda di San Martino). <strong>Tester</strong> peperoni cruschi (poivrons séchés), pane di Matera (IGP), cavatelli, lampascioni. <strong>Bari</strong> à 1h en bus.",

    "taormina:fr": "Taormine, station balnéaire chic du nord-est de la Sicile, perchée à 200m sur la Méditerranée avec l'Etna en arrière-plan. <strong>Juin est mon mois préféré</strong> (9.5/10) : 20-27°C, 15% de pluie, mer à 23°C, théâtre antique encore ouvert pour Taormina Arte (festival musique-théâtre-cinéma juin-août). <strong>Juillet-août chutent à 6.9/10</strong> à cause de la chaleur (23-31°C) et surtout de la <strong>foule extrême</strong> : Corso Umberto I bondé, prix hôteliers x4 (la série White Lotus saison 2 tournée à San Domenico Palace en 2022 a fait exploser les prix), <strong>réservations 4-6 mois à l'avance</strong> en haute saison. <strong>De décembre à février</strong>, comptez 8-15°C et 27-32% de pluie : doux, beaucoup d'hôtels ouverts, ambiance plus paisible. <strong>Sites majeurs</strong> : <strong>Théâtre antique</strong> (IIIe siècle av JC, l'un des plus beaux du monde grec, vue Etna+mer), <strong>Corso Umberto I</strong> (rue piétonne principale), <strong>Piazza IX Aprile</strong> (terrasse panoramique), <strong>Castelmola</strong> (village perché à 30 min de marche), <strong>Isola Bella</strong> (plage avec presqu'île). <strong>Etna excursion</strong> à 1h30. <strong>Plage Mazzaro/Spisone</strong> en téléphérique depuis le centre. <strong>Tester</strong> granita di mandorla, cannoli siciliani. <strong>Catania</strong> à 1h. Mai et septembre-octobre sont les meilleurs compromis foule/météo.",

    "sierra-nevada:fr": "Sierra Nevada, c'est la station de ski la plus méridionale d'Europe et la plus haute d'Espagne : sommet Veleta 3398m, à 30 km de Grenade. <strong>Juillet est mon mois préféré</strong> (9.3/10) : 13-25°C, 13% de pluie, ciel parfait pour la randonnée vers le Mulhacén (3479m, plus haut sommet d'Espagne continentale). <strong>De décembre à mars</strong>, comptez -2/6°C et 26-45% de précipitations souvent neige : c'est la saison ski, 100 km de pistes, station moderne (Pradollano à 2100m), neige fiable grâce à l'altitude (orientation nord). Particularité : on peut <strong>skier le matin et se baigner sur la Costa del Sol l'après-midi</strong> (Granada-Malaga 1h30 de route). <strong>Avril à juin et octobre-novembre</strong> sont les intersaisons : ski qui finit (parfois jusqu'à fin avril), randonnée pas encore au point. La <strong>Coupe du Monde de ski alpin</strong> y revient régulièrement. <strong>Hors ski</strong> : trek de 3-5 jours par les Alpujarras (versant sud, villages morisques de Pampaneira, Bubión, Capileira), <strong>Mulhacén ascension</strong> (15 km aller-retour de Hoya del Portillo, juin-octobre). <strong>Tester</strong> jamón de Trevélez (séché en altitude). <strong>Granada</strong> et <strong>Malaga</strong> sont les bases logistiques. Vol direct Granada ou Malaga depuis Paris.",

    "malaga:fr": "Malaga a fait sa mue depuis 2010 : ville de transit qu'on traversait pour aller vers Marbella ou Nerja, devenue une vraie destination culturelle (<strong>Picasso est né ici</strong>, Centre Pompidou Malaga, Musée Russe, Carmen Thyssen). <strong>Juin est mon mois préféré</strong> (9.8/10) : 20-28°C, 6% de pluie, mer à 22°C. <strong>Juillet-août chutent à 6.9/10</strong> à cause de la chaleur écrasante (23-31°C, intérieur ressenti 38°C+) : les locaux vont à la plage de la Malagueta tôt le matin ou en fin de journée. <strong>De décembre à février</strong>, comptez 9-18°C et 16-21% de pluie : climat doux, idéal pour <strong>l'Alcazaba</strong> et le Castillo de Gibralfaro sans foule. Le <strong>Caminito del Rey</strong> à 1h (réservation 3-4 mois avant) reste l'attraction nature majeure. Ronda à 1h30 pour le pont fameux. Marbella à 1h, Nerja à 1h. Mai et septembre-octobre sont les vrais bons compromis. La rénovation du quartier <strong>Soho</strong> a transformé la nightlife. NOTE : avis déjà existant en doublon, voir version précédente.",

    "marbella:fr": "Marbella, c'est la station balnéaire chic de la Costa del Sol : jet-set international, marinas de luxe, golfs, soirées sur la plage de Puerto Banús. <strong>Juin est mon mois préféré</strong> (9.8/10) : 20-27°C, 3% de pluie, mer à 22°C, températures parfaites avant la canicule. <strong>Juillet-août chutent à 6.9/10</strong> à cause de la chaleur (23-30°C) et surtout de la <strong>foule</strong> : prix hôteliers x3, restos pleins, plages bondées. <strong>De décembre à février</strong>, comptez 10-17°C et 20-24% de pluie : doux pour l'Espagne, golfeurs européens présents toute l'année (50+ parcours dans la région). <strong>Sites majeurs</strong> : <strong>Casco Antiguo</strong> (vieille ville charmante avec Plaza de los Naranjos), <strong>Puerto Banús</strong> (marina jet-set, yachts à 50M€, boutiques Gucci-Prada-Cartier, restos chers), <strong>Paseo Maritimo</strong> (10 km de promenade en bord de mer), <strong>Playa de Cabopino</strong> (la plus naturelle). <strong>Soirées</strong> : Nikki Beach, Ocean Club, Olivia Valère. <strong>Excursions</strong> : Ronda à 1h, Gibraltar à 1h, Tanger en ferry depuis Algésiras (1h en voiture + 1h en ferry). <strong>Tester</strong> espetos (sardines grillées sur pic de bois sur la plage), pescaíto frito, vin de Malaga. Mai et septembre-octobre sont les meilleurs compromis foule/météo.",

    "ronda:fr": "Ronda est l'un des plus spectaculaires <strong>pueblos blancos</strong> d'Andalousie : ville perchée à 750m, traversée par le canyon de la Tajo (120m de profondeur), Puente Nuevo construit en 1793. <strong>Juin est mon mois préféré</strong> (9.8/10) : 17-28°C, 7% de pluie, températures parfaites avant la chaleur, lumière dorée sur les murailles arabes. <strong>De juillet à août</strong> restent excellents (8.7-8.8/10) avec 21-33°C : chaleur sèche supportable grâce à l'altitude (10°C de moins qu'à Séville). <strong>De décembre à février</strong>, comptez 6-15°C et 22-28% de pluie : doux en journée, frais le soir, parfait pour visiter sans foule. <strong>Sites majeurs</strong> : <strong>Puente Nuevo</strong> (vue plongeante sur la Tajo, photo signature), <strong>Plaza de Toros</strong> (1785, l'une des plus anciennes d'Espagne, école de tauromachie ronda), <strong>Casa del Rey Moro</strong> et ses jardins suspendus, <strong>Baños Árabes</strong> (bains arabes du XIIIe), <strong>Mirador de Aldehuela</strong>. <strong>Hemingway et Orson Welles</strong> y séjournaient régulièrement (la Plaza de Toros est mentionnée dans Pour qui sonne le glas, l'auteur enterré à Sun Valley). <strong>Camino de los Molinos</strong> sentier pour descendre dans la Tajo. <strong>Setenil de las Bodegas</strong> (village troglodyte) à 30 min, <strong>Grazalema</strong> et la sierra à 1h pour les randonnées. <strong>Tester</strong> rabo de toro (queue de taureau), vin de Ronda. Mai et septembre-octobre sont les vrais bons compromis tourisme/météo.",

    "minorque:fr": "Minorque, la plus calme des Baléares : 700 km², 95 000 habitants, classée Réserve de Biosphère UNESCO en 1993 (35% du territoire protégé). Plages plus sauvages qu'à Majorque ou Ibiza. <strong>Juin est mon mois préféré</strong> (9.5/10) : 20-27°C, 11% de pluie, mer à 22°C, foules encore raisonnables. <strong>Juillet-août chutent à 6.9/10</strong> à cause de la chaleur (22-30°C) et de la <strong>foule estivale</strong> : surtout Italiens et Catalans, prix hôteliers x3-x4, location de voiture difficile (réservation 3 mois avant en juillet-août). <strong>De décembre à février</strong>, comptez 9-16°C et 24-25% de pluie : doux, beaucoup d'hôtels ferment, ferries Barcelone réduits. <strong>Sites majeurs</strong> : <strong>Mahón</strong> (Maó, capitale, port naturel, l'un des plus grands du monde), <strong>Ciutadella</strong> (vieille ville charmante), <strong>Cami de Cavalls</strong> (sentier de 185 km autour de l'île, héritage des cavaliers du Moyen Âge). <strong>Calas (criques)</strong> : Cala Macarella, Cala Macarelleta, Cala Mitjana, Cala Pregonda (la plus sauvage), Cala Tortuga (accès difficile). <strong>Sites talayotiques</strong> (UNESCO 2023) : Talatí de Dalt, Trepucó (constructions mégalithiques 2000-1000 av JC). <strong>Tester</strong> caldereta de langosta (origine ici), sobrasada, queso Mahón, pomada (gin Xoriguer + citronnade). <strong>Festes de Sant Joan</strong> à Ciutadella mi-juin (chevaux qui se cabrent dans la foule). Mai et septembre-octobre sont les vrais bons compromis tourisme/météo.",

    "algarve:fr": "L'Algarve, c'est tout le sud du Portugal : 300 km de côte atlantique, falaises dorées, plages spectaculaires, golfs (l'une des destinations golf #1 d'Europe). <strong>Juillet est mon mois préféré</strong> (9.9/10) : 18-28°C, 2% de pluie, mer à 21°C (un peu fraîche), ciel constant. <strong>Août</strong> excellent (9.7/10) mais foules de Britanniques et Allemands, prix x2-x3. <strong>De décembre à février</strong>, comptez 10-17°C et 21-29% de pluie : doux, golfs en pleine activité (Européens du Nord en hivernage), beaucoup d'hôtels ouverts. <strong>Sites majeurs</strong> : <strong>Praia da Marinha</strong> (régulièrement classée meilleure plage d'Europe), <strong>Benagil cave</strong> (grotte accessible en kayak ou bateau au lever du soleil), <strong>Lagos</strong> (ville historique, plages Dona Ana et Camilo), <strong>Sagres</strong> et <strong>Cabo de São Vicente</strong> (point le plus sud-ouest de l'Europe), <strong>Faro</strong> (capitale, vieille ville, base aéroport), <strong>Tavira</strong> (plus authentique, ambiance arabe), <strong>Albufeira</strong> (touristique anglosaxon), <strong>Vilamoura</strong> (marina chic). <strong>Ria Formosa</strong> (parc naturel, lagune avec ornithologie). <strong>Tester</strong> sardines grillées, cataplana de marisco, piri-piri (chez Ramires à Guia, l'origine), pastéis de nata, vin Quinta dos Vales. Mai-juin et septembre-octobre sont les meilleurs compromis foule/météo. Vol direct Faro depuis Paris en 2h45.",

    "sintra:fr": "Sintra, classée UNESCO, c'est la station de villégiature des rois portugais : 30 min en train de Lisbonne, microclimat humide qui crée une végétation luxuriante (presque tropicale par endroits). <strong>Août est mon mois préféré</strong> (9.3/10) : 17-24°C, 4% de pluie, températures parfaites quand Lisbonne tape à 30°C+. <strong>Juillet</strong> excellent (9.2/10). <strong>De novembre à mars</strong>, comptez 8-17°C et 33-45% de pluie : très brumeux (les châteaux dans la brume sont photogéniques mais les vues panoramiques disparaissent), beaucoup d'hôtels et restos ferment. <strong>Sites majeurs</strong> : <strong>Palacio Nacional da Pena</strong> (palais romantique XIXe en couleurs criardes, le plus connu, bondé en haute saison, réservation obligatoire), <strong>Quinta da Regaleira</strong> (puits initiatique, jardins ésotériques), <strong>Castelo dos Mouros</strong> (ruines mauresques au sommet), <strong>Palacio Nacional</strong> (centre-ville), <strong>Cabo da Roca</strong> (point le plus à l'ouest de l'Europe continentale, à 30 min en bus). <strong>Logistique</strong> : prendre le train depuis Lisbonne Rossio (40 min, 2,30€), puis bus 434 entre les sites (boucle, 12€/jour). Y aller en semaine et tôt absolument (ville bondée 11h-17h). <strong>Tester</strong> travesseiros et queijadas (pâtisseries locales) chez Piriquita. <strong>Cascais</strong> et <strong>Estoril</strong> à 30 min en train pour la mer.",

    "madere:fr": "Madère, l'\"île des fleurs\" : île portugaise volcanique de l'Atlantique, à 1000 km du Portugal continental, climat subtropical doux toute l'année. <strong>Juillet-août sont mes mois préférés</strong> (9.2/10) : 19-26°C, 10-12% de pluie, mer à 22°C, températures stables. <strong>De décembre à février</strong>, comptez 13-19°C et 31-35% de pluie : le côté nord de l'île reste humide quasi toute l'année (laurisilve UNESCO), le sud (Funchal, Calheta) est nettement plus sec. <strong>Sites majeurs</strong> : <strong>Funchal</strong> (capitale, vieille ville Zona Velha, marché Mercado dos Lavradores), <strong>levadas</strong> (canaux d'irrigation aménagés en sentiers, 2500 km au total : 25 Fontes, Caldeirão Verde, Caldeirão do Inferno), <strong>Pico do Arieiro</strong> (1818m, télérandonnée 7 km vers Pico Ruivo 1862m, idéal lever de soleil au-dessus des nuages), <strong>Câmara de Lobos</strong> (village de pêcheurs immortalisé par Churchill), <strong>Cabo Girão</strong> (2e plus haute falaise d'Europe, 580m, skywalk en verre), <strong>Porto Moniz</strong> (piscines naturelles dans la lave). <strong>Téléphérique de Monte</strong> (jardins) et descente en luge en osier (carros de cesto, expérience unique). <strong>Tester</strong> espetada (brochette de bœuf), bolo do caco, poncha (rhum-citron-miel), vin de Madère (Sercial sec à Malvasia doux). Mai-juin et septembre-octobre sont les vrais bons compromis tarifs/météo. Vol direct Paris-Funchal en 4h.",

    "sao-miguel:fr": "São Miguel, la plus grande des Açores (746 km²) : île portugaise de l'Atlantique, à 1500 km de Lisbonne, paysages volcaniques verts (Hawaï européen). <strong>Juillet-août sont mes mois préférés</strong> (8.2-8.3/10) : 18-24°C, 46-48% de pluie, températures clémentes, baignade dans l'Atlantique (eau à 22°C). <strong>De décembre à mars</strong>, comptez 12-17°C et 52-56% de précipitations : pluie quasi continue (climat océanique humide), mais paysages les plus verts. Île météo capricieuse : 4 saisons en une journée possibles. <strong>Sites majeurs</strong> : <strong>Sete Cidades</strong> (cratère avec lacs vert et bleu, panorama depuis Vista do Rei ou Boca do Inferno), <strong>Lagoa do Fogo</strong> (lac dans cratère plus sauvage), <strong>Furnas</strong> (vallée volcanique avec geysers, sources thermales gratuites Poça da Dona Beija ou Terra Nostra), <strong>Cozido das Furnas</strong> (plat traditionnel cuit dans la terre volcanique, à commander la veille), <strong>Ponta Delgada</strong> (capitale), <strong>Vila Franca do Campo</strong> (atoll volcanique au large). <strong>Whale watching</strong> avril-octobre (cachalots toute l'année, baleines bleues mars-juin). <strong>Plantations de thé</strong> Gorreana (la seule plantation européenne, depuis 1883). <strong>Tester</strong> ananas des Açores, fromage São Jorge, vin de Pico, queijadas. Mai-juin et septembre-octobre sont les meilleurs compromis tourisme/météo. Vol direct Lisbonne (2h) ou Porto.",

    "acores:fr": "Les Açores, c'est l'archipel portugais de l'Atlantique : 9 îles volcaniques, paysages spectaculaires verts (collines, lacs de cratères, sources thermales). <strong>Juillet est mon mois préféré</strong> (8.0/10) : 18-23°C, 46% de pluie, températures clémentes pour les randonnées. Climat océanique = pluie possible toute l'année (très changeant). <strong>De juin à septembre</strong> est la saison plus sèche relative (45-50% de pluie). <strong>De novembre à mars</strong>, comptez 13-17°C et 52-56% de pluie : tempêtes atlantiques, mer agitée, ferries inter-îles parfois annulés. <strong>9 îles principales</strong> : São Miguel (la plus grande, voir avis dédié), <strong>Pico</strong> (le volcan 2351m, plus haut sommet du Portugal, ascension 5h aller-retour), <strong>Faial</strong> (Horta marina avec son Peter Café Sport pour les marins du monde entier), <strong>Terceira</strong> (Angra do Heroísmo UNESCO, taureaux dans les rues), <strong>São Jorge</strong> (fromage), <strong>Flores</strong> (cascades, l'une des plus belles), <strong>Corvo</strong> (la plus petite, 400 habitants), <strong>Graciosa</strong>, <strong>Santa Maria</strong> (la plus chaude). <strong>Whale watching</strong> avril-octobre (25 espèces différentes possibles). <strong>Plongée</strong> aux Açores parmi les meilleurs spots d'Atlantique (raies mantas à Princess Alice, requins). <strong>Logistique</strong> : Azores Airlines vols inter-îles obligatoires, 1 seul ferry (Atlanticoline). Comptez 10-15 jours minimum pour 3-4 îles. Vol direct Paris-Ponta Delgada (4h)."
}

with open(PATH, encoding='utf-8') as f:
    data_existing = json.load(f)

before = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

data_existing['_version'] = '1.9'
data_existing['_updated'] = '2026-04-27'

for k, v in AVIS_BATCH7_FR.items():
    data_existing[k] = v

after = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data_existing, f, ensure_ascii=False, indent=2)

print(f"Avis FR avant : {before}")
print(f"Avis FR après : {after}")
print(f"Nouveaux : {after - before}")

# Audit immédiat
import re
patterns_check = [
    ('em-dash', r'—'), ('guillemets', r'[«»]'),
    ('attendez-vous', r'attendez-vous à'),
    ('parfait', r'\bparfait[es]*\b'),
    ('fenêtre', r'\bfenêtre[s]?\b'),
    ('saturé', r'\bsatur[eéa]\w*\b'),
    ('se mérite', r'\bse méri[tes]+\b'),
    ('magique', r'\bmagiques?\b'),
    ('Si vous X:', r'Si vous \w+ : '),
    ('iconique', r'\biconique[s]?\b'),
    ('antithèse', r'antithèse'),
    ('mythique', r'\bmythique[s]?\b'),
    ('emblématique', r'\bemblématique[s]?\b'),
    ('authentique', r'\bauthentique[s]?\b'),
    ('féérique', r'\bféérique[s]?\b'),
    ("c'est aussi", r"[Cc]'est aussi"),
    ('à monitorer', r'à monitorer'),
    ('à éviter', r'à éviter'),
]

print("\n=== Audit batch 7 ===")
issues_total = 0
for slug in AVIS_BATCH7_FR.keys():
    plain = re.sub(r'<[^>]+>', '', data_existing[slug])
    issues = []
    for label, p in patterns_check:
        n = len(re.findall(p, plain))
        if n > 0:
            issues.append(f"{label}={n}")
            issues_total += n
    flag = "OK" if not issues else "PB " + ", ".join(issues)
    print(f"  {slug:<22} {len(plain.split()):>3}m {flag}")
print(f"\nTotal issues : {issues_total}")
