"""Batch 15 : 25 avis FR Tier 2 Méditerranée secondaire (6) + Asie tier 2 (19)."""
import json

PATH = 'data/avis_annuel.json'

AVIS_BATCH15_FR = {
    # === Méditerranée secondaire (6) ===
    "lagos:fr": "Lagos, dans l'Algarve portugais : 22 000 habitants, station balnéaire à l'extrême sud-ouest du Portugal. Plages de falaises calcaires sculptées (les plus connues du Portugal), grottes marines (Ponta da Piedade), atmosphère plus authentique que les stations bétonnées de l'Algarve central (Albufeira, Vilamoura). <strong>Août est mon mois préféré</strong> (6.9/10) : 24-28°C, 71% de pluie. Lagos ne dépasse jamais 6.9/10 (climat océanique tempéré, plus humide que les Canaries voisines). <strong>De juin à septembre</strong>, c'est la haute saison touristique : 24-30°C, mer à 21°C (fraîche, courant Atlantique), prix hôteliers x2-x3, plages bondées. <strong>De novembre à mars</strong>, comptez 25-32°C et 18-60% de pluie : doux pour le Portugal, snowbirds européens en hivernage (golfs ouverts toute l'année). <strong>Sites majeurs</strong> : <strong>Ponta da Piedade</strong> (signature de Lagos, falaises et grottes accessibles en bateau ou kayak depuis le port, 30 min de promenade côtière depuis le centre), <strong>Praia Dona Ana</strong> (l'une des plus belles plages du Portugal selon de nombreux classements), <strong>Praia do Camilo</strong> (200 marches à descendre), <strong>Praia do Pinhão</strong>, <strong>Meia Praia</strong> (longue plage de 4 km à l'est, plus calme), <strong>Vieille ville fortifiée</strong> (XVIe, Mercado Municipal, Igreja de Santa Maria, Forte da Ponta da Bandeira), <strong>Cape Saint-Vincent</strong> à 40 min (extrême sud-ouest de l'Europe continentale, phare, falaises 75m). <strong>Sagres</strong> à 35 min (cap de l'École de Navigation d'Henri le Navigateur, surf, ambiance bohème). <strong>Tester</strong> cataplana de marisco (cassolette de fruits de mer), bacalhau à brás, pastéis de nata, vins Algarve (rouges Negra Mole), ginja (liqueur de cerises). <strong>Logistique</strong> : Lagos à 1h de Faro (aéroport principal de l'Algarve), 4h de Lisbonne en train ou bus.",

    "zadar:fr": "Zadar, ville de Croatie en Dalmatie nord : 75 000 habitants sur la côte adriatique. Souvent négligée au profit de Split ou Dubrovnik, mais à la fois plus authentique et stratégiquement placée pour visiter les <strong>Plitvice National Park</strong> (1h30) et les <strong>îles Kornati</strong> (140 îles archipel rocheux). <strong>Juin est mon mois préféré</strong> (9.4/10) : 19-27°C, 18% de pluie, mer à 22°C, lumière dorée sur la Riva. <strong>Juillet-août chutent à 6.9/10</strong> à cause de la chaleur (21-30°C) et de la foule estivale (Italiens et Allemands en majorité, prix hôteliers x3). <strong>De novembre à mars</strong>, comptez 3-13°C et 30-45% de pluie : doux pour la Croatie, beaucoup d'établissements ferment hors saison. <strong>Sites majeurs</strong> : <strong>Vieille ville</strong> sur péninsule, riche héritage romain (Forum romain Ier siècle, plus grand des Balkans) et vénitien (Tour de l'Horloge, Porte de la Terre Ferme), <strong>Cathédrale Sainte-Anastasie</strong> (XIIIe), <strong>Église Saint-Donat</strong> (IXe romane préromane, l'une des plus anciennes de Croatie), <strong>Sea Organ</strong> (\"Orgue de la Mer\", installation acoustique 2005 de l'architecte Nikola Bašić : 35 tubes sous la promenade émettent des sons sous l'effet des vagues, à écouter au coucher du soleil), <strong>Greeting to the Sun</strong> (à côté de la Sea Organ, disque de 22m de panneaux solaires qui s'illumine la nuit), <strong>Riva</strong> (promenade en bord de mer, l'un des plus beaux coucher de soleil au monde selon Alfred Hitchcock qui y séjournait dans les années 60). <strong>Excursions</strong> : <strong>Plitvice National Park</strong> à 1h30, <strong>Krka National Park</strong> à 1h (cascades, baignade autorisée), <strong>Iles Kornati</strong> en bateau (140 îles dans un parc national maritime). <strong>Tester</strong> pasticada (boeuf à la croate), peka, vins Skradin. Aéroport direct depuis Paris (Ryanair).",

    "budva:fr": "Budva, station balnéaire monténégrine : 14 000 habitants sur la côte adriatique, surnommée la \"Saint-Tropez monténégrine\" pour son ambiance party-chic, à 30 min de Kotor. <strong>Juin est mon mois préféré</strong> (9.1/10) : 21-27°C, 29% de pluie, mer à 22°C, températures idéales avant la canicule. <strong>Juillet-août chutent à 6.9/10</strong> à cause de la chaleur (23-30°C) et de la <strong>foule extrême</strong> (Russes et Ukrainiens en majorité historiquement, plus de Serbes et Allemands aujourd'hui, prix hôteliers x4-x5, plages bondées, vie nocturne intense type Bay 42 et Top Hill). <strong>De novembre à mars</strong>, comptez 5-13°C et 41-49% de pluie : doux pour les Balkans, beaucoup d'hôtels ferment hors saison. <strong>Sites majeurs</strong> : <strong>Stari Grad</strong> (vieille ville fortifiée vénitienne XVe, dédale de ruelles pavées, citadelle, cathédrale Saint-Jean), <strong>Plage Mogren I et II</strong> (sous les remparts, l'une des plus belles plages de la côte monténégrine), <strong>Slovenska plaža</strong> (la plus grande plage de Budva, 1,6 km, animée), <strong>Statue de la Ballerine</strong> (Mogren). <strong>Sveti Stefan</strong> à 5 km (île-village fortifié XVe transformée en hôtel 5*+ par Aman Resorts depuis 2009, photo signature du Monténégro mais hôtel fermé depuis 2021 pour litiges, accès aux remparts payant uniquement, plage de Sveti Stefan publique et magnifique). <strong>Excursions</strong> : <strong>Kotor</strong> à 30 min (UNESCO, baie spectaculaire), <strong>Lovćen National Park</strong> à 1h (mausolée Petar II Petrović-Njegoš au sommet 1660m, 461 marches), <strong>Cetinje</strong> à 45 min (ancienne capitale royale du Monténégro). <strong>Tester</strong> pršut (jambon fumé), kačamak, raki monténégrin. Aéroport Tivat (15 min).",

    "ravello:fr": "Ravello, perché sur les hauteurs de la <strong>Côte amalfitaine</strong> en Italie : 2400 habitants à 365m d'altitude au-dessus de la Méditerranée. Vue panoramique exceptionnelle sur la côte, refuge des aristocrates européens depuis le XIXe siècle (Wagner, Greta Garbo, Jacqueline Kennedy y ont séjourné). <strong>Juillet-août sont mes mois préférés</strong> (9.1-9.4/10) : 18-29°C, 15-22% de pluie, mer à 25°C en bas (300m de descente), température clémente en altitude (5°C de moins qu'en bord de mer Amalfi). <strong>De juin à septembre</strong>, c'est la haute saison touristique : 13-29°C, mais aussi prix hôteliers x4-x5 (Ravello est l'un des villages les plus chic d'Italie, hôtels 5*+ Belmond Caruso ou Palazzo Avino à 800-3000€/nuit), réservation 6 mois avant. <strong>De novembre à mars</strong>, comptez 4-17°C : doux pour l'altitude, beaucoup d'hôtels ferment, climat venté. <strong>Sites majeurs</strong> : <strong>Villa Rufolo</strong> (XIIIe, jardins suspendus avec vue panoramique signature sur la côte, Wagner s'y est inspiré pour Parsifal en 1880, festival musique classique en plein air <strong>Ravello Festival</strong> juin-septembre), <strong>Villa Cimbrone</strong> (XIIe, plus haute et plus spectaculaire, <strong>Terrazza dell'Infinito</strong> = panorama unique avec bustes en pierre face à la mer), <strong>Duomo di Ravello</strong> (XIe, mosaïques, ambon), <strong>Centro storico</strong> (Piazza Duomo, ruelles à pied, escaliers vers Atrani et Amalfi 30-45 min de descente). <strong>Côte amalfitaine</strong> : <strong>Amalfi</strong> en bus 15 min (Duomo Sant'Andrea, Pontone), <strong>Positano</strong> à 30 min (village pastel sur falaise), <strong>Capri</strong> à 1h en hydrofoil. <strong>Tester</strong> limoncello (production locale, vergers de citrons d'Amalfi), pasta con vongole, fior di latte mozzarella, vin de la côte (Costa d'Amalfi DOC). <strong>Logistique</strong> : Ravello à 1h30 de Naples en bus (parking obligatoire, accès piéton seulement).",

    "procida:fr": "Procida, la plus petite des trois <strong>îles du golfe de Naples</strong> (Procida, Ischia, Capri) : 4 km², 10 000 habitants, île de pêcheurs préservée du tourisme de masse, maisons pastel typiques de la Marina Corricella. <strong>Capitale italienne de la Culture 2022</strong> (la première fois qu'une île reçoit ce titre). <strong>Juillet est mon mois préféré</strong> (9.4/10) : 23-29°C, 8% de pluie, mer à 24°C, températures idéales. <strong>D'août</strong> reste excellent (9.1/10). <strong>De juin à septembre</strong>, c'est la haute saison touristique : 20-29°C, mais Procida reste beaucoup moins fréquentée que Capri ou Ischia (touristes italiens en majorité, weekenders napolitains, peu d'étrangers), prix hôteliers x2-x3. <strong>De novembre à mars</strong>, comptez 8-15°C et 30-48% de pluie : doux pour la Méditerranée, beaucoup d'hôtels ferment, île presque déserte (4000 habitants permanents). <strong>Sites majeurs</strong> : <strong>Marina Corricella</strong> (port de pêche emblématique, maisons pastel rose-jaune-bleu, l'une des images-cartes postales les plus connues d'Italie, popularisé par <em>Le Talentueux Mr Ripley</em> 1999 et <em>Il Postino</em> 1994), <strong>Terra Murata</strong> (citadelle médiévale au point culminant 91m, vue panoramique), <strong>Abbaye de San Michele Arcangelo</strong>, <strong>Marina Grande</strong> (port d'arrivée des ferries depuis Naples), <strong>Plage Chiaiolella</strong> (la plus connue, sable noir volcanique), <strong>Plage du Pozzo Vecchio</strong> (\"Postino Beach\" où Massimo Troisi tournait le film). <strong>Excursions</strong> : <strong>Vivara</strong> (îlot relié par pont, réserve naturelle), <strong>Ischia</strong> à 25 min en ferry (sources thermales). <strong>Tester</strong> spaghetti alle vongole, lemon cake (citrons procidans, plus petits qu'Amalfi), insalata di limoni (oui, salade de citrons procidans pelés). <strong>Logistique</strong> : Procida à 1h de Naples en ferry (départs port Beverello), 25 min en hydrofoil. Pas de voiture nécessaire (île traversable à pied 1h).",

    "ischia:fr": "Ischia, la plus grande des trois <strong>îles du golfe de Naples</strong> : 46 km², 65 000 habitants, île volcanique encore active (dernière éruption 1302), réputée pour ses <strong>sources thermales</strong> (les Romains s'y rendaient déjà au Ier siècle av JC). <strong>Juillet est mon mois préféré</strong> (9.2/10) : 20-24°C, 7% de pluie, mer à 24°C. <strong>D'août</strong> reste excellent (9.0/10). <strong>De juin à septembre</strong>, c'est la haute saison touristique : 17-24°C, prix hôteliers x3-x4, ferries surchargés. <strong>De novembre à mars</strong>, comptez 5-11°C et 29-47% de pluie : doux pour la Méditerranée, beaucoup d'hôtels ferment mais les centres thermaux principaux restent ouverts (Negombo, Castiglione, Poseidon). <strong>Sites majeurs</strong> : <strong>Castello Aragonese</strong> (sur îlot relié par pont, panorama signature, accès payant, 1 km de visite), <strong>Mont Epomeo</strong> (789m, point culminant, randonnée 2h aller-retour, panorama 360° golfe de Naples-Vésuve-Capri), <strong>Sant'Angelo</strong> (village de pêcheurs piéton à l'extrême sud, plage chaude où l'on peut creuser dans le sable et trouver de l'eau bouillante), <strong>Giardini La Mortella</strong> (jardin botanique du compositeur William Walton), <strong>Forio</strong> (ville principale ouest), <strong>Lacco Ameno</strong> (\"Fungo\" champignon de pierre signature). <strong>Centres thermaux célèbres</strong> : <strong>Negombo</strong> (le plus chic, jardins japonais), <strong>Castiglione</strong> (face au Castello), <strong>Poseidon</strong> (le plus grand, 22 piscines en terrasses sur Citara), <strong>Aphrodite Apollon</strong> à Sant'Angelo. <strong>Plages</strong> : Sant'Angelo, Maronti (la plus longue), Citara (avec Poseidon). <strong>Tester</strong> coniglio all'ischitana (lapin à la Ischia, plat traditionnel), bucatini alle olive, vins blancs Biancolella et Forastera (cépages autochtones). <strong>Logistique</strong> : Ischia à 1h en ferry depuis Naples (port Beverello), 50 min en hydrofoil.",

    # === Asie tier 2 (19) ===
    "yangon:fr": "Yangon (ex-Rangoon), ancienne capitale du <strong>Myanmar</strong> (Birmanie) : 5 millions d'habitants, déclassée comme capitale en 2005 quand Naypyidaw a été créée artificiellement (capitale administrative à 320 km au nord). Yangon reste la capitale économique et culturelle du pays. Marquée par le coup d'État militaire de février 2021 (ère sombre, sanctions internationales, conseiller voyage déconseillé). <strong>De novembre à février</strong> sont mes mois préférés (6.9/10) : 20-32°C, 5-30% de pluie, c'est la saison sèche idéale. Le Myanmar ne dépasse jamais 6.9/10 (climat tropical chaud). <strong>De mars à mai</strong>, c'est la canicule pré-mousson : 23-38°C (parfois 42°C), impossible de visiter en milieu de journée. <strong>De juin à octobre</strong>, c'est la mousson : 68-99% de précipitations, inondations possibles, taux d'humidité oppressant. <strong>Sites majeurs</strong> : <strong>Pagode Shwedagon</strong> (la signature spirituelle du Myanmar, stupa doré 99m recouvert de 60 tonnes d'or et 4500 diamants au sommet, vu de loin scintille au coucher du soleil, accès aux étrangers 5$ + obligation de retirer chaussures et vêtements jambes/épaules nues), <strong>Pagode Sule</strong> (au cœur du centre-ville, point repère cardinal), <strong>Marché Bogyoke Aung San</strong> (Scott Market, héritage colonial britannique 1926), <strong>Quartier colonial</strong> (architecture britannique XIXe-XXe en délabrement chic), <strong>Lac Inya</strong> et <strong>Lac Kandawgyi</strong> (parcs publics), <strong>Pagode Botataung</strong> (en bord de fleuve). <strong>Excursions</strong> majeures du Myanmar : <strong>Bagan</strong> en avion 1h (3000 stupas et temples sur la plaine, montgolfière au lever du soleil), <strong>Mandalay</strong> en avion 1h, <strong>Lac Inle</strong> (pêcheurs Intha à une seule jambe). <strong>Important</strong> : situation politique instable depuis le coup d'État militaire de février 2021. Beaucoup de pays déconseillent les voyages.",

    "vientiane:fr": "Vientiane, capitale du <strong>Laos</strong> : 950 000 habitants sur le Mékong en bordure de la Thaïlande (le pont de l'Amitié relie Vientiane à Nong Khai côté thaïlandais en 20 min). L'une des capitales les plus calmes et bohèmes d'Asie du Sud-Est, héritage colonial français très présent (architecture, baguette quotidienne, café au lait). <strong>Janvier est mon mois préféré</strong> (9.3/10) : 18-28°C, 7% de pluie, fin de la saison sèche, températures idéales. <strong>Décembre</strong> reste excellent (9.3/10). <strong>De novembre à février</strong>, c'est la saison sèche : 18-32°C, climat sec et frais le matin (parfois 12°C en décembre, frais surprenant pour l'Asie tropicale). <strong>De mars à mai</strong>, c'est la canicule pré-mousson : 25-34°C (parfois 40°C), brumes de brûlis agricoles polluent l'atmosphère du nord du Laos. <strong>De juin à octobre</strong>, c'est la mousson : 47-89% de précipitations, mais températures plus supportables (23-31°C). <strong>Sites majeurs</strong> : <strong>Pha That Luang</strong> (signature nationale, stupa doré XVIe, le monument le plus sacré du Laos), <strong>Patuxai</strong> (\"Arc de Triomphe laotien\", ressemble à celui de Paris construit avec ciment américain prévu pour aéroport en 1968), <strong>Wat Si Saket</strong> (XIXe, le plus vieux temple subsistant après le pillage siamois 1828, 6800 statues de Bouddha), <strong>Wat Sisaket</strong> et <strong>Wat Ho Phra Kaew</strong> (lieux historiques), <strong>COPE Visitor Center</strong> (mémorial poignant sur les UXO bombes à sous-munitions encore présentes 50 ans après la guerre, le Laos a reçu plus de bombes US que toute la Seconde Guerre mondiale combinée). <strong>Marché du soir Vientiane Night Market</strong> (sur les berges du Mékong, coucher du soleil, street food, artisanat). <strong>Excursions</strong> : <strong>Buddha Park (Xieng Khuan)</strong> à 25 km (200 statues bouddhistes et hindouistes éclectiques 1958), <strong>Vang Vieng</strong> à 4h en bus (paysages karstiques, tubing). <strong>Tester</strong> laap (salade de viande hachée), sticky rice, papaya salad (tam mak hoong), Beer Lao (la fierté nationale, 90% du marché bière au Laos).",

    "manille:fr": "Manille, capitale des <strong>Philippines</strong> : 14 millions d'habitants en aire urbaine (Metro Manila), mégapole asiatique chaotique mélangeant héritage espagnol (1565-1898), américain (1898-1946) et asiatique. Probablement l'une des capitales les plus polluées et embouteillées d'Asie. <strong>Janvier est mon mois préféré</strong> (8.3/10) : 23-29°C, 35% de pluie, fin de la saison sèche. <strong>De décembre à février</strong>, c'est la haute saison touristique : 23-30°C, climat sec relatif. <strong>De mars à mai</strong>, c'est la canicule pré-mousson : 24-34°C, taux d'humidité oppressant (souvent 90%+). <strong>De juin à novembre</strong>, c'est la saison cyclonique active (les Philippines reçoivent en moyenne 20 typhons par saison) : 53-92% de précipitations, inondations urbaines régulières. <strong>Sites majeurs</strong> : <strong>Intramuros</strong> (vieille ville espagnole fortifiée XVIe, en grande partie détruite WWII, partiellement reconstruite : Fort Santiago avec cellule où José Rizal a été emprisonné avant son exécution 1896, Cathédrale, San Agustín Church UNESCO la plus vieille église des Philippines 1607), <strong>Rizal Park</strong>, <strong>National Museum</strong> (Spoliarium de Juan Luna), <strong>Manila Cathedral</strong>, <strong>Quartier Binondo</strong> (le plus vieux Chinatown au monde, fondé 1594), <strong>Makati</strong> et <strong>BGC (Bonifacio Global City)</strong> = quartiers d'affaires modernes (gratte-ciel, malls, restos), <strong>Quezon City</strong> (universitaire). <strong>Sécurité</strong> : Manille demande vigilance (vols à l'arraché, scams), zones touristiques surveillées mais arrière-pays risqué pour Européens (kidnappings dans le Sud Mindanao notamment). <strong>Excursions</strong> : <strong>Tagaytay</strong> à 2h (volcan Taal en bord de lac), <strong>Pampanga</strong> (capitale culinaire). <strong>Manille = base de transit</strong> pour les îles : Cebu (1h en avion, plages), Palawan (Coron, El Nido = parmi les plus belles eaux turquoise du monde), Bohol (Chocolate Hills, tarsiers). <strong>Tester</strong> adobo, sinigang, lechon (cochon de lait rôti), halo-halo (dessert glacé). Vol direct Paris-Manille en 14h via Doha ou Dubai.",

    "cebu:fr": "Cebu, capitale de la <strong>région des Visayas</strong> aux Philippines : 1 million d'habitants (3 millions en aire urbaine), 2e plus grande ville des Philippines après Manille, ancienne capitale coloniale espagnole (Magellan y est arrivé en 1521 avant d'être tué quelques semaines plus tard à Mactan voisine). Base pour explorer les <strong>plus belles îles des Philippines</strong> (Bohol, Siquijor, Camotes, Malapascua). <strong>Janvier est mon mois préféré</strong> (6.9/10) : 24-28°C, 70% de pluie. Cebu ne dépasse jamais 6.9/10 (climat tropical équatorial humide). <strong>De décembre à mai</strong>, c'est la saison la plus sèche relative : 24-30°C, 50-70% de pluie, c'est la haute saison touristique. <strong>De juin à novembre</strong>, c'est la saison plus pluvieuse : 83-94% de précipitations, mais températures stables (25-30°C), risque cyclonique réel (les Visayas ont été dévastées par <strong>Yolanda/Haiyan</strong> en novembre 2013, 6300 morts). <strong>Sites majeurs Cebu City</strong> : <strong>Magellan's Cross</strong> (croix érigée par Magellan en 1521, première célébration chrétienne aux Philippines), <strong>Basilica del Santo Niño</strong> (la plus vieille église des Philippines, XVIe), <strong>Fort San Pedro</strong> (espagnol XVIIe), <strong>Temple Taoïste</strong>, <strong>Tops Lookout</strong> (vue panoramique). <strong>Excursions Cebu</strong> : <strong>Kawasan Falls</strong> au sud (canyoneering aventureux), <strong>Moalboal</strong> (sardine run, plongée), <strong>Oslob</strong> (whale shark watching, controverse éthique car requins-baleines nourris pour rester sur place), <strong>Bantayan Island</strong> au nord. <strong>Iles voisines en ferry</strong> : <strong>Bohol</strong> (Chocolate Hills, tarsiers, plage Alona à Panglao), <strong>Siquijor</strong> (île mystique des sorciers blancs, plages turquoise), <strong>Camotes Islands</strong>, <strong>Malapascua</strong> (plongée requins-renards à thresher sharks). <strong>Tester</strong> lechon de Cebu (le meilleur cochon de lait rôti des Philippines selon Anthony Bourdain), kinilaw (ceviche), puso (riz cuit en feuilles tressées). Vol direct Cebu depuis Doha/Singapour (escale obligatoire depuis Europe).",

    "da-nang:fr": "Da Nang, 4e ville du <strong>Vietnam</strong> : 1,1 million d'habitants sur la côte centrale, base touristique entre Hué (1h30 au nord) et Hoi An (45 min au sud). Plage <strong>My Khe</strong> 30 km le long de la ville (réputée par les soldats américains pendant la guerre 1965-1973 = \"China Beach\"). <strong>Février est mon mois préféré</strong> (7.9/10) : 20-24°C, 49% de pluie, températures idéales avant la chaleur estivale. <strong>De janvier à mars</strong>, c'est la saison sèche : 20-27°C, 33-65% de pluie, période la plus agréable. <strong>D'avril à août</strong>, comptez 25-34°C : chaleur croissante, pic en juillet (27-33°C), mais c'est aussi la haute saison touristique pour la baignade (mer à 27-29°C). <strong>De septembre à novembre</strong>, c'est la saison des typhons : 74-86% de précipitations, risque ouragans réel sur la côte centrale du Vietnam. <strong>Sites majeurs</strong> : <strong>Pont du Dragon</strong> (Cầu Rồng, ouvert 2013, 666m de long, dragon doré qui crache feu et eau le samedi/dimanche soir 21h), <strong>Marble Mountains</strong> (Ngũ Hành Sơn, 5 collines de marbre avec grottes-temples bouddhistes, Da Nang était la capitale du Champa empire IIe-XVe), <strong>Bà Nà Hills</strong> à 30 min (téléphérique le plus long au monde 5,8 km vers village français reconstitué + le fameux <strong>Golden Bridge</strong> soutenu par 2 mains géantes ouvert 2018, photo virale Instagram), <strong>Cathédrale Da Nang</strong> (\"Coq Cathédrale\" rose), <strong>Cham Museum</strong> (la plus grande collection au monde d'art Cham). <strong>Excursions majeures</strong> : <strong>Hoi An</strong> à 45 min (UNESCO, ville portuaire ancienne avec lanternes en soie, tailleurs sur mesure), <strong>Hué</strong> à 1h30 (UNESCO, ancienne capitale impériale Nguyen 1802-1945), <strong>My Son</strong> (UNESCO, ruines hindoues Cham IVe-XIIIe). <strong>Tester</strong> mì quảng (nouilles régionales), bún chả cá (soupe de poisson), bánh tráng cuốn thịt heo (rouleaux). Da Nang reçoit des vols directs depuis plusieurs villes asiatiques.",

    "hue:fr": "Hué, ancienne capitale impériale du <strong>Vietnam</strong> sous la dynastie Nguyen (1802-1945) : 350 000 habitants sur la <strong>Rivière des Parfums</strong>, classée UNESCO depuis 1993 pour son ensemble monumental de la Cité Impériale. <strong>Mars est mon mois préféré</strong> (8.6/10) : 22-28°C, 32% de pluie, températures idéales avant la chaleur estivale. <strong>De janvier à avril</strong>, c'est la saison la plus agréable : 18-31°C, 26-53% de pluie. <strong>De mai à août</strong>, comptez 25-35°C : chaleur étouffante (parfois 38°C avec humidité), saison sèche mais inconfortable. <strong>De septembre à décembre</strong>, c'est la saison des typhons et de la mousson : 75-82% de précipitations, inondations régulières (Hué est l'une des villes vietnamiennes les plus touchées par les inondations chroniques). <strong>Sites majeurs</strong> : <strong>Cité Impériale</strong> (UNESCO, copie inspirée de la Cité Interdite de Pékin, palais Cung An Định, Porte du Midi Ngọ Môn, partiellement détruite Tet 1968 lors de la bataille de Hué pendant la guerre du Vietnam, restauration en cours depuis 1993), <strong>Tombeaux royaux des empereurs Nguyen</strong> (7 tombes monumentales dans la campagne autour de Hué, à voir : <strong>Tombeau de Tu Duc</strong> le plus grand et le plus poétique, <strong>Tombeau de Khai Dinh</strong> mélange occidental-asiatique du XXe, <strong>Tombeau de Minh Mang</strong> classique chinois), <strong>Pagode Thien Mu</strong> (icône à 7 étages au bord de la Rivière des Parfums, bonze Thich Quang Duc s'est immolé en 1963 partis depuis ici), <strong>Marché Dong Ba</strong>, <strong>Citadelle</strong>. <strong>Excursions</strong> : <strong>DMZ</strong> (zone démilitarisée à 100 km au nord, ancien tunnel Vinh Moc, base américaine Khe Sanh, Hamburger Hill = sites mémoriels guerre du Vietnam). <strong>Tester</strong> bún bò Huế (soupe nouilles boeuf épicée, plat signature local), bánh khoái (crêpe), nem lui (brochettes), bia hơi (bière fraîche pression). Aéroport Phu Bai (15 km), vols directs depuis Hanoi/Saigon.",

    "sapa:fr": "Sapa, station de montagne du <strong>nord du Vietnam</strong> : 9000 habitants à 1500m d'altitude dans les <strong>Alpes Tonkinoises</strong>, base pour les célèbres <strong>rizières en terrasses</strong> de Mường Hoa et le <strong>mont Fansipan</strong> (3143m, le \"Toit de l'Indochine\"). Importante population minoritaire (Hmong noirs, Dzao rouges, Tay), marchés ethniques. <strong>Avril est mon mois préféré</strong> (7.6/10) : 15-22°C, 59% de pluie, ciel dégagé, températures clémentes en montagne. <strong>De mars à mai</strong>, c'est la haute saison touristique : 12-23°C, ciel souvent dégagé, rizières au stade pousse verte fluorescente. <strong>De septembre à novembre</strong> est la 2e haute saison : 12-22°C, ciel dégagé, <strong>rizières en or pré-récolte</strong> (les fameuses photos avec dégradés jaunes). <strong>De juin à août</strong>, c'est la saison des pluies : 78-95% de précipitations, brouillard fréquent qui cache la vue, mais paysages les plus verdoyants. <strong>De décembre à février</strong>, comptez 8-17°C : froid pour le Vietnam, possibilité de neige rare au sommet du Fansipan. <strong>Sites majeurs</strong> : <strong>Mường Hoa Valley</strong> (rizières en terrasses spectaculaires sur 5-10 niveaux, randonnée Cat Cat → Lao Chai → Ta Van 12 km à pied), <strong>Mont Fansipan</strong> (téléphérique ouvert 2016, 6283m de câble, 15 min depuis Sapa, contre 2-3 jours de trek autrefois), <strong>Marché de Bac Ha</strong> (le dimanche, à 2h de Sapa, l'un des plus colorés du nord Vietnam, minorités Hmong fleuris). <strong>Trek</strong> avec guide local (jeune femme Hmong généralement) dans les villages : Cat Cat (Hmong noir), Ta Phin (Dzao rouge), Lao Chai (Hmong noir), Ta Van (Giay). Nuit chez l'habitant possible (homestay 10-25€/nuit avec repas). <strong>Tester</strong> thắng cố (soupe traditionnelle Hmong à base d'organes), cá hồi (truite), légumes frais d'altitude, alcool de riz local (rượu cần). <strong>Logistique</strong> : Sapa à 6h en bus de Hanoi via l'autoroute, ou train de nuit jusqu'à Lao Cai + bus 1h.",

    "mandalay:fr": "Mandalay, 2e ville du <strong>Myanmar</strong> (Birmanie) : 1,2 million d'habitants, dernière capitale royale birmane (1857-1885 avant la conquête britannique). Centre culturel, religieux et artistique du pays (60% des moines bouddhistes du Myanmar y sont concentrés). <strong>Janvier est mon mois préféré</strong> (9.3/10) : 17-28°C, 6% de pluie, fin de la saison sèche, températures idéales. <strong>Décembre</strong> reste excellent (9.3/10). <strong>De novembre à février</strong>, c'est la saison sèche idéale : 17-30°C, 2-19% de pluie. <strong>D'avril à septembre chutent à 3.8-5.2/10</strong> à cause de la canicule extrême (26-38°C, parfois 45°C dans la plaine sèche centrale, l'une des régions les plus chaudes d'Asie du Sud-Est). <strong>De mai à octobre</strong>, c'est la mousson : 47-82% de précipitations, mais Mandalay reçoit relativement peu de pluie (en zone d'ombre pluviométrique). <strong>Sites majeurs</strong> : <strong>Palais royal de Mandalay</strong> (vaste enceinte fortifiée 4 km², palais de teck reconstruit après destruction WWII, douves), <strong>Mandalay Hill</strong> (240m, 1729 marches couvertes, panorama signature au coucher du soleil sur la ville et le fleuve Irrawaddy), <strong>Pagode Kuthodaw</strong> (\"le plus grand livre du monde\" : 729 stupas blancs renfermant chacun une dalle gravée du Tipitaka canon bouddhiste), <strong>Pagode Mahamuni</strong> (statue de Bouddha recouverte de feuilles d'or par les fidèles depuis 200 ans, devenue informe), <strong>Monastère Shwenandaw</strong> (entièrement en teck sculpté, le seul vestige du palais original sauvé du bombardement de 1945), <strong>Pont U Bein</strong> à Amarapura (1,2 km, le plus long pont en teck au monde, magique au coucher du soleil), <strong>Sagaing Hill</strong> (600 stupas et monastères sur les collines en face). <strong>Excursions vers les anciennes capitales</strong> : Inwa (Ava), Sagaing, Mingun (gigantesque pagode inachevée 1790), <strong>Bagan</strong> à 4h en bateau ou 5h en bus (3000 stupas, montgolfière). <strong>Tester</strong> mohinga (soupe nouilles poisson), tea leaf salad. <strong>Important</strong> : situation politique instable depuis le coup d'État militaire de février 2021.",

    "battambang:fr": "Battambang, 2e ville du <strong>Cambodge</strong> : 250 000 habitants sur la rivière Sangker au cœur de la \"ceinture rizicole\" cambodgienne. Souvent négligée par les touristes au profit de Siem Reap (Angkor) ou Phnom Penh, c'est pourtant la ville cambodgienne où l'<strong>héritage colonial français</strong> est le mieux préservé (architecture années 1920-30 le long du fleuve). <strong>Janvier-février sont mes mois préférés</strong> (6.9/10) : 22-34°C, 10-15% de pluie, c'est la saison sèche idéale. Battambang ne dépasse jamais 6.9/10 (climat tropical chaud). <strong>De novembre à mars</strong>, c'est la haute saison touristique : 22-35°C, climat sec, températures supportables le matin et le soir. <strong>De mars à mai</strong>, c'est la canicule pré-mousson : 25-35°C (parfois 40°C), impossible de visiter en milieu de journée. <strong>De mai à octobre</strong>, c'est la mousson : 63-89% de précipitations, mais températures plus clémentes (24-34°C). <strong>Sites majeurs</strong> : <strong>Bamboo Train</strong> (\"Norry\", plateformes en bambou sur les voies ferrées rouillées, propulsées par un moteur 8 ch, vitesse 30 km/h, 7 km de balade dans les rizières et villages, 5$/personne, expérience unique au monde), <strong>Phare Sampov</strong> à 12 km (colline avec temple, <strong>Killing Caves</strong> mémorial des massacres khmers rouges 1975-1979), <strong>Battambang Bat Cave</strong> (à proximité de Phnom Sampeau, sortie de millions de chauves-souris chaque soir 18h, spectacle de 30 min en filée noire continue, gratuit), <strong>Wat Banan</strong> à 25 km (temple angkorien XIe siècle, prefiguration mini Angkor), <strong>Temples Wat Kor</strong> (à pied dans la ville). <strong>Phare Asia</strong> et architecture coloniale française du centre-ville. <strong>Phnom Penh</strong> à 5h en bus, <strong>Siem Reap</strong> à 4h en bus (Angkor). <strong>Tester</strong> amok (curry de poisson), beef lok lak, num pang sandwich (héritage français), bia angkor.",

    "guilin:fr": "Guilin, ville de la <strong>province du Guangxi</strong> en Chine : 760 000 habitants, paysages karstiques uniques (pitons calcaires sortant de la rivière Li), considérée parmi les plus belles régions de Chine selon les anciens (\"Guilin shanshui jia tianxia\" = \"Les paysages de Guilin sont les plus beaux du monde\"). <strong>Octobre est mon mois préféré</strong> (8.6/10) : 18-26°C, 25% de pluie, températures idéales avant l'hiver. <strong>De septembre à novembre</strong>, c'est la haute saison touristique : 13-31°C, climat sec idéal, vendanges des orangeraies. <strong>De juin à août</strong>, comptez 24-32°C avec 62-84% de pluie : haute saison estivale chinoise (foule maximale, prix x2-x3, sentiers en montagne saturés), mais aussi paysages les plus verts et brumeux. <strong>De décembre à février</strong>, comptez 6-16°C et 28-55% de pluie : froid humide, peu de touristes mais paysages mystiques avec brumes basses. <strong>Sites majeurs</strong> : <strong>Croisière sur la Rivière Li</strong> (Lijiang, de Guilin à <strong>Yangshuo</strong> à 1h en bus puis 4-5h de croisière, 80 km de paysages karstiques signatures du paysage chinois traditionnel - ce sont ces paysages qui figurent sur les billets de 20 yuans), <strong>Yangshuo</strong> (village touristique au sud, vélo dans les rizières, escalade sur les pitons karstiques, light show sur la rivière Li avec 600 figurants chorégraphié par Zhang Yimou), <strong>Longji Rice Terraces</strong> à 2h (\"Dragon's Backbone\", rizières en terrasses sur 5 niveaux dans des montagnes 1000m, paysages spectaculaires en mai-juin pousse verte ou octobre récolte dorée, villages Yao/Zhuang minoritaires), <strong>Reed Flute Cave</strong> (grotte calcaire colorée au néon dans Guilin), <strong>Elephant Trunk Hill</strong> (collisée signature en bordure de rivière dans Guilin). <strong>Tester</strong> Guilin rice noodles (mi fen), beer fish (poisson de la rivière à la bière, spécialité Yangshuo), osmanthus tea/cake (fleurs d'osmanthus = symbole de Guilin).",

    "xian:fr": "Xi'an (Xian), capitale de la <strong>province du Shaanxi</strong> en Chine : 9 millions d'habitants, ancienne capitale de 13 dynasties chinoises (notamment Han et Tang, durant 1000 ans, jusqu'au IXe siècle). Point de départ historique de la <strong>Route de la Soie</strong>. Site de la découverte archéologique la plus stupéfiante du XXe siècle : l'<strong>Armée de Terre Cuite</strong>. <strong>Mai est mon mois préféré</strong> (8.8/10) : 15-28°C, 23% de pluie, températures idéales avant la canicule estivale. <strong>De septembre à octobre</strong>, comptez 10-26°C : excellente période, foliage début octobre. <strong>De juin à août</strong>, comptez 20-33°C avec 26-35% de pluie : chaud, parfois caniculaire (39°C+). <strong>De décembre à février</strong>, comptez -4/10°C et 6-13% de pluie : froid sec continental, pollution atmosphérique souvent élevée (Xi'an souffre du smog hivernal du nord chinois). <strong>Sites majeurs</strong> : <strong>Armée de Terre Cuite</strong> (UNESCO, à 35 km à l'est de Xi'an, découverte par hasard par des paysans en 1974, <strong>8000 soldats grandeur nature</strong> en argile cuite enterrés en 210 av JC pour garder le tombeau de l'empereur Qin Shi Huang, premier empereur chinois unificateur, 3 fosses excavées sur estimés 600 fosses au total, encore en cours d'excavation), <strong>Remparts de la ville Ming</strong> (XIVe, 14 km de tour à pied ou à vélo, l'un des seuls remparts chinois encore intacts, hauteur 12m, largeur 15m), <strong>Grande Pagode de l'Oie Sauvage</strong> (Big Wild Goose Pagoda, 64m, dynastie Tang VIIe siècle, construite pour héberger les sutras bouddhiques rapportés d'Inde par Xuanzang), <strong>Quartier musulman</strong> (Hui People, descendants des marchands arabes/persans de la Route de la Soie installés à Xi'an au VIIe-VIIIe siècle, atmosphère unique, street food, <strong>Mosquée de Xi'an</strong> XIVe = la plus vieille mosquée intacte de Chine, architecture chinoise atypique pour mosquée), <strong>Tour du Tambour et Tour de la Cloche</strong>, <strong>Famen Temple</strong> à 2h (relique du Bouddha). <strong>Tester</strong> rou jia mo (\"hamburger chinois\" sandwich pain plat porc effiloché), biang biang noodles, lamb skewers du quartier musulman, cumin-flavored beef.",

    "chengdu:fr": "Chengdu, capitale de la <strong>province du Sichuan</strong> en Chine : 21 millions d'habitants en aire urbaine (l'une des mégapoles chinoises les plus dynamiques), surnommée \"la cité des hibiscus\", capitale culturelle/gastronomique du sud-ouest chinois. Réputée pour les <strong>pandas géants</strong> (centre de recherche le plus connu au monde, 80% des pandas en captivité dans le monde) et la <strong>cuisine sichuanaise épicée</strong> (poivre Sichuan, mala = sensation engourdissante-piquante unique). <strong>Mai est mon mois préféré</strong> (7.7/10) : 18-27°C, 41% de pluie, températures idéales avant l'humidité estivale. <strong>D'avril à octobre</strong>, c'est la haute saison touristique : 14-31°C, mais climat humide constant (Chengdu est célèbre pour son ciel grisâtre permanent, les habitants disent qu'on voit le soleil 60 jours/an). <strong>De juin à septembre</strong>, comptez 21-31°C avec 44-66% de pluie : chaleur lourde et humide. <strong>De décembre à février</strong>, comptez 4-12°C et 16-26% de pluie : froid humide, peu de touristes. <strong>Sites majeurs</strong> : <strong>Centre de Recherche et de Reproduction des Pandas Géants</strong> (à 15 km au nord de Chengdu, le plus grand au monde, 80 pandas adultes + bébés, à visiter le matin tôt 7h30-9h quand les pandas mangent et sont actifs, 55 yuans), <strong>Vieille rue Jinli</strong> (rue commerçante traditionnelle reconstituée, street food, artisanat), <strong>Wenshu Monastery</strong> (le plus grand monastère bouddhiste de Chengdu, salle de thé fameuse), <strong>Du Fu Thatched Cottage</strong> (mémorial du grand poète Tang Du Fu qui y a vécu 4 ans en exil 759-763), <strong>Wuhou Shrine</strong> (mémorial Zhuge Liang stratège des Trois Royaumes), <strong>Quartier de Kuanzhai</strong> (Wide and Narrow Alleys, ruelles traditionnelles Qing reconvertis en restos-bars). <strong>Excursions</strong> : <strong>Mont Emei</strong> (UNESCO) à 2h30 (3099m, l'une des 4 montagnes sacrées bouddhistes chinoises, randonnée 2 jours), <strong>Bouddha Géant de Leshan</strong> (UNESCO, 71m, le plus grand Bouddha de pierre au monde, sculpté 713 dans la falaise au confluent de 3 rivières, à voir en bateau pour la perspective), <strong>Jiuzhaigou</strong> (UNESCO) en avion 1h (vallée des 9 villages tibétains, lacs turquoise multicolores). <strong>Tester</strong> hot pot sichuanais (huo guo, le plus épicé de Chine), mapo tofu, kung pao chicken (tous originaires du Sichuan), dan dan noodles.",

    "zhangjiajie:fr": "Zhangjiajie, parc national en Chine dans la <strong>province du Hunan</strong> : ville de 1,5 million d'habitants au pied du parc, célèbre pour ses <strong>3000 pitons karstiques de quartz-grès</strong> de 200 à 800m de hauteur, paysages qui ont inspiré James Cameron pour les <strong>montagnes flottantes du film Avatar</strong> 2009 (le piton Hallelujah Mountain a été officiellement renommé après le succès du film). <strong>Septembre est mon mois préféré</strong> (8.2/10) : 21-29°C, 35% de pluie, températures idéales et brumes mystiques caractéristiques. <strong>D'avril à octobre</strong>, c'est la haute saison touristique : 14-33°C, mais aussi <strong>foule extrême</strong> (l'un des sites les plus touristiques de Chine, 30 millions de visiteurs/an chinois en majorité, ascenseur Bailong et téléphérique souvent saturés en 2-3h d'attente). <strong>De juin à août</strong>, comptez 22-33°C avec 48-58% de pluie : chaleur étouffante en bas, plus frais en altitude. <strong>De décembre à février</strong>, comptez 3-12°C : froid hivernal, sentiers parfois fermés pour neige, mais paysages spectaculaires sous brume. <strong>Sites majeurs</strong> : <strong>Wulingyuan Scenic Area</strong> (UNESCO 1992, parc national de Zhangjiajie + Suoxi Valley + Tianzi Mountain), <strong>Bailong Elevator</strong> (\"Hundred Dragons Elevator\", l'ascenseur extérieur le plus haut du monde 326m, 3 cabines parallèles, 2 min de montée, expérience vertigineuse), <strong>Glass Bridge de Zhangjiajie</strong> (Grand Canyon Bridge, 430m de long, 300m au-dessus du sol, le plus long pont en verre au monde 2016), <strong>Tianmen Mountain</strong> (porte du ciel, téléphérique 7,5 km le plus long du monde, escalier 999 marches vers la cavité naturelle Tianmen Cave 131m de haut), <strong>Yellow Stone Village</strong> (Huangshi Village), <strong>Golden Whip Stream</strong>. <strong>Logistique</strong> : entrée parc 230 yuans/4 jours (plusieurs entrées Wulingyuan/Forêt Park/Yangjiajie), comptez 3-4 jours minimum pour bien profiter. Vol direct Zhangjiajie depuis Shanghai/Pékin/Chengdu en 2-3h.",

    "suzhou:fr": "Suzhou, à 100 km à l'ouest de Shanghai dans la <strong>province du Jiangsu</strong> : 6 millions d'habitants, surnommée la <strong>\"Venise de l'Est\"</strong> pour ses canaux datant des dynasties Tang-Song (VIe-Xe siècles). UNESCO 1997 pour ses jardins classiques chinois (Suzhou est le berceau de l'art des jardins chinois). <strong>Septembre est mon mois préféré</strong> (8.0/10) : 22-28°C, 44% de pluie, températures idéales après la canicule estivale. <strong>De septembre à novembre</strong>, c'est la haute saison touristique : 10-28°C, foliage des érables des jardins en novembre. <strong>D'avril à mai</strong>, comptez 12-26°C : printemps avec floraison des cerisiers. <strong>De juin à août</strong>, comptez 21-34°C avec 46-54% de pluie : chaleur étouffante typique du delta du Yangtsé, taux d'humidité oppressant. <strong>De décembre à février</strong>, comptez 1-11°C et 20-30% de pluie : froid humide, peu de touristes. <strong>Sites majeurs</strong> : <strong>Jardins classiques de Suzhou</strong> (UNESCO, 9 jardins inscrits, à voir en priorité : <strong>Humble Administrator's Garden</strong> Zhuozheng Yuan le plus grand 5 hectares XVIe, <strong>Lingering Garden</strong> Liu Yuan calligraphies, <strong>Master of the Nets Garden</strong> Wangshi Yuan le plus intimiste à voir illuminé le soir, <strong>Lion Grove Garden</strong> Shizilin avec ses pierres calcaires en formes de lions), <strong>Pingjiang Road</strong> (rue piétonne historique le long d'un canal, ambiance ancienne, salons de thé, boutiques traditionnelles), <strong>Tiger Hill</strong> (Huqiu, colline avec pagode penchée XIe siècle qui penche encore plus que la Tour de Pise), <strong>Hanshan Temple</strong> (rendu célèbre par le poème Tang \"Mouillage de nuit au Pont des Érables\" de Zhang Ji, cloche ancestrale frappée 108 fois pour le Nouvel An), <strong>Suzhou Museum</strong> (architecture I.M. Pei né en Chine 2006), <strong>Suzhou Silk Museum</strong> (Suzhou est la capitale historique de la soie chinoise depuis 4000 ans). <strong>Excursions</strong> : <strong>Tongli</strong>, <strong>Zhouzhuang</strong>, <strong>Wuzhen</strong> (water towns à 1-2h, villages d'eau ancestraux). <strong>Tester</strong> Suzhou-style noodles, songshu yu (poisson écureuil sucré-acidulé), jiangsu cuisine. À 30 min en train rapide de Shanghai, parfait excursion journée.",

    "hangzhou:fr": "Hangzhou, capitale de la <strong>province du Zhejiang</strong> en Chine : 12 millions d'habitants à 200 km au sud-ouest de Shanghai, ancienne capitale de la dynastie Song du Sud (1127-1279), surnommée \"<em>paradis sur terre</em>\" par Marco Polo qui l'a visitée au XIIIe siècle (\"la plus grande et la plus noble ville du monde\"). Siège mondial d'<strong>Alibaba</strong> (Jack Ma a fondé l'entreprise ici en 1999). <strong>Septembre est mon mois préféré</strong> (7.9/10) : 22-29°C, 47% de pluie, températures idéales après la canicule. <strong>De septembre à novembre</strong>, c'est la haute saison touristique : 10-29°C, fleurs de osmanthus parfumées en septembre, érables rouges en novembre. <strong>D'avril à mai</strong>, comptez 13-26°C : printemps avec thé Longjing nouvelles feuilles (la récolte de printemps avant la fête du \"qing ming\" 5 avril donne le thé le plus prestigieux et cher). <strong>De juin à août</strong>, comptez 22-34°C avec 49-62% de pluie : chaleur étouffante typique du delta. <strong>De décembre à février</strong>, comptez 2-12°C et 23-39% de pluie : froid humide. <strong>Sites majeurs</strong> : <strong>Lac de l'Ouest</strong> (Xi Hu, UNESCO, l'un des paysages naturels les plus connus de Chine, modèle pour les peintures de paysages traditionnels chinois, tour à pied 15 km ou en bateau-dragon 2h, plus belles vues : <strong>Pagode de Leifeng</strong> au sud, <strong>Su Causeway</strong>, <strong>Bai Causeway</strong>, <strong>3 Pools Mirroring the Moon</strong>), <strong>Lingyin Temple</strong> (\"Temple de la retraite spirituelle\", l'un des plus grands monastères Chan/Zen du sud chinois, fondé en 326), <strong>Six Harmonies Pagoda</strong> (Liuhe Ta, sur les berges du fleuve Qiantang, vue sur le Bore du Qiantang phénomène de vague tidale célèbre mi-septembre), <strong>Hefang Street</strong> (rue piétonne traditionnelle restaurée, boutiques et street food), <strong>Plantations de thé Longjing</strong> (\"Dragon Well\", le thé vert chinois le plus prestigieux, à visiter dans les villages Meijiawu ou Longjing à 30 min). <strong>National Tea Museum</strong>. <strong>Tester</strong> dongpo pork (porc braisé sucré-salé, plat de Hangzhou inventé par le poète Su Dongpo XIe siècle), beggar's chicken (poulet enveloppé dans feuilles de lotus et boue), thé Longjing.",

    "lijiang:fr": "Lijiang, ville UNESCO dans la <strong>province du Yunnan</strong> au sud-ouest de Chine : 1,3 million d'habitants à 2400m d'altitude au pied de la <strong>Jade Dragon Snow Mountain</strong> (5596m), berceau de la culture <strong>Naxi</strong> (minorité ethnique avec écriture pictographique <strong>Dongba</strong> = la seule écriture pictographique vivante au monde aujourd'hui, encore utilisée par les chamanes Dongba). <strong>Avril est mon mois préféré</strong> (8.1/10) : 7-21°C, 33% de pluie, températures idéales en altitude, ciel dégagé pour voir la Jade Dragon. <strong>De mars à mai et octobre-novembre</strong> sont les meilleures saisons : 3-21°C, climat sec et ensoleillé. <strong>De juin à septembre</strong>, c'est la mousson : 75-84% de précipitations, paysages verts mais brumes fréquentes qui cachent la montagne. <strong>De décembre à février</strong>, comptez -1/15°C : froid sec, ensoleillé, neige possible sur les sommets autour, beaucoup moins de touristes. <strong>Sites majeurs</strong> : <strong>Vieille ville de Lijiang</strong> (UNESCO 1997, dédale de ruelles pavées avec canaux, maisons traditionnelles Naxi en bois sculpté, atmosphère unique préservée malgré le tourisme de masse - depuis 2000 Lijiang est devenue l'une des destinations touristiques chinoises les plus populaires, parfois saturée), <strong>Black Dragon Pool</strong> (Heilongtan, parc public au nord avec étang offrant la vue signature sur la Jade Dragon Snow Mountain reflétée dans l'eau et pavillon Wufeng), <strong>Mu Family Mansion</strong> (résidence des chefs hereditary Naxi du XIVe au XVIIIe siècle), <strong>Jade Dragon Snow Mountain</strong> (téléphérique vers 4506m glacier, oxygène à 4000m+, à acheter en bouteille pour les sensibles à l'altitude). <strong>Excursions</strong> : <strong>Tiger Leaping Gorge</strong> à 2h (l'une des plus profondes gorges au monde, 3790m de différence entre fleuve Yangtsé et sommet Haba 5396m, randonnée 2 jours), <strong>Shangri-La</strong> à 4h (anciennement Zhongdian, renommée en 2001 pour le tourisme, monastère tibétain Songzanlin, altitude 3200m), <strong>Première Bend du Yangtsé</strong> à Shigu, <strong>Lac Lugu</strong> à 6h (peuple Mosuo matriarcal). <strong>Tester</strong> Naxi cuisine (yak butter tea, baba grilled, hot pot mushroom).",

    "kanazawa:fr": "Kanazawa, dans la <strong>préfecture d'Ishikawa</strong> sur la côte ouest du Japon : 460 000 habitants, ancienne capitale du puissant clan féodal Maeda durant l'époque Edo (1583-1868), épargnée par les bombardements WWII donc l'une des seules villes japonaises avec architecture traditionnelle préservée. Considérée comme \"la petite Kyoto sans la foule\". <strong>Juin est mon mois préféré</strong> (8.1/10) : 17-25°C, 44% de pluie, températures clémentes avant l'humidité estivale. <strong>De mai à juin et septembre-octobre</strong>, comptez 13-26°C : climat doux. <strong>De juillet à août</strong>, comptez 22-31°C avec 49-51% de pluie : chaud et humide. <strong>De décembre à février</strong>, comptez 0-9°C et 68-80% de précipitations souvent neige (la côte ouest du Japon reçoit énormément de neige, Kanazawa est l'une des grandes villes les plus enneigées au monde 3-4m/saison). <strong>Sites majeurs</strong> : <strong>Kenroku-en</strong> (l'un des <strong>3 plus beaux jardins traditionnels du Japon</strong> avec Kairaku-en de Mito et Koraku-en d'Okayama, 11,4 hectares créés sur 200 ans 1620-1840 par les seigneurs Maeda, particulièrement spectaculaire en hiver avec ses pins suspendus sur cordes \"yukitsuri\" pour ne pas se casser sous la neige), <strong>Château de Kanazawa</strong> (à côté de Kenroku-en, complexe en cours de reconstruction depuis 2001), <strong>Quartier Higashi Chaya</strong> (l'un des 3 quartiers de geishas conservés au Japon avec Kyoto Gion et Tokyo Asakusa, maisons en bois XIXe encore en activité, possibilité de prendre le thé dans une maison de thé historique), <strong>Quartier Nagamachi</strong> (anciennes résidences de samouraïs), <strong>Kanazawa 21st Century Museum of Contemporary Art</strong> (architecture circulaire SANAA, l'un des musées contemporains les plus visités du Japon), <strong>Marché Omicho</strong> (\"la cuisine de Kanazawa\", marché aux poissons depuis 1721, plus de 170 stands), <strong>Quartier Teramachi</strong> (\"quartier des temples\" avec Ninja Temple Myoryu-ji = pas vraiment un temple ninja mais un temple à pièges secrets construit pour défense). <strong>Tester</strong> sushi de la mer du Japon (parmi les meilleurs au Japon grâce à proximité), kaga ryori cuisine régionale, jibu-ni stew, gold leaf ice cream (Kanazawa produit 99% de la feuille d'or japonaise utilisée pour décorer temples et laques).",

    "nagoya:fr": "Nagoya, 4e ville du Japon : 2,3 millions d'habitants au cœur de la <strong>région du Chubu</strong>, capitale industrielle de l'industrie automobile japonaise (siège mondial de <strong>Toyota</strong> à Toyota City voisine, <strong>Mitsubishi</strong>, <strong>Yamaha</strong>). Souvent négligée par les touristes, étape utile entre Tokyo (1h40 en Shinkansen) et Kyoto (35 min en Shinkansen). <strong>Mai est mon mois préféré</strong> (8.0/10) : 14-24°C, 41% de pluie, températures idéales avant la mousson tsuyu juin-juillet. <strong>D'avril à juin</strong>, c'est la haute saison touristique : 9-27°C, fin des cerisiers en avril. <strong>De juin à mi-juillet</strong>, c'est le tsuyu (saison des pluies). <strong>Juillet-août chutent à 6.7-6.9/10</strong> à cause de la canicule humide (23-32°C). <strong>D'octobre à novembre</strong>, comptez 7-22°C : excellente période, momiji (couleurs d'automne). <strong>De décembre à février</strong>, comptez 0-11°C et 18-24% de pluie : froid sec, neige rare. <strong>Sites majeurs</strong> : <strong>Château de Nagoya</strong> (XVIIe, reconstruit après bombardements WWII, donjon avec 2 dauphins en or sur le toit \"shachihoko\" symboles de la ville, en cours de reconversion en bois traditionnel depuis 2018), <strong>Sanctuaire d'Atsuta</strong> (l'un des plus importants sanctuaires shinto du Japon, gardien du sabre sacré Kusanagi-no-Tsurugi l'un des 3 trésors impériaux du Japon), <strong>Musée Toyota Commemorative</strong> (visite passionnante de l'industrie textile puis automobile Toyota), <strong>Musée des Sciences de Nagoya</strong> (planétarium le plus grand au monde 35m de diamètre), <strong>Quartier Sakae</strong> (centre commercial moderne, Oasis 21 architecture flottante), <strong>Quartier Osu</strong> (street commerçante traditionnelle), <strong>Toyota Stadium</strong> (Coupe du Monde Rugby 2019, Coupe du Monde Football 2002). <strong>Excursions</strong> : <strong>Inuyama Castle</strong> à 30 min (le plus vieux château japonais en bois 1537), <strong>Magome et Tsumago</strong> sur l'ancienne route Nakasendo (Edo-Kyoto), <strong>Takayama</strong> à 2h en train (vieille ville Edo préservée), <strong>Shirakawa-go</strong> (UNESCO, maisons traditionnelles à toit de chaume gassho-zukuri). <strong>Tester</strong> miso katsu (porc pané à la sauce miso de Nagoya), tebasaki (ailes de poulet frites), hitsumabushi (anguille grillée 3 façons), kishimen (nouilles plates).",

    "jeju:fr": "Jeju (Jeju-do), île volcanique de la <strong>Corée du Sud</strong> à 100 km au sud du continent : 670 000 habitants sur 1849 km² (la plus grande île de Corée), inscrite UNESCO 2007 (volcans tubes de lave et écosystème unique), réputée comme \"l'île du miel-lune\" pour les couples coréens. <strong>Mai est mon mois préféré</strong> (7.9/10) : 15-22°C, 36% de pluie, températures idéales, fleurs de cerisier (sakura, le sud de la Corée fleurit fin mars-début avril, Jeju les premières début mars). <strong>De mai à septembre</strong>, c'est la haute saison touristique : 15-30°C. <strong>De juillet à août</strong>, comptez 25-30°C avec 57-59% de pluie : chaleur lourde et humide, mais aussi pic touristique coréen (vacances scolaires). <strong>De décembre à mars</strong>, comptez 2-13°C et 40-46% de pluie : doux pour la Corée (Jeju est l'île la plus chaude de Corée), neige possible sur Hallasan en hiver. <strong>Sites majeurs</strong> : <strong>Mont Hallasan</strong> (1947m, point culminant de Corée du Sud, volcan endormi avec lac de cratère, ascension 9 km par sentier Seongpanak ou Gwaneumsa, 4-5h aller, parfois fermé en hiver pour neige), <strong>Manjanggul</strong> (UNESCO, l'un des plus longs tubes de lave du monde 7,4 km, 1 km accessible aux visiteurs avec lanternes, frais 11°C constant toute l'année), <strong>Seongsan Ilchulbong</strong> (\"Sunrise Peak\", UNESCO, cratère volcanique de 5000 ans à l'extrême est, 182m, ascension 30 min, vue spectaculaire au lever du soleil), <strong>Jusangjeolli Cliff</strong> (falaises basaltiques en colonnes hexagonales géologiques), <strong>Cheonjeyeon Falls</strong> et <strong>Jeongbang Falls</strong> (chutes), <strong>Cheonjiyeon Waterfall</strong>, <strong>Olle Trails</strong> (réseau de 425 km de sentiers côtiers en 27 segments, popularisé depuis 2007 sur le modèle du Camino de Santiago), <strong>Plages</strong> : Hyeopjae (sable blanc, eau turquoise), Hamdeok, Jungmun. <strong>Phénomène culturel des haenyeo</strong> (\"femmes de la mer\", plongeuses en apnée sans équipement qui pêchent ormeaux, oursins, ormeaux jusqu'à 70-80 ans, tradition matriarcale millénaire UNESCO 2016, en voie d'extinction - 4500 dans les années 1960, moins de 4000 aujourd'hui dont 60% ont plus de 70 ans). <strong>Tester</strong> heuk dwaeji (porc noir de Jeju), abalone porridge, hallabong (mandarine de Jeju), omija tea. Vol direct Séoul-Jeju en 1h (l'une des liaisons aériennes les plus fréquentées au monde, 80 000 vols/an)."
}

with open(PATH, encoding='utf-8') as f:
    data_existing = json.load(f)

before = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

data_existing['_version'] = '2.6'
data_existing['_updated'] = '2026-04-28'

for k, v in AVIS_BATCH15_FR.items():
    data_existing[k] = v

after = len([k for k in data_existing if k.endswith(':fr') and not k.startswith('_')])

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data_existing, f, ensure_ascii=False, indent=2)

print(f"Avis FR avant : {before}")
print(f"Avis FR après : {after}")
print(f"Nouveaux : {after - before}")

# Audit immédiat
import re
patterns_check = [
    ('em-dash', r'—'), ('guillemets', r'[«»]'),
    ('attendez-vous', r'attendez-vous à'),
    ('parfait', r'\bparfait[es]*\b'),
    ('fenêtre', r'\bfenêtre[s]?\b'),
    ('saturé', r'\bsatur[eéa]\w*\b'),
    ('se mérite', r'\bse méri[tes]+\b'),
    ('magique', r'\bmagiques?\b'),
    ('Si vous X:', r'Si vous \w+ : '),
    ('iconique', r'\biconique[s]?\b'),
    ('antithèse', r'antithèse'),
    ('mythique', r'\bmythique[s]?\b'),
    ('emblématique', r'\bemblématique[s]?\b'),
    ('authentique', r'\bauthentique[s]?\b'),
    ('féérique', r'\bféérique[s]?\b'),
    ("c'est aussi", r"[Cc]'est aussi"),
    ('à monitorer', r'à monitorer'),
    ('à éviter', r'à éviter'),
]

print("\n=== Audit batch 15 ===")
issues_total = 0
for slug in AVIS_BATCH15_FR.keys():
    plain = re.sub(r'<[^>]+>', '', data_existing[slug])
    issues = []
    for label, p in patterns_check:
        n = len(re.findall(p, plain))
        if n > 0:
            issues.append(f"{label}={n}")
            issues_total += n
    flag = "OK" if not issues else "PB " + ", ".join(issues)
    print(f"  {slug:<22} {len(plain.split()):>3}m {flag}")
print(f"\nTotal issues : {issues_total}")
