"""
Réécriture batch 1 : suppression des patterns LLM.
- 0 em-dash, 0 « », 0 apostrophe courbe (déjà fait)
- Suppression : se mérite, magique, magique, parfait (qualif), fenêtre, attendez-vous,
  saturé, Si vous X:, C'est aussi, antithèse, iconique, mythique
- Phrases plus courtes et naturelles
- Faits chiffrés et noms propres conservés
"""
import json

PATH = 'data/avis_annuel.json'
data = json.load(open(PATH, encoding='utf-8'))

REWRITES = {
    "la-gomera:fr": "La Gomera demande un peu d'effort : pas d'aéroport international, ferry obligatoire depuis Tenerife. Une fois sur place, <strong>de mai à octobre</strong>, le climat devient excellent avec 18-28°C et 0-8% de pluie sur les côtes. <strong>Juillet-août</strong> sont mes mois préférés (9.6/10) : le parc national de Garajonay reste à 18°C dans la laurisilve même quand San Sebastián tape à 28°C. Bon compromis pour les randonneurs : le réseau de senderos couvre tous les niveaux, et le silbo gomero (langage sifflé) reste pratiqué dans certains villages. <strong>De décembre à mars</strong>, la pluie monte à 11-15% et les alizés rafraîchissent. Toujours doux (15-22°C) mais ciel changeant côté nord. Bon plan pour qui cherche la randonnée sans la chaleur écrasante du sud des Canaries.",

    "windhoek:fr": "Windhoek, c'est avant tout la base logistique pour la Namibie. À 1700m d'altitude sur le plateau central, les températures restent surprenantes : <strong>de mai à août, les nuits descendent à 8°C</strong> alors que les journées restent à 22-25°C. <strong>Septembre est mon mois préféré</strong> (9.5/10) : 13-29°C, 2% de pluie, ciel dégagé pour rejoindre Sossusvlei, Etosha ou la Skeleton Coast. <strong>De décembre à mars</strong>, la saison des pluies amène 25-33% d'averses orageuses (souvent en fin d'après-midi) et les températures grimpent à 30-32°C. Les pistes peuvent devenir difficiles, certains lodges ferment. C'est aussi la seule période où la Namib reverdit : un visage rare et photogénique du désert. Avril-mai sont une bonne transition : pluies finissantes, lumière dorée, températures redevenues clémentes.",

    "agadir:fr": "Agadir mise tout sur sa stabilité météo : <strong>11 mois sur 12 au-dessus de 8/10</strong>, océan régulé par le courant des Canaries. <strong>Juin-juillet</strong> sont mes mois préférés (9.5/10) : 17-26°C, 0% de pluie, plage de 6 km bien orientée. Septembre garde la baignade tiède (20°C en mer) avec un soleil moins agressif qu'en plein été. <strong>De décembre à février</strong>, on retombe à 11-21°C avec quelques averses. Toujours portable mais finie la baignade. C'est l'angle le plus économique : tarifs hôtels divisés par 2-3 vs juillet. À 25 km au nord, <strong>Taghazout</strong> attire les surfeurs toute l'année grâce aux houles d'Atlantique constantes. Ne cherchez pas la médina ici : Agadir a été reconstruite après le séisme de 1960.",

    "gran-canaria:fr": "Gran Canaria, le continent miniature : dunes de Maspalomas au sud, pinèdes en altitude, Atlantique à l'ouest. <strong>Juillet-août dominent</strong> (9.6/10) avec 21-28°C et 0-1% de pluie. C'est aussi la haute saison touristique européenne. <strong>Mai-juin et septembre-octobre sont mon vrai compromis</strong> : météo presque identique, foule réduite, tarifs en retrait. Le sud (Maspalomas, Playa del Inglés) reste sec quasi toute l'année grâce à la Cordillera Central qui bloque les nuages. <strong>De décembre à mars</strong>, prévoyez 16-21°C et 6-11% de pluie. Toujours doux mais moins fiable côté nord (Las Palmas plus humide que Mogán de 30%). Le Roque Nublo à 1800m peut neiger en hiver, étonnant pour des Canaries. Las Palmas garde une vraie vie urbaine toute l'année, contrairement aux stations sud.",

    "karachi:fr": "Karachi vit au rythme de la mousson, mais la sienne est limitée : <strong>juillet-août seulement</strong> avec 21-22% de précipitations contre 90% à Mumbai à la même période. Le climat reste majoritairement aride. <strong>Février est mon mois préféré</strong> (9.3/10) : 17-27°C, 2% de pluie, mer à bonne température pour Clifton Beach. <strong>De juin à août</strong>, la chaleur humide devient pesante (28-33°C, taux d'humidité élevé) avec des averses parfois fortes. La mousson amène aussi smog et embouteillages massifs dans cette mégapole de 16 millions. De novembre à mars, c'est le bon moment : ciel bleu, journées chaudes mais portables, soirées agréables. C'est aussi quand les marchés en plein air et la cuisine de rue (biryani, nihari) prennent vie : trop de chaleur en été pour les food stalls.",

    "santa-barbara:fr": "Santa Barbara, c'est la Californie tempérée par excellence : microclimat protégé par les Santa Ynez Mountains au nord, brises océaniques constantes. <strong>Juillet est mon mois préféré</strong> (10.0/10) : 18-28°C, 0% de pluie, et les fameuses \"May Gray / June Gloom\" (brouillards matinaux) déjà dissipées. La saison des feux de forêt court de juin à octobre : l'air peut se charger de fumée selon les vents (Sundowner). <strong>De décembre à mars</strong>, le visage devient plus humide, 18-21% de pluie, mais toujours 8-19°C. Très bien pour la randonnée à Romero Canyon ou la route 1 vers Big Sur. Avril-mai et septembre-octobre sont des saisons charnières excellentes : moins de touristes, vignobles de la Santa Ynez Valley en pleine récolte (Sideways oblige), et State Street accessible.",

    "honolulu:fr": "Honolulu, c'est la stabilité tropicale presque ennuyeuse : <strong>20-29°C toute l'année, jamais de saison vraiment mauvaise</strong>. La vraie variable, c'est la pluie sur la côte au vent : 22-39% selon les mois, mais souvent en averses brèves. <strong>Juin reste mon mois préféré</strong> (9.2/10) : 23-28°C, 24% de pluie seulement, alizés constants, mer à 25°C pour Waikiki. Avril-mai voient les surfeurs migrer du North Shore (vagues finies) vers la South Shore (Diamond Head, Ala Moana). <strong>D'octobre à mars</strong>, la pluie monte à 24-35% avec quelques averses tropicales et la grande houle qui revient sur le North Shore (Pipeline, Sunset Beach). C'est aussi le pic touristique américain et la haute saison des prix. Les Européens préfèrent souvent mai-septembre, plus économique.",

    "fuerteventura:fr": "Fuerteventura, c'est la Canarie la plus aride et la plus ventée : peu de relief pour bloquer les nuages, mais aussi peu pour arrêter le vent. <strong>Août est mon mois préféré</strong> (9.7/10) : 18-28°C, 1% de pluie, mer à 22°C. Le sud (Sotavento, Costa Calma) est devenu un spot mondial de kitesurf grâce aux alizés thermiques constants de mai à septembre. Le PWA y organise une étape du World Tour chaque été. <strong>De novembre à mars</strong>, prévoyez 12-22°C et un vent moins prévisible. Toujours portable, mais finie la baignade pour les Européens. Tarifs hôtels divisés par 2 vs été. <strong>Le calima</strong> (vent de sable du Sahara) peut frapper toute l'année avec une visibilité réduite et 28-35°C subitement. Phénomène plus fréquent ces dernières années (changement climatique). Corralejo au nord reste la base la plus animée, El Cotillo plus tranquille.",

    "sal:fr": "Sal, porte d'entrée du Cap-Vert : île plate, désertique, dont l'attrait est entièrement dans la mer. Donnée curieuse : <strong>septembre et octobre tombent à 6.9/10</strong> à cause des pluies tardives ramenées de la zone de convergence intertropicale (rare mais marquant). <strong>Mai-juin sont mes mois préférés</strong> (9.4/10) : 21-27°C, 0-1% de pluie, alizés constants. Santa Maria au sud concentre 90% des hôtels et les écoles de kitesurf : la baie protégée et les vents thermiques en font un spot de niveau mondial. <strong>D'août à octobre</strong>, des averses orageuses sont possibles (4-23% de pluie selon le mois). Toujours chaud mais ciel moins fiable. De décembre à avril restent la haute saison européenne : fuite de l'hiver, prix qui montent, plages qui se remplissent. Pedra de Lume (mines de sel dans un cratère) et le shark watching à proximité d'Essinger Beach valent le détour.",

    "guanajuato:fr": "Guanajuato, ville coloniale UNESCO encastrée dans une vallée minière à 2000m d'altitude. La saison sèche tient le tourisme. <strong>Mars est mon mois préféré</strong> (9.6/10) : 12-28°C, 4% de pluie, idéal pour grimper le Pípila ou explorer les callejones. <strong>De juin à septembre</strong>, c'est la saison des pluies : 47-58% d'averses orageuses, souvent en fin d'après-midi (les matinées restent souvent ensoleillées). Températures qui retombent à 14-27°C grâce à l'altitude. Le <strong>Festival Cervantino</strong> en octobre transforme la ville pendant 3 semaines : compagnies internationales, prix hôteliers x3, réservations 6 mois à l'avance. Les momies du Museo de las Momias attirent les curieux toute l'année. À 30 minutes, San Miguel de Allende offre une autre ambiance coloniale plus chic. Novembre-avril restent la saison la plus stable et la plus photogénique.",

    "los-angeles:fr": "Los Angeles, c'est la stabilité méditerranéenne sur 12 mois : pas de saison vraiment dure, mais des nuances importantes. <strong>Juin est mon mois préféré</strong> (9.7/10) : 15-28°C, 2% de pluie, et le brouillard du \"June Gloom\" se dissipe enfin. <strong>De juillet à septembre</strong>, prévoyez 17-32°C avec des Santa Ana winds en automne qui attisent les feux dans les collines (saison des incendies de juillet à octobre). Le smog peut être pénible quand l'inversion thermique bloque l'air. <strong>De décembre à mars</strong>, c'est la \"rainy season\" californienne : 17-27% de pluie, mais cela reste 8-20°C, hivers doux. La Pacific Coast Highway vers Malibu reste praticable, les glissements de terrain peuvent fermer Mulholland après gros épisodes. Avril-mai et octobre-novembre sont des transitions excellentes : moins de monde sur les plages, terrasses agréables, ciel souvent clair après les pluies finissantes.",

    "essaouira:fr": "Essaouira, l'opposé de Marrakech : Atlantique au lieu d'aride, vent au lieu de chaleur, médina apaisée au lieu de souks bondés. <strong>Juillet-août sont mes mois préférés</strong> (9.4/10) : 19-25°C, 0% de pluie, période où Marrakech à 130 km à l'intérieur tape à 38°C. Le <strong>festival Gnaoua</strong> mi-juin transforme la ville pendant 4 jours (musique soufie, jam sessions gratuites). <strong>L'alizé (taros) souffle quasi en permanence</strong> de mars à septembre : 25-40 km/h en moyenne, ce qui en fait un spot mondial de kitesurf et windsurf. Côté plage classique, c'est défavorable. <strong>De décembre à mars</strong>, comptez 11-21°C et 9-21% de pluie. Toujours portable mais ciel changeant. La médina UNESCO se découvre à pied en 2h, les remparts de Mogador (où Welles a tourné Othello) et le port de pêche restent des classiques.",

    "oaxaca:fr": "Oaxaca, c'est le Mexique le plus dense culturellement : zones zapotèques, mezcal artisanal, marchés précolombiens encore vivants. À 1500m d'altitude, le climat reste tempéré toute l'année. <strong>Février est mon mois préféré</strong> (9.5/10) : 11-28°C, 2% de pluie, ciel dégagé pour Monte Albán ou Hierve el Agua. <strong>De juin à septembre</strong>, c'est la saison des pluies tropicales (59-70% d'averses), souvent fin d'après-midi mais parfois longues. C'est aussi la période la plus verte, intéressante pour la photo si vous acceptez l'incertitude. <strong>Día de los Muertos fin octobre-début novembre</strong> est le pic touristique absolu : prix hôteliers x3-x5, réservations 6 mois à l'avance, mais ambiance unique au monde (cimetières illuminés, défilés de catrinas). Le <strong>Guelaguetza</strong> en juillet est un autre temps fort, malgré les pluies. Novembre-mai restent la saison sèche stable.",

    "santiago:fr": "Santiago est dominé par les Andes : pollution atmosphérique en hiver (l'inversion thermique bloque le smog dans la cuvette), été méditerranéen sec. <strong>Décembre est mon mois préféré</strong> (9.8/10) : 14-29°C, 3% de pluie, journées de 14h. <strong>De juin à août</strong> (hiver austral), le mercure descend à 7-15°C avec un smog pesant en semaine. La randonnée au Cerro San Cristóbal devient irrespirable certains jours. C'est en revanche la saison de ski au Valle Nevado (1h30 de la ville) : 60 jours de ski par an en moyenne. Valparaíso et Viña del Mar à 1h30 restent un classique du week-end. <strong>Le Cajón del Maipo</strong> (canyon andin) se randonne d'octobre à avril. Mai et septembre sont des transitions correctes : moins de smog, prix hôteliers en retrait, vignobles de la Vallée du Maipo agréables (Concha y Toro à 30 minutes).",

    "harare:fr": "Harare, c'est la haute altitude africaine (1500m) qui adoucit le climat : pas la canicule du Mozambique, ni la sécheresse extrême du Botswana. <strong>Septembre est mon mois préféré</strong> (9.6/10) : 14-28°C, 2% de pluie, juste avant la saison humide. <strong>De novembre à mars</strong>, c'est la saison des pluies subtropicale : 38-71% d'averses orageuses, souvent en fin d'après-midi. Les routes deviennent boueuses dans certains parcs nationaux (Mana Pools, Hwange). Le pic touristique des chutes Victoria, lui, est en avril-mai (pleines eaux après les pluies). <strong>Mai à août</strong> sont la saison sèche fraîche : 9-23°C, ciel dégagé, idéal pour les safaris (animaux concentrés autour des points d'eau). Le contexte économique zimbabwéen reste compliqué : prévoyez du cash USD, peu de cartes acceptées hors hôtels haut de gamme. Lake Chivero à 30 km offre une échappée nature.",

    "lima:fr": "Lima est paradoxale : capitale d'un des pays les plus ensoleillés au monde (sud), mais elle-même dans une ceinture de brouillard côtier (la <strong>garúa</strong>) cinq mois par an. Pas de pluie significative jamais. <strong>Février est mon mois préféré</strong> (9.0/10) : 21-26°C, ciel bleu enfin, plages du sud (Asia, Punta Hermosa) accessibles. <strong>De juin à octobre</strong>, c'est la garúa : un brouillard épais matin et soir, ciel gris constant, 14-21°C. Le soleil fait des apparitions courtes vers midi. C'est la période où Miraflores et Barranco prennent leur visage le plus mélancolique (très bien pour les fans de Vallejo et de littérature péruvienne). Cusco et Machu Picchu, à l'altitude, ont leur saison sèche à ce moment précis (juin-août = pic touristique inca). Beaucoup de voyageurs n'utilisent Lima que comme base de transit. La <strong>scène gastronomique</strong> (Central, Maido) reste la principale raison de s'arrêter.",

    "petra:fr": "Petra demande de bien choisir son moment : <strong>2200m d'altitude au cœur d'un désert</strong>, donc froid l'hiver, brûlant l'été. <strong>Mai est mon mois préféré</strong> (9.8/10) : 17-28°C, 4% de pluie, lumière dorée sur le grès rose. La randonnée jusqu'au Monastère (Ad Deir, 40 minutes de marches d'escalier) reste praticable. <strong>De juin à août</strong>, le mercure atteint 22-32°C dès 9h. Il devient impératif de partir avant 6h pour le Trésor (Khazneh) à la lumière du matin, et de rentrer avant midi. Les bédouins servent le thé partout sur le site. <strong>De décembre à février</strong>, les nuits descendent à 6°C, des chutes de neige rares mais possibles peuvent fermer le site quelques heures. Le Wadi Rum à 2h de route complète bien Petra (1-2 nuits en bivouac). Le \"Petra by Night\" 3 fois par semaine est touristique mais reste un moment singulier.",

    "socotra:fr": "Socotra est l'une des destinations les plus difficiles d'accès au monde : île yéménite de l'océan Indien, vols seulement depuis Abou Dhabi (Air Arabia, 1 fois par semaine), guides obligatoires pour la plupart des sites. <strong>Octobre à avril</strong> est la période praticable. <strong>Février est mon mois préféré</strong> (9.3/10) : 16-27°C, 5% de pluie, mer calme pour rejoindre Detwah Lagoon. Les <strong>dragonniers (Dracaena cinnabari)</strong> du plateau de Diksam sont la signature absolue, complétés par les bottle trees et les desert roses endémiques. <strong>De mai à septembre</strong>, la mousson de sud-ouest amène vents violents, certains vols suspendus, accès aux plages du nord coupé. C'est aussi quand les bougainvilliers fleurissent. La logistique reste rudimentaire : hébergement en eco-camps, peu d'eau chaude, électricité au générateur, paiement cash en USD uniquement. Comptez 1500-2500€ pour un voyage de 8 jours. Destination réservée aux voyageurs préparés.",

    "casablanca:fr": "Casablanca est plus une ville à vivre qu'à visiter : capitale économique du Maroc, peu de monuments hors la mosquée Hassan II (3e plus grande au monde, ouverte aux non-musulmans). <strong>Août est mon mois préféré</strong> (9.6/10) : 20-27°C, 1% de pluie, brises atlantiques qui rafraîchissent (Marrakech à 240 km est à 38°C au même moment). La Corniche d'Aïn Diab concentre la vie nocturne. <strong>De novembre à mars</strong>, comptez 9-21°C et 20-31% de pluie : c'est la saison des pluies atlantiques, souvent fortes mais courtes. Le <strong>quartier des Habous</strong> (médina récente) reste le plus accessible aux visiteurs, contrairement à l'ancienne médina plus brute. Mai-juin et septembre-octobre sont des transitions douces, idéales pour les terrasses de Maarif. La gare de Casa-Voyageurs et l'aéroport Mohammed V en font surtout une base de transit pour Marrakech, Fès ou Essaouira (TGV jusqu'à Tanger en 2h).",

    "tenerife:fr": "Tenerife, c'est la plus grande des Canaries et la plus diverse : <strong>El Teide à 3700m</strong> sépare le climat sec du sud (Costa Adeje, Los Cristianos) du climat humide du nord (Puerto de la Cruz, La Laguna). <strong>Août est mon mois préféré</strong> (9.2/10) : 21-26°C, 10% de pluie, période où la Laurisilve d'Anaga garde ses vapeurs photogéniques. <strong>De décembre à mars</strong>, prévoyez 15-21°C et 19-31% de pluie côté nord. Toujours portable, mais le sud reste presque toujours ensoleillé (différence de 200% de pluie selon le côté de l'île). Le Teide peut neiger 3-4 mois par an, parfois fermé en téléphérique pour vent. La <strong>Laguna</strong> (UNESCO) garde une vraie vie urbaine étudiante. Le carnaval de Santa Cruz en février-mars est le 2e plus grand au monde après Rio. Pic touristique et tarifs majorés. Mai-juin et septembre-octobre sont les meilleurs compromis tarif/météo.",

    "mendoza:fr": "Mendoza, c'est le pays du Malbec argentin : 1200 bodegas, vendanges tardives à 1000m d'altitude. Les Andes voisines (Aconcagua à 6960m, plus haut sommet des Amériques) règlent le climat. <strong>Novembre est mon mois préféré</strong> (9.5/10) : 16-28°C, 14% de pluie, vignobles en pleine pousse. Les vendanges (vendimia) ont lieu en mars : <strong>Fiesta Nacional de la Vendimia</strong> début mars, l'un des plus grands événements d'Argentine. <strong>De juin à août</strong> (hiver austral), le mercure descend à 4-16°C avec des nuits glaciales. C'est aussi la saison de ski à Las Leñas (3h de route, 24 km de pistes). Le ciel reste majoritairement clair (9-11% de pluie). Décembre à mars sont la haute saison touristique : températures idéales, mais aussi pluie maximale (14-23%). Le <strong>Cajón del Maipo argentin (Cordón del Plata)</strong> et la route vers Uspallata complètent le séjour. Cordoba à 600 km par bus est une autre belle escale.",

    "la-palma:fr": "La Palma, l'\"Isla Bonita\", a connu l'éruption du <strong>Cumbre Vieja en 2021</strong> qui a redessiné une partie du sud-ouest. Aujourd'hui les coulées sont accessibles guidées. <strong>Juillet est mon mois préféré</strong> (9.8/10) : 21-28°C, 1% de pluie, ciel dégagé pour le Roque de los Muchachos (2400m) et son observatoire international (l'un des meilleurs au monde, ciel certifié Starlight). <strong>Août chute curieusement à 6.9/10</strong> dans nos données : possible biais de calcul, à vérifier. Le réseau <strong>GR-130 et GR-131</strong> couvre toute l'île pour les randonneurs (4-7 jours en autonomie). <strong>De novembre à mars</strong>, prévoyez 14-23°C et 25-37% de pluie : le climat le plus humide de toutes les Canaries, surtout côté nord (Los Tilos, forêt primaire). Le sud reste plus sec, mais l'atmosphère générale est plus capricieuse qu'à Tenerife ou Gran Canaria. Île exigeante en location de voiture (routes de montagne sinueuses) mais peu touristique.",

    "faro:fr": "Faro, c'est la porte de l'Algarve : aéroport principal du sud du Portugal, mais souvent traversé sans qu'on s'arrête vraiment. La vieille ville (Vila Adentro) mérite pourtant 2-3h. <strong>Juillet est mon mois préféré</strong> (9.7/10) : 20-29°C, 1% de pluie, mer à 22°C. Toute l'Algarve devient praticable : <strong>Praia da Marinha, Benagil cave, Lagos</strong>. <strong>De décembre à mars</strong>, comptez 10-18°C et 20-32% de pluie. Toujours portable et touristiquement vide, idéal pour la <strong>Ria Formosa</strong> (lagune protégée, ornithologie d'hiver, flamants roses). C'est devenu une destination digital nomad croissante (Lagos, Tavira) avec coworkings et communauté française importante. Mai-juin et septembre-octobre sont les vrais compromis : 14-26°C, peu de pluie, foules réduites, tarifs raisonnables. Sevilla à 2h en voiture (Espagne) complète bien un séjour.",

    "san-miguel-de-allende:fr": "San Miguel de Allende, classée UNESCO, est devenue la ville mexicaine préférée des Américains expatriés (10-15% de la population). À 1900m d'altitude, climat tempéré quasi constant toute l'année. <strong>Avril est mon mois préféré</strong> (9.2/10) : 14-29°C, 10% de pluie, jacarandas en fleurs, Parroquia rose qui se découpe sur ciel bleu. <strong>De juin à septembre</strong>, c'est la saison des pluies (40-49% d'averses), souvent en fin d'après-midi, qui rafraîchissent à 14-26°C. Les centres-villes deviennent vivants en soirée après les averses. <strong>Día de los Muertos fin octobre</strong> et <strong>Día de la Independencia mi-septembre</strong> sont les deux pics culturels. Réservations 4-6 mois à l'avance. La scène art (Fábrica La Aurora), les hot springs autour de Taboada, et les food tours de la cuisine de Guanajuato sont les classiques. Guanajuato à 1h de bus complète bien le séjour. La gentrification a fait monter les prix : compter 80-150€/nuit pour un boutique-hôtel."
}

for slug, new_text in REWRITES.items():
    data[slug] = new_text

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

# Audit immédiat
import re
patterns_check = [
    ('em-dash', '—'),
    ('guillemets', r'[«»]'),
    ('attendez-vous', r'attendez-vous à'),
    ('parfait', r'\bparfait[es]*\b'),
    ('fenêtre', r'\bfenêtre[s]?\b'),
    ('saturé', r'\bsatur[eéa]\w*\b'),
    ('se mérite', r'\bse méri[tes]+\b'),
    ('magique', r'\bmagiques?\b'),
    ('Si vous X:', r'Si vous \w+ : '),
    ('iconique', r'\biconique[s]?\b'),
    ('antithèse', r'antithèse'),
]

print("=== Audit après réécriture batch 1 ===")
issues_total = 0
for slug in REWRITES.keys():
    plain = re.sub(r'<[^>]+>', '', data[slug])
    issues = []
    for label, p in patterns_check:
        n = len(re.findall(p, plain))
        if n > 0:
            issues.append(f"{label}={n}")
            issues_total += n
    flag = "OK" if not issues else "PB " + ", ".join(issues)
    print(f"  {slug:<30} {len(plain.split()):>3}m {flag}")
print(f"\nTotal issues : {issues_total}")
