"""Réécriture batch 3 — suppression patterns LLM."""
import json

PATH = 'data/avis_annuel.json'
data = json.load(open(PATH, encoding='utf-8'))

REWRITES = {
    "victoria-falls:fr": "Victoria Falls, côté zimbabwéen, offre l'accès le plus connu aux chutes : pont du Knife Edge, vue panoramique depuis Main Falls. <strong>Mai est mon mois préféré</strong> (9.4/10) : 14-27°C, 0% de pluie, période où les chutes sortent juste de leur pic et restent puissantes. <strong>D'avril à juillet</strong>, c'est la saison des hautes eaux : volume maximum (10 millions de litres/seconde), brume si dense que la vue peut être totalement obstruée certains jours. Devil's Pool fermé. <strong>D'août à octobre</strong> (basses eaux), le débit chute mais la visibilité devient maximale : c'est la période du <strong>Devil's Pool</strong> côté Livingstone (mais la majeure partie du débit est côté Zimbabwe). <strong>De novembre à mars</strong>, comptez 20-31°C et 31-68% de précipitations : chaleur humide, mais paysages reverdis. La situation économique zimbabwéenne reste compliquée : prévoir cash USD. Visa double-entry recommandé pour passer côté Zambie facilement. Hwange National Park à 2h pour les éléphants en abondance.",

    "marsa-alam:fr": "Marsa Alam est le contraire de Hurghada : station récente, calme, dédiée à la plongée sérieuse plutôt qu'à l'animation. Mer Rouge sud, récifs encore préservés. <strong>Avril est mon mois préféré</strong> (9.4/10) : 22-29°C, 0% de pluie, mer à 24°C. Les sites majeurs : <strong>Elphinstone Reef</strong> (longimanus en automne, à plongeurs confirmés), <strong>Sataya Reef</strong> et <strong>Dolphin House</strong> (banc de dauphins long-bec, snorkeling depuis bateau), <strong>Abu Dabbab</strong> (dugongs). <strong>De juin à octobre</strong>, comptez 25-36°C : la chaleur sèche reste portable au bord de mer mais éprouvante sur le bateau toute la journée. <strong>De décembre à février</strong>, prévoyez 14-23°C et un vent qui peut souffler à 40 km/h, refroidissant fortement le ressenti. Combinaison 5mm pour la plongée. Marsa Alam reste plus calme que Sharm el-Sheikh, mais les options resto et sortie hors hôtel restent limitées. Vols charters depuis Europe en haute saison.",

    "el-hierro:fr": "El Hierro est la plus reculée et la moins peuplée des Canaries : 11 000 habitants, 268 km², géoparc UNESCO, première île au monde à viser l'autosuffisance énergétique 100% renouvelable. <strong>Août est mon mois préféré</strong> (9.1/10) : 16-23°C, 3% de pluie, alizés constants. Climat doux toute l'année (10-23°C selon les saisons), peu d'écarts. <strong>De novembre à avril</strong>, comptez 10-19°C et 13-21% de pluie : toujours portable mais les nuages s'accrochent au sommet (Pico de Malpaso 1500m). La <strong>Reserva Marina de la Restinga</strong> au sud est l'un des meilleurs spots de plongée des Canaries (méros, raies pastenagues, mantas en saison). Le <strong>Sabinar</strong> (genévriers tordus par le vent) est l'image phare. Pas d'aéroport international : ferry depuis Tenerife (2h30) ou vol intérieur depuis Tenerife/La Palma. Île pour amateurs de calme absolu, randonnée et plongée. Pas pour la nightlife.",

    "maui:fr": "Maui, la \"Magic Isle\" d'Hawaï, est plus diversifiée qu'Oahu, plus accessible que Big Island. Climat tropical stable. <strong>Juillet est mon mois préféré</strong> (8.8/10) : 19-26°C, 32% de pluie en averses brèves côté ouest (Kihei et Wailea sont quasi toujours secs, Hana à l'est est gorgée d'eau). <strong>La Road to Hana</strong> (110 km, 600 virages, 56 ponts d'une voie) reste le road trip emblématique : partir tôt et compter 8h aller-retour. <strong>Haleakalā</strong> (3055m) pour le lever de soleil au-dessus des nuages (réservation NPS obligatoire). <strong>De décembre à mai</strong>, comptez 15-23°C et 38-56% de pluie : c'est la saison des baleines à bosse (sorties depuis Lahaina, novembre-mai). <strong>Lahaina a brûlé en août 2023</strong> : la ville historique reste largement détruite, à vérifier l'état actuel avant de s'y rendre. La saison touristique haute reste décembre-avril : prix x2-x3, plages qui se remplissent. Mai-juin et septembre-octobre sont les vrais bons compromis.",

    "tanger:fr": "Tanger est la porte d'entrée méditerranéenne du Maroc : ferry depuis Tarifa en 1h, ferry pour Algésiras, lien ferroviaire TGV avec Casablanca et Rabat. <strong>Juillet est mon mois préféré</strong> (9.6/10) : 20-29°C, 1% de pluie, brises atlantiques. <strong>Août chute curieusement à 6.9/10</strong> dans nos données malgré 21-30°C : pic touristique européen, ville qui déborde (les Marocains de l'étranger reviennent en masse), tarifs majorés, plages bondées. <strong>Juin et septembre</strong> sont les meilleurs mois pour la baignade dans le calme. <strong>De décembre à mars</strong>, comptez 10-18°C et 25-38% de pluie : humide et venteux, mais la kasbah et la médina prennent leur visage le plus local. Le <strong>Café Hafa</strong> (Bowles, Burroughs, Stones) garde son charme bohème. Les <strong>Grottes d'Hercule</strong> et le Cap Spartel se visitent en demi-journée. Asilah à 45 km au sud (médina blanche peinte par artistes) complète bien.",

    "hawaii:fr": "Big Island (officiellement Hawaiʻi) est la plus grande et la plus jeune de l'archipel : volcans actifs (Kilauea, Mauna Loa), 11 zones climatiques sur une seule île, observatoires sur Mauna Kea (4205m). <strong>Juillet est mon mois préféré</strong> (8.8/10) : 20-27°C, 32% de pluie côté ouest sec (Kona/Kohala), bien plus humide à Hilo à l'est (4500mm/an, l'une des villes les plus pluvieuses des USA). <strong>Volcanoes National Park</strong> reste le passage obligé : éruptions imprévisibles, le Kilauea est entré en éruption à plusieurs reprises depuis 2020. <strong>Mauna Kea</strong> au coucher du soleil (4205m, prévoir doudoune même en juillet) avec stargazing public 2 fois par semaine. <strong>De décembre à mai</strong>, comptez 15-24°C avec 38-56% de pluie côté est : saison des baleines à bosse au large. La saison touristique haute reste décembre-avril (saison sèche) : prix x2-x3. Pour la diversité (snorkel à Kealakekua, plages noires/vertes, parc national), prévoir 5-7 jours minimum.",

    "oran:fr": "Oran est la 2e ville d'Algérie, donnant sur la Méditerranée. Climat méditerranéen sec. <strong>Juin est mon mois préféré</strong> (9.9/10) : 18-28°C, 5% de pluie, brises marines régulières. <strong>Juillet-août chutent à 6.9/10</strong> à cause de la canicule sèche (21-31°C) et de l'humidité côtière qui rend la chaleur pesante. Les Oranais évacuent vers les plages d'Aïn El Turk ou Cap Falcon. <strong>De novembre à mars</strong>, comptez 8-20°C et 22-30% de pluie : humide, vent fréquent, mais la ville garde son rythme. La <strong>scène raï</strong> (Khaled, Mami) y est née : quelques cabarets historiques persistent. <strong>Santa Cruz</strong> (forteresse espagnole en surplomb) pour la vue panoramique. Le Théâtre Régional Abdelkader Alloula et la place du 1er-Novembre concentrent l'animation. Le tourisme international algérien reste limité : visa à anticiper, infrastructures hôtelières basiques. Pour les voyageurs préparés, l'expérience reste forte.",

    "maun:fr": "Maun est la base logistique du <strong>delta de l'Okavango</strong>, l'un des plus grands deltas intérieurs au monde, classé UNESCO. Aéroport international, agences pour mokoros et safaris. <strong>Mai est mon mois préféré</strong> (9.5/10) : 13-28°C, 0% de pluie, juste après les pluies où le delta est en pleine inondation. <strong>De juin à août</strong>, c'est la saison sèche fraîche (matinées 9-13°C, journées 25°C) : la grande saison des safaris. Animaux concentrés autour des points d'eau permanents, visibilité maximale. <strong>De septembre à novembre</strong>, comptez 17-36°C : la chaleur devient écrasante, les premières pluies arrivent. <strong>De décembre à mars</strong>, c'est la saison verte : 20-30°C avec 26-47% de pluie, paysages photogéniques, prix divisés par 2-3, mais certaines pistes deviennent impraticables. Mokoro (pirogue traditionnelle) reste la signature du delta. Comptez 350-800$/nuit pour un camp dans la concession. Vol intérieur Air Botswana depuis Gaborone ou vol charter direct.",

    "barcelone:fr": "Barcelone vit sa crise du surtourisme : 12 millions de visiteurs/an pour 1,6 million d'habitants, manifestations anti-touristes en 2024. La mairie a interdit les locations Airbnb en zone résidentielle d'ici 2028. <strong>Juin reste mon mois préféré</strong> (9.3/10) : 18-26°C, 19% de pluie, terrasses jusqu'à minuit, festivals (Sónar, Primavera). <strong>Juillet-août</strong> sont chauds et bondés (21-29°C, plages pleines). <strong>De décembre à mars</strong>, comptez 4-17°C et 14-27% de pluie : période paradoxalement excellente pour les classiques (Sagrada Familia, Park Güell, Barri Gòtic) sans foule, sans chaleur. La <strong>Sagrada Familia</strong> devrait achever sa tour centrale en 2026. Fin du chantier prévue plus tard pour la façade. <strong>Park Güell</strong> demande réservation obligatoire désormais. Les marchés (Boqueria, Sant Antoni) restent vivants en semaine matin. Mai et septembre-octobre sont les meilleurs compromis. Sitges à 30 minutes en train pour échapper à la cohue.",

    "alicante:fr": "Alicante est la principale porte d'entrée de la Costa Blanca : aéroport très bien connecté, plages urbaines, château San Bárbara qui domine la ville. <strong>Juin est mon mois préféré</strong> (9.7/10) : 20-27°C, 7% de pluie, mer à 22°C. <strong>Juillet-août chutent à 6.9/10</strong> à cause de la chaleur écrasante (23-30°C, ressenti 35°C+ avec l'humidité côtière) et du tourisme massif (Britanniques notamment). La plage de Postiguet déborde. <strong>De décembre à mars</strong>, prévoyez 8-17°C et 10-25% de pluie : climat doux, idéal pour visiter la ville sans foule. Les <strong>Hogueras de San Juan</strong> en juin (équivalent valencien des Fallas, mais plus modeste) restent un temps fort culturel. Bonne base pour explorer la Costa Blanca : <strong>Calpe</strong> (Peñón de Ifach), <strong>Altea</strong> (vieille ville blanche), <strong>Benidorm</strong> (skyline tropical), <strong>Tabarca</strong> (île protégée en ferry). Mai et septembre-octobre restent les meilleurs compromis touristique/météo.",

    "arusha:fr": "Arusha est la capitale du safari tanzanien : aéroport Kilimanjaro à 1h, agences pour <strong>Serengeti</strong>, <strong>Ngorongoro</strong>, <strong>Tarangire</strong>, <strong>Manyara</strong>. À 1400m d'altitude, climat tempéré africain. <strong>Septembre est mon mois préféré</strong> (8.8/10) : 14-25°C, 19% de pluie, le bon moment entre saison sèche et premières pluies. <strong>De juin à octobre</strong>, c'est la grande saison sèche : <strong>migration des gnous</strong> au Serengeti (croisement de la rivière Mara en juillet-août, pic de 1,5 million d'animaux). <strong>D'avril à mai</strong> sont les longues pluies (56-90% d'averses) : beaucoup de lodges ferment ou réduisent les tarifs (-50%), pistes parfois impraticables, mais animaux encore présents en concentrations vertes. <strong>De novembre à mai</strong>, c'est la saison verte qui suit, avec baby season (gnous nouveau-nés en février au sud du Serengeti). Comptez 200-1500$/nuit selon le type de lodge. Le <strong>marché Maasai</strong> d'Arusha pour souvenirs et tissus shukas. Mont Meru (4566m) pour acclimatation avant Kilimandjaro.",

    "sao-paulo:fr": "São Paulo, ce sont 12 millions d'habitants (22 millions avec la grande couronne), une mégapole verticale, sans plage, mais avec la scène culturelle la plus dense du Brésil. <strong>Juillet est mon mois préféré</strong> (8.7/10) : 12-23°C, 8% de pluie, climat sec et frais (hiver austral à 800m d'altitude). <strong>De décembre à mars</strong>, comptez 18-27°C et 59-78% de précipitations : orages tropicaux quasi quotidiens, parfois inondations dans le centre (Avenida 9 de Julho). La pollution s'améliore alors. <strong>Avenida Paulista</strong> le dimanche (piétonne) reste l'expérience la plus paulistana. <strong>MASP</strong> (Lina Bo Bardi) pour l'art moderne, <strong>Pinacoteca</strong>, <strong>Mercado Municipal</strong> pour le mortadelle sandwich géant. <strong>Liberdade</strong> (1ère diaspora japonaise hors Japon) le dimanche pour son marché. <strong>Beco do Batman</strong> (street art à Vila Madalena). La sécurité demande vigilance : éviter les transports publics tard, Uber abondant et bon marché. Vols depuis Europe directs (Air France, TAP, Alitalia, Lufthansa).",

    "saint-martin:fr": "Saint-Martin est l'île la plus partagée des Caraïbes : 53 km² entre Français au nord (Marigot) et Néerlandais au sud (Philipsburg/Sint Maarten), passage frontalier libre. <strong>Mars-avril sont mes mois préférés</strong> (8.4-8.6/10) : 23-28°C, 27-38% de pluie, mer à 26°C. <strong>D'août à octobre</strong>, c'est la saison cyclonique de pleine intensité : <strong>l'ouragan Irma de septembre 2017</strong> (catégorie 5) a dévasté l'île. Beaucoup de bâtiments restent en reconstruction, certaines plages ont changé de forme. <strong>De juin à novembre</strong>, comptez 24-29°C et 33-70% d'averses tropicales : soleil entre les averses, mais risque cyclonique réel à vérifier. <strong>Maho Beach</strong> reste l'image instagramée : avions A340/A380 qui passent à 20m de la plage en approche de Princess Juliana Airport. Côté français : Grand Case (gourmet), Orient Bay (plage longue, partie naturiste). Côté néerlandais : casinos, duty-free shopping, Philipsburg pour les croisiéristes.",

    "tel-aviv:fr": "Tel Aviv est l'une des villes les plus laïques et les plus 24h/24 du Moyen-Orient. <strong>White City UNESCO</strong> avec 4000 bâtiments Bauhaus des années 1930, plages urbaines, scène tech mondiale. <strong>Juin est mon mois préféré</strong> (9.6/10) : 21-29°C, 2% de pluie, mer à 23°C. <strong>De juillet à septembre</strong>, comptez 23-31°C avec une humidité pesante (le hamsin/sirocco peut faire monter à 40°C ressenti). Les Tel-Aviviens vivent en climatisation, sortent vers le bord de mer en soirée. <strong>De décembre à mars</strong>, prévoyez 10-20°C et 25-39% de pluie : humide, parfois orages, mais hivers doux. Les <strong>marchés Carmel et Levinsky</strong> pour la cuisine israélienne (sabich, hummus, sambousek). <strong>Yafo</strong> (Jaffa, vieille ville arabe) au sud pour le port et les antiquaires. <strong>Le contexte sécuritaire évolue</strong> selon les périodes : à vérifier (notamment 2023-2025). Jérusalem à 1h en train, Mer Morte à 1h30, désert du Néguev à 2h. La scène nightlife est l'une des plus actives du bassin méditerranéen.",

    "malaga:fr": "Málaga a fait sa mue depuis 2010 : ville de transit qu'on traversait pour aller vers Marbella ou Nerja, devenue une vraie destination culturelle (<strong>Picasso est né ici</strong>, Centre Pompidou Málaga, Musée Russe, Carmen Thyssen). <strong>Juin est mon mois préféré</strong> (9.8/10) : 20-28°C, 6% de pluie, mer à 22°C. <strong>Juillet-août chutent à 6.9/10</strong> à cause de la chaleur écrasante (23-31°C, intérieur ressenti 38°C+). Les locaux vont à la plage de la Malagueta tôt le matin ou en fin de journée. <strong>De décembre à mars</strong>, prévoyez 9-18°C et 16-35% de pluie : climat doux, bon pour <strong>l'Alcazaba</strong> et le Castillo de Gibralfaro sans foule. Le <strong>Caminito del Rey</strong> à 1h (réservation 3-4 mois avant) reste l'attraction nature majeure. Ronda à 1h30 pour le pont fameux. Marbella à 1h, Nerja à 1h. Mai et septembre-octobre sont les vrais bons compromis. La rénovation du quartier <strong>Soho</strong> a transformé la nightlife.",

    "barbade:fr": "La Barbade, c'est la Caraïbe britannique : conduite à gauche, cricket national, rhum (Mount Gay, fondé en 1703, plus vieille distillerie au monde). <strong>Avril reste mon mois préféré</strong> (8.6/10) : 23-28°C, 41% de pluie, mer à 27°C. La barrière corallienne extérieure (côte ouest) protège des grosses houles : <strong>Carlisle Bay</strong>, plage abritée bonne pour la baignade. La <strong>côte est</strong> (Bathsheba, Soup Bowl) garde l'Atlantique sauvage : surf de classe mondiale, baignade dangereuse. <strong>D'août à octobre</strong>, c'est la saison cyclonique avec 70-77% de précipitations : risque de tempêtes tropicales, mais hors trajectoire principale (la Barbade est protégée par sa position à l'est de l'arc caribéen). <strong>Bridgetown</strong> est UNESCO pour son centre historique colonial (synagogue Nidhe Israel de 1654, l'une des plus vieilles d'Amérique). <strong>De décembre à mars</strong> reste la haute saison américaine et britannique : prix x2-x3. Mai-juin et novembre sont d'excellents compromis foule/météo/prix.",

    "gozo:fr": "Gozo est la sœur rurale de Malte : 67 km², 30 000 habitants, ferry de 25 minutes depuis Cirkewwa. Pas d'aéroport. Atmosphère plus apaisée, plus locale. <strong>Juillet est mon mois préféré</strong> (9.7/10) : 24-26°C, 0% de pluie, mer à 25°C. <strong>L'Azure Window</strong>, l'arche signature, s'est effondrée en 2017 lors d'une tempête : ne plus la chercher dans les guides. La <strong>Citadella de Victoria</strong> (citadelle médiévale) reste la pièce maîtresse, vues sur toute l'île. Plages : <strong>Ramla Bay</strong> (sable rouge), <strong>San Blas</strong> (accessible par sentier). Plongée sur le <strong>Blue Hole de Dwejra</strong> (effondré aussi mais restant beau) et l'épave HMS Trusty. <strong>Août chute à 6.9/10</strong> à cause de la canicule (25-26°C ressenti 35°C+). <strong>De novembre à mars</strong>, prévoyez 13-20°C et 23-39% de pluie : humide et venteux, beaucoup de tavernes ferment, mais les balades sur falaises (Ta' Cenc) restent superbes. 2-3 jours suffisent en complément de Malte.",

    "lake-tahoe:fr": "Lake Tahoe, c'est le plus grand lac alpin d'Amérique du Nord (à 1900m d'altitude, profondeur 500m, eau cristalline). 2 saisons distinctes : <strong>ski d'hiver</strong> (Heavenly, Squaw Valley/Palisades, Northstar, Kirkwood, l'un des plus grands domaines skiables d'Amérique du Nord) et <strong>été paddleboard et randonnée</strong>. <strong>Juillet est mon mois préféré</strong> (9.5/10) : 15-27°C, 7% de pluie, lac à 18-20°C (frais mais accessible). <strong>De décembre à mars</strong>, comptez -3/5°C avec 32-39% de précipitations (souvent neige) : c'est la haute saison ski avec parfois des chutes de neige record (Sierra Nevada peut prendre 5-10m sur un hiver). Les routes peuvent être fermées en cas de tempête. <strong>D'avril à mai</strong>, c'est la transition difficile : ski qui se finit, été qui n'a pas commencé, beaucoup de restos en intersaison. South Lake Tahoe (côté Nevada) pour les casinos, North Lake (côté Californie) pour le calme. Tahoe Rim Trail (165 miles) pour les randonneurs.",

    "mammoth-mountain:fr": "Mammoth Mountain, c'est la station de ski de référence de la Sierra Nevada californienne : 3370m de sommet, saison parmi les plus longues d'Amérique du Nord (parfois novembre à juillet sur les bonnes années). <strong>Juillet est mon mois préféré</strong> (9.4/10) : 10-25°C, 9% de pluie, ciel dégagé pour les randonnées vers <strong>Devils Postpile</strong>, Rainbow Falls, <strong>Convict Lake</strong>. <strong>De décembre à mars</strong>, comptez -9/2°C avec 30-36% de précipitations (souvent en grosses tempêtes) : c'est la saison de ski. La station appartient au domaine Ikon Pass. <strong>De juin à septembre</strong>, c'est la saison été : VTT (Mammoth Bike Park), pêche à la truite (Crowley Lake), accès à <strong>Mono Lake</strong> et au <strong>Yosemite par Tioga Pass</strong> (route fermée d'octobre à mai-juin selon enneigement). <strong>D'avril à mai</strong>, c'est la transition : ski en altitude possible, mais routes basses désertées. Vol depuis LA-Mammoth Yosemite Airport (saisonnier) ou route 5h depuis Los Angeles.",

    "bariloche:fr": "Bariloche, c'est la \"petite Suisse argentine\" : Patagonie nord, lacs et forêts d'araucaria, architecture chalets. <strong>Janvier est mon mois préféré</strong> (9.3/10) : 10-24°C, 11% de pluie, journées de 14h, été austral idéal pour le <strong>Circuito Chico</strong> (route panoramique de 65 km), <strong>Cerro Catedral</strong> (lift d'été, vue sur Nahuel Huapi), <strong>Refugio Frey</strong> (rando vers le lac glaciaire). <strong>De juin à août</strong> (hiver austral), c'est la saison de ski sur le <strong>Cerro Catedral</strong> (la plus grande station d'Amérique du Sud, 120 km de pistes) : températures à 1-6°C en bas, neige garantie de juillet à mi-septembre. <strong>D'avril à novembre</strong>, comptez 1-14°C et 26-53% de pluie : climat humide patagonien, mais les forêts en couleurs d'automne (mai) restent photogéniques. <strong>Bariloche est célèbre pour son chocolat</strong> : Calle Mitre concentre les chocolatiers (Mamuschka, Rapanui, Fenoglio). El Bolsón à 2h pour les hippies argentins. Cerro Tronador (volcan en activité) pour rando d'une journée.",

    "dolomites:fr": "Les Dolomites (UNESCO 2009), c'est le calcaire pâle des Alpes orientales italiennes : refuges en altitude, via ferrate connues. <strong>Juillet-août sont mes mois préférés</strong> (4.8/10, note climat trompeuse car nos données reflètent les zones d'altitude où l'été reste frais 12°C). En vallée (Bolzano, Cortina, Selva di Val Gardena), prévoir 18-25°C en plein été. <strong>De juin à septembre</strong>, c'est la saison rando et via ferrata : <strong>Tre Cime di Lavaredo</strong> (boucle de 9 km, classique), <strong>Lagazuoi</strong> (téléphérique + tunnels guerre), <strong>Seceda</strong> (panorama célèbre). Les refuges du CAI ouvrent juin à septembre, réservation obligatoire en haute saison. <strong>De décembre à avril</strong>, c'est la saison de ski : <strong>Sella Ronda</strong> (boucle 26 km à ski autour du massif Sella, 4 vallées), Cortina d'Ampezzo (Olympiques 2026), Val Gardena (Coupe du monde). <strong>Mai et octobre-novembre sont des intersaisons</strong> : refuges fermés, remontées arrêtées, météo capricieuse. À éviter sauf objectif spécifique. Accès depuis Venise (2h30) ou Innsbruck (1h30).",

    "montgenevre:fr": "Montgenèvre, station de ski franco-italienne au col du Montgenèvre (1860m), donne accès au domaine de la <strong>Voie Lactée</strong> : 400 km de pistes en liaison avec Sestrière, Sansicario et Claviere côté italien. <strong>Juillet est mon mois préféré</strong> (8.9/10) : 9-22°C, 19% de pluie, bon pour rando, VTT, golf. La station fait partie du Briançonnais : <strong>Briançon</strong> (UNESCO Vauban, plus haute ville d'Europe à 1326m) à 12 km. <strong>De décembre à mars</strong>, comptez -10/3°C : c'est la saison ski, neige fiable grâce à l'altitude et orientation nord, possibilité de skier en France et déjeuner en Italie. <strong>D'octobre à novembre et avril-mai</strong>, c'est l'intersaison : station semi-fermée, peu de services. Climat plutôt continental sec (moins de neige fraîche que le Nord des Alpes, mais conditions plus stables). Accès depuis Turin (1h30), Briançon (15 min), Grenoble (3h). Plus accessible que Serre-Chevalier voisine, idéale pour familles et débutants. Oulx en gare TGV Italo (45 min) pour ceux qui viennent de Paris-Lyon.",

    "park-city:fr": "Park City, Utah, c'est l'ex-ville minière reconvertie en station de ski premium, à 35 minutes de Salt Lake City. <strong>Juillet est mon mois préféré</strong> (9.8/10) : 12-28°C, 12% de pluie, climat sec d'altitude (2100m), ciel constamment bleu. Idéal randonnées et VTT (50+ pistes au Park City Mountain Bike Park). <strong>De décembre à mars</strong>, comptez -11/4°C : c'est la saison ski. <strong>\"The Greatest Snow on Earth\"</strong> est le slogan officiel de l'Utah : la neige y est sèche et légère (\"champagne powder\") grâce au climat continental sec et à l'effet du Grand Lac Salé. Park City Mountain (le plus grand domaine US, 7300 acres) + Deer Valley (ski only, no snowboard) + Canyons forment un trio remarquable. <strong>Sundance Film Festival</strong> chaque janvier (ex-Robert Redford) remplit la ville pendant 10 jours : prix x3-x4, réservations 1 an à l'avance. <strong>D'avril à mai et octobre-novembre</strong>, c'est l'intersaison : ski qui ferme, VTT pas encore ouvert. Vols directs depuis Europe via Salt Lake City.",

    "aspen:fr": "Aspen, c'est la station de ski la plus chic des États-Unis : Colorado, jet-set, prix démentiels (200-2000$/nuit), 4 montagnes (Aspen Mountain, Snowmass, Buttermilk, Highlands). <strong>Juillet est mon mois préféré</strong> (9.2/10) : 8-26°C, 25% de pluie, le bon moment pour le festival <strong>Aspen Music Festival</strong> (2 mois d'opéra et classique) et la randonnée vers les <strong>Maroon Bells</strong> (les pics les plus photographiés du Colorado). <strong>De décembre à mars</strong>, comptez -13/2°C : saison ski culte. <strong>X Games d'hiver</strong> à Buttermilk fin janvier (gratuit, mais foule monstre). Aspen Highlands abrite Highland Bowl, l'un des plus difficiles bowls hike-to-ski d'Amérique du Nord. <strong>D'avril à mai et novembre</strong>, c'est l'intersaison : tout se ferme, ville fantôme. La <strong>scène culinaire</strong> rivalise avec NY/SF (Element 47, Matsuhisa). John Denver vivait ici. Vol direct Aspen-Pitkin Airport mais turbulent l'hiver. Alternative Denver (4h de route via Independence Pass, fermé novembre-mai).",

    "cervinia:fr": "Cervinia (Breuil-Cervinia), c'est la face italienne du Cervin (Matterhorn), station à 2050m d'altitude au pied du sommet. Liaison ski avec <strong>Zermatt</strong> en Suisse via le Plateau Rosa (3500m), l'un des rares domaines skiables internationaux. <strong>Juillet est mon mois préféré</strong> (7.6/10, climat alpin frais constant) : 8-17°C, 40% de pluie en orages d'après-midi, le bon moment pour le <strong>Lago Blu</strong> (lac qui reflète le Matterhorn) et la rando vers le <strong>Plan Maison</strong>. <strong>De décembre à avril</strong>, c'est la grande saison ski : neige fiable grâce à l'altitude (la plupart des pistes au-dessus de 2000m), <strong>ski d'été sur le glacier du Plateau Rosa</strong> jusqu'à fin août certaines années. <strong>De mai-juin et octobre-novembre</strong>, c'est l'intersaison : ski d'été vs randonnée pas encore au point. Cervinia est l'opposé chic de Courmayeur ou Cortina : station construite pour le ski, peu d'âme de village italien. Aoste à 1h en voiture, Turin à 2h.",

    "sun-valley:fr": "Sun Valley, Idaho, c'est <strong>la plus ancienne station de ski d'Amérique du Nord</strong> (1936), créée par Averell Harriman pour son chemin de fer Union Pacific. Station historique qui a inventé le télésiège (\"chairlift\"). <strong>Juillet est mon mois préféré</strong> (9.9/10) : 10-28°C, 10% de pluie, ciel sec (climat semi-aride d'altitude, 1750m). Idéal randonnées dans les <strong>Sawtooth Mountains</strong> et baignade dans les <strong>hot springs</strong> naturels (Goldbug, Boat Box, Russian John). <strong>De décembre à mars</strong>, comptez -11/0°C : saison ski sur Bald Mountain (Baldy, 1052m de dénivelé) et Dollar Mountain (débutants). Neige sèche d'altitude, foules limitées vs Aspen ou Park City. <strong>D'avril à mai et octobre-novembre</strong>, c'est l'intersaison : station semi-fermée. Ketchum, le village voisin (Hemingway y est mort), garde un charme rustique-chic. <strong>Ernest Hemingway</strong> y est enterré au cimetière de Ketchum. Vol direct Sun Valley Airport (Hailey) ou Boise à 2h30 de route.",

    "almaty:fr": "Almaty est l'ancienne capitale du Kazakhstan (jusqu'en 1997, remplacée par Astana/Nur-Sultan), mais reste la capitale économique et culturelle. À 800m d'altitude au pied des <strong>Tian Shan</strong>. Climat continental marqué. <strong>Août est mon mois préféré</strong> (9.4/10) : 17-28°C, 14% de pluie, le bon moment pour <strong>Big Almaty Lake</strong> (3300m, accessible en taxi 1h), Charyn Canyon (\"le Grand Canyon kazakh\" à 3h de route), et la <strong>Medeo Skating Rink</strong> + Chymbulak Ski Resort accessibles en téléphérique depuis le centre. <strong>De décembre à février</strong>, comptez -8/-1°C avec 18-24% de précipitations (souvent neige) : c'est la saison ski à Chymbulak (3200m), petite station mais accessible facilement. <strong>De mars à avril et octobre-novembre</strong>, c'est l'intersaison capricieuse : 0-17°C, fonte des neiges, beaucoup de pluie. Le <strong>marché vert (Zelyony Bazaar)</strong>, la cathédrale orthodoxe Zenkov (l'une des plus hautes constructions en bois au monde), et le quartier de <strong>Panfilov Park</strong> concentrent les visites. Vol direct depuis Istanbul, Frankfurt, Dubai, ou via Moscou."
}

for slug, new_text in REWRITES.items():
    data[slug] = new_text

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

import re
patterns_check = [
    ('em-dash', '—'),
    ('guillemets', r'[«»]'),
    ('attendez-vous', r'attendez-vous à'),
    ('parfait', r'\bparfait[es]*\b'),
    ('fenêtre', r'\bfenêtre[s]?\b'),
    ('saturé', r'\bsatur[eéa]\w*\b'),
    ('se mérite', r'\bse méri[tes]+\b'),
    ('magique', r'\bmagiques?\b'),
    ('Si vous X:', r'Si vous \w+ : '),
    ('iconique', r'\biconique[s]?\b'),
    ('antithèse', r'antithèse'),
    ('emblématique', r'\bemblématique[s]?\b'),
    ('mythique', r'\bmythique[s]?\b'),
    ('authentique', r'\bauthentique[s]?\b'),
    ('féérique', r'\bféérique[s]?\b'),
]

print("=== Audit batch 3 nettoyé ===")
issues_total = 0
for slug in REWRITES.keys():
    plain = re.sub(r'<[^>]+>', '', data[slug])
    issues = []
    for label, p in patterns_check:
        n = len(re.findall(p, plain))
        if n > 0:
            issues.append(f"{label}={n}")
            issues_total += n
    flag = "OK" if not issues else "PB " + ", ".join(issues)
    print(f"  {slug:<28} {len(plain.split()):>3}m {flag}")
print(f"\nTotal issues : {issues_total}")
